### ISSUE TITLE
Rounding issue when entering the timing point menu in editor

### ISSUE THREAD

**Issue by percyqaz** [ppy/osu-stable-issues#1]
Often when pressing F6 to enter the timing point management window when there are lots of slider velocity changes in a small time span, the highlighted green line when the window opens is not the point the cursor is on.

Illustration:
https://cdn.discordapp.com/attachments/441741591430955009/624212239104344064/unknown.png
Note how the editor cursor is at 00:29:633
See also at the timeline at the top, the cursor is on one green line and there is another shortly after it (at 00:29:670)
https://cdn.discordapp.com/attachments/441741591430955009/624212285195550720/unknown.png
Note how the lightlighted (in grey) timing point is the one at 00:29:670, not 00:29:633

Should be a quick fix (maybe hack it by pretending the cursor is 2ms earlier when calculating, since green lines won't be THAT close)
Would be much appreciated as it is confusing/irritating when working with lots of green lines :)

**Comment by smoogipoo** [comment]
I can't replicate this one. Provide the beatmap perhaps?

**Comment by percyqaz** [comment]
Here is the beatmap in question
https://osu.ppy.sh/beatmapsets/759144#mania/1596647

**Comment by smoogipoo** [comment]
Does it always occur? I still can't replicate it with that beatmap... Stable already has a +5ms offset.

**Comment by percyqaz** [comment]
Yes this always occurs, whether I scroll to the green line from before it or after it in the timeline. The window will always snap to the green line immediately after it if there is one within a certain distance

After some experimenting, this occurs when the second green line is 50ms (exact) or less after the first one. If they are spaced 51ms apart this doesn't occur.

**Comment by smoogipoo** [comment]
Ah I see, this occurs when you use F6 specifically and you're not in the timing page. Thanks,

**Comment by peppy** [comment]
Fixed in next Cutting Edge build.
