### ISSUE TITLE
Multiplayer - this one "white clouds" aren't mirrored on the left side

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu-stable-issues#100]
**Issue from multiplayer only**
This one "white clouds" aren't mirrored on the left side. I try take a screenshot on ingame, is hard to timing take a one screenshot. I put on the youtube liveplay and take this a one screenshot:

![ss (2019-09-24 at 08 55 40)](https://user-images.githubusercontent.com/53025167/65541624-ffc23f80-df0d-11e9-837f-33de44e13a4d.jpg)

Right side worked normal, but left side are weird.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge build.
