### ISSUE TITLE
Maps not showing up (Even after following all known solutions besides un/reinstall)

### ISSUE THREAD

**Issue by djmax34** [ppy/osu-stable-issues#1001]
The game allows me to change my beatmap by going to the main menu and changing the song, but I cannot choose the star rating. All of my maps are downloaded and have been processed, and I have renamed the osu!.db file still with no fix. 

![image](https://user-images.githubusercontent.com/81657087/175795545-a5c60b60-dc9b-4cc6-83d4-e4c13cd2f2f2.png)
![image](https://user-images.githubusercontent.com/81657087/175795548-80bc1baf-d455-4b90-ae84-fdc7c68fc06e.png)
![image](https://user-images.githubusercontent.com/81657087/175795552-a33c11ed-cc0e-4a27-863c-032fe09d4191.png)
![image](https://user-images.githubusercontent.com/81657087/175795577-2dccca03-9bc8-4bf6-82cf-0fd8fa6a5a86.png)

**Comment by peppy** [comment]
missing any actionable information, but your songs folder is probably corrupt. move apl songs out then move some back until you find the corrupt beatmap

**Comment by djmax34** [comment]
Oh wow... Thanks... you are correct... Pretty dumb for not checking this myself. 
![image](https://user-images.githubusercontent.com/81657087/175824054-953aaedb-14fb-42d9-9818-8813a7956113.png)

**Comment by djmax34** [comment]
uhhhh actually I removed every beatmap from my songs folder and it still is not working even after importing new beginnings... 
At this point I will just un/reinstall osu and see if that works
![image](https://user-images.githubusercontent.com/81657087/175824972-fbffcc33-b982-4e2c-90f4-1e837bfe980f.png)
![image](https://user-images.githubusercontent.com/81657087/175825091-59f4200a-6749-4fc9-9c37-4b99e581eb79.png)

**Comment by smoogipoo** [comment]
You have the collections grouping selected in the top right, is that intended? Can you try a different grouping?

**Comment by djmax34** [comment]
> You have the collections grouping selected in the top right, is that intended? Can you try a different grouping?

:v That was the issue.......... well uhhhh.... thanks...... i-
