### ISSUE TITLE
bug ?

### ISSUE THREAD

**Issue by cloudirus** [ppy/osu-stable-issues#1002]
![screenshot388](https://user-images.githubusercontent.com/94827711/176114560-388b8485-fb69-41f1-9485-1a21c36e54db.jpg)

**Comment by smoogipoo** [comment]
Do you have the score completed on another game mode?

**Comment by cloudirus** [comment]
no

**Comment by peppy** [comment]
Did you (or someone else) login on a different account?

**Comment by cloudirus** [comment]
oh i found it, someone used another account and did that score
