### ISSUE TITLE
High mouse reports will increase latency and lower FPS significantly

### ISSUE THREAD

**Issue by Rothes** [ppy/osu-stable-issues#1006]
Mouse polling rate: 500/1000Hz. 500Hz is kinda random to reproduce, 125Hz is ok.
Windows 11 (25145.1011)

Lazer will also increase latency significantly, but doesn't cause lag.
![screenshot084](https://user-images.githubusercontent.com/47097395/177009872-5e46e8d5-a589-4367-9b50-2bd88388952b.png)

**Comment by peppy** [comment]
This happens when something on your system is processing the mouse badly. Please close all otehr applications and drivers. It's not something at our end.

**Comment by Rothes** [comment]
> This happens when something on your system is processing the mouse badly. Please close all otehr applications and drivers. It's not something at our end.

Right, caused by Discord overlap. Thanks for support.
