### ISSUE TITLE
Question.   Why isn't osu!stable playable in the browser?

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [ppy/osu-stable-issues#1007]
I recently found this project on scratch, and it looks like an almost full version of osu! 
https://scratch.mit.edu/projects/613688710
Sorry for asking, but the current browser version of osu! Sucks tbh.

**Comment by peppy** [comment]
Browsers come with limitations and aren’t our style. Please see https://github.com/ppy/osu#running-osu which supports all platforms without using a browser.
