### ISSUE TITLE
osu closes when pessing alt tab

### ISSUE THREAD

**Issue by StevenSihhv** [ppy/osu-stable-issues#1010]
is there a way to fix osu closing when pressing alt tab or when you open other things on ur pc?

**Comment by peppy** [comment]
Can you try switching to cutting edge and see if the behaviour is better?

**Comment by StevenSihhv** [comment]
> Can you try switching to cutting edge and see if the behaviour is better?

yes it helped, thanks

**Comment by peppy** [comment]
Great to hear, tentatively closing this. I'm not 100% sure whether the new behaviour will stay, or whether we'll resort to it being a toggle, but in some way it will likely make its way to stable soon.
