### ISSUE TITLE
Cutting Edge will show the supporter message even while logged out

### ISSUE THREAD

**Issue by tgpholly** [ppy/osu-stable-issues#1012]
Clicking on Multi while logged out will still show the supporter required message as opposed to the must be conencted to osu!Bancho message which seems a bit weird to be doing.

![screenshot447](https://user-images.githubusercontent.com/37120476/180666748-502983fa-bb91-4b8a-804d-83e8716c3d30.png)

**Comment by smoogipoo** [comment]
I don't think time needs to be spend addressing this issue.
