### ISSUE TITLE
Offset Wizard has no green bars for timing

### ISSUE THREAD

**Issue by StayBlue** [ppy/osu-stable-issues#1014]
I have no idea what the correct terminology is for it, but my friend is experiencing an issue where he doesn't see any bars on the offset wizard even though the song is playing. He's running on Stable.

Image demonstrating the issue:
![image](https://user-images.githubusercontent.com/23127866/181696768-64b88205-2143-4fb8-839e-371c25346173.png)

**Comment by peppy** [comment]
Please make sure a beatmap is playing which has timing data.

**Comment by peppy** [comment]
Also change the skin if the user is using something weird. Seek further help at https://osu.ppy.sh/community/forums/5 if required.

**Comment by StayBlue** [comment]
He has both the default skin, and he is also using a ranked map. Thanks anyway!
