### ISSUE TITLE
"Your version of osu! is too old to submit scores"

### ISSUE THREAD

**Issue by BrightOS** [ppy/osu-stable-issues#1017]
Since yesterday, after each successful bitmap pass, I get the error "ERROR: Your version of osu! is too old to submit scores! Please run the updater.". At startup, there are no notifications about the existence of a new version. By clicking on the update search button, an inscription appears that there are no new updates.

Tried the following versions: Stable 20220424, Beta 20220421 and Cutting Edge 20220713. Identical error everywhere. Through third-party services using the official "osu! API" it is possible to get only information about scores with failings, successful passes are not displayed there either. I tried to make an attempt on my second device - the same result. However, this problem does not occur in Lazer 2022.731.1.

I tried to run the installer from the site without deleting the old version, as described in "ppy/osu-stable-issues#989" - it didn't help.

[network.log](https://github.com/ppy/osu-stable-issues/files/9254278/network.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/9254280/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/9254281/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/9254282/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/9254283/update_success.log)

**Comment by peppy** [comment]
Do you happen to have "test mode" enabled? If so, please try turning it off.

**Comment by BrightOS** [comment]
Yes, it helped, thank you very much!
