### ISSUE TITLE
Romanian translation of very poor quality

### ISSUE THREAD

**Issue by NiceAesth** [ppy/osu-stable-issues#1019]
The current Romanian translation has a multitude of errors and is outdated. I have updated the translation to match the new lazer translations and corrected the errors. You may look at the changes in the revisions tab, if necessary.

https://gist.github.com/NiceAesth/eea5630fa03038fb06bc83274626dc6c

PS: I have noticed a typo with "Options_TabSkin_UpsiedDown"

Edit: the translation is finished and proofread by other native speakers, no further updates will be made by us unless requested, it is safe to add.

**Comment by NiceAesth** [comment]
Also, the "Render at native resolution" text seems to not be localizable

**Comment by smoogipoo** [comment]
Had a look through some of the strings and they look fine.

**Comment by peppy** [comment]
The file seems truncated at the start. @NiceAesth could you please check on that?

No guarantees I'll get this live, I don't even know if this update process still works.

**Comment by NiceAesth** [comment]
Oh, my bad, I hadn't noticed. Will fix now

**Comment by NiceAesth** [comment]
Fixed

**Comment by peppy** [comment]
Will close this for now, have merged into the code base. Will look to hopefully deploy soon.
