### ISSUE TITLE
Tag coop scoreboard

### ISSUE THREAD

**Issue by Inversu** [ppy/osu-stable-issues#102]
When playing tag coop with my friends, I noticed that the scoreboard is automatically enabled every time a map begins. In normal multiplayer, the scoreboard stays disabled ingame after pressing tab once (until closing the game). I find it distracting, and it would be nice to not have to disable it at the start of every map.

**Comment by peppy** [comment]
This is by-design, because without this displayed it's basically impossible to know how the other players are doing.

We will consider making this more subtle in lazer so it is not distracting to keep it visible.
