### ISSUE TITLE
Error: Your versions is too old to submit scores

### ISSUE THREAD

**Issue by roxandtol** [ppy/osu-stable-issues#1020]
Hi, I'm having the same issue as this (#1017) issue, I've tried doing a fresh install, keeping some of my data (Songs, skins and the `data` folder),  But I still get the error. I also tried switching between the beta and Cutting edge, but nothing. Before I reinstalled, I also tried going to fallback and then stable, and that temporarily fixed it, but only for 5 mins
Logs:
[runtime.log](https://github.com/ppy/osu-stable-issues/files/9274236/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/9274237/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/9274238/update_success.log)

**Comment by peppy** [comment]
What version of windows are you using? Do you have test mode or some other dodge enabled?

**Comment by roxandtol** [comment]
> What version of windows are you using? Do you have test mode or some other dodge enabled?

I'm having the issue with WINE set to Windows 10, and I'm not sure how to check if I have test mode on

**Comment by peppy** [comment]
Please make sure to not have wine fake its OS. Look at a common setup guide for wine to make sure you're running it correctly.

Our general test environment is Wine 6.2 set to Windows 10, without any custom settings.

**Comment by roxandtol** [comment]
Reinstalling the prefix did the trick, fixed now
