### ISSUE TITLE
Game is overall laggy and slow

### ISSUE THREAD

**Issue by DaGDNoob** [ppy/osu-stable-issues#1021]
Opening F9 menu freezes game for a little bit
Song selection takes a while to load
Typing any search query freezes the game for a long time
Gameplay is unaffected

https://user-images.githubusercontent.com/29365478/184791220-71876a8d-41b5-412b-a493-ae4e3eed501e.mp4

[session.log](https://github.com/ppy/osu-stable-issues/files/9347698/session.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/9347699/runtime.log)
[osu!auth.log](https://github.com/ppy/osu-stable-issues/files/9347702/osu.auth.log)

**Comment by smoogipoo** [comment]
Change to the cutting edge release stream, reproduce the issue, and post the `performance.log` file.

**Comment by DaGDNoob** [comment]
[performance.log](https://github.com/ppy/osu-stable-issues/files/9347713/performance.log)

**Comment by peppy** [comment]
Based on that log file, your system is likely not in a good state. It's hitching on calls which shouldn't hitch, suggesting that there might be something else running on your system using your resources.

- Try going through https://osu.ppy.sh/help/wiki/Performance_Troubleshooting 
- Try restarting your PC
- Make sure nothing is running externally, no overlays like discord, etc
- Try switching to default skin

If it still happens, please open osu!, wait about 5 minutes then try reproducing a second time. If you can reproduce, please cause some more lag spikes to occur (maybe 10 or more) then attach another performance.log. I don't know I'll be able to give you any further advice, but if you first try all the above and isolate the issue further I may be able to give you some insights.

**Comment by smoogipoo** [comment]
Also please reproduce it outside of song select, since we're getting some noise from there in the logs. Or let us know if it _only_ happens in song select.

**Comment by DaGDNoob** [comment]
Creating new wineprefix fixed the issue, but just in case I played on old wineprefix for a while

[performance.log](https://github.com/ppy/osu-stable-issues/files/9347973/performance.log)

https://user-images.githubusercontent.com/29365478/184801499-66302089-380c-4679-a026-28f839727b52.mp4

Clicking on other tabs made the game unusable but when click player lag goes away

**Comment by peppy** [comment]
PLEASE state from the outset that you are running under wine, and include your FULL wine installation as a zip in the future. It wastes both our time if you report liek this.
