### ISSUE TITLE
crash on startup after importing a map

### ISSUE THREAD

**Issue by minisbett** [ppy/osu-stable-issues#1023]
I imported an osu! map from a friend I'm not allowed to share publicly (unless it's really needed here) but it caused my osu! client to be stuck at crashing on startup. The error first occured when starting osu! through opening the .osz file but now continues to happen even when I'm starting plain osu!. Currently running on latest cuttingedge. I'd try to switch the branch but I don't exactly know if this is possible just by changing the release stream in some config files.
The crash window leaves me with this obfuscated stacktrace:
```
#=zyxfDeTBsrfcrGQg14UmRcoTJ3N4e: Unknown extension controller found: ff00a4200000
   at #=z$cgjOzE09O3WgAz8NHk0o0xdP71W.#=z64nDNvI$RC0I()
   at #=z$cgjOzE09O3WgAz8NHk0o0xdP71W.#=zhTjBqdmMHoub(Byte[] #=z8lNl38FiLa04)
   at #=z$cgjOzE09O3WgAz8NHk0o0xdP71W.#=zpudAxQw=(IAsyncResult #=z1Qfybk8=)
   at System.IO.FileStreamAsyncResult.AsyncFSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by minisbett** [comment]
![image](https://user-images.githubusercontent.com/39670899/184971676-9579e6f2-f6eb-4cce-85c2-e235caa6150f.png)
osu! starts up until this point

**Comment by minisbett** [comment]
I already tried to delete the imported the map from the songs folder without success.

**Comment by minisbett** [comment]
I switched to stable using the configurator but it didn't fix the issue

**Comment by peppy** [comment]
Are you importing from a network drive or similar? It looks like an external error.

**Comment by minisbett** [comment]
I didn't, I imported it from Edge's download cache which it is doing when you run the while directly instead of saving it somewhere. But today I tried launching osu again and it magically disappeared, really weird. Can't be sure if switching to stable did anything but let's hope this was a one time edge case that won't affect other users.
