### ISSUE TITLE
Allow Spectator Hide/Blocking

### ISSUE THREAD

**Issue by ReiFan49** [ppy/osu-stable-issues#1024]
I would like to see users are blocked from spectating certain user if they block them.

Something like their name is hidden from spectator chat and list by using Ignore list option `@s` parameter. Or, utilizing the website block feature to prevent them interacting to respective user's spectator.

Some people may feel uneasy if the person they block is shown to spectating them while they can't see the message, so spec blocking or spec hiding would do the solution.

**Comment by peppy** [comment]
Should work in the next release.
