### ISSUE TITLE
Devserver option make a http request with wrong port

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-stable-issues#1025]
I'm making a custom server for my friends, and i can't connect cuz the client make a HTTP request using port 443 (HTTPS port). This only happens for devserver. 

# osu!Bancho requests 
You can see the HTTPS
![image](https://user-images.githubusercontent.com/62405013/185806690-d0c79d96-fccb-4b19-94a7-48a0d01616b5.png)

# Devserver requests
The client is making HTTP requests using HTTPS port
![image](https://user-images.githubusercontent.com/62405013/185806728-0ab83648-494c-4717-9ba0-5c5735abb9c6.png)

A soultion for this is make a https request instead http

**Comment by peppy** [comment]
This sounds like an issue with your server setup. It definitely isn't what osu! is doing. I've double-check to make sure.

Sorry but we can't provide further help.
