### ISSUE TITLE
Error: Your versions is too old to submit scores

### ISSUE THREAD

**Issue by quayosu1992** [ppy/osu-stable-issues#1026]
i got this today,i tried redownload,change release stream and run updater but still not work

**Comment by peppy** [comment]
Could you please switch to the latest cutting edge release and see if things work better for you?

**Comment by quayosu1992** [comment]
no,it not work

**Comment by peppy** [comment]
At very least you should see a different message. Can you confirm what you're seeing, and confirm the version of cutting edge you are running?

**Comment by quayosu1992** [comment]
it work now thanks
