### ISSUE TITLE
skin whose name contains leading spaces not found after restarting

### ISSUE THREAD

**Issue by daifkyou** [ppy/osu-stable-issues#1027]
when i use a skin whose folder name starts with spaces, it initially works, but when restarting the game the skin is not found and the default skin is used instead.
the leading spaces are still present in the user .cfg when opened in a text editor.
just in case, i'm running osu b20220424 with wine staging 7.15 on arch with linux zen 5.19.3 and my skin is symlinked to the skins folder.

**Comment by smoogipoo** [comment]
Dunno. Very rare occurrence that is potentially related to your system. Rename the skin.
