### ISSUE TITLE
AiMod Background image should be max of 2560 x 1440 and check if size is above 2.5mb.

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-stable-issues#103]
As what title says, when opening the AiMod with a background higher than 1366x768, it pops up with "Background image is larger than 1366x768", even though the latest ranking criteria state 
`Background images must not exceed a width of 2560 pixels, a height of 1440 pixels, and a filesize of 2.5MB. Images with lower vertical or horizontal resolutions than that of the player's will be upscaled to fit the entire screen.`
I'm sure the first issue can be fixed but the second issue can be implemented into lazer.
Hope this helps!

**Comment by MillhioreF** [comment]
Updated in next cuttingedge.
