### ISSUE TITLE
Osu frame drop when using huion devices

### ISSUE THREAD

**Issue by futag** [ppy/osu-stable-issues#1030]
When i moving cursor using Huion h340p tablet, fps osu drop instantly

**Comment by smoogipoo** [comment]
There is not enough info in this issue for anything. Please provide a video and logs.

**Comment by peppy** [comment]
You may also want to go through our self-help guide https://osu.ppy.sh/help/wiki/Performance_Troubleshooting

**Comment by futag** [comment]
@smoogipoo
[runtime.log](https://github.com/ppy/osu-stable-issues/files/9475085/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/9475086/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/9475087/update_success.log)
[osu!auth.log](https://github.com/ppy/osu-stable-issues/files/9475088/osu.auth.log)
