### ISSUE TITLE
My osu frame drop when using pentab

### ISSUE THREAD

**Issue by futag** [ppy/osu-stable-issues#1031]
When cursor move with huion h430p + official driver, osu in my computer frame drop. Not effected in my mouse

https://user-images.githubusercontent.com/21020026/188245254-a32d36af-b749-4c31-a448-7a8f78d7d7ce.mp4

Logs:
[update_success.log](https://github.com/ppy/osu-stable-issues/files/9481452/update_success.log)
[osu!auth.log](https://github.com/ppy/osu-stable-issues/files/9481454/osu.auth.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/9481456/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/9481451/session.log)

**Comment by peppy** [comment]
This is going to be an issue with the driver or something else on your pc.

https://osu.ppy.sh/help/wiki/Performance_Troubleshooting may help.
