### ISSUE TITLE
Beatmaps sometimes open osu!updater rathter than being imported straight to stable

### ISSUE THREAD

**Issue by venix12** [ppy/osu-stable-issues#1034]
Basically recently (from a few months?), from time to time an .osz file, or osu!direct URL opens osu!updater rather than running in the game. In those cases, closing the updater and opening the file or clicking the "osu!direct" button again seems to work fine. Most of time, those work just fine and the beatmaps can be opened in osu! without any issues.

I've had this occour quite often recently, as well as heard other people are facing it as well.

Not sure if that's on osu! side, but it doesn't seem to have happened in the past and is quite annoying to deal with so it's worth asking i guess.

**Comment by peppy** [comment]
got a video?

**Comment by venix12** [comment]
https://user-images.githubusercontent.com/30481900/190628507-27235299-c9be-4a44-b3f5-db58e8a32bf8.mp4

**Comment by AJT127** [comment]
this happens like 20% of the time for me now, and also happens when clicking timestamps from modding threads, making BN work extremely annoying

**Comment by peppy** [comment]
Could you please try the latest cutting edge release and see if things work better now?

**Comment by AJT127** [comment]
roger, will note my observations over a day or so and report back

**Comment by AJT127** [comment]
ok the bug still happens D:

edit: strangely i haven't had it happen again tonight, meanwhile it happened on literally the first click of the session, will update again after a day 

edit: happened again, was again the first click in a while, maybe after it happens once now it "remembers" that osu is already open, and then forgets after a while? (idk how stuff works lol)

**Comment by AJT127** [comment]
i feel like it stopped happening now

**Comment by peppy** [comment]
Great to hear. Will close this for now, let us know if it happens again.
