### ISSUE TITLE
15th anniversary backgrounds commonly overrides beatmap background after tapping the random beatmap button (F2) 

### ISSUE THREAD

**Issue by MikkelKristensen** [ppy/osu-stable-issues#1035]
When you hold the random beatmap button, the game will do an animation of scrolling through your beatmaps until picking one at random. While you do this, one of the 15th anniversary backgrounds are shown. However, if you tap the random beatmap button with your keyboard shortcut, this process happens almost instantly. Very commonly (~10-20% chance for me), the anniversary background will load in *after* the beatmap's background, and thereby override it. This leads to the incorrect background being shown for the beatmap until you select a new beatmap.

https://user-images.githubusercontent.com/11474386/190683523-26c70435-1989-4507-9a52-9d5f5676ef2f.mp4

Here's a video where I spam F2 for a little bit to replicate it. As you can see, the maps Ievan Polkka Trance Remix and White Prism showed a 15th anniversary background instead of their actual background. Not shown properly in the video is that often the actual background of the beatmap loads for a fraction of a second before the anniversary background overrides it.

**Comment by peppy** [comment]
Thanks for the report, but we aren't really fixing these kinds of minor issues in stable. Rest assured it can't happen in the next major release of osu! (known as "lazer").

**Comment by MikkelKristensen** [comment]
Yeah I wasn't sure if this was even remotely close to being important enough to fix, but figured I'd report it anyway incase it was a super quick fix and you just weren't aware of it :P
