### ISSUE TITLE
Incorect online star rating displayed for a beatmap

### ISSUE THREAD

**Issue by potato4444** [ppy/osu-stable-issues#1037]
On the [Insane\] difficulty of the beatmap [Shotgun Senorita (Zardonic Remix)](https://osu.ppy.sh/beatmapsets/65853#osu/192508) the in game version of online star rating is displayed as 4.62 whereas as on the website it is 5.53. The other difficulties have the correct star rating displayed.
![screenshot125](https://user-images.githubusercontent.com/32945005/190998476-833c140c-f853-4153-817c-7b8096d0050a.png)

Someone on Reddit also mentioned encountering this problem with this beatmap: https://www.reddit.com/r/osugame/comments/v430wq/star_rating_glitch_on_shotgun_senorita/

**Comment by WindowsMeosu** [comment]
![image](https://user-images.githubusercontent.com/104236864/191035833-c5b1d257-385d-4a3c-ac36-dbdef5b2a1bd.png)
hmm I'd assume it's some type of bug with old maps, alternatively local star rating also has a few downsides
![image](https://user-images.githubusercontent.com/104236864/191036241-f5ff8c53-9139-46d6-ab74-aca384c2c40b.png)
^ also note that's also a really old map (2012 iirc) however, iirc star rating is fetched from the website so I am confused here

**Comment by smoogipoo** [comment]
Does it remain this way after restarting the game? I can't reproduce.

**Comment by WindowsMeosu** [comment]
> Does it remain this way after restarting the game? I can't reproduce.

![image](https://user-images.githubusercontent.com/104236864/192065218-78e21749-bfcd-43c8-b102-25384ac62940.png)
appears to be fixed
