### ISSUE TITLE
Double spinner bug

### ISSUE THREAD

**Issue by sadsweat** [ppy/osu-stable-issues#1039]
https://www.youtube.com/watch?v=RPxMk2PzAwM the bug happens at 1:46 
I was playing osu on my tv then paused right after the spinner and went to plug my monitor back in. The rest I can't really describe. 

edit: btw please watch the video until the end and you will see everything. someone answered my mail and said that nothing is wrong with that just reopen osu. meaning that the staff who was looking at it watched my video for like 30 seconds. I really want this problem to be fixed because it is kind of game breaking.

**Comment by peppy** [comment]
Thanks for the report.

Not sure how this can happen, but it's the first time we've seen this reported in a decade so I don't think it's worth investigating further. Restarting the beatmap (or osu!) is a valid solution.
