### ISSUE TITLE
Beatmaps with extremely long file lengths display a file error

### ISSUE THREAD

**Issue by ghost** [ppy/osu-stable-issues#1040]
Ever since Stable 20220829, myself and others have been experiencing an error when trying to save a beatmap with a long file length: 'Unable to write to file'

A fix was deployed to cutting edge (20220830) but it didn't really fix the issue

Video of it in action on cutting edge: https://www.youtube.com/watch?v=JNdcUVo_--g
Forum post from a month ago: https://osu.ppy.sh/community/forums/topics/1637503

**Comment by peppy** [comment]
A temporary fix is to move your osu install somewhere not-so-nested.

I still intend to deploy a fix (or really, rollback the original fix because it's too much of a PITA to support).

**Comment by peppy** [comment]
Should be resolved now.
