### ISSUE TITLE
Osu can't detect my keyboard input randomly during the middle of the map

### ISSUE THREAD

**Issue by YuJJun0918** [ppy/osu-stable-issues#1043]
This is a problem that occurred with my recently bought keyboard. The keyboard works just fine on every other game INCLUDING rhythm games such as O2Jam -- I've thoroughly tested the keyboard out by playing dense maps as well as easy, simple maps. This problem only persists on Osu, and it's seems to be getting worse. This means overloading isn't an issue here, especially because the problem occurs sometimes when I'm pressing one or two notes at a time. 

I've tried using compatibility mode, optimal frame rates, borderless, fullscreen, etc, but nothing seems to work. Tomorrow I'm going to borrow my friend's keyboard and check if the problem still exists, but in the meantime, I would like to submit this issue as it doesn't make sense that only Osu causes my keyboard to stop working for short 0.5 ~ 2 sec bursts.

**Comment by peppy** [comment]
Please follow up in your existing issue thread to keep everything in one place https://github.com/ppy/osu-stable-issues/issues/1042
