### ISSUE TITLE
Background images for certain maps haven't been showing for years.

### ISSUE THREAD

**Issue by Remyria** [ppy/osu-stable-issues#1044]
So, this is an issue that's been present on some maps for many years. Some of the BG's got removed for obvious reason, with the image deleted from the map folder, but some others I'm confused as to what happened exactly for them to disappear.

I remember, for example, on [this](https://osu.ppy.sh/beatmapsets/14983#osu/54697/) mapset, the BG's worked when I started in 2012 but stopped showing in the menu and during gameplay years ago despite the files still being in the folder. Something really odd is that the BG still shows in the editor on the proper difficulty.

Screenshots:
[Menu(SteRRuM diff)](https://osu.ppy.sh/ss/18199645/3ec8)
[Editor(SteRRuM diff)](https://osu.ppy.sh/ss/18199648/ca88)
[Menu(Teke diff)](https://osu.ppy.sh/ss/18199667/934a)
[Editor(Teke diff)](https://osu.ppy.sh/ss/18199669/0b12)

I did a bit of inspection and compared it with another V7 .osu but I can't figure out what's going on besides the line with the image file looking different on the bugged one:
https://Remyria.s-ul.eu/sJZuseES

(Worth nothing worse bugs appear on some even older maps, like [This one](https://osu.ppy.sh/beatmapsets/664#osu/4563) (V4 .osu, although I'm not sure that's the cause, many other maps from the same era or older work just fine) which the BG only shows on the [Easy] for me as well as having trouble getting the audio to work(updating+1x F5 not being enough, kida just magically started playing after opening a few other maps in editor trying to see their .osu files). (The import process doesn't quite work and the diffs need to be updated, initially showing as corrupted/empty)

If it's fixable in stable, lazer, both or neither, I'm interested to know what's up with those mapsets regardless if you know. It's unfortunate that some maps miss their BG's :\

**Comment by peppy** [comment]
That's very weird. I can reproduce the issue so will take a look further.

**Comment by Coppertine** [comment]
My guess is that the client expects the full string of `0,0` instead of the enum return values like those for the Storyboard implementation. So a quick fix would be to check for the background as that enum instead of a full string check. It might also not be that case.

**Comment by peppy** [comment]
It actually supports both, but a change was made by someone in 2013 which was 100% incorrect and broke this behaviour ever since. I'll include a fix in the next release.

**Comment by Remyria** [comment]
idk if I should make an issue in lazer section instead of replying here(especially since this issue is closed) but whatever. I rewrote the post a few times before sending and I didn't mention it but on lazer, the BG show neither in the menu, during play or in the editor. (sorry for forgetting to include it initially and also if I was meant to post it over there instead, I just realized it >.<)

**Comment by peppy** [comment]
Would be appreciated if you can open a discussion or issue on the lazer repository, we'll handle it separately.

**Comment by Remyria** [comment]
got it ^^
