### ISSUE TITLE
Mysterious rare "Cannot write to file" errors when saving beatmap

### ISSUE THREAD

**Issue by tilda** [ppy/osu-stable-issues#1045]
Not exactly sure what is happening here. This started happening relatively recently, I think after that one update that changed saving behavior? In another (semi-related) issue you said you rolled this back but it just happened to me. It's happened more than once, but I haven't really thought to capture it on video until now.

https://user-images.githubusercontent.com/8301262/197357768-6da1ce86-dc56-4970-af8f-04a03f81118c.mp4

(sidenote: there's no audio because I worked on this map for like 2 hours and then it just got erased like that with no way to return my progress, so of course I kind of started shouting profanities into my microphone)

I'm on b20221016cuttingedge. My osu! install is on a separate drive, I checked if both my drives were in healthy status (in fact the one osu! is on is 100% healthy). The filename itself is also only around 119 characters long, so Windows shouldn't be throwing anything.

**Comment by peppy** [comment]
So two things:

Your beatmap can't be erased. With the new file write behaviour, it will never cause a previous version to be lost, so at most you can only lose one save.

Also, each save is first written to a temporary file, so your work is not lost. It is likely in your windows temporary file folder.

I can't tell you why the write failed without your logs, so can you provide those to begin with?

**Comment by tilda** [comment]
Hmm, is it supposed to be in the `Temp\osu!` folder? Don't see anything there.
I zipped up the logs folder for you: [Logs.zip](https://github.com/ppy/osu-stable-issues/files/9845317/Logs.zip), I *believe* this is the same session that this issue happened in.

**Comment by peppy** [comment]
It will be in the temp folder with a non-description random file name (not in the osu! subfolder). Sort by modified time.

**Comment by tilda** [comment]
I found the file, thanks for the solution. I definitely am curious what's happening with this though...
