### ISSUE TITLE
osu chat bug

### ISSUE THREAD

**Issue by jorivero321** [ppy/osu-stable-issues#1046]
When using ctrl + tab to switch between chat tabs it works fine the first time, but if you keep the keys pressed down it makes the sound of switching tabs repeatedly without changing the tab, not sure if intended, but if it is at least maybe make the sound not play when a user happens to keep the keys pressed down

**Comment by smoogipoo** [comment]
This is not a critical issue and likely not simple to fix, so I'm calling it out of scope. This doesn't happen on lazer (the next release of osu!), although there's no sound there in the first place.
