### ISSUE TITLE
Scroll bars suddenly show up while playing

### ISSUE THREAD

**Issue by TheRealStevie** [ppy/osu-stable-issues#1048]
While I was playing a map scroll bars show up. I must have accidently press something along the way, but I don't think this should happen. I also can't seem to interact with it. Restarting the game makes it disappear.

Screenshot below was taken in-game using F12.

![screenshot089](https://user-images.githubusercontent.com/75444413/199355691-c5ef20eb-8584-4b33-ac56-e082a34986e7.png)

For reference, I use mouse to aim and keys G/H to tap.

I forgot to collect logs before restarting the game, sorry. :(

**Comment by smoogipoo** [comment]
These don't come from the game. They're related to some overlay you have running, perhaps an application like Discord.

**Comment by TheRealStevie** [comment]
> These don't come from the game. They're related to some overlay you have running, perhaps an application like Discord.

I had a browser in my background so maybe it has something to do that caused this. Thanks!
