### ISSUE TITLE
Osu database corrupts when closing osu too quickly

### ISSUE THREAD

**Issue by ElectroYan** [ppy/osu-stable-issues#105]
When closing osu right after exiting, finishing a beatmap or rage quitting with alt-f4 it sometimes causes the beatmap database to corrupt, because it's still writing something but exits anyway.
In one case I had to completely delete it because it was too corrupted to be read by osu. This caused a constant 100% drive usage unless you force-closed osu via taskmanager. 
Also on some occasions this deletes all local scores and the collections database.

**Comment by peppy** [comment]
osu! writes the database to a temporary file and moves it as an atomic operation, meaning this should not be possible. Could you please provide a video of this happening and the resulting database file for further investigation?

**Comment by ElectroYan** [comment]
I tried for some time but I couldn't reproduce it. So I assume it might not exactly be caused by quitting but it occasionally happens and that's the only pattern I noticed.
