### ISSUE TITLE
Absence of internet logs me out

### ISSUE THREAD

**Issue by TheAirBlow** [ppy/osu-stable-issues#1050]
Basically, it's just annoying to log in each time you play offline and then reconnect to internet.
Suggestions: All online features will get disabled the same way it does when you're not logged in, and the user "signed in" card would show "No internet" instead of Online/Do not disturb/etc. and the token won't be erased from existence. To detect if you have internet, just ping `1.1.1.1` or `8.8.8.8` as fallback.

**Comment by smoogipoo** [comment]
I don't think this is a simple change, and given that this doesn't affect the vast majority of the playerbase who don't frequently switch between online/offline, I'm tempted to mark as out of scope and fixed in lazer.

**Comment by peppy** [comment]
I'm not sure what you're seeing, but stable does not log you out with no internet. Please take a video.

**Comment by TheAirBlow** [comment]
> I'm not sure what you're seeing, but stable does not log you out with no internet. Please take a video.

I just realised that I accidentally chose the stable instead of the lazer one. Meh.
And also, that was just a fluke and smth else happened, idk.
