### ISSUE TITLE
Cursor/Sensitivity Issue (Windows 11)

### ISSUE THREAD

**Issue by eggooooo** [ppy/osu-stable-issues#1053]
As of recently, when running osu! in windowed mode while having a low sensitivity setting, the windows cursor would clip outside the game window. (see video)

**(Edit: Windows cursor also feels *extremely* sluggish when in the social browser, doesn't happen when alt-tabbed though)**

This didn't happen prior to yesterdays update (not sure when exactly, i rarely update my os), so it's most likely an issue with windows itself 

Client version: b20221104.1beta
Windows version: Windows 11 Pro 21H2 (Build 22000.1219)

https://user-images.githubusercontent.com/64386789/202707890-2d11dc41-810f-4f3a-ab83-2b41c756285d.mp4

**Comment by Macacito** [comment]
this is a bug from osu!auth.dll

**Comment by peppy** [comment]
This should be fixed now! Please restart osu! to receive the latest update.

**Comment by eggooooo** [comment]
Hm, there doesn't seem to be a new update available on my end. Does it take a bit longer for new updates to arrive?

**Comment by peppy** [comment]
Restarting your game once or twice should be enough to receive the update.
