### ISSUE TITLE
Persist closing #osu

### ISSUE THREAD

**Issue by Edythator** [ppy/osu-stable-issues#1054]
Currently, in stable, your changes to #osu don't persist. That is to say that, if you close #osu, it will reopen on startup.

On close:
![1b72](https://user-images.githubusercontent.com/20105459/202894901-afdf126b-02b6-4fa5-9fed-b5c8b267e7c3.jpeg)

On open:
![4a94](https://user-images.githubusercontent.com/20105459/202894907-5addec57-e92e-468e-9903-c2d80f3ce000.jpeg)

What would be optimal in this case would be to persist the chat change in between restarts, so that you don't have to manually close #osu every time.

Potentially related to #21?

**Comment by BK8000L** [comment]
yeah this is annoying

**Comment by peppy** [comment]
I've tried to do this in the past and it was a bit too hard to do it without regressing things. Please wait for lazer, where this behaviour has been implemented.
