### ISSUE TITLE
Microstutters causing slight offset throughout map

### ISSUE THREAD

**Issue by NoelleTGS** [ppy/osu-stable-issues#1055]
I started noticing this essentially right when I downloaded osu! on my laptop, it never had this issue on my old PC. While playing a map, occasionally it'll microstutter and give an offset of about 5ms (as in, I'll start hitting early). Usually when it's only one it's not noticeable, but often it'll happen multiple times during a map and I'll end up being upwards of 35ms off. 
I typically use stable but I switched over to cutting edge to see if it happens there and it still does. I attatched the performance log that cutting edge makes and a replay showcasing it. You can see that (although my UR still sucks lol) it's pretty noticeable that I get slightly more off as the map progresses.

[NoelleTGS - inabakumori - Lagtrain [Apollo's Insane] (2022-11-20) Osu.zip](https://github.com/ppy/osu-stable-issues/files/10050418/NoelleTGS.-.inabakumori.-.Lagtrain.Apollo.s.Insane.2022-11-20.Osu.zip)
[performance.log](https://github.com/ppy/osu-stable-issues/files/10050420/performance.log)

Specs are a Ryzen 7 5825U with 16GB of 3200mhz RAM.

**Comment by peppy** [comment]
Please check https://osu.ppy.sh/help/wiki/Performance_Troubleshooting for performance troubleshooting tips.

If audio is changing, it sounds like a probable driver or hardware issue (I'd start with audio drivers.

**Comment by NoelleTGS** [comment]
Unfortunately I'm not able to consistently reproduce this. Some days it happens, some days it doesn't, nothing consistent between the days. I'll come back if I can find anything that causes it.
