### ISSUE TITLE
[Mania] ScoreV2 gameplay changes award skill medals too easily.

### ISSUE THREAD

**Issue by Gamer81900** [ppy/osu-stable-issues#1056]
Hello, I am part of a medal hunting community. Recently, enabling ScoreV2 has allowed medals to be awarded (I'm pretty sure with all modes). This has come with side effects that were likely unintended. By mashing every key at a 1/2 rhythm, some maps can be FCed without 50s / BADs , and will award their respective FC medals. 

I have seen players use this method to FC maps from 4* up to and including 8*. Considering the mania 8* FC medal was the second rarest medal before this event, there is an issue. I have listed some examples of maps that this is possible on below, including a 6* FC video that shows the technique being used. Thanks.

5* : <https://osu.ppy.sh/beatmapsets/553866#mania/1236035> +DT
6* : [Anone DT FC Video Example](https://youtu.be/uVGhw4uwqnk)
7* : <https://osu.ppy.sh/beatmapsets/397764#osu/865102> +DT
8* : <https://osu.ppy.sh/beatmapsets/1779730#mania/3727758> +DT

**Comment by peppy** [comment]
This has already been disabled.
