### ISSUE TITLE
Perfomance issue when switching languages

### ISSUE THREAD

**Issue by FrameMuse** [ppy/osu-stable-issues#1058]
## Platform
Windows 11 - Pro

## Description
When switching language to the same language, osu suffers significant fps drop (about 25-50%), then in a few seconds it goes to normal again.

#### From this state which is normal for my osu
![image](https://user-images.githubusercontent.com/53980482/204359513-24766943-cca9-4f25-9bfe-fe4ca41e15d1.png)
#### To this
![image](https://user-images.githubusercontent.com/53980482/204359926-071318a5-e1d3-4eff-8d5b-6edcda6f8bdf.png)

## Tips
To be able to switch to the same language, you may set a hotkey for a language.

**Comment by FrameMuse** [comment]
This is kinda interesting issue ^-^, I wonder if it's `Windows` or `OSU!` issue.

**Comment by smoogipoo** [comment]
This is not a "critical" issue.

**Comment by FrameMuse** [comment]
Oh, sorry, I didn't read that these issues have to be critical.
