### ISSUE TITLE
Buged menu buttons

### ISSUE THREAD

**Issue by FrameMuse** [ppy/osu-stable-issues#1059]
## Description

The menu buttons behave in a weird way.
I'm too lazy to explain on text, so watch this video.

https://user-images.githubusercontent.com/53980482/204639072-c8047bf4-5fde-4516-8413-0974e51208f2.mp4

- I have VPN enabled and bancho connection fails while chats works.
- Disabling VPN and successful connection gives no effect (it's still buged).
- Changing theme gives no effect (it's still buged).

## Platform

Windows 11 Pro

**Comment by peppy** [comment]
Your GPU is failing to load textures. This could be due to your custom skin, drivers, or hardware failure. Please check on these.
