### ISSUE TITLE
Editor timeline goes beyond

### ISSUE THREAD

**Issue by Mahonzu** [ppy/osu-stable-issues#1061]
I was playing around with bpm and found this

![bug](https://ilia21.s-ul.eu/1AgObz7I.gif)

Steps to reproduce:
1. Make first timing point at 180 bpm
2. Make second timing point near end with 1 bpm 
3. Scroll

This also works if song starts with 1 bpm
![bug2](https://ilia21.s-ul.eu/gWdVEqTp)

After a little research, I realized that bug only works on the "design" tab

**Comment by peppy** [comment]
This is by design. The design tab allows creating intros and outros
