### ISSUE TITLE
shift+f2 bug?

### ISSUE THREAD

**Issue by daishin108** [ppy/osu-stable-issues#1065]
this happens to me when a map is shared between collections and then I f2 and shift+f2 to get back to it. It teleports me to the other collection with the same map. 

https://user-images.githubusercontent.com/107208864/206047197-b5d5e813-f414-4945-b404-fd76bb6ae656.mp4

**Comment by Sharqosity** [comment]
Yep, it always goes to the topmost collection the beatmap is in. This has been annoying me for a while

**Comment by smoogipoo** [comment]
Will be fixed in the next release.
