### ISSUE TITLE
Repeatedly spamming spinners prevents players from pausing during maps

### ISSUE THREAD

**Issue by Protastic101** [ppy/osu-stable-issues#1069]
Recently, there was a map (now deleted) where it repeatedly spammed spinners (5/8 long spinners at 212 BPM for reference) while the song was just audio repeating a racial slur. The player was unable to pause during the spinner spam, and had to sit out the entire 2 minute map or forcibly quit osu! using task manager or something similar to exit the song. I can see people abusing this in similar ways if not fixed soon. I found that you cannot pause during spinner spam in standard and taiko. You can pause if playing catch though.

**Comment by peppy** [comment]
This should be fixed on the latest cutting edge release.
