### ISSUE TITLE
Multi room overlays on lobby show old game mode name

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-stable-issues#107]
![](https://puu.sh/El6eb/529ff051cf.png)

![](https://puu.sh/El6eV/6d0cc0fbff.png)

and so on.

`Osu` -> `osu!`
`Taiko` -> `osu!taiko`
`Catch The Beat` -> `osu!catch`
`Osu Mania` -> `osu!mania`

**Comment by peppy** [comment]
I believe I looked at this once before but it wasn't a simple change, due to the underlying enums being used in API methods where the name mattered.
