### ISSUE TITLE
horrible frametimes because of...

### ISSUE THREAD

**Issue by BK8000L** [ppy/osu-stable-issues#1070]
running osu on only 1 cpu core gives a terrible frametimes, but can be fixed with... can be seen on the video.

https://user-images.githubusercontent.com/82240117/207742815-b33395cd-9076-4b8c-b661-7104912c8475.mp4

or in youtube: https://www.youtube.com/watch?v=pU77u4Q9rUE

**Comment by peppy** [comment]
Could you please provide your system specs / model?

**Comment by peppy** [comment]
It has been pointed out you're using a modified client. We cannot provide any support sorry.
