### ISSUE TITLE
Decrease minimum slider velocity from 0.1x to 0.01x or lower

### ISSUE THREAD

**Issue by 1103x** [ppy/osu-stable-issues#1072]
Numerous mappers have suggested this game change as an alternative to a proposed ranking criteria change, which would have been a band-aid fix to the underlying issue that there's an arbitrary limit on how slow we can make sliders (https://osu.ppy.sh/community/forums/topics/1682839).

posting on behalf of quila due to problems with their github account

**Comment by peppy** [comment]
I think we can likely make this change. @smoogipoo can I get your thoughts on this?

**Comment by smoogipoo** [comment]
Sounds fine to me.
