### ISSUE TITLE
Unable to navigate between windows due to NVIDIA drivers

### ISSUE THREAD

**Issue by Ladwick** [ppy/osu-stable-issues#1073]
I'm new to issues, so sorry if I'm missing something!

OS: W10 64x
Integrated Graphics: Intel UHD Graphics
Discrete Graphics: RTX 2070

**THE PROBLEM**

A couple of months ago I started to experience a curious problem with stable, each time I tried to alt+tab and then go back to the osu window, the game would crash, the game and the sound would be still running, but the image would be stuck until I restarted the app, this also happened when I opened the editor, it looked like this: 
![image](https://user-images.githubusercontent.com/37979533/208166577-98cfe674-29f2-4269-9e16-0947d086d003.png) (the image is from [this thread](https://osu.ppy.sh/community/forums/topics/1667701?n=1))

Looking through the osu! help forum, I found [this thread](https://osu.ppy.sh/community/forums/topics/1668659?n=3), where they said the [NVIDIA drivers ver. 526.47](https://www.nvidia.com/download/driverResults.aspx/194112/en-us/) (and newer, at least until [527.37](https://www.nvidia.com/download/driverResults.aspx/197300/en-us/), I'm not sure if the problem persist with even newer drivers) were at fault, I tried running the game with the integrated graphic and, in fact, the problem was solved.

Today I tried reinstalling old drivers for NVIDIA, more specifically, the [NVIDIA drivers ver. 522.25](https://www.nvidia.com/download/driverResults.aspx/193713/en-us/) and in fact (again), the problem was solved. 

I mean, the problem is fixed for me, but maybe this piece of information can help somebody else!

**Comment by peppy** [comment]
Does turning on compatibility mode fix the issue too?

**Comment by Ladwick** [comment]
> Does turning on compatibility mode fix the issue too?

In my case, compatibility mode get things worse.

First, when I turn it on, the game closes, ok, thats fine, but when I open it again, it throw this error from three to four times.
![image](https://user-images.githubusercontent.com/37979533/208223940-3b0ac17b-820e-4ad4-80a3-b1bfcab17d84.png)
After closing the error many times, I can enter into the game, but instead of just freezing the image after switching the window and going back to the app, it goes completely black. Aditionally, I won't be able to disable the compatibility mode in-game since everytime I try it, the game would close and once I open it again, it's still enabled (and giving those OpenGL errors). The only way I can disable it is turning it off manually from the game configuration archive.

**Comment by peppy** [comment]
That message means that it's not even using your nvidia card. Can you check your windows graphics performance settings (moved to control panel if you're on windows 11) and force osu! to use your nvidia card and see if things get any better?

**Comment by Ladwick** [comment]
> That message means that it's not even using your nvidia card. Can you check your windows graphics performance settings (moved to control panel if you're on windows 11) and force osu! to use your nvidia card and see if things get any better?

I tried forcing the game to run with the NVIDIA card (high performance) through the windows graphics performance settings and the NVIDIA control panel, the problem still appeared.

The only way to fix all the problems in the end was downgrading my NVIDIA drivers and set off compatibility mode, I should try using the latest drivers again tho to see if anything changed with newer versions.

**Comment by Ladwick** [comment]
I forgot to close this, [20231121.5](https://osu.ppy.sh/home/changelog/stable40/20231121.5) fixed the problem.

**Comment by Ladwick** [comment]
I forgot to close this, [20231121.5](https://osu.ppy.sh/home/changelog/stable40/20231121.5) fixed the problem.
