### ISSUE TITLE
Song select menus seem to reject inputs if too fast

### ISSUE THREAD

**Issue by AzerFrost** [ppy/osu-stable-issues#108]
Using keybinds to navigate some menus was slowed down, two observed and consistent examples I've personally noticed were the map options screen (deleting a beatmap with F3 2 1 used to be instant and now the 2 input will go in the search field if entered too fast) and the mod selection screen (same thing, I have mods bound to keypad keys and they will go in the search field if applied too fast). 100% reproduction rate on both.

**Comment by smoogipoo** [comment]
Have tested that the fix for https://github.com/ppy/osu-stable-issues/issues/97 has not fixed this.

**Comment by peppy** [comment]
Can seemingly reproduce this easily, but I haven't tested against previous builds to ensure it's a regression.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge build.
