### ISSUE TITLE
New stable update broke Wine compatibility

### ISSUE THREAD

**Issue by EllySensei** [ppy/osu-stable-issues#1081]
OS: Arch Linux (reported instances on Fedora, and other Linux distros as well)
Kernel Version: 6.1.1-273-tkg-pds
osu! version: [Stable 20230121.1](https://osu.ppy.sh/home/changelog/stable40/20230121.1)
Wine Version: wine-7.11
Steps to reproduce: 1. Update to the latest osu! Version on Wine.
[log.txt](https://github.com/ppy/osu-stable-issues/files/10471989/log.txt)

![2023-01-21_18-35](https://user-images.githubusercontent.com/50310657/213863265-afb0b71b-ee54-49a9-84a0-30e5fd72e02f.png)

**Comment by peppy** [comment]
Thanks for the report. This was fixed via a hotfix a few hours after the update. Forgot to close this issue.
