### ISSUE TITLE
Storyborad sample sound  can't be accelerated

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#1083]
If use DT or HT mod, storyborad sample sound  can't be accelerated, is this a bug or is it not intended to be implemented?
Can we repair or expand the implementation of acceleration function?

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu). If you have the time, please check on lazer whether this is already fixed, and if not, search for existing issues covering this. You're welcome to report over there if you can't find it already reported.
