### ISSUE TITLE
Computer reboots/crashes when playing osu

### ISSUE THREAD

**Issue by Gann4Life** [ppy/osu-stable-issues#1086]
Yes, I think that this is quite serious, I did a complete reinstall of the operating system and the issue is still present, the computer is brand new as I bought it last year.

**I'll quickly describe the issue**, which happens in two different situations but might have something in common:
Today I launched osu and, **while I was waiting for it to load, the computer rebooted. Before the reboot, there was a black screen that didn't allow me to alt-tab or interact with the system, not even being able to use CTRL - SHIFT - ESC or CTRL - ALT - DEL.**

But a few days ago, playing normally, I alt-tabbed quite often to open and minimize the game (repeatedly)  because of some stuff I was doing at the same time I was playing, and then this black screen thing happened, with the same behaviour of not letting me manipulate the computer and then reboots.

## What was I doing? 
Well, I think that it doesn't matter at all as today (where the issue happened just by launching the game) I only had discord and web browser (Microsoft Edge) open, but I often use blender and other programs in the background and no problem with them, not even with heavier games (although I do limit these other heavy games to 60fps but input lag is not important)

## Game settings
I play on fullscreen with no framerate limit, I fear that it has todo with any of these settings but I do not want to lose perfomance, having it limited to 60fps generates way too much input lag for my taste, and I use fullscreen mode to keep perfomance at the top because of the other software I have open sometimes.

## Specs
OS: Windows 10 Pro 21H2 Build 19044.2486
APU: AMD Ryzen 5 5600g (I think it's using 0.5GB for vram)
RAM: 16GB
AMD Driver: AMD Software Adrenaline Edition, version 22.11.2

**Comment by smoogipoo** [comment]
osu! doesn't have the capability to restart the system by itself. This is an issue with your system, likely related to either drivers or power (PSU). Running at no framerate limit can exacerbate issues with the latter.

In any case, you should have an entry in the event viewer telling you more about it.

**Comment by nyannoying1337** [comment]
I allow myself to butt into here.

It appears to be a AMD Driver issue in general. i had it happen multiple times by now. im unsure if there would be a way to get this looked into or anything or perhaps put out a info about it.

**Comment by smoogipoo** [comment]
Are there any errors in event viewer when it happens? It should help you debug/report the issue.

**Comment by nyannoying1337** [comment]
@smoogipoo this is all i get sadly. dont think thats enough to point it down. i did submit a bugreport to AMD about this but perhaps this tells you more ( altough i would doubt )
![grafik](https://user-images.githubusercontent.com/17437302/227739849-5dd19263-0180-4174-a96b-cb334ea0c579.png)
[Microsoft (R) Windows Debugger Vers.txt](https://github.com/ppy/osu-stable-issues/files/11070004/Microsoft.R.Windows.Debugger.Vers.txt)
