### ISSUE TITLE
Cannot start chat on cuttingedge

### ISSUE THREAD

**Issue by marcostudios** [ppy/osu-stable-issues#1088]
https://streamable.com/zokyfw https://osu.ppy.sh/community/forums/topics/1715651

Saw many users having this issue, and it seems only cuttingedge has this issue.

**Comment by msmcculley** [comment]
Seems that it is strictly a client issue as the /query command works in IRC and on stable. Can confirm that it works on stable and beta, but not on cuttingedge. Subsequently the /msg command does not work either.

Funny enough, the /query command works if the user is not an actual user as seen in the video below.

https://user-images.githubusercontent.com/90729492/216158491-870468ad-89b2-49bc-930b-80874d78cd6e.mp4

**Comment by peppy** [comment]
Should be fixed now!
