### ISSUE TITLE
Beatmaps double counted

### ISSUE THREAD

**Issue by Ocklepod** [ppy/osu-stable-issues#1089]
When changing grouping from Rank Achieved to Difficulty, I noticed that the amount of beatmaps found changes. Traced this back to Difficulty grouping displaying "10 Stars" and "Above 10 Stars", which double displays and counts 10.00*-10.99*. For example. with hrdt mods enable this adds ~2000 matching beatmaps to search results

I assume this is not intended, since the other Groupings except Collections don't double count any maps. I suggest removing either "10 Stars group" or making a "Above 11 Stars" or even adding "11 Stars" and "Above 12 Stars" as to keep all maps with a "broken" Star rating in one tab.

Here's a screenshot showing a random 10* map being in both categories (light blue instead of dark blue)
![screenshot1296](https://user-images.githubusercontent.com/56438032/216316506-d84c5792-e8f3-47f1-8c72-260f2791f9cf.jpg)

**Comment by smoogipoo** [comment]
Will be fixed in the next release.
