### ISSUE TITLE
why isn't this implemented

### ISSUE THREAD

**Issue by its0ka** [ppy/osu-stable-issues#1091]
this is what the correct media player looks like in the taskbar:
![image](https://user-images.githubusercontent.com/125186204/220161508-4b33aee9-511f-433d-81a8-bcfb93ab0c41.png)
there is song name and pause/next buttons

in osu there is nothing like in wmp:
![image](https://user-images.githubusercontent.com/125186204/220161750-2355aab9-38e2-4e5b-9918-dff4a122fdd8.png)

is it possible to add these features to make it a full fledged music player like this?
![image](https://user-images.githubusercontent.com/125186204/220162125-4733c3b1-1a7c-479a-a2e7-9d5df9c02b3b.png)
lack of this affects my daily enjoyment

**Comment by its0ka** [comment]
also bass boost and vocal remover would be nice to see in new versions

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. Also, osu! is not a music player (please use spotify or similar for this).
