### ISSUE TITLE
"This Beatmap's Thread" button in Editor doesn't do anything upon clicking

### ISSUE THREAD

**Issue by Skubers** [ppy/osu-stable-issues#1093]
As in the title.
![image](https://user-images.githubusercontent.com/82095491/220756789-f517a97e-2251-452b-82f3-4f0b0be3e733.png)
This button doesn't do anything upon clicking, when it should redirect to discussions.

Reproduced on Stable

**Comment by peppy** [comment]
Should be fixed in the next release.
