### ISSUE TITLE
[Quick Fix / Feature Request Suggestion] (osu!standard) Automatically disable SpunOut mod if the beatmap has no spinners

### ISSUE THREAD

**Issue by gabrielwoj** [ppy/osu-stable-issues#1094]
<hr>

- Operational System: Windows 10 Pro 21H2 (64-Bits)
- osu! version: b20230206
<hr>

The "SpunOut" mod is a mod only available to osu!standard. Upon enabling it, the game will automatically spin spinners for the players at a reduced speed rate, as well subtracting the Score Multiplayer to -0,10x.

However, the "SpunOut" mod is still enabled for beatmaps even without spinners, and the mod will still reduce the amount of score you can receive if you ended up having it enabled by accident before starting the map in question. The SpunOut icon, as well the text "SpunOut" is shown on the song selection screen, are shown when entering a map with no spinners while it is enabled.

<hr>

I made a small test on a short map, with no spinners, and made a SS playthrough with SpunOut enabled and disabled:

![image](https://user-images.githubusercontent.com/13741779/221258688-a4c5422c-17fb-4be3-915b-c333ec721c0b.png)

As we can see, the score with "SO", SpunOut, has a lower score, despite the map having no spinners to begin with.

<hr>

I enjoy playing osu!standard in a more casual manner, so I often times keep SpunOut enabled. Although I like playing casually, yes, I don't really like how the game just applies a penalty for my score for beatmaps that have no spinners to begin with.

Often times I end up going to another map with no spinners when having SpunOut already enabled, and I get a penalty for it, and it's a bit cumbersome having to always check if a map has spinners or not so I can manually disable it.

<hr>

In osu!mania, for converted songs (playing osu!mania on songs made for osu!standard), the Score Multiplayer changes depending on how many keys the beatmap has, and how many keys the user wishes to play using the Mod Selector.

If a user selects "4K" on the Mod Select menu, and selects a beatmap with 4K↓, the mod will still be enabled (as it's shown as 4K in the song select screen), but no Score Multiplayer penalty is applied.

I don't know 100% how osu!mania works, but, considering there's a code in the game that checks the amount of keys on a map on osu!mania, and dynamically changes the Score Multiplayer, I think a similar code can be made so users don't have SpunOut enabled on a beatmap that has no spinners while playing osu!standard.

Thank you.

<hr>

**Comment by peppy** [comment]
We may consider adding a warning or similar in lazer, but Indo not foresee a change like this happening in stable as the game is feature locked and this is a non-trivial change.

**Comment by gabrielwoj** [comment]
> We may consider adding a warning or similar in lazer, but Indo not foresee a change like this happening in stable as the game is feature locked and this is a non-trivial change.

Thank you for your response. I'll be closing the issue now.
Hope you have a nice rest of your day/night 😊
