### ISSUE TITLE
Abnormal bg flickering issue and audio transition temporarily not working for a short time

### ISSUE THREAD

**Issue by Stehsaer** [ppy/osu-stable-issues#1096]
- When switching osu! from background to foreground while osu is in **song select screen**, the bg shifted a bit and causes visible visual anormaly.
- One more thing I noticed was that the audio transition between songs seems to be not working after the bg flickers, but it "fixed" itself that after clicking different songs for some more times the audio transition somehow starts to work again

Doing the same but with osu in main screen doesn't generate the audio transition issue but the bg still occasionally flickers

For the audio issue, noticing the sudden increase of volume when switching to another song
For the bg issue, notice the bg shifts for a few frames

### See screen recording below:

- video with audio transition issue and bg issue, notice how the LET'S JUMP audio begins with loud volume:

https://user-images.githubusercontent.com/54050160/221361459-eba9e07a-b485-4147-8720-570b0166586b.mp4

- switching to main screen doesn't generate the audio transition issue, notice how different the LET's JUMP audio starts from the previous one:

https://user-images.githubusercontent.com/54050160/221361540-645aee4b-4d89-44d9-b970-13a8af8b7c68.mp4

### More Info:
- osu version: stable 20230206
- Graphics driver updated to the latest one available provided by Nvidia

**Comment by peppy** [comment]
No idea sorry. This is going to be an issue with something between osu! and your eyes (drivers hardware etc.) which we likely will not be able to reproduce.

If you can make anything similar happen on lazer then please report there, but we can't really do much on stable for issues like this.

**Comment by smoogipoo** [comment]
The visual issue looks to be related to parallax. Don't know about the audio issue, but as above.
