### ISSUE TITLE
"Show approach circle on first "Hidden" object" does nothing if the first object is a spinner

### ISSUE THREAD

**Issue by Octol1ttle** [ppy/osu-stable-issues#1102]
Expected: If the option is enabled, the circle/slider after the spinner will have an approach circle
Actual: The approach circle is missing

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
