### ISSUE TITLE
update osu caused system to reboot, and osu will not open after the reboot

### ISSUE THREAD

**Issue by arily** [ppy/osu-stable-issues#1103]
What I did:
- open osu!
- letting it update
- quit osu
- start osu again 
- screen goes black then system rebooted
- open osu again and saw an error with title `osu!.exe - Corrupt File` and content `The file or directory \osu!\_staging is corrupt and unreadable. Please run the Chkdsk utility. ` 
![image](https://user-images.githubusercontent.com/10007589/224486846-eaaabc1f-3f98-464b-a764-dc1eb7cab0c4.png)

 I cannot close the dialog, each time I click `ok` or `x` it pops up again.
there's no process in taskmgr so the only way to terminate the game is to reboot.

**Comment by peppy** [comment]
this looks like disk corruption. show hidden files and delete the _staging folder and see if it recovers.

also run a full disk check, like it tells you to.

**Comment by arily** [comment]
Thank you for the help! My osu is working again.
One small thing: this window still pops up every time I click ok or close it until I reboot the PC again. Could you please see if you can prevent it from constantly showing?

**Comment by peppy** [comment]
This is not an osu! error message, but a windows one. You can google for more details on potential fixes.
