### ISSUE TITLE
osu! ignores all in-app acitivities

### ISSUE THREAD

**Issue by rvneXe** [ppy/osu-stable-issues#1104]
Hi, i've realized that my osu! profile ALWAYS shows me offline, unless I open osu!'s website.
and nothing of my scores are calculating in it.

![image](https://user-images.githubusercontent.com/89677246/224507690-4b461db2-9a61-490d-b769-854e1a28a2c0.png)
Ranked Score is 0, and Play Count never changes. Even after I played around 20 beatmaps today, this number never changed... .
![image](https://user-images.githubusercontent.com/89677246/224507691-36800c51-52f9-48fb-ba8b-238821991bab.png)
Not any A Scores I got are counted here. (I got some S 's too)

Why this is happening? (my profile https://lazer.ppy.sh/users/32706897 )

**Comment by rvneXe** [comment]
*I'm # 1 on the beatmap that I've pinned, and:
![image](https://user-images.githubusercontent.com/89677246/224507987-8ac1cd74-946b-4da7-820c-6fe6292caaed.png)

**Comment by peppy** [comment]
You linked your lazer profile. Please read the message at the bottom of the screen.
