### ISSUE TITLE
Relax pressing early when aimed at something else while in previous object's hitwindow

### ISSUE THREAD

**Issue by Paladynee** [ppy/osu-stable-issues#1106]
While playing with the Relax mod, theres an issue which causes Relax's autoclick to press early (sometimes way too early to cause combo breaks).

This bug will happen if the conditions are met:
(object 1 is a slider, object 2 is a sliderhead or a hitcircle)

- happens at: after the earliest point in time Relax's could've clicked object 1, but before object 1's sliderhead's hitwindow ends

- your cursor must be on top of/pass the hitbox of object 2 any time during this window.

This will cause Relax to click on object 2 early, possibly causing 100's, 50's, even combo breaks.

### This bug can occur when object 1 is a hitcircle too, but it triggers a notelock and thus does not trigger a combobreak.

This issue is not minor nor very hard to replicate. I've had this issue happen on normal stream maps, slider heavy maps, basically every kind of map. Usually its in the form of early 100's but it sometimes ruins my Relax runs on [XNOR XNOR XNOR by fanzhen0019](https://osu.ppy.sh/beatmapsets/1236927#osu/2573162)

I think this bug is caused by Relax not checking whether the object under the cursor (object 2) and the object Relax is trying to hit (object 1) is the same. Relax is trying to click object 1 while we are aiming at object 2, causing this bug. I think this bug is fixable with a few lines of code (not that big of a scope).

### Here are sample videos where the bug occurs.

https://user-images.githubusercontent.com/62181440/224539258-f6684358-2163-4fe3-8f71-7325995388b7.mp4

https://user-images.githubusercontent.com/62181440/224539265-bce7ed1b-851c-4db2-a7f3-afa84b6641e7.mp4

https://user-images.githubusercontent.com/62181440/224539281-cebae5bd-aed3-4541-93b4-692f94ef0193.mp4

### Here's proof it happens on normal maps too. (non-2B)

https://user-images.githubusercontent.com/62181440/224540630-658984a7-595d-45ab-8483-1a7e68218254.mp4

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu). If it hasn't, please report it as a bug on lazer and we'll see to it!

**Comment by Paladynee** [comment]
> Thanks for the suggestion.
> 
> As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu). If it hasn't, please report it as a bug on lazer and we'll see to it!

I'm currently rank 1 on the leaderboards of the map [XNOR XNOR XNOR by fanzhen0019](https://osu.ppy.sh/beatmapsets/1236927#osu/2573162) in the akatsuki private server and I'm close to getting the first FC on the map. But theres this one pattern in the map which forces you to experience this bug. It is super hard to pull off the workaround strat and renders the map basically unfcable.

Even if I switch to the lazer version of the game, the map is still very laggy and unplayable. The current state of lazer does not allow me to play the map at all. 

Based on your words
> Valid Reports:
> Things that affect your daily enjoyment of the game.

This bug absolutely annihilates my enjoyment of Relax. I know there aren't many Relax Aspire players but you guys are known for your compatibility towards the smallest of the audiences for lazer.

I insist you fix this issue, please. I'm hoping that you can fix this issue so that I can fully enjoy the game again. Thank you for your consideration.

**Comment by peppy** [comment]
Thanks for the explanation. We'll definitely examine it in lazer!
