### ISSUE TITLE
Hitsound sample playback volume is not limited

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-stable-issues#1108]
In some circumstances when third-party tools have been used to alter hitsounds, they set volume values far in excess of 100%, causing the client to produce an extremely loud sound. Anecdotes from users suggest [this change](https://osu.ppy.sh/home/changelog/stable40/20200104.8) may be responsible, but comments on the affected map samples listed below seem to predate this change.

This is prominent on the following maps:

https://osu.ppy.sh/beatmapsets/581729#mania/1231252, Ultimate difficulty (video: https://puu.sh/JC01H/29479bf3c7.mp4)
- 03:02:326 (182326|2)

https://osu.ppy.sh/beatmapsets/592272#mania/1260544, Lunatic difficulty (video: https://puu.sh/JC025/ec211eee92.mp4)
- 00:16:640 (16640|3) 
- 00:16:790 (16790|3)

**Comment by peppy** [comment]
This has been resolved in the last release.
