### ISSUE TITLE
repeated pausing and restarting of a beatmap causes the pause music to play in the background

### ISSUE THREAD

**Issue by SigmaTheFox** [ppy/osu-stable-issues#111]
An issue I keep experiencing is the pause menu music keeps looping in the background if I restart a map too quickly or too often. The sound keeps playing until I close the game.
Pausing while this issue is in effect causes the sound to stack

**Comment by aerouk** [comment]
As a temporary solution to save restarting the game every time, the sound can be stopped by reloading (ctrl+alt+shift+S) or changing the current skin

**Comment by smoogipoo** [comment]
If anyone can figure out an exact replication for this, that would be great. I've replicated it once during my normal play, but haven't been able to re-replicate while testing.

**Comment by smoogipoo** [comment]
I've potentially fixed this in the next cutting edge build, report back if it still happens.

**Comment by smoogipoo** [comment]
Reopening because I've managed to replicate on the latest cutting edge.

**Comment by SigmaTheFox** [comment]
I just found out that this sound issue still persists after pressing ctrl+alt+shift+S and/or changing current skin (it might not work for me because none of my skins have custom pause music).
And another thing about it, normally the pause music is supposed to fade out when tabbing out of osu, while this issue is in effect it'll still keep playing

**Comment by krsmll** [comment]
The only temporary fix that worked for me is restarting the game. It gets quite annoying after sometime so I really hope this gets more attention. The sound overlaps everything, including gameplay and main menu.

**Comment by Aergwyn** [comment]
Since last patch this happens to me at least once every play session. Have never experienced this bug before. Nothing but restarting seems to fix it.
I tend to retry pretty often which seems to be consistent with the other reports, no exact replication possible yet.

**Comment by SigmaTheFox** [comment]
one other way that fixes it from what I noticed it just restarting the beatmap another thousand times. I got so used to the pause sound looping even while playing that I don't even notice it anymore, but last time it happened, it also disappeared again after probably 20 plays/retries

**Comment by peppy** [comment]
Fixed in next cutting edge.
