### ISSUE TITLE
Error loading Storyboard in editor, some images cannot be loaded.

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#1113]
Beatmap Link: https://osu.ppy.sh/beatmapsets/1929270#osu/3984915
If played inside the gameplay, there will be no errors， storyboard can play.
But If use editor,sometimes it can be fully loaded, sometimes only partially loaded.
It now looks like a random event,  it should have a impact on beatmap audit work.
Like these pictures，cant load some images.
![QQ截图20230404022110](https://user-images.githubusercontent.com/26690346/229594567-5045f35c-8f20-4735-a091-4304338af0dd.jpg)

![QQ截图20230404021726](https://user-images.githubusercontent.com/26690346/229594554-5e651da5-f287-4074-9b39-49275a467e8d.jpg)

### If I use auto or play this map, that can play it.
![screenshot2243](https://user-images.githubusercontent.com/26690346/229596862-999a8ca4-9638-4ae7-b074-18be7dc024c5.png)
![screenshot2244](https://user-images.githubusercontent.com/26690346/229596903-f38700de-fbcb-4832-bfbc-9e22f442515f.png)

### sometimes it can be fully loaded
![screenshot2245](https://user-images.githubusercontent.com/26690346/229598612-3657aa70-2924-410f-ad9e-201c7e22a07a.png)
![screenshot2247](https://user-images.githubusercontent.com/26690346/229598632-978c0bd0-b163-47fd-bdb2-2bf0747b80c6.png)

### logs
[network.log](https://github.com/ppy/osu-stable-issues/files/11141307/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/11141308/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/11141309/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/11141310/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/11141311/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/11141312/update_success.log)

### Sometimes there may be crash. these are the logs from the crash.
[network.log](https://github.com/ppy/osu-stable-issues/files/11141315/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/11141316/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/11141317/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/11141318/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/11141319/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/11141320/update_success.log)

**Comment by peppy** [comment]
Posted on the wrong repository, but may as well just answer here:

Try not using numbers in the naming, it's probably recognising it as an animation sequence.

**Comment by wanjiaXG** [comment]
> Posted on the wrong repository, but may as well just answer here:
> 
> Try not using numbers in the naming, it's probably recognising it as an animation sequence.

I am replacing it with an alphabetical character file name and it will still appear，
This may have an impact on the auditing of certain Beatmaps，It is a random event。

**Comment by wanjiaXG** [comment]
> Posted on the wrong repository, but may as well just answer here:
> 
> Try not using numbers in the naming, it's probably recognising it as an animation sequence.

Using auto in the gameplay can fully load. I think this is an editor bug, unrelated to the file name.
