### ISSUE TITLE
Osu! makes my monitors black and then crash

### ISSUE THREAD

**Issue by maor727** [ppy/osu-stable-issues#1114]
When I play osu! and I minimize my 2 monitors turns black and then when I open osu again my game instantly crashes.

**Comment by maor727** [comment]
Another thing I noticed, when osu crashes, discord crash as well.

**Comment by peppy** [comment]
You're going to need to update your GPU drivers.

**Comment by maor727** [comment]
It didn't help. My osu and my discord still crashing

**Comment by Joehuu** [comment]
I suspect the discord overlay is causing this. Can you try disabling it for now and see if it fixes the crashes?

**Comment by maor727** [comment]
unfortunately it still crashes, I did disable discord overlay.

**Comment by maor727** [comment]
?
