### ISSUE TITLE
Editor object layering problems

### ISSUE THREAD

**Issue by tutis12** [ppy/osu-stable-issues#1115]
When copying objects they copy the z-value of and then sometimes appear not correctly, for example:

copying a circle (backward in time) will result in two circles having wrong z-values, either the same or wrong order.
![image](https://user-images.githubusercontent.com/22875209/232598471-7040fb20-ae2c-4108-922f-49374932f429.png)

When copying the slider sometimes the slider body decides to hide the slider head 
![image](https://user-images.githubusercontent.com/22875209/232598850-e457a490-e28a-4556-af8b-a3c16b4d2424.png)

Similarly, the slider ball also looks weird sometimes due to the same bug.

I think a good fix would be to recalculate the object z-value when copying or moving the object in the timeline. 

The current workaround is to save and reload: ctrl+s, ctrl+alt+l

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
