### ISSUE TITLE
osu! stable instant driver crash upon startup

### ISSUE THREAD

**Issue by BlackDiamond3180** [ppy/osu-stable-issues#1118]
I am running a 6700xt in my system and thus far the game has worked just fine (even without compatability mode) though as of today, for some reason it makes my drivers just completely die whenever I launch it. My screen goes black and loses any output from the gpu...

I can provide a video taken from my phone if need be, though I don't see that as much of a use at the moment...

**Comment by BlackDiamond3180** [comment]
Update: A fiew computer restarts later it no longers seems to crash upon launch...

**Comment by BlackDiamond3180** [comment]
Update v2: I have found that when I launch osu!Lazer first, play a fiew maps and then close it, launching osu classic is just fine..
When I just launch osu classic without lazer in prior then it just dies on me..

**Comment by peppy** [comment]
This is 100% going to be a driver or PC issue. I'm sorry but you're going to have to figure out what changed at your end.
