### ISSUE TITLE
Performance issue: consistent lag every 18-19s

### ISSUE THREAD

**Issue by Zoggoth** [ppy/osu-stable-issues#1119]
[Video](https://youtu.be/ysZcXYw40Ok)
The lag appears at 0:06, 0:25, 0:43, 1:02, 1:21, 1:39, 1:58 & 2:17. It is visible on the frame time
Video recorded with all other programs closed except OBS (recording). Problem persists even with OBS closed

The issue doesn't affect gameplay in most gamemodes, unless the lag frame happens to line up with an input
However, it's a big problem for catch, where the majority of time is spent moving, and it can easily mess up the spacing during a jump (standard with mouse may have a similar issue)
A full PC restart is an easy temporary fix, but because the issue mostly results in bad play (which I have been known to do on my own) I often assume it's me & continue to be affected by the issue until I notice it during a fast jump section (It is very visible at high speed)

Github is having trouble processing Performance.log, so I'll summarise:
Lots of random slow frames in menus (Doesn't matter)
75.00s in Play (I think this is the big one at 1:04, since that's the only one that's different & I haven't been able to replicate)
149.00s in Rank (Doesn't matter)
Tons of slow frames at 154s in Rank (I tabbed out to stop the recording, I'll get a better recording of this & make a separate issue because it's really uncomfortable to look at, even as someone without epilepsy)

None of the consistent 18-19s ones seem to be detected, but they're the only ones giving me trouble

**Comment by peppy** [comment]
Please attach the log. Describing in words is not too helpful.

**Comment by Zoggoth** [comment]
[performance.log](https://github.com/ppy/osu-stable-issues/files/11380186/performance.log)
Worked out why Github was having trouble, it was my fault

The point I was trying to make is that there isn't a log every 18 seconds or anything helpful like that

**Comment by peppy** [comment]
Hard to say from that log, but it looks like the issue is not within osu!. Something else on your system might be running every x seconds which is causing the latency.

Reading through https://osu.ppy.sh/help/wiki/Performance_Troubleshooting might be a good start.

**Comment by Zoggoth** [comment]
That's a shame, I was sure it was osu! because it's the only game with these issues I was aggressively closing everything else.
I guess osu!'s the only thing where I would actually _notice_ a few frame drops, and some sort of memory leak in another program does match up to the behaviour (going away after restarting & returning later)
The other thing I should check is the graphics card. I'm on a laptop, so it does have a "low power mode" (for when it's not plugged in) which does lower performance, but I don't know why it would leave & re-enter it so consistently (reaching 100%?)
If anyone has a similar issue, I'd be interested in knowing whether they're also on a laptop

**Comment by ItsJustSomeDude** [comment]
Do you have a periodically changing Desktop Background by chance?  I have seen in a case totally unrelated to osu! that certain programs would lag if the desktop background was setup to change.
