### ISSUE TITLE
[mania] the tab button isn't working properly in mania's editor.

### ISSUE THREAD

**Issue by FAMossu** [ppy/osu-stable-issues#112]
Usually it needs only 1 tap to change the view between the notes and the storyboarded hitsounds, but now it requires a brief moment of holding to actually switch between the view. But at the same time holding the Tab button would cause an insanely fast switching between the views, which is pretty frustrating to get the correct view that we want when we are doing checks with the storyboarded hitsounds.

**Comment by smoogipoo** [comment]
Probably related to https://github.com/ppy/osu-stable-issues/issues/108

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge build.
