### ISSUE TITLE
Bancho doesn't record PMs to offline users with spaces

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-stable-issues#1120]
When a message is sent to a Bancho-offline user, Bancho usually returns 401 (no such nick) but still forwards the message to osu-web for recording to database and display on osu-web/osu!lazer.

When the recipient's nickname contains spaces, Bancho still returns 401 but the forwarding process to osu-web fails. Given Bancho is handling the underscore->space conversion due to limitations of the IRC protocol, the issue is most likely on Bancho's end.

Reproduced over IRC with bancho.js

**Comment by peppy** [comment]
I've fixed this and will deploy sometime later this week or early next week.
