### ISSUE TITLE
Chat Commands Inconsistency

### ISSUE THREAD

**Issue by RoanH** [ppy/osu-stable-issues#1121]
Currently the [osu! wiki article on Chat Commands](https://osu.ppy.sh/wiki/en/Client/Interface/Chat_console#commands-list) lists 3 commands that are not reported by Bancho's `/help` command. These commands are `/part`, `/join` and `/msg [user] [msg]`.

Of these `/part` and `/join` work properly and should maybe be added to `/help`.

However, `/msg [user] [msg]` functions more like `/msg [user]`, resulting in e.g., the following for `/msg RockRoller Test`:
![image](https://user-images.githubusercontent.com/8530896/236487895-39f1cb14-f26d-49b9-9f49-96e303221394.png)
I could update the wiki by removing the `[msg]` argument, but this would make the command identical to `/chat [user]`, which seems unintended.

**Comment by peppy** [comment]
I don't foresee this being changed stable side. `chat` `query` and `msg` all work the same way (and don't send a message) so let's just update the wiki to match.
