### ISSUE TITLE
osu!mania special style and MR mod unintentionally mirrors S key

### ISSUE THREAD

**Issue by aryoadhi** [ppy/osu-stable-issues#1122]
An osu!mania map with special style layout enabled and using special style layout in gameplay will mirror the whole map (including S key) when using Mirror mod.

Screenshot 1: Normal map with left S key (original)

![screenshot917](https://user-images.githubusercontent.com/5029654/236675618-a64c1134-0103-4e3a-97c1-3afd788c529f.png)

Screenshot 2: Normal map with left S key and Mirror mod

![screenshot918](https://user-images.githubusercontent.com/5029654/236675627-2a090fe7-daf3-4d0c-8307-52d2b84c032b.png)

Screenshot 3: Normal map with right S key

![screenshot928](https://user-images.githubusercontent.com/5029654/236675645-b3c81a85-ab3d-4198-9919-ec7b057d4c54.png)

Screenshot 4: Normal map with right S key and Mirror mod

![screenshot929](https://user-images.githubusercontent.com/5029654/236675658-6bb85064-2680-40a1-8b3b-0142ff1bdcbf.png)

Expected result pattern-wise:
- Left S key (1) when mirrored should reproduce (4)
- Right S key (3) when mirrored should reproduce (2)

**Comment by WindowsMeosu** [comment]
"````An osu!mania map with special style layout enabled and using special style layout in gameplay will mirror the whole map ````"
Pretty sure mirror is meant to mirror the whole map regardless if special style is enabled... right?

**Comment by aryoadhi** [comment]
That, however, is an unintended result. On games with special key, mirror mod only mirrors non-special lanes order.

**Comment by aryoadhi** [comment]
I should have look at the existing posts (for some reason Github defaults to open cases). I guess we already concluded with not fixing it on stable as it's already feature-locked.

Read: https://github.com/ppy/osu-stable-issues/issues/912
