### ISSUE TITLE
osu! lagging/having frame drops when entering a discord stream.

### ISSUE THREAD

**Issue by Admant3x** [ppy/osu-stable-issues#1125]
As the title suggest when entering on a friend's streaming on Discord (while osu! is running) it starts to lag/having frame drops. Im getting annoyed about this because the frame drops happen randomly when you play, and it's frustrating because it counts some notes as missed due to the lag.
Now I don't know if it's a problem regarding the Discord's Rich Presence because I tried anything: reinstalling Windows, Discord and osu!, tried to update GPU, CPU, chipset drivers but it's still the same. Any idea? Let me know, thanks in advance.

**Comment by peppy** [comment]
Have you tried compatibility mode in osu?

**Comment by navidmafi** [comment]
Try toggling hardware acceleration in discord settings to see if it helps (not recommended, just for testing)

I'm not sure but maybe your GPU cannot handle hardware video decoding (discord) and graphics rendering (osu) at the same time?
If you are playing maps with video storyboards try disabling them temporarily to see if that affects anything? (Discord stream decode + osu video decode at high resolutions might be the cause?)

Also try ppy's suggestion
More info about your device would help!

**Comment by kirowaterxyz** [comment]
I have the same problem as yours I tried a lot of stuff as reinstalling Windows, Nvidia drivers & settings, giving pc full max optimization, and so on. Reducing dropped frames, and Detect performance issues also won't help when recording with obs if I good remember the frame drops also happen, with limiting fps to 1000 it was kinda playable but still NOT, and the frame drops still were but I'm gonna try the compatibility mode

**Comment by kirowaterxyz** [comment]
Okay so far no lags recorded only 1min with obs I'm going to record a longer video, and also later test am I still getting frame drops with my friend screen sharing and me

**Comment by kirowaterxyz** [comment]
okay no longer lags on the recording and while playing, also tested with the discord seems the compatibility mode helps will update if I'll get again frame drops, but yeah I no longer get lags
