### ISSUE TITLE
Osu Crashed and Clear .osu mapping file data while editing.

### ISSUE THREAD

**Issue by Mirageasuka** [ppy/osu-stable-issues#1126]
I have encounter this weird situation, after I save progress of the map by press CTRL+S in the editor, it crashed itself instantly with no error messages. But when I boot it back up it turns out that .osu mapping file data has been cleared.

I don't know what really happen and still confuse me for a bit. I have attach event viewer log.

[eventviewer log.txt](https://github.com/ppy/osu-stable-issues/files/11444625/eventviewer.log.txt)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/11444633/runtime.log)

**Comment by smoogipoo** [comment]
Unfortunately, there's nothing that we can do here as the error indicates that something has gone wrong with your system elsewhere - perhaps memory corruption or disk failure.

I suggest you run a chkdsk and the "Windows Memory Diagnostic" tool to check for errors in those parts.
