### ISSUE TITLE
Using osu Collections as playlist doesn't work well

### ISSUE THREAD

**Issue by leandiez** [ppy/osu-stable-issues#1129]
Hi devs,

I usually use osu! as music player using collections.

The issue is that when you select a song from, menu Jump To... -> Collections: (my colllection) the rest of the playlist doesn't keep in background. 

If I keep the same window active, the collection reproduces songs randomly inside the same collection. If I minimize the window or move to another screen, then player reproduce random songs from the entire list.

![image](https://github.com/ppy/osu-stable-issues/assets/8433725/3ee4f198-478f-41f2-8dd8-4677a692ce59)

![image](https://github.com/ppy/osu-stable-issues/assets/8433725/bb0da715-13be-4ec2-b87e-b3f2d8576b7b)

Thanks in advance!

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).

Specifically, osu! is not intended to be used as a music player in the first place. You may have better luck with lazer, where the playlist and music overlay features have been redesigned, but it's intentionally not a focus as we would prefer users listen to music using services specifically made for that.
