### ISSUE TITLE
Skin.ini version: 1 as default is outdated

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu-stable-issues#113]
When some people make a new skin without skin.ini or never known what "Version: x" (like line is empty) is it, need Version: 1 to latest (2.5) as default.

**Comment by peppy** [comment]
Unfortunately, changing the default would cause these old skins to potentially behave incorrectly. The skin template is currently listed at `Version: 2`, so updating that to the latest (2.7) may be a good start?

**Comment by Fatal3ty** [comment]
For old Skins need line "Version: 1" for worked correctly, but newer Skin would be nice latest as default (when "Version" line are missing in the skin.ini). Mostly people play no longer with old skins. I see some mixed skin from another player and ranking panel and some element designed for the Version: 2 (or newer) work incorrectly for default the "Version: 1".

And Beatmap Skins need Version: 1 (when don't ignore the map skin, mostly maps are old)

**Comment by peppy** [comment]
You should understand from what you just wrote why we can't correctly do what you want here. There's no way to discern if a skin is an "old" or "new".

And people not using old skins is not really a valid statement, since we *do* still want to support all skins made.

**Comment by peppy** [comment]
Template updated, thanks @ephemeralis.
