### ISSUE TITLE
Player stats in 4:3 get cut off by the osu cookie

### ISSUE THREAD

**Issue by gazecube** [ppy/osu-stable-issues#1130]
Back in around 2012-2013, when peppy first changed the song select to include a mode select option, he moved the player stats over to accommodate selection-mode.png. When selection-mode was phased out in mid 2013, I guess nobody decided to move it back. What I'm suggesting is as follows: Player stats stay the same in all resolutions, except for those that are 4:3, in which the stats move closer to the beatmap-options button. This shouldn't break skins, and, truthfully, it isn't very high on the "gripes list" that i have with the game, but it's a small QoL improvement that I feel should at least be considered.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
