### ISSUE TITLE
Songs sometimes fail to load (including freshly downloaded)

### ISSUE THREAD

**Issue by kiwec** [ppy/osu-stable-issues#1132]
Songs failed to load, and after downloading one from osu!direct, the song list got emptied...?

Full session recording below. Skip 1:30 for first song loading issue, skip to 2:30 for the song list bug.

https://www.youtube.com/watch?v=HG_5bd-acA8

It went back to normal after restarting. I have gotten it to happen again, and again it was after playing one song. I don't expect it to be reproducible easily; just putting it here for reference. osu! folder (including songs folder) is on main disk, which is an NVMe SSD if that matters.

**Comment by kiwec** [comment]
Game also crashes while playing/at song selection.

I had to change my pipewire config because updates broke it, posting it in case someone sees something obvious: https://gist.github.com/kiwec/ea3b0f42bec12d46ba587b298bf81808

**Comment by peppy** [comment]
I'm sorry but this sounds like you're using linux. We don't support this officially for stable.
