### ISSUE TITLE
About background image import issue

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#1134]
If I edit the .osu file and use "SB/BG/04-1.jpg", that can be loaded and used.
![QQ截图20230602110145](https://github.com/ppy/osu-stable-issues/assets/26690346/131cc91e-433d-426a-aecf-27e5d5f269e2)
But if I in desgin use "Background Image/Video" import this image, It will cause errors, Is there a reason why the BG file must be in the root directory？
![QQ截图20230602110258](https://github.com/ppy/osu-stable-issues/assets/26690346/afebf54c-9ff5-44ca-a34d-7a820f2c8d87)
![QQ截图20230602110313](https://github.com/ppy/osu-stable-issues/assets/26690346/26c00153-d884-4ee3-9d63-e916c400ffbc)

**Comment by peppy** [comment]
This seems like a limitation of the editor. If it works okay using `.osu` edits, then it's probably fine to do it that way.

**Comment by wanjiaXG** [comment]
> This seems like a limitation of the editor. If it works okay using `.osu` edits, then it's probably fine to do it that way.

I have modified several images in `.osu` file and they can all be loaded. I hope this prompt can be fixed in future versions. ;w;

**Comment by peppy** [comment]
I'll keep this issue open and take a look into it. If it's a simple fix I'll definitely fix it.

**Comment by wanjiaXG** [comment]
> I'll keep this issue open and take a look into it. If it's a simple fix I'll definitely fix it.

I noticed that this feature has been fixed in Cutting Edge. I would like to know how long it will take for testing to be applied to stable. If testing cannot be completed in the near future, I may need to place the images in SB in the root directory to pass rank review.

**Comment by peppy** [comment]
What? This doesn't affect ranking or anything. You already have a workaround. Use it please.

**Comment by wanjiaXG** [comment]
> What? This doesn't affect ranking or anything. You already have a workaround. Use it please.

ok, thank you.
