### ISSUE TITLE
Announce whenever new room mods are picked 

### ISSUE THREAD

**Issue by matte-ek** [ppy/osu-stable-issues#1138]
Basically having BanchoBot announce whenever new room mods are picked, as in `BanchoBot: Mods changed to <mods>`, as already done with for example beatmaps. 

The reason for this is there is no way (that I am aware of) to get a room's mods in "real-time", which make "auto host rotate" bots unable to correctly calculate star rating for example whenever double time is picked. This is then unfortunately abused by some players to play maps that would normally be out of a lobby's regulations.

Totally understand if this request is deemed out of scope/too complicated, then just close it.

**Comment by peppy** [comment]
I've added this in the next release.

**Comment by matte-ek** [comment]
For anyone stumbling across this issue in the future: this was unfortunately never deployed due to too many unexpected edge cases during testing that would have been too much of a hassle to fix.
