### ISSUE TITLE
Storyboard display different results in editor and Ingame.

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#1148]
Client Version: b20230814.3

In Editor:
![QQ截图20230818211604](https://github.com/ppy/osu-stable-issues/assets/26690346/83e1b848-a99c-481a-98dc-5e07005d74a8)

In Game:
![QQ截图20230818211541](https://github.com/ppy/osu-stable-issues/assets/26690346/5e8fa7f9-5354-43d2-a223-900a52f48868)

**Comment by peppy** [comment]
Could you explain what you are seeing as wrong?

**Comment by wanjiaXG** [comment]
> Could you explain what you are seeing as wrong?

It looks bright yellow in the editor, but it is pure white in the game.

Or you can see the comparison below.

In Editor:
![QQ截图20230818215302](https://github.com/ppy/osu-stable-issues/assets/26690346/9f2d1f09-e506-4506-93c9-1cf413698515)

In Game:
![QQ截图20230818215321](https://github.com/ppy/osu-stable-issues/assets/26690346/8a6a1986-45c2-437f-974f-0b75ec2e7a76)

**Comment by aryoadhi** [comment]
Since it's an additive rather than simply overlaying it, doesn't that mean a pure white with additive filter should also appear as pure white in SB editor?

**Comment by wanjiaXG** [comment]
> Since it's an additive rather than simply overlaying it, doesn't that mean a pure white with additive filter should also appear as pure white in SB editor?

Yes, it is obvious that the editor and gameplay use different color mixing methods separately.

**Comment by peppy** [comment]
Or one is dimmed more than the other? The yellows are completely different.

**Comment by wanjiaXG** [comment]
> Or one is dimmed more than the other? The yellows are completely different.

In the second comparison, it's quite clear that the layers beneath can be displayed in the editor, while in the gameplay, only pure white is shown.In the wiki, the explanation for this command is use of additive color blending, Interpreting it literally, I believe the representation in the gameplay is correct – pure white combined with any color should yield white. However, I cannot be certain about this since the wiki doesn't provide a formula for the algorithm.In the mentioned comparison, the editor only increases the brightness of the area where color is added, which is clearly different from the blending algorithm used in the gameplay.

**Comment by wanjiaXG** [comment]
> Or one is dimmed more than the other? The yellows are completely different.

![QQ截图20230819133233](https://github.com/ppy/osu-stable-issues/assets/26690346/e66f09b2-bd19-499f-b5d2-da6967e5c860)
![QQ截图20230819133451](https://github.com/ppy/osu-stable-issues/assets/26690346/6f507eea-28e1-4074-8b42-f8f8f521491b)

**Comment by peppy** [comment]
It's probably something to do with the background layer in the storyboard being the same as the actual background, so background dim is applied. check the colours of the background – in the editor they are dimmed, which is why the additive blend is not hitting pure white.

**Comment by wanjiaXG** [comment]
> It's probably something to do with the background layer in the storyboard being the same as the actual background, so background dim is applied. check the colours of the background – in the editor they are dimmed, which is why the additive blend is not hitting pure white.

I am unable to investigate the specific reason, I can only find that using the same code results in different results displayed on both sides of the editor and gameplay. I think it's a bug

**Comment by Walavouchey** [comment]
Storyboard dimming (both in-game and in the editor) works by dimming the colour of each sprite (and the background) separately, rather than dimming everything post-render.

There seems to be some confusion in this thread. This has everything to do with how additive blend mode behaves under the dimming implementation, nothing else.

The editor applies a 30% dim

![additive-blend-mode-with-dim](https://github.com/ppy/osu-stable-issues/assets/36758269/bd2051c4-f3a4-4799-a963-c22560d50c83)

**Comment by wanjiaXG** [comment]
> Storyboard dimming (both in-game and in the editor) works by dimming the colour of each sprite (and the background) separately, rather than dimming everything post-render.
> 
> There seems to be some confusion in this thread. This has everything to do with how additive blend mode behaves under the dimming implementation, nothing else.
> 
> The editor applies a 30% dim
> 
> ![additive-blend-mode-with-dim](https://user-images.githubusercontent.com/36758269/261797007-bd2051c4-f3a4-4799-a963-c22560d50c83.png)

This is too confusing for those who are not familiar with the dimming implementation mechanism in OSU. Now that I understand, thank you for your answer.

**Comment by wanjiaXG** [comment]
> It's probably something to do with the background layer in the storyboard being the same as the actual background, so background dim is applied. check the colours of the background – in the editor they are dimmed, which is why the additive blend is not hitting pure white.

If we don't modify the sprite dim and use a black layer at the top and modify the alpha value of this image to achieve this function, would it be better? I'm not sure about the specific modification difficulty and performance issues, even if the stable is not planned to be implemented, will the lazer fix this issue？

**Comment by peppy** [comment]
Background dim is a game concept. Please look it up.

It's not a bug.

If you need further help please consider the game forums.
