### ISSUE TITLE
Latest song starts anyways after entering on an empty search

### ISSUE THREAD

**Issue by SusieDroid** [ppy/osu-stable-issues#115]
Describe the bug:
Hi I'm new to this community and I really love the game. I noticed that after a search without results, the latest song starts anyways if I press enter. I don't know if it is a real issue or just a default action but it would be nice to catch the event and notify the user about their action. I only tried in solo mode. Thanks!

Screenshots or videos showing encountered issue:
![aa](https://user-images.githubusercontent.com/55773786/65650257-7c255300-dfe0-11e9-8c6a-31826552e6d1.gif)

osu!lazer version:
stable 20190924.2

**Comment by smoogipoo** [comment]
Intentional as stable doesn't have the knowledge of a non-selected beatmap. This was fixed in lazer.
