### ISSUE TITLE
Hitburst Particles don't always spew out when autoplay goes through a map

### ISSUE THREAD

**Issue by nagi-desuuu** [ppy/osu-stable-issues#1153]
Works with the default skin, for good measure.

https://github.com/ppy/osu-stable-issues/assets/75596775/a532acb5-b0da-477f-a3ea-f8b7061d1cac

https://github.com/ppy/osu-stable-issues/assets/75596775/208a750e-00de-4d3a-ba3c-5bcf95e87f66

https://github.com/ppy/osu-stable-issues/assets/75596775/09d62ed1-4ea0-4b99-b12e-8211ab9c14ee

**Comment by smoogipoo** [comment]
Can you provide the skin? Or a minimal reproduction?

**Comment by nagi-desuuu** [comment]
I made this quick and dirty [test skin.zip](https://github.com/ppy/osu-stable-issues/files/12545612/test.skin.zip) from whatever images I have lying around. Should probably have everything you need.
(particle300.png is the most prominent, being `hitlighting.png` from the default skin)

It's worth mentioning that in the videos that I've sent, my latency on the bottom-right corner is on a constant 17ms due to hardware black magic that I'd rather not dwell into.

**Comment by smoogipoo** [comment]
Unfortunately I still can't repro even with that skin. Could it be related to whatever "hardware black magic" you've got going on? Are you able to test without that?

**Comment by nagi-desuuu** [comment]
Now that I think about it, it might be my hardware black magic which turned out to be VSync capping my frames to 60 likely causing the animation skipping. (I only realized this now, cut me some slack.)
Thanks for the effort, though.

**Comment by peppy** [comment]
Will close this one for now, seems like a very edge case which we'll most definite have handled correctly in lazer!
