### ISSUE TITLE
Multiplayer/Tournament: one player changing team color will unready the whole room

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu-stable-issues#1157]
In TeamVS, when a player changes color, all the players in the room are forced to non-ready status, which is really troublesome.

Example:
4v4 time-size 8 matches usually involve a lot of roster rotations between maps, and player often joins at the end of the timer.
When player joins the room, there is a chance that he gets assigned the wrong color and that he will have to change color.
Thus, all other players will have to ready-up again, but since they are not attentive they don't notice immediately (also it doesn't help that it is very hard to see who is not ready in the player list in-game), it usually usually delays the start of the map.
When the match is reffed via IRC, the ref usually has no way of knowing if a non-ready players never clicked ready or if he was just "unready-ed" by the color-change.

Suggested fix:
- You simply do not unready all players when a player changes color, or at least not when a referee issued the color change.
- In bonus, it would be nice to save colors of players leaving the room to reassign the same color if joining again later.

**Comment by smoogipoo** [comment]
Only the player changing teams will be unreadied in the next bancho release.
