### ISSUE TITLE
Osu! freezes when tabbing or clicking out of the game

### ISSUE THREAD

**Issue by Kryomancer** [ppy/osu-stable-issues#1159]
I run osu! fullscreen on a two screen setup. Whenever I alt+tab or otheriwse click outside of the osu! window, osu! freezes. The sounds continue and from the sound effects I can determine the game is still running and menus remain usable, but the screen freezes until I restart the game. I haven't played osu! in almost a year so I can't really pinpoint an update that might have started this but I know previously it worked without issues on this same computer.

Things I have tried and didn't help:
- Turning pc of and on again
- Updating graphics drivers (Currently on 537.34)
- Updating Windows
- Disabling Discord overlay
- Disabling Geforce experience overlay
- Disabling Windows focus assist
- Disabling osu! fullscreen mode, though this causes the same freeze and the setting isn't saved. And it'd likely just be unplayble with the input delay anyways.
- Osu! renderer compatibility mode

osu! version: Stable 20230814.2 (latest)

Pc specs:
Intel Core i5-11400H
NVIDIA GeForce RTX 3050 Laptop (GA107M)
16 GB Ram
Windows 11 Home (22H2, 22621.2134)

[DxDiag output](https://gist.github.com/Kryomancer/f1911e9016ef9b9f1a7b54dfa27318e2)

**Comment by Kryomancer** [comment]
After replacing my second screen with another screen of same resolution, different manufacturere but identical specs, changing absolutely nothing else, I can no longer replicate the issue So I guess I there's nothing else to do but to close it. I'm well aware it makes no sense.

**Comment by Kryomancer** [comment]
After replacing my second screen with another screen of same resolution, different manufacturere but identical specs, changing absolutely nothing else, I can no longer replicate the issue So I guess I there's nothing else to do but to close it. I'm well aware it makes no sense.

**Comment by peppy** [comment]
Could you try lazer and confirm the issue doesn't reproduce there? These are the kinds of issues that can happen to individuals but are very high effort to fix on stable (as we'll usually break 10 other users' systems in the process).
