### ISSUE TITLE
Legacy API max_combo is null

### ISSUE THREAD

**Issue by wesley-221** [ppy/osu-stable-issues#1161]
When using the `/get_beatmaps` endpoint, the max_combo seems to be null for some maps, from what I've seen it only affects Graveyarded maps but it does not affect every single one. 

I've tried it with the following 2 maps, one older map and one newer map: 
- https://osu.ppy.sh/beatmapsets/176256#osu/424579
- https://osu.ppy.sh/beatmapsets/2052255#osu/4286383

The first one returns null and the second one does return the actual max combo.

**Comment by peppy** [comment]
Please see https://github.com/ppy/osu-web/issues/10566
