### ISSUE TITLE
sliderpoint skin elements cannot be animated

### ISSUE THREAD

**Issue by Nyanaro** [ppy/osu-stable-issues#1163]
The sliderpoint10 and sliderpoint30 judgements cannot be animated in skins, unlike other judgements which can be animated.

Could the sliderpoint10 and sliderpoint30 judgements have their properties changed so they could be animated by skins? I can't think of any issues this would cause. Thanks!

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. We could look at adding this in lazer.
