### ISSUE TITLE
Crash every time i lauch a song.

### ISSUE THREAD

**Issue by Bibou1494** [ppy/osu-stable-issues#1164]
Hello. i just have a problem and i don't like because now i can't play because when i start a song it's crash but I don't know why.
Here is my specs:
CPU: Intel(R) Atom(TM) CPU Z3735F@ 1.33GHz
GPU: Intel HD Graphics
RAM: 2,0 Gb DDR3
Storage: 32 Gb of internal storage NTFS with 8 Gb of external storage with SD card FAT32 slot.
osu! is stored in my sd card and i don't know why is crash when i'm playing. It's my skin?

**Comment by peppy** [comment]
Without some kind of logs we can't help you.

**Comment by Bibou1494** [comment]
Where I can found logs?

**Comment by peppy** [comment]
If you click "open osu folder" in settings, there should be a logs folder. Note that you should make the game crash and grab the logs before starting it again, else the crash details won't be in ther.

**Comment by Bibou1494** [comment]
Ok but its m'y skin because I change my skin and its work and i retry with it but I change the resolution to 1280x800 to 800x600 I think and its work.
