### ISSUE TITLE
Music being significantly quieter on some custom hitsounds (Audio Ducking)

### ISSUE THREAD

**Issue by Omekyu** [ppy/osu-stable-issues#1165]
This is an issue i noticed a few days ago, but it could have persisted longer than that. 
It's an effect commonly refered as "audio ducking", it's the process of automatically reducing the volume of a sound when another sound reaches a specific threshold. 
And this is exctly what happens, when the hitsounds are loud enough, the music volume goes down by a significant amount. The effect is much more noticable with "808-like" kickdrum custom hitsounds. An example beatmap where the effect is really noticable is [Rude Buster by Sylas](https://osu.ppy.sh/beatmapsets/1197216#osu/2493793), especially at the last two kiais, which both use lots of mentioned kicks as a hitnormal hitsounds. The vocals at [04:00:035](osu://edit/04:00:035) get quieter when there are bursts. A similar iffect, if not more prominent happens at the end.
Also, the effect gets stronger the louder the master volume is. You can easilly verify that by turning up the master volume to 100% and quieting down the windows volume, or as i did the volume knob on my headphones themselfs. 

I tried replicating this effect using different hardware and software, and the effect stayed consistent throughout. 
I tried ith with my main usb headphones, JBL Quantum 400 and their drivers (usind the JBL quantum engine) and i also tried using an external Sound Card (arturia minifuse 2) using both the JBLs with their audio jack port and another pair of headphones, the Sony MDR-7506. The effect was the same on all configurations i tested.

Some ather stuff that happened right before i noticed the effect:
I updated my OS to the Windows 11 "Moment 4" version, which introduces a new design for the audio mixer.
I started playing actively with custom hitsounds (the most likely reason i noticed if the effect was there all the time)
I installed a new PCIE expension card (most likely unrelated)

Again, I don't know how long this effect has been there, but I personally get very annoyed with is, since i can't enjoy the music properly. I have the option to disable custom hitsounds, which will greatly reduce the effect, since i use a skin with moderately soft hitsounds (JesusOmega Planets), buit the effect is still there, and niw that i noticed i can't unhear it, which really affects my enjoyment of the game.

What I suggest/wish for is at least an option to disable this effect in the options, if it's possible. I talked with a developer who knows a bit about software audio processing and they said it's an artifact from how audio gets processed in osu, and the effect has been there all the time, and it's not really possible to fix. If that is the case, I would as least ask for an implementation in lazer, to get the option to disable it there, again, if possible.  

Here are some other spesifications of my system since i wasn't able to test that effect on other systems:
Mainboard: TUF GAMING B550-PRO
Processor: AMD Ryzen 5 5600X
Graphics Card: 8GB Gigabyte GeForce RTX 3070
Memory: 24GB  3600 MHz

Please reach out to me if I need to provide any more information.

**Comment by peppy** [comment]
This is windows level. If you want to avoid it, please reduce game volume levels. It only happens when overall system volume increases beyond 1, and is done so to not audibly clip / distort audio.

If you set game volume to 50% the chance of you ever hitting this is slim. If this means you need to increase volume elsewhere (ie. on a hardware volume control) then that would be your best option.

**Comment by Omekyu** [comment]
alright, thanks for the fix! i did't know windows had a limiter built in
