### ISSUE TITLE
No audio / unable to play a beatmap

### ISSUE THREAD

**Issue by tarorororororo** [ppy/osu-stable-issues#1167]
No audio - the osu! logo in beatmap selection is pulsing at an insanely high bpm, not matching the currently playing song's BPM like it usually does. When starting a map, I hang there and am unable to begin playing. When in the editor, it also hangs at any point I scrub to, and the notes somewhat "shake" when I hit play. 
Here is a video of the issue: https://youtu.be/1-L99-eMKDM
(the background noise is my friend's stream I am watching and him talking.. Maybe this will help show that my audio on my PC is fine, this issue is just localized to my osu! - That song you are hearing him play is from his game that I am watching on his stream, not mine.)

I am on arch linux, using pipewire.

**Comment by peppy** [comment]
We can't help with linux issues sorry.
