### ISSUE TITLE
Mania HP regeneration breaking on maps with a lot of long notes

### ISSUE THREAD

**Issue by tailsdk** [ppy/osu-stable-issues#1169]
On maps with a lot of long notes HP will regenerate a lot slower than on maps without LNs and the same HP value.

As an example [here](https://drive.google.com/file/d/1av78E3Y7IFLJrhcG4AgLJ7lidOlYSyTK/view?usp=sharing) are four maps linked with both a version where the LNs are there and one with all the LNs made into regular notes for comparison. For comparison reasons they have all been changed to HP 9 since the bug scales with HP as well so it should be easier to see.

website links here as well:
1. https://osu.ppy.sh/beatmapsets/1617344#mania/3302254
2. https://osu.ppy.sh/beatmapsets/1449950#mania/2989030
3. https://osu.ppy.sh/beatmapsets/1848177#mania/3818593
4. https://osu.ppy.sh/beatmapsets/1982293#mania/4116682

An easy way to test it is going into the editor and losing all HP and then turning on auto. the map with LNs will take significantly longer get to full health. 

The cause of it other than being related to LN is unknown. However, something we did notice is that not all maps are impacted equally and applying score V2 mod will help a lot with the problem. So it it likely has something to do with LN combo in some way.

Edit: the bug only starts to occur on map 1 on HP 8.2 so its most likely a bug in health regen

**Comment by smoogipoo** [comment]
This will be fixed in the next release.
