### ISSUE TITLE
Japanese language will show 2 silver SS instead of 1

### ISSUE THREAD

**Issue by tyuii0107** [ppy/osu-stable-issues#117]
When using the client, switching to the Japanese language and sorting maps by rank achieved will result in 2 silver SS categories being displayed. 

So far it only works on the Jp language, Eng is fine.

![image](https://user-images.githubusercontent.com/40938763/65673326-35d20180-e07d-11e9-8d9a-64d226a25809.png)

**Comment by smoogipoo** [comment]
Has been fixed. You can force an update by deleting the `Localisation` directory, or wait for a new osu! build.
