### ISSUE TITLE
When fullscreen is on, tabbing onto the osu! window sets refreshrate to 60hz.

### ISSUE THREAD

**Issue by LittleLilyBun** [ppy/osu-stable-issues#1177]
When I have fullscreen on (windowed and borderless do not have this issue) tabbing onto the osu! window sets my refresh rate to 60hz, despite me having a 120hz display, and tabbing off sets it right back to 120hz. It doesn't matter what Frame limiter I use, I normally use VSync, but it happens with Optimal and Power saving options, too. The graphics settings in Windows itself is whats changing, but I don't have this issue with any other game, so it must be an issue with osu!.

If it helps, I'm using the latest version of Windows 11, and the latest version of osu! cutting edge.

**Comment by peppy** [comment]
Can you confirm that you don't have compatibility mode enabled?

**Comment by LittleLilyBun** [comment]
I do not have compatibility mode enabled.

**Comment by peppy** [comment]
Are you running a single display or more than one?

Are you updated to the latest drivers?

Could you please attach logs?

**Comment by LittleLilyBun** [comment]
I am using multiple displays, but even when the second display is unplugged, the issue still occurs.
I am using the latest drivers for everything, except BIOS, I'll update that and let you know if that fixes the issue, here are all the logs for now:

[network.log](https://github.com/ppy/osu-stable-issues/files/13296082/network.log)
[osu!auth.log](https://github.com/ppy/osu-stable-issues/files/13296083/osu.auth.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/13296085/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/13296086/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/13296087/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/13296089/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/13296091/update_success.log)

**Comment by LittleLilyBun** [comment]
Seems like updating my BIOS fixed the issue, thank you for the help!
