### ISSUE TITLE
Can't click manage collections' buttons

### ISSUE THREAD

**Issue by kawaemon** [ppy/osu-stable-issues#118]
Video: https://streamable.com/jrf6m

**Comment by Ganondorfosu** [comment]
Affects this menu too

![screenshot2004](https://user-images.githubusercontent.com/55597697/65722002-94ae6f80-e0ab-11e9-878a-55be949ced4c.jpg)

**Comment by kawaemon** [comment]
They seems to work in beta(checked 10 hours ago)

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.

**Comment by kawaemon** [comment]
Thank you!

**Comment by E223** [comment]
Seems like whatever was fixed here may have broken the media controls at the top right of the screen with the Jump To window?  I'm not sure if they were working when the entire window was broken, but they are currently unclickable.

**Comment by peppy** [comment]
Not sure if this worked before, but it's definitely not working now. Could you please open a new issue for this, as it may be unrelated.

**Comment by ThePooN** [comment]
Not sure how long back you mean by before - but if you mean ever, I've definitely used them a ton in the past, so they were working at some point.
