### ISSUE TITLE
scorebar-bg is overlapping everything

### ISSUE THREAD

**Issue by grindersky** [ppy/osu-stable-issues#1180]
Hi, I made a black-colored skin with a white background to make it playable, sadly I just tested it in stable and scorebar-bg makes it unplayable. It was my fault that I tested the skin in McOsu (I know, different game) and it looked good. Would it be somehow possible to make it layered under everything else instead of on top of everything? I understand if scorebar-bg being displayed as the top layer is intentional.
Here are screenshots of what I mean: https://imgur.com/a/wXOKIeF

I can also send the skin if needed.

**Comment by peppy** [comment]
We can't give skinning advice here, this place is for bug reports. There's skinning reference on the wiki so please read through that.
