### ISSUE TITLE
Pausing on top of a hit circle breaks the replay file

### ISSUE THREAD

**Issue by thekrowned** [ppy/osu-stable-issues#1182]
Step-by-step reproduction:
1. Play any beatmap
2. Move your cursor on top of a hitcircle
3. Pause, and then unpause the game
4. Click the orange circle to resume the gameplay
5. Click the hitcircle properly

After playing the map, watch the replay. The game will register the click on step 4 instead of ignoring it.

Here's the live demonstration:

https://github.com/ppy/osu-stable-issues/assets/151819685/613ae3b1-8d14-40bf-809d-a1b64f4577aa

I can't attach my replay file here, but it's downloadable [from the leaderboards](https://osu.ppy.sh/scores/osu/4541145842).

**Comment by smoogipoo** [comment]
This is a known issue that is difficult to fix and out of scope for osu!stable.
