### ISSUE TITLE
Chat messages not being properly removed after a silence/mute

### ISSUE THREAD

**Issue by CaptainBasculin** [ppy/osu-stable-issues#1183]
![resim](https://github.com/ppy/osu-stable-issues/assets/48386548/d1b36d3a-84ea-43e7-8050-77c0236f4319)

This user got silenced yet their texts didn't got removed from client. Typically on mutes the text the people sent are removed after their posts, but this user's texts didn't.

**Comment by peppy** [comment]
Sometimes it can fail due to the client not having the correct local metadata mappings for the user. It's very rare so won't be fixed on stable, but will be on lazer.
