### ISSUE TITLE
Bugged Score

### ISSUE THREAD

**Issue by YF7k** [ppy/osu-stable-issues#1185]
![image2](https://github.com/ppy/osu-stable-issues/assets/146726555/054554bd-8712-4626-a14d-0f713a3a00cf)
![image](https://github.com/ppy/osu-stable-issues/assets/146726555/e177d55f-9134-45e8-93ec-45a2cf294876)

score bug i found on that map

https://osu.ppy.sh/beatmapsets/1622189#mania/3318046
https://osu.ppy.sh/beatmapsets/1061287#osu/2231839

**Comment by peppy** [comment]
Thanks, these have been resolved.
