### ISSUE TITLE
Delete all visible maps not working

### ISSUE THREAD

**Issue by iexavl** [ppy/osu-stable-issues#1186]
I am trying to free up some space by deleting lower star maps via the "delete all visible maps" button. I tried first deleting all <3 star maps (which were about 4000) and the game crashed. After a couple of attempts I decided to try deleting less maps. That seemed to work but the osu folder size on disk remains unchanged. Is there a chance I am doing something wrong?

**Comment by peppy** [comment]
Deleting difficulties will not free up disk space. Individual difficulties are tiny. You will have to delete full sets to free up space.

**Comment by iexavl** [comment]
> Deleting difficulties will not free up disk space. Individual difficulties are tiny. You will have to delete full sets to free up space.

Is there a way to do this without deleting entire sets? I just want to delete every map that's less than 4.5 stars for example and if there is a map in that set that is >4.5* I don't want want to delete it

**Comment by peppy** [comment]
I don't think that is possible. Also most beatmaps have a spread with at least one difficulty over 4.5* so I don't think this would save you much space in the first place.

**Comment by iexavl** [comment]
> I don't think that is possible. Also most beatmaps have a spread with at least one difficulty over 4.5* so I don't think this would save you much space in the first place.

Ah.. its because of the actual audio and video files...right. Well thanks!
