### ISSUE TITLE
mania keybind menu doesn't remember the key mode

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-stable-issues#119]
`ManiaLayoutSelected#K` in config doesn't do anything, even though it's supposed to. I don't personally think this is a super useful feature but Millhiore discovered it was broken in #osu-wiki

clayton: @ MillhioreF do u know what ManiaLayoutSelected does ?
MillhioreF: it's supposed to remember the last key layout that was selected and bring it back next time the keybind manager is opened but it might be busted
clayton: looks like it, I tried setting one of them to 1 and it didn't do anything
clayton: .. and then it changed to -1 when i closed the game and still did nothing

**Comment by smoogipoo** [comment]
I suggest dropping this from the wiki if it is currently in there - it is not implemented in any capacity.

**Comment by cl8n** [comment]
in that case could you have the game not write it to the config file? I don't want to leave it undocumented if it's still there

**Comment by smoogipoo** [comment]
I'm against spending time making unimportant changes to stable.
