### ISSUE TITLE
/np messages coming from lazer are incorrectly formatted when they are received through the IRC gateway

### ISSUE THREAD

**Issue by omkelderman** [ppy/osu-stable-issues#1193]
This isnt exactly an issue with the stable client, but I wasnt sure where else to post this issue. Whatever component is responsible for forwarding messages coming from lazer to the irc gateway is not correctly formatting ACTION messages.

For more detailed info see https://github.com/Tillerino/Tillerinobot/issues/228#issuecomment-1866384083

Summary: the PRIVMSG message text should be formatted as `<0x01 byte>ACTION <the actual text><0x01 byte>` and with the messages coming from lazer the last 0x01 byte is skipped. Wireshark even gets angry about it.

**Comment by smoogipoo** [comment]
Will be fixed in the next bancho deploy.
