### ISSUE TITLE
Losing monitor signal after opening map in editor from song select and seemingly random black screens

### ISSUE THREAD

**Issue by krsmll** [ppy/osu-stable-issues#1195]
Newly bought monitor loses signal when opening editor from solo play song select. Here is demo of the issue:

https://github.com/ppy/osu-stable-issues/assets/57319032/ca7ef940-ba6f-498a-ad39-d01cdc9c4cae

No issues in other games or in desktop.
The monitor is Alienware AW2723DF and I use Acer B247Y as a secondary monitor. Both monitors plugged into RTX 4090.
AW2723DF running at 1440p 280hz.
B247Y running at 1080p 75hz.

What I tried and didn't work:
- Swapped DP cables
- Disabled Smart HDR in monitor settings
- Disabled G-SYNC in NVIDIA settings
- Updated graphics drivers
- Stable
- Turned on compatibility mode (it fixed the lost signal issue, however I started getting random black screens that last a second or two during gameplay)

**Comment by krsmll** [comment]
The issue is to do with Display Stream Compression. Disabling it and dropping down to 240hz fixes the issue however it means I am unable to push my hardware to the fullest potential. Again, none of the other games have this issue.

**Comment by peppy** [comment]
Unfortunately fixing something like this is out of scope. We've resolved the editor issue in lazer (by not using a windows native menu bar) so if that's an option, then you can consider it :).
