### ISSUE TITLE
DT pitches up to NC on this map. 

### ISSUE THREAD

**Issue by msmcculley** [ppy/osu-stable-issues#1198]
As posted here: https://osu.ppy.sh/community/forums/topics/1862194?n=1

When using DT on the New Beginnings (https://osu.ppy.sh/beatmapsets/1011011#osu/2116202) it will upscale the audio from normal to a NC audio pitch. It does not include the bass kick and extra sounds that NC does but it just switches the audio to NC. 

When using NC it doesn't switch to DT it stays NC.

**Comment by quat1024** [comment]
The voice is added with storyboarded samples, and this map has "samples match playback rate" enabled, which pitchshifts the samples instead of timestretching them. (It's always done that.)

**Comment by tsunyoku** [comment]
As correctly said above, this occurs due to the map having samples which match the playback rate. This does not lock the pitch, hence why it adjusts pitch.
