### ISSUE TITLE
A couple of issues to track

### ISSUE THREAD

**Issue by peppy** [ppy/osu-stable-issues#1199]
@tsunyoku could you check on these? may be related to difficulty calculation changes

https://osu.ppy.sh/community/forums/topics/1858347?n=1
https://osu.ppy.sh/community/forums/topics/1861171

**Comment by tsunyoku** [comment]
for the first link, relax has it's own calculations now which means it gets calculated like every other combo - issue with sorting by difficulty likely means that their maps haven't completed calculations yet. i've had quite a lot of people come to me with this exact issue and has always been solved as a "recalculation not complete" issue, so unless we have any more info from this user i will assume that is what's happening here.

for the second link, 0* is what SR will display as before calculations aren't complete. i've had some people say they had issues with the 0* count never going down, but after telling them to leave song select run for some time (~1 hour), they've noticed the count go down by an expected amount so i think it's an issue of the calculations just being slow..

for the sake of clarity, may it be better to push a build with some more logging regarding difficulty calculation? on release builds it returns 0* as star rating in failure cases, and we may benefit from extra logging here to distinguish the cases.

**Comment by peppy** [comment]
Rather than logging, I think something needs to show at song select to let users know that processing is ongoing, a counter of remaining items or something.

**Comment by tsunyoku** [comment]
received a report of an out of memory exception, which i think is potentially related to difficulty calculation. putting here for myself to track.

attaching exception (since it's taken from event viewer) and the user's runtime.log so that i can look into this later.

```
Application : osu!.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.OutOfMemoryException
   à #=zP9lQF3b2bBqlaDX1t3R$PxA=.#=zZqKUsdQ=()
   à #=zk2aOBjfJLEsyR9SLCpY03P0=+#=zNOOi_nW409yO6eiWpQ==.#=zFoOWegYE5byHc3g1ag==()
   à System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   à System.Threading.ThreadHelper.ThreadStart()
```

[runtime.log](https://github.com/ppy/osu-stable-issues/files/13842336/runtime.2.log)

**Comment by peppy** [comment]
I think these should be mostly fixed now.
