### ISSUE TITLE
Chattering first Korean chars while searching at map selection

### ISSUE THREAD

**Issue by mirusu400** [ppy/osu-stable-issues#12]
Here example:
https://www.youtube.com/watch?v=RbyXUGc-DqM&feature=youtu.be

When searching maps at map selection with Korean, first Korean chars chattering and type twice. I don't know it's about all Unicodes(Ex. Japanese or Chinese).

And also, `osu! lazor` completely not support searching in Korean.

**Comment by peppy** [comment]
This is likely going to be a complicated one. Wouldn't spend too long on it (IME is a black hole of effort). Also broken on lazer FWIW.

**Comment by peppy** [comment]
Fixed in next Cutting Edge build.
