### ISSUE TITLE
Stable and Lazer switch in stats

### ISSUE THREAD

**Issue by uunknown01** [ppy/osu-stable-issues#1200]
1- Switch in Accuracy:  Sometimes and out of nowhere, Lazer and stable overall accuracy keep swapping repeatedly, which I need to set a score to get back.
2- Stable scores gone from lazer: the scores from stable imported to lazer with the mod "Classic" are gone from lazer, which means my lazer profile got resetted in the process.

**Comment by peppy** [comment]
The statistics will be combined soon.
