### ISSUE TITLE
where my maps X(

### ISSUE THREAD

**Issue by Doshurakychek** [ppy/osu-stable-issues#1201]
Hello, today (January 1, 2024) I logged into osu and discovered that most of my maps were missing. there were more than 600 of them, but it was written that 185 were available. In the help it was written that if the osu version is new, write here. I updated the game just a couple of days ago. I also checked whether I could display cards from 0 to 10 plus stars and everything was fine with that.
also after the update, when entering the game, an error occurs as if there is no Internet, but I have excellent internet (photo).
text on the photo: failed to connect, we will try after 30 seconds.
please help me, I don’t know what to do and I don’t really want to lose progress and maps... :(
it was written using Yandex translator.
![Снимок экрана (2827)](https://github.com/ppy/osu-stable-issues/assets/155375334/c1a80dc0-7238-4a04-8173-e3a9085e9449)

**Comment by peppy** [comment]
Hit F5 at the song select screen a few imes.

**Comment by tsunyoku** [comment]
Closing as this seems to be a problem with the user's database file and not an issue which requires fixing.
