### ISSUE TITLE
weird approach circle stutter in the beginning of some maps is that normal?

### ISSUE THREAD

**Issue by DennisTunes** [ppy/osu-stable-issues#1203]
after the newest update 2 days ago or 3 on stable i get this weird micro stutter in the beginning of some maps even tho my fps is not even dipping  as if the approach circle skips a few frame it only happens on some maps not all of them whice is weird to me and i don't know if its me or the game. i already have tried repairing osu but it did not work
sorry to bother anyways i never really talked in communities in the first place

https://github.com/ppy/osu-stable-issues/assets/131561515/7d8a05c8-9c37-4f95-b82d-d0930c7ec3be

**Comment by peppy** [comment]
This can happen on beatmaps which start veyr close to the start of the audio track. It also looks like your universal offset is set quite high.

It could also happen if you changed your sound device.

But nothing in the update changed this.

**Comment by DennisTunes** [comment]
oh what i'm blind thank you peppy it was the offset
