### ISSUE TITLE
Relax changes map star rating

### ISSUE THREAD

**Issue by whatepa** [ppy/osu-stable-issues#1206]
Turning relax mod on lowers map start rating. Don't know if this is intended bahavior, if so, why doesn't autopilot lower sr aswell?

![nm](https://github.com/ppy/osu-stable-issues/assets/104326359/d38c8f36-5547-4b10-ad10-c6ebf3396de0)
![rx](https://github.com/ppy/osu-stable-issues/assets/104326359/f9be128b-5c64-4771-b0ed-251134a4f1d4)

**Comment by tsunyoku** [comment]
This is intended behaviour. Autopilot star rating will come in the future but this is a responsibility for the difficulty calculation system itself rather than osu!stable.
