### ISSUE TITLE
Pretty consistent memory leak/crashes after 20240120.1

### ISSUE THREAD

**Issue by quat1024** [ppy/osu-stable-issues#1208]
Hi. After updating to [20240120.1](https://osu.ppy.sh/home/changelog/stable40/20240120.1) I am experiencing significant and consistent lag spikes during the start of gameplay. The memory usage of the game starts climbing and when it hits about 2500mb the game crashes.

https://github.com/ppy/osu-stable-issues/assets/2068021/f21eae4b-ba0e-4d7b-8217-0e0b6e5267e5

I was able to get past the crash once (idk how, maybe i waited for a few minutes on song select). When I paused and pressed "Retry" without visiting song-select, the lag did not return. So I think it's related to difficulty-calculation, it might be choking on a weird map.

I played for an hour or so before updating to 20240120.1 and did not experience anything like this.

**Comment by peppy** [comment]
This isn't going to be directly related to the update. It probably means you have a very broken beatmap loaded though (which is basically processing forever). Check and remove any weird beatmaps (ie. those made to crash the game).

**Comment by quat1024** [comment]
Deleted XNOR XNOR XNOR and haven't had the problem again. This goddamn map
