### ISSUE TITLE
Please let taiko drumroll hits appear on hit error bar.

### ISSUE THREAD

**Issue by Gracidea16** [ppy/osu-stable-issues#121]
This is a thing, I wanted to request for a long time. Sometimes it's hard to see if you are hitting the drumroll too early or too late. Please implement this if it's not too much of a hustle.

**Comment by peppy** [comment]
Keep in mind this is not in lazer, so if added here it should be added there first (or at the same time).

**Comment by smoogipoo** [comment]
Closing for now - will be implemented in lazer.
