### ISSUE TITLE
What the "parallax" feature does and it adjusts my resolution tremendously?

### ISSUE THREAD

**Issue by NamOpt** [ppy/osu-stable-issues#1210]
What is turning this feature off and on for? To add more effects to my mouse pointer? I don't see much difference.

https://github.com/ppy/osu-stable-issues/assets/120299835/1f4ea18e-e373-4b26-949c-914e9259b39d

**Comment by cdwcgt** [comment]
check your background image, it will move based on your mouse position and this is not a problem, you should go #general channel in discord server
