### ISSUE TITLE
The number of remain beatmaps in Difficulty calculation is large than I have

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#1211]
![image](https://github.com/ppy/osu-stable-issues/assets/34775378/605805ec-63f4-42ad-9a24-9d1bf85df5c3)

25300 beatmaps remain.

![image](https://github.com/ppy/osu-stable-issues/assets/34775378/24784f1b-fa66-4e4d-bbd5-88e809441acd)
24113 beatmaps available.

Found a way to reproduce:
1. select a ruleset that need difficulty calculate
2. switch to another ruleset that difficulty calculate complete (not sure completely calculate is necessary), and the number of remain beatmaps in Difficulty calculation will stop change.
3. switch back to the ruleset in first step, and the number of remain beatmaps in Difficulty calculation will increase.
4. repeat 1-3

**Comment by peppy** [comment]
Yes. That's because it requires calculation per mode.

**Comment by cdwcgt** [comment]
This doesn't make sense, I feel like it calculated the mania beatmaps that needs to be calculated twice, because the difficulty of my std mode has already been calculated.

**Comment by peppy** [comment]
Trust in that it can't process the same beatmap twice based on how it's implemented. Even if it does happen to get queued twice, the processing will only run once.
