### ISSUE TITLE
Beta 20240120 difficulty calculation loads CPU to 100% during gameplay

### ISSUE THREAD

**Issue by Airkek** [ppy/osu-stable-issues#1212]
I think it's difficylty calculation. It slows down all my pc. It loads up to 100% even in gameplay:
![image](https://github.com/ppy/osu-stable-issues/assets/45855057/60727e37-8e23-4430-ae05-3f2d7fba307c)

I waited for 10 minutes in pause screen and got this:
![image](https://github.com/ppy/osu-stable-issues/assets/45855057/c1f85231-c5c6-4d07-9977-79267ea02b0a)

**Comment by peppy** [comment]
Thanks for the report. Will be fixed soon.
