### ISSUE TITLE
Difficulty calculation slows down the entire PC

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#1213]
My CPU usage goes to 100% causing the game and my entire system be very sluggish. Like cursor jumping when focused outside the game slow. At the very least I expected diff calc to pause while playing, but that doesn't seem to happen. I noticed it started happening yesterday.

Version: 20240119cuttingedge

System Specs:
- CPU: Intel Core i7-3770
- RAM: 32 GB
- GPU: AMD Radeon HD 7700
- OS: Windows 10

[runtime.log](https://github.com/ppy/osu-stable-issues/files/13999779/runtime.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/13999780/performance.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/13999782/session.log)

**Comment by peppy** [comment]
Thanks for the report. This will be resolved soon. Please switch to "stable" stream for now.
