### ISSUE TITLE
Difficulty Recalculation for broken maps restarts every time when entering song select

### ISSUE THREAD

**Issue by KabiPac** [ppy/osu-stable-issues#1214]
I have ~90 maps that seem to not recalculate properly. This isn't inherently an issue.

However, since the difficulty recalculation starts every time I re-enter song select, the game keeps trying to recalculate these maps. It takes ~20 seconds to (try to) recalculate all of them, but by then I will usually be in the next song already, which means effectively 100% of my time in song select is spent recalculating, which heavily impacts performance, even though theres no working maps left to recalculate.

The simplest way to solve this is probably to only try and re-calculate a map once per session, rather than every time song select is entered. However I'm not familiar with how the process works exactly, so I'm not sure how difficult that would be to implement.

(I also don't know which maps are failing in the calculation or how to find them, since the runtime.log and session.log file don't seem to contain that information.)

**Comment by tsunyoku** [comment]
Please switch to the Cutting Edge release stream and attach your `runtime.log` after spending some time in song select.

**Comment by KabiPac** [comment]
[runtime.log](https://github.com/ppy/osu-stable-issues/files/14042566/runtime.log)

Seems like the re-calculation errors stem from some Paths being too long

**Comment by tsunyoku** [comment]
You are correct. I'm not too sure what to suggest in this case; this blocks osu! from being able to process the beatmap. The beatmap IDs are yet to be discovered since it has to read them from the file, so they are all 0 at the point of calculation - this makes it basically impossible for me to track what beatmap is failing and prevent it from attempting to calculate again.

**Comment by KabiPac** [comment]
Ah yes that makes sense. If the map id cant even be found, then my proposed solution wouldnt work.

Guess ill just have to try and find the maps somehow and delete them.

**Comment by KabiPac** [comment]
I managed to fix the issue.
Turns out, when I downloaded a lot of unranked maps from a collection at some point, I just moved the whole folder into my songs folder. The game can mostly handle that without issues, but some maps with really long artist + song name ended up causing the error we saw in the log.
Just moving all the maps from the folder directly into the songs folder solved the issue.
