### ISSUE TITLE
fps drops on ryzen 5 3600 + nvidia

### ISSUE THREAD

**Issue by its0ka** [ppy/osu-stable-issues#1215]
fps drops from 2500 to ~100 and stays this way, it happens randomly during the game, cpu usage also drops at the same time.
![image](https://github.com/ppy/osu-stable-issues/assets/125186204/3d1661e9-7bf5-44d5-a22e-c3b16f485557) (cpu usage)
setting process affinity to CPU 2 and CPU 4 fixes the issue, multiple alt+tab also fix it and it doesn't seem to come back.
gpu driver is the latest

**Comment by peppy** [comment]
Probably throttling or something.

Not something we need an issue open for though.

**Comment by its0ka** [comment]
the comment above is shocking, I have no words. I was ready to test different drivers, settings, etc, but is there a point now? 25x performance hit is not something that needs an issue, really? can someone more adequate look in to this? 
"Probably throttling or something" if this means cpu thermal throttling then no.

**Comment by peppy** [comment]
Please see the readme:

> Examples of invalid reports:
> PC/hardware compatibility issues (ask for help on the [help forum](https://osu.ppy.sh/community/forums/5) instead)

This project is in maintenance mode and while we will fix compatibility issues, we only do so when they affect large numbers of users. And the fix is usually to contact the hardware vendor.

Thanks for understanding. Please do not ping people unnecessarily.

**Comment by PlavorSeol** [comment]
Why am I pinged?

**Comment by peppy** [comment]
Apologies to those pinged, the user above mass-pinged users.
