### ISSUE TITLE
Changing the circle size slider at cs7+ can crash the game

### ISSUE THREAD

**Issue by exylophone** [ppy/osu-stable-issues#1216]
If you modify the circle size slider to a decimal value above cs7 in the notepad file (e.g. cs7.5), then drag it such that osu tries to increment it to a higher integer (i.e. cs8 in this instance), game crash. This works with cs7.5-7.9, cs8.5-8.9 etc., not sure why it doesn't crash for cs7.1-7.4 etc.. Very low priority obviously, very few people will encounter this, but I felt it was worth reporting.

https://github.com/ppy/osu-stable-issues/assets/87776554/35c7a599-367c-41c0-b96e-508628492442

**Comment by peppy** [comment]
This is what happens when you edit files outsdie the editor. You're on your own at that point 🙃 .
