### ISSUE TITLE
Unable to connect to bancho

### ISSUE THREAD

**Issue by Crayshaw** [ppy/osu-stable-issues#1222]
Hello, i've re-installed windows, installed the **latest version of osu!** from homepage. but i can't login into my account getting an error saying "_Bancho connection failed: your copy of osu! is too old and needs to be updated before online play is possible_". i tried using the osu! updater but it says that the game is up-to-date, tried to re-install the game several times but i'm still getting the same error. please help!

**Comment by smoogipoo** [comment]
Do you have [test mode](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option#enable-or-disable-use-of-test-signed-code) enabled? If yes, please disable it to play online.

**Comment by Crayshaw** [comment]
> Do you have [test mode](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option#enable-or-disable-use-of-test-signed-code) enabled? If yes, please disable it to play online.

yes i do, but i can't run windows 10 without test mode enabled due to some drivers compatibiliy problems, is there is any way to play online while test mode is still enabled? because i've been trying to solve this problem with my drivers for almost 2 years and it seems that there is no solution.

**Comment by smoogipoo** [comment]
Can you provide more info about the driver/etc?

**Comment by Crayshaw** [comment]
the problem is that i'm still having very old hardware and the drivers for it are out-dated at windows 7, the wireless network driver and the graphics driver, the only way to install them is by enabling test mode and installing the windows 7 version of the network driver on windows 10, and for the graphics driver it's about using an edited version they made to work on windows 10 but it's impossible to make it work without test mode too.

**Comment by peppy** [comment]
Unfortunately we can't support this, sorry.

I'd recommend upgrading the components which are unsupported. You will likely face similar issues in other games, too.
