### ISSUE TITLE
Osu! crashes when adding a video to the beatmap [Osu!Stable]

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu-stable-issues#1223]
### Type

Crash to desktop

### Bug description

Title pretty much says it all.

### Screenshots or videos

[2024-02-23 22-45-52.webm](https://github.com/ppy/osu/assets/48768314/d871c120-0ec2-4617-b7f9-e969218cd961)

### Version

b20240123

### Logs

[Logs.zip](https://github.com/ppy/osu/files/14390411/Logs.zip)

**Comment by peppy** [comment]
Please try recompressing the video, it's probably broken.

**Comment by GamingWithJanko** [comment]
I'll try.

Even tho I'm quite certain, that a 2-pass ffmpeg run compresses it a lot, especially with q=20

Except if it can handle WEBM. Then imma use that instead. (The bug vid was made using an ffmpeg terminal) 

I only know about MP4 being supported.

I'll keep you posted.

**Comment by GamingWithJanko** [comment]
Problem can be closed. It's working as of rn.

If it breaks, I'll reopen this issue.

**Comment by wanjiaXG** [comment]
Compress the size of the video to 1280x720, with a bit rate preferably less than or equal to 1200k, and use CBR encoding to minimize the occurrence of bugs.

720p is also the current maximum limit for Ranked.
Specific restrictions can be referred to https://osu.ppy.sh/wiki/en/Ranking_criteria

The video background function of stable has always had bugs, and the triggering conditions are irregular, but there are ways to accelerate the triggering
The conditions for triggering acceleration are
1. There are a lot of local Maps, and the more you have, the easier it is to trigger.
2. The higher the resolution and bit rate of the video, the easier it is to trigger.

video bug can be referred to https://github.com/ppy/osu-stable-issues/issues/1197
