### ISSUE TITLE
Can add Instant Fade？

### ISSUE THREAD

**Issue by ghost** [ppy/osu-stable-issues#1225]
This feature currently only works in HD mode, but cannot work in other modes. In the current stable version, if the same effect needs to be achieved, the skin needs to be modified, but this method will make the hitobject lose its custom color. Of course, if this effect is a difficulty factor, then there is no other way.

About the skin implementation and explanation of Instant Fade.
https://skinship.xyz/guides/insta_fade_hc
https://www.youtube.com/watch?v=jk_tNBQ9lKA
https://github.com/clarks03/Osu-Instafade-Tool

If possible, I hope to add a switch to the stable to enable or disable this function.

**Comment by tsunyoku** [comment]
Stable is feature locked.
