### ISSUE TITLE
Seeing wrong game mode ranks in all game modes

### ISSUE THREAD

**Issue by frukoyurdakul** [ppy/osu-stable-issues#123]
### Version:

osu! Cutting Edge b20190926

### Issue explanation:

From what I've heard, this also happens on osu-stable as well so I think it's worth reporting it. Reference:

![image](https://user-images.githubusercontent.com/33460209/65790612-b15cad00-e168-11e9-950e-42d07352458e.png)

 I believe this issue is going on for a while (I'd say for at least 6 months), but when we pick another game mode such as Taiko or Mania, on random spots it switches showing wrong game mode ranking (I experience this a lot while switching back and forth between Taiko and Standard modes) which triggers the ranking change animation that is on the top-right side of the screen, or where the ranking is shown. I'm not entirely sure what specifically triggers it, but it mostly happens when I open the chat panel with F8 or F9.

In the image below, after triggering the bug somehow, it shows my standard ranking instead of Taiko (where my actual rank is 204 as of now), and automatically switches back after a while, or if I change game modes.

### Screenshot:

![image](https://user-images.githubusercontent.com/33460209/65789966-3050e600-e167-11e9-92dd-61c02f8d868a.png)

**Comment by peppy** [comment]
@frukoyurdakul does this generally happen at times when you are not manually changing the mode you're playing? i can't seem to reproduce it when manually switching (it very responsively switches between stats 100% of the time).

please let us know if you have any further information on reproduction.

**Comment by frukoyurdakul** [comment]
Yes, it seems to be happening after a while, not after a manual switch. Some time needs to pass, I don't know what triggers it exactly. It mostly happens while playing a beatmap or hang on at the main screen while chatting and looking for profiles.

**Comment by peppy** [comment]
Does it always switch backto osu!?

**Comment by frukoyurdakul** [comment]
In my case, yes. I have never seen it switching to catch or mania, just from taiko to osu.

**Comment by peppy** [comment]
Have you ever noticed bancho potentially disconnecting when this happens? Can you confirm that it isn't caused by a disconncetion?

**Comment by frukoyurdakul** [comment]
Yes, I can confirm, the issue is not related to disconnections. The bottom warning saying "Server is disconnected, reconnecting..." does not appear when this happens.

**Comment by WinterIsPretty** [comment]
This happens to me too, whenever I'm playing a different mode sometimes it changes my rank to my last mode I was on, which most of the time it is standard.

**Comment by peppy** [comment]
I'm 99% sure I fixed this at the bancho end. If anyone can still reproduce the issue please let me know.
