### ISSUE TITLE
Watching Lazer replays on Stable gives incorrect input for keystrokes

### ISSUE THREAD

**Issue by estrogenn** [ppy/osu-stable-issues#1231]
Searched and couldn't find this issue anywhere I also don't know where to put this (stable or Lazer) , I Played Diastrophism in Lazer then watched the replay in stable. Says I'm pressing mouse buttons, (I'm not they're disabled) throughout the replay.   

![IMG_2432](https://github.com/ppy/osu-stable-issues/assets/163699553/024956df-82ff-4f05-a7c3-b46bfff59d55)
![stable](https://github.com/ppy/osu-stable-issues/assets/163699553/baad9a6a-3b44-4ff2-aab1-7c3f2e3b7a0b)

**Comment by smoogipoo** [comment]
I don't think this is going to happen or be prioritised in the short term. This is just how lazer works - it doesn't distinctly handle mouse/keyboard keys for replays.
