### ISSUE TITLE
Hang when displaying a specific map's global leaderboard

### ISSUE THREAD

**Issue by bdach** [ppy/osu-stable-issues#1234]
Reporting on behalf of a discord user (original report here: https://discord.com/channels/188630481301012481/1097318920991559880/1235308957568860255).

When accessing the global leaderboard of https://osu.ppy.sh/beatmapsets/1670387#mania/3413460 the game will sometimes freeze. It doesn't happen every time but it should happen eventually. For me the hit rate is like 50%. If it doesn't happen the first time then exit out to main menu and go back to song select.

I see nothing in logs but maybe you can see more than me.

[osu!auth.log](https://github.com/ppy/osu-stable-issues/files/15180738/osu.auth.log)
[network.log](https://github.com/ppy/osu-stable-issues/files/15180739/network.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/15180740/update_success.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/15180741/runtime.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/15180743/performance.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/15180744/update.log)

I can also privately provide a memory dump taken at the moment of the crash if it helps.

Would have debugged more but I can't trigger the crash scenario on a debug reference build because it requires being able to log in.

**Comment by peppy** [comment]
Will be fixed in the next release!
