### ISSUE TITLE
Beatmap difficulty calculation is running on the background bug

### ISSUE THREAD

**Issue by Akurii7** [ppy/osu-stable-issues#1236]
this isn't specifically about the beatmap difficulty calculation as itself, you see, 2 days ago I updated my osu after almost 2 years of not playing online because my PC broke, and I had to wait until all of the calculations were done. I only have 16k maps and it took 27 whole hours until it got finished, it was 3 a.m. when I finally was able to play, and I did so, I only played one map and I closed osu, turned off my pc and went to sleep. Today I came home from school and I wanted to play osu, and I thought I was going to play calm and relaxed but now there's a bug, on the right top corner it says "difficulty calculation in progress (1 beatmaps remaining)" and it's stuck there, and it's extremely slow and it gets freezed around for 2 minutes or 1 minute when I try to switch a map, hell even the diffs of a map, and I don't know what to do. I only want to play peacefully but I can't because of this.
![image](https://github.com/ppy/osu-stable-issues/assets/170988947/3ac3e54e-1b33-4356-8bab-fe8abbfe38a1)

**Comment by tsunyoku** [comment]
Could you please attach logs?

**Comment by Akurii7** [comment]
how?

**Comment by Akurii7** [comment]
which logs specifically and how?

**Comment by Akurii7** [comment]
problem is solved, I deleted a image material map that was corrupted and now the problem is solved :)
