### ISSUE TITLE
Storyboards saved on "irregular" Decimal Symbols set on the computer breaks animation frame times.

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-stable-issues#1237]
This is a bit of a weird issue.
But the main bug is that when uploading a storyboard, frame-times on an animated sprite can save using the comma-decimal system instead of the period-decimal system from the operating system.

Map Example: https://osu.ppy.sh/beatmapsets/2126726#osu/4474872
Sprite example (before saving)
```
Animation,Background,Centre,"sb/light/fadein/.jpg",320,240,23,83.3333333333333,LoopOnce
 F,0,8793,,1
 F,0,10793,,0
 S,0,8793,,0.7619018
```

Sprite example (after saving):
```
Animation,Background,Centre,"sb\light\fadein\.jpg",320,240,23,83,3333333333333,LoopOnce
 F,0,8793,,1
 S,0,8793,,0.7619018
 F,0,10793,,0
```

note that `83.3333333333333` (12fps) is changed to `83,3333333333333` which breaks the sprite generation.

A reproduction has been recorded and can be viewed below (no audio, also uses `'` but same effect applies, decimal change at 0:56 and saving at 1:25),
https://github.com/ppy/osu-stable-issues/assets/37494321/c8c1cba4-6cd5-4503-85ff-b02e0ba54d26

**Comment by peppy** [comment]
Should be fixed in the next release, when that happens.
