### ISSUE TITLE
absolute positioning doesn't work on Osu! Stable

### ISSUE THREAD

**Issue by XReDoX** [ppy/osu-stable-issues#1239]
I wanted to report a problem that I still have, so when I play osu, absolute positioning doesn't work on my tablet, but when I run osu lazer! absolute positioning works normally. is there any way to fix it? If not, everything is fine, I like playing Osu Lazer
tablet: Huion h430p
(tablet drivers are downloaded)

**Comment by smoogipoo** [comment]
Stable doesn't have an integrated tablet driver like Lazer. You'll need to use an external driver, either from the manufacturer or [OpenTabletDriver](https://opentabletdriver.net).

If that still doesn't work then you may need to turn off Raw Input in settings.

**Comment by XReDoX** [comment]
> Stable doesn't have an integrated tablet driver like Lazer. You'll need to use an external driver, either from the manufacturer or [OpenTabletDriver](https://opentabletdriver.net).
> 
> If that still doesn't work then you may need to turn off Raw Input in settings.

I installed OpenTabletDriver and its working! Thank you!
