### ISSUE TITLE
Submitting a beatmap with multiple videos in a single difficulty deletes all but the last video

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-stable-issues#1240]
Would prevent: 
- Hybrid sets using different - gamemode-fitting videos (i.e. taiko / standard / mania, each with a video that takes into account the playfield differences)
- SB / Video hybrids where parts of the storyboard are accented through a video (my usecase in question)

replicating:
a `.osb` like this will cause only `vids/part2.avi` to be in the `.osz` downloaded 

```
[Events]
//Background and Video events
Video,8940,"vids/part1.avi"
Video,135929,"vids/part2.avi"
Video,201628,"vids/part2.avi"
```

local folder
![](https://puu.sh/K9qHo/b4d88a1bc9.png)
osz download:
![](https://puu.sh/K9qHL/0e10c8b411.png)

example:
https://osu.ppy.sh/beatmapsets/2195167#osu/4644543

example of this state:
https://drive.google.com/drive/folders/1IGYzCZAO5S5k5YOQBAw9atA8vl56k1r1?usp=sharing

Used to be possible (and playing the videos seems to work) in stuff like https://osu.ppy.sh/beatmapsets/29157#osu/156352

Just wanna know if this is known and a wontfix or if this is a bug
edit: i do not get a warning about unused files or anything when uploading this state. It's very counterintuitive

**Comment by peppy** [comment]
At what point does the video get deleted?

Also could you try using different filenames (not `part1` / `part2` ie. anything without a numeric sequence) just to rule that out?

**Comment by Okorin** [comment]
when you click "download with video" on the beatmap, the osz on the server will only contain the second video

edit: the game never informs you of this deletion, it just wont be there 

when you go through file->export package it works as expected 

what we tried
- different video formats (avi / mp4) between both parts 
- putting the video in a sub folder 
  - this just removed the subfolder from the `.osb` for some reason AND didn't upload the first video
  
will try non-numeric filenames sec

**Comment by Okorin** [comment]
using a non-numeric name deleted the second video now lol

```
[Events]
//Background and Video events
0,0,"bg.jpg",0,0
Video,8940,"opening.avi"
Video,135929,"ending.mp4"
Video,201628,"ending.mp4"
```
![](https://puu.sh/K9qY2/f5faf85581.png)

**Comment by Okorin** [comment]
tried to work around by having a video used as a sprite. this also doesn't work as uploading it _removes the video offset if they overlap for long enough for some reason?_

the video i tried this with:
https://drive.google.com/file/d/1C9Y2WiNsopbhlT3l-icMyICK5U564Grz/view?usp=drive_link

Before in the `.osu` uploading:
```
Video,8727,"video.avi"
 F,0,0,19114,0
 F,0,19114,96879,1
 F,0,96879,,0
Video,48027,"video.avi"
 F,0,0,141125,0
 F,0,141125,196097,1
 F,0,196097,,0
Video,173974,"video.avi"
 F,0,173974,238834,0
 F,0,238834,261795,1
 F,0,261795,,0
```
 after uploading
```
Video,0,"video.avi"
 F,0,0,19114,0
 F,0,19114,96879,1
 F,0,96879,,0
Video,0,"video.avi"
 F,0,0,141125,0
 F,0,141125,196097,1
 F,0,196097,,0
Video,173974,"video.avi"
 F,0,173974,238834,0
 F,0,238834,261795,1
 F,0,261795,,0
```

**Comment by Okorin** [comment]
we can work around it in this case by just making the entire experience into one bigger video but it may go over the 55mb upload limit for 5 minute songs (?) and is pretty wasteful

**Comment by Okorin** [comment]
adding another diff and starting the video blocks off with a `MY` command instead of `F` ... fixed this particular issue? I do not understand how or why though https://github.com/ppy/osu-stable-issues/issues/1240#issuecomment-2184230098

```
Video,8894,"video.avi"
 F,0,8894,19114,0
 F,0,19114,96879,1
 F,0,96879,,0
Video,48027,"video.avi"
 F,0,48027,141125,0
 MY,0,48027,141125,3000
 MY,0,70000,,0
 F,0,141125,196097,1
 F,0,196097,,0
Video,173974,"video.avi"
 F,0,173974,238834,0
 MY,0,173974,238834,3000
 MY,0,238834,,0
 F,0,238834,261795,1
 F,0,261795,,0
```

seems to be retained properly, performance of showing multiple videos at once notwithstanding...

## things i'm wondering for now: 

- is multiple videos deleting any other video but one intended
  - i couldn't consistently observe _which_ of the multiple videos gets deleted or why...
- putting the video in subfolders will edit the references to the videos so referring to `Video,173974,"vids/video.avi"` would become `Video,173974,"video.avi"` after upload, breaking the reference
- using the _same_ video as a storyboard element works, but the fadein seems to still be forced in a way a `F` command cannot get rid of, though you can just start playing it offscreen until the fadeout takes effect (which is super hacky)
- For some reason using the same video as a sb element while only having one difficulty seems to reset video offsets to `0`
- the client really doesn't like playing multiple videos at the same time, even if one of them is completely faded out (which is understandable and I think I should try optimizing the filesize of this video further)
  - this makes testing really difficult

**Comment by peppy** [comment]
i'd heavily recommend you avoid doing this in the first place. treading on new ground where stable doesn't support what you're doing is probably going to inhibit ranking.

**Comment by Okorin** [comment]
oh. none of what i did was technically declared unrankable. that's why i was doing it to begin with :D

There's https://osu.ppy.sh/beatmapsets/29157#osu/156352 with multiple videos ranked so I'm at least fairly certain at some point in some way, it was supported, which is why i made the issue in the first place

Edit:
Well and I made the issue because as far as I can see none of what I did in the beatmap is currently unrankable, but lots of behaviour is unexpected when dealing with it. I don't know if you remember what was and wasn't intended, but multiple things I ran into do seem more like bugs, hence the report here

Edit2
the game also supports _playing the videos_, uploading the set and including multiple videos or using videos as sprites also _works locally_ but uploading the beatmap messes with the main part involved inconsistently

**Comment by peppy** [comment]
> we can work around it in this case by just making the entire experience into one bigger video but it may go over the 55mb upload limit for 5 minute songs (?) and is pretty wasteful

if this is due to empty time between each video, try doing a two-pass encode. this will make the overhead for the "empty" sections negligible.

as for the loss of videos in the `.osu` file output i'm not sure i'll be fixing that since it seems to work in some cases for you. i'd recommend working around it for now and we'll make sure it works correctly in lazer (it should already, i've checked).

**Comment by Okorin** [comment]
> if this is due to empty time between each video, try doing a two-pass encode. this will make the overhead for the "empty" sections negligible.

since there was no movement on this i recreated the entire video by hand as a storyboard lol

> i'd recommend working around it for now and we'll make sure it works correctly in lazer (it should already, i've checked).

how'd you check BSS in lazer not deleting files when uploading a beatmap? I thought that whole thing didn't exist there yet 🙃 

and well the problem was that it inconsistently decides to delete multiple videos upon upload from both the `.osu` files and just from the folder with no warning to the user. I assume it just doesn't like having more than one video. 

I think it would still be worth looking into this as hybrid mode mapsets of like osu! and taiko specifically would prefer having different videos optimised around the default playfield placements of both gamemodes
