### ISSUE TITLE
Some beatmapset's leaderboard loading is not loaded

### ISSUE THREAD

**Issue by Sitoria** [ppy/osu-stable-issues#1241]
BSID 1 and BSID 93 cant load its ranking info
![image](https://github.com/ppy/osu-stable-issues/assets/85770829/fc4723e9-b2d6-40ba-a2ea-04d0d548915c)
![image](https://github.com/ppy/osu-stable-issues/assets/85770829/a8b22e57-613b-4674-b40e-103b0be666be)
BSID 1 can load ranking when it re download on web

**Comment by Sitoria** [comment]
just asked @civilwiki (civil oath, GMT) - can u load that mapset then he said no too

**Comment by peppy** [comment]
While "Shichiten Hakki" doesn't work, "Disco Prince" works fine for me, could you please double check @Sitoria?

**Comment by peppy** [comment]
I've applied a fix for https://osu.ppy.sh/beatmapsets/93#osu/209.

Please confirm that everything is okay now.

**Comment by Sitoria** [comment]
thx for the fix, BSID 1 can load when it redownload on web.
i'll check on tomorrow
