### ISSUE TITLE
Game crashes if you try to enable kiai mode on the editor for wine users

### ISSUE THREAD

**Issue by Jinkku** [ppy/osu-stable-issues#1242]
Affects:
all the objects you didn't save yet before clicking that button
Can't open the editor if that is ticked (can vary,it can or just crashes the game entirely)

How to reproduce it:
Go to the editor
click on a map that have timings with kiai mode enabled
click on the timing that have kiai mode enabled
then it crashes with no logs identifying about this even happening and there will be no Segfaults messages from wine

used wine 8.x to run osu!stable
OS: OpenSuse Tumbleweed (up-to-date)

**Comment by peppy** [comment]
Can you reproduce the crash without wine? If not then we can't help sorry.

**Comment by Jinkku** [comment]
Yep it only happens in wine, guess I have to avoid that button for now ;>
