### ISSUE TITLE
Bug where beatmaps get deleted automatically 

### ISSUE THREAD

**Issue by Mr1celandd** [ppy/osu-stable-issues#1244]
i have no idea if its a hardware or software issue. it only occurs on the normal client not lazer and when it happens entire artist collections like xi and imperial circus dead decade get deleted from the client. And the Artists that are getting deleted are those at the end of the alphabet

**Comment by tsunyoku** [comment]
Can you try pressing F5 in song select to reprocess all of your beatmaps and see if it helps?

**Comment by Mr1celandd** [comment]
> Can you try pressing F5 in song select to reprocess all of your beatmaps and see if it helps?

It fixed the problem thank you
