### ISSUE TITLE
Custom intros made by skin not working

### ISSUE THREAD

**Issue by UniqueName12345** [ppy/osu-stable-issues#1245]
Yeah, I have nothing else to explain here. I only tested two osu!stable versions, b20210520.2 and the current stable version as of writing this comment. In the former version, custom intros were working, in the latter version, custom intros are NOT.

**Comment by peppy** [comment]
Are you a supporter?

**Comment by UniqueName12345** [comment]
> Are you a supporter?

ooooh yeah that might be it actually
