### ISSUE TITLE
Playfield Background is useless

### ISSUE THREAD

**Issue by celerih** [ppy/osu-stable-issues#125]
This option hasn't changed anything in the game for like, idk a good 6 years at least at this point, as the game now uses default bgs when there's no bg for a map.
![](https://celerih.s-ul.eu/ESUNp8HD.png)

Should probably be removed

**Comment by peppy** [comment]
I don't think this is worth changing at this point. It can still be used in cases the background is not present, anyway.

**Comment by dorothy3242** [comment]
It is not used when the background is not present, the main menu background image is. It used to be the background color would tint the default background, but that has not been the case in years. 

Background Colour presently does zip, nada, zero.

**Comment by peppy** [comment]
Aha, I see.

**Comment by Coppertine** [comment]
plus, it gives an instant crash to the parser to the .osu file once you do change the value
![image](https://user-images.githubusercontent.com/37494321/66645486-ec7dd680-ec66-11e9-99ae-60204ac3f06f.png)
