### ISSUE TITLE
Objects count not showing properly

### ISSUE THREAD

**Issue by Yoth999** [ppy/osu-stable-issues#1251]
When there's too much object on a beatmap the value doesn't show correctly.
![image](https://github.com/user-attachments/assets/8a197ad4-9bc4-4121-b655-8f6232b66bcf)

For example in this beatmap, the object count is 114,027 but the circles and sliders combined only have 48,491 objects.
the issue is probably value exceeding the ushort value cap so the bits flip over and start at 0 again.

This issue also happened in the results screen with the count of marvelous too (only tested this issue in mania, assumed other modes also have this issue)
![image](https://github.com/user-attachments/assets/be1468cf-3492-4239-9a81-8952797ceeff)
![image](https://github.com/user-attachments/assets/edf25beb-2265-4d33-b914-6943891150c0)

**Comment by smoogipoo** [comment]
Known. Won't be fixed.
