### ISSUE TITLE
tourney Custom fps issue

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu-stable-issues#1252]
Now osu! tourney will be limited to 60fps, but some live streams already support 120fps (in fact, for example catch or mania, 120fps is a big improvement), Could consider adding a setting item like `CustomFrameLimit` to `tournament.cfg` ? Give users the freedom to set fps, default is 60fps, instead of forcing a lock 60 fps
![a4c15222-d9c1-4098-a05d-fed02785dc38](https://github.com/user-attachments/assets/2e5a18da-63c4-4442-be5a-322a3ec36e8d)

**Comment by peppy** [comment]
I've made this change on cutting edge. Please give it a try.

**Comment by mas-alone** [comment]
seems not working
![QQ20240826-085900](https://github.com/user-attachments/assets/79b1e80e-6e98-4718-97eb-8ba049f89352)

**Comment by mas-alone** [comment]
> I've made this change on cutting edge. Please give it a try.

seems not working
![QQ20240826-085900](https://github.com/user-attachments/assets/79b1e80e-6e98-4718-97eb-8ba049f89352)

**Comment by mas-alone** [comment]
Here is my `tournament.cfg`
```
TeamSize = 1
Height = 720
Aspect = 1
privateserver = 
ClientNameSize = 45
ContactTime = 10000
BufferTotalTime = 3000
BufferDangerTime = 1000
BufferTimeoutTime = 20000
RankingChatDelay = 8000
acronym = 4CWC
MinimalDraw = 0
StartupDelay = 0
CustomFrameLimit = 120
```

here is the `osu!.<username>.cfg`
```
CustomFrameLimit = 120
FrameSync = Custom
```

**Comment by peppy** [comment]
I can see why it isn't working. Another build should arrive momentarily to fix this.

**Comment by mas-alone** [comment]
> I can see why it isn't working. Another build should arrive momentarily to fix this.

😭still not working.
tourney default is still (Custom 60fps), like as the fps overlay shows.
Only when I set it to `Vsync` can I get my screen refresh rate (240 fps)
![微信截图_20240826140919](https://github.com/user-attachments/assets/1936e15f-005b-4422-9c18-37571c424882)
![微信截图_20240826140928](https://github.com/user-attachments/assets/52bbe9eb-5b8d-4ff1-9b59-baac2d4db1dc)

**Comment by peppy** [comment]
I think the remaining issue is that it's only applying to the main client, not the individual tournament clients.

**Comment by mas-alone** [comment]
> I think the remaining issue is that it's only applying to the main client, not the individual tournament clients.

yes!  only applying to main client
![微信截图_20240826141735](https://github.com/user-attachments/assets/4a9063d1-db40-4781-8997-4265ea7401ba)

**Comment by peppy** [comment]
I've pushed another build, please test again.

**Comment by mas-alone** [comment]
ty ppy! it working, have a nice day.

> I've pushed another build, please test again.

ty ppy! it working, have a nice day <3
