### ISSUE TITLE
osu! turns monitor dim while using HDR in full screen mode

### ISSUE THREAD

**Issue by LuNa-2424** [ppy/osu-stable-issues#1258]
In fullscreen mode when I launch osu! it causes the whole screen to dim by about 50%. this only happens while it's in fullscreen mode or has compatibility mode turned off

**Comment by smoogipoo** [comment]
osu! doesn't and won't support HDR especially under opengl (compatibility off).

**Comment by peppy** [comment]
If you need a way to quickly toggle HDR, you can set a keyboard shortcut for this in windows game bar settings.
