### ISSUE TITLE
Stats display at results screen appears to show pp increase relative to highest score play, not highest pp play

### ISSUE THREAD

**Issue by bdach** [ppy/osu-stable-issues#1259]
Reported at https://discord.com/channels/188630481301012481/1097318920991559880/1301527520600002612, logging here for posterity. Have not verified claim or looked at code, but it makes sense that this could happen after preserving more than one score per beatmap/mods/user combination.

Scores involved, for reference (were set in succession as far as I can tell):

- https://osu.ppy.sh/scores/3774047614 (67pp, 4,276,950 total)
- https://osu.ppy.sh/scores/3774072737 (81pp, 3,248,160 total => +14pp, -1,028,790 score relative to first)
- https://osu.ppy.sh/scores/3774098698 (78pp, 5,075,962 total => +11pp, +799,012 score relative to first, but -3pp relative to second)

Could be called as "working as intended", but also as misleading. Not sure.

**Comment by bdach** [comment]
More screenshots corroborating this provided by user in https://discord.com/channels/188630481301012481/1097318920991559880/1301538758201704569 on another map (mirroring so that they don't disappear in depths of discord cdn purges):

First score:
![screenshot558](https://github.com/user-attachments/assets/57ec595c-25b5-4773-b530-743d826b38ba)

Second score:
![screenshot560](https://github.com/user-attachments/assets/ee10dac3-cae1-4877-a6b9-19cc438ff60a)

Third score:
![screenshot563](https://github.com/user-attachments/assets/173b28e3-06d9-4263-bd33-1a188a92f6bb)

Local leaderboard after all three:
![image](https://github.com/user-attachments/assets/38d87deb-b6af-4590-b1bc-fa4c1c493c48)

**Comment by peppy** [comment]
Yeah this sounds like it will need some adjustment in web-10 code.

I'll look at this tomorrow, in theory it should be a very easy fix.
