### ISSUE TITLE
I can't open the options menu from pressed Shift+O when i spectate the people

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu-stable-issues#126]
I can't open the options menu from press Shift+O when i spectate the people. When i play the map with autoplay mod, pressed Shift+O worked fine. 

![screenshot10874](https://user-images.githubusercontent.com/53025167/65819924-e88f9480-e222-11e9-86da-a00153f4e046.png)

**Comment by peppy** [comment]
Ctrl-O is the key. It only works in certain places (intentionally). If it doesn't work with replay, there's a reason for it.

**Comment by Fatal3ty** [comment]
Oops, i mean CTRL + O, is my typo sorry.
