### ISSUE TITLE
Option to only show filename instead of full path when file fails to save in editor

### ISSUE THREAD

**Issue by TheFantasticLoki** [ppy/osu-stable-issues#1261]
So I was watching a streamer do some mapping and it would always fail to save on the first attempt, this reveals the filepath which unfortunately due to windows saving parts of names as the user folder name can dox parts or even full names on stream if they are short enough.

So I propose a toggle in the options menu to only show the file name since you can assume it's in the song folder if it ends in .osu in order to avoid this issue while also preventing streamers from needing to cover up parts of the screen at all times.

Note: Please don't hate me if this is a duplicate issue, Github search can suck my *.

**Comment by tsunyoku** [comment]
An option for this seems really unnecessary. If any of the other devs feel strongly about making a change to *only* display filename instead then that's fine, but overall I think this isn't really necessary.

**Comment by peppy** [comment]
> An option for this seems really unnecessary. If any of the other devs feel strongly about making a change to *only* display filename instead then that's fine, but overall I think this isn't really necessary.

changing to show relative path is fine if low effort.

**Comment by TheFantasticLoki** [comment]
> > An option for this seems really unnecessary. If any of the other devs feel strongly about making a change to _only_ display filename instead then that's fine, but overall I think this isn't really necessary.
> 
> changing to show relative path is fine if low effort.

Doesn't need to be high effort, I and many others just want something to block this by default cause we do think it's very concerning especially with how resourceful people can be when they are trying to dox someone online.

**Comment by tsunyoku** [comment]
Should be fixed in the next release.
