### ISSUE TITLE
Certificate has seemingly expired.

### ISSUE THREAD

**Issue by gazecube** [ppy/osu-stable-issues#1265]
Not sure how nobody caught this, but the signing certificate that's used to sign the exe (both installer and game client itself) seems to be expired as of 11/1/2024 and 10/23/2024 respectively, which makes the game refuse to launch with the error "System.Exception: Unsigned executable!" on my system.

OS: Windows Vista SP2 with all updates installed.

**Comment by peppy** [comment]
No certificates have expired.

Your operating system is too old to handle newer code signing. You will need to update to something that is supported. Remaining on Vista in this day and age is a huge security risk.
