### ISSUE TITLE
Add "!mp checktimer" command to see the remaining time on an !mp timer

### ISSUE THREAD

**Issue by DigitalHypno** [ppy/osu-stable-issues#1268]
Creating a separate thread for part of what I mentioned in https://github.com/ppy/osu/discussions/31002.

This sort of command would be useful during tournament matches when players want to check how much time is left before they need to pick the next map or enter the lobby after a map is picked, especially when they weren't in the lobby when the timer was made.

Common example scenario: The enemy team just picked a map, and the referee starts a 2-minute timer for you to get your players in the lobby. Your team goes into solo to try the map and decide who should play it (VERY common occurrence). Your teammates ask you how much time is left in the timer. You join the lobby to check, but instead of being able to check instantly, you have to wait for BanchoBot to send an update in chat. Adding a command to check how much time is remaining in a timer would be a huge QoL upgrade for tournament teams, and would be a transferable feature to osu!lazer if/when it supports !mp commands.

The command does not need to be named "checktimer", just whatever makes the most sense.

**Comment by peppy** [comment]
Added in the next release.
