### ISSUE TITLE
Ctrl+A anables Auto when there are already multiple ways of enabling it

### ISSUE THREAD

**Issue by naochan117** [ppy/osu-stable-issues#127]
As the title suggests, ctrl+a enables the auto mod when this is already doable by either ctrl clicking the map or manually enabling the mod. 

It would be much more useful for ctrl+a to highlight all text in the search field rather than being an unnecessary third way to enable a mod which isn't even used that often

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
