### ISSUE TITLE
Tacky christmas slop makes the welcome screen take ages

### ISSUE THREAD

**Issue by hurrrrdurrrr** [ppy/osu-stable-issues#1270]
"welcome" screen takes 7 seconds and is unskippable, where as it's normally skippable after a second or so.

**Comment by peppy** [comment]
Have a great christmas! This will be reverted after christmas ends.

**Comment by hurrrrdurrrr** [comment]
>5+ days of an unskippable blank screen everytime I launch the game

Grinch behavior.
