### ISSUE TITLE
[Editor mania] AiMod still says more than 6 Notes are not allowed 

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#128]
The AiMod in the osu!mania Editor still says that more than 6 notes simultaneously are not allowed. We had recently an Ranking Criteria change which allows exactly this.

RC Thread: https://osu.ppy.sh/community/forums/topics/915024

**Comment by Coppertine** [comment]
Just making sure it's only for Insane and lower diffs btw.

**Comment by peppy** [comment]
Fixed in next cutting edge.
