### ISSUE TITLE
Delete Yahoo! and MSN Messenger integration options

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-stable-issues#129]
both messengers are dead, so there's no reason to keep those options available in the game

---

**Comment by Joehuu** [comment]
- StreamCompanion uses MSN.
- For Rainmeter, you can use the MSN setting for `PlayerName=WLM` of NowPlaying to get Title/Artist.

TL;DR: This will break third party apps that use these settings.

**Comment by smoogipoo** [comment]
Proper IPC integration for those purposes would be preferable, but that is out of scope.
