### ISSUE TITLE
Scores made in multiplayer not recorded to local leaderboard

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#130]
This is a recent bug after updating osu!.

**Comment by smoogipoo** [comment]
Failed scores?

**Comment by abraker95** [comment]
Oh they were indeed failed scores. Never saw failed scores being recorded in multi as a bug, and actually became part of my regular experience. So it was weird when this happened.

**Comment by smoogipoo** [comment]
Yeah, this is intentional. They can still be saved if you press F2.

**Comment by abraker95** [comment]
I just got one that is not a failed score

![](https://osu.ppy.sh/ss/14097767/201b)

![](https://osu.ppy.sh/ss/14097771/3415)

**Comment by peppy** [comment]
Reopening for further investigation.

**Comment by qcl12345** [comment]
Might be the same as https://github.com/ppy/osu-stable-issues/issues/175?

**Comment by smoogipoo** [comment]
Indeed it is.

**Comment by peppy** [comment]
Should be resolved in cutting edge.
