### ISSUE TITLE
Copypasting too much items in the editor then scrolling back in the timeline crashes osu!

### ISSUE THREAD

**Issue by recognitionmark** [ppy/osu-stable-issues#132]
Ok, so this is an **EDITOR** issue. Once I tried making a map, it ended up impossible, and because I copypasted them too much and trying to scroll the timeline, osu crashed. Sorry if I could not provide logs, I was writing this on mobile.

**Comment by peppy** [comment]
Please reopen with crash log (click pippi on crash screen then copy and paste).
