### ISSUE TITLE
Comma in difficulty names causes incorrect display in the osu!direct menu

### ISSUE THREAD

**Issue by waefwerf** [ppy/osu-stable-issues#133]
When hovering over the game-mode icons in osu!direct, the corresponding difficulty name and star rating is shown. However, when there is a comma in the difficulty name, two bubbles are shown with the first one being abruptly cut off at the point of the comma.

Bug showcased here:
https://imgur.com/a/lUKas4c

**Comment by smoogipoo** [comment]
This may require a fix that is out of scope for stable.

**Comment by peppy** [comment]
I've fixed this one server-side. It will take around 12 hours to apply (pending index updates to the search backend).
