### ISSUE TITLE
Cutting Edge Replay Speed hotkeys return NC back to NoMod

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#134]
Not a major issue, but when using the replay speed hotkeys, when watching a replay with DT, changing the replay speed, then pressing 0/6 to go back to the original speed returns the replay to DT speed (which is the intended action I assume), while with NC, it returns it to NoMod

Shown here - https://streamable.com/mvicj

**Comment by smoogipoo** [comment]
May be an involved fix / out of scope.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
