### ISSUE TITLE
Audio samples played at wrong volume for a split second

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-stable-issues#138]
When playing with a low volume (say, 5%), audio samples like hitsounds will play at full volume for a split second before going down to the configured volume on the first play, before playing at the right volume for all subsequent plays.

Seems related to #124 

Edit: After looking at the videos posted in issue 124, it appears that it's not quite the same issue

**Comment by peppy** [comment]
Does this only happen to the first hitsound in the beatmap? Can you make a video showing this?

**Comment by Jeremiidesu** [comment]
I'll make a video whenever I can. (most likely over the weekend)

The issue occurs on the first time a given hitsound is played, for each different hitsound.

So if the map I'm playing uses 3 different hitsounds that the game has never played before (e.g. first time I'm playing the map after starting the game), I can expect up to 3 volume spikes early in the map

I'd assume it only happens on low performance devices, but I can't say for sure at this point

**Comment by peppy** [comment]
Please reopen if you can provide a video of this happening.
