### ISSUE TITLE
Add option to hide placement in free-for-all multiplayer lobbies

### ISSUE THREAD

**Issue by TheToaphster** [ppy/osu-stable-issues#139]
Not really an issue persay, but in playing free-for-all multis, especially for 1v1 tournament matches, the 1st/2nd/etc place in the background (at least for mania and especially when your placement changes) is distracting and can cause unnecessary nerves. A setting to hide just that would be very appreciated.

**Comment by smoogipoo** [comment]
We discussed this when the interface hiding functionality was implemented, and the decision is it was intentional for the placement not to hide. Has your opinion changed these days @peppy ?

**Comment by peppy** [comment]
Does the scoreboard already hide? If so, that would mean zero elements would be present to show it's a multiplayer game. In which case I'm strongly against this.

**Comment by smoogipoo** [comment]
Yup, in which case I'll mark this as intended.
