### ISSUE TITLE
Option to opt-out of Discord Rich Presence

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-stable-issues#140]
I feel like some people may not want to display their detailed osu! status in Discord all the time, especially those who use the game as a music player. Would be great to make this an option

**Comment by peppy** [comment]
can you not just disable at discord's end?

**Comment by Jeremiidesu** [comment]
You can do that but that's disabling for all games, not just osu!

Say, if you play another game detected by Discord, osu!'s (or any game's) rich presence will take over the "simple detection" game you're playing

**Comment by camellirite** [comment]
if you use osu! as a music player it'll always say either idle or afk

if you're complaining about the "for x minutes," its got nothing to do with rich presence and you'll just have to turn off app detection across the board

**Comment by Jeremiidesu** [comment]
I'm specifically referring to the rich presence overriding other currently focused games, due to the way Discord works with it

"Rich presence" here being your name, mode, rank, afk... as you mentioned.

**Comment by nl-tatatat** [comment]
can't you just delete the presence.db file?

**Comment by smoogipoo** [comment]
presence.db has nothing to do with rich presence.

**Comment by nl-tatatat** [comment]
dang

**Comment by smoogipoo** [comment]
Fixed in the latest cutting edge.
