### ISSUE TITLE
Object count overflow at 65k objects

### ISSUE THREAD

**Issue by Hydria** [ppy/osu-stable-issues#141]
![RW70pdN](https://user-images.githubusercontent.com/13346079/66080555-36c3d100-e55e-11e9-8603-d6df1174b8fc.png)
can be a potential issue with very long marathon mania maps (we already have a 40,000 note map in loved)

**Comment by peppy** [comment]
Probably out of scope.

**Comment by peppy** [comment]
Also would need fixes in replays, and potentially server-side.

**Comment by peppy** [comment]
Closing as out of scope. Lazer should already have fixed the base issue; server-side there will be many places to fix if this is to be supported.
