### ISSUE TITLE
Tournament client does not update ipc.txt everytime

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu-stable-issues#143]
Sometimes stable does not write beatmapID into ipc.txt file so Lazer doesn't catch the needed information.

**Comment by peppy** [comment]
This probably means your client has not actually *found* a beatmap ID for the beatmap. The best way to fix this is to preload the beatmaps into the client and go into song select, make sure you can see scores.

**Comment by l3lackShark** [comment]
Yep, that helped, thanks for the explanation.
