### ISSUE TITLE
Mania multiplayer matches end prematurely if last note is a long note

### ISSUE THREAD

**Issue by ElectroYan** [ppy/osu-stable-issues#144]
When the last note is a rather long long note the game starts to show "Waiting for all players to finish" while you're still holding it and also ends the match before you're able to properly release it. This causes the score to not submit.

**Comment by peppy** [comment]
Could you please link a beatmap that you saw this happen on?

**Comment by ElectroYan** [comment]
This map:
https://osu.ppy.sh/beatmapsets/884441#mania/1848678
Screenshot showing it didn't get submitted:
https://i.imgur.com/3v0UDid.jpg

**Comment by ElectroYan** [comment]
Additionally you can see the combo being about 100 lower

**Comment by peppy** [comment]
Fixed in next cutting edge build!
