### ISSUE TITLE
Random Crashes / Stutters (Seemingly After Recent Windows Update)

### ISSUE THREAD

**Issue by Karthyz** [ppy/osu-stable-issues#146]
https://twitter.com/topkaku/status/1180038201236320256?s=20

This tweet shows it happening, also happens to me every few maps. Happens on both stable and cutting edge. Frametime gets a massive spike (and the cpu usage blocks spike also). Haven't noticed the issue in any other game. Running an 8th gen i7 and GTX1060.

**Comment by smoogipoo** [comment]
Nothing can be done without the logs from this run at the very minimum. With that being said it is 100% some process running on their PC that is consuming tons of resources, and they should be monitoring their task manager for any instantaneous disk usage or CPU spikes from another process.

**Comment by Karthyz** [comment]
Where could I find the log that this would be in? As I said this also happens to me and I've heard it from others also. Seems unlikely we would all have the same problematic process running and it all springing up since a recent Windows update.

**Comment by smoogipoo** [comment]
You can click the button in settings that says “open osu! folder” and there’s a logs directory in there. If it’s not a task then it’s most likely a consequence of running the game at unlimited fps overloading the gpu.

**Comment by Karthyz** [comment]
If it were GPU overloarding wouldn't you expect it to be constant? I've had the GPU overloading from unlimited FPS before and this seems very different. I'll drop logs next time I catch it happening though.

**Comment by smoogipoo** [comment]
Hard to say how consistent they would be. Just drop all the logs.

**Comment by peppy** [comment]
Make sure to run on cutting edge to generate performance logs.

**Comment by peppy** [comment]
And make sure to not run unlimited fps.

**Comment by peppy** [comment]
Closing due to lack of information. Please reopen if you capture performance logs.
