### ISSUE TITLE
Failscreen with shaders on shouldn't flash to black when displaying "retry" and "quit" buttons

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu-stable-issues#148]
Currently failscreen will start fading to red after you fail, then instantly go back to black when displaying the buttons and then fail-background.jpg starts fading in. Instead of this, the red should either stay or fade out smoothly.

**Comment by peppy** [comment]
Can't be fixed due to stable architecture (shaders are applied game-wide).
