### ISSUE TITLE
Collections show as empty after database corruption

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-stable-issues#149]
When osu!.db gets corrupt and after the database has rebuilt itself, collections all show as empty. However, as the collections are left untouched by the user, the collections.db file is not erased and is parsed correctly after restarting the game.

Step-by-step video guide on how to reproduce: https://youtu.be/d9BZOEIyQKw

Despite the existence of a workaround, this issue is very important as most players believe their collections are all gone before trying to restart the game. I've seen many people, unaware of the workaround, rebuild their entire collections from zero because of this bug.  
This bug likely exists since the introduction of collections.

Reprocessing beatmaps with F5 does not trigger this bug. It seems the maps need to be not present in the database when osu! starts for this bug to be triggered.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
