### ISSUE TITLE
osu!direct still links forums

### ISSUE THREAD

**Issue by celerih** [ppy/osu-stable-issues#15]
with the changes to the modding system of maps, in editor the web option for opening threads was changed to open the beatmap's modding page 
![](https://celerih.s-ul.eu/PrYd0a65.png)

This change was not done to osu!direct which still sends you to the now unusable and locked forum threads of maps
![](https://celerih.s-ul.eu/mrRswSVW.png)

**Comment by celerih** [comment]
Additionally would be nice to implement it like the website deals with the Discussion button where on maps that it is appropriate it still links to forum while on nower v2 maps it goes to the v2 panel

**Comment by peppy** [comment]
Fixed in next Cutting Edge build.
