### ISSUE TITLE
Local offset on all difficulties of a given mapset is reset by creating a new one

### ISSUE THREAD

**Issue by nautzz** [ppy/osu-stable-issues#150]
To reproduce: Set a local offset on any difficulty in any mapset, then create a new difficulty for it and save it.

Hopefully an easy fix.

Edit: I forgot to mention the reason why this would cause anyone trouble; it's whenever you need to make a practice difficulty for a map that needs an offset.

**Comment by peppy** [comment]
Unsupported behaviour / out of scope.
