### ISSUE TITLE
Beatmap database still getting corrupted after update b20191006.1

### ISSUE THREAD

**Issue by maia011** [ppy/osu-stable-issues#151]
![Untitled](https://user-images.githubusercontent.com/56280235/66369831-471be780-e974-11e9-9207-74ffca513f29.png)
2 days after the update I'm still getting this message, which forces me to refresh my beatmap list, as well as making me lose all my collections and local scores.
Release stream: Stable
OS: Windows 7 Ultimate SP1

**Comment by smoogipoo** [comment]
Thanks. Provided databases are in: https://github.com/ppy/osu-stable-issues/issues/60#issuecomment-539273938.

This is going to take a lot more investigation and we're holding off on spending too much time on it for now. If others can replicate on b20191006 or later and post their databases in here, that would be great.

I've looked through the databases provided and it seems like the written count of beatmaps differs from the the number of beatmaps actually written to the file. This indicates that the write wasn't properly flushed but this happened on a beatmap boundary and no excess bytes were written. Very weird.

**Comment by Ocklepod** [comment]
I had the same corrupt database issue twice this week already, here is all the .db and db.bak files i found in my osu folder
https://puu.sh/EriPY.rar

**Comment by smoogipoo** [comment]
This may be fixed in the next cutting edge (not released yet). I'll keep this issue open for now but please report back if it still occurs.

**Comment by peppy** [comment]
Closing this for now as I believe we've solved every possible cause of this. Please reopen if you manage to reproduce.
