### ISSUE TITLE
Team VS fail causes other players to be kicked

### ISSUE THREAD

**Issue by peppy** [ppy/osu-stable-issues#152]
Transferring this report from my todo list:

>Okay so, short backstory as to how we even encountered this problem. I'm a tournament host and I've been hosting a variety of different osu! tournaments for the past almost 3 years. Anyway, my oldest and still ongoing tournament is the Rapid Monthly osu! Tournament (RMoT). It's a 1v1 tournament that uses slightly easier maps than you would usually find in the same rank range, because we use Team VS. This means that as soon as one of the players fail the map, the game kicks both players out of the map and back into the lobby. At least, that's what it should do. In the last few months (2 or so months, I know for a fact it's been present for at least the last 2 tournaments), a bug appeared. It doesn't happen all the time, but sometimes when one of the players fail the map, it instead only kicks out the player that didn't fail, kicking them back into the lobby. Meanwhile, the player that failed the map just doesn't fail and gets to continue the map until they eventually either fail again or finish the map. This bug is a serious detriment to our tournament and we'd like to see it fixed. 
>
>I only have 1 multiplayer link showing this right now, but this has not been a one time thing. We haven't gone and tested what exactly causes it, but it's a thing. Check the amount of hits on the third map and you can clearly see there's a problem here. 
>https://osu.ppy.sh/community/matches/53311601 
>
>Hopefully this gets fixed before the next installment. Thank you.

**Comment by huupoke12** [comment]
Is this bug same as https://github.com/ppy/osu-stable-issues/issues/7?

**Comment by peppy** [comment]
Ah yes, that's correct.
