### ISSUE TITLE
Stutters in replays will trigger a miss even when it's an FC

### ISSUE THREAD

**Issue by tyuii0107** [ppy/osu-stable-issues#153]
It dosen't happen often so I can't really get a screenshot/ replay or when it will happen. But sometimes when viewing replays, the client lags up and the replay will show a miss (hitsounds, combo reset) even when viewing a replay of an FC.

Small issue, but for people who record videos, it can be a tad bit tiring to re-shoot the video.

**Comment by peppy** [comment]
Not within the scope of fixability, sorry. Please consider using lazer for recording videos.
