### ISSUE TITLE
Slider tick issues in taiko

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#155]
There are two main issues with slider tick rate in taiko. 
first is that at 125bpm or lower, drumrolls place drum roll ticks every 1/8th tick, instead of the usual 1/4th tick. This makes drumrolls undesirable at these bpms, since they don't represent the slow tempo of <125bpm. A fix to this should only apply to all future beatmaps.

The second issue is that only slider tick rate 1 and 3 have any gameplay affects in taiko. Slider tickrate 1 is the default tick rate, while slider tick rate 3 snaps all drumroll ticks to 1/6. Having other slider tick rates such as 0.5 and 2 would be greatly useful. 0.5 would half the amount of ticks (as expected), and 2 would double the amount of ticks(as expected). These tick rates are already functional in other gamemodes. Why not taiko too?

**Comment by smoogipoo** [comment]
We did try to use the tick rate for ScoreV2 at one point, and most people disliked it. That's why for ScoreV2 it only uses 1/3 for tickrate=3 and 1/4 otherwise. This is something which we'll consider changing for lazer, but it's pretty out of scope for stable.

**Comment by nl-tatatat** [comment]
"We did try to use the tick rate for ScoreV2 at one point, and most people disliked it. " players disliked it? Well if slider tick rate affected sliders for ALL previously created beatmaps too, that would go against what the mapper intended. 

What about the 125bpm issue? Somewhat unrelated to the slider tick rate issue, but still valid imo.

**Comment by smoogipoo** [comment]
That's still related to scorev1, which we're not touching. Doesn't exist on scorev2.
