### ISSUE TITLE
Large stutters every few minutes

### ISSUE THREAD

**Issue by potato4444** [ppy/osu-stable-issues#156]
Here is [a video showing off at least one of these stutters](https://streamable.com/ufqb8), the stutter happens at around 1:38.

[performance.log](https://github.com/ppy/osu-stable-issues/files/3712562/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/3712564/runtime.log)
[network.log](https://github.com/ppy/osu-stable-issues/files/3712565/network.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/3712566/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/3712567/update_success.log)

The video corresponds to the last play in performance.log.

I don't think this is https://github.com/ppy/osu-stable-issues/issues/146 because I have been having these stutters for years, not just recently, and am not running Windows.

I am running osu! through Wine on linux, but have had these stutters when I used to run osu! on Windows 2-ish years ago as well.

**Comment by peppy** [comment]
Your performance logs show the stutter to be at `SwapBuffers`. This means it could be:

- Your graphics drivers.
- Something else on your PC blocking your GPU pipeline.
- Your hardware.
