### ISSUE TITLE
Wrong "report an issue..." link on crash window

### ISSUE THREAD

**Issue by E223** [ppy/osu-stable-issues#157]
The "report an issue..." button at the bottom of the osu! crashed window still links to the old forum's create topic page.  Since that has been disabled and there is no redirect in place it just leads to a blank page.

It should probably link to https://osu.ppy.sh/community/forums/topics/create?forum_id=5 instead.

**Comment by smoogipoo** [comment]
maybe should even link here.

**Comment by peppy** [comment]
Fixed via osu-web-10 fallback rules.
