### ISSUE TITLE
AiMod is still breaking sliders

### ISSUE THREAD

**Issue by lassem22** [ppy/osu-stable-issues#158]
this was supposedly fixed in https://github.com/ppy/osu-stable-issues/issues/6 but I can still reproduce it on both stable and cutting edge (b20191007)

stable: https://streamable.com/7o59m
ce: https://streamable.com/o9too
map: https://lasse.s-ul.eu/fWR4basQ.osz ("test" difficulty is before, "bug" difficulty after)

how to reproduce: 
- have a slider that gets moved due to autostacking, for example https://i.imgur.com/vzt9zEz.jpg (or multiple)
- make any change to the map without saving
- open aimod
- press "refresh"
=> each time you press refresh there will be an additional diagonal grey node added to all sliders that get moved due to autostacking
once: https://i.imgur.com/AzCDBcn.jpg
twice: https://i.imgur.com/N8WJzAa.jpg

upon saving and reloading the map you will then get things like https://i.imgur.com/DwwZpUn.jpg

**Comment by lassem22** [comment]
thought it might be an issue related to the view -> stacking option: https://i.imgur.com/7UpQyxI.jpg 
but it occurs regardless of it being enabled or not

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
