### ISSUE TITLE
osu!direct, Global Rankings and osu!updater not working

### ISSUE THREAD

**Issue by BeanGreen247** [ppy/osu-stable-issues#16]
Hi I've been facing these issues for the past few weeks.
The issues are as follows:

- osu!direct isn't working despite having suporter
- Global rankings don't work and didn't work before getting supporter
- And osu!updater doesn't download cutting edge release if the release stream is selected

Many thx for any information given.

**Comment by peppy** [comment]
Sounds like a network issue. please ask for help via forum or support@ppy.sh
