### ISSUE TITLE
Scrolling top 50 scores while still loading causes visual glitch

### ISSUE THREAD

**Issue by Vince7778** [ppy/osu-stable-issues#162]
If you scroll down the top 50 scores for a beatmap while they are still loading, then the username, accuracy, mods and score difference will not appear for the top score visible.

Video: https://youtu.be/di1Ba17OX7Y

Version: Stable 20191006.1

**Comment by smoogipoo** [comment]
Gonna call this as being out of scope, because the issue is deep in the game's drawing code.
