### ISSUE TITLE
country leaderboard issue

### ISSUE THREAD

**Issue by askart** [ppy/osu-stable-issues#164]
Global and country leaderboard has different scores on client, but website is ok. It was during yesterday [issue](https://twitter.com/osustatus/status/1183373043764064262?s=20) with leaderboard unable to load.
I've thought it was local issue, and for this sake installed osu in another folder to check it, but still country score was old.
May be this occurs because client gets cached scores for country leaderboard, but website working other way and has no this issue.

**Comment by peppy** [comment]
Could you please include actual details? screenshots? beatmaps? something?

Open the issue again if you can provide this.
