### ISSUE TITLE
Multiplayer scoreboard reenables after restarting the game

### ISSUE THREAD

**Issue by cocosenpai** [ppy/osu-stable-issues#167]
It's just really annoying for me to keep disabling the scoreboard everytime I want to play multi and if I forget it I get distracted by it. Especially annoying in tournaments where the performance matters. 

It should either keep your setting from the last time you played like the hud disabling or just have an option for it in the settings menu.

**Comment by peppy** [comment]
It should not be remembered after restarting osu! (the scoreboard is intended to be present in multiplayer).

**Comment by smoogipoo** [comment]
If it's intended to be displayed, it should _always_ be displayed, bar-none. I've also personally encountered this and it is a very big PITA, because you can't actually disable it until gameplay starts at which point circles may already be appearing.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
