### ISSUE TITLE
Numpad 5 cannot be bound without numlock on, every other key can be

### ISSUE THREAD

**Issue by Rev-el** [ppy/osu-stable-issues#168]
From here, paraphrased: https://osu.ppy.sh/community/forums/topics/973803

I have a Leopold TC210TP and I cannot bind numpad 5 to left or right click in "Change Keyboard Bindings". This is with numlock on (no keys on the numpad can be bound with numlock on) and numlock off (every other key on the numpad can be bound with numlock off).

This would be a much less confusing/aggravating issue if osu did not recognize the button at all, but if I press it on the "skip intro" screen before a song, osu simply makes a "pop" sound and nothing else.

Is there something I can put in the osu(username).cfg file manually?  The key is typically referred to as "clear" without numlock on (to the best of my knowledge), but putting that in the .cfg under left click or right click does nothing.

Any help would be appreciated, has been driving me nuts since I got this numpad.

**Comment by peppy** [comment]
When numlock is off, numlock keys are mapped at a *hardware level*. I do not believe there is any way to change this, apart from turn numlock on.

**Comment by qcl12345** [comment]
Doesn't numpad 5 work in lazer with both num lock on and off?

**Comment by smoogipoo** [comment]
Lazer is different to stable.

**Comment by qcl12345** [comment]
I get that, but theoretically it should be possible for numpad 5 to work in stable if it works in lazer. peppy's response made it seem like it was impossible. Whether or not the solution requires some large change with input handling though, I have no idea. Just thought I'd mention it.

**Comment by peppy** [comment]
Doesn't work on lazer in our testing. You may have a local application installed which is doing some weird mapping.
