### ISSUE TITLE
BSS updating gets stuck at 11%

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#17]
The exact causes are not known besides being related to more often happening on larger filesizes, and being basically guaranteed to happen if the mapset has video.

Issue:
When **updating** a beatmap, it may get stuck at Preparing Changes 11% and never finish updating.
The common solution to this is deleting the .osz2 file for the mapset from the game's SubmissionCache folder. Restarting the game sometimes fixes this, clearing SubmissionCache instantly fixes this.

_why should users be feeling the need to delete files in a subfolder of hidden directory (Data) just to update their beatmaps?_

This issue is a repost of
https://twitter.com/shinitagareee/status/1173640952692559872?s=20
https://twitter.com/IcekaltO/status/1143070922267607040?s=20
https://osu.ppy.sh/community/forums/topics/716852
https://osu.ppy.sh/community/forums/topics/509309
https://osu.ppy.sh/community/forums/topics/461765
https://osu.ppy.sh/community/forums/topics/803866
.... and many more

Edit: imo, if the 11% issue isn't fixable, the game should clear submissioncache automatically if it detects that an update is stuck instead of putting the onus on the user to know this fix.

**Comment by peppy** [comment]
Can logs be provided? None of the linked threads or tweets have any kind of logs. I need logs to understand what is going on,

**Comment by nl-tatatat** [comment]
This happens to me all the time too, especially on projects with bigger file sizes.

**Comment by peppy** [comment]
Please provide logs after it next occurs.

**Comment by dorothy3242** [comment]
Where / what logs would be needed? This is pretty easy to replicate for sets with video at least.

**Comment by hypercyte** [comment]
I'm stuck at 11% right now but I'm not too sure where to get logs from other than the logs folder in my osu folder so i'll just give whatever's there if it helps

runtime.log -> https://pastebin.com/h76neqkn
update_success.log -> https://pastebin.com/8VLMwnNB
what i see -> https://hypercyte.s-ul.eu/IOkv7cG9

**Comment by peppy** [comment]
Are you on cutting edge when testing this?

**Comment by dorothy3242** [comment]
runtime.log - > https://pastebin.com/7C3UJPsL
my own log if this helps
this one is a stable log, hypercyte was also on stable when testing.

when I switched to cutting edge, I noticed that there are more logs. next time this happens would we post either every log or a specific one?

**Comment by peppy** [comment]
CE is always best

**Comment by hypercyte** [comment]
okay did it on CE, i'll just post all the logs here

what I see -> https://hypercyte.s-ul.eu/xzW2HpK5
network.log -> https://pastebin.com/38GmtEPm
performance.log -> https://pastebin.com/KxBWG2R9
runtime.log -> https://pastebin.com/U1pMTHKx
update.log / update_success.log -> https://pastebin.com/uvYpFMUn

hope these help :)

**Comment by smoogipoo** [comment]
Unfortunately those logs don't provide anything useful. Is the form interactive in this state? Can you click buttons/etc?

**Comment by hypercyte** [comment]
Yeah can still hit the buttons, it just doesn't progress after "Preparing changes... 11.0%" no matter how long you wait

**Comment by peppy** [comment]
@smoogipoo i'm pretty confident I know what's happening and can fix it.

**Comment by peppy** [comment]
I've pushed a fix for this. It will fallback to full upload logic and also log some more detailed error output. While I'm going to close this issue for now, please send logs here if this happens to you!

**Comment by hypercyte** [comment]
I still seem to be getting stuck at 11%

running on CE (up to date) this is what i see -> https://hypercyte.s-ul.eu/I1xXOzL6

logs:
network.log https://pastebin.com/zD399g0q
performance.log https://pastebin.com/3LgmqEpG
runtime.log https://pastebin.com/ECg6CDTe
update logs https://pastebin.com/N2wNmfsF

**Comment by peppy** [comment]
A new build has not been published yet. Please try again later today.
