### ISSUE TITLE
Main Menu songs not shuffling 

### ISSUE THREAD

**Issue by BradleyCourt** [ppy/osu-stable-issues#170]
It seems after booting up osu after the most recent update only the song currently playing and the song previous are the only ones loading, after the song either finishes playing it will just loop over and you cant press to the next song, selecting a new song makes that new selected song loop instead 

(video of described issue)
https://puu.sh/EtUoG/1a1a92e2a0.mp4

**Comment by peppy** [comment]
Thanks for pointing this out. Should be fixed in next update.
