### ISSUE TITLE
F9 Friends Filter List Bugged Out and Shows an Empty List

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-stable-issues#171]
I'm not sure if this (still) has to do with max friends list, but currently I have less than 500 people added. Whenever I F9 to see my friends list the past couple of days or so, it seems to be completely empty (as shown below). 

![image](https://user-images.githubusercontent.com/18523454/67066267-07e95580-f12f-11e9-9e13-7015ff99cec5.png)

Before this week, (and when I had 500 people added,) I was still able to see people using the friends filter. I'm not sure why this started to happen recently, but I do know that [I'm not the only person having such issues.](https://twitter.com/Skillosu/status/1184898253621465090)

**Comment by peppy** [comment]
Can you try removing a few friends and see if it starts working again?

**Comment by VINXIS** [comment]
It shows up after I removed a couple people; I think the issue is caused by exceeding non-supporter friend limit without having supporter since my supporter did run out this week

**Comment by peppy** [comment]
likely a bit more involved (server-side). i'll look into it.

**Comment by peppy** [comment]
Has been fixed.
