### ISSUE TITLE
AIMod window is not selected after opening, so pressing Escape immediately leaves the map

### ISSUE THREAD

**Issue by MzudemO** [ppy/osu-stable-issues#172]
Video showing the issue: https://www.youtube.com/watch?v=IXiSsTB_Rog
Similar to https://github.com/ppy/osu-stable-issues/issues/88

**Comment by smoogipoo** [comment]
May be difficult to fix.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
