### ISSUE TITLE
Scores done on unranked beatmaps in Multiplayer don't get auto-saved to local ranking

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#175]
Issue #74 was intended so that failed scores don't get auto-saved to local ranking, however it seems that not failed scores done on unranked beatmaps are also not auto-saved, which I assume wasn't intended?

Video: https://streamable.com/t36w5

**Comment by peppy** [comment]
Should be resolved in cutting edge.
