### ISSUE TITLE
Plays with same score and same username do not save in local ranking regardless of mod combination

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#176]
As stated in title, when getting two scores/plays with the same score, only the first one is saved, while the second is discarded, even if it is done with different mods.

Video: https://streamable.com/t426r

Shown in the video, I have an HDDT SS on the map, when I get an HDFL SS, it won't appear because it is the same score as the HDDT play

**Comment by peppy** [comment]
Is this a regression?

**Comment by Magnus-Cosmos** [comment]
I'm not sure, I think it was always like this

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
