### ISSUE TITLE
osu! shows incorrect length of Beatmap when last object is slider

### ISSUE THREAD

**Issue by Peter-GHub** [ppy/osu-stable-issues#177]
If Beatmap ends with a slider (It's clearly visible if there is long slider at the end) the length shows where slider starts not ends. I think the game should use the time where slider ends not starts instead when last object is a slider

**Comment by Peter-GHub** [comment]
the length works perfectly for spinners but not sliders btw

**Comment by smoogipoo** [comment]
This is not easy to fix since the length is determined during a quick parsing pass. As such, going to mark this as out of scope.
