### ISSUE TITLE
Tournament client on cutting edge displays player names in Ariel font

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu-stable-issues#178]
![](http://puu.sh/EutcX/18e1e94e8d.jpg)

**Comment by smoogipoo** [comment]
What version of Windows are you running?

A fix for this has been tried many times before, and it isn't quite easy to fix unfortunately. The core of the issue lies within Windows' font loading.

**Comment by stanriders** [comment]
Is there any way to make font smaller at least?

**Comment by ThePooN** [comment]
Yes, the `ClientNameSize` property in `tournament.cfg` sets the font size as you desire.

**Comment by stanriders** [comment]
Doesn't that only change player names and not team names?

**Comment by ThePooN** [comment]
Ah, yes that's right.

**Comment by l3lackShark** [comment]
@smoogipoo this screenshot isn't mine, but I can confirm having the exact same issue and it seems that it appeared after the last couple of updates. Windows 10 on my system.

**Comment by peppy** [comment]
This should now be fixed.
