### ISSUE TITLE
Saving more than one replay on one map in one day results in latest file overwriting all previous

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-stable-issues#179]
1. Play a map
2. Save a replay
3. Play map again
4. Save replay again
5. Only the second replay is available

Cutting Edge 20191018.3

**Comment by peppy** [comment]
Is this a regression?

**Comment by E223** [comment]
I _think_ this 2 year old forum thread is describing the same issue, although it is worded very poorly: https://osu.ppy.sh/community/forums/topics/611251

Unless it was fixed at some point between Fallback and the present, I don't think this is a regression.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
