### ISSUE TITLE
Rankings don't match up in song select (because of restricted users)

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu-stable-issues#18]
![image](https://user-images.githubusercontent.com/16261733/65265474-5ba55680-db11-11e9-986a-5e29eee2451e.png) ![image](https://user-images.githubusercontent.com/16261733/65265713-cbb3dc80-db11-11e9-9043-b94a34f84eb5.png)

An apparently long-standing issue.

**Comment by peppy** [comment]
This should be fixed now, thanks to infrastructure changes [detailed here](https://twitter.com/osustatus/status/1196735955559829505).
