### ISSUE TITLE
Support diacritics in romanised titles

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu-stable-issues#181]
In the editor's song setup window the romanised title and artist text fields don't support diacritics, so if a title uses them you have to strip them of accents which can result in weird-looking text or changed meaning as it's the 'romanised' version that gets displayed by default in-game and on the web.

![image](https://user-images.githubusercontent.com/15932372/67229163-0a072900-f43b-11e9-9147-370da8106638.png)

**Comment by venix12** [comment]
I believe this is the intention of having romanized fields. You can always use this option:
![](https://venix2.s-ul.eu/bmM3d8I8)

**Comment by smileyhead** [comment]
> I believe this is the intention of having romanized fields. You can always use this option

Except that accented characters shouldn't count as not romanised in the first place.
Also, enabling that option is overkill for getting accents back, since it would also turn actually romanised titles back into their original language and I'm pretty sure most people can't read Asian characters.
