### ISSUE TITLE
Replays from data/r folder being deleted

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [ppy/osu-stable-issues#182]
Rarely happens, but replays sometimes get deleted from data/r folder.

<img width="960" alt="data replays" src="https://user-images.githubusercontent.com/52870410/67441142-c0007d80-f5c9-11e9-9738-d111a327ec1f.PNG">

All of the replays for the plays I did after 7:40 PM were somehow deleted by the game. I don't know when they were deleted as I only noticed today, but the replays were definitely there on the day I set them.

<img width="960" alt="screenshot4068" src="https://user-images.githubusercontent.com/52870410/67441250-1f5e8d80-f5ca-11e9-96cf-5d274654bde6.png">

The scores still show in local ranking, but there is no watch replay button anymore.

**Comment by MillhioreF** [comment]
Did the game crash or get closed by task manager / windows at the end of your play session? Most disk saves are buffered and can be canceled if the game crashes before getting a chance to do a background save.

If not, more info is necessary, there shouldn't be any code paths left in the game that can delete replay data without user input.

**Comment by sometimeszzzzzzz** [comment]
I'm not sure if it crashed during this session or not, most likely not if my memory is correct. And I kept playing till ~9:30, so that's 2 hours of replays missing. Usually when my game crashes, I don't lose any replays and the only thing lost is a bit of the score.db.

**Comment by peppy** [comment]
can you show us the content of the replays folder without truncation as well?

**Comment by sometimeszzzzzzz** [comment]
<img width="758" alt="replays 1016" src="https://user-images.githubusercontent.com/52870410/67532840-c3613b00-f695-11e9-83ea-6c36ba8661b9.PNG">

**Comment by peppy** [comment]
I was hoping to see the full filenames, up to the end.

**Comment by sometimeszzzzzzz** [comment]
Oh, so that's what you meant, my bad.
<img width="663" alt="full replay name thing" src="https://user-images.githubusercontent.com/52870410/67543064-96288300-f6bd-11e9-88aa-08e169815c67.PNG">

**Comment by peppy** [comment]
Thank you!

**Comment by peppy** [comment]
The only way replays can be deleted from this folder is if they exit your top 250 scores for a specific beatmap. A maximum of one replay can be deleted per new score set, so there's no chance of mass deletion.

There may have been something else on your PC that caused this issue, but I don't believe it was osu!.
