### ISSUE TITLE
"Toggle annotation" button in CE tourney client does not show annotation

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-stable-issues#185]
![image](https://user-images.githubusercontent.com/8269193/67619613-5c16c880-f806-11e9-8ab7-7cefc361d134.png)
It does hide scores though

**Comment by peppy** [comment]
The CE client has a slightly different tournament implementation. please use stable if this is necessary.

**Comment by ThePooN** [comment]
I would argue this is confusing and should probably be reworded to "Toggle warm-up".
It is not a localized string (at least in French) so this is essentially no effort to do.

**Comment by peppy** [comment]
Done.
