### ISSUE TITLE
Can't create new beatmap if same audio file as previously used

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#186]
Tried to make it somehow clear in the title but that's hard because i can't come up with a proper naming for the issue.

I reported this issue already once around 3 years ago.
That's a pretty interesting bug.

Following: I got used to use for audio-files just "audio" as name. For example when i reduce the kbit of a file from 320 to 192 with an audio editing Programm i just save it as "audio". 

Importing the audio file named "audio" creates a folder with the same name in the osu! song folder.
I did **not** submit the created beatmap so far (because that would also re-name the folder then).

Then i decided to map another song. Same procedure. I reduced the kbit of the audio file and namen it "audio". When i now try to import it into osu, it does not create a new .osz, instead it moves this audio file in the previously created one! That should obviously not happen.  

Old report thread: https://osu.ppy.sh/community/forums/topics/546651

--

I know, easy fix would be "just don't use the same audio file name". But it is still a bug and i think it should be at least addressed.

**Comment by smoogipoo** [comment]
Not sure how easy this is to fix.

**Comment by peppy** [comment]
Fixed in next cutting edge.
