### ISSUE TITLE
Editor beat snapping is off by 1 ms on a beatmap

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu-stable-issues#187]
broken map in question: https://caps.s-ul.eu/t436djVi

scrolling to the red line lands 1 ms early compared to the actual red line's position. trying to place an object on the red line also places it 1 ms behind the red line. afaik, this only happens with this one map.

**Comment by NerovaRiuzGX** [comment]
check your .osu file. don't use floating points on your red line's offset.

**Comment by peppy** [comment]
I think being 1ms off is out of scope of fixes for stable. This will not be noticeable in normal usage.

Are you seeing this 1ms display in AiMod or similar?

**Comment by STCapricorn** [comment]
actually, the problem is probably the bpm value obtained from using the 'tap' timing method.

before:
```
[TimingPoints]
2409,365.853658536585,4,1,0,100,1,0
```

after:
```
[TimingPoints]
2409,363.636363636364,4,1,0,100,1,0
```

after replacing the line, the editor snaps correctly.

**Comment by STCapricorn** [comment]
there are no floating points in the offset of the red line

>Are you seeing this 1ms display in AiMod or similar?

no. it only happens with specific bpms.

**Comment by peppy** [comment]
Out of scope then. Will likely be better in lazer.

**Comment by STCapricorn** [comment]
just found out it only happens with red lines created with the timing helper (pressing T to the beat in the timing panel). red lines created in the timing setup panel don't have this problem.
