### ISSUE TITLE
Two tracks playing at the same time

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-stable-issues#189]
I'm not sure how it happened, but two tracks started playing at the same time. Possibly caused by a lag, happened after I exited a map (with an unrelated song) using alt+f4. One track is behaving as normal, can be controlled by play/pause/etc buttons, changes when switching to another beatmap. Another track just plays in the background ignoring everything (even during gameplay), but fade in/out effects are still applied on it, and it doesn't loop nor switch to other songs. I recorded a video just in case, but I think the description should be enough.

**Comment by peppy** [comment]
This sounds nigh impossible to reproduce and likely out of scope. We're looking to fix common issues which affect osu-stable usability as a priority, so going to close this one for now. Feel free to reopen if there's reliable reproduction steps.
