### ISSUE TITLE
Lag on cutting edge

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-stable-issues#190]
isn't technically stable, but I hope it still goes here. When switching to cutting edge, the game commonly lags for like 10 seconds, for example, when switching beatmaps. First lag I experienced happened after opening mod list, the game didn't even respond after that and I had to restart.

**Comment by peppy** [comment]
you may have some weird side-effects from having performance logging turned on. try turning it off.

**Comment by pavlukivan** [comment]
that seems to fix the issue
