### ISSUE TITLE
Osu pause sound over lapping fail sound when on fail screen

### ISSUE THREAD

**Issue by SHIFT1672** [ppy/osu-stable-issues#191]

**Comment by JereJylli** [comment]
Also having this problem, im on b201910330 cutting edge

**Comment by peppy** [comment]
Does it happen on stable?

**Comment by peppy** [comment]
This seems like it isn't a regression, and would also happen on stable. Please confirm this.

**Comment by SHIFT1672** [comment]
> This seems like it isn't a regression, and would also happen on stable. Please confirm this.
> 
> As a sidenote: the fail sound is not supposed to be a long audio track. This will be slowing down your game client as it is loaded each time you play a beatmap, even if you never fail. It's not supposed to be bigger than a few kilobytes.

Can confirm 100%, i am on stable.
also been searching on the internet before posted here and apparently this isnt a new issue, ive seen posts from 2016 on reddit and osu forums.

**Comment by peppy** [comment]
So I can easily fix this by making the fail sound stop when the pause screen appears. But based on the video above that's not what the user intention is.

**Comment by SHIFT1672** [comment]
Is the other way around, the pause song plays during the fail screen.
In the video you can hear the background 2 different songs playing in the fail screen, i paused to use it as a reference as what song is playing the fail.

**Comment by peppy** [comment]
The pause track is *supposed to play*. The fail sound effect is not supposed to last for longer than the fail animation. As I say above, it is going to be killing your game's performance.

**Comment by SHIFT1672** [comment]
Oh i see what you mean now.
In that case i guess this case is solved i suppose. 
But I would suggest making fail screenplay its own _song_ and not the pause one, separate from the fail _sound_

**Comment by peppy** [comment]
I would suggest we don't ask for new skinnable features in osu-stable, as that is not the goal of this repository.

**Comment by SHIFT1672** [comment]
Understand
