### ISSUE TITLE
Can't import any map correctly

### ISSUE THREAD

**Issue by vistafan12** [ppy/osu-stable-issues#194]
When I add a file to a beatmap folder, after refreshing the song base I've get a error that does not allow me to import the map to the game. This is what I see when I press F5:

![Zrzut ekranu 2019-10-30 o 18 10 48](https://user-images.githubusercontent.com/20767476/67881523-ef226c00-fb40-11e9-8f14-afb1d448eb61.png)

But Failed folder is empty:

![Zrzut ekranu 2019-10-30 o 18 12 39](https://user-images.githubusercontent.com/20767476/67881566-ffd2e200-fb40-11e9-8263-90011434e149.png)

I use [the Wine version for macOS](https://osu.ppy.sh/community/forums/topics/682197), but I don't think that it's making any difference.

**Comment by peppy** [comment]
Which version are you on? Which beatmap are you importing? Where are your logs?

**Comment by vistafan12** [comment]
Latest stable version (20191031).

Maps I've tried to import:
[1](https://osu.ppy.sh/beatmapsets/332623)
[2](https://osu.ppy.sh/beatmapsets/1044986)
[3](https://osu.ppy.sh/beatmapsets/942642)

Interestingly, map 2 showed an import error again, but was correctly extracted and added to the song library.

Currently I do not have access to logs ATM for various reasons.

**Comment by peppy** [comment]
Please provide logs and reopen the issue.
