### ISSUE TITLE
Toggle Scoreboard does not work with Alt keys

### ISSUE THREAD

**Issue by E223** [ppy/osu-stable-issues#196]
Left/Right Alt can be bound in settings as a scoreboard toggle key although they don't seem to work.

**Comment by peppy** [comment]
Do you actually use that key for toggling scoreboard?

**Comment by Emfyr** [comment]
Also if left shift is used to toggle scoreboard then it enable/disable the in-game interface instead.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
