### ISSUE TITLE
returning to title screen from spectating causes to much snow

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-stable-issues#197]
# steps to reproduce:
- spectate someone
- player does something which causes the title screen to appear (in this case taking long to select a song)
# screenshots/video:
[expected amount](https://streamable.com/3yvyx), [actual amount](https://streamable.com/2yhjn)
# logs:
None
# version/setup:
- latest ce (`b20191031.1cuttingedge`)
- windows 10 1903/18362.418 (64 bit)

**Comment by Magnus-Cosmos** [comment]
I think this also happens when osu is not in focus (for a while?) while on the title screen

**Comment by peppy** [comment]
That looks pretty cool!
