### ISSUE TITLE
Beatmaps with video throwing errors on stable

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#198]
as of a recent update, saving when a mapset has video automatically adds fade commands if video is enabled in the editor.
![image](https://user-images.githubusercontent.com/33286824/67972098-65c47580-fbe4-11e9-81ae-0975c2e2ee67.png)
like so

however, if you have video disabled after that, this error will appear when starting the map:
![image](https://user-images.githubusercontent.com/33286824/67972207-9ad0c800-fbe4-11e9-8baa-a62e23ac5292.png)
this happens both in editor and **in gameplay.**

once you click "ok" to close the errors, gameplay will continue like usual, but it's really not ideal to have to click through error messages the average user won't understand to be able to play a map.

**This is causing any recently updated mapset with a video option to throw errors for users on stable if they disable video,** and as such is a serious issue. 

Since videos have no issue with being modified via storyboard scripting commands, it's the error message that needs to be fixed and not the added fade commands.

**Comment by JBHyperion** [comment]
Can't confirm from work, but not sure what's causing this error if videos have no issue with being modified via storyboard scripting like fade, scale, rotate, etc... Can you confirm on additional beatmaps (and provide a link for this one if it's uploaded)?

No storyboarding whiz, but "not set to reference of an object" seems to imply it's trying to modify something that hasn't been defined previously?

Even if this isn't throwing critical errors that prevent beatmaps from loading, beatmap calculation from parsing, etc., this is still going to be confusing to a significant portion of the playerbase who play without video enabled and should be addressed.

**Comment by dorothy3242** [comment]
It seems to be the commands are looking for the object (video), but because the video is not loaded in memory when video is disabled this confuses the game. I'm not entirely sure myself because it's the only context I've been seeing this error appear.

I don't have uploaded examples as of right now as the issue is rather recent and occurrences so far have been force-fixed by making sure the fade commands are not present in the beatmaps. But it can be recreated by saving a map with video with the video enabled, then trying to play with video disabled.

So far we've been fixing maps that have had added fade commands by remvoing them from the .osu and making sure to save in the editor with video disabled, as this way it won't add fade commands back to the .osu. However that's a really hacky workaround and the real issue with the error being thrown is what needs to be fixed.

**Comment by JBHyperion** [comment]
I was just about to say what a hackjob approach manually editing .osu files and force-saving them sounds like (reminds me of wcx's hitsound copier / star rating bug from a while back) but you beat me to it haha.

Might be that the error simply arises because the client is trying to parse an undefined object as you say (and can be ignored), but could also be indicative of something more sinister we haven't witnessed yet - not sure how osu!'s error-handling is performed but I wouldn't want memory buffers filling up with errors and exceptions in the long run / on low-end systems.

**Comment by peppy** [comment]
Please provide a link to an osz causing this issue.
