### ISSUE TITLE
osu fps spike when receiving messages 

### ISSUE THREAD

**Issue by UneCloud** [ppy/osu-stable-issues#199]
As said in the title, whenever I get mentioned/pm'ed, osu gets an fps spike. Originally I thought this problem was fixable by disabling pop-up notifications, but unfortunately it does not help. 

My client version is b20191031

**Comment by peppy** [comment]
Please provide performance logs from cutting edge and a screenshot of your frame graph when this occurs.

**Comment by UneCloud** [comment]
Here they are
[performance.log](https://github.com/ppy/osu-stable-issues/files/3797309/performance.log)

![screenshot156](https://user-images.githubusercontent.com/39381925/68014987-0fb60780-fca2-11e9-8f2e-062923384af6.png)

**Comment by peppy** [comment]
Thanks. Do you know the rough (wall-clock) time that you received that message?

**Comment by UneCloud** [comment]
Judging by saved chat logs it was between 12:06 and 12:07

**Comment by peppy** [comment]
Thanks so much for providing everything required! I'll look into this one over the next few days.

**Comment by peppy** [comment]
Hmm, the provided performance.log doesn't cover the point at which you received the PM. Can you try again? Note that the performance log file resets each startup.

**Comment by UneCloud** [comment]
Sorry for taking so long. 
I have tried reproducing this bug today multiple times, but it looks like it's now gone on CE version (b20191103cuttingedge). 
Thanks a lot for your time and the fix!

**Comment by peppy** [comment]
Weird. I did push a possibly related fix, but didn't expect it to solve your issue. Please re-open if you find it occurring again.
