### ISSUE TITLE
Clicking 'Edit' on the main menu resets selected game mode

### ISSUE THREAD

**Issue by percyqaz** [ppy/osu-stable-issues#2]
To replicate:
- Select play and enter level select menu
- Change game mode to anything other than osu!standard at the bottom
- Go back to the menu and go to edit
- When you return to level select, the mode has been reset to osu!standard
Expected outcome:
- Game mode should persist when you return to level select

I understand this is likely done to not display standard charts as their gamemode-converted counterparts in the editor menu, but if a quick fix is possible (like dumping last selected mode in the settings and setting it back after) that would be much appreciated :)

**Comment by peppy** [comment]
Seems like it could be a simple fix (but potentially not). Will look into it.

**Comment by Poyo-SSB** [comment]
This also resets any active mods.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
