### ISSUE TITLE
Background difficulty calculations causing noticeable lag

### ISSUE THREAD

**Issue by Sleepteiner** [ppy/osu-stable-issues#200]
I left the song select screen on mania on for more than 4 hours total, and it is still trying to calculate the star ratings of my maps despite there only being like 25 mapsets with the SR still listed at 0. The client is obviously still doing something, since I can hear my computer working hard like it normally does when trying to calculate the SR of a lot of maps, so I can't imagine that it was good for my computer to leave this broken process going on for that long. Also, leaving the process on for longer than a few minutes starts to really hurt the client. Things start to freeze up and sometimes even crash.

https://osu.ppy.sh/ss/14053934/5d79

**Comment by Sleepteiner** [comment]
It finally stopped saying that it was calculating difficulty. I guess the Halloween update made the game calculate all key modes at once, instead of waiting for the player to actually go to that key mode. Since I have all ranked maps, this means the client was calculating the difficulty for over 900,000 mania maps. This was obviously overloading the client, which was causing constant performance issues, glitches relating to files not loading correctly, and occasional full game crashes. One of the glitches is still going on too. There are 40-50 maps per key mode that are stuck at 0 stars, and the only way that I've found to get the game to calculate the SR again is be manually redownloading each map, which will likely take hours and can mean losing historical local scores. This change to how mania convert star rating is calculated in bulk needs to either be reverted or changed. It is obvious that the client was not designed to take that much calculation all at once since it caused endless problems for me for 2 days, and some of the problems persist still.

**Comment by peppy** [comment]
The recalculations only happen at song select (they stop during gameplay) and run at the lowest priority possibly.

**Comment by Sleepteiner** [comment]
If it does run at the lowest priority possible, then why did it sometimes cause the song select menu to be so laggy as to be pretty much unusable for most of the 5 hours I left it on? And, why did it cause tons of glitches with things not loading correctly like backgrounds, audio, and the SR of those specific maps? The last time the standard SR formula got updated, it took like 20-30 minutes, but there were no glitches caused by it and pretty much no lag. Is it possible that each key mode calculation is running at the same time, which made all those low priority functions add up to be something that is certainly not low priority? I don't really know, I don't know much about programming.

**Comment by peppy** [comment]
There’s no need to redownload anything, but it may be helpful if you can narrow down the specific beatmap causing the issue. It’s probably a beatmap with infinite BPM or other user-edits that are unsupported by osu!

**Comment by Sleepteiner** [comment]
I have only ranked maps saved, so I don't have too many crazy game breaking maps. The maps that were affected were pretty random. Most of them were maps with songs from u's, and a couple from a band called "Usa". The fact that those two were so common makes me think that something froze when the calculator was on US alphabetically, but it still registered them as calculated, which meant that I have to redownload them. Pretty much every other one had no pattern that I could find. https://osu.ppy.sh/s/829646 and https://osu.ppy.sh/s/582089 were broken without any key mods. Some, but not all, of the difficulties of https://osu.ppy.sh/s/885158 were broken on 4k, I think. Some of the difficulties of both sets of Everything will freeze were broken on 14k, if I remember correctly. This is a tiny fraction of the ones that I would have to redownload.

I am reinstalling osu anyway since this is only one of the issues that the Halloween update caused for my client. My only hope is to reinstall. If some maps get broken again when I do the difficulty calculation on the new install and they are the same maps, we will know if it is qualities of those particular maps, or state of my song folder, that is causing them to get glitched.

**Comment by peppy** [comment]
This should be a lot better now (we've fixed some maps getting stuck in difficulty calculation). Please comment if you have this happen again in the future.
