### ISSUE TITLE
osu!direct shows "last updated" instead of "ranked on"

### ISSUE THREAD

**Issue by camellirite** [ppy/osu-stable-issues#203]
in osu!direct beatmaps are sorted by the time they're ranked so im pretty sure that's what should be shown instead of the date they were last updated

![FHqtgV4](https://user-images.githubusercontent.com/23125409/68081020-ed191f80-fe56-11e9-921a-0623c2a39908.png)

**Comment by smoogipoo** [comment]
Should be a fairly easy fix (web-side).

**Comment by peppy** [comment]
Fixed in next CE
