### ISSUE TITLE
File size requirements for AIMod are redundant to latest BSS

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-stable-issues#205]
In one of the newer updates to Stable, a change was made to how file sizes are regulated.

The current AI Mod has a limit (unpackaged) of 10mb (without video) 
and 24mb with Video.

The new changes made the regulations as:
(All sizes to final .osz size)
`10mb + (10mb * max drain time of set)`
with a final size of 100mb

Additionally, a warning of more than 100 difficulties should be made through AIMod along the lines of "200 difficulties found from a max of 100 difficulties allowed on Beatmap Submission"

**Comment by peppy** [comment]
Fixed in next cutting edge.
