### ISSUE TITLE
"Delete all visible map" is bugged.

### ISSUE THREAD

**Issue by GoldenNocturne** [ppy/osu-stable-issues#208]
I'm a mania player, and i want to delete, for example, every 8k/16k map, but i can't because if i do that, it will just make random maps disappear and break the others (of course i'm using group by key count).
It's not like it deletes them, actually, it makes them disappear until you f5 update, and makes the difficulty calculation start from 0. And well, when you have something like 20k maps, that process breaks the game and some maps.
Also, if my guess is correct, it doesn't interact well with the grouping system, when i tried to delete the 7k maps were the 5k maps which disappeared.

**Comment by peppy** [comment]
You are supposed to type a search and then delete. If they are not visible (ie. the group is collapsed) it likely won't delete.

**Comment by GoldenNocturne** [comment]
After reading your comment i tried deleting every 5k map by searching key=5 instead of using the group by key count option. When i did it, there were 250 5k maps, now there are only 141, which can only be seen by not using the search option. Something else broke.
![screenshot547](https://user-images.githubusercontent.com/57441467/68322044-01615480-00c3-11ea-8f7e-187b7d47c65b.jpg)
![screenshot548](https://user-images.githubusercontent.com/57441467/68322085-14742480-00c3-11ea-8a9e-1f70273e3c76.jpg)

**Comment by Leniane** [comment]
This normal that they are still there because they are most likely standard beatmaps that are converted to 5K mania difficulties and not real 5k mania beatmaps.

**Comment by peppy** [comment]
Can this safely be closed as working-as-intended?

**Comment by Leniane** [comment]
Yes since it's not suppose to delete standard maps that are converted to 5K mania diffs
