### ISSUE TITLE
Everytime you start osu! #osu opens even if you didn't have it opened before

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#21]
Problem is pretty self explanatory. Whenever you close osu! with a channel currently opened(not including pms), that channel will still be open the next time you start up osu! The same also goes if you close a channel. If a channel is closed when you close osu!, it won't open up the next time you open osu! All this is thrown out when it comes to the #osu channel though. No matter if its closed, it will ALWAYS be open the next time you start up osu! I, and many tens of thousands of other players have closed #osu hundreds or thousands of times every time we opened up Osu! because... we don't play osu!standard, and aren't interested in that gamemode's chat either.

I hate #osu and I want it closed forever. Thank you.

**Comment by ShinKeyKai** [comment]
I'm one of those tens of thousands

**Comment by iptq** [comment]
+1

Since osu receives messages in the background this could potentially lag the game

**Comment by peppy** [comment]
To my knowledge the chat display is not updated in the background. It waits until it is displayed to do updates.

Not sure about this change. It requires server-side changes, as well as default handling for users which are arriving to the game. It would also require testing against stable-fallback to make sure the server changes don't break there.

Leaning towards fixd-in-lazer for this.

**Comment by Cynplytholowazy** [comment]
Suddenly displaying Unicode characters in #osu (which is occasionally seen in #osu because people don't read rules) will cause sudden lag spike in low-end PCs. Have had it several times before I changed my PC.

**Comment by peppy** [comment]
Yes, when chat is open. Not when chat is not open.

**Comment by WinterIsPretty** [comment]
I close it because if I leave it on for more than an hour it lags my game

**Comment by peppy** [comment]
Chat can't cause game lag. It doesn't perform any operations unless you open and view the channel.

**Comment by peppy** [comment]
I've changed the conditions for when #osu will be auto-joined to only be applicable to new players. Next bancho release.

**Comment by WinterIsPretty** [comment]
Oh thanks, this is will be useful for me in the future
