### ISSUE TITLE
Crash with first-note spinners and negative offsets (only with shaders active)

### ISSUE THREAD

**Issue by TheDoomcaster** [ppy/osu-stable-issues#211]
I was recommended to post this here, from the original forum post: [Link](https://osu.ppy.sh/community/forums/topics/985318)

osu! username: Blitzkraken

After some testing, I've been able to narrow down a crash relating to the first spinner of a song crashing the game if shaders are enabled, and the local offset is set to too low of a negative value. This particular song has a spinner that appears very quickly after the song begins, which is why I was able to find this.

The other song mentioned in the original post didn't have this issue, but it's first slider appears much later. Even if I set it to an extreme offset like -800, it won't have any effect since the offset is applied long before it appears.

No other songs are effected by this issue, since that game runs perfectly fine. Even the other difficulties in this song are fine.

This might be related to a "rewind stutter" effect from having a large offset value, as I've noticed other songs having a visible adjustment to their hit-circle radius indicator, and the opacity in the Hidden mod. This happens in songs that have circles appear quickly after the song has started.

Song: [Aozora Morning Glory (lit120's Insane)](https://osu.ppy.sh/beatmapsets/807524#osu/1696042)

**Steps to reproduce:** 
Turn on shaders in the options. 
Set global offset to 18ms. 
Play the specified map and difficulty. 
Set the local offset of the song to -30ms or less (-40, -50, etc). 
Restart the song. 
Hit retry or hold "~" after first spinner if it doesn't happen after the first attempt or two.

**Workarounds:**
1. Turn off shaders.
2. Set local offset to a value of -25 or above.

**My guess:**
The game adjusts the offset shortly after the song begins (rather then before the audio plays).

So, in this case, the spinner gets loaded before the offset is applied. The shader drawing it to the screen is already setup at this point. The offset is then applied, which changes the value sent to the shader to a much lower value than it can handle, and triggers a crash.

This is just an assumption, as I haven't messed with programming shaders or programming in general in a few years.

**Computer details:** 
HP 8300 Elite SFF 
Windows 10 
Intel i5-3470 @ 3.2GHz, 3.6GHz-turbo (quad-core) 
Gigabyte GTX 1050 ti, 4G 
8GB DDR3 

All drivers and Windows 10 updates are installed. I also re-installed the song mentioned above, which led me to figure out that the offset is part of what causes the issue.

**Crash logs:**
To avoid making this post too long, both the error log from the game crashing, and the runtime.log information can be found in the forum post linked at the top of the post. I can repost them here if necessary.

Fairly new to reporting bugs, but I hope this helps out.

**Comment by peppy** [comment]
Please test latest cutting edge to see if this is fixed.

**Comment by peppy** [comment]
Very weird, I can't reproduce any more..

**Comment by peppy** [comment]
I've made one more attempt to fix this, please try again.

**Comment by TheDoomcaster** [comment]
Seems to still happen, and while I did some more testing with different values, it's pretty inconsistent.
Universal Offset, Local Offset = result

+18, -30 = crash after 13 retries
0, -30 = fine, after 15
0, -45 = crash after 8
+18, -45 = crash after 7
+15, -45 = fine after 20
+27, -45 = crash after 17

At this point it's hard to pin point anything, but I can tell it's a lot better than it was since it was crashing after one or two attempts before. I do notice a bit of a frame skip an attempt or two before the crash attempt, though it's so slight I may be over-analyzing it.

I can re-upload a new set of crash logs if needed, but it looks about the same as before since the error dialog was exactly the same, letter-to-letter.

[osu!.lanar.txt](https://github.com/ppy/osu-stable-issues/files/3844747/osu.lanar.txt)

Here's my config file if it helps, and I made _absolutely sure_ that I removed all login information (the password) since the file warns me of that. The only identifiable info in it now, is my username which is fine.

Normally I set my mouse sensitivity to 0.25 in here, but the cutting edge update reset that to 0.4.
The universal offset usually +18, but I forgot to set it back after it crashed.

Looking into the phrase "Negating the minimum value of a twos complement number is invalid" brings up a few things about "16 bit signed int" (short) being [limited](https://stackoverflow.com/questions/6265381/c-sharp-short-error-negating-the-minimum-value-of-a-twos-complement-number-is-i) to -32,767 and 32,767 values, and that if you go out of that range it'll throw this error. From the sound of it, it's like an array where the max value is -1 from the maximum value.

So somehow a variable is being set beyond it's range from the sound of it? I'm not too knowledgeable about C#, since I used to be more of a hobbyist Typescript coder, but I'm willing to look more into it if it helps at all.

**Comment by peppy** [comment]
I've added some extra logging to the next build, please run and attach runtime.log

**Comment by TheDoomcaster** [comment]
I don't know if you changed anything, but this time it took a lot longer for it to crash. Around 40+ attempts I think. Here's the [runtime.log](https://github.com/ppy/osu-stable-issues/files/3844958/runtime.log)

**Comment by peppy** [comment]
Unfortunately it looks like the log file was not completely written out, and is missing the important part. Could you try again and ensure the log has the exception listed? I think this may be possible by waiting at the crash screen until it finishes writing.

**Comment by TheDoomcaster** [comment]
Ah, I left the crash window open when I copied it over. When I closed it it updated the file.
Here's the newer one: [runtime.log](https://github.com/ppy/osu-stable-issues/files/3844973/runtime.log)

**Comment by peppy** [comment]
Thank you, super helpful.

**Comment by peppy** [comment]
Another attempted fix in latest cutting edge.

**Comment by TheDoomcaster** [comment]
Completely fixed now! I went all the way to 100 retries to makes sure of it. Tried -30 local offset all the way up until 60, then -40 until 75, then -45 until 100. No freeze or frame-skipping either either.

Thanks peppy!

**Comment by peppy** [comment]
perfect, thanks
