### ISSUE TITLE
Discord Integration: Name of multiplayer room displays incorrectly if it contains Unicode characters

### ISSUE THREAD

**Issue by nautzz** [ppy/osu-stable-issues#212]
Discord Rich Presence will display a mess if the name of the multiplayer room a given player is playing in contains Unicode characters. I already contacted Discord about this, and was told it wasn't an issue on their end.

[Here's a screenshot.](https://i.imgur.com/7zpeMp4.png)

**Comment by peppy** [comment]
For context, I did discuss this with the discord rpc guys and believe we never came to a working solution. Seems someone manually fixed this [here](https://github.com/discordapp/discord-rpc/issues/119#issuecomment-363916563) though.

I'll take a look into this.

**Comment by peppy** [comment]
Has been fixed in latest release.
