### ISSUE TITLE
Pause + F9 after pause causes map to restart with no notes

### ISSUE THREAD

**Issue by xduski** [ppy/osu-stable-issues#213]
Upon finishing a map in osu!taiko, I first pressed Esc in order to get to the post-map screen faster, but it caused a pause since the map wasn't at the end. After I unpaused the game and pressed F9 to open my friends list, it caused the game to restart the map - but the notes disappeared. When the map reached the end with two spinners in it, I automatically got the bonus points for finishing the spinners. After the "ghost" map ended, the ranking screen popped up but I indeed had more points than a normal SS would warrant due to the ghost spinners. 
The replay of the score plays normally until the end, where like 100 hitsounds play at once. Also the replay provides accurate scoring without the ghost spinners. I attempted to recreate this issue, but did not succeed in 5 or so attempts.
Map in question (you can see my nomod score is higher than other SS scores): https://osu.ppy.sh/beatmapsets/1044666#taiko/2183847
Replay: https://puu.sh/EEssy/8532a7cf28.osr

**Comment by peppy** [comment]
Please provide a video and we will investigate this.
