### ISSUE TITLE
Discord multiplayer invites need osu!supporter

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-stable-issues#214]
Not sure if the osu!supporter requirement is intended, but there is no indication that you need it and the "Join" button does nothing.

**Comment by peppy** [comment]
Why do you think it's supporter related?

**Comment by Joehuu** [comment]
I was still supporter when my friends started to use this feature, and it works while my friends (not supporter) say it doesn't work. My supporter ended recently and now it doesn't work for me.

**Comment by Coppertine** [comment]
The only way that multiplayer makes it supporter related is on CuttingEdge where it does require suportter.

**Comment by peppy** [comment]
going to tentatively close this is invalid.

**Comment by Joehuu** [comment]
Without supporter: https://puu.sh/EGV6z/f9bdbcb55c.mp4

With supporter (has audio, needs relog to work): https://puu.sh/EGUZ8/a312cf8854.mp4

This is stable. Just want to know if intended and if that's the case, show some notification that you need supporter.

**Comment by peppy** [comment]
Looks like this could be a server-side issue. Will put out a fix today.

**Comment by peppy** [comment]
This should now be resolved on all builds. Please confirm!

**Comment by Joehuu** [comment]
It works now. Thanks!

**Comment by Joehuu** [comment]
Seems to be broken again. This time it doesn't matter if you're supporter or not.

Is this related to the rollback in https://twitter.com/osustatus/status/1197881624022548480 ?

**Comment by peppy** [comment]
Possibly. Will re-deploy on monday.

**Comment by Joehuu** [comment]
Still not working. Should probably reopen until fixed.

**Comment by peppy** [comment]
Can you confirm it works *with* supporter?

**Comment by Joehuu** [comment]
It doesn't work with supporter.

**Comment by peppy** [comment]
Fixed again, in cutting edge.
