### ISSUE TITLE
Unable to use 100% dim in tournament client

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-stable-issues#216]
I know it's intended, but there's really no reason to not allow that for community tournaments. I'm pretty sure most of the tournament client users won't use 100%, but want to have more dim than allowed right now

**Comment by peppy** [comment]
What value would you want to use?

**Comment by stanriders** [comment]
Something like 90-95 would be good

**Comment by ThePooN** [comment]
95% makes the background so barely visible after video compression, especially on non-gaming displays.

**Comment by peppy** [comment]
I can't find any code limiting the dim. How are you testing this?

**Comment by stanriders** [comment]
I can't tell you the value before testing them out, and there's no way to test /shrug

It shouldn't be the same for everyone for sure, some may want to keep the dim as it is right now, some may even want 100% dim

**Comment by stanriders** [comment]
Try setting dim to 100% either in configg or in the clients themselves

**Comment by ThePooN** [comment]
Just start osu! normally, set a dim, start it back in osu!tourney mode, and notice the different dim.

**Comment by peppy** [comment]
Finally found it in a very weird place (was capped at 50).

I'm changing it to 90% max in the next cutting edge build.
