### ISSUE TITLE
Editor timeline not fully working unless the default skin is used

### ISSUE THREAD

**Issue by Minion24** [ppy/osu-stable-issues#218]
I don't know if this has been already put on here, but sometimes when a skin that is not the default one is used in the editor the timeline becomes partially working (you can still select notes but not move them on the timeline)

**Comment by peppy** [comment]
Please provide the skin.

**Comment by Coppertine** [comment]
Please make sure you don't have Note lock enabled..

**Comment by Minion24** [comment]
> Please make sure you don't have Note lock enabled..

this happens randomly without enabling note lock

**Comment by Minion24** [comment]
> Please provide the skin.

here.

https://raisemysword.s-ul.eu/AnjTheoi

**Comment by Minion24** [comment]
also, here's a video showcasing the same problem happening with a different skin

https://youtu.be/CmpACdezE5M

**Comment by peppy** [comment]
Your skin is broken. hitcircle@2x is 1x1px.
