### ISSUE TITLE
Unable to read the requested replay file

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#219]
All of the replays I download from the website show this error.
![](https://osu.ppy.sh/ss/14144433/070a)

Sample replay file by Jakads taken from [here](https://osu.ppy.sh/beatmapsets/400078#mania/992512): [replay-mania_992512_313689494.zip](https://github.com/ppy/osu-stable-issues/files/3877672/replay-mania_992512_313689494.zip)

**Comment by smoogipoo** [comment]
your browser seems to have done something weird to the file and caused permissions issues. re-downloading from the website works for me and @peppy .

**Comment by abraker95** [comment]
After reading your comment I tried Edge, and turns out it works. Looking at permissions I found that Firefox added a read-only attribute to the file. After unchecking the read-only option in the general tab of file properties I could open the replay.
