### ISSUE TITLE
Osu minimizing to tray when Numpad 0 is pressed

### ISSUE THREAD

**Issue by Cr4zyG4m3rLP** [ppy/osu-stable-issues#22]
I'm not sure if that's a bug or intended behavior, but I accidentally press the "Numpad 0" button all the time, and the game just minimizes into tray.

**Comment by LittleEndu** [comment]
Is your boss key set to numpad0?

**Comment by nl-tatatat** [comment]
^ isn't that just the boss key?

**Comment by peppy** [comment]
Intentional behaviour. numpad0 = insert when numlock is off.
