### ISSUE TITLE
osu! crashes with current discord change

### ISSUE THREAD

**Issue by Ticle** [ppy/osu-stable-issues#220]
**Problem details:**
Hello, maybe I'm suffering from the 'Stable 20191122' update(latest).
I updated osu! about 2 hours ago, and osu crashes itself so I wondered what causes that appcrash?
Computer reboot, redownloading .Netframework, windows update, graphic driver check, etc. < This is what I did.

The weird thing is osu shutdowns not always instantly. At first, it was instantly but I found it still alive for some secs.

And finally, I got the hint, the discord update.

_Reliability

Fix spinners crashing on some maps with shaders enabled
Fix potential crashes when spinning with a local offset set
"Update discord rich presence library to fix UTF8 strings"
"Fix discord rich presence multiplayer join not working for some users"
Improve reliability of score submission after using editor_

You know, Peppy updated like this and please check between the quotation mark.

The point is: **I took action like click 'Quit discord', and osu! works well still now.**
That's pretty great I can do more osu, but I can't do this with discord now.
I wish this problem fixed as soon as fast.

**Video or screenshot showing the problem:**
Actually, this is just appcrash, and I don't know well about computer things, so if you want something more data with my computer then let me know with the details!

Txt written below is about my computer spec.

Windows 7 Ultimate KN 64bit
i3-4130
8MB RAM
GTX 750ti

**osu! version: Stable 20191122 (latest)**

**Comment by peppy** [comment]
We had one other report of windows 7 startup failure. I tested but could not replicate, but i was in 32 bit windows 7.

Could you please provide more details f the crash - ie what you see or what appears in event viewer when it occurs?

**Comment by Ticle** [comment]
aaaa It will be my first use of event viewer. but I can't check that rn cuz im outside now. After about 8pm(utc+9), i can leave a comment.

I'm sorry I couldn't help you right now!!

**Comment by Ticle** [comment]
Here it is. I hope this is what you want


+ System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2019-11-23T11:30:32.000000000Z 
 
   EventRecordID 78911 
 
   Channel Application 
 
   Computer Ticle-PC 
 
   Security 
 

- EventData 

   osu!.exe 
   1.3.3.7 
   5dd76278 
   ntdll.dll 
   6.1.7601.17514 
   4ce7ba58 
   c0000374 
   000ce653 
   1ee0 
   01d5a1f167f71258 
   C:\Users\Ticle\AppData\Local\osu!\osu!.exe 
   C:\Windows\SysWOW64\ntdll.dll 
   a82494c4-0de4-11ea-a414-00ac0a12761c

**Comment by peppy** [comment]
Could you please test http://m2.ppy.sh/r/osu!.exe/f_bf23604bef29bd7ff8cdb387f208243d (drop in your osu! folder, overwriting existing exe).

**Comment by Ticle** [comment]
Unfortunately, this didn't work well.
What I did: 

1. Downloaded the file
2. Picked off original osu!.exe
3. Changed the file's name to 'osu!.exe'
4. Launched without discord and checked osu! works well
5. Launched with discord and saw osu! crashed.


And here's the event log again!

+ System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2019-11-26T03:59:24.000000000Z 
 
   EventRecordID 79228 
 
   Channel Application 
 
   Computer Ticle-PC 
 
   Security 
 

- EventData 

   osu!.exe 
   1.3.3.7 
   5dd76278 
   ntdll.dll 
   6.1.7601.17514 
   4ce7ba58 
   c0000374 
   000ce653 
   2528 
   01d5a40de1bb62fb 
   C:\Users\Ticle\AppData\Local\osu!\osu!.exe 
   C:\Windows\SysWOW64\ntdll.dll 
   21ee8acc-1001-11ea-859c-00ac0a12761c

**Comment by peppy** [comment]
Thanks for the feedback. I'm making another build to test, please hold the line.

**Comment by peppy** [comment]
http://m2.ppy.sh/r/osu!.exe/f_e449e9db9b693babe3d936219009beeb

**Comment by Ticle** [comment]
Maybe the same problem shows.

+ System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2019-11-26T04:18:32.000000000Z 
 
   EventRecordID 79234 
 
   Channel Application 
 
   Computer Ticle-PC 
 
   Security 
 

- EventData 

   osu!.exe 
   1.3.3.7 
   5dd76278 
   ntdll.dll 
   6.1.7601.17514 
   4ce7ba58 
   c0000374 
   000ce653 
   16f4 
   01d5a4108eb53263 
   C:\Users\Ticle\AppData\Local\osu!\osu!.exe 
   C:\Windows\SysWOW64\ntdll.dll 
   ce329c1b-1003-11ea-859c-00ac0a12761c

**Comment by peppy** [comment]
http://m2.ppy.sh/r/osu!.exe/f_6c5b5bdbc7b44b9b97335f3169c763ed

this one should resolve.

**Comment by Ticle** [comment]
I'm afraid the same error occurs...

+ System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2019-11-26T04:45:44.000000000Z 
 
   EventRecordID 79244 
 
   Channel Application 
 
   Computer Ticle-PC 
 
   Security 
 

- EventData 

   osu!.exe 
   1.3.3.7 
   5dd76278 
   ntdll.dll 
   6.1.7601.17514 
   4ce7ba58 
   c0000374 
   000ce653 
   1df4 
   01d5a4145b606442 
   C:\Users\Ticle\AppData\Local\osu!\osu!.exe 
   C:\Windows\SysWOW64\ntdll.dll 
   9a948ee7-1007-11ea-859c-00ac0a12761c

**Comment by peppy** [comment]
Do you see the osu! updater window appeal after clicking the executable?

**Comment by Ticle** [comment]
yes, and it automatically updated itself.

**Comment by peppy** [comment]
I see! I think that may be the problem. Could you please open osu!.cfg and change the release stream to cuttingedge then try replacing the executable again?

![image](https://user-images.githubusercontent.com/191335/69600841-7934f600-1055-11ea-8b2b-054de512d07a.png)

**Comment by Ticle** [comment]
Finally done! It works with discord :o
Thank you for the help !!

Now I should buy more supporter <3

https://osu.ppy.sh/ss/14163258/a796

**Comment by peppy** [comment]
Thanks for the help.

**Comment by peppy** [comment]
A new stable release has just gone out with a fix, so you can change your release stream back if you wish.

https://osu.ppy.sh/home/changelog/stable40/20191126.3
