### ISSUE TITLE
Discord Rich Presence doesn't work on updated windows 10

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-stable-issues#223]
![image](https://user-images.githubusercontent.com/34809632/69626547-23f2e780-1049-11ea-8b9f-ba14af0b69de.png)
![image](https://user-images.githubusercontent.com/34809632/69626573-31a86d00-1049-11ea-9076-0cf70629ab0e.png)

**Comment by peppy** [comment]
Please test on latest cutting edge.
