### ISSUE TITLE
Can't change the playing speed for osu!mania when test playing from the editor

### ISSUE THREAD

**Issue by Leniane** [ppy/osu-stable-issues#224]
I recently was looking into the editor of some other modes and noticed when test playing the map in the editor that you can change the speed of the map to 1.5x and back to 1x with F3 but for osu!mania that doesn't work since F3 will only lower the scroll speed and doesn't change the speed of the song/beatmap.

On standard with auto play pressing F3 works fine
https://osu.ppy.sh/ss/14167842/9d45

But on mania you get this
https://osu.ppy.sh/ss/14167845/172b

**Comment by smoogipoo** [comment]
Change your keybindings.
