### ISSUE TITLE
Settings Presets

### ISSUE THREAD

**Issue by Karthyz** [ppy/osu-stable-issues#229]
As asked for on Reddit, wasn't really sure how to format it so I just took screenshots of what I thinks important.

Gameplay focused preset: https://i.imgur.com/h7kvQ5F.jpg
Aesthetic focused preset: https://i.imgur.com/kW56Fqw.jpg

**Comment by smoogipoo** [comment]
Out of scope for stable. May be implemented at some point in lazer.

**Comment by peppy** [comment]
on top of that, the provided images make little sense with a potential implementation (it seems like some settings would save their state in one mode but not the other). if/when implemented in lazer it would save all settings at very least.

**Comment by Karthyz** [comment]
Ahh I misunderstood, I thought this was something you wanted for an implementation on stable. I think something with presets would only need to change certain settings and not others, hence all of the "preference" notes. Those ones I don't think would need to be changed by a preset. But yeah, kind of irrelevant for stable, my bad
