### ISSUE TITLE
rename #ctb text channel to #catch

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-stable-issues#23]

**Comment by nl-tatatat** [comment]
any reason.. why?

**Comment by revelsix** [comment]
I don't entirely agree with this, but I guess it could make sense as it matches #osu and #mania ... wait- I mean #osumania

**Comment by Xinnoh** [comment]
catch the beat used to be the official name, it was removed and is now just called osu!catch
plenty of time went in to renaming everything on the wiki from ctb/catch the beat to catch
It's an acronym that is no longer used.

also yeah should #osumania be renamed to #mania ?

**Comment by revelsix** [comment]
I didn't know about the change to just catch, I do actually agree with this change in that case.

> also yeah should #osumania be renamed to #mania ?
Probably. The best way (I think) to go about it is #osu #mania and #catch. Having osu in front of mania is redundant, we know what game we're playing lol.

**Comment by peppy** [comment]
Not an easy fix (we don't have support for renaming channels in osu-stable). Can be done after switching to lazer.
