### ISSUE TITLE
Ignore all beatmap skins affects gameplay and editor

### ISSUE THREAD

**Issue by Respektive** [ppy/osu-stable-issues#231]
I think having seperate checkboxes for the editor and gameplay would be useful. 

Many players prefer to play without custom beatmap skins, but in the editor I think it's actually better to have them enabled to check custom combo colors and other skin changes. Having to change the setting everytime you want to use the editor is pretty annoying.

I know you can also disable skins per beatmap, but doing that on every map is also annoying. It's the same thing for the custom hitsounds option btw.

**Comment by peppy** [comment]
I always find this one super funny. Mappers making skins / colours then turning them off when they play the game.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
