### ISSUE TITLE
Make scoreV2 submit scoreV1 scores

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-stable-issues#233]
This may be too large of a scope, but I want to give it a try anyway:

I believe tournament plays shouldn't be unranked and I propose calculating score for both v1 and v2 simultaniously in the client. As for accuracy you can either use final scorev2 accuracy or keep separate results for v1 and v2 (which may be easier if you just slap two judjements systems on top of each others for this).

I think it shouldn't be too hard to implement, and it's not really a feature and more of a fix for whats been wrong all that time.

**Comment by smoogipoo** [comment]
This isn't easy to implement. Lazer already has this mostly sorted out.

**Comment by stanriders** [comment]
Yeah I know lazer will remove the need for an unranked v2 mod completely, but the issue is present now and lazer will have score submission who knows when. 

The fact that v2 is unranked makes tournament players heavely underranked and also makes their stats incorrect (low playcount, score, etc) and I believe this issue is quite important as tournament scene keeps growing bigger and becoming more important and its becoming more and more hard to properly estimate players skill (hence why things like badge weighted ranking had to be invented). 

Even if you're not going to make v2 score conversion (which to me seems like the easiest solution for now if we dont count 'release lazer' as a solution), I hope you'll at least add this to your probably giant list of things that **really** need fixing.

**Comment by smoogipoo** [comment]
I didn't close it because it's already implemented in lazer. I closed it because there's so many systems at play here. The upload for sure can be done in very little LOC, but what about replays, what about display for the leaderboard, what about slider accuracy and other changes that were done to other game modes (ticks have changed in taiko iirc, hit windows changed in mania)?

This is more complex of a change than you're imagining it to be.

**Comment by stanriders** [comment]
That's exactly why I'm proposing running both judgement systems together. All gameplay changes could be reflected properly in both scores and replays aren't storing judgement data iirc. In the end to the player its the same as just doing two exact scores, one with v1 and another with v2. You can even store them both in the client

I understand that it's a complex change, I just hope you'll consider it worth the time it would take

**Comment by smoogipoo** [comment]
That requires a complete rewrite of gameplay. Not worth it.

**Comment by stanriders** [comment]
Unfortunate. Alright, thanks for the response then
