### ISSUE TITLE
Editor - Slider control points not adding

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu-stable-issues#235]
### Description
In the editor, you cannot add slider control points before extending a slider more than the `'minimum slider length'`
`'minimum slider length'`: The smallest slider that renders at current SV and Beat snap divisor.

### Steps to reproduce:
1. Open editor on a random map with high SV
2. Set Beat Snap Divisor to 1/1
3. Press 3
4. Click
5. Move the mouse a few(2 or 3) pixels in any direction
6. Click

Expected:
- A Slider control point appears

Actual Result:
- Nothing happens ( Cursor ripples )

### Temporary fix:
5. Move the mouse far enough for a small slider to appear
6. Move back to the place you wanted to put the slider control point
7. Click
8. Control point appears

It's ever so annoying when mapping to have to extend the slider and the go back to the actual point I wanted.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
