### ISSUE TITLE
Why aren't beatmap packs encrypted?

### ISSUE THREAD

**Issue by Pumperknuckle** [ppy/osu-stable-issues#236]
Sorry if this isn't the place for this or if this is too difficult to do, but I couldn't find discussion of this anywhere and it seems so obvious. OSU is on shaky ground legally, but it seems it would be much better if all beatmap packs were encrypted. Maybe stayed as one file similar to the **.osk** but it never becomes a folder with easily accessible mp3 and bg. That way there isn't the legal issue of OSU distributing illegal downloads.

I like free music as much as anyone, but it seems like this somewhat needs to happen at some point. Similar to how if you download offline Netflix movies, you cant access the movies at all unless it's through the Netflix app.

**Comment by smoogipoo** [comment]
Please leave this matter to us.
