### ISSUE TITLE
Facilitate Metadata management

### ISSUE THREAD

**Issue by Nyxa** [ppy/osu-stable-issues#237]
Currently, metadata is required to be uniform across all difficulties. This means if any change in the metadata is to happen, it needs to be applied to each difficulty, one by one. On top of this, metadata is tied to individual beatmaps, which means that if there is an issue with a map's metadata during the qualification period, it must be disqualified and requalified over something as minor as "add bms to tags."

A simple, fast solution to this would be to only make the metadata of the difficulty with the highest star rating editable, and have any lower difficulties copy the metadata off of that diff. This way no extra parsing or files are needed, and it should be a quick fix, but make metadata management a lot easier.

A more thorough solution to this would be to have a separate Metadata file, which is simply a part of the set that holds all the relevant metadata. I imagine this is much less trivial than the other solution to implement, but I felt I'd still bring it up since it would allow to change metadata without affecting a map's qualification status. Since metadata isn't directly related to a map's quality, disqualifying over a minor metadata issue is a bit over the top, but currently the only solution available. This would add a great alternative.

**Comment by smoogipoo** [comment]
This isn't quite a simple fix. It is planned for / the structures are already in-place for it in lazer.
