### ISSUE TITLE
having discord open causes mini jitter lags every so often while playing mania

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-stable-issues#238]
I've tried disabling discord rich presence, but it doesn't help
let me know if you want a performance.log or something
having discord closed solves it, but yea
version: b20191204cuttingedge

**Comment by peppy** [comment]
- Disable the discord in-game overlay.
- Make sure your discord window is minimised and not running any gif animations.
- Ensure osu! is running exclusive full screen.

Closing as not-our-issue, but feel free to reply if you need more advice.
