### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by Kaizeralti** [ppy/osu-stable-issues#239]
I managed to download osu! on my mac (High Sierra 10.13.3) after a lot of work and when i try to create my account from the page it tells me to download the game, even if i click on create account inside osu! it still tells me to download the game

**Comment by peppy** [comment]
You may be on a very old version of osu (known as stable-fallback). Please confirm this first of all (it should show you at the bottom of the settings pane).

You have two options:
- Use [osu!lazer](https://github.com/ppy/osu/releases/download/2019.1205.0/osu.app.zip) instead. If you're not that interested in global leaderboards, lazer is already a fully-fledged client which runs well on all operating systems.
- Use [osu!lazer](https://github.com/ppy/osu/releases/download/2019.1205.0/osu.app.zip) to create an account, then use stable-fallback as you are. Not really my recommendation as it is very limited in features (and will not exist soon).

**Comment by Kaizeralti** [comment]
yes, i do have stable-fallback but i was wondering if it was possible for
me to create an account on someone elses computer and then log in in my own
computer?

**Comment by peppy** [comment]
I gave you instructions above on how to make an account. Please follow them.

**Comment by Kaizeralti** [comment]
I downloaded Lazer and made my account there but it will not verify my
account when playing in the older version, it shows a message to verify my
account, i click on it, sends me to a webpage which says your account has
been verified, i go back to osu and it still tells me to verify

**Comment by Kaizeralti** [comment]
this is what it shows me

**Comment by peppy** [comment]
Sorry but you've hit the limitations of support for stable-fallback. I'd recommend using lazer for now. It is mostly functional minus global leaderboards.

**Comment by Kaizeralti** [comment]
welp too bad, thanks for the help anyways :)
