### ISSUE TITLE
Beatmap deleted himself

### ISSUE THREAD

**Issue by Zenku6767** [ppy/osu-stable-issues#241]
I was mapping for 3 hours and wanted to play solo so i left the editor and played a little bit solo after playing solo i wanted to continue the editing and as i started the map everything was deleted >:(

**Comment by peppy** [comment]
The editor does not just delete beatmaps. Are you sure you aren't looking at the wrong difficulty?

**Comment by peppy** [comment]
Closing as we have no idea what happened here. Please provide logs or otherwise if you can reproduce this.
