### ISSUE TITLE
Incorrect "0 star" ratings for beatmaps

### ISSUE THREAD

**Issue by Morilli** [ppy/osu-stable-issues#244]
I caused a GSOD a while ago, and apparently osu! was running in the background while it happened, because afterwards, my database was corrupt and all beatmaps had to be re-processed. This was not an issue besides the waiting time, but now some maps are showing 0 stars as difficulty, even though it says differently everywhere else.

For example [this map](https://osu.ppy.sh/beatmapsets/539221#osu/1267365), specifically Emilia's difficulty, is displayed as 0 stars in game, but as 6.68 on the website.
I tried switching from cutting edge to stable and back, deleting and redownloading the map and even deleting the osu!.db and letting it get re-created, none of which helped. I therefore assume this is a universal issue, but I'd be happy to provide more information in case this can't be reproduced.

**Comment by peppy** [comment]
only specific maps?

**Comment by Morilli** [comment]
Yes, only very few maps have this issue; most maps display everything just fine. Every map that had this issue seems to also have a bpm of infinity at some point, although not all beatmaps with infinite bpm have this issue.

**Comment by peppy** [comment]
Could you provide a list of at least a few of these beatmaps so we can cross-check?

**Comment by Morilli** [comment]
Sure. Actually most of them are Acid Rain maps from the last aspire contest, so I can't link them here, but the other ones are:
``Emilia'sC9H13NO3`` from https://osu.ppy.sh/beatmapsets/539221#osu/1267365, 
``Hey jia`` and ``NiNo's Aspire`` from https://osu.ppy.sh/beatmapsets/537048#osu/1529757 and
https://osu.ppy.sh/beatmapsets/631235#osu/1332830 (only one diff).

**Comment by peppy** [comment]
Fixed in upcoming cutting edge build.
