### ISSUE TITLE
Ctrl + w carries over onto game

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#247]
Not really sure how to word this, but when closing some other window/application with ctrl + w, when that window closes, the ctrl + w also applies on osu. Not an important issue, but gets annoying sometimes because I have to keep reopening channels.

Video: https://streamable.com/w9ar1 (I press ctrl + w on a chrome window, it closes, but the BanchoBot tab also closes)

**Comment by peppy** [comment]
Cannot reproduce. Probably something specific to your system.

osu! doesn't handle input when not in focus.

**Comment by Magnus-Cosmos** [comment]
I assume my osu! goes into focus when I close the window above it, which I guess isn't normal?
