### ISSUE TITLE
[Editor] False "Unused files found" warning when updating maps.

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#248]
Whenever people try to update a beatmap which uses more than one background file an warning get's displayed:

"There are files in this beatmap's directory that are not used! Do you wish to remove them?

[File Link]"

The problem here is that these files are actually used in different difficulties of a beatmap. It also happens with one of my beatmaps: https://osu.ppy.sh/b/984417

Another thing which came to my mind while writing this report, is that when there are really unused files in the beatmap directory, this warning does not appear. 
The best example would be an unused hitsound file. No warning appear, AiMod doesn't show anything and it can happen (and did already in the past) that maps with unused hitsound files got qualified.

**Comment by smoogipoo** [comment]
May or may not be an easy fix. Erring on the side of not being an easy fix due to the way that beatmaps work in stable. Maybe we can use lazer as a post-processing step BMS-side to remove unused files automatically.

**Comment by peppy** [comment]
If this is considered "annoying" removing it altogether would be best. Making it work over multiple difficulties or with hitsounds is out of scope due to complexity.

**Comment by Feerum** [comment]
Sounds fair to me to remove the warning from the stable client since it mostly only appear as false warning.
And I also like smoogis idea for lazer.

**Comment by smoogipoo** [comment]
Can anyone else confirm that this is an annoying feature? Would like more than one opinion on this.

**Comment by Leniane** [comment]
Yeah it gets quite annoying if you update your map multiple times and seeing it pop up constantly for each update

**Comment by peppy** [comment]
I think for now we'll leave this in place, as it *does* still catch cases where unused files are present. As it's only on upload, it's only a minor annoyance.
