### ISSUE TITLE
Timing using the tap button creates timing points with floating-point ms values

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu-stable-issues#249]
title says it all. it causes things to be off by 1 ms when the float is .5 or more.

**Comment by peppy** [comment]
0.5ms inaccuracy is acceptable. we may revisit this in lazer but it's pretty pointless in the scheme of things.

**Comment by STCapricorn** [comment]
I was thinking it could be locked to a integer for now, but if you say so.
