### ISSUE TITLE
Osumania 0.01x scroll speed does not work

### ISSUE THREAD

**Issue by Yoshiap** [ppy/osu-stable-issues#25]
Despite attempts to fix multiple times now, this feature still does not work as stated. [Here](https://osu.ppy.sh/beatmapsets/1032908#mania/2159579)'s an example map to illustrate this point.

If you do decide to fix this, it would be nice to also allow scroll speeds over 10.0x, which is also capped right now.

**Comment by nl-tatatat** [comment]
This will also be immensely helpful in taiko as well, with at least 20x scroll speeds allowed.

**Comment by MillhioreF** [comment]
This would be possible to change, but is not currently planned to be supported in lazer so I'm not sure it's a good change to make right now. Probably best to get an OK in #osu-lazer before moving on with this.

**Comment by nl-tatatat** [comment]
The only current workaround for this is to either change the BPM (which is a HUGE NO-NO), or to change the base slider velocity multiplier (can also be a big no-no)

**Comment by Yoshiap** [comment]
It's worth noting that this change was supposed to be already formally supported in mania without .osu editing, which you can see by being allowed to input 0.01 into the timing menu in game. I'll try to find the previous PR or changelog originally stating this change, but I haven't has luck so far

**Comment by smoogipoo** [comment]
It is/will be supported in lazer. This was supposed to be working (I remember relaxing limits a while ago), but there's another limit somewhere, perhaps in beatmap parsing.

**Comment by MillhioreF** [comment]
Fixed in next cutting edge.

**Comment by nl-tatatat** [comment]
Can we also get this for taiko? 0.01 to 20 scroll speeds? 0.1 isn't slow enough, and 4 is DEFINITELY not fast enough. (Not even 10, the current hidden hard cap is fast enough)

**Comment by smoogipoo** [comment]
The values were decided via a ranking criteria update and not an arbitrary decision. You would need to propose such a ranking criteria change for that to happen, but this issue was a bug.
