### ISSUE TITLE
Unset frame limiter

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-stable-issues#251]
Looks like my frame limiter got... unset? No manual editing happened.  
Noticed on b20191210cuttingedge, persisted after restarting for update on b20191211cuttingedge.

![b20191210cuttingedge](https://user-images.githubusercontent.com/4985725/70565266-00c05000-1b92-11ea-81bf-88f68514dd52.jpg)  
![b20191211cuttingedge](https://user-images.githubusercontent.com/4985725/70565261-fe5df600-1b91-11ea-9c29-2dd5be74d20b.jpg)  

The actual behavior is 30fps when unfocused, 120fps on focused, 240fps in gameplay.

Would upload my cfg file, but I'm afraid that may compromise my account. Here are a few probably useful entries however:
```
FrameTimeDisplay = 0
CustomFrameLimit = 240
ForceFrameFlush = 0
FrameSync = Custom
```

This is an osu! install I often use for tournament streaming purposes, by the way, only ever used on Windows 10 1903 (VM) and a 60Hz monitor.

**Comment by peppy** [comment]
what are you expecting it to be?

**Comment by ThePooN** [comment]
I don't really know. It seems like it's set to a custom frame limit, so I would say "Custom"?  
I never set it on my own though, so that was probably set by osu!tourney.

**Comment by peppy** [comment]
Right, the blank entry in the dropdown is correct. That means you're using "custom", which will no longer display in the interface.

**Comment by ThePooN** [comment]
So this is the expected behavior? I feel like a custom value set by osu!tourney should also be handled properly in the options back in normal client, but fair enough.

**Comment by peppy** [comment]
I've pushed a change to show non-blank in the case you have a custom limiter set. It will only show if you manually set it in the config, otherwise will not be in the list.

**Comment by ThePooN** [comment]
That's indeed what I expected in the first place. Thanks!
