### ISSUE TITLE
Osu!mania free star rating medals bug

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#252]
> ![](https://cdn.discordapp.com/attachments/463638143422169088/654822995860389918/screenshot029.jpg)
> ↑
> As you can see, it is 4 stars
> but...
> 
> ![](https://cdn.discordapp.com/attachments/463638143422169088/654823014197755914/screenshot030.jpg)
> 
> I still got the 7 star medal because it is 7 stars without the 4k mod

↑ This is the proof

You can get 7 star medals for playing a ranked standard map in mania that is 7 stars with dt and play it with the 4k mod and make it 4 stars (this applies to all other star ratings as well) 
...this has existed for more than a year, idk how long since before I started playing though

**Comment by Remyria** [comment]
it also seems you can get the FC medals while getting 100's under certain conditions and that's really weird (Getting anything below a 200 remove the FC status from the plays in mania)

https://cdn.discordapp.com/attachments/639515567233171478/654706175035572224/screenshot003.jpg

**Comment by WinterIsPretty** [comment]
https://cdn.discordapp.com/attachments/463638143422169088/654822995860389918/screenshot029.jpg
/\
As you can see, it is 4 stars
but...

https://cdn.discordapp.com/attachments/463638143422169088/654823014197755914/screenshot030.jpg

I still got the 7 star medal because it is 7 stars without the 4k mod

**Comment by peppy** [comment]
This has been resolved. Thanks for pointing it out.
