### ISSUE TITLE
Status of maps not updating or changing to wrong status

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#253]
Whenever I import more than 30 or 50 maps I download all the maps that are imported have no status, I need to do status!=r status!=l status!=p status!=q and go through hundreds of maps for them to update.

**Comment by peppy** [comment]
Status updates require an active bancho connection, and may take a few minutes if you are importing large numbers of beatmaps. I've tested locally and it works fine, though.

**Comment by WinterIsPretty** [comment]
I use osu!direct with a full internet connection, this only happens when I download many beatmaps at once and import the maps when I exit the direct tab.

**Comment by WinterIsPretty** [comment]
Another side effect of this is that maps get put in the wrong status like a loved map would be ranked until I update it with the global ranking leader board turned on

**Comment by peppy** [comment]
Next time this happens could you please try restarting osu!, going into song select and waiting a minute. Then see if they get categorised correctly.

**Comment by WinterIsPretty** [comment]
I left 200 maps not updated after I downloaded a lot of loved maps so I will see if they are updated yet

**Comment by WinterIsPretty** [comment]
It did update most of the maps but it left about 50 maps with no status (The maps are mostly random ranked maps)

**Comment by WinterIsPretty** [comment]
This is an example of a map that wasn't updated, very ironic for it to be this map lol

https://cdn.discordapp.com/attachments/463638143422169088/655825630537056266/screenshot036.jpg

**Comment by peppy** [comment]
Can you explain which part of the screenshot is showing this issue?

**Comment by xenallio** [comment]
Answering for Winter: The search bar is saying !ranked, meaning the map was marked as "[unknown](https://osu.ppy.sh/ss/14332502/1616)", "unranked" or "[not submitted](https://osu.ppy.sh/ss/14332494/8b10)" because pressing it. It then requires to switch to a online leaderboard to update the status (any leaderboard other than local)

Probably connected to this issue: Some maps, regardless of how many times I update their status, they just won't stay ranked and reset their status to "not submitted" at every launch ([exemple](https://osu.ppy.sh/b/1360912) for me at least, unconfirmed if it's everyone or just local).

**Comment by WinterIsPretty** [comment]
I think that may be the case, I didnt see peppy's comment until now sry about that

**Comment by WinterIsPretty** [comment]
it seems like every other month or two it goes through all my maps and changes them to status' that aren't correct and even doesn't show my rank for the map I have played. Like it reverts back to when this started.

**Comment by peppy** [comment]
@xenallio *every* launch? If this is reproducible, please provide your database file (osu!.db).

**Comment by WinterIsPretty** [comment]
I can provide mine, it happens every launch for me

**Comment by WinterIsPretty** [comment]
I found out the bigger part of this issue so I made #342

**Comment by stevefan1999-personal** [comment]
![screenshot049](https://user-images.githubusercontent.com/29133953/113407096-40dac000-93df-11eb-9050-02a5b0b16989.jpg)

Please reopen the issue, [this map](https://osu.ppy.sh/beatmapsets/999645#osu/2090843) itself is ranked but is considered pending
