### ISSUE TITLE
You can't do creator!=[name]

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#255]
When you want to exclude a beatmap creator it only searches for that author. I wanted to exclude graveyard beatmaps I have made (because I have made more than 100 maps) but I can't do that.

**Comment by peppy** [comment]
Can you show us what you're seeing?

**Comment by WinterIsPretty** [comment]
https://cdn.discordapp.com/attachments/463638143422169088/655020027975696384/screenshot031.jpg

**Comment by WinterIsPretty** [comment]
I don't think cutting edge mode makes a difference in this situation

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
