### ISSUE TITLE
Can't reset universal offset

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#258]
If I move the universal offset amount by any number I find it extremely difficult to put it back to 0ms and I have to put my sensitivity on the lowest and slightly move it to the center.

**Comment by InvisibleSymbol** [comment]
clicking on the glowing part will reset the offset to 0ms
![](https://i.fiery.me/84xrc.gif)

**Comment by WinterIsPretty** [comment]
Bruh I wish I knew that about a year and a half ago
