### ISSUE TITLE
The ability to either leave a channel fully or temporarily

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#259]
Since now the osu chat room goes away when you exit out of it maybe you could make it so you can't leave out of the channel fully unless you leave by going to the channel selection tab by pressing that yellow plus button

So you can make it so when you close it in osu, it comes back next time you join or you can leave completely by going to the selection spot.

I have this problem when I want to close the osu!mania channel so I clear my tabs but when I want to come back I need to go back to the selection tab and search for it again

- Channels that you are in should appear up top for ease of access

**Comment by smoogipoo** [comment]
Too big of an implementation overhead for stable, sorry!
