### ISSUE TITLE
In-game notifications for new maps getting ranked

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#260]
For osu you should be able to enable notifications for ranked maps in standard or mania or taiko or ctb. They appear in the announcements but it is hard to find them mixed in with the 1st place plays.

You could also instead of that make it where you can toggle where in the announcements channel it mentions your username whenever there is a new map ranked

**Comment by smoogipoo** [comment]
Too big of an implementation overhead for stable, sorry! (We are not implementing new features).
