### ISSUE TITLE
Osu!direct not updating downloaded maps sometimes

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#261]
I hope I'm not bothering you with all my submissions

Whenever I download maps using osu!direct sometimes it permanently displays some beatmaps that I have already previously downloaded, or even more rarely doesn't show the maps I haven't downloaded

https://cdn.discordapp.com/attachments/463638143422169088/655183798077751306/screenshot032.jpg

**Comment by smoogipoo** [comment]
Click the “show already downloaded” checkbox.

**Comment by WinterIsPretty** [comment]
That isn't my problem, also show already shows literally everything I have downloaded, I am having a problem with beatmaps not registering they are downloaded
