### ISSUE TITLE
Beatmaps sometimes not updating after download in osu!direct

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#264]
I'm gonna do this again because you didn't understand what I was saying the first time.

Whenever I download maps using osu!direct sometimes it permanently displays some beatmaps that I have already previously downloaded, or even more rarely doesn't show the maps I haven't downloaded

https://cdn.discordapp.com/attachments/463638143422169088/655183798077751306/screenshot032.jpg

I don't want those beatmaps to show I have them downloaded already they shouldn't be up there. If I keep my screen on there overnight you get more maps that are already downloaded but still pop up for no reason.

**Comment by WinterIsPretty** [comment]
I don't want to see any maps up there, I (should) have every map downloaded because I took the time to download 60k maps

**Comment by peppy** [comment]
This is a very hard problem to solve. We may be able to do something on lazer, but this cannot be easily resolved in stable (the server does not know what beatmaps you have on your local install).

**Comment by WinterIsPretty** [comment]
good thing i guess, I ran out of supporter recently
