### ISSUE TITLE
Pressing "clear all" in your notifications doesn't clear all

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#265]
It only clears what is visible not "all"

**Comment by peppy** [comment]
what notifications are you talking about?

**Comment by peppy** [comment]
if you mean the web, then this is the wrong place to report this. also, we are aware and working on a solution.

**Comment by WinterIsPretty** [comment]
Oh sorry

**Comment by WinterIsPretty** [comment]
I hope it gets fixed soon, it takes a while to clear out 200 notifications of the same text I have already seen in-game
