### ISSUE TITLE
Web chat messages sent by users not logged into client or IRC link to /u/-1 when attempting to view profile via User card menu.

### ISSUE THREAD

**Issue by Dontmakemeeatyou** [ppy/osu-stable-issues#266]
If a user using web chat sends a message to another user or channel while not logged into client, the user card context menu will direct to https://osu.ppy.sh/u/-1 when attempting to view profile. 

From quick testing, as soon as the user logs into the game any messages sent from web will work correct. 

Messages sent before the user logged on will still direct to /u/-1 even after logging in.

Could potentially inhibit moderation, also kinda annoyin' ;p.

**Comment by peppy** [comment]
Fixed in next cutting edge release.
