### ISSUE TITLE
Audio stutters due to recent environment changes

### ISSUE THREAD

**Issue by peppy** [ppy/osu-stable-issues#267]
As reported [here](https://twitter.com/youicyk/status/1205766179937120256).

No changes have occurred at osu!'s end and on investigating I cannot find a feasible cause from our code.

Looking for more information from people who can reproduce:

- Some users have said this only happens after weeks of PC uptime. Please confirm/deny
- After this starts happening, can you reproduce it after restarting osu!?
- Does it still happen if you completely close discord (including from system tray)?
- Does it happen if you switch audio devices?
- Can you see any stutter on the frame display (Ctrl-F11 twice) when this happens?
- What audio device are you using?

Log files are also appreciated.

**Comment by VINXIS** [comment]
I had this issue for almost a year now, I'm not sure if you remember but I had made a tweet with [this video](https://streamable.com/ycrf6) and after that tweet someone suggested I use [InSpectre](https://www.grc.com/inspectre.htm) and it had seemed to fix all of my stuttering issues. I can answer all of the questions except for the first one

> After this starts happening, can you reproduce it after restarting osu!?

Yes, also tried cutting edge, stable, beta, and fallback. Restarting in any of these gave me these issues

>Does it still happen if you completely close discord (including from system tray)?

Yes

> Does it happen if you switch audio devices?

Yes, and the following audio drivers I have used are Asus Xonar DSX, Steinberg UR12, and PreSonus AudioBox iOne. The following peripherals I used are Logitech Z506 and Sennheiser HD579 (this should answer the last question too)

> Can you see any stutter on the frame display (Ctrl-F11 twice) when this happens?

I had seen this when I had the stutters.


This is a performance.log file I found from May 14, 2019 that I had sent to Nyquill regarding this issue https://cdn.discordapp.com/attachments/515329811091030026/578012216746311680/performance.log

**Comment by peppy** [comment]
@VINXIS can you still repro this? an updated video would be great if so.

**Comment by VINXIS** [comment]
Really? Is this one related then because I thought they were the same thing or at least connected since they both were fixed for me at the same time https://streamable.com/48fib

If this one is related I can still try to reproduce it, if not then I'll take my leave

**Comment by ItzFireable** [comment]
This problem started happening to me after the FPS option changes, the audio rewinds a few seconds back but my GPU usage is ~60-70% on osu! without anything else open (Vega 56) which isn't normal, was ~10% before the change. It only happens on osu!, any other game is completely fine.

> Some users have said this only happens after weeks of PC uptime. Please confirm/deny
Confirm, although partially (Sometimes helps, sometimes not)
> After this starts happening, can you reproduce it after restarting osu!?
It happens every time, so yes.
> Does it still happen if you completely close discord (including from system tray)?
Yes, it does.
> Does it happen if you switch audio devices?
Happens still.

They stopped right now as I restarted my computer (didn't help before), I'll comment again after it starts happening again (with performance.log and video proof)

**Comment by peppy** [comment]
Thank you for the GPU util% reports. Please keep tabs over time and let me know when it starts to happen again.

**Comment by Xelostar** [comment]
For me I get these stutters, but also in the game itself. At least once almost every play session. Especially big ones I clearly saw that it was as ifthe game went back in time and forward about 4x. You could see the circles getting bigger and smaller for half a second or so.

I have not restarted my computer in a long time. I've always put it in hibernation as well. I do see problems decrease when I close Dropbox, which might be because of CPU usage. I am not sure if it happens with other games as I don't play too many other, but I haven't experienced something like this in other games yet. Not sure if related to Discord. Will try playing with Discord closed later. I sually play with a Turtle Beach Earforce P11 headset, but sometimes I play with my (?) speakers. I don't think switching audio device has an impact but not 100% sure.

**Comment by WinterIsPretty** [comment]
I haven't had this problem and I'm running on the recent version of windows. I do have lag spikes but I think that happens due to my computer being bad; it clears out after a while

**Comment by peppy** [comment]
Note that this thread is not about any "stutters" that aren't related to audio rewinding about 100ms and playing a second time. See the video in the linked tweet for an example.

I need people that can reliably reproduce this so I can do further targeted testing.

**Comment by WinterIsPretty** [comment]
So only audio not both?

**Comment by peppy** [comment]
Only audio. See the video and description. This is a very specific request.

**Comment by manmathew** [comment]
An update. Restarting the pc is the only way to fix the issue since for me it starts later in the osu session. This time I restarted without letting discord open, and I haven't been having any issues for longer than usual. I have tried before without discord, however that was where I closed discord in the tray after windows booted. I currently have discord open, but the rich presence is disabled in osu, and it's running fine so far. So I guess I'll update here later if the problem comes back.

**Comment by peppy** [comment]
If it comes back, please don't reboot and get in touch so I can get you to run some more checks.

**Comment by manmathew** [comment]
I wasn't getting any of the rewinding so I tried making the workload on the computer larger by opening more tabs in chrome, photoshop, and streamlabs obs. The chrome tabs and photoshop with a skinning psd didn't do anything, but streamlabs did. It wasn't only when recording, just having it open causes the rewinding to happen. I have 2 35ish second clips on the same map that I produced from this, but idk how much that will help. I haven't rebooted so I'd like to know what I can do from here to help.

**Comment by peppy** [comment]
Please upload the clips at least.

**Comment by manmathew** [comment]
[https://drive.google.com/open?id=1Zt6Hg0WnmbWSBD0auWXVKIHaaDb2O68J](url)
First clip I still had photoshop open, but as you can see in the second clip, closing it made no difference.
[https://drive.google.com/open?id=1jukjug035rb0cn6ZEDNB21R6PpeKWlZt](url)

**Comment by peppy** [comment]
I've made some adjustments to cutting edge, please give it a try after getting into a bad state and see if it helps.

**Comment by ItzFireable** [comment]
Stutters started happening again, here's a video recording with the stutters + task manager usage + frame display; https://streamable.com/bzkr9

Optimal FPS, 1680x1050 resolution, borderless windowed

**Comment by peppy** [comment]
Could you please try switching to cutting edge?

**Comment by manmathew** [comment]
I've updated cutting edge and recorded the experience starting from having discord, chrome, photoshop, streamcompanion, and streamlabs all open. I closed them all in reverse order, and I'll upload it if my phone allows. For now, I have the performance log to upload in case it helps.
[performance.log](https://github.com/ppy/osu-stable-issues/files/3974589/performance.log)

**Comment by peppy** [comment]
From your performance log I can see lots of random high frame times, but nothing really repeating. Also performance.log doesn't help with the audio rewind issue, so I'll be waiting for your video.

**Comment by manmathew** [comment]
[https://drive.google.com/open?id=1FM6A53blFfmouISAJgdW5BagcDR4CS1Z](url)
Took a while to upload, but now it's there. Not sure why it changed, but yesterday the issue disappeared after closing streamlabs.

**Comment by ItzFireable** [comment]
I just tried cutting edge, GPU usage is still high but framedrops ended.

**Comment by peppy** [comment]
Is GPU usage only high when osu! is open?

**Comment by peppy** [comment]
We've pushed a fix to cutting edge to hopefully resolve this. Please test it out.

**Comment by InvisibleSymbol** [comment]
Just to be sure you are aware of this on some systems the latest cutting edge is completely broken (https://clips.twitch.tv/SolidStormyBearFUNgineer)
On my personal system this issue only occurred once, never after that (which makes me believe that this is a server side switch...?)

**Comment by peppy** [comment]
I'm looking for feedback on whether this solved the issue in this thread. Please post other issues as new issues.

**Comment by peppy** [comment]
Closing as fixed on cutting edge. Other issues will be resolved separately.
