### ISSUE TITLE
Reduce transparency of "ready" player names

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu-stable-issues#268]
In multi, when you click "ready" you bar goes green and the name container tints green.
However, it's really hard to notice the difference in Team Vs with seasonal backgrounds.
I suggest the transparency of the rectangle that contains the name is reduced slightly so it's easier to see who isn't ready.

**Comment by smoogipoo** [comment]
Visuals are generally out of scope for the sort of issues we're looking to fix on stable.
