### ISSUE TITLE
Clear Local Scores button instantly deletes local scores.

### ISSUE THREAD

**Issue by GriffinOwO** [ppy/osu-stable-issues#27]
This results in permanent deletion of all local scores on a map which can be incredibly annoying if hit by accident. Hitting it by accident is surprisingly common because of where it is located. (https://pogu.s-ul.eu/nCjF3Rk4)

**Comment by Magnus-Cosmos** [comment]
Adding a confirmation to this would be greatly appreciated, same for the Delete all unranked maps button, having it ask the user to confirm would help prevent accidental presses.

**Comment by MillhioreF** [comment]
Confirmation added in next cuttingedge.

**Comment by Magnus-Cosmos** [comment]
Could this be done for the "Delete all unranked maps" button as well, since my game just crashes every time I accidentally click it

**Comment by MillhioreF** [comment]
Make a separate issue rather than a comment here please.
