### ISSUE TITLE
Notes constantly stacking on top of each other in the editor of cuttingedge 20191219.1

### ISSUE THREAD

**Issue by HDJump** [ppy/osu-stable-issues#271]
![editor bug](https://user-images.githubusercontent.com/59057209/71180923-83de5600-22b6-11ea-99c7-f9a32835a318.gif)

Since the most recent update for cuttingedge, whenever I try to stack a placed note on top of another note, the two notes constantly change places, even though they are placed in different time.

**Comment by peppy** [comment]
Fixed in cutting edge, please confirm.
