### ISSUE TITLE
Discord RPC not working (cuttingedge b.20191220.3 build / stable b20191220.2)

### ISSUE THREAD

**Issue by tasnimtamim** [ppy/osu-stable-issues#272]
The "Discord Rich Presence" under Integration tab on osu! options is enabled. Yet Discord RPC is not working. That little box thing beside "Playing osu!" text won't show up.

Here is a screenshot of it: https://i.imgur.com/P9G8kbI.png (cuttingedge)
https://i.imgur.com/a1rj8uz.png (stable-latest)

I've checked all options on my Discord app and there's nothing I can't find that has anything to do with RPC that I can toggle. Still fiddled with anything I can find and still same issue. [However other games work](https://i.imgur.com/UyVvwy7.png). [Even osu!lazer works](https://i.imgur.com/uX4EcmH.png).

It definitely used to work few weeks ago. Now it doesn't.

**Comment by peppy** [comment]
Can you attach your `network.log`?

**Comment by peppy** [comment]
Actually I can seem to reproduce this. Will investigate.

**Comment by tasnimtamim** [comment]
> 
> 
> Can you attach your `network.log`?

[network.log](https://github.com/ppy/osu-stable-issues/files/3988601/network.log)
Here it is

**Comment by tasnimtamim** [comment]
the new b20191221.1 cuttingedge update fixed it! https://i.imgur.com/RARMA0O.png
