### ISSUE TITLE
"View Profile" doesn't works to themself

### ISSUE THREAD

**Issue by AlexouWolfy** [ppy/osu-stable-issues#273]
When we click on the "View Profile" button, in the chat by clicking on our username, the game redirect to `https://osu.ppy.sh/users/-1` and not `https://osu.ppy.sh/users/<userID>`
The "bug" only happened when i did it to myself and not another person.

**Comment by Dontmakemeeatyou** [comment]
Related to https://github.com/ppy/osu-stable-issues/issues/266 

Didn't notice this when testing myself.
