### ISSUE TITLE
Last Played Bug

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#274]
Shouldn't every song marked as last played 1/1/0001 be in last played never instead of over 6 months ago

Every map I haven't ever played is set to last played 1/1/0001

**Comment by smoogipoo** [comment]
Please give a screenshot.

**Comment by WinterIsPretty** [comment]
![screenshot041](https://user-images.githubusercontent.com/52920930/71368472-ab127d00-256d-11ea-9ff6-fe691c4a6be2.jpg)

I have not played 61k maps

![screenshot042](https://user-images.githubusercontent.com/52920930/71368482-b49be500-256d-11ea-8e31-f4139d82bd46.jpg)

In a multiplayer lobby it says that I have last played it in 1/1/0001
