### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#275]
I deleted this over a month ago and it still keeps trying to access it, this is annoying because it keeps looking for new files everytime I open osu

![20191221_202756](https://user-images.githubusercontent.com/52920930/71316129-ae541e80-2430-11ea-88cb-b5277a7aa8dd.jpg)

The image is sideways for some reason lol

**Comment by peppy** [comment]
Try restarting. It's definitely still there.

**Comment by WinterIsPretty** [comment]
I did many times, it's been like this for about a month

**Comment by WinterIsPretty** [comment]
Would it be possible for it to stop checking after osu has been closed?

**Comment by peppy** [comment]
I don't follow. You need to remove the file.

**Comment by WinterIsPretty** [comment]
The file has been removed from my computer for a while, osu is requesting to use it for longer than it should
