### ISSUE TITLE
Random lag spike

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-stable-issues#276]
I'm running osu! (Stable 20191221.3) on Wine (5.0-rc1) on Arch Linux. To provide more accurate result, I have closed all resource-consuming processes and processes which can cause spike (I can create a cleaner environment if this is not enough).
I have tested with Power-saving profile (2 * 60 = 120 FPS) which my PC can run stably (since my PC can go up to more than 350 FPS in optimal).
Map I tested: https://osu.ppy.sh/beatmapsets/235836#osu/546514 (no storyboard and no video)
I ran the test with NF turned on and not click anything (dim 85%).

- When not doing anything (not moving mouse or clicking, just let it run):
![screenshot018](https://user-images.githubusercontent.com/16283764/71317237-9fad4c00-24b0-11ea-9c68-d49d7206f77d.png)
I see the blue ones spiking up which mean "Sleep", so I think there maybe some wrong calculation of remaining time to idle.

- When constantly moving mouse in a circle (but not clicking):
![screenshot017](https://user-images.githubusercontent.com/16283764/71317254-c7041900-24b0-11ea-9f02-94252f8bef1c.png)
I see the white ones spiking up which mean "Between frames", I'm not sure about what caused this (maybe input update?).

**Comment by peppy** [comment]
The first screenshot is a non-issue (you'll notice the next frame is making up for the extra sleep).

The second screenshot white area implies overhead of the windows process handling loop. Likely wine or your input stack overhead.

**Comment by huupoke12** [comment]
I just changed the version to cutting-edge to get the perf log:
[osu-lag.log](https://github.com/ppy/osu-stable-issues/files/3992380/osu-lag.log)
The "Sleep" ones don't produce any call stack record, but some of the "Between Frames" do like in the above log.

**Comment by ThePooN** [comment]
What's the version of your Linux kernel?

**Comment by huupoke12** [comment]
5.4.5-arch1-1

**Comment by ThePooN** [comment]
Can you try using `linux-lts`?

**Comment by huupoke12** [comment]
Tried with both `linux-lts` and `nvdia-lts` but the spikes still exists.
Then I even tried to start a session with only Openbox instead of Plasma, those spikes still exists, but somehow it feels less laggy.

**Comment by ThePooN** [comment]
That is because the KDE compositor induces lag.

I recommend reading my article re: osu! on linux btw, I believe it's good knowledge to have: https://blog.thepoon.fr/osuLinuxAudioLatency/ and as this is likely related to your set-up and not osu!, and out-of-scope of the support provided here, I would encourage joining the mentioned Discord and get help there instead.

**Comment by smoogipoo** [comment]
We can't help you here - this isn't an issue with osu!.

**Comment by huupoke12** [comment]
Please don't close this, since this still is an osu! issue, and other people who having the same issue can contribute more useful info instead of creating a new issue.
By the way, I have a new call stack record when playing (actual play) of the same map with the same setting, it can be useful (no mystery setting enabled):
[osu-call-stack.log](https://github.com/ppy/osu-stable-issues/files/3995086/osu-call-stack.log)

**Comment by peppy** [comment]
this is operating system related. this repository is for bug reports. you are welcome to continue discussion in the closed thread.

**Comment by huupoke12** [comment]
@ThePooN 
Completely changed to XFCE and uninstall every KDE-related packages, nearly no improvement.

But I have noticed something interesting: When PLAYING with Optimal/Unlimited profile (which my PC can't even render to its full FPS (only around 375/480FPS) I experience less frequent shutters and they are less severe than when playing with Power-saving profile (120FPS).
This makes me think that the problem maybe on one of these:
1. There is a bug in the code which only being executed when the frames are being rendered enough
2. Scheduler
3. The number on the FPS counter is a lair/The game thinks that the number of frames are being rendered is enough so it stops rendering frames when it's actually not enough. 

Using osu!beta 20191227.2

**Comment by ThePooN** [comment]
can you show what your ctrl f11 graph typically looks like?

**Comment by huupoke12** [comment]
Power-saving w/o video:
![screenshot024](https://user-images.githubusercontent.com/16283764/71544807-0f8e6b80-29b6-11ea-8c95-56040cfb9779.png)

Optimal w/o video:
![screenshot026](https://user-images.githubusercontent.com/16283764/71544817-1e751e00-29b6-11ea-81f0-856e68d5c406.png)


Power-saving with video:
![screenshot027](https://user-images.githubusercontent.com/16283764/71544822-259c2c00-29b6-11ea-827b-552ca176bf3d.png)


Optimal with video:
![screenshot028](https://user-images.githubusercontent.com/16283764/71544825-2af97680-29b6-11ea-8288-1d1ebbf75740.png)

**Comment by ThePooN** [comment]
can you give a more detailed look at your setup, especially hardware ? (CPU, GPU, laptop/desktop, peripherals...)

were these graphs captured during gameplay or while spectating/watching replays? can you screenshot these graphs in the case you haven't done yet?

also try using other USB ports and toggling raw input on/off

**Comment by huupoke12** [comment]
It is already on my profile: https://osu.ppy.sh/users/6326135
Those graph were capture during real playing.
I'm using 2 USB 2 ports at the back for keyboard and mouse.
I've never use raw input in wine since it's broken.

**Comment by huupoke12** [comment]
- These are tested with real playing:
Tried raw input, no change. Tried other ports (USB3) for both keyboard and mouse, no change.
Tried to decrease mouse refresh rate to 125Hz, shutters still exist:
![screenshot030](https://user-images.githubusercontent.com/16283764/71556259-aae01900-2a68-11ea-9194-85222094a8de.png)

- These are tested with watching Auto (shutters are still more frequent and severe with Power-saving):
Power-saving w/o video:
![screenshot035](https://user-images.githubusercontent.com/16283764/71556285-0c07ec80-2a69-11ea-99ba-9729d7e6825f.png)
Optimal w/o video:
![screenshot036](https://user-images.githubusercontent.com/16283764/71556288-132efa80-2a69-11ea-971d-c979a846119b.png)
Power-saving with video:
![screenshot038](https://user-images.githubusercontent.com/16283764/71556290-1e822600-2a69-11ea-9bc6-169b5f299172.png)
Optimal with video:
![screenshot039](https://user-images.githubusercontent.com/16283764/71556291-2215ad00-2a69-11ea-90ea-c39633f29ccf.png)

**Comment by ThePooN** [comment]
Optimal on Auto looks fine here. If you can confirm it is stable only while viewing replays, it's likely related to input handling. Then, can you please try different peripherals?

**Comment by huupoke12** [comment]
I have tested with a cheap generic office mouse and keyboard, no differences:

Power-saving w/o video:
![screenshot040](https://user-images.githubusercontent.com/16283764/71568024-83d02880-2af6-11ea-9359-0a14dcc4d660.png)


Optimal w/o video:
![screenshot041](https://user-images.githubusercontent.com/16283764/71568027-87fc4600-2af6-11ea-88bb-c204c186a399.png)


Power-saving with video:
![screenshot042](https://user-images.githubusercontent.com/16283764/71568032-90ed1780-2af6-11ea-9bc2-74c48af28030.png)


Optimal with video:
![screenshot043](https://user-images.githubusercontent.com/16283764/71568035-93e80800-2af6-11ea-81d5-6066968e459d.png)

**Comment by huupoke12** [comment]
> Optimal on Auto looks fine here. If you can confirm it is stable only while viewing replays, it's likely related to input handling. Then, can you please try different peripherals?

@ThePooN Please note that Power-saving on Auto doesn't stable, I don't think it's only related to input handling:
Power-saving on Auto on CE:
![screenshot044](https://user-images.githubusercontent.com/16283764/71590371-c75c7e00-2b5a-11ea-89eb-fbc75447c961.png)
