### ISSUE TITLE
Toshiba Laptop Turns off after a while Playing osu!

### ISSUE THREAD

**Issue by kravque** [ppy/osu-stable-issues#277]
The latest updates are like weirder, for me it's a huge problem because my laptop started turning off after the latest updates
So i started to look at the temperature of the hardware and there's no overheating from motherboard, cpu, gpu, etc
Tried to use the laptop without the battery and still
Even i tried to test all the RAM sticks using memtest86 and they were fine ?
Like this is weird actually

**Comment by huupoke12** [comment]
Can you check the log in your Event Viewer? In Windows Logs/System. And search for any critical or error and shutdown event.

**Comment by kravque** [comment]
Found this from Windows Event Viewer and i found this in critical and the source was called " Kernel-Power "
The Date is 12/22/2019 12:36:54 PM " before 3 hours for me when i posted "

[Log from Windows Event Log.txt](https://github.com/ppy/osu-stable-issues/files/3992420/Log.from.Windows.Event.Log.txt)

**Comment by huupoke12** [comment]
I mean not just only critical, since they might not have useful info. Please search for nearby errors as well (see timestamps).

**Comment by kravque** [comment]
There's nothing else just these.

[yes.txt](https://github.com/ppy/osu-stable-issues/files/3992437/yes.txt)
[yes2.txt](https://github.com/ppy/osu-stable-issues/files/3992438/yes2.txt)
[yes3.txt](https://github.com/ppy/osu-stable-issues/files/3992439/yes3.txt)

**Comment by huupoke12** [comment]
Hmm, I don't see any useful info here. Can you please use something like [BlueScreenView](https://www.nirsoft.net/utils/blue_screen_view.html) and check if there are any dumps?

**Comment by kravque** [comment]
No, there are no dumps
bluescreen doesn't show at all even.

**Comment by smoogipoo** [comment]
This isn't an issue with osu! - it does not have the capability to shutdown your PC. There are many likely causes for this - is your power plugged in? is the AC actually providing enough power to support the PC, or is the battery constantly draining even with power plugged in? have you updated drivers recently? have you tried reinstalling your drivers? does it happen at a consistent time, maybe windows update? have you tested your ram?

General PC tech support is outside of the scope of things we can help you with.
