### ISSUE TITLE
Vsync frame cap isn't be applied when on Menu and Select Song screen

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-stable-issues#278]
It default to 240FPS instead in the menu and song select.
On the other side, it is extremely unstable when using VSync when playing:
![screenshot021](https://user-images.githubusercontent.com/16283764/71321482-81fdd800-24ec-11ea-9ed3-d4953f2ba8f8.png)

**Comment by peppy** [comment]
The instability while playing is normal for vsync (generally how vsync should behave).

Fixed the menu limiting in next release, though!
