### ISSUE TITLE
Osu keeps searching for files I deleted a month ago

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#280]
I already reported this but it was ignored, for some reason osu keeps searching for a file after I have shut down my computer many times, deleted the files, tried to make a new file with the same name, and repaired osu. 

Why does osu bother to still try to look for a file that has been deleted for so long?

![20191221_202756](https://user-images.githubusercontent.com/52920930/71328426-bb2e4c00-24dc-11ea-8347-391fad2590b8.jpg)

It does it twice because when I had the file it didn't do anything the first time until a little bit after my second time

**Comment by peppy** [comment]
Search for the file. It still exists. Please stop posting here – this is for bug reports, not technical support.

Use windows search to find the files and figure out why they are broken (easiest is to delete them).
