### ISSUE TITLE
Shift-F2 doesn't return to correct collection

### ISSUE THREAD

**Issue by Morilli** [ppy/osu-stable-issues#281]
When having beatmaps filtered by collection, and a map is present in multiple collections, rolling away from it using F2 and going back with Shift-F2 won't necessarily return to the map in the same collection as it was previously selected in (I think it chooses the first occurrence from the top).
Can make a video if my explanation was unclear.

**Comment by peppy** [comment]
This one is not such an easy fix. We'll make sure it works correctly in lazer.
