### ISSUE TITLE
All maps I haven't played show up in "over 5 months ago"

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#285]
The beatmaps now show up as "last played: never" but they don't show up that way in the last played section. I used to have a collection that said never but I don't anymore because there was only 2 maps.

I haven't played 61k maps otherwise I would have more score than xasuma
![screenshot043](https://user-images.githubusercontent.com/52920930/71526748-e975a800-289d-11ea-9ae1-fda6f922ff3e.jpg)

**Comment by WinterIsPretty** [comment]
![screenshot045](https://user-images.githubusercontent.com/52920930/71538222-02f21080-28ed-11ea-8b8b-0ee2e93fd554.jpg)
here is the "never" tab

**Comment by peppy** [comment]
Please test against the next cutting edge release.
