### ISSUE TITLE
Kinda audio surround effect at hitsounds in last cutting edge

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu-stable-issues#286]
Audio playing on hitsounds sounds like it has a surround effect in the last cutting edge build (**b20191227.1cuttingedge**), so it seems like it is something to do with the _bass_ library, since lazer has the same issue at legacy skinning.

The issue is reproducible using the [Yugen Skin](https://osu.ppy.sh/community/forums/topics/365036)

**Comment by aerouk** [comment]
Took a couple videos of the same map being played in cutting edge and stable respectively:

[![](https://iaero.me/i/3FOGJ.png)](https://iaero.me/i/3FOGJ.png)

In the latter audio file (stable), you can see the hitsounds are lot more "punchy" as they should be.

**Comment by peppy** [comment]
could you please turn off game music and provide a waveform comparison vs the .wav files themselves? would be helpful in figuring out what is going on.

**Comment by aerouk** [comment]
Sure. I tried to match them exactly so this is when the waveform first starts to change in each instance: https://iaero.me/i/RedG1.png (note the cutting edge waveform is much quieter too)

Here's another illustration of the lack of "punchiness" I was talking about earlier: https://iaero.me/i/auIPg.png

**Comment by maotovisk** [comment]
if i would describe with only one word i would say that stable sounds is way more "sharp".

**Comment by peppy** [comment]
there's no sharp or otherwise. it either watches the original waveform or not.

**Comment by aerouk** [comment]
I misunderstood what you wanted - the hitsounds in this skin go straight into 100% volume (https://iaero.me/i/yoq5Y.png) which is not what the cutting edge (output2) waveform shows (https://iaero.me/i/RedG1.png)

**Comment by peppy** [comment]
Could you please test the new CE update and see if this is resolved?

**Comment by maotovisk** [comment]
i'm not at home and i'm on my laptop, but i would say the issue is solved. By the way if the fix is easy enough to implement i think you should apply it on lazer, since it has the same problem.

**Comment by aerouk** [comment]
Sounds good to me on the latest CE build 👍

**Comment by peppy** [comment]
Thanks. Closing as resolved for now. Please comment in this issue if you find further issues.

Will apply this same fix to lazer going forward.
