### ISSUE TITLE
Beatmap is not downloading on fresh install

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#288]
Today i build in a new hard drive into my Laptop.
After i installed osu normally it started automatically and started to download beatmaps as it should be.

But one beatmap seem not to download. 
To see on this Screenshot:  https://i.imgur.com/7jpfC8c.png

Since i didn't had anything special i uninstalled the game and tried it again to make sure it's not just on my side.

Problem repeats again. 
It's not a big issue, but i feel it should be reported

**Comment by peppy** [comment]
Thanks for reporting this. I've pushed a fix out to cutting edge.
