### ISSUE TITLE
Clicks not registering but holds are

### ISSUE THREAD

**Issue by joebuss** [ppy/osu-stable-issues#290]
Problem details:
Cutting edge bug seems to allow holds but not register presses, so will register on all but the first hit of a slide. Appears seemingly at random.

First example of the bug can be seen at 0:45, this has been after clicking on a replay.

At 2:00 I am playing the map normally, however at 2:16, you can see it start to fail during game-play.

Because of it failing when I used the replay, I thought it was probably not my setup, and possibly a bug.

Video or screenshot showing the problem:
https://youtu.be/91bWwkKr0xM

osu! version: Cutting Edge 20191229.1

Posted on forums and was told to put it here

**Comment by peppy** [comment]
Same issue as https://github.com/ppy/osu-stable-issues/issues/287. Please help reproduce with the test executable there!
