### ISSUE TITLE
osu!taiko default drum hitsounds has reversed pitch

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu-stable-issues#291]
Current drum hitsound sample has reversed pitch. Don has the sound of high-pitched hi-hat sound and Kat has the sound of low-pitched drums. Has a very large impact on gameplay. 

Suggestion: Swap the hitsound.

Additional: 
osu!taiko are better with drum sounds, so advise to switch the hi-hat sound with another sound.

**Comment by cl8n** [comment]
if it's at all possible to get taiko-specific defaults for this sampleset (like the normal sampleset currently has), I think that'd be even better. the current drum sounds, even if swapped, feel out of place since they aren't made to sound like a taiko drum

**Comment by peppy** [comment]
i think switching them around is fine for now. we can consider new samples for lazer.

**Comment by peppy** [comment]
Please test the mapping on next cutting edge release.
