### ISSUE TITLE
cutting edge: the never played category k i n d a works

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#293]
It only works for local beatmaps not maps you played with no local score

![screenshot047](https://user-images.githubusercontent.com/52920930/71637173-5f617280-2c02-11ea-8f80-6cbd89c76bb2.jpg)

as you can see I have played that map once, but it has no local scores since I switched computers so it is in the never played category (same thing with like 100 other maps)

**Comment by peppy** [comment]
Never played is local to the system.
