### ISSUE TITLE
.osu and .osb files potentially corrupted by the game (zero byte characters in file)

### ISSUE THREAD

**Issue by MikasaSerket** [ppy/osu-stable-issues#295]
![691EAFF0-8F1C-481D-B6B7-E2E2640E0658](https://user-images.githubusercontent.com/59469578/71715229-b8701700-2e4b-11ea-95c7-0e294cb2b9e6.png)

I was offline mapping and I created a new difficulty as well as a storyboard for my already uploaded map

[Map in question](https://osu.ppy.sh/beatmapsets/395503#osu/2263567) 

Come back the next day, the difficulty is there but with nothing in the editor as well as no background but the sr and diff settings still intact. However, eventually the difficulty just didn't show up as being part of the set at all/ In addition to that, the storyboard was also gone. 

The thing is, in the folder itself the .osb and .osu of my difficulty are still there it's just, blank with nothing in it, it's still highlight-able though and I tried copy and pasting what I had highlighted but to no avail. The storyboard files were still in the beatmap folder as well.

I’d like to know if there’s a way to get my progress back and to further prevent something like this from happening again

I am currently on the stable version of osu

**Comment by dudehacker** [comment]
This occurred to me when I was working in editor mode and suddenly my PC shutdown due to blackout and lost all progress.

I suggest a simple version control system which saves the last update as a hidden file in song folder which doesn't show on the web but still saved on osu backend server. only mapper can download this hidden save file but not other players.
Mapper can revert to this save file in case of this problem occurs, and also helps to visualize changes in editor when applying mod

**Comment by peppy** [comment]
@dudehacker can you confirm you saw the same "file empty but full of spaces" behaviour?

**Comment by dudehacker** [comment]
> @dudehacker can you confirm you saw the same "file empty but full of spaces" behaviour?

yes, same as in the screenshot above

**Comment by peppy** [comment]
Thanks. I don't suppose you still have a copy of the file>

**Comment by dudehacker** [comment]
unfortunately, i didn't keep the file. 
and the logs under osu\logs don't have history of it either.

is there another log location i can look for it?

**Comment by peppy** [comment]
No, I don't believe it will be anywhere. Not super important, thanks anyways. We have a general idea of what could be responsible for this. Can you share your OS version and hardware specs (anything storage related specifically)?

**Comment by dudehacker** [comment]
OS Name	: Microsoft Windows 10 Home
Version:	10.0.19042 Build 19042
System Type:	x64-based PC
Installed Physical Memory (RAM)	16.0 GB
Processor:	AMD Ryzen 5 1600 Six-Core Processor, 3200 Mhz, 6 Core(s), 12 Logical Processor(s)
Graphics:         NVIDIA GeForce GTX 1080
BaseBoard Product: 	B350 TOMAHAWK (MS-7A34)

Storage
File System	NTFS
Size	446.06 GB (478,956,113,920 bytes)
Volume Name	SSD
Compressed	No
Model: MKNSSDE3480GB

I have another HDD but osu is stored on SSD (same as OS)

**Comment by peppy** [comment]
As a heads up, there was another report of this on twitter yesterday.

**Comment by peppy** [comment]
Just a heads up to any future visitors: please report this issue if you encounter it. We are yet to understand how this can happen, but it sounds like there may be a third party issue here, either with storage hardware, drivers or something else in between.

**Comment by Zawajiro** [comment]
peppy i got the same problem

**Comment by cunny1111** [comment]
@peppy i just got the same problem

**Comment by peppy** [comment]
We've fixed this on lazer. I'm not sure the same fix will be applied to stable though. Quite an intrusive one.

**Comment by dudehacker** [comment]
Just occurred to me again, cuz of power outage. this time i have the corrupted file

corrupted file: https://puu.sh/J1x84/c94086b981.osu

from this map: https://osu.ppy.sh/beatmapsets/1721538#mania/3518248

hope it helps

Osu version: b20220413cuttingedge
