### ISSUE TITLE
Setting the current position on map in editor to negative time

### ISSUE THREAD

**Issue by minusSylvari** [ppy/osu-stable-issues#297]
Since the Stable version 20200103.3 you can put the current position of the map on negative time (e.g. -13s or -25s) [https://osu.ppy.sh/ss/14322314/1070] without any problems by both posibilities (by moving the white line on the bottom and by mouse wheel. Haven't noticed anything in changelog so I think it's unintentional.

Beta version 20200103.2 and cuttingedge 20200102 have this bug as well.
Stable 20191227.3 haven't got it.

Additionally when you will unpause when editor stops on "outro" (place where the audio ends) it still moves on the timeline [https://osu.ppy.sh/ss/14322412/7ccb the song has 30s audio and it can continue it's movement even after outro.

**Comment by peppy** [comment]
This is intentional for now. Please leave another comment if this is actually causing you issues.
