### ISSUE TITLE
Exiting test mode in the editor always moves you to 00:00:015

### ISSUE THREAD

**Issue by Darius-Wattimena** [ppy/osu-stable-issues#299]
**Version:** Stable
**Issue:** When I try to exit test mode I always get moved to 00:00:015 
This happens when you press ESC, F1, F2 or press the quit button when paused.

Asked some people in the BN server and catch mapping server and everyone seems to have this issue.

Some things that might be related to this issue:
- You can now move to minus offset in the editor by moving the song slider to the left.
- You can now go beyond the end of the mp3 by moving the song slider to the far right and then press the play button.

**Comment by Xinnoh** [comment]
^ important to fix quickly since this annoys all mappers

**Comment by peppy** [comment]
Could you explain why this is annoying? can't you just seek left or rigth once?

**Comment by Darius-Wattimena** [comment]
It completely ruins the workflow for a mapper and gets really frustrating when you get moved to the start when pressing F2 is suppose to be moving to the current point where you are testing right now.

**Comment by Larakagi** [comment]
If you press F2 (exit the testplay field) the timeline goes to 00:00:000 for some reason. Same with Esc button.

**Comment by Peter-GHub** [comment]
I think it might be somehow connected to that 15 ms early difference in editor which I opened in other post

**Comment by uwuplant** [comment]
[small little demonstration of a few bugs here](https://youtu.be/aCeSK9lpiYo)

**Comment by uwuplant** [comment]
most of these issues seem to be connected to the switch to wasapi, as none of these bugs are present in audio compatibility mode.

**Comment by nl-tatatat** [comment]
There have been multiple issues that have popped up since the introduction of the feature "You can now move to minus offset in the editor by moving the song slider to the left."
I don't see why its even necessary in the first place. Its impossible to have music from the .mp3 file before 00:00:000 - , only the design tab and timing tab should need to access timestamps before 0. 

In fact, placing notes before 00:00:000 - just crashes the game.

**Comment by WinterIsPretty** [comment]
Oh yes this really annoys me, idk why it happens but it seems to happen after you do something random and then exit your map and open it back up in the editor. It gets annoying when you are trying to quickly test your map with mods or like just taking a break.

**Comment by peppy** [comment]
I can't reproduce the "exiting takes to 00:00:015" and none of the provided videos or information gives reproduction steps.

- Starting at 0ms and using F1, I am exited to 0ms (as expected)
- Starting at 0ms and using F2 or Pause>Quit, I am exited to the current position (as expected)
- Starting at an arbitrary time value and using F1, I am returned to that time value (expected)
- Starting at an arbitrary time value and using F2 or Pause>Quit, I am exited to the current position (as expected)

**Comment by uwuplant** [comment]
[second vid, with keyboard what I'm doing.](https://youtu.be/sf0fzhilvTM)

w10 64bit, build 17763
latest osu! stable

**Comment by peppy** [comment]
It could reproduce by setting my universal offset above zero. Can anyone confirm they also have a non-zero universal offset to make this happen?

**Comment by WinterIsPretty** [comment]
My offset is set to 17

**Comment by peppy** [comment]
please test latest cutting edge. this issue should be resolved.

**Comment by uwuplant** [comment]
still occurring on latest cutting edge, still opens to 00:00:015, but you can no longer scroll before 00:00:000.

**Comment by peppy** [comment]
opening to that time is intended.

**Comment by uwuplant** [comment]
it's now working fine, thankies
