### ISSUE TITLE
osu!mania special style key doesn't work properly

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#31]
Reporting here an **really old** issue which exist in osu!mania.

The special key in osu!mania 8K (7+1K) does not work properly.
It is possible to assign the special key to two different keys on the keyboard. 

While playing 7+1K beatmaps, the 2nd key does not react, as long the 1st key is still pressed. 
This issue affected the rankability of beatmaps in the past, which got disqualified because of "more difficult" special key column usage, but because of the bug these maps were not passable on 100%.

Old forum thread: https://osu.ppy.sh/community/forums/topics/392668

**Comment by smoogipoo** [comment]
This is intentional, and it's a pretty complex fix with multiple things to consider.
