### ISSUE TITLE
pressing f2 during a testplay in the editor is broken

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#310]
It used to be that pressing f2 while testplaying a beatmap in the editor would exit the testplay and leave you at the moment you were just playing on the timeline, now it reverts you back to the the beginning of the map.

The problem is though, f3 already does that. 

This is a serious issue for those wishing to refine their beatmaps.

**Comment by Ceotom** [comment]
It seems same problem as #299

**Comment by nl-tatatat** [comment]
yes! definitely. this could probably be closed or merged.
