### ISSUE TITLE
New BASS dlls cause inconsistent audio desync between different beatmaps/mp3s

### ISSUE THREAD

**Issue by McKay42** [ppy/osu-stable-issues#312]
- The required offset to compensate for this changes inconsistently +- between audio files (though always the same for the same audio file).

- Using any universal offset does *not* solve the problem. You fix it for one beatmap, but desync another.

- Using audio compatibility mode does *not* solve the problem. You fix it for one beatmap, but desync another.

- Using cutting edge does *not* solve the problem. Same behavior as stable.

- This has *nothing* to do with Windows versions or audio drivers. Only BASS is at fault here.

- This of course also affects lazer, but is more important for stable right now.

With 2019 BASS dlls and audio compatibility mode *disabled*:
- [Beatmap 1](https://osu.ppy.sh/beatmapsets/230989#osu/537377) is +9 ms too early.
- [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532) is +4 ms too early.

With 2019 BASS dlls and audio compatibility mode *enabled*:
- [Beatmap 1](https://osu.ppy.sh/beatmapsets/230989#osu/537377) is now almost synced correctly.
- [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532) is now -22 ms too late!

Tested by recording auto playing (with somewhat loud hitsounds) at 1000 fps limit, and comparing timings in audacity after aligning all tracks by music waveform parts which didn't contain any hitsounds:

![latencycomp](https://user-images.githubusercontent.com/16856443/71818376-10e02800-3089-11ea-88a3-4b4ce261fc0e.png)

Note the BASS dll versions per track.
For the first beatmap above, the first track uses forced 2009 BASS dlls in osu!stable to verify things.
Unfortunately, cutting edge always validates file integrity before launching, so you can't easily overwrite dlls on that release stream, so I can't do the extra double verification there.

![latencycomp2](https://user-images.githubusercontent.com/16856443/71818381-1473af00-3089-11ea-97aa-ebd47b4e1917.png)

Conclusion:

- BASS has changed the behavior of BASS_ChannelGetPosition(), either by decoding audio files differently or some other internal change.

- All osu beatmaps created/submitted before the dll update are timed to the 2009 BASS dlls, while all new beatmaps since then are timed to the 2019 BASS dlls, creating an inconsistent mess.

- Assuming this is related to how BASS decodes audio files, maybe the audio file can be parsed manually to additionally apply a correction offset depending on the contents (in addition to the hardcoded universal offset currently).

**Comment by peppy** [comment]
- The timing has changed with newer bass, but we added an offset to account for this. It shouldn't be different for different beatmaps, though.
- Compatibility mode is not intended to be correct from a timing or latency perspective, and only provided for people who can't play without it for some odd reason. It should not be used for normal play.
- Timing of new beatmaps should not be affected.
- Anything under 10ms off can be accounted to windows/WASAPI precision, which has/is 10ms. It may change each play.

**Comment by McKay42** [comment]
> So it seems like it may more likely be something to do with WASAPI.

Ah see this is what I was missing (generally confused as to why you mentioned switching to WASAPI even though no `basswasapi.dll` is present anywhere).

With version 2.4.13 - 19/12/2017 BASS switched from DirectSound to WASAPI internally.
Adding `BASS_DEVICE_DSOUND` to `BASS_Init()` fixes all problems, timing is perfect even with post 2017 dlls, because it then falls back to the DirectSound backend.

So therefore the new WASAPI [`IAudioClock::GetPosition`](https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclock-getposition) behavior does not match [`IDirectSoundBuffer::GetCurrentPosition()`](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mt708925(v%3Dvs.85)), or BASS is using them in such a way where they are inconsistent for different audio files. (The two beatmaps I tested are perfect examples.)

> Potentially latency being different if you have spatial audio or other enhancements turned on?

Everything was off, especially when I'm testing something like this.

> Anything sowing difference of under 10ms can be accounted to windows/WASAPI precision, which was/is 10ms. It may change each play.

No. I've done multiple tests, and this is 100% consistent every time.
Playing a hitsound sample does *not* have a random precision offset.
The WASAPI buffer size does *not* add a random offset to samples or music each play.

If the reported playback position always got a random offset each play, then there would be bigger problems?

> Also to note, we did extensive testing of this and the timing/offset was different for different users

Then newly created beatmaps will appear randomly mistimed on random computers, like I said.

**Comment by peppy** [comment]
The legacy audio toggle adds exactly that flag (`BASS_DEVICE_DSOUND `). Dropping in an old dll will probably result in weird behaviour (it may think it's WASAPI and is applying the offset when it shouldn't).

> No. I've done multiple tests, and this is 100% consistent every time.

Interesting that you got consistency, since over 100 odd tests (done on the same hardware) i definitely did not. Also having others test resulted in up to 30ms difference.

> If the reported playback position always got a random offset each play, then there would be bigger problems?

The reported playback position is not the issue – it's the playback time of the samples that occurs in 10ms windows currently. It's been this way since vista. This can potentially be improved upon, though, in a future update.

If you are getting reproducible results with different mp3s, can you make a simple tester app and/or try and figure out what's causing the difference? Would be very helpful!

**Comment by McKay42** [comment]
> The legacy audio toggle adds exactly that flag (BASS_DEVICE_DSOUND )

Just found out why some beatmaps are still desynced even with DirectSound in stable: [BASS_CONFIG_VISTA_TRUEPOS](https://www.un4seen.com/doc/#bass/BASS_CONFIG_VISTA_TRUEPOS.html)

You never explicitly `BASS_SetConfig(BASS_CONFIG_VISTA_TRUEPOS, 0);` in stable, right?
Which means it is enabled (default). It did not exist in 2009 dlls, but now affects timing after the fact.
Could you please set this flag to 0 when Audio Compatibility Mode is enabled? Then everything matches perfectly (with compatibility mode on).

**Comment by peppy** [comment]
I did experiment with that flag but not with directsound (only WASAPI). maybe that’s why it seemed to do nothing.

Will give this some testing, thanks!

**Comment by smi3tana** [comment]
@McKay42 Please tell me if I'm right or wrong. Could perfectly matching video (approach circles) and song but delayed hitsounds be caused by this issue?

**Comment by peppy** [comment]
@smi3tana if you had the "legacy" setting turned on, it's possible. i'd recommend not using this unless you have to, though.

@McKay42 change has been deployed to cutting edge and looks fine from my end. could you please confirm?

**Comment by smi3tana** [comment]
hmm, audio compatibility changes nothing for me here. I tested it similarly using audacity.
![image](https://user-images.githubusercontent.com/4450862/71915676-8973e100-317c-11ea-8d8c-2f1c530216d7.png)

I'd like to retest it with previous osu version but I didn't go as far as running it through dotnet (there is no other way, right? only cloning the repo, checking out the previous release and building it)

**Comment by peppy** [comment]
Please check once more – there's no way both modes should match that close (the waveforms are way too perfectly aligned and shaped).

**Comment by InvisibleSymbol** [comment]
I have tested the latest ce with your offset map.
![](https://i.fiery.me/IQiKV.png)
I aligned and highlighted the sound from the mp3, the black line is the hitsound (default skin).
Top is with it off, bottom is with it on.

**Comment by McKay42** [comment]
> change has been deployed to cutting edge and looks fine from my end. could you please confirm?

Yes thank you, has reduced the difference by 10 ms as expected:

![latencycomp4](https://user-images.githubusercontent.com/16856443/71921737-b1b60c80-3189-11ea-9787-775b1884e8d0.png)


---

You were correct that there really is a random +10 ms delay when playing samples, seems I was just lucky and didn't look at enough datapoints for it to occur:

![Capture](https://user-images.githubusercontent.com/16856443/71921838-f5107b00-3189-11ea-9df5-41f30236b6a7.PNG)

- Same beatmap recorded 3 times with 2009 dlls (DirectSound, 0 TruePos):
I've manually counted 100 hitsounds, and 4 of them were offset by +10 ms, so it at least happen very rarely (like max. <5% of the time). Really didn't want this to be true, but here we are.

- Then did the same (3 recordings) with 2019 dlls with `BASS_WASAPI_Init()` (shared mode, 11 ms buffer size) and only got 1 out of 100 hitsounds offset.
As long as it occurs this rarely it doesn't impact rhythm sense by hearing enough to be a problem (didn't notice it myself over 6 years of playing so yeah). (All tests done at 1000 fps limit.)

**Comment by smi3tana** [comment]
testing cutting edge on my side

audio compatibility off
---------------------------- 
audio compatibility on

![image](https://user-images.githubusercontent.com/4450862/71928784-84bd2600-3198-11ea-936c-3c5a4002c84b.png)

**Comment by peppy** [comment]
@smi3tana thanks for the feedback. that's about what i was seeing too with non-realtek sound hardware.

we'll iterate further to hopefully fix the cases where playback latency changed (note that it's actually more likely the case that the universal offset is wrong).

**Comment by McKay42** [comment]
Here are my results for the latency test beatmap:

![latencycomp5](https://user-images.githubusercontent.com/16856443/71967237-4f99ed80-3203-11ea-84bf-a3f26694f0ad.png)

Cutting edge with the 0 trupos fix is almost perfect now *for this specific beatmap*:
If I add -15 ms hardcoded offset to fix [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532), then the latency test beatmap is now 15 ms too early, and vice versa.

**Comment by MaxKruse** [comment]
Random question that makes me look stupid and doesnt help the cause of this:

Did the old bass.dll files also have a random 10ms offset, as i have never noticed ingame. It would also be, lets say unhelpful, for a rhythm game to randomly change the rhythm of hitsounds.

**Comment by peppy** [comment]
yes. it's a windows limitation.

we have known this for years. internally, osu! interpolates the time so this does not affect judgements, only hitsound playback.

consider it a wake up call that 10ms difference is generally not enough to cause an issue!

**Comment by McKay42** [comment]
> consider it a wake up call that 10ms difference is generally not enough to cause an issue!

It's not an issue because it doesn't happen very often for playing samples (higher fps = even more unlikely, with the chance hovering around 1% on 2019 wasapi at 1000 fps).

I can easily identify a *constant* +-10 ms or higher offset in any beatmap just by listening to hitsounds, and this is the problem with the new dlls across different beatmaps.

**Comment by MaxKruse** [comment]
> I can easily identify a _constant_ +-10 ms or higher offset in any beatmap just by listening to hitsounds, and this is the problem with the new dlls across different beatmaps.

a **constant** offset of anything bigger than 3-ish ms is noticable to most 4 digit players, maybe even 5 digits. If its just the occasional 10ms offset, nobody notices. Depends on the actual occurance rate, not the exact value itself.

**Comment by peppy** [comment]
the precision is 10ms. it always has been. it will be more than 1% chance depending on the beatmap and timing points regardless of bass version. think about it for a bit.

**Comment by aya-shamei** [comment]
factors influencing why more players don't notice the offset:

- there's already ~30ms best case scenario of audio delay on windows10, which makes inconsistencies less noticeable compared to if a player were using low latency audio (0-2ms baseline vs 30+ ms)

- most players' input devices have additional delays and input inconsistencies due to debounce and scan rate, HID bFilter, etc

- latency on host system influencing input processing and precision.

- many players have varying delays at the start of their hitsounds

- frame rate inconsistencies

- some players play entirely visually with little care for audio feedback, while others have tactile switches hence feedback by touch instead of sound

this goes more noticed by players pushing themselves to obtain low unstable rate/od11 scores. i've noticed the odd hit sound being slightly off beat compared to where expected.

i don't mean to move discussion away from fixing the issue

**Comment by Peter-GHub** [comment]
Maybe players won't notice the different but mappers will if editor is affected as well, ranking criteria states that timing needs to be perfect and only about 3 ms imperfection is allowed

**Comment by peppy** [comment]
again, nothing has changed and this has always been a thing.

please only reply further if you have additional information on a fix or otherwise.

**Comment by McKay42** [comment]
The minor offset variations start happening between these two dll versions:

- 2.4.11.0 2014 dll has perfect timing (like 2009 dll).
- 2.4.11.14 2014 dll has **bad** timing!

This is **independent** from the #326 `ItunSMPB` problem which is now solved.
Same behavor still occurs even with the 2.4.15.1 2020 dll.

**Comment by peppy** [comment]
Where are you finding the old builds of BASS by the way? I had a lot of trouble digging them up.

**Comment by McKay42** [comment]
From my own projects and gravedigging github repositories, here you go:

WARNING: Use at your own risk, never trust random dll downloads etc. etc.
[bass_dll_history.zip](https://github.com/ppy/osu-stable-issues/files/4077727/bass_dll_history.zip)

**Comment by peppy** [comment]
@McKay42 I've followed up with the bass dev for further information on the differences between the two builds you reported above. I think that's the logical next step to solving this one.

**Comment by peppy** [comment]
@McKay42 could you check the value of `BASS_ChannelGetLength` across the two version you are seeing the discrepancy? If there's a difference here, it may still be an issue surrounding `ItunSMMPB`.

**Comment by McKay42** [comment]
> @McKay42 could you check the value of `BASS_ChannelGetLength` across the two version you are seeing the discrepancy? If there's a difference here, it may still be an issue surrounding `ItunSMMPB`.

---
Default `BASS_Init()` with 0 flags:

BASS `2009 to 2014` 2.4.3.12 to 2.4.11.0 (ground truth):
- [Beatmap 1](https://osu.ppy.sh/beatmapsets/230989#osu/537377):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 19679408 bytes
- [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 25652736 bytes

BASS `2015 to 2020` 2.4.11.14 to 2.4.15.1 `BASS_SetConfig(BASS_CONFIG_MP3_NOITUNESTAG, 0)`:

- [Beatmap 1](https://osu.ppy.sh/beatmapsets/230989#osu/537377):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 19679408 bytes
- [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 25650620 bytes

BASS `2015 to 2020` 2.4.11.14 to 2.4.15.1 `BASS_SetConfig(BASS_CONFIG_MP3_NOITUNESTAG, 1)`:
- [Beatmap 1](https://osu.ppy.sh/beatmapsets/230989#osu/537377):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 19679408 bytes
- [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 25650620 bytes

---

And `BASS_DEVICE_DSOUND` also has no effect (seems reasonable since it doesn't handle mp3 decoding):

BASS `2015 to 2020` 2.4.11.14 to 2.4.15.1 `BASS_DEVICE_DSOUND` + `BASS_SetConfig(BASS_CONFIG_MP3_NOITUNESTAG, 0)`:
- [Beatmap 1](https://osu.ppy.sh/beatmapsets/230989#osu/537377):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 19679408 bytes
- [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 25650620 bytes

BASS `2015 to 2020` 2.4.11.14 to 2.4.15.1 `BASS_DEVICE_DSOUND` + `BASS_SetConfig(BASS_CONFIG_MP3_NOITUNESTAG, 1)`:
- [Beatmap 1](https://osu.ppy.sh/beatmapsets/230989#osu/537377):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 19679408 bytes
- [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532):	BASS_ChannelGetLength(handle, BASS_POS_BYTE) = 25650620 bytes

---

Interestingly, seems that only [Beatmap 2](https://osu.ppy.sh/beatmapsets/300330#osu/673532) shows any change (2116 bytes less), and even then the change has nothing to do with `BASS_CONFIG_MP3_NOITUNESTAG`.

Though the playback position would linearly interpolate across a larger length, wouldn't it? So it would have perfect timing at the start of the mp3, but then slowly get worse till the end. Therefore this shouldn't be the cause for any _constant_ desync.

**Comment by peppy** [comment]
I believe it's more that the offset is silence at the start of the track, so it *would* end up being a constant inaccuracy.

**Comment by peppy** [comment]
> Ah, I think I know what that is now. There was another change introduced around the same time as "ItunSMPB" tag support, which was to assume a 529 sample (2116 byte in stereo 16-bit) delay if the MP3 file doesn't specify. That was done for more consistent (identical) results across platforms and standard/mp3-free BASS versions, because OSX/iOS's MP3 decoder always removes 529 samples.
> 
> Here's an update that extends and renames the BASS_CONFIG_MP3_NOITUNESTAG option to BASS_CONFIG_MP3_OLDGAPS:
> 
> www.un4seen.com/stuff/bass.zip

@McKay42 i'll test this myself tomorrow, but feel free to beat me.

**Comment by McKay42** [comment]
No perceptible offset anymore, I'll test more beatmaps tomorrow as well.

**Comment by peppy** [comment]
Looks good here too, for all the beatmaps I noticed minor discrepancies. I've pushed a cutting edge build out with this dll update.

**Comment by Peter-GHub** [comment]
> ![image](https://user-images.githubusercontent.com/191335/71822773-11a0aa80-30d9-11ea-9abf-c0a5284f87ef.png) 

Is this still in game? I feel like maps are 15 ms early when Wasapi is used.

**Comment by peppy** [comment]
This was added as a sane middle-ground. Please adjust your UO once and you should be fine.

**Comment by Peter-GHub** [comment]
Wouldn't that affect older maps though? if you subtract 15 ms from all maps without compatibility mode, yeah setting UO from 0 to +15 would fix the problem but just for me not everyone and there will be difference between wasapi and legacy, which will make all maps 15ms off or maybe i'm just misunderstanding?

**Comment by peppy** [comment]
The 15ms is constant and wasapi specific, not beatmap or mp3 specific.

**Comment by peppy** [comment]
@McKay42 i'll leave it up to you to confirm and close this issue if you are satisfied with the results. Will be pushing out the new dll to beta/stable branches tonight or tomorrow.

**Comment by McKay42** [comment]
Looking good

**Comment by MaxKruse** [comment]
hurray!
