### ISSUE TITLE
LightingL and LightingN don't do anything in the skin.ini

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#315]
![Screenshot_20200106-184751_Chrome](https://user-images.githubusercontent.com/52920930/71859677-67635b80-30b5-11ea-97a1-7f39c3c75ce2.jpg)
These are supposed to use the lighting images in a mania skin but they don't do anything because the skin is always either using the skin's lighting or the default one at all times, you cant use different lightings in different keys

**Comment by smoogipoo** [comment]
I have tested this and it works fine. Please provide a failing skin.

**Comment by WinterIsPretty** [comment]
I swear I tried it many times it didn't work and now all of a sudden it does....................................... this is awkward

**Comment by WinterIsPretty** [comment]
I did have another one which I just posted now and with the skin dl link
my skin for some reason sometimes has these weird errors were some stuff works and others don't
