### ISSUE TITLE
ColourLight# not working for skin.ini on my skin + skin dl link

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#317]
this is the skin I am using

https://cdn.discordapp.com/attachments/463638143422169088/664002334958813184/WinterIsPrettys_Skin.osk

for some reason on my skin the ColorLight or ColorLight don't work and finally I have the skin dl link for you to see for yourself. I copied this off of Jakad's skin which on there it does work idk what is different about mine that makes this not work.

**Comment by smoogipoo** [comment]
It's because your skin contains a 1x1px `mania-stage-light.png`.
