### ISSUE TITLE
Watching an osu!mania replay changes your scroll speed

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#32]
When you watch an osu!mania replay it changes your scroll speed which is to be expected during the replay because you want to watch it at the same scroll speed the player played it at. However if you change the scroll speed during the replay, when you're done with the replay, that player's scroll speed still persists and you have to change it back the next time you want to play.

My solution would be to only have the replay's scroll speed for the replay, and not have it persist after that.

**Comment by percyqaz** [comment]
I believe this is working as intended as the replay scroll speed only persists if you change it while watching (at which point you can easily change it to your preferred scroll speed).

**Comment by nl-tatatat** [comment]
I'd say its somewhat functional, however the replay scroll speed should be completely independent of your own scroll speed.

**Comment by MillhioreF** [comment]
Fixed in next cuttingedge.
