### ISSUE TITLE
viewing map in editor then playing auto-fails the map

### ISSUE THREAD

**Issue by camellirite** [ppy/osu-stable-issues#321]
watching a few seconds in the editor then playing the same map basically auto-fails 

I tried having a look in the logs but i don't think there was anything relevant in there, I can post if needed, reproducible on any map that doesn't have a skip button, but its still kinda of iffy.

auto-fail: https://youtu.be/er41D_qUJbs

**Comment by peppy** [comment]
Only in cutting edge / beta?

**Comment by peppy** [comment]
For future reference *please* include a link to the beatmap at very least.

**Comment by peppy** [comment]
Should be fixed in next cutting edge.
