### ISSUE TITLE
Editor is not importing mp3 metadata anymore

### ISSUE THREAD

**Issue by Mordredosu** [ppy/osu-stable-issues#325]
Not sure since when this is the case but if you throw an mp3 into the editor with the current stable release it doesn't import the mp3's metadata like it did before. This is especially annoying when the title / artist / etc. is a rather complex one, since doing research and finding the proper thing isn't always easy, more so when you only have the mp3 and can't read / write the language of its name (I think in some cases a user's os might not even be able to display for example japanese characters so that makes it even more annoying but I might be wrong there).

**Comment by WinterIsPretty** [comment]
This happened to me as well

**Comment by peppy** [comment]
This should be fixed in cutting edge. Please confirm.

**Comment by Mordredosu** [comment]
works on cutting edge yes, nice
