### ISSUE TITLE
Importing a skin while in a multi kicks you out

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#327]
Is it supposed to bring you to the menu when you import a skin while in a multi or is that not supposed to happen.

**Comment by peppy** [comment]
An easy fix would be to avoid importing a skin during multiplayer.

In all seriousness, this is out of scope of the fixes we are looking to provide.

**Comment by WinterIsPretty** [comment]
I shared my skin with my friends and they had trouble getting back in the multi because they got kicked out

**Comment by peppy** [comment]
Tell them to rejoin for now
