### ISSUE TITLE
Hitting notes with bad accuracy in taiko gives more HP

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#33]
In taiko, there are three levels of accuracy: 300, 100, and miss.
Usually, when you hit a 300 you are awarded the most HP, hitting a 100 give a smaller amount of HP, and missing reduces your HP. However, at lower HPs (around <4 HP) hitting a 100 will actually reward more HP than a 300. This doesn't make any sense.
Here is the difference in HP gain between a [100](https://i.imgur.com/DLeRKJI.png) and a [300](https://i.imgur.com/0o2tRw8.png) at 3.6 HP
and again at 0 HP: [100](https://i.imgur.com/22c0vi5.png) and [300](https://i.imgur.com/34w4LOg.png)

While these HPs aren't commonly used in TV sized songs, HPs can and will drop at or below 4 in marathon length maps. I believe there is something wrong with the HP gain formula that needs to be fixed. Hitting notes accurately should be rewarded, not punished.

**Comment by smoogipoo** [comment]
Yeah this is a known issue, and it's not just an issue with taiko. Not sure about changing the HP universally at this point.

Will be fixed when HP is properly implemented in lazer.
