### ISSUE TITLE
Editor timeline starts at 15ms when WASAPI is enabled with 0ms global offset.

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu-stable-issues#330]
The editor timeline starts at 15ms (00:00:015) when global offset is set to 0. This doesn't happens with DirectSound (Audio Compatibility Mode).

- With a global offset of 0ms, the editor started at (00:00:015):
![0ms](https://user-images.githubusercontent.com/20617307/72644545-0a3a9600-3950-11ea-8c36-341038906798.png)

- When, for example, i've put a global offset of -20ms, the editor started at (-00:00:005):
![-20ms](https://user-images.githubusercontent.com/20617307/72644670-54bc1280-3950-11ea-92de-8f743945a359.png)

- This shift in the start happens with DirectSound, but it is the exact global offset, as you can see here in this screenshot with -20ms and Audio Compatibility Mode activated:
![-20ms Direct Sound](https://user-images.githubusercontent.com/20617307/72644796-b11f3200-3950-11ea-9bf5-fd2b10d88a37.png)

- With 0ms global offset as well:
![0ms Direct Sound](https://user-images.githubusercontent.com/20617307/72644920-0bb88e00-3951-11ea-9b4f-0ab10c94a11f.png)

_My theory is that the hardcoded plus 15ms when WASAPI is enabled causes that._

Can reproduce in both **Windows 10** (with the standard Windows High Definition Drivers) and **Linux** (_wine-staging 5.0-rc4 and patched wine-staging 3.12_), in any beatmap, the map in question i've used on the screenshots is [this one](https://osu.ppy.sh/beatmapsets/1073482#osu/2246648).

**Comment by peppy** [comment]
This is correct and intended behaviour. Internal timings are slightly different with WASAPI so osu! accounts for this so everyone is on the same page.
