### ISSUE TITLE
Windows 10 notifications "break" cursor

### ISSUE THREAD

**Issue by tilda** [ppy/osu-stable-issues#332]
I've been noticing whenever I get a Windows 10 notification that the cursor sort of breaks.

I'll try to get some sort of video of what I'm seeing, but basically the Windows cursor is visible for very short periods. It's very distracting and I just lose my concentration on the map I'm playing whenever it happens.

**Comment by peppy** [comment]
Please turn on focus assist or disable notifications via quiet time mode when playing osu!
