### ISSUE TITLE
Multiplayer and osu connection

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#334]
Since I got VR and we needed games we downloaded a ton of stuff; summary is we now have low internet. Since I have this low internet I have had trouble with osu in multiplayer specifically with this one error...

If you disconnect from osu (the link image pops up in the corner) right before the match starts you get stuck at "waiting for players" as you watch everyone play the map.

This only happens on this specific occasion but it is still enough to have it happen more than once  a day and it also crashes the game where you cannot exit or do anything

![screenshot057](https://user-images.githubusercontent.com/52920930/72706261-33f7e680-3b23-11ea-936f-cb7c9c9a12fe.jpg)

**Comment by peppy** [comment]
This is out of scope of what we can fix with stable. Better net code will be present in lazer's multiplayer implementation.

**Comment by WinterIsPretty** [comment]
Dangit.. well at least it will be fixed in lazer
