### ISSUE TITLE
Allow users to search using genre, language, and online tags in-game

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#337]
This would essentially require beatmaps to grab this information alongside other online information when the client is connected to the internet - just like beatmap thumbnail or the gameplay title/artist text formatting.

Online tags should behave the same way as current in-game tags, and genre language could possibly be specified by searching Genre:_genre_ Language:_language_ or something similar, only working if the genre is set to something besides _unspecified_ .

Right now the mismatch between website and in-game searching can cause inconveniences and confusion, such as finding a map one way to download it from the website, but not being able to find it a similar way in-game later.

**Issues with online tags:**
For example, on the website if you search "fan club vocaloid" you'd get https://osu.ppy.sh/beatmapsets/57701#osu/173832 (**Midasmens'** set) and  https://osu.ppy.sh/beatmapsets/58736#osu/176432 (**Chewin's** set) as the top results.
If you have both downloaded and use the same search term in-game, only **Chewin's** set will show up, because the "Vocaloid" tag on **Midasmens'** set is website-only. There is no distinction between how the two are searched on the website, and can be confusing in game as to why one set shows up and the other does not. On numerous occasions this has definitely made me think I was missing sets in my downloaded library, just to realize the search isn't working because they're not tagged the same way in-game. The average user who doesn't know the difference between online and in-game tags would probably never know why the search is "bugged" like this.

While of course the ideal is to make sure maps don't get ranked while lacking relevant tags to avoid using online tags in the first place, this obviously does not really help for existing cases where online tags were added later. 

**Issues with Genre/Language:**
Right now only being able to use genre/language filters on the website (not even in osu direct) makes the feature less than useful. This has resulted in multiple discussions relating to putting the genre/language in beatmap tags to try to bring website and in-game search closer together. Rather than make up for features that are currently lacking by compensating with RC requirements, I'd like to know if in-game implementation would be simple and/or possible. Relevant discussion: https://osu.ppy.sh/community/forums/topics/1012477
The relevant guideline has been in RC for the past year-ish, but a big reason it is not well followed is because of people wondering why on earth it isn't just an in-game implementation to start with.

**Comment by peppy** [comment]
All of this metadata will be refunded at a point in the near future. This depends on an updated server side beatmap processor and beatmap format which will arrive with lazer.

I don’t mind leaving this open for now but please understand it likely won’t make it to stable due to the scope.

**Comment by dorothy3242** [comment]
Okay! I understand, thanks for the response on this.
