### ISSUE TITLE
stacking doesn't display when editing standard maps if play mode is set to t/c/m

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#34]
Mainly posting because this may be related to https://github.com/ppy/osu-stable-issues/issues/2

To replicate 

- Select play and enter level select menu
- Change game mode to anything other than osu!standard at the bottom
- Open an osu!standard map by Beatmap Options -> Edit (**not Edit select via main menu**)
- In-editor stacking will not display.

the stacking will not display until the play mode is changed back to standard. I can't tell you how many times I accidentally did this and thought beatmaps I was modding had unrankable stacking settings

This seems to be a bug where for some reason the play mode is applied to the edit mode, and the other issue may be related, as they are both caused by issues with play/edit modes sharing game mode.

**Comment by MillhioreF** [comment]
I'd argue this is desired behavior since only osu! and catch are affected by playfield positions, and catch doesn't stack at all.

**Comment by nl-tatatat** [comment]
It would be desired... if they were actually editing a non-osu!standard beatmap.

**Comment by dorothy3242** [comment]
Changing the mode of the beatmap you're editing is seperate from what I'm talking about, this is the gameplay mode affecting osu!standard beatmaps.

**Comment by MillhioreF** [comment]
My apologies, I missed a couple words. Will look into this one too.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
