### ISSUE TITLE
Input delay since January 

### ISSUE THREAD

**Issue by JDECOMBE** [ppy/osu-stable-issues#340]
Hi !
I'm not sure which update made this (I haven't played between ~24dec and ~15jan) but updating my client to the latest version of Osu! add around 1.5ms of input delay (had about 3.6 in game and now it's around 5.1). What's even more disturbing is that it feels like the input delay on mouse and tablet is even worst.  Had no sensation of delay before updating and now it's really ennoying (it feels like about 10 to 15ms of delay for those devices). On the other hand, FPS didn't suffer from the update...
I've tried on Cutting Edge, Stable and Beta.
I haven't change any of the windows settings which could lead to such things...

**Comment by peppy** [comment]
How are you measuring millisecond values of input delay? The number shown bottom-right is not input delay and correlated 1:1 to frame rate. If you say your frame rate has not changed, then that number should also be the same.

Nothing has changed in updates which could affect such performance. Are you sure you didn't change your frame limiter setting or are not running exclusive full screen when you used to be?

**Comment by JDECOMBE** [comment]
I've been using the bottom right value (sorry). Well I didn't notice FPS drops and I think I have always been around ~200FPS (I think)... As I am playing on a 60hz monitor, I guess I wouldn't have noticed a slightly change in FPS (most noticeable change been the input delay).
Still running in Unlimited (I've tried all the values of the frame limiter as well without any success). Maybe it's just one sneaky windows update I didn't notice ... 
Sorry to have bothered you ! Thank you 👍 

(btw I've been playing around with osu-framework and it's awesome to use !)

**Comment by peppy** [comment]
Closing for now, then.
