### ISSUE TITLE
Osu data getting mixed up

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#342]
The reason why #253 happens is because of the beatmap ID's getting mixed up

My claim: Beatmap ID's get mixed up cause maps to show the wrong status, rank, and thumbnail.

Evidence: The thumbnails get mixed up unless you refresh it by using global ranking. After you refresh the map it updates your ranking on that map, the status, and the thumbnail.

Issues: If you are in a multi and you don't update the map, it displays the wrong map and nobody can download the map. If you share someone a map that you haven't updated yet, it sends the wrong map. If you want to play only ranked maps it doesn't show all your ranked maps and it also displays loved and graveyard maps.

![Screenshot_20200123-185848_Discord](https://user-images.githubusercontent.com/52920930/73037007-ff31ab00-3e12-11ea-882e-f732ae869377.jpg)

https://cdn.discordapp.com/attachments/666447024471670794/670064948365230100/osu_Screenshot_2020.01.24_-_00.38.27.44.png

**Comment by peppy** [comment]
Can you stop opening, closing and posting? You are destroying this repository. You will be banned next time. Please Post this in the previous issue and open it again.
