### ISSUE TITLE
Problem with compatibility mode

### ISSUE THREAD

**Issue by Shigeraa** [ppy/osu-stable-issues#343]
Hello!

I have since yesterday an error when I launch osu! on my graphic card (Nvidia GTX 1660 Ti) in compatibility mode it displays this "
OpenGl ES Error 
Can't find the name of Intel ICD OpenGL driver" and also on the window of osu crash it says

"OpenTK.Graphics.GraphicsContextException: [EGL] Failed to create window surface, error BAD_NATIVE_WINDOW.
   à OpenTK.Platform.Egl.EglWindowInfo.CreateWindowSurface(IntPtr config)
   à OpenTK.Platform.Egl.EglContext..ctor(GraphicsMode mode, EglWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   à OpenTK.Platform.Egl.EglAnglePlatformFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   à OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   à #=z7ziWQbcLUBcONIRyk$EldmT$qOiX.#=zceH8GHw=(Int32 #=zJ2cfUmU=, Int32 #=zNQOae0o=, GraphicsContextFlags #=zotTPjN8=)
   à #=zOSYV8yTSf3K60P8HHcM7m3E=.OnHandleCreated(EventArgs #=z0c_uPy8=)
   à #=ztn2Yc6dYe8Ta3jHf3CB0JL4gFY8m.OnHandleCreated(EventArgs #=z0c_uPy8=)
   à System.Windows.Forms.Control.WmCreate(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.ContainerControl.WndProc(Message& m)
   à System.Windows.Forms.Form.WmCreate(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à #=zTBVB7KFRJhBe5k43WW7$WO0=.WndProc(Message& #=zEATu7Q8=)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"
but when I run it on my processor it works fine, would you have a solution or something.

Shigera

**Comment by peppy** [comment]
Could you please try restarting your PC as a first step?

**Comment by Shigeraa** [comment]
I restarted, but it didn't change anything.

**Comment by peppy** [comment]
Did you change graphics drivers or anything? This error can only mean that your graphics card is no longer showing support for OpenGL.

**Comment by Shigeraa** [comment]
On January 6th I got an update of GeForce experience, but the problem started yesterday afternoon, I reset my computer and reinstalled the drivers but it didn't change anything.

**Comment by Ceotom** [comment]
In this case, you started game on built-in intel graphics, not on nvidia gpu. 
You have laptop?
Have you tried installing intel drivers manually from your device manufacturer site?

And what did you mean by "I run it on my processor it works fine"?

**Comment by Shigeraa** [comment]
When I launch osu! with but integrated graphics I can play with the compatibility mode but with my graphics card from when I launch it there is this problem

**Comment by Ceotom** [comment]
You changed video card in the NVIDIA control panel as in screenshot or via windows explorer context menu (right click)?
![AnyDesk_mnCB6NlRbh](https://user-images.githubusercontent.com/36301121/73137544-330f0980-407b-11ea-92c7-f3afa36b4c1c.png)

If using context menu change video card through NVIDIA control panel.

**Comment by Shigeraa** [comment]
I tried both, but before the problem arose it was on nvidia's control panel.

**Comment by Ceotom** [comment]
Write model of your laptop

**Comment by Shigeraa** [comment]
MSI GP75 Leopard 95D
Intel Core I7 9750H
GeForce GTX1660Ti
8 GO Ram

**Comment by Ceotom** [comment]
1. Uninstall intel and nvidia driver with geforce experience (I recommend use [DDU](https://www.wagnardsoft.com/forums/viewtopic.php?f=5&t=2608 ) for this)
2. Reboot device
3. Download WGA drivers from [msi site](https://www.msi.com/Laptop/support/GP75-Leopard-9SD#down-driver&Win10%2064)
4. Install Intel driver
5. Install nvidia driver, reboot
6. Without updating driver, run osu!

**Comment by Shigeraa** [comment]
Thank you. It worked.

**Comment by Ceotom** [comment]
I recommend trying to upgrade nvidia driver, most likely now it will work fine
