### ISSUE TITLE
Input overlay background is displayed above hitcircles in replay mode

### ISSUE THREAD

**Issue by TheWildTree** [ppy/osu-stable-issues#344]
During gameplay `inputoverlay-background.png` is layered behind hitobjects, but in the replay mode it's the other way around.

Gameplay on the left, replay mode on the right (black box is `inputoverlay-background.png`):

![image](https://user-images.githubusercontent.com/27722894/73295519-210ea180-4208-11ea-8fd7-d1ba7511819d.png)

Might be the case for other UI parts too, I haven't tested them though.

**Comment by peppy** [comment]
doesn't sound like something which needs to be fixed (especially as you seem to be using it in a way it was not intended)

**Comment by TheWildTree** [comment]
there are skins that have actual inputoverlay backgrounds big enough to cover up parts of gameplay in the replay mode (especially in non-widescreen aspect ratios), while they're perfectly fine in normal gameplay.

unless there is a reason for this inconsistency, it should be fixed.

**Comment by peppy** [comment]
please provide an example of such a skin and i will make a decision based on how stupid it is

**Comment by TheWildTree** [comment]
people having your generic anime girl image next to the key overlay has been a thing for as long as that element has been skinnable.

and using skins *as intended*, expecting them to behave consistently is stupid? with all due respect, don't blame users and their works while it's your own code that's at fault here

i'll provide an example when i'll get on my PC.

**Comment by peppy** [comment]
the template provides sizes for elements. if you go beyond that you are in your own territory.

**Comment by TheWildTree** [comment]
fine, here's it on the default skin, gameplay vs. replay mode:

![image](https://user-images.githubusercontent.com/27722894/73852954-5f234b00-4830-11ea-9309-18dbd5091df2.png) ![image](https://user-images.githubusercontent.com/27722894/73852847-2aaf8f00-4830-11ea-8ab1-4a38b0c045a2.png)

while it's a minor difference i'd argue it still wouldn't hurt to fix it. up to you, though.

**Comment by peppy** [comment]
I foresee this as being an intentional decision, where the player does not want this blocking their gameplay during gameplay, but while watching a reply you actually *do*.
