### ISSUE TITLE
GUI breaks if user kicked from lobby while opened channel list

### ISSUE THREAD

**Issue by Ceotom** [ppy/osu-stable-issues#348]
In this state you cannot:
Use chat
Open any overlays (e.g. Exit promt, Beatmap options)
Use keyboard shortcuts in menu
Changing maps on songs selection screen

[Video](https://streamable.com/irpyn)

**Comment by peppy** [comment]
Thanks for the report, but I think this is such a rare occurrence that we will not be fixing it in stable.
