### ISSUE TITLE
osu!direct not downloading new beatmaps in a mapset

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-stable-issues#349]
I've had an old version of [this mapset](https://osu.ppy.sh/beatmapsets/912120) downloaded, I wanted to update it to get the new maps in it via direct but after it downloaded new maps didn't appear, neither they did after the second retry.

**Comment by peppy** [comment]
can you reproduce on any beatmap?

**Comment by pavlukivan** [comment]
Yes, i reproduced it on https://osu.ppy.sh/s/1098825

**Comment by peppy** [comment]
Please test again in the next cutting edge release (hopefully today).
