### ISSUE TITLE
In menu, the now playing song title doesn't cutoff with different languages

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#35]
![screenshot1906](https://user-images.githubusercontent.com/39173355/65284730-758e6b80-db08-11e9-9bc4-55bdab639f9c.png)
Not a high importance issue, but it's a bit bothering every time I go to menu and a long song with a non-English is playing and the bar below the song title sticks out
Intended behaviour should be for it cut off with ...
Like shown here with English metadata:
![screenshot1907](https://user-images.githubusercontent.com/39173355/65284974-2bf25080-db09-11e9-8553-3632a8ba69b2.png)

**Comment by peppy** [comment]
I think this may be out of scope unless it can be determined to be a quick fix. Due to how this is done I don't think it will be.

**Comment by MillhioreF** [comment]
Fixed in next cuttingedge.
