### ISSUE TITLE
Skin.ini behaviour

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-stable-issues#351]
https://github.com/ppy/osu-wiki/issues/2740

This issue over on the wiki mentioned skin verions 2.6 and 2.7, which no one ever heard of before. 
2.7 behaviour is pretty straight forward, but what 2.6 actually does is pretty questionable. We had those 3 files for years allready and arrow pause and warning work just fine (even in versions before 2.6, I think they work even in V1), but no one knows where arrow-generic is actually used.
So atm it looks like 2.6 didnt actually add anything and the usage of arrow-generic is still unknown. So what actually changed with version 2.6 and what does arrow-generic do? Also, is there any note of atleast roughly when this got added? Never heard of this before the issue and I am quite curious.
Lastly, are there any other additions during the last years to the skinning system that may have gone unnoticed, besides the addition of images for the new mod icons?

**Comment by peppy** [comment]
`arrow-generic` is used on the scoreboard for tag coop. added on 14th april 2015.

**Comment by RockRoller01** [comment]
Tried it earlier if its used in coop but it didnt show up. Guess I shoudl try that again and make sure I didnt make some mistake.
So, any explanation as to why the arrows work in other versions besides 2.6? Doesnt that mean there is no point in setting that skin.ini version

**Comment by peppy** [comment]
It's a change which did not have any breaking backwards compatibility effects so is applied to all versions.

**Comment by RockRoller01** [comment]
So I just tested it and it did not work. I tried both, arrow-generic and play-warningarrow (and their @2x counter parts) and it did not show them ingame. I Played Tag Co-op in mutliplayer with one friend, set to win condition score.

**Comment by peppy** [comment]
Are you looking in the wrong place? It uses it for the scoreboard.

**Comment by RockRoller01** [comment]
Thats where I looked. This is what I have in my skin  folder. I tried both Version 2.5 and 2.7
https://puu.sh/F7PVA/96e1827c4c.png
