### ISSUE TITLE
mouse sometimes disconnects while playing osu!

### ISSUE THREAD

**Issue by aehrea** [ppy/osu-stable-issues#353]
probably should've done this when it first started ~2-4 months ago (iirc) but oh well better late than never i guess?
my mouse (logitech m325) will sometimes just disconnect while playing osu. likely in part a hardware issue as well, but considering it never happens outside of osu during playtime (doesn't happen in editor, doesn't happen in menu/song select, doesn't happen when i mirror in-game movement outside of osu), i doubt it's solely a hardware issue. the mouse continues to remain disconnected even after exiting osu, and the only ways i've found to fix it are to remove the battery and put it back in/push the negative side of the battery against the spring pretty hard.
frequency: unpredictable, but happens quite often to the point i borderline can't play since i die soon after it disconnects.
i can provide logs/video of it happening during play on request.

**Comment by peppy** [comment]
are you running unlimited frames? my suspicion is electric interference from CPU or PSU due to driving your frame rate too high during gameplay.

Could you try at a lower frame limit and see if it helps?

**Comment by aehrea** [comment]
I'm already on powersaving, 120fps

**Comment by peppy** [comment]
It may still be an issue if you aren't on a crazy high spec machine. Could you try moving the mouse dongle to a different USB port (or an external hub if you have one available)?

**Comment by aehrea** [comment]
yeah, my machine is pretty bad. I didn't have the issue until a couple months ago, though
Also, I attempted switching the port when the bug first started but it didn't go away. I can't test again right now as I have since gotten a keypad and my computer only has 2 USB ports and I don't have a USB hub on me right now

**Comment by peppy** [comment]
I'm going to close this issue for now as it's definitely not something on our end. My next suggestion would definitely be trying a usb hub or something similar to move the receiver further away from your PC. Or moving your mouse closer to the receiver
