### ISSUE TITLE
scorebar-bg gets overlapped by numbers (layer bug)

### ISSUE THREAD

**Issue by OGValiente** [ppy/osu-stable-issues#354]
**Describe the bug:** So I have this custom scorebar-bg overlay that I use for hiding the accuracy/score area to prevent any possible distractions. I don't disable all the UI because I'm using the play area borders aswell. However in CuttingEdge, the numbers started to get drawn on the front layer, don't know if this is an intentional change or a bug, decided to report here anyway.

Also, the bug remains in "Cutting Edge 20200203" but it first occured way before than this version. In Stable, this bug doesn't exist.

**Screenshot:**
![image](https://user-images.githubusercontent.com/44140291/74005603-76764b80-498a-11ea-8489-57b62e97011c.png)

**osu version:** Cutting Edge 20200203

**Comment by peppy** [comment]
This is intended as we use it for tournaments. Please use stable if you want the stable behaviour (stable will never change).
