### ISSUE TITLE
Account Restricted 

### ISSUE THREAD

**Issue by Ekario** [ppy/osu-stable-issues#356]
Hello

My name is _Manyura. Today, i write you for my ban appeal.

As you know, i got restrict the 3rd January 2019 for multi-account

My username on osu! is : _Manyura

Link of my profile : 
https://osu.ppy.sh/users/8335913

Knows why i'm banned : 
Because i created an other account which is : Paranoid[Lost] and i submitted some scores on it.

Why do you think your account is restricted? 
Because i did not respect the rules of osu!. And what i did is not allowed on the game. I committed something that wasn't good on Bancho. I created a new account instead of playing on my main account.

Do you believe you did something wrong?
I have done something wrong one time, i created a new account to do many plays on Bancho, and this isn't allowed by the rules of Bancho because it breaks the rules of the community.

Are there any specific rules you KNOW you broke?
Yes, the first rule of the section Community Rules which is ''Each player may only have ONE account, ever. The first account you make during account registration is your one and only osu! account, from the moment of its creation and forevermore. This account is YOU. It is not anyone else - not your brother, your mother, your sister, your friend - it is YOU. Don't share your account with anyone else. You don't get to make a new one if you lose access to it. Keep it safe.''

Give us a full run-down of what you've done.
I created a new account to do news plays, and broke the leaderboards on purpose because i'm stupid and it's something who shouldn't be on osu! because it's break the leaderboards, and global ranking.

Why should we allow you back?
You should allow me to come back on osu, because i changed during these 6 months. I got really bored because i wasn't able to play with my friends, wasn't able to react to their plays, wasn't able to communicate with this beautiful community. 

How can we be sure you won't simply reoffend?
Because i'm swearing to never create new account and break the community rules in the future because it's useless and it hurts me and the community.
I won't reoffend because i was really bored to not be able to be in this community, and my friends, and the osu!catch community.
I won't reoffend because what i did is useless, it's just a waste of time for me, for the support, and the community.

When was the last time you logged into osu!?
The last time when i logged into osu! on Bancho was today. Now i only play on Bancho, because playing on private server is something bad for me, and the game. In my opinion, private servers give a bad reputation to the official server because the community in it are very toxic and don't respect the community rules, that's why i decided to stop playing on them and only play on Bancho.

Best regards.

**Comment by Ceotom** [comment]
Send it here: accounts@ppy.sh

**Comment by Ekario** [comment]
I already sent this to them, and so it's been 1 month since I didn't have too much response at once, I send my appeal here. Because, I had to be unrestricted 1 month or 2 weeks ago.

**Comment by Ceotom** [comment]
If you post it here nothing will change

**Comment by Ekario** [comment]
I said to myself, since there are a lot of people who have had peppy responses in this kind of subject I wanted to post here.

**Comment by peppy** [comment]
pe@ppy.sh
