### ISSUE TITLE
Adding a timing section through the timing panel in Editor causes it to be added 100 ms ahead

### ISSUE THREAD

**Issue by frukoyurdakul** [ppy/osu-stable-issues#357]
On the timing panel in Editor (opens by pressing F6) and clicking to "Add timing section" causes the inherited point (green one) to be added 100 ms ahead of its related red point. It should be added on the spot.

Should be an easy fix I think.

Screenshots:
![image](https://user-images.githubusercontent.com/33460209/74086894-6cdb0980-4a98-11ea-9adb-2e193e66d8b2.png)
![image](https://user-images.githubusercontent.com/33460209/74086915-9300a980-4a98-11ea-839b-76c63d22171c.png)

**Comment by peppy** [comment]
This is intentional. You shouldn't be placing two timing sections at the same point in time. It will place it at the current time if one doesn't arleady exist.

**Comment by frukoyurdakul** [comment]
I am sorry but why is this intentional again? It's not like they are both green points or red points, it's one green and one red point. Red point itself resets the adjusted slider velocity to 1 and a green point at the same time is used to adjust it. Putting it before or after doesn't work. This method is used in almost all maps.

**Comment by peppy** [comment]
I see. We could change it to allow this case.

**Comment by peppy** [comment]
Fixed in next cutting edge release.
