### ISSUE TITLE
Client doesn't sort same time same score correctly

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#36]
![screenshot1908](https://user-images.githubusercontent.com/39173355/65285238-d8cccd80-db09-11e9-8de5-da8f2d1d1f66.png)
As seen, the client displays kevin3333g as 5th, but when hovering over the score, it shows a "1" above the profile picture.
![hitogata 7 tie](https://user-images.githubusercontent.com/39173355/65285358-352fed00-db0a-11e9-9074-614af437f63b.PNG)
^The correct ordering as shown according to the website (both old and new)
The client's ordering for this 7-way tie is: 5, 6, 7, 4, 1, 2, 3

**Comment by nl-tatatat** [comment]
Thats because they all have an identical score. They're all tied for first. Might be intentional.

**Comment by Magnus-Cosmos** [comment]
This is definitely not intentional, because as shown on the site, they are sorted by score_id, there is no reason for the client to randomly flip/change the order

**Comment by smoogipoo** [comment]
osu-web is sorting incorrectly.

**Comment by smoogipoo** [comment]
Actually I take that back, it does look to be the client's fault here.

**Comment by MillhioreF** [comment]
Fixed in next cuttingedge.
