### ISSUE TITLE
Using cinema mod before viewing playback causes visual settings to be disabled

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#361]
[2020-02-13 01-06-14.zip](https://github.com/ppy/osu-stable-issues/files/4193866/2020-02-13.01-06-14.zip)
like this

**Comment by peppy** [comment]
Why would you want to change visual settings for cinema mod? The idea is that you watch the storyboard. Visual settings apply to gameplay.

**Comment by peppy** [comment]
Right, I see now what's happening.

This is fixed in lazer, very rare case so out of scope for stable.
