### ISSUE TITLE
Issues when uploading marathon maps (86mb)

### ISSUE THREAD

**Issue by MakcSan** [ppy/osu-stable-issues#363]
![image](https://user-images.githubusercontent.com/60064880/74584966-3282e680-501b-11ea-97a7-78bb2df5bd6c.png)
i tried to upload a work in progress 2 hour Marathon maps.
i also discussed this issue in a community 
error says:error while uploading: A server side error occurred. please try again later
i searched this issue on google
but nothing is helping me
this song length is over 2 hours (still wip only 2% completed xd). maybe is this the problem? but i dont think so
i looked at a wiki and it says if one of difficulty name was "Marathon" the file uploading limit is up to 100mb, and my filesize is around 80~90 it shouldn't cause issue of file size i think
i placed a note in end of the song and beginning to avoid uploading error of short map time against song length
but still this error is happening :c
please help me

**Comment by peppy** [comment]
@MakcSan could you please try again now?

**Comment by peppy** [comment]
I have tested and believe this is resolved. The limit server-side was set to 80mb, not 100mb. It now matches the specification correctly.

**Comment by MakcSan** [comment]
Its resolved thanks!
