### ISSUE TITLE
osu!.cfg Resetting 

### ISSUE THREAD

**Issue by HelveticaToast** [ppy/osu-stable-issues#364]
Sometimes after updating, osu! resets my .cfg file and reprocesses all of my beatmaps, and deletes most of the scores and replays. This has happened 6 times to me and its getting annoying.

**Comment by peppy** [comment]
This can only happen if you are changing PC username, moving your osu! install, or something else on your PC is deleting the files.

**Comment by Vikadoon** [comment]
Does it happen when you have multiple osu installs? I have 2 others, and have made certain that I am launching the right one. I have not changed my windows username, nor have any apps deleting files.

**Comment by peppy** [comment]
Again, if it's happening it is something else on your PC. osu! doesn't delete such files (there's no code to do so).

**Comment by Vikadoon** [comment]
> Does it happen when you have multiple osu installs?

**Comment by WinterIsPretty** [comment]
maybe it could overwrite the other osu files from the other installs 🤔

**Comment by Vikadoon** [comment]
I think because I'm quite certain I have nothing deleting files.

**Comment by peppy** [comment]
can you reproduce this by ween release streams?

**Comment by Vikadoon** [comment]
Ok, I will try to reproduce it.
