### ISSUE TITLE
Cannot process beatmaps because of this

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#365]
I have had this problem since October 2019 and for some reason, it thinks there is a file I am requesting that doesn't exist

https://cdn.discordapp.com/attachments/463638143422169088/678504431414935552/20200216_012317_compress_1.mp4

This is a big problem because I cannot process my beatmaps anymore and every time I open osu it does this.

I have reported this in December but was ignored.. please don't ignore this, the file does not exist I even had my computer search for the song overnight in my C drive.

**Comment by peppy** [comment]
Could you please read the issue? It is telling you which file is broken, so remove the file.

**Comment by WinterIsPretty** [comment]
I said there is no file!

**Comment by peppy** [comment]
install osu! to a new location and move your beatmaps and configuration across. it may be file system level corruption.
