### ISSUE TITLE
Osu crash when watch Quit User Score two times

### ISSUE THREAD

**Issue by ReDesignedJP** [ppy/osu-stable-issues#366]
If you check the score of the user who quit the game during multiplayer, osu will stop working.
![unknown](https://user-images.githubusercontent.com/33867923/74601367-ebf7bf80-50e0-11ea-87f2-376b678df773.png)

NullReferenceException

**Comment by peppy** [comment]
Could you please paste the raw exception text? (click to select and then copy it).

**Comment by Rumia0291** [comment]
``System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   위치: #=zDsGgjm2kc4kHQSMvR$A6$8b12PnGTownCDSbvjQWM_U8.#=zO2pHvBRd$AKv(#=ztcpJYvsO2JOEwm5C$vBNkng7i2IIT7QEYRz1F4Q= #=zMs6cVl5zwCVk, Nullable`1 #=z3hqTBFaF6D6F)
   위치: #=zDsGgjm2kc4kHQSMvR$A6$8b12PnGTownCDSbvjQWM_U8.#=zSp4Xy_cFikxX_99PN0Ft718=(Object #=zCuVvRXA=, EventArgs #=z4c6sczM=)
   위치: #=zsMnU$oQpAj76CKaYm_1P0VKZVxip.#=zKnmhVk4=(Boolean #=zCYVrv_QZQauKcSlnfg==)
   위치: #=zCrLSh7j6HMNCUzfCdm5bkMpdX_6MT1Iyog==.#=zHDgmu0u7GjuL(Boolean #=zeRvGX7o=)
   위치: #=zCrLSh7j6HMNCUzfCdm5bkMpdX_6MT1Iyog==.#=zIQXHC1D0Yagh(Boolean #=zeRvGX7o=)
   위치: #=zk22MDysxyfoAJWa7e3pFVZs=.#=zsb2MA$KV9Mef()
   위치: #=zguQE0qOcL06zNg$5Pg==.#=z0K7UOO0=(#=ztH_01yt9eaM87od7KyQYg3w= #=zC2TvaF0=)
   위치: #=zawrZjcDFGFN3WxT5WQ==.#=z9uELRh8=()
   위치: #=zAF9ftoWd40USr0eKMg==.#=zu$4zIfDNhcKQ(Object #=zCuVvRXA=, EventArgs #=z4c6sczM=)
   위치: #=zrhxphuscd8_tperuxbOYEXw=.#=zTo6PcBY=(Object #=zCuVvRXA=, EventArgs #=zSXcek70=)
   위치: #=zWFyMg3cxF6km0ppSI$Ax3as=.#=zYY1m1EZnfPdcADRrEQ==(Object #=zCuVvRXA=, EventArgs #=z4c6sczM=)
   위치: System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   위치: System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   위치: System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   위치: System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   위치: System.Windows.Forms.Application.Run(Form mainForm)
   위치: #=zWFyMg3cxF6km0ppSI$Ax3as=.#=z1r3G0ZI=()
   위치: #=zAF9ftoWd40USr0eKMg==.#=z1r3G0ZI=()
   위치: #=zsxC23dam3M26SVlPAA==.#=zBFA$LxQqV3VR(String #=zKT0vJ19XlKiR, Boolean #=zFal$SqUTp_kaIDi5zqOJw_8=, Boolean #=zn74D38aoz386Xfo46A==)
``

**Comment by Rumia0291** [comment]
Mania + Multiplayer

**Comment by osu-funkyfeelin** [comment]
Same here.
With the obfuscation, I'm not sure if our traces are the same.

https://osu.ppy.sh/community/forums/topics/1140394

> System.NullReferenceException: Object reference not set to an instance of an object.
> at #=zCrR7zTA5KiJCAQrea$_pTDAomxZ_59wLxqd8oIxhqaXU.#=zz494zOf1zMem(#=zX33IKcn6$bxsaStwBNTdGkeKd_FKw6lvO1eeh8Y= #=zIo2deIJ2KfVV, Nullable`1 #=zfHznPTbapZqW)
> at #=zCrR7zTA5KiJCAQrea$_pTDAomxZ_59wLxqd8oIxhqaXU.#=z5kQ_6$XqyO77LZk2F2BWAB4=(Object #=zF$EgHL8=, EventArgs #=zTOOPspU=)
> at #=zOM2Fn7Wr_IQ$PAG3iWQ9Hh2X4yDb.#=ze8KvzRI=(Boolean #=z82IEsljhKuRhyV5QrQ==)
> at #=zmZi9HU5_tozKeI9rGABgV8wIuHEzDbYU_w==.#=zFGMTSRuZS6An(Boolean #=zhzXWGzk=)
> at #=zmZi9HU5_tozKeI9rGABgV8wIuHEzDbYU_w==.#=z_B8nrKbPDm$I(Boolean #=zhzXWGzk=)
> at #=z6$LZuyBvLZHpyGdngMTS0d8=.#=zETSYz38rg8pl()
> at #=zsT_IlAb8javdc_h$Vg==.#=zvGUROxM=(#=zamuwZN_HnzppGnVeyAwo9sY= #=zNhx2r8A=)
> at #=zRXf0K_ptdpTbI0l0Pg==.#=zleYQg_w=()
> at #=z6aRu3E6oPh981Fu7wg==.#=zi0DyridF1ou$(Object #=zF$EgHL8=, EventArgs #=zTOOPspU=)
> at #=zfpwwcQmIthKuao73f9Ol7QM=.#=zETODGmk=(Object #=zF$EgHL8=, EventArgs #=zLqiN8w4=)
> at #=zc6HVqeBMg25ACLXvQfyoyo4=.#=z0UsNapEUZQAPJXRWHQ==(Object #=zF$EgHL8=, EventArgs #=zTOOPspU=)
> at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
> at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
> at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
> at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
> at System.Windows.Forms.Application.Run(Form mainForm)
> at #=zc6HVqeBMg25ACLXvQfyoyo4=.#=zduiz3N0=()
> at #=z6aRu3E6oPh981Fu7wg==.#=zduiz3N0=()
> at #=zWSZj_AFbINUxFYXWSA==.#=zx_dd28KuyOyV(String #=zFDAIxyVyEADb, Boolean #=zXGSSJQ50Xe$AWNSZWqe8rns=, Boolean #=zKnC62I7RHsSkcu2TCA==)

**Comment by peppy** [comment]
This should be fixed in the next cutting edge release!
