### ISSUE TITLE
osu!mania editor doesn't remember to Show Sample Name

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#369]
While mapping osu!mania, its a near necessity to enable the [View option "Show Sample Name"](https://i.imgur.com/LHPAHv8.png) this makes it so that every note you place in the editor that has a hitsound edition will show the name of that addition: W for Whistle, F for Finisher, and C for Clap. This is highly useful for seeing if you've missed a note to hitsound, or to compare hitsounds between difficulties. 

The only problem though is that you must enable this setting every time you open up the osu!mania editor. Even if you've enabled it before, the editor forgets. There have been many times that I've forgotten to enable this setting, and accidentally missed an unrankable issue because of it.

I am proposing two things:

1. Have the editor remember the state of this toggle between editor sessions (like other View toggles)
2. Have this setting enabled by default. 

Since this setting is near essential to mapping in osu!mania, I think its fitting to have it enabled by default. If a mapper wishes to disable it, they can toggle it off, and it'll be remembered in the future. This will greatly help newer mappers who might not even know to turn it on, and there are an extremely few cases where you might want to turn it off.

**Comment by peppy** [comment]
Thanks for the report, but I don't think we will be touching the mania editor in stable (the code was written by someone who is not longer on the dev team and very hard to work with).

You're more likely to find the lazer mania editor come to fruition first, so please keep a look out for that

**Comment by nl-tatatat** [comment]
Ahh thats a bummer. I was hoping this toggle could be fixed. Oh well

**Comment by peppy** [comment]
Would it makes sense to just change the default to on for all users?

**Comment by nl-tatatat** [comment]
Yes.

**Comment by peppy** [comment]
Should be fixed in next cutting edge.
