### ISSUE TITLE
Editor capitalizes default diff names by itself

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#373]
Rather a small but pretty annoying issue.

Sometimes user don't want to be the diff names capitalized because it fit with the song name. Example: https://osu.ppy.sh/beatmapsets/1114940#mania/2329040

When using "Easy", "Normal", "Hard", "Insane", the editor capitalizes the first letter in each of them automatically. It's only possible to access the non-capitalize difficult names by editing the .osu 

It shouldn't be necessary to do that though edit the .osu

**Comment by peppy** [comment]
Fixed in next release.
