### ISSUE TITLE
windows key temporarily disabled after alt+tabbing from osu!

### ISSUE THREAD

**Issue by rymeilema** [ppy/osu-stable-issues#374]
has been happening for about a month, i use alt+tab a lot to change screens, i do it a lot during pauses - i also use the shortcut for quickly changing windows based on the taskbar (windows+1, windows+2, etc)

after using either of these to switch away from the osu! fullscreen window, the windows key seems to not respond whatsoever for the next 5 ish seconds, with no real.. reason, or cause, that is apparent on first sight

**Comment by peppy** [comment]
Fixed in next cutting edge!
