### ISSUE TITLE
osu!direct displaying incorrect information when @ is used in difficulty name

### ISSUE THREAD

**Issue by MBomb-osu** [ppy/osu-stable-issues#376]
Quite self-explanatory from the title. Everything after an @ sign in a difficulty name isn't displayed in osu!direct, including star rating in those difficulties, and for some reason, the difficulty is always displayed as standard, even if the mode isn't.

https://osu.ppy.sh/ss/14563782/01fc 
https://puu.sh/FgGFV/04f3f46543.jpg

These are two different instances of the issue (both cases are catch difficulties that are marked as standard icons for some reason).

**Comment by peppy** [comment]
Fixed in next cutting edge.
 
![image](https://user-images.githubusercontent.com/191335/76823699-5161dc00-6858-11ea-97c4-7c15dd077117.png)
