### ISSUE TITLE
Taiko skinning is getting progressively more broken

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu-stable-issues#377]
Originally reported [here](https://osu.ppy.sh/community/forums/topics/1026086).

The update Beta 20200221 removed what little extent we had in customizing the hitcircle colours by altering the colours of taikohitcircle.png without anything about it in the changelog, and then later ended up in Stable 20200225.

Old look (taken from an old recording, before Beta 20200221):
![image](https://user-images.githubusercontent.com/12499153/75777285-e6a4a100-5d7f-11ea-8d0b-dff8c95199e0.png)
New look (Beta 20200221, Stable 20200225):
![image](https://user-images.githubusercontent.com/12499153/75777424-29667900-5d80-11ea-9a14-9c8e4b026041.png)

Back then, I thought it might be that using taikohitcircle.png of a different colour could actually be unintended behaviour (however horrible was the pain of having to basically remake the whole skin to re-harmonize the colours and having to suffer the bright kiai blinking of the default colours), but

Beta 20200303 broke another element of my skin with the same desaturation, taiko-bar-right.png that had blue edges for me before now has them grey. This one still hasn't made it into Stable, still doesn't have anything about it in the changelog, and I definitely don't think this is intended behaviour.

Old look (Stable 20200225):
![image](https://user-images.githubusercontent.com/12499153/75777564-6599d980-5d80-11ea-9536-cdebd68cc5ba.png)
New look (Beta 20200303):
![image](https://user-images.githubusercontent.com/12499153/75777709-a396fd80-5d80-11ea-8973-c2e3606f655c.png)

**Comment by peppy** [comment]
Colouring the base element is no longer supported, sorry!

You can achieve colouring using overlay elements (taikohitcircle-overlay). We may be able to add overlay elements for the full bar length, too, if required.
