### ISSUE TITLE
Part of skin not affect correctly

### ISSUE THREAD

**Issue by yuto0214w** [ppy/osu-stable-issues#378]
I don't know how to describe this. Please see the video.
OS: Windows 7 (64-bit)
Graphic: NVIDIA Quadro K600
Version: b20200225, b20200303beta, 
(Video is b20200303beta)
[AGDRec 20200303 215133 - YouTube](https://www.youtube.com/watch?v=B8ywkySotec)

Edit 1: Same bug occurred at oldest osu of all I have (2016).
Edit 2: Bug wasn't fixed on b20200304beta

**Comment by peppy** [comment]
you mean the thing where settings are stored per beatmap?

**Comment by peppy** [comment]
Closing as unsure-what-is-wrong. Please comment with further information or acknowledging this was a misunderstanding of above.

**Comment by yuto0214w** [comment]
I am awfully sorry about the delay and misunderstanding (of that).

**Comment by peppy** [comment]
No worries, we're debating whether to remove the feature since it's very hard to understand.
