### ISSUE TITLE
Unsubmitted maps inherit setID from folder

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu-stable-issues#38]
**Issue:** The editor gives the map a `BeatmapSetID` despite not being uploaded to BSS causing osu! to think that you don't own the set.

A workaround has been available: https://osu.ppy.sh/community/forums/topics/325639

**How to reproduce:** Drag and drop any audio file with numbers on the start of the file name (or just rename the folder it generates with numbers on the start). Doing so will cause osu! to give you "The beatmap you're trying to submit isn't yours!" warning.

Forum link: https://osu.ppy.sh/community/forums/topics/316897

**Comment by smoogipoo** [comment]
I can't replicate this one. I've tried importing song files named:
```
123.mp3
123 - asdf.mp3
```
Have also tried logging out before importing.

Can you post a video?

**Comment by Loctav** [comment]
Have you checked if the folder that was created upon importing also started with a number? Because this issue only seem to occur when the song folder itself starts with a number (and the client assumes this number to be the setID)

**Comment by smoogipoo** [comment]
They do...

![image](https://user-images.githubusercontent.com/1329837/65330200-09d5fc80-dbf5-11e9-86f7-e9d89ed3ca50.png)

Again, a video would be much appreciated.

**Comment by LeNitrous** [comment]
Have you tried leaving and re-entering after importing the MP3? Initially, the set ID is -1 however when saving then exiting, the set ID overwrites it to what those numbers are.

I'll provide a video tomorrow at best.

**Comment by smoogipoo** [comment]
Got it, thanks.
