### ISSUE TITLE
Show epilepsy warning in editor

### ISSUE THREAD

**Issue by MzudemO** [ppy/osu-stable-issues#382]
Maps that have a storyboard with quick strobing rightfully show a warning when playing them (if that option is selected by the mapper). This warning does not display when opening such a map in the editor, but the storyboard still appears.

I don't personally suffer from epilepsy so I don't know if it has the same effect as during gameplay, but I believe it wouldn't hurt to display it.

**Comment by peppy** [comment]
Not going to happen in stable. I'd recommend people affected use play mode.
