### ISSUE TITLE
Two identical Beatmapset cause a crash,and Aimode crash too

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#384]
Two identical Beatmapset,I don't know how it cause
![NDNR3)LR6EDYYMT1U {LCSS](https://user-images.githubusercontent.com/34775378/76546278-29742080-64c6-11ea-9f98-856d4121ed63.png)
![VYZG$I 4F{PMI(HUQ)(~5@H](https://user-images.githubusercontent.com/34775378/76546284-2c6f1100-64c6-11ea-8325-47f5673277b6.png)
![VLY{AS}OUDVZGX`9YY1FW8Y](https://user-images.githubusercontent.com/34775378/76546289-2e38d480-64c6-11ea-9540-45ec0e0ce789.png)

Aimod crash

![(`@63WJF5K%_MN`LT)AZCEX](https://user-images.githubusercontent.com/34775378/76546359-4f99c080-64c6-11ea-9028-006d34dfc3f4.png)
![HKKHC~DNRGSACRW2437$Y%6](https://user-images.githubusercontent.com/34775378/76546383-59bbbf00-64c6-11ea-945f-b2cf97adf154.png)
![T9}R4J9(QR{{KN)PCLN{AP0](https://user-images.githubusercontent.com/34775378/76546390-5cb6af80-64c6-11ea-811e-5d2a31bb19b7.png)
![@KL9@XD5%D9LT7SG_ZKO4~O](https://user-images.githubusercontent.com/34775378/76546605-c5059100-64c6-11ea-977e-293271a20924.png)

**Comment by peppy** [comment]
- No logs provided
- No beatmaps provided for reproduction

lease attach either or both and I will reopen this issue.
