### ISSUE TITLE
Unsubmittable Scores on Loved maps

### ISSUE THREAD

**Issue by xasuma** [ppy/osu-stable-issues#385]
There are a few maps that do not allow scores to be set, some of them allowed them during the first day or so after being loved and never again. Some of them have had their leaderboards wiped on the website but not in game, some haven't . 

A few examples: 
https://osu.ppy.sh/beatmapsets/129520#osu/327228
https://osu.ppy.sh/beatmapsets/147910#osu/572525
https://osu.ppy.sh/beatmapsets/598905#osu/1265925

Please allow scores to be set on all loved maps. Otherwise they should be removed altogether.

**Comment by peppy** [comment]
this isn't a client issue.

@ephemeralis will probably need to check on these. if they are disabled they were for a reason.

**Comment by xasuma** [comment]
I apologize I wasn't sure where to post this. But I posted it here because of the difference between the client and the website. If you notice here (Insanity^2 diff) https://osu.ppy.sh/beatmapsets/129520#osu/327228 , there are no leaderboards on the website, but the client has a leaderboard. There seems to be something strange going on in the client that its making it display a leaderboard when there isn't one.

**Comment by peppy** [comment]
Aha, we can fix that one. Should be fixed now.

**Comment by xasuma** [comment]
While this is still open, I think its a good chance to bring up these two easy diffs from ranked sets that have no leaderboards for some reason. Not sure if its similar to the above, or why they have no score submission available. 

https://osu.ppy.sh/beatmapsets/126#osu/554242
https://osu.ppy.sh/beatmapsets/957#osu/554239

Both easy diffs. 

Thank you!

**Comment by Sleepteiner** [comment]
It is worth mentioning that those two Easy difficulties had a full leaderboard in-game that you could submit scores to. That was until a little over three years ago when a change in response to [this forum thread](https://osu.ppy.sh/community/forums/topics/527670) was made. The change was meant to fix some issues with some Loved leaderboards and unintentionally broke those two difficulties even further than they already were.

**Comment by peppy** [comment]
will need @ephemeralis for the remaining issues, for sure :)

**Comment by Ephemeralis** [comment]
The maps listed in the OP were intentionally disabled due to the fact that it is impossible to submit scores on them due to overlapping hitobjects and other shenanigans. This is most obvious in the Graces of Heaven set.

**Comment by peppy** [comment]
Fixed both easy maps mentioned above. Closing this as resolved.
