### ISSUE TITLE
Clicking a note just before the first 50 hit-window results in a miss

### ISSUE THREAD

**Issue by hostilew** [ppy/osu-stable-issues#386]
https://www.youtube.com/watch?v=DTJ6NKQDcqQ&feature=youtu.be
As you can see in the video there are 2 stages before an object is clickable, notelock, and then the time just before the 50 hit-window where a click will result in a miss, then the hit-window where you can click the note safely. This doesn't seem like intended behavior because it's so complicated, but if it is intended behavior or if the scope of modifying notelock is too large then this issue can be closed. 

Just to describe why this is significant, at higher ar, you can end up clicking absentmindedly, for example during break, before even realizing the object is there and it will register as a miss without giving you a chance to hit the note correctly.

**Comment by peppy** [comment]
This is intended behaviour.
