### ISSUE TITLE
Stacked objects are broken in editor

### ISSUE THREAD

**Issue by rgbeing** [ppy/osu-stable-issues#388]
osu! help forum sent me here: [Link](https://osu.ppy.sh/community/forums/topics/1035255)

Objects are not in its place in editor when they are severely stacked. I don't know if it is caused by stack issue, but it appears to me when objects are stacked.
Although all of my computers are suffering from this bug, support team in the forum said this is not reproducible in his computer, so this bug may not always be the case.

![Imgur](https://i.imgur.com/ujB3Noc.jpg)
▲ Crashed in editor

![Imgur](https://i.imgur.com/vhcDwE8.jpg)
▲ It should looks like this.

Map here is [DJPop's Marisa Hard diff](https://osu.ppy.sh/beatmapsets/243)
Version in trouble is both stable(20200304.1) and beta(20200304beta)

**Comment by peppy** [comment]
This is likely due to the beatmap being so old. When you open it in the editor it converts it to a newer version which has different algorithms. You can fix this in this map for instance by decreasing stack leniency.

Please comment if you are seeing this in a recent map, else this is as-intended.
