### ISSUE TITLE
Translations text files should be Unicode normalized

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-stable-issues#389]
Some of the Vietnamese translations are not being NFC-normalized, which causes the problem as seen on the below image. Normalize (NFC) the translation text file solves the problem.

![unicode_unnormalized](https://user-images.githubusercontent.com/16283764/76702707-8eb25680-66fe-11ea-9300-2bd8b5800957.png)

Btw, I also see many (user-submitted) Vietnamese translations on Google Translate not using pre-composed characters, so I think you should running an normalization program before using these translation.

**Comment by peppy** [comment]
We aren't updating translations in stable any more, but you can attach a normalised copy of the .txt in this thread if you would like me to look into updating it.

**Comment by huupoke12** [comment]
I used `uconv` to generate the NFC-normalized file: `uconv -x any-nfc -o vi-VN-nfc.txt vi-VN.txt`
[vi-VN-nfc.txt](https://github.com/ppy/osu-stable-issues/files/4341300/vi-VN-nfc.txt)

**Comment by peppy** [comment]
Thanks. I've updated this. Please give it a few days to propagate.
