### ISSUE TITLE
When I use Wii Control in Cuttingedge 20200316,osu! crash

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#392]
![QQ截图20200316214922](https://user-images.githubusercontent.com/34775378/76764733-4e230d80-67d0-11ea-9f9e-df40689d56eb.png)

**Comment by peppy** [comment]
missing any form of useful details. please at leasst provide a crash log.

**Comment by cdwcgt** [comment]
When I tried to recreate the problem extraction log, he fixed it, it was supposed to be a spacing problem, it should be fine now
