### ISSUE TITLE
taiko-bar-right.png not displaying any color

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#393]
I couldn't find anything about this in changelogs looking through the past couple of months so I'm pretty sure it's a bug

So like in my taiko skin I normally use this as the taiko-bar-right.png image, to fit the skin's color scheme of being very red+brown overall->
![taiko-bar-right](https://user-images.githubusercontent.com/33286824/76890413-b4a23d00-685d-11ea-8e1f-00157fb147a7.png)

How it looked before->
![screenshot326](https://user-images.githubusercontent.com/33286824/76890628-1367b680-685e-11ea-98fc-858e735aa3b3.jpg)

How it looks now->
![screenshot384](https://user-images.githubusercontent.com/33286824/76890647-1bbff180-685e-11ea-820c-2e20d5572c03.jpg)

It was very shocking to go and play taiko just to find my personal skin is bugging out for some reason, and the image in the folder is still normal, I tried to fix it but couldn't figure out the cause.

![image](https://user-images.githubusercontent.com/33286824/76891453-668e3900-685f-11ea-94cd-d52ab60803e2.png)

**Comment by peppy** [comment]
This is actually an intentional change to counter people using skins to make the game easier. Apologies that it affects your skin. We will continue to iterate to try and bring back colour to these elements.

**Comment by peppy** [comment]
Closing for now.
