### ISSUE TITLE
Allow maps that exceed the score limit to have leaderboards

### ISSUE THREAD

**Issue by NevarrenF** [ppy/osu-stable-issues#394]
Currently, maps that exceeds score limit cannot have leaderboard, making maps like [THE ORAL CIGARETTES - Songs Compilation](https://osu.ppy.sh/beatmapsets/970063) and [TWICE - TWICE MEGAMIX](https://osu.ppy.sh/beatmapsets/1030499#osu/2154990) sit in the graveyard when they are completely okay to be ranked or at least, loved.

This happens because of how scorev2 scores are not being submitted by the client, thus making leaderboards on such maps are unnecessary. Which is very unfortunate as fairly huge portion of the community wants maps like these to get leaderboard for competition, as it is requiring a much larger scope of skills in order to pass or even, FC the map.

Due to the reasoning above, I believe enabling leaderboard on such maps would be highly appreaciated by the community as it will unlocks longer maps to get ranked and larger scope of competition. Therefore I suggest these changes, you can pick anything that suits better with current ecosystem of osu!:

- Make scorev2 scores on maps that exceed scorev1 limit to be submitted
- Remove score limit with the expense of removing 32-bit support

Any more opinions are absolutely welcomed! I am sure anyone else could come up with better options to resolve this problem.

Huge thanks to @rorre for helping me write this.

**Comment by peppy** [comment]
ScoreV2 submissions have now been enabled, so these beatmaps can be ranked now. I've made changes server-side to allow leaderboards to be shown for v2 for such beatmaps.
