### ISSUE TITLE
Black screen after match is aborted in multiplayer

### ISSUE THREAD

**Issue by timiimit** [ppy/osu-stable-issues#397]
I finally got around to posting this issue.

In multiplayer there's an issue when command *!mp abort* is used right after match is started but before the map loads. If used fast enough, screen will turn completely blank and you need to press the back key twice (sometimes more) to get back to the lobby. This may have also happened when the command is used while playing, but I'm not completely sure about that.

Here's a [video](https://youtu.be/dcQpBJ8W9sY) showing what happens. In the video I needed to press back key 2 times before I got back to the lobby. Both presses are heard in video.

*!mp abort* is often used that fast, when multi gets stuck with "Waiting for players..."  message (which is yet another issue on its own).

Personally I've been experiencing this issue for at least 4 months now.

**Comment by peppy** [comment]
Did you end up finding a solution for this, or has it stopped happening possibly?
