### ISSUE TITLE
Random mod in Taiko

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-stable-issues#399]
I know stable is more or less feature locked, however recently Mirror mod was added to Mania, and Random mod would be appreciated by many players in the Taiko community. I'm only requesting this because it's a low effort addition that would probably require less than 15 minutes to add, as large chunks of logic can be copied from Mania. If it's absolutely not ok, feel free to close this.

**Comment by smoogipoo** [comment]
How would random work in taiko? Randomise the colour of every single note?

Worst case we can implement this in lazer.

**Comment by peppy** [comment]
We'll add it in lazer. There's too much overhead in adding it in stable (infrastructure / icon / etc / etc).
