### ISSUE TITLE
Search text gets cleared when pressing escape to return to level select

### ISSUE THREAD

**Issue by percyqaz** [ppy/osu-stable-issues#4]
To replicate:
- Type something into the search on level select menu (can be editor level select too)
- Play or edit a map
- From the pause menu, editor or score screen press escape to return to level select
- The search text will be cleared
Expectation: search text is not cleared as it should only clear when returning to the main menu or when I press escape while I am on the level select screen

I'm sure this is a bug because when I leave by clicking buttons (for example the quit button in the editor) the text is not cleared, only when I press the key.

I believe what is happening is that when you press escape to leave a screen, on the next frame the level select screen also sees that escape is pressed and clears the search text.

This is hopefully a quick fix (maybe search box is checking for held key rather than tapped key) and would be appreciated as I often find my searches deleted after every score I set

**Comment by peppy** [comment]
Fixed in next Cutting Edge build.
