### ISSUE TITLE
If skin used, selection-options fades down when beatmap started

### ISSUE THREAD

**Issue by Akorian** [ppy/osu-stable-issues#400]
Hi,
this is my first post on GitHub so I apologize beforehand for anything I could do wrong.
The skin I use uses a custom selection-options. And the problem with that is, that it fades downwards when I start a beatmap. I couldn't find a thread with this problem (which surprised me) but ok. So I made this post.
When I understand correctly, the upper part of the selection-options isn't supposed to get skinned. BUT it gets skinned by a lot of users and skinners. Thus I think this could be fixed.

Here are 4 pictures, that show what I mean. I am sure almost everyone who played OSU with a skin, had this problem.

![1](https://user-images.githubusercontent.com/37375458/77258722-d136de80-6c7c-11ea-8227-cc7e3e0c93b5.PNG)
![2](https://user-images.githubusercontent.com/37375458/77258724-d2680b80-6c7c-11ea-8572-592a32a6ede5.PNG)
![3](https://user-images.githubusercontent.com/37375458/77258728-d5fb9280-6c7c-11ea-8ab6-777fbed40f83.PNG)
![4](https://user-images.githubusercontent.com/37375458/77258729-d72cbf80-6c7c-11ea-964c-cf61a28b8f2a.PNG)

**Comment by stanriders** [comment]
This is probably intended? selection-options wasnt made for fullscreen overlaying

**Comment by Akorian** [comment]
So there is no dedicated element for this upper-part? Then this is, what should be fixed. There are so many skins which change this upper part of the skins. Even the White Cat skin has this problem. (They tried to hide it and make it less bad, but it is still a thing that triggers me every time.)

**Comment by stanriders** [comment]
Wait for lazer

**Comment by peppy** [comment]
Please note that skins using this are reducing your performance drastically and should probably be avoided at all costs. A fix would be for the skinners to request a proper element rather than hack something else to do what they want. Very unfortunate for players using such skins.
