### ISSUE TITLE
Preview Point playing incorrectly

### ISSUE THREAD

**Issue by XiriouZ** [ppy/osu-stable-issues#401]
Sometimes, when I insert a Preview Point in my maps, it starts either earlier or much later than it should, the closer to the song's end I put it, the more delay it has.
 I'm using Stable, but it happens on Cutting Edge as well.
Video showing the problem: [https://www.youtube.com/watch?v=TFi2-U03tTU](url)

**Comment by peppy** [comment]
Did you forget to update it on every difficulty?

**Comment by XiriouZ** [comment]
> Did you forget to update it on every difficulty?

All of them have only 1 difficulty and it's the one shown in the video

**Comment by STCapricorn** [comment]
what type of bit rate did you use for the mp3s? afaik, it happens with mp3s that *aren't* constant bit rate-encoded.

**Comment by XiriouZ** [comment]
I don't remember if it was 145-185 or 170-210, and the rest of settings are default in audacity. But I always those kbps when I need to make the MP3 file lighter (the 5mb rule is kinda annoying for long maps ngl)

**Comment by peppy** [comment]
Sounds like it could be VBR related. does the same issue happen in lazer? lazer doesn't prioritise performance for loading and will always do a "long" load which should result in correct positioning.

**Comment by XiriouZ** [comment]
I just checked and lazer plays the preview point as it should, so the problem is in the old client

**Comment by peppy** [comment]
I'm not sure we can change this as it would add perceivable latency at song select. lazer achieves this by threading a lot better. will maybe take a look and see if it can be resolved, but do know that you can avoid this by using CBR. not that i would recommend using CBR. maybe just go with it and be assured your maps will sound correct on lazer :).

**Comment by XiriouZ** [comment]
Okok, thank you!
