### ISSUE TITLE
Conversion Mappings does not copy standard mode positions to Expected Conversions file. 

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-stable-issues#402]
When testing out the Conversion Mapping function, I noticed that through the Standard Conversion Mappings only copy the start time and not the position into the expected conversion file, it does in the case of Catch the Beat. However, the ruleset I am testing with requires a std position to calculate the correct position.

[Beatmap](https://osu.ppy.sh/b/2240647)

[Conversion Mapping (Osu) files](https://github.com/ppy/osu-stable-issues/files/4368554/mappings.zip)

**Comment by peppy** [comment]
@Coppertine please test on cutting edge.

**Comment by Coppertine** [comment]
This was on the latest version of cutting edge

**Comment by peppy** [comment]
As in we pushed an update, it should now be fixed, please test again.
