### ISSUE TITLE
medal unlock animations will show medals at different sizes

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#405]
currently medal images at the score results screen may display in different sizes as pictured below
![image](https://user-images.githubusercontent.com/33286824/77585260-9326fe00-6eba-11ea-9324-a89304792de9.png)
![image](https://user-images.githubusercontent.com/33286824/77585264-94f0c180-6eba-11ea-9048-cb58cb8c314f.png)

it may be dependent on which medal is being unlocked, but there's no way for me to check that since you can only unlock each medal once. the bigger hyun medal is definitely more nice and fulfilling to see, so other medals being smaller should get fixed.

**Comment by Ephemeralis** [comment]
This should be (mostly) fixed now, once the image server cache is refreshed. Thanks for pointing this out!
