### ISSUE TITLE
The client thinks certain ranked maps are unranked

### ISSUE THREAD

**Issue by Sleepteiner** [ppy/osu-stable-issues#406]
There are a number of ranked maps that the client mistakenly thinks are unranked. This can be temporality fixed by scrolling over the map with an online leaderboard selected, but a few days later, they will be broken again. This can cause a few issues.

1. It messes with the Ranked Status grouping. https://osu.ppy.sh/ss/14673657/80dd (I only have ranked mapsets. Ignore the Loved section, that is where the old TAG maps are, which should be re-ranked, imo, but that is different topic.)
2. It causes the game to forget what score you have on the affected map until scrolling over the map again with an online leaderboard. https://osu.ppy.sh/ss/14673681/d280
3. It can sometimes cause already downloaded maps to reappear in osu!direct, although, this seem to be happening less lately.

There are two causes that I know of.

The mapset was copied and reuploaded by another user, causing the client to think that the ranked map is the unranked copy. This is sometimes fixed by the copy mapset being deleted by the user, but occasionally the client keeps thinking that it is the copy even after it was deleted. The way to find which map the client thinks the ranked map is is to wait until it breaks and then scroll over the map with local ranking selected and click the "Quick web access for this beatmap" button. Here are some examples that happen to be broken for me just today, which means that this isn't a full list of every map affected:

[ranked mapset -> what the client links to]
1. https://osu.ppy.sh/beatmapsets/160201#osu/391522 -> https://osu.ppy.sh/beatmapsets/229249#osu/533497
2. https://osu.ppy.sh/beatmapsets/92347#osu/250277 -> https://osu.ppy.sh/b/2158145
3. https://osu.ppy.sh/beatmapsets/45307#taiko/145032 -> https://osu.ppy.sh/beatmapsets/1028283#taiko/2152953
4. https://osu.ppy.sh/beatmapsets/35546#osu/142356 -> https://osu.ppy.sh/beatmapsets/98722#osu/263090
5. https://osu.ppy.sh/beatmapsets/18260#taiko/65313 -> https://osu.ppy.sh/beatmapsets/60284#taiko/248091
6. https://osu.ppy.sh/beatmapsets/17450#osu/62523 -> https://osu.ppy.sh/beatmapsets/56516#osu/381546
7. https://osu.ppy.sh/beatmapsets/20891#taiko/81307 -> https://osu.ppy.sh/beatmapsets/101796#taiko/281444
8. https://osu.ppy.sh/beatmapsets/30296#osu/101727 -> https://osu.ppy.sh/beatmapsets/180001#osu/432634
9. https://osu.ppy.sh/beatmapsets/17953#osu/74852 -> https://osu.ppy.sh/b/442678
10. https://osu.ppy.sh/beatmapsets/79236#taiko/221441 -> https://osu.ppy.sh/beatmapsets/102664#taiko/271991
11. https://osu.ppy.sh/beatmapsets/601607#mania/1270895 -> https://osu.ppy.sh/b/1761197
12. https://osu.ppy.sh/beatmapsets/6593#osu/33181 -> https://osu.ppy.sh/b/619731
13. https://osu.ppy.sh/beatmapsets/940726#osu/1964685 -> https://osu.ppy.sh/b/2285286
14. https://osu.ppy.sh/beatmapsets/1025972#osu/2172642 -> https://osu.ppy.sh/b/2286613
15. https://osu.ppy.sh/beatmapsets/1051396#taiko/2197281 -> https://osu.ppy.sh/b/2204300

The diff name has a unicode character. Examples:

1. https://osu.ppy.sh/beatmapsets/326608#osu/725139 (†)
2. https://osu.ppy.sh/beatmapsets/641854#osu/1360912 (†)
3. https://osu.ppy.sh/beatmapsets/673290#osu/1513093 (’)
4. https://osu.ppy.sh/beatmapsets/846636#osu/1770695 (’)
5. https://osu.ppy.sh/beatmapsets/740990#osu/1563135 (—)
6. https://osu.ppy.sh/beatmapsets/965125#osu/2020385 (†)
7. https://osu.ppy.sh/beatmapsets/857638#osu/2223893 (†)
8. https://osu.ppy.sh/beatmapsets/776165#taiko/1630856 (’)

There are also some maps that have this issue, but I have no idea why. This could be due to another cause that I can't figure out, or maybe the map files are broken on my end. Here are some example, just in case it helps to see them:

1. https://osu.ppy.sh/beatmapsets/66516#osu/194041
2. https://osu.ppy.sh/beatmapsets/63240#osu/225594
3. https://osu.ppy.sh/beatmapsets/60#osu/148
4. https://osu.ppy.sh/beatmapsets/476646#osu/1021815

Again, these are not complete lists. Not all regularly glitched maps become glitched every time you launch the game if you temporarily fixed them the day before. Also, I only linked one diff per mapset, but sometimes multiple diffs from one mapset are affected, especially when the cause is related to a mapset being copied.

This has been an issue for a long time now and has been shown to be widespread for those who have these maps. Here is an old forum thread for context: https://osu.ppy.sh/community/forums/topics/329236 . Most of the information in that thread is either outdated or just wrong, especially the lists of maps affected, as that changes as copied mapsets are created and deleted. So, don't take the information in there as fact.

**Comment by Sleepteiner** [comment]
This seems to have been fixed with the "Fetch beatmap ranks and statuses without relying on bancho" update. I don't think I've seen it happen once since then and I've seen a couple other people say the say thing. I probably shouldn't say this with fully certainty, but the issue really seems like it might finally be gone.

**Comment by peppy** [comment]
I did fix a few issues in that change. Thanks for confirming, will close for now!
