### ISSUE TITLE
fps drops because no reason

### ISSUE THREAD

**Issue by neutoreu** [ppy/osu-stable-issues#407]
cpu:Intel Core i3 4130 @ 3.40GHz
ram:8gb dual channel
graphics:AMD Radeon HD 6570
hdd: 1tb seagate (new)
after the latest updates, freezes up to 20ms and more started to appear during the game.

**Comment by peppy** [comment]
Please restart your PC and check any recent changes.

here's a guide to help you: https://osu.ppy.sh/help/wiki/Performance_Troubleshooting
