### ISSUE TITLE
incorrect scaling with windows scaling

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [ppy/osu-stable-issues#408]
I'm running a two monitor setup, one 4k and one 1080p. 4k monitor is at 150% windows scaling, 1080p is at 100% windows scaling. When I try to open the game on my 1080p monitor, the game thinks my 1080p monitor is 2880x1620. And when I switch it back to 1080p, cursor position is scaled by 1.5x (sensitivity is at 1.0x).
vid: https://streamable.com/rb7v1

**Comment by peppy** [comment]
Can you fix this by starting osu! on the correct monitor? I don't foresee this being fixed from our end as it is a very edge case (and not a simple one to fix).

**Comment by sometimeszzzzzzz** [comment]
Vid is with osu started from the 1080p monitor. Yeah this is definitely some problem from my end, cause I have a working version of osu installed that does scale correctly. But when I copy the game to a different location, it doesn't scale correctly anymore ¯\_(ツ)_/¯
