### ISSUE TITLE
Cannot see key count in direct

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#411]
When looking for mania maps in osu!direct, you can't tell the difference between a 4k and a 7k map. Can this be fixed?

**Comment by Feerum** [comment]
This is more a feature request than a issue. It's also not visible on the website (only when hover with mouse over the mania icon on the beatmap card).
As far as i know there's already a feature request for that.

**Comment by peppy** [comment]
On hover of difficulty sounds correct? Key count changes per difficulty after all.

**Comment by peppy** [comment]
Added this for osu!direct
