### ISSUE TITLE
osu!direct is slacking behind on ranked status

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-stable-issues#415]
A new map gets ranked, but then when you go into osu!direct it's not there.
Taiko maps for example right now look like this:
![image](https://user-images.githubusercontent.com/34809632/78850168-cdde7980-7a16-11ea-91e6-0c095a136626.png)
But there are already new ranked taiko maps since 12 hours ago:
![image](https://user-images.githubusercontent.com/34809632/78850225-f1092900-7a16-11ea-8b0d-5b14b6dd26fb.png)
Showing you I don't have any taiko maps installed in song select:
![image](https://user-images.githubusercontent.com/34809632/78850312-2f064d00-7a17-11ea-8809-a0b6856e5d82.png)
Screenshot showing that the map is considered qualified still:
![image](https://user-images.githubusercontent.com/34809632/78850445-886e7c00-7a17-11ea-8dc4-43a2cc15e05c.png)

**Comment by peppy** [comment]
Should be fixed now. Please confirm.

**Comment by GrilledCheeese** [comment]
It's showing the latest beatmaps right now so I think it's fixed. I'll make a new issue if it changes
