### ISSUE TITLE
osu!lazer tournament client source ipc issue

### ISSUE THREAD

**Issue by CebollaVladimir** [ppy/osu-stable-issues#416]
it gets the IPC from the client I use for playing normally instad of getting it from the tournament client I installed (to have both separated). Its any way to change the IPC address which gets the lazer tournament client?

**Comment by omkelderman** [comment]
you can since lazer version https://osu.ppy.sh/home/changelog/lazer/2020.312.0

set an environment variable `OSU_STABLE_PATH` containing the path to your osu!stable installation which lazer should use for IPC

**Comment by peppy** [comment]
Closing this as the above solution is correct (we use it for official tournaments so it definitely works).
