### ISSUE TITLE
osu! doesn't extract file when importing beatmap with a file with long filename

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-stable-issues#418]
This beatmapset's background filename is long: https://osu.ppy.sh/beatmapsets/662120
This makes the file missing in the beatmapset folder after importing.
I think this should be handled, or at least notify the user about the problem, not failing silently.

**Comment by peppy** [comment]
What's your osu! install (full) path?

This is a very hard one to fix as the reference to the file would also need to be updated in the .osu file if it was to work as expected. This is also fixed in lazer already, for what it's worth.

**Comment by huupoke12** [comment]
Since I'm using Wine, its default install location is `C:\Users\huupoke12\Local Settings\Application Data\osu!`
Moving the osu! folder to outside the prefix (which will be mapped to `Z:\home\huupoke12\osuDir`) solves the problem.
> This is a very hard one to fix

Yes, I also considered if this is worth fixing because it requires changing many references in files, especially with storyboard elements. But can you make it

> not failing silently

There should be a notification about it or at least being written to the logs.

**Comment by peppy** [comment]
The best fix may be fixing the beatmap itself. @ephemeralis wanna haxsubmit fix this ranked map?

**Comment by Ephemeralis** [comment]
I've updated the beatmap to have a much more reasonable filename for its background (clover) and changed all references in both the .osu and .osb files.
