### ISSUE TITLE
Visualizer bug

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu-stable-issues#419]
Problem Details:
I changed from a normal song (Which worked just fine) into a musicless song (SFX Map).

Well... This happened. (See Screenshot)

SFX-Map mentioned above:
https://osu.ppy.sh/beatmapsets/152065#mania/374464

======================================================================================

Video or screenshot showing the problem:
https://osu.ppy.sh/ss/13379347 (Old screenshot system)

The Screenshot showed the visualization peaking out way past its supported limits. 

======================================================================================

osu! version: 20190611.2 and latest

**Comment by smoogipoo** [comment]
Screenshot broken, but given that this is a rare occurrence and not game-breaking, it falls under the category of issues we're not looking to fix.

**Comment by GamingWithJanko** [comment]
https://osu.ppy.sh/ss/14868851/cd18

V 20200427.2

**Comment by GamingWithJanko** [comment]
Since the old screenshot doesn't load anymore here's the same issue visualized again:
https://osu.ppy.sh/ss/15658110/66ad

v 20200918.3

![66ad](https://user-images.githubusercontent.com/48768314/95666190-9bddd980-0b57-11eb-81cc-06baf95dccf9.jpg)
@smoogipoo

**Comment by peppy** [comment]
Please just restart the game to fix this. It's either an issue with the audio libraries or audio hardware/drivers on your system and will not be fixed on stable. If you can reproduce on lazer we will likely be more interested in tracking the issue.

**Comment by GamingWithJanko** [comment]
Stager is an SFX map (no music, just effects)
if one switches to another song, that visualizer gets disabled it seems. 
Going into the song carousel and back on the main menu fixes it again. 

this visualizer but only works with SFX Only maps.

I'll look later, if that works in lazer too. 

'Til then!
