### ISSUE TITLE
The preview skin button is way too close to the dropdown

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#42]
The preview skin button automatically brings you away from whatever screen you were looking at, like exiting out of multiplayer lobbies. Lots of people have complained about the placement of this button; can you just reorder it somewhere else?

**Comment by MillhioreF** [comment]
Considering adding a prompt dialog when this is clicked instead since I do hear a lot of complaints about hitting it by accident.

**Comment by MillhioreF** [comment]
Prompt added in next cuttingedge.
