### ISSUE TITLE
updating -> deleting -> redownloading a map makes it not show up in selection

### ISSUE THREAD

**Issue by ackhack** [ppy/osu-stable-issues#420]
As stated in Title,
when i update, then delete, then redownload a map, it doesnt show up
in beatmap selection until i press f5 to reprocess my 20k beatmaps,which takes a while.

Already happend with 2 maps now [1](https://osu.ppy.sh/beatmapsets/1034179#osu/2162263) [2](https://osu.ppy.sh/beatmapsets/1132633#osu/2365752).

The folder of the beatmap exists, but osu! doesnt seem to register it, redownloading the map again makes a duplicate of the folder and still doesnt show up in selection.

**Comment by peppy** [comment]
Should be fixed by the fix I made for https://github.com/ppy/osu-stable-issues/issues/349. Please test in next cutting edge release.
