### ISSUE TITLE
Group by bpm not working in french 

### ISSUE THREAD

**Issue by Dyf-Tfh** [ppy/osu-stable-issues#421]
Problem details: The BPM value are not displaying correctly, instead there are zero everywhere
Only affect osu! in french. English is fine 

![screenshot006](https://user-images.githubusercontent.com/39443642/79266711-50908a00-7e98-11ea-8268-465996439f83.jpg)

osu! version: Stable 20200320

**Comment by peppy** [comment]
Fixed in next cutting edge.
