### ISSUE TITLE
Ever Increasing lag

### ISSUE THREAD

**Issue by manmathew** [ppy/osu-stable-issues#422]
So my problem started ever since I got a dock for my laptop.
Before, the laptop would only use the intel hd 4400 graphics to power the display, whether it was the internal display, or an external one using the dp or vga. Because it would use the intel graphics, I had compatibility mode turned on, but regardless, the game would run perfectly fine with a solid 4 ms of input latency when in a map.
I'm not sure why, but I am happy that it is this way, using the dock and having the dp cable plugged into the dock rather than the laptop has the amd firepro m4100 power the display. The amd graphics runs considerably better, with higher frames, and it runs both with and without compatibility mode with no noticeable change in the input latency.
The problem is that for some reason, the input latency just gradually increases, and the frame rate decreases with it. Changing the fps limit doesn't help (I'm on unlimited since it gives the lowest input latency), and the problem just resets its cycle every time I reopen the game.  Interestingly enough, VSync seems to help with the framerate, however the input latency is still pretty high with it, so it's not really a solution.
I have a link to a video demonstrating the issue while using the lightest skin I have and disabling aero. In the video I stopped it at around 14ms, however it doesn't stop there, and I've reached 22ms before. Hopefully it will help the diagnosis.
If this issue can't be resolved, oh well, but it is fine since I can just go back to using the intel graphics and not having this issue again, just that I would prefer if the issue could be resolved.
Link to video: [https://drive.google.com/open?id=1AkWDJHzrCTB534_-dE56_tqqxdaP3Nrg](url)

**Comment by peppy** [comment]
all i can think of is a bug with drivers (doubt it is osu! side).

we don't have the resources or knowledge to debug such issues, sorry (would need the same hardware here).

**Comment by manmathew** [comment]
I believe I have the answer to the problem.
When this problem happens, I am using windows 7.
I created a new partition and installed windows 10, and installed the same drivers (granted they are the windows 10 version from AMD's website), and this problem was non-existent.
It still is unclear if it's just osu not being compatible with windows 7 or not, but most likely not, as it runs just fine with the Intel graphics and an nvidia card.

**Comment by peppy** [comment]
windows 7 isn't really supported any more, so that's a good move on your end
