### ISSUE TITLE
Score V2 should either be always on or off for nomod scorebreaking maps

### ISSUE THREAD

**Issue by NevarrenF** [ppy/osu-stable-issues#423]
There's an issue with maps that force ScoreV2 in qualifed/ranked, players that use NoFail are able to circumvent the forced ScoreV2 score limit thus leading to leaderboards that aren't exactly fair. As seen on https://osu.ppy.sh/beatmapsets/986003#osu/2062833
![U3HjXfn](https://user-images.githubusercontent.com/62331647/79671099-571b4c00-818d-11ea-939c-98ba86aee9c7.png)

I would say a possible fix would be force the ScoreV2 limit to all mods for a mode, but the ScoreV2 setting would be separate per game mode. Also the fix should probably only apply to maps that break score with NoMod as to not make maps such as https://osu.ppy.sh/beatmapsets/29157#osu/156352 forced ScoreV2 when it only breaks score with Double Time

**Comment by peppy** [comment]
Fixed on cutting edge.
