### ISSUE TITLE
Scores for a certain Loved Taiko map don't submit under some conditions

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-stable-issues#428]
![](https://i.imgur.com/7Z0HaeX.png)
![](https://i.imgur.com/DSqZtEv.png)
![](https://i.imgur.com/K299RVU.png)
![](https://i.imgur.com/hCh9j6x.png)

map: https://osu.ppy.sh/beatmapsets/1124769

As far as I'm aware peppy knows Japanese, so i wont translate the screenshots

**Comment by peppy** [comment]
Fixed for stable build. We'll fix for cutting edge in next release.
