### ISSUE TITLE
No way to refresh skins list

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#43]
Title says it all

**Comment by peppy** [comment]
a button could maybe be added for this, unsure.

**Comment by smoogipoo** [comment]
Was thinking maybe adding a refresh on Ctrl+Alt+Shift+S, may be difficult to implement.

**Comment by TheUnkn0wnN00b** [comment]
I'm thinking F5 similar to the beatmaps list, but that could mess up when you try to use it with settings open in the beatmaps list.

**Comment by peppy** [comment]
Can be refreshed via Ctrl+Shift+Alt+S
