### ISSUE TITLE
Restricted? accounts still have their scores appear on leaderboards

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu-stable-issues#430]
Some accounts still have their scores appear on leaderboards despite not 'existing'.

I know of two accounts, which this happens too, but there might be more.

The first account is from the user named God_old_1 (previously God, but this changed some time ago)
![screenshot080](https://user-images.githubusercontent.com/64087607/79877816-030ea280-83ed-11ea-8d19-99baf2d6452a.jpg) -Screenshot showing their score in game, nothing seems out of the ordinary.

When you go to the leaderboards of a map God_old_1 has a score on and hover over their profile it says: 'This user doesn't exist'
![p1](https://user-images.githubusercontent.com/64087607/79878084-4ec14c00-83ed-11ea-9bd7-658689a6a6d8.PNG)
If you try to go to their profiles you get the 'User not found' screen. 

The second account which has this issue is Jacqli
![screenshot081](https://user-images.githubusercontent.com/64087607/79878573-dd35cd80-83ed-11ea-82d8-4514cfd9ef96.jpg)
![p2](https://user-images.githubusercontent.com/64087607/79878497-c7280d00-83ed-11ea-83c2-dc5dd502fd88.PNG)
The same thing happens when checking the leaderboards on the website.

What is also quite interesting about this is that up until some time ago, the user in second place would get the first place on the map. Taking the map shown by Jacqli:
![image](https://user-images.githubusercontent.com/64087607/79879200-aad8a000-83ee-11ea-9498-63388a42ebe0.png)
![image](https://user-images.githubusercontent.com/64087607/79879237-b62bcb80-83ee-11ea-8c50-db3a71f19984.png)
Note that these are old screenshots (from june 2019) as this is currently not the case, as Darkpan does not have a first place on that map anymore (in his top plays).
![p3](https://user-images.githubusercontent.com/64087607/79880069-ce501a80-83ef-11ea-9378-a4eb62b2d9bf.PNG)
You can see he does not have a first place on that map anymore.

Personally, I think these accounts have been restricted incorrectly but I can only guess.
Some research on Jacqli gives the indication this used to be Shurelia's account as Jacqli is his ask fm name. 
Because of this, it might make some sense? that these accounts may also just have been incorrectly deleted, as I doubt a Global moderator, who also participated in CWC, would cheat. (this could be the case for the 'Jacqli' account assuming Shurelia used to play as Jacqli before and got a 'new' account when changing names or becoming GMT or something).

**Comment by peppy** [comment]
This should now be resolved (permanently). Thanks for pointing out!
