### ISSUE TITLE
(Taiko) Score v2 with unlimited FPS causing finishers to sound too loud

### ISSUE THREAD

**Issue by frukoyurdakul** [ppy/osu-stable-issues#431]
Basically, whenever I play a map with score v2 is on, the issue appears if I normally hit a finisher (I mean, with 2 keys as a normal player does).

If it helps, the issue has been going on for me at the time score v2 finisher scoring system was changed to its latest, which is about a year now I'd say, if not more.

I've recorded the replay and the loud ones were different from what I've played in the video but they still exist, so I can tell it is an issue in the gameplay itself, maybe even related to when a frame was rendered, even though the hit milliseconds were in the replay file. On the video, the heard hitsounds are original normal hitsounds for taiko, but the map itself has soft sampleset. I mean, I'm using "taiko-normal-hitnormal.wav" as "taiko-soft-hitnormal.wav" etc. in the skin. But I can tell it's not related to that as I've tested with a map that has normal sampleset, where the hitsounds are used by default and not customized.

I think it probably happens because the score is counted 4 times more as opposed to twice in score v1, because the issue doesn't happen on score v1.

Replay: https://streamable.com/7fx2er

My gameplay configuration:

![image](https://user-images.githubusercontent.com/33460209/79894129-ae2f5400-840d-11ea-8c94-4a308b910db1.png)
![image](https://user-images.githubusercontent.com/33460209/79894203-c7380500-840d-11ea-9aa2-9b35c003adff.png)

I also get about 2.5 ms input lag while playing which is about 500 fps, and my monitor is 60 Hz.

About the configuration: I've tried using "Optimal" for frame limiter while "Compatibility mode" is off, but it didn't solve the stutters so I'm using this configuration for the best experience for myself.

I'm using a laptop and my specs are these:

1) **Graphics card**: NVIDIA GeForce GTX 1050 (2 Gb) (of course I'm using this graphics card while playing the game)

2) **Graphics card (secondary)**: Intel(R) UHD Graphics 630

3) **Processor**: Intel(R) Core(TM) i7-8750H CPU @2.20GHz (12 CPUs), ~2.2GHz

4) **DirectX version**: DirectX 12

5) **OS version**: Windows 10 Pro 64 bit

6) **osu! version**: b20200421cuttingedge (latest version as of now)

If you need any more information, please let me know. Thanks.

**Comment by peppy** [comment]
Can you confirm this *only* happens with score v2? If so, it may be isolated enough that it's not worth fixing on stable (and only taken into consideration for lazer implementation).

**Comment by frukoyurdakul** [comment]
I can confirm, however, the reason why I opened the issue here is that, all tournaments use score v2 as its scoring system and every time I join one of those, this issue starts to appear. Since it is unexpected it can lead to score drops, or maybe some sort of jumpscares even. So, even if it happens on a future scoring system, it affects the stable version on all tournaments. Because of it, if this is an easy fix, please work on it.

Thanks.

**Comment by peppy** [comment]
Tournament use is a fair point. Will take a look into this.

**Comment by peppy** [comment]
@frukoyurdakul i've pushed a fix to cutting edge. could you please test it out?

**Comment by frukoyurdakul** [comment]
Sure, one second please.

**Comment by frukoyurdakul** [comment]
It seems like the issue has been fixed. I've tested on multiple maps including the one in the video, and didn't encounter loud finishers. Thanks.

**Comment by peppy** [comment]
Great to hear!
