### ISSUE TITLE
Song select filters don't work for keywords with spaces

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#433]
For example when using the `creator` filter to search for a mapper with spaces in their name like [P A N](https://osu.ppy.sh/users/1285234). When typing in `creator=P A N` the search only recognizes the "P" part of the request and interprets the rest of the characters as not part of the filter. 

Perhaps allow quotes to indicate characters part of the whole keyword like `creator="P A N"`, and if quotes are needed as part of the keyword, then escape them like so `\"test\"`.

**Comment by smoogipoo** [comment]
This is resolved in lazer, but the implementation is very different. We may be able to temporarily fix this on stable - seems like stable uses `string.Split(' ')` which could be changed to a bit more complex loop that only outputs on `(count of " % 2 == 0)`.

Quite some time investment is required.
