### ISSUE TITLE
Accuracy weighs 300 score same as 300 rainbow in osu!mania

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#440]
It's weird that score calculation weighs 300 with 300 hitvalue and 300 rainbow with 320 hit value, but acc doesn't reflect that. It would greatly benefit players to have 300 rainbow properly represented in accuracy display.

**Comment by peppy** [comment]
Are you implying changing all existing logic? This repo is for bug fixes to stable, not re-thinking the scoring system (that can be considered for lazer, so please post there instead).
