### ISSUE TITLE
osu!direct downloads give corrupt file until I empty my windows garbage can

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-stable-issues#442]
Not sure what's causing this, but it's usually on newly ranked beatmaps.
I recorded it with the newest ranked beatmap:
https://streamable.com/r437ip
I try to download and process it twice, and it says it's corrupt.
Then I delete a map to put in the trash can and immediately redownload the same map to show that it works on other maps.
Then at 1 minute I alt tab to Empty the windows Recycle Bin and try the newly ranked beatmap again.
This time it somehow works.

**Comment by peppy** [comment]
Maybe you have no disk space? This is out of scope of what we can fix here.

**Comment by GrilledCheeese** [comment]
Ah okay fair enough, I got 1.5 TB left tho, so it's not a disk space issue 
![image](https://user-images.githubusercontent.com/34809632/80584012-5c8c5800-8a11-11ea-94af-e67e38c74cbe.png)
I started with an empty recycle bin at the start of the video, I can download as many maps as I want, it's just the newly ranked ones give this error, in this particular circumstance
