### ISSUE TITLE
osu! can't process beatmaps with non-ASCII characters

### ISSUE THREAD

**Issue by TamamoNoMae13** [ppy/osu-stable-issues#445]
https://osu.ppy.sh/beatmapsets/965125#osu/2020385
This diff name is "†LEGGENDARIA".
osz file downloaded from the website/osu!direct give a "Tyrfing - Verflucht (Muya) [ü⌡LEGGENDARIA].osu" and osu! can't process it.

**Comment by peppy** [comment]
This is an issue with the beatmap itself and will need to be fixed via a reupload. @ephemeralis wanna look into this?

**Comment by peppy** [comment]
Not actually sure how this was ranked... do we even allow such characters in the difficulty name?
