### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#446]
![T@7801Q7Q1)7 CJ9C$7 HC](https://user-images.githubusercontent.com/34775378/80865077-7e0f6d00-8cb9-11ea-8983-ef2e9a03bf44.png)
[Logs.zip](https://github.com/ppy/osu-stable-issues/files/4567751/Logs.zip)
fps is suddenly drastically reduced

**Comment by cdwcgt** [comment]
This seems to be problematic for all modes

**Comment by peppy** [comment]
Your limiter is set to 480fps and you're getting 480fps.

If you're talking about the swapbuffer spikes, that's something else on your pc probably hooking the graphics context. reboot or fix (here's a guide: https://osu.ppy.sh/help/wiki/Performance_Troubleshooting)

**Comment by cdwcgt** [comment]
I check and I believe
it problem only in taiko mode
