### ISSUE TITLE
option to disable notification "beatmap difficulty is running in background"

### ISSUE THREAD

**Issue by Methosss** [ppy/osu-stable-issues#448]
**Describe the new feature:** 
option to disable notification "beatmap difficulty is running in background", i really hate notifications, i have 110K beatpamps+ and i got this notification always when play map, even this map is played by me many or maybe hundred times, every i open osu i got this message on every map, 
**Proposal designs of the feature:** 
osu -> options -> "show notifications when beatmap difficulty is running [enabled/disabled]"

**Comment by peppy** [comment]
This should not appear at any point apart from when you refresh all beatmaps. Is that what you're doing?

**Comment by Methosss** [comment]
how many times i should refresh all beatmaps?

**Comment by peppy** [comment]
You should never be refreshing them. If you are seeing this message, could you start by providing your log files?
