### ISSUE TITLE
Timeline cursor snaps 1ms before timing point position

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-stable-issues#451]
issue only applies to some maps

the exact ms value of a timing point cant be reached when scrolling in the timeline. using [this map](https://assets.ppy.sh/artists/36/osz/Creo%20-%20Gravitate.osz) as an example, the first red line is at 2085 but when scrolling, you can only reach 2084

when placing a green line on the first red line, it needs to be adjusted +1ms manually. an object on tick is also snapped to 2084 though, so a slider wouldn't have the green line's slider velocity multiplier applied. ![](https://i.imgur.com/WBoRdHR.png)

solution to this is manually moving the slider +1ms in the .osu to 2085, but clicking it in the timeline will move it back to 2084. it'd be easier to manage if it were able to be snapped as expected

this can also be tested on the first object of https://osu.ppy.sh/beatmapsets/234919#osu/544671

**Comment by qcl12345** [comment]
Is this the same as https://github.com/ppy/osu-stable-issues/issues/187 ?

**Comment by pishifat** [comment]
oh so it is
