### ISSUE TITLE
Osu Standard/Taiko/Catch Editor and Show Sample Name

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#452]
Shouldn't Show Sample Name show the sample name in the standard editor too?

Also in the taiko editor, it is hard to tell what is a big note and a normal note.

the show sample works only for mania which is cool, but in the standard-like editor, it doesn't even show what sample you are using anywhere if you are using custom samples.

**Comment by peppy** [comment]
lazer.
