### ISSUE TITLE
Editor beat snap divisor change

### ISSUE THREAD

**Issue by LordOfDesync** [ppy/osu-stable-issues#453]
Hi, i truly hope this isnt the wrong place

Could the beat snap divisor be changed so that when use ctrl + srcoll it changes from ex 1/4 to 1/3 instead of the current 1/4 to 1/2
It feels like this would be a very nice change considering every time you want to map a part in 1/3 you have to move the slider 
If this is the wrong place, im terribly sorry

**Comment by dorothy3242** [comment]
You could just use the existing shortcuts shift + 2, shift + 3, shift + 4 etc to change snapping to 1/2 , 1/3 , or 1/4 respectively. this already exists and is a lot faster than using the slider

**Comment by peppy** [comment]
1/3 is a less common usage, so it's intentionally done this way. using the aforementioned shortcuts is probably your best bet for now.
