### ISSUE TITLE
this map's md5 is listed as the empty file md5

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-stable-issues#454]
https://osu.ppy.sh/beatmapsets/93655#mania/252483 , the map's comments allude to why it is a problem.

just noticed when I was trying to get info from API about the osu files on data.ppy.sh, those empty ones I mentioned on discord were hitting https://osu.ppy.sh/api/get_beatmaps?h=d41d8cd98f00b204e9800998ecf8427e , which for some reason does return this map (the real md5 is different)

**Comment by peppy** [comment]
Fixed, and also blocked uploads from potentially gaining this md5 for safety.

**Comment by cl8n** [comment]
@peppy these maps also had different hashes in the .osu dump vs. online. were they updated after ranking or something like that?

```
1401607
1401608
1422575
1432899
1443309
1445743
1535572
1541641
1912711
2331141
2331919
2331920
2352261
2366660
275266
```

**Comment by peppy** [comment]
I've checked a few in that list and they look to have been changed in the mean time, yes. In each case I checked the osz content matches a fresh retrieval from web.
