### ISSUE TITLE
game crash on loading beatmap slider colors without combo colors

### ISSUE THREAD

**Issue by Karoo13** [ppy/osu-stable-issues#455]
adding just a slider border and/or just a track override will crash the game
```
[Colours]
SliderBorder : 1,2,3
SliderTrackOverride : 4,5,6
```

**Comment by peppy** [comment]
you probably got the format wrong?

**Comment by Karoo13** [comment]
you probably didn't test it with "ignore beatmap skins" off, it definitely crashes

**Comment by Karoo13** [comment]
https://puu.sh/FKs81/78afc31dd0.mp4
video proof

**Comment by Karoo13** [comment]
not sure if you see updates on closed issues, ill make a copy of this issue with more details
