### ISSUE TITLE
game crash on loading beatmap slider colors without combo colors

### ISSUE THREAD

**Issue by Karoo13** [ppy/osu-stable-issues#457]
video demonstration
https://puu.sh/FKs81/78afc31dd0.mp4
note that after removing combo colors, the sliders remain blue when loaded in editor, so this data is still being parsed correctly, but crashes when it tries to load the rest of the skin (after disabling ignore all beatmap skins). this applies to gameplay as well.

**Comment by Karoo13** [comment]
why is this closed? i checked cutting edge and it still happens

**Comment by smoogipoo** [comment]
Please at least check the version of cutting edge that you're on...
![image](https://user-images.githubusercontent.com/1329837/88253564-572b6a80-cced-11ea-8104-5f948788afa1.png)

Yes, it will be in the next release.
