### ISSUE TITLE
Fade to desktop is sometimes broken

### ISSUE THREAD

**Issue by GamerProYT54** [ppy/osu-stable-issues#463]
Sometimes, osu! fades to desktop, but sometimes it doesn't.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
