### ISSUE TITLE
[bug]can‘t upload beatmap, about "Maximun FileSize"

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#464]
look at the picture
![Image text](https://osu.wanjiaxg.com/cloud/20200530235204.png)
![Image text](https://osu.wanjiaxg.com/cloud/20200530235244.png)

**Comment by wanjiaXG** [comment]
if create a zip file, only 2.9mb
![Image Text](https://osu.wanjiaxg.com/cloud/20200530235751.png)

**Comment by wanjiaXG** [comment]
Maybe this is bug？ “Maximun Filesize” is not const value.
![Image Text](https://osu.wanjiaxg.com/cloud/20200531023919.png)

**Comment by cl8n** [comment]
the size limit depends on how long your map is. try putting a circle at the end of the song to make your map longer

from [wiki](https://osu.ppy.sh/help/wiki/Submission#limitations):
> The file size limit is 5MB plus an additional 10MB for every minute of beatmap length, and it caps at 100MB.
