### ISSUE TITLE
osu!taiko multiplayer scores being different by one point for no reason

### ISSUE THREAD

**Issue by Kasumiikun** [ppy/osu-stable-issues#466]
This is something I've been noticing in quite a few of my tournaments, mostly happened on several occasions during the qualifiers phase of my tournament this week however.
Some screenshots of it happening: 
![](https://i.imgur.com/FF0xAbN.png)
![](https://i.imgur.com/392XJzv.png) (No tie, but no one being able to get 1 million score, despite all of them being SS. (NoMod scores)
![](https://i.imgur.com/JPuFUKL.png) (Denied max score again.)
![](https://i.imgur.com/fRNjMMe.png)

These scores were the same in the actual in-game lobby as well, which is why I'm putting it out here, instead of the osu-web repository
Related MP links: https://osu.ppy.sh/mp/62300088
https://osu.ppy.sh/mp/62345668
https://osu.ppy.sh/mp/62290336
https://osu.ppy.sh/mp/62294374
https://osu.ppy.sh/mp/62328552
https://osu.ppy.sh/mp/62313470
https://osu.ppy.sh/mp/62287165
https://osu.ppy.sh/mp/62284252
https://osu.ppy.sh/mp/62331064
https://osu.ppy.sh/mp/62272741
https://osu.ppy.sh/mp/62317080

**Comment by smoogipoo** [comment]
Hmm seems like the score processors truncate. Maybe we can consider rounding instead (lazer already does this).

**Comment by peppy** [comment]
sounds good.

**Comment by Kasumiikun** [comment]
Is anything ever happening in regards to this?

It's still been happening in every taiko tournament nowadays so..

**Comment by peppy** [comment]
A fix for this will be in the next cutting edge release.
