### ISSUE TITLE
Star rating with Easy mod shows wrong values in api v1 

### ISSUE THREAD

**Issue by wesley-221** [ppy/osu-stable-issues#467]
I have done some testing and it seems like the star rating calculations aren't properly implemented in the api v1. Because of this a lot of maps (if not all) are giving a lot of pp compared to what they are supposed to give (at least, I think so)

Few examples, all with Easy mod enabled:
| | SRingame (correct? pp) | SR api v1 (Live pp) | 
|---|---|---|
| https://osu.ppy.sh/beatmapsets/1139396#fruits/2380004 | 2.54 (73.21 pp) | 4.21142 (201.5 pp) |
| https://osu.ppy.sh/beatmapsets/815097#fruits/1711543 | 3.84 (192.57 pp) | 4.41946 (255.14 pp) |
| https://osu.ppy.sh/beatmapsets/776495#fruits/1631468 | 3.43 (136.05 pp) | 3.95668 (181.09 pp) |
| https://osu.ppy.sh/beatmapsets/728864#fruits/1538689 | 4.13 (206.66pp pp) | 4.76364 (275.01 pp) |
| https://osu.ppy.sh/beatmapsets/286386#fruits/648330 | 5.31 (484.9pp) | 6.01296 (621.89pp) |
| https://osu.ppy.sh/beatmapsets/492407#fruits/1049018 (Converted map) | 5.79 (480.89 pp) | 5.88638 (496.93 pp) |
| https://osu.ppy.sh/beatmapsets/371569#fruits/826968 (Converted map) | 3.44 (164.98 pp) | 3.8622 (173.41 pp)|

The problem seems to be with just Easy as I've tried checking the values with Hardrock, Doubletime or Halftime enabled but those give the proper values.

**Comment by smoogipoo** [comment]
Turns out lazer is correct here, stable was actually bugged here.

I've pushed a fix and it'll probably appear on CuttingEdge very soon, but you'll have to re-import existing beatmaps to get the correct SR for EZ.
