### ISSUE TITLE
Star Difficulty of osu!catch is different from client and web at some maps

### ISSUE THREAD

**Issue by Molqus** [ppy/osu-stable-issues#470]
I realized that some maps (mostly recent ones) has two difficulty values between client and web.  
For example, this is the map which is ranked today:  
https://osu.ppy.sh/beatmapsets/1024220#fruits/2142452  
osu! web tells me the difficulty is 4.66, but client says it's 5.04.
![1](https://user-images.githubusercontent.com/66590819/84007528-88eda980-a9ab-11ea-9b14-2a3d238cf0fa.png)  
  
All recent maps also have this issue including specific maps. I'll show you random pending specific map:  
https://osu.ppy.sh/beatmapsets/1188304#fruits/2476281  
6.30 in web and 6.28 in client.
![2](https://user-images.githubusercontent.com/66590819/84008531-fa7a2780-a9ac-11ea-9d3b-f7004593d561.png)  
(but somehow the difference is very small)  

Also I found there are several old maps that have similar problem:  
https://osu.ppy.sh/beatmapsets/13169#fruits/51000  
2.27 in web and 4.15 in client.
![3](https://user-images.githubusercontent.com/66590819/84009632-86d91a00-a9ae-11ea-9d8b-2d28bdd0a98d.png)  

https://osu.ppy.sh/beatmapsets/22212#fruits/76717  
2.85 in web and 4.49 in client.
![4](https://user-images.githubusercontent.com/66590819/84009647-8c366480-a9ae-11ea-868d-8f049403815f.png)  

I don't know the details of pp calculation, but I think these two maps are having different problem from I showed at first (maybe about processing wiggles? idk).

This is the first time I open new issue, so if I mistake, please tell me and I'll fix my description.

**Comment by smoogipoo** [comment]
Perhaps related to https://github.com/ppy/osu-stable-issues/issues/432 .

Will keep open while investigating.

**Comment by smoogipoo** [comment]
Beatmaps 2-4: stable was applying stacking to non-osu! modes for the purpose of difficulty calculation only.

Beatmap 1: no idea yet. Lazer gives 5.05*, so something weird went wrong and we'll probably just have to recalc that one @peppy .

**Comment by WinterIsPretty** [comment]
This happens in mania as well and for some reason osu catch and mania both have weird star rating problems

**Comment by smoogipoo** [comment]
Mania is a separate issue altogether. Please make another issue and provide beatmaps.

**Comment by WinterIsPretty** [comment]
Look at issue 476 i believe this correlates with this issue

**Comment by peppy** [comment]
@smoogipoo i ran a reprocess on the first with no visible change. can you confirm the (lazer) diffcalc output of it is different on HEAD?

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/85500009-a5314d80-b61d-11ea-8285-d951c2dca8a2.png)

**Comment by peppy** [comment]
Very weird indeed... I'll try updating the server-side deploy just in case it's missing something.

**Comment by peppy** [comment]
The first map has been fixed. I think this issue can be closed @smoogipoo?

**Comment by smoogipoo** [comment]
Yep, all the others have previously been fixed.

**Comment by Molqus** [comment]
Confirmed fixing the stacking issue and the first beatmap. Thank you!  
But this problem occurs not only the first map that I gave as an example but also **ALL** recent ranked convert maps.  
So I think this issue shouldn't be closed. Or should I make another issue about this?

**Comment by smoogipoo** [comment]
Rest of the maps are being recalculated, please check back in a few days.

**Comment by Molqus** [comment]
I see. Will the fix also apply to future maps?

**Comment by smoogipoo** [comment]
Yes, all future maps will be fine.

**Comment by Molqus** [comment]
Okay. Thanks!
