### ISSUE TITLE
Note locking with relax mod

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#473]
With the relax mod, note locking shouldn't be a thing. It is extremely distracting.

Good examples such as when a jump happens across a note, it locks the note in the middle and throws me off, especially for multiple fast patterns like that.

I don't know if this is a thing for laser but I've been thinking about this since mcosu doesn't have that problem.

I'm pretty sure it should only note lock for notes that are too late to hit not too early

**Comment by peppy** [comment]
have you tested lazer?

**Comment by WinterIsPretty** [comment]
lazer can't load all my maps it crashes whenever I open it up again

**Comment by peppy** [comment]
Could you just test any beatmap? Or download the specific one you're investigating via osu!direct?

**Comment by WinterIsPretty** [comment]
ok I will redownload lazer and see if this note locking effect is on there, there is this one map heavily with these patterns so I'll check it out

**Comment by WinterIsPretty** [comment]
I can't play osu lazer I have no cursor... what

**Comment by peppy** [comment]
ctrl-shift-alt-r will reset your input settings and hopefully resolve any weird settings you had set.

**Comment by WinterIsPretty** [comment]
I use the most default settings I can use, but none of the skins I have support the cursor skin

**Comment by WinterIsPretty** [comment]
wait no I jsut can't see my cursor what
I did the ctrl shift alt r

**Comment by WinterIsPretty** [comment]
the normal cursor that is supposed to display in the menu doesn't work but the skin cursor works when I play a map

**Comment by WinterIsPretty** [comment]
also I have 2 different osu files, one for private servers and one for normal osu, how can I get my skins to lazer from those folders? and song files

**Comment by WinterIsPretty** [comment]
reinstalling lazer did nothing I still have no cursor, and idk where it is pulling any of my skins from I have nothing where osu normally installs

**Comment by WinterIsPretty** [comment]
well I know there is no visual note locking in lazer with relax

**Comment by peppy** [comment]
thanks for the confirmation.

due to the way stable works, this is a non-trivial change so i don't believe we will be fixing it.
