### ISSUE TITLE
Old scores on the 'classic' TAG maps still give PP in catch, taiko and mania

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu-stable-issues#474]
I think the title explains the issue.

At the end of 2016 the 'classic' TAG maps got moved to the loved category.
This is a list of the maps that got moved (as far as I am aware).
https://osu.ppy.sh/beatmapsets/5774#osu/27737
https://osu.ppy.sh/beatmapsets/4651#osu/24722
https://osu.ppy.sh/beatmapsets/25739#osu/87570
https://osu.ppy.sh/beatmapsets/6593#osu/29844
https://osu.ppy.sh/beatmapsets/7385#osu/35015
https://osu.ppy.sh/beatmapsets/5807#osu/27638
https://osu.ppy.sh/beatmapsets/15920#osu/58064
https://osu.ppy.sh/beatmapsets/12563#osu/48874

As you can see on the leaderboards of the Utage wa eien ni TAG4 map in CTB,
![tag utage](https://user-images.githubusercontent.com/64087607/84263481-d854e680-ab1f-11ea-875e-5fa920a4c8e8.PNG)
Old scores are still worth quite a significant amount of PP.
You can see that ExGon's 1 miss HR score is worth 680PP, yet Motion's 8 miss HR score is worth nothing, since it was set more recently.
I find that this is really unfair to Motion as well as other players who have set good scores on these maps after these maps got loved.

Personally, I see two ways to fix this.

The easier? and perhaps more logical way is to recalculate the old scores aswell, making them worth 0PP and thus cementing the loved status of these maps.

The other way to fix this issue, which I would prefer, is to make these 8 TAG maps award PP in catch, taiko and mania (again). 
My reasoning for this is that in catch, these maps are pretty playable and a lot of fun. They also aren't super-overweighted or much different from recently ranked converts anyways.
The TAG maps are also still a really nice challenge to catch players and I would love to see them reward PP again, as this would allow top-players to get some cool scores on them.
I don't know much about playability/overweightedness in taiko/mania, but as far as I can tell there shouldn't be any issues in these modes.

Of course there is also the option of moving the TAG maps fully back to the approved section for all modes, but I can see why this might be an issue in standard even though I think getting PP from a good score on these maps would be really cool.

If the option to 're-approve' the catch/taiko/mania converts of this map is chosen you could also choose to make it so the standard scores award 0PP by default, such as was the case on https://osu.ppy.sh/beatmapsets/1028115#osu/2149792 in catch, since the big stacks made this map worth 1.5k+PP with HTHR. Choosing for something similar to this would also allow to re-approve the TAG maps, without 'breaking' the current PP system in standard.

**Comment by peppy** [comment]
I've resolved this one, checking all loved maps and removing all pp scores. Please confirm it looks okay.

**Comment by KevKjef** [comment]
Similar to https://github.com/ppy/osu-stable-issues/issues/480, scores are still shown as 0pp in top plays.
![exgontag](https://user-images.githubusercontent.com/64087607/85559026-9ea8d300-b629-11ea-8ff6-f68d3f3e4908.PNG)
this can be seen in ExGon's top plays, for example.
The same thing happened on the other map, so I think doing the same which fixed the other map, would fix these scores from appearing.

**Comment by peppy** [comment]
that will eventually be resolved as indices refresh. no hurry.
