### ISSUE TITLE
soft-hitnormal sample is often inaudible over music

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#475]
The soft-hitnormal sample often provides inadequate feedback due to being too soft. As a hitsound sample, its purpose should be to reinforce when the player clicked the sound, but it tends to blend in with many types of music. As a result, it's been the cause of heated debates in the threads of qualified beatmaps:

- https://osu.ppy.sh/beatmapsets/1182518
- https://osu.ppy.sh/beatmapsets/897884

Please consider changing it to something that's a bit more tactile and more likely to be audible over songs, similar to the little click sound that other rhythm games have.

**Comment by peppy** [comment]
Have you checked whether this is fixed by the current lazer default?

Also have you considered using a skin?

**Comment by iptq** [comment]
> Have you checked whether this is fixed by the current lazer default?

The lazer default skin uses a better hitnormal, but this is regarding the current default client and skin as most newer players who will be playing osu will be using this combination.

> Also have you considered using a skin?

The concern over the default skin is because most of the mappers involved in the threads are under the assumption that the ranking criteria's hitsounding guidelines are about default skin (since it wouldn't make sense for the ranking criteria to make an assumption about which skin a player is using).

If this shouldn't be the case then the ranking criteria should be updated to say that no assumptions about the skin should be made and that if default skin's samples are inaudible then it's advised to change to a different skin.

**Comment by peppy** [comment]
If the default skin is inaudible, it sounds like the issue may be an audio volume normalisation one (ie. the music track being too loud). That's something we haven't addressed anywhere yet, but something we likely will in lazer via replaygain or similar.

I can say for sure that we won't be changing the default osu-stable skin as it is locked in place for history (we don't want to break existing beatmaps etc.). But lazer is an open canvas for such changes.

As such I'm going to close this issue for now. I think maybe if soft is not audible during a "soft" section of the song then all is fine. If people are using soft during loud sections and getting told that's not acceptable, maybe the soft sampleset is not appropriate for that section.

**Comment by WinterIsPretty** [comment]
;-;
