### ISSUE TITLE
Star rating increases when notes are placed further from the beginning [catch and mania]

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#476]
When you make a map with the song starting near the beginning, the map is a lower star rating than if you had a long pause in the beginning before the song started

You can see the if you exaggerate it by doing like 5 or 10 minutes before the song starts but this shows me that it must happen at minor instances

**from experimenting this only happens with mania and catch**

----
Mania screenshots first exaggerated last is realistic:

[Before](https://cdn.discordapp.com/attachments/463638143422169088/720765639165214770/screenshot082.jpg)
[After](https://cdn.discordapp.com/attachments/463638143422169088/720765650926043136/screenshot083.jpg) bpm is zero but the notes are the exact same

[Before](https://cdn.discordapp.com/attachments/463638143422169088/720765664008208454/screenshot084.jpg)
[After](https://cdn.discordapp.com/attachments/463638143422169088/720765673839657021/screenshot085.jpg)

----
Catch Screenshots:

[Before](https://cdn.discordapp.com/attachments/463638143422169088/720769554292277308/screenshot092.jpg)
[After](https://cdn.discordapp.com/attachments/463638143422169088/720769563574140928/screenshot093.jpg)

**Comment by WinterIsPretty** [comment]
Now that I think about it, sometimes it doesn't increase but it changes, why is the star rating different though if it has the same note but starting at a different time

**Comment by smoogipoo** [comment]
This is dependent on how notes align to strain sections. It happens for all modes and we're aware of it but don't yet have a solution.

We'll probably find a way to fix it in lazer which will eventually trickle back to stable, but is not an immediate priority for us. Feel free to make an issue there.
