### ISSUE TITLE
Star rating of Acid Rain - Aspire (convert) is broken/incorrect in catch

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu-stable-issues#480]
The map Acid Rain (https://osu.ppy.sh/beatmapsets/980599#fruits/2052199) currently awards way too much PP, since the SR is incorrect on the website. The website says this difficulty is 6.58* while the game thinks it is 3.72*
![acidrain](https://user-images.githubusercontent.com/64087607/84574176-05fe9180-ada5-11ea-9d06-a90b0cef8b0a.PNG)
![screenshot131](https://user-images.githubusercontent.com/64087607/84573939-d438fb00-ada3-11ea-8f18-e604e02d3c17.jpg)
I don't know why the site thinks this map is 6.58* but this might be related to #470 
While this map isn't easily fc'able due to the pattern at the beginning (this is the reason why everyone misses there) it is really easy to get 1k/1.3k combo and get an easy 400-500 PP score, since the SR from the website is taken to calculate the PP (as far as I can tell). Besides the precise jump the map is basically just notes stacked on top of each other, which could explain the higher SR, but not the difference on web/in-game SR. 
Either way, if the notes stacked on top of each other (as in at the same time of the map) are the reason for this inflated SR something should be changed, as these are really easy to catch, resulting in literal 'free' PP

**Comment by smoogipoo** [comment]
Thanks. This beatmap should be moved to loved.

**Comment by KevKjef** [comment]
I see the map already got moved to 'loved'. 
Some players' scores on this still award PP though, e.g. https://osu.ppy.sh/users/8417087 and https://osu.ppy.sh/users/2754651 (FruktoLove and Byeol) 
![acidrainppinc](https://user-images.githubusercontent.com/64087607/84588233-f1aea900-ae25-11ea-825c-8bb132e3e83a.PNG)
Players' who had a score on this yesterday (before it got 'loved)' still have the play in their to plays though.
![subclassacidraintopplay](https://user-images.githubusercontent.com/64087607/84588237-f5423000-ae25-11ea-9528-d5b53a74c226.PNG)
As you can see in the picture above it is counted as 0pp, but it is still among the other plays.
*Note: this is not the case on the old site, presumably due to it handling top plays differently?

**Comment by smoogipoo** [comment]
Has now been fixed.

**Comment by KevKjef** [comment]
The scores are still among top plays and as far as I can tell, PP gained from them hasn't been reset yet

**Comment by smoogipoo** [comment]
We're working on it. Will post back for confirmation once everything's been fixed.

**Comment by smoogipoo** [comment]
Looks to be fixed now, please confirm!

**Comment by KevKjef** [comment]
The scores are now no longer present in top plays,
However, the PP gained seems to still exist.
this can be seen on SadEgg's and Sub Class' profiles (https://osu.ppy.sh/users/10278243 & https://osu.ppy.sh/users/1417202) for example.
They gained a lot of a ranks 15/5 days ago, which is when they got their 400+ PP score on this but they have no visibble rank decay.
I'm also pretty sure Sub Class had 7.5k PP two days ago, which is just after he got his 480ish PP score on this, yet he didn't lose any.

**Comment by peppy** [comment]
pp will be fixed next score submission.
