### ISSUE TITLE
Auto mods score reset when changing skin

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu-stable-issues#484]
How to replicating this issue:
1. Play osu!mania with Auto Mod enabled
2. Play any song
3. Change skin using Ctrl + O
4. Change to other skin
5. Score and combo resetted.

Video to proof : https://www.youtube.com/watch?v=6PdtdkkTMrQ

**Comment by HerendraTJ** [comment]
Normally the score shouldn't be resetted and the score either being paused until the skin changed or the score keep climbing while the song is played.

**Comment by peppy** [comment]
I'm not sure we have the spare bandwidth to (ever) fix this. It works correctly on lazer though. Can you confirm this *only* happens on osu!mania?

**Comment by HerendraTJ** [comment]
@peppy Oh, pardon me for not checking in every game modes. It happened in all game modes with the same method.

**Comment by peppy** [comment]
I'm not sure this is something we can fix. One option we have is to just restart the beatmap from the start when a skin change is triggered, does this sound better to you?

**Comment by smoogipoo** [comment]
I don't think this is important enough to fix for the amount of effort required. Going to call this one out of scope and fixed in lazer.
