### ISSUE TITLE
logs for map which osu calculating for a while time

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-stable-issues#487]
This is needed in order to find and remove problematic maps.

problem: Map recalculation process is not going
want: logs of this maps

video: https://mega.nz/file/IR1klaiL#tiw3E1g5F2GNFgebLDk8xhD1XrHq0O5WYFxs9CqFH00

**Comment by smoogipoo** [comment]
I believe there should already be a log of the form `({BeatmapId}) difficlty calculation started` in your `runtime.log`.

(Also whoops spelling mistake)

**Comment by peppy** [comment]
@cyperdark have you checked the mentioned logs?

**Comment by cyperdark** [comment]
yes, and i fix my problem
