### ISSUE TITLE
"key=x" doesnt filter mania only maps

### ISSUE THREAD

**Issue by InitialDet** [ppy/osu-stable-issues#488]
https://osu.ppy.sh/community/forums/topics/1093176
The filter "key=4" is showing every osu!std easy/normal map, without the gamemode being set to "osu!mania" to convert then.

![image](https://i.ppy.sh/a469ab5b77af5a7dddb1165e36a0203da844b48b/68747470733a2f2f6f73752e7070792e73682f73732f31353131323238332f33323037)

**Comment by WinterIsPretty** [comment]
It's so you can search for converts via a key count, and mode=m does mania only

**Comment by InitialDet** [comment]
But why show every std map if they are NOT converted? of the 10k results I got, 8k of then were std difficulties. 

At least they should appear only when osu!mania is selected
![image](https://i.imgur.com/1A5Yjbw.png)

**Comment by peppy** [comment]
I don't understand. You expect non-converts to be hidden when looking up a key count while in osu! mode? This sounds completely wrong.

This is already fixed in lazer by allowing hiding converts via a toggle.

**Comment by InitialDet** [comment]
I mean... thats how it was up until recent updates. if I typed "key=4" it would only bring difficulties that have 4 keys. But now it brings every easy/normal osu!std maps for some reason.

![image](https://user-images.githubusercontent.com/13919114/85347623-7b6a1080-b4cf-11ea-86f5-a96c949aa44b.png)

**Comment by peppy** [comment]
please add mode=mania to your search for what you're looking for.

**Comment by InitialDet** [comment]
That really makes me sad. It always worked like that for years. 
If I'm looking for maps with 4 keys, why does it bring non-mania difficulties now?

I know that it works with the mode=mania, but that was the default for so long... was it an intentional change?

**Comment by peppy** [comment]
Yes, it was an intentional change and actually makes more sense than what you are implying it used to be.

**Comment by InitialDet** [comment]
I see, at least it is was not a bug with my client. Its a weird change for me, but it must have a reason for it.

Would at least be possible to have an alternative filter? maybe something like "mkey=4" or "key=4m" to make mode=mania short or something. 

Thanks for the attention, Peppy. Good luck on lazer.

**Comment by peppy** [comment]
filter should be stored until you exit the game, so i don't think typing it is such a huge deal.

**Comment by InitialDet** [comment]
It's not a big problem, its more like a muscle memory command since I swap a lot between std and mania. But that's something I have to get used to.

But a short filter would be a lovely QoL change.

**Comment by WinterIsPretty** [comment]
It isnt random osu maps that are easy and normal diff btw it's all the standard maps that convert to 4 keys, but with the standard mode it just doesn't show the key count, also with the taiko mod and catch mod you can search key count but it will only show standard converts, kinda weird but isn't a huge problem. It doesnt create any issues like it did before

**Comment by InitialDet** [comment]
The main reason I made this topic made this issue was the fact that osu!std difficulties where being showed even tho they aren't converted when looking for mania maps with x keys. I wasn't aware of this change.

I honestly think that the converteds should be the ones to need an extra command to be filtered (like key=4 mode=all) since their quality is too inconsistent. It buries all good originals mania maps in a sea of converted beatmaps by default.

Or like I said, std difficulties could be at least be shown when the gamemode is set to osu!mania, because NOW they are actually converted and playable as mania.
![image](https://camo.githubusercontent.com/4b7cdaf2bc514add8762f71255a793dcb5429452/68747470733a2f2f692e696d6775722e636f6d2f314135596a62772e706e67)

Its more like a QoL change now then an issue.
