### ISSUE TITLE
Can't Find Intel ICD OpenGL Driver Error

### ISSUE THREAD

**Issue by Kirinagi** [ppy/osu-stable-issues#489]
So recently all the drivers in my laptop got automatically updated and i got this Intel OpenGL Driver problem and i can't open osu!, i found some temporary solutions and that is to use intergrated graphics instead of the nvidia graphics that i usually use for osu!, or disabling compatibility mod but those options really degrades the performance and it gives a really noticeable input lag. i tried switching to cutting edge and it's still doesn't work.
![image](https://user-images.githubusercontent.com/67285952/85318028-85990880-b4e9-11ea-98b5-e93b5a39be8d.png)
![image](https://user-images.githubusercontent.com/67285952/85318685-9eee8480-b4ea-11ea-8a63-c177e558b3af.png)

I don't know a proper solution for this and it's pretty much effecting osu! only, for now i'll try playing with intergrated graphics until this gets fixed or until i found another solution that works for me

**Comment by peppy** [comment]
Please see https://github.com/ppy/osu/issues/9298
