### ISSUE TITLE
Have a separate "ignore beatmap skins" for the editor only

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#49]
I tend to ignore beatmap skins while i play but not when i map. Since i map regularly, i end up toggling this button on and off a lot.

Side note: a better solution would probably be "profiles" where u toggle multiple settings together but that seems like a lazer thing

**Comment by peppy** [comment]
Adding a new setting for this seems pretty low overhead

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
