### ISSUE TITLE
osu!catch EZ mod star rating calculation completely broken

### ISSUE THREAD

**Issue by TTGL1618** [ppy/osu-stable-issues#490]
EZ mod calculation is completely broken, on many maps it only lowers the star rating by a very small amount or even buffs in some cases, and this isn't a rare occurence, within 10 minutes of searching I found up to 25 maps that have this issue, and the fact that they reward pp is worrying since it inflates the leaderboards. This affects both standard maps as well as catch maps. Here are some examples:

Two standard maps

![screenshot133](https://user-images.githubusercontent.com/55665413/85462275-34e2e780-b59d-11ea-90f8-9a0481f1b4a9.jpg)

![screenshot134](https://user-images.githubusercontent.com/55665413/85462353-488e4e00-b59d-11ea-8d6e-30b64e96491e.jpg)

![screenshot137](https://user-images.githubusercontent.com/55665413/85462363-4c21d500-b59d-11ea-88a5-4487c33aad64.jpg)

![screenshot138](https://user-images.githubusercontent.com/55665413/85462376-4f1cc580-b59d-11ea-8301-8ee3e74b83fc.jpg)

Two catch maps

![screenshot139](https://user-images.githubusercontent.com/55665413/85462453-63f95900-b59d-11ea-886c-f368e7848f10.jpg)

![screenshot140](https://user-images.githubusercontent.com/55665413/85462464-678ce000-b59d-11ea-9bce-e5521904d731.jpg)

![screenshot141](https://user-images.githubusercontent.com/55665413/85462474-6956a380-b59d-11ea-9a9c-acae124c470e.jpg)

![screenshot142](https://user-images.githubusercontent.com/55665413/85462482-6bb8fd80-b59d-11ea-85de-440a03e0c7d9.jpg)

**Comment by smoogipoo** [comment]
This has already been resolved, you will need to re-import the beatmaps to have the SR update.

**Comment by TTGL1618** [comment]
Sorry for the late reply but this is with the SR update, the day I made this post I had re-imported all my maps and updated them.

This isn't just a visual bug it affects the PP you get from the map too, a DT fc on Krfawy - Kac is worth 123pp while an EZDT fc is 280pp which is completely broken.

**Comment by peppy** [comment]
awarded pp will be renormalised at some point. if there are heavy outliers that you think should be addressed immediately, please list the beatmap links.

**Comment by TTGL1618** [comment]
That's good to hear, there's honestly too many of these to link all of them but Platter diffs seem to be the most broken so I'll link a bunch of them.

https://osu.ppy.sh/beatmapsets/1119839#fruits/2358763
https://osu.ppy.sh/beatmapsets/472434#fruits/1009515
https://osu.ppy.sh/beatmapsets/1139396#fruits/2380004
https://osu.ppy.sh/beatmapsets/273355#fruits/652111
https://osu.ppy.sh/beatmapsets/865565#fruits/1870417
https://osu.ppy.sh/beatmapsets/943803#fruits/1971060
https://osu.ppy.sh/beatmapsets/872723#fruits/1826388
https://osu.ppy.sh/beatmapsets/972764#fruits/2043177
https://osu.ppy.sh/beatmapsets/584575#fruits/1287353
https://osu.ppy.sh/beatmapsets/749557#fruits/1602435

This is just some of the worse offenders I've found so far but there are still many more lower star maps that get buffed by around a full star, there's honestly too many for me to link them all it's pretty bad lol
