### ISSUE TITLE
When switching audio output during play with HT, song goes down in pitch

### ISSUE THREAD

**Issue by imaginative12** [ppy/osu-stable-issues#492]
This happened while I was switching from a bluetooth connected speaker (lol) to my computer's speaker, and I noticed that the song went down a few keys/didn't correct for the song slowing down.
I tried it in spectator but osu! doesn't recognize changes in output when spectating unless you exit it.

**Comment by smoogipoo** [comment]
This isn't a common use case and as such is out of scope for the issues we want to fix here.
