### ISSUE TITLE
Lower fps Without compatibility mode on RTX 2070 max q ( laptop )

### ISSUE THREAD

**Issue by MavisTail** [ppy/osu-stable-issues#494]
issue: osu has very low fps on a high end laptop
specs:
intel 10th gen 10750H,  32GB RAM 2666hz,  RTX 2070SUPER max q,  300hz monitor,  500GB ssd.
I get about 500fps which is not normal
Things I have tried: running osu on intel integrated graphics (got 250 fps)
running the game at full screen while my tablet is plugged in, makes it become 60fps, without FS it goes to 500
having compatibility mode turned on, makes my fps goes up to 900

my other laptop with lower specs and a 1050Ti GPU has 500fps 

tablet I use: a graphical tablet; XP pen artist pro 15.6

**Comment by peppy** [comment]
Thanks for your feedback. We can't service individual user hardware / performance requests. If you'd like to look into performance further, here's a guide to help you out: https://osu.ppy.sh/help/wiki/Performance_Troubleshooting
