### ISSUE TITLE
In rare cases ipc-channel.txt doesn't get written to in cutting edge

### ISSUE THREAD

**Issue by MiraiSubject** [ppy/osu-stable-issues#495]
I don't have a reliable way of reproducing this and it's been very random so far. 

When joining a lobby using the tournament client `ipc-channel.txt` does not get written to and then lazer does not know which chat channel to join.

The chat shows in cutting edge, but lazer shows the DMs of the logged in user or nothing at all. At the same time it shows that the `ipc-channel.txt` was either not written to or non-existant at all. 

Deleting all the ipc-related files and remaking new empty ones for them does not work. 
Deleting all the ipc-related files and only remaking the `ipc.txt` files regenerates all the files except `ipc-channel.txt` even when joining a lobby.

**Comment by peppy** [comment]
Can you confirm that when it starts to fail, switching lobbies any number of times does not recover?

**Comment by MiraiSubject** [comment]
Just tested this out and it does recover when you switch between lobbies. It seems like it only fails to write on the first join. 

Tested scenarios:
Client startup done -> click on lobby 1: fails
Client startup done -> click on lobby 1 (fails) -> click on lobby 2  (succeeds) -> click on lobby 1 (succeeds now as well)

**Comment by peppy** [comment]
Can you confirm it happens with only one click on one lobby? Just want to rule out the possibility that you are quickly clicking two lobbies or something when this occurs (since that looks like it could be a potential fail case).

When it happens, do you see the "Match history available" chat from BanchoBot (in the cutting-dge client)?

**Comment by MiraiSubject** [comment]
> Can you confirm it happens with only one click on one lobby? 
Yeah, I made sure to only click once and wait for the client to react to the change of lobby before doing any other actions. 

In all cases I observe "Match history available" whether it's failing or succeeding. 

https://www.twitch.tv/videos/670706500?t=00h08m47s this video shows that the chat does show in CE, but lazer in the background reads from #osu

**Comment by peppy** [comment]
Can't repro locally.

I've added more logging in the latest cutting-edge. Please reproduce and check runtime.log for any errors.

**Comment by MiraiSubject** [comment]
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4880854/runtime.log)

I don't see anything in particular standing out from it. This was a session where I was able to reproduce it. 

I also had sessions during testing using the same steps where it just worked first try.

**Comment by peppy** [comment]
I've pushed out another build with even more logging. Please try once more.

**Comment by MiraiSubject** [comment]
After my observations this time around I can conclude that it's not stable, but lazer. 

After further inspection this time on the lazer side, I logged in a local checkout what happened there with the rooms: 

(Make sure lazer is closed first)
1. Connect to a lobby in CE tourney, observe ipc-channel being written to
2. Boot up lazer tournament and observe the API errors Forbidden and Not Found

Switching to a second lobby and then back to the first one makes the chat show as normal again. 

These are the errors that show up: 
![Code_2020-07-07_22-21-07](https://user-images.githubusercontent.com/803255/86839062-3c2bea00-c0a1-11ea-8769-4cb89694118a.png)

The `Logger.Log($"Chat room is changing... {c.newValue}");` runs inside `chatChannel.BindValueChanged` to observe when it changes. 

This looks like a race condition because it tries to connect to the lobby _before_ authentication completes. This also becomes apparent after observing that on bootup sometimes only Forbidden gets thrown, but the room does get found. (but it won't display)

Sorry for wasting so much time by poking around on the stable side. This one can be closed/moved to the lazer repo.

**Comment by peppy** [comment]
what was the deal with the file not being written then?

**Comment by MiraiSubject** [comment]
> what was the deal with the file not being written then?
 
Oh yeah I forgot about that in the midst of the whole lobby situation. I just tried to reproduce it but I can't any more.

I tried the failing scenarios that I described here in the issue and now they all succeed.

**Comment by peppy** [comment]
Could you please provide your lazer log file rather than a screenshot of it? Please also include the follow-up successful requests.
