### ISSUE TITLE
Approach circle under hitobjects for first two objects in map (in rare cases)

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#497]
This very rarely happens but if it does happen in a map, it will consistently happen every time.
https://osu.ppy.sh/beatmapsets/863319 on the Easy, Normal, Advanced, Insane difficulties, you can see approach circles for (2) are rendered underneath (1) objects instead of above.
![image](https://user-images.githubusercontent.com/33286824/86701567-230f3480-bfe0-11ea-8633-3f543fe51848.png)
![image](https://user-images.githubusercontent.com/33286824/86701585-273b5200-bfe0-11ea-8902-3e62a847a9da.png)
![image](https://user-images.githubusercontent.com/33286824/86701620-2dc9c980-bfe0-11ea-92a8-68d3c582f399.png)

The same also currently occurs on this mapset, https://osu.ppy.sh/beatmapsets/1165972 on just the Easy and Normal difficulties.
![image](https://user-images.githubusercontent.com/33286824/86708484-f9a5d700-bfe6-11ea-8f88-85ecdda57153.png)
![image](https://user-images.githubusercontent.com/33286824/86708509-ff9bb800-bfe6-11ea-937f-e614f40b460e.png)

In both cases this only occurs with the 2nd object's approach circle going under the 1st object's hit circle. Besides that the maps are normal. I'm not sure what causes the issue, as the only common point that I can tell between both maps is the objects are early timestamps, and it happens with the first two objects in particular.

It can obfuscate the approach circle a bit particularly in the easy difficulties where hitcircles are quite large, so it'd be nice for this to be checked out. However it's not gamebreaking, just a bit "off". Hopefully this bug would be an easy fix (???)

**Comment by smoogipoo** [comment]
Should be fixed in the next cutting edge.
