### ISSUE TITLE
banchobot thinks game already started when use !mp start 0

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-stable-issues#498]
![i](https://user-images.githubusercontent.com/13962537/86806402-42ff3080-c092-11ea-9192-bbf3819d9c9d.png)
even after playing beatmap he still thinks so

EDIT: Also Ready button doesn't work after.
EDIT2: Also, after this host wont receive other's messages (even banchobot's)

**Comment by peppy** [comment]
Will be fixed in the next bancho update.
