### ISSUE TITLE
Significant performance issues in the editor for osu!mania beatmaps

### ISSUE THREAD

**Issue by AlFasGD** [ppy/osu-stable-issues#499]
Forwarded issue from [here](https://osu.ppy.sh/community/forums/topics/1103363):

Opening an osu!mania beatmap to edit will cause the editor to have performance issues, with severity depending on the number of notes that are currently visible that also have a sample name on top of them, while also regarding the sample name's length.

[Screenshots](https://imgur.com/a/8EunfVz)

Notice the FPS counters on the bottom right of the screen. All screenshots were taken within a small time interval within the same environment, the same running processes and after some time for the FPS counter to stabilize itself.

The screenshots were taken on [this beatmap](https://osu.ppy.sh/b/1038662)

osu! version: Stable 20200704 (latest)

**Comment by peppy** [comment]
Thanks for the report!

The numbers you quote still seem within usable spec. If you find the fluctuating frame rate to be an issue, I'd suggest limiting to 60fps for the time being.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. We are making sure to make all gameplay and editor screens in lazer highly performant, so this shouldn't be an issue [osu!lazer](https://github.com/ppy/osu).
