### ISSUE TITLE
Crash on song exit

### ISSUE THREAD

**Issue by mikumikuyo** [ppy/osu-stable-issues#5]
How to replicate:
I'm actually not sure, seems to happen randomly

Bug: after finishing a song, pressing escape before the ranking panel crashes my game, on restart, the map(set) i played is no longer in song select and i have to reprocess all my maps. When it happens once its guaranteed to happen at least a couple more times until it stops for apparently no reason either.

Osu stable 
24 gigs of ram
gtx 1080
intel i5

**Comment by peppy** [comment]
Please click the pippi on the crash dialog and include the call stack (reopen the issue if you manage to capture this).
