### ISSUE TITLE
Add a beatmap search criteria "mapper=xxx"

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#50]
There's things like star= or od=, why not add a mapper= or creator= field as well? I know there's sort by already but this doesn't seem too hard to add anyway

**Comment by MillhioreF** [comment]
This sounds redundant to me since you can just search the mapper's name directly, and would only be useful in an extremely limited amount of cases.

**Comment by iptq** [comment]
searching the mappers name brings up guest diffs because of tags, i use this more than u would probably expect. if its too much of a hassle then forget about it

**Comment by smoogipoo** [comment]
I've made it `creator=` and `artist=`, but it'll be in the next release.
