### ISSUE TITLE
opening aimod twice in one session crashes the game on some maps

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-stable-issues#501]
steps I can do to reproduce

- open any diff of https://osu.ppy.sh/beatmapsets/605907
- open and close aimod
- open aimod again
- game stops responding, eventually grays out and has report issue to microsoft popup

[runtime.log](https://github.com/ppy/osu-stable-issues/files/4929688/runtime.log)
06:21:10 is when I opened aimod the first time, and 06:21:22 the second

the map's creator said they have the same problem

**Comment by peppy** [comment]
Fixed in next release!
