### ISSUE TITLE
Make Sudden Death immediately restart the beatmap just like Perfect does.

### ISSUE THREAD

**Issue by ryancsh** [ppy/osu-stable-issues#503]
Sudden Death doesn't immediately restart the game whereas Perfect does.
This makes the game feel inconsistent and I believe it would be better if Sudden Death automatically restarted the beatmap.

From what I gathered, this change has already been implemented and simply needs to be applied to stable osu.
https://github.com/ppy/osu/issues/9615

**Comment by peppy** [comment]
Thanks for the request, but stable is feature locked and we are not looking to apply such changes (as lazer will eventually replace stable).
