### ISSUE TITLE
Qualified map can be marked as pending when 'submit' button is clicked after qualification

### ISSUE THREAD

**Issue by Darius-Wattimena** [ppy/osu-stable-issues#506]
The following beatmap [765 MILLION ALLSTARS - UNION!!](https://osu.ppy.sh/beatmapsets/1205919/discussion) was moved to qualified a couple hours ago. After the map was qualified by the beatmap nominators it shortly moved itself to pending for no reason. 

This created multiple bugs:
- On the website the map could be found in the [following list](https://osu.ppy.sh/beatmapsets?s=qualified) although showing as Pending in the top left corner of the card
- No leaderboard in-game and on the website

Not sure if the issue can be reproduced but the following steps happened:
- Mapper updates the map while leaving the 'Upload Beatmap' popup open
- BN's nominated the map
- Map moved to qualified
- Mapper presses the 'submit' button in the popup
- Map moved back to pending

**Comment by peppy** [comment]
Thanks for pointing this out. It has now been fixed. It should be fine to re-qualify the beatmap in question.
