### ISSUE TITLE
Unable to change map status from WIP to Pending

### ISSUE THREAD

**Issue by Genjurowo** [ppy/osu-stable-issues#507]
Updating the map via BSS updates everything except the map status (wip/pending) and the description. Here's a map where I have this issue: https://osu.ppy.sh/beatmapsets/1230649#taiko/2558487 The first time I submitted the map I choose Pending but it was still uploaded as WIP. Another thing that I noticed is that no forum thread was generated for the map (by forum thread i mean this https://osu.ppy.sh/community/forums/topics/1113362?start=7581854) So this might be the main cause.

Anyways this is a huge issue because maps that are set to WIP cannot receive nominations so it's basically just taking up spacing off my pending list.

**Comment by Darius-Wattimena** [comment]
Possibly got broken after the fix at #506 ? 

Seems to happening for a lot of other people their sets. First broken map seems to be https://osu.ppy.sh/beatmapsets/1230433#osu/2558005

**Comment by peppy** [comment]
Not related to linked issue, but fixed.

**Comment by Regou01** [comment]
Doesn't seem to be completely fixed unfortunately. My mapset: https://osu.ppy.sh/beatmapsets/1228132#osu/2565270 have the same issues here, where I did multiple attempts to submit it to the pending section recently (until yesterday), it uploads as WIP. Might need further investigation into this.

**Comment by peppy** [comment]
We've tested this with multiple maps and it definitely seems to be working. Could you confirm you are going through the whole BSS process and hitting submit at the end?

If it's still happening, please make a video so we can try and diagnose the issue.

**Comment by Regou01** [comment]
> 
> 
> We've tested this with multiple maps and it definitely seems to be working. Could you confirm you are going through the whole BSS process and hitting submit at the end?
> 
> If it's still happening, please make a video so we can try and diagnose the issue.

tried to do a testrun upload just now. https://puu.sh/Ghsou/ce9a241bf1.mp4 As you can see, the map has been uploaded through the whole BSS process properly but it remains in the wip section. Adding on top of that, its corresponding forum thread is missing as well: https://osu.ppy.sh/community/forums/topics/1118297 .

**Comment by peppy** [comment]
Oh, I see. If there's no forum thread that will definitely be an issue.

I've reset things for you – please try once more.

**Comment by Regou01** [comment]
> 
> 
> Oh, I see. If there's no forum thread that will definitely be an issue.
> 
> I've reset things for you – please try once more.

It has been fixed and has been uploaded to pending.
