### ISSUE TITLE
Playing with flashlight hides the leaderboard

### ISSUE THREAD

**Issue by TheNinty** [ppy/osu-stable-issues#508]
I usually play with the local leaderboard on so I can see my score improvement. When I play maps with flashlight though, the "flashlight" hides the leaderboard.

**Comment by Waveium** [comment]
I'm pretty sure thats a intended feature. but you can see a spectator list with flashlight.

**Comment by peppy** [comment]
I don't think we'll be changing this in stable. May reconsider if it's a popular request in lazer (or potentially the layering is already different to the point that this is how it is).
