### ISSUE TITLE
Skin file stop working(Taiko)

### ISSUE THREAD

**Issue by lucasnathaniel** [ppy/osu-stable-issues#509]
According to criteria: _"Things that affect your daily enjoyment of the game"._

Recently I've noticed that **taikohitcircleoverlay.png isn't working anymore**, I used to play with [my skin](https://mega.nz/file/aB1jTSJJ#_Hw6HZuXtjQqZqMKrGjKWJrEWT6AWraH0V8ias7HAs8) that has overlay and only taikobigcircleoverlay.png is working. I test on skinning maps like [Living Color (Dezpot Remix) - MitiS](https://osu.ppy.sh/b/1544021) and this file isn't working too(I checked with Default skin).
The example below show the difference between the bigcircle(that is correct) and the hitcircle that is just the original color(isn't loading the overlay file):
![](https://osu.ppy.sh/ss/15242629/968c)

I asked to some friends and they're with this problem too, please check this issue,
Thanks, [K4L1](https://osu.ppy.sh/users/11334594)

**Comment by peppy** [comment]
this is intended to stop gameplay manipulation. sorry to have broken your skin.

**Comment by peppy** [comment]
to clarify: overlay still works but you can't colour it outside certain bounds.

**Comment by lucasnathaniel** [comment]
Oh man... How someone can gain advantage changing the color? I don't like this default color, and why the finishs(bigcircle) still with color overlay? It made me sad :(. But ok my friend.... This update just break all maps with color overlay, now instead to read 2 colors the player need to read 4 or disable the skin.

**Comment by peppy** [comment]
yeah, it's an unfortunate case. people were using colours to change taiko into mania. it's always a few that spoil the fun for the masses, but not much we can do at this point.
