### ISSUE TITLE
osu!catch: Sliders over 1 minute make the map unloadable

### ISSUE THREAD

**Issue by squirrelpascals** [ppy/osu-stable-issues#51]
Sliders that last exactly one minute are able to be loaded and played successfully. Anything longer than that can't be. I tested this with spinners too but this only seems to be the case with sliders. Here's a [.osz](https://puu.sh/EjaSd/4f17c02499.osz) that demonstrates the problem.

**Comment by MillhioreF** [comment]
This is intentional due to excessive amounts of droplets being created and stalling out difficulty calculations and map loading. The limit could probably be relaxed a little, but would still need to be a sane value. How does 5 minutes sound?

**Comment by squirrelpascals** [comment]
5 minutes sounds better. mainly pointing this out because this is an actual issue that came up from converting a map of mine. i dont think anyone will attempt to rank a 5 minute slider lol

**Comment by iptq** [comment]
brb ranking a 5 minute slider

**Comment by JBHyperion** [comment]
I can't see a single slider exceeding 5 minutes ever being used in a "serious" map - not least of all in catch where sliderart is not that prevalent due to only having one dimension to work with :D

Proposed limit sounds good to allow a few extra osu! -> osu!catch convert cases as long as it doesn't put the difficulty calculation process system at risk.

**Comment by smoogipoo** [comment]
Are there any ranked maps with 1 minute sliders?

**Comment by MillhioreF** [comment]
The longest ranked slider I'm personally aware of is [21 seconds](https://osu.ppy.sh/s/95701) so I can't see any legitimately going over one minute, but I don't see the harm in this for certain unranked [fun maps.](https://osu.ppy.sh/b/716954)

**Comment by smoogipoo** [comment]
I mean, so then if a similar map goes over 5 minutes we extend it to 10 minutes? I don't think there's a reason to spend time on this and go to the effort to make sure it's actually even playable on these beatmaps.
