### ISSUE TITLE
Invalid time point at editor

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#510]
I know this has been brought up and fixed before
But there seem to be some problems
[2020-08-08 12-50-13.zip](https://github.com/ppy/osu-stable-issues/files/5044602/2020-08-08.12-50-13.zip)
It looks like I have this problem in my beatmap(I added it in zip)(seens only my beatmap?)
Other beatmap will be played from scratch in Compose when click play button at end of the play
It seems to twitch in my beatmap

**Comment by cdwcgt** [comment]
This issues seens solved after cuttingedge20200815

**Comment by peppy** [comment]
We didn't change anything which would fix this, but I'm glad you resolved your issue.
