### ISSUE TITLE
Hitsounds and Storyboard Issues

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#511]
When ignore beatmap hitsounds are enabled it should also disable storyboard hitsounds because it doesn't fit in, or maybe a button to disable storyboard hitsounds or maybe when you disable storyboard it disables hitsounds as well
example: when you are playing a map and a random piano noise is played

Also when you have ignore beatmap hitsounds, it shouldn't load the hitsounds because it causes lag. Maps with little to no hitsounds give me 60fps and no latency, maps that have tons of hitsounds, such as maps with piano noises as the notes, causes latency and an fps drop. It also causes the map to take a long time to load.

**Comment by peppy** [comment]
If hitsounds are taking time to load, it may be an issue with your PC or drivers elsewhere.

We aren't making such performance optimisations on stable because the performance is already pretty good, but if you find the same issues on lazer then we can address them there, if they aren't already.

**Comment by WinterIsPretty** [comment]
What about the issues with storyboard hitsounds being played when ignore beatmap hitsounds is on

**Comment by peppy** [comment]
please disable storyboard to fix that

**Comment by WinterIsPretty** [comment]
In mania (what I play on most so haven't done standard) it stays on and is super distracting when playing you can't turn it off unless u have effects turned off
