### ISSUE TITLE
Increase Maximum BSS Filesize For Pack Mapsets, and Removing or Changing "Beatmap Plagiarization" Protection

### ISSUE THREAD

**Issue by downpour-osu** [ppy/osu-stable-issues#512]
Hello Development team,

I cannot understand why the maximum beatmap filesize is so small. I am currently hosting a beatmap pack from a mapper who deleted their maps but gave me permission to reupload them on discord and linking the download in my userpage, because the game is unwilling to allow me to release a 35 MB pack consisting of a literal handful (eight) of maps, with only six total 192kbps mp3s and a couple of modestly sized backgrounds. I find it ridiculous that I can send the pack as a discord message, yet it is too large for the osu website. 50 MB is really not a lot to ask for, in my opinion, because some of the most iconic map packs and mapsets in the game couldn't get uploaded today, which is really unfortunate. The Unforgiving, which is still competitive today, occupies 100 MB! Forget ranking, you couldn't even upload it today **in four parts**!

I also do not understand why the "beatmap plagiarization" protections are still in the game, because as we've seen, they don't really prevent plagiarization at all anymore. Every mapper has encountered it and learned how to get around it, and this usually occurs when you are very new to mapping and are using someone else's mp3 and timing to make your own set. This is not plagiarization, rather, a great way for mappers to worry about learning basic mapping before attempting to time their own maps, but usually results in this plagiarization protection that they think is an error. 

In reality, all you have to do is to drag the audio file to your desktop, rename it, import it, and then create your own difficulty for the upper parts of the file and copy and paste the timing points and hitobjects, and it's that easy to steal a map. What exactly is the BSS protection meant to protect against? I, personally, would love to see this done away with entirely, as I feel there are many valid reasons for re-uploading a map, but at a minimum, it would be awesome to see plagiarization protections that are actually designed against plagiarism. This would entail hashing the hitobjects and timing points of every beatmap uploaded and comparing the hashes to every new upload, instead of the strange model now that doesn't really prevent plagiarization to anyone who knows that they are doing, but rather inconveniences newbies.

I'm going to wrap this up because it is getting long, but please remember that these are modular requests. You can just implement the larger filesize, or just deal with fixing the BSS, but I would absolutely love to see both. These QoL changes are long overdue, and I honestly don't understand why the 25MB limit wasn't applied exclusively to the ranking criteria in the first place.

**Comment by ThePooN** [comment]
The limit isn't 25MB; see https://osu.ppy.sh/help/wiki/Submission

**Comment by cl8n** [comment]
as a workaround to your filesize limit, you can make a new difficulty and put circles at 00:00 and 10:00, then submit the mapset from that diff. mapsets aren't designed to hold packs so I'll think you'll just have to deal with that

the anti-plagiarism check on upload sounds nice, but this isn't the place to suggest new features -- maybe https://osu.ppy.sh/community/forums/4 or osu-web issues (BSS doesn't use the new website for now, though)

**Comment by peppy** [comment]
as a workaround, DONT DO THIS.

one beatmap, one audio track. if you want to "HOST A PACK" please do it via a file sharing site. if you want to upload other people's beatmaps host it via a file sharing site or otherwise.
