### ISSUE TITLE
Graphic bug

### ISSUE THREAD

**Issue by AwesomeGaming25** [ppy/osu-stable-issues#515]
![15973091414286134751126665192854](https://user-images.githubusercontent.com/69625799/90115191-5636a780-dd86-11ea-8f27-9e36ad853f54.jpg)
There is some kind of graphics flashing bug hope you guys can fix it and there's a black line which is the bug that makes the screen distorted

**Comment by AwesomeGaming25** [comment]
It's on an old pc

**Comment by smoogipoo** [comment]
"old pc" doesn't help us. We need your full PC specs. Easiest way to provide this is by providing a [dxdiag report](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).

Also, please provide a video.

**Comment by AwesomeGaming25** [comment]
I can't send the video it won't let me

**Comment by AwesomeGaming25** [comment]
> "old pc" doesn't help us. We need your full PC specs. Easiest way to provide this is by providing a [dxdiag report](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).
> 
> Also, please provide a video.

I can't send the video it won't let me do it

**Comment by AwesomeGaming25** [comment]
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/5068216/DxDiag.txt)

[VID20200813171919.zip](https://github.com/ppy/osu-stable-issues/files/5068231/VID20200813171919.zip)
here is the video need to unzip if you wanna see

**Comment by AwesomeGaming25** [comment]
Nvm it's fix by defragmenting it
