### ISSUE TITLE
Bancho's IRC bridge will always send quits to the client

### ISSUE THREAD

**Issue by jvyden420** [ppy/osu-stable-issues#516]
The IRC bridge will always send quits to IRC clients, regardless if the user is sharing a channel with the user unlike what a normal IRCD would do. 
This can make some clients _(at least on Quassel IRC v0.13.1)_ bug out. In my scenario, it will cause a message to be logged in the log file. On other clients, worst case scenario it would probably cause a crash.

**Comment by peppy** [comment]
This is unfortunately best-effort. The IRC gateway is a legacy service. Bancho does not internally operate anything like an IRC server and does not have this state information.

We have already exposed chat APIs via apiv2 (docs.ppy.sh) if you are looking to make something automated. If this is just for accessing as a user, you may want to choose another client.
