### ISSUE TITLE
Pressing F2 to exit editor saves replay every time.

### ISSUE THREAD

**Issue by Baron9876** [ppy/osu-stable-issues#518]
The default key to exit the play test in editor is F2. With the latest update that also saves failed replays which for some reason is also implemented into the editor. This creates a lot of replay files, especially mapping osu!catch for example which requires a lot of in editor testing.
[Example](https://baron.s-ul.eu/KtIsJXiv)

I think this should be disabled in editor mode

**Comment by peppy** [comment]
Has been fixed.
