### ISSUE TITLE
Online accuracy on catch beatmaps shows incorrect values when increased

### ISSUE THREAD

**Issue by LiterallyFabian** [ppy/osu-stable-issues#519]
When you finish a catch beatmap you already have submitted a score on and get higher accuracy than before, the number that shows your improvement from the previous highest accuracy will be too high.
## Some examples:
Improvement was only 0.94% but it says 18.49%
![image](https://user-images.githubusercontent.com/47401343/90420067-bcd60100-e0b7-11ea-80ec-366103fe1ec6.png)
![image](https://user-images.githubusercontent.com/47401343/90420041-b5aef300-e0b7-11ea-9d7c-79eab665bd97.png)

Improvement was only 0.32% but it says 13.35%
![image](https://user-images.githubusercontent.com/47401343/90420429-3c63d000-e0b8-11ea-9359-6bc185c08578.png)
![image](https://user-images.githubusercontent.com/47401343/90420493-52719080-e0b8-11ea-8c2a-ab3c5c1b2ce6.png)

Improvement was only 2.83% but it says 32.92%
![image](https://user-images.githubusercontent.com/47401343/90420831-c744ca80-e0b8-11ea-8ac1-a1b18aae6003.png)
![image](https://user-images.githubusercontent.com/47401343/90420815-c2801680-e0b8-11ea-8c81-e24003838e4c.png)

**Comment by Kasumiikun** [comment]
This happens also on mania, so perhaps taiko as well, I haven't been able to check for there.
But yeah, recurring bug in catch and mania for whatever reason.

**Comment by peppy** [comment]
This should now be resolved.
