### ISSUE TITLE
"Unshakable" Loved Map is Impossible to Update

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu-stable-issues#521]
For some reason this map is impossible to **Update to latest version** which makes it impossible to submit scores (it is a loved map). https://osu.ppy.sh/beatmapsets/1237363#osu/2571858

Video of this bug: https://youtu.be/2g8V3Syc7BA

**Comment by peppy** [comment]
@ephemeralis can you check on this one?

**Comment by Ephemeralis** [comment]
This is fixed.

Messing around with the BSS while submitting something is bad mojo.
