### ISSUE TITLE
Random mod for osu! mania does not work as intended in multiplayer

### ISSUE THREAD

**Issue by jms8719** [ppy/osu-stable-issues#522]
Currently, when freemod is enabled in multiplayer mania map, the random mod can only be applied to all users or none, similar to how double time is forced onto every user. Users should be able to apply random mod selectively, like all the other non-double and half time mods.
I found an osu forum thread with a comment from an alumni stating that this behavior is not intended.
https://osu.ppy.sh/community/forums/topics/333283

**Comment by smoogipoo** [comment]
This is a limitation of how the seed is passed to and used between clients. Very involved change involving both osu! and bancho and is unlikely to change, but will be fixed in lazer.
