### ISSUE TITLE
Scoreboard in multiplayer matches is not hidden after game restart

### ISSUE THREAD

**Issue by Thymue** [ppy/osu-stable-issues#523]
In singleplayer you hide the scoreboard by pressing TAB and it remains that way until you press it again
In multiplayer you hide it with TAB and it is visible again after you restart the game

**Comment by WinterIsPretty** [comment]
thank you for reporting this lol it has been irritating me for a while I just didn't want to report it

**Comment by WinterIsPretty** [comment]
:(

**Comment by WinterIsPretty** [comment]
spoke too soon
