### ISSUE TITLE
animated hits broken

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-stable-issues#525]
Problem: hits (100, 50, Miss) not showing after recent osu! update
Skin: https://ck1t.ru/s-1552
Video: https://mega.nz/file/5McT2A6C#HjsoQw8MK4gc_puZWVl45wihT7OTYY1b0Z13O7yf85E

**Comment by smoogipoo** [comment]
Which skin are you using? The download link contains 9 skins... Please give the name.

Did you change resolution recently?

**Comment by cyperdark** [comment]
i use 1280x720
version: CK

**Comment by cyperdark** [comment]
also on 1920x1080 it's works fine

**Comment by smoogipoo** [comment]
Are you using the "v1.1" skin? That skin does not provide low-res hit sprites.
