### ISSUE TITLE
Error in the italian translation of osu!

### ISSUE THREAD

**Issue by Jack7878ts** [ppy/osu-stable-issues#526]
When you scroll down to see how much pp you gained from a map you'll read: 
![screenshot020](https://user-images.githubusercontent.com/70257745/91272568-376be400-e77c-11ea-8299-0f5faa7f1aee.jpg)

They wrote: Ottentuo and Classfica, But the correct words are Ottenuto and Classifica, ottentuo and classfica doesn't mean anything.
If you want to correct those words you have to go to the localisation folder: C:\Users\*YourName*\AppData\Local\osu!\Localisation
Open the it.txt file and replace: "RankingDialog_LocalRanking=Hai ottentuo il rank #{0} nella classfica locale di questa mappa!"(you'll find it at the very end of the file) with "RankingDialog_LocalRanking=Hai ottenuto il rank #{0} nella classifica locale di questa mappa!"

**Comment by peppy** [comment]
I've updated this but the workflow for updating localisations isn't really active any more, so I can't promise when it will be deployed.
