### ISSUE TITLE
inconsistency with ipc.txt and ipc-channel.txt

### ISSUE THREAD

**Issue by nekoraw** [ppy/osu-stable-issues#527]
sometimes ipc.txt and ipc-channel.txt doesn't work as expected

normally osu-cuttingedge in tourney mode should write the multiplayer id in the ipc-channel.txt so lazer can access it to show the messages and that's the case like 90% of the time.
sometimes it simply doesn't write anything in ipc-channel.txt so lazer doesn't show anything

also, when you import a new song (downloading a song you don't have from a lobby) it doesn't write the id in ipc.txt until you check the map status manually on the client (you can do this simply by clicking edit in the window 0 and waiting to verify the map status). it works normally for new maps or maps you already had.

you can verify things in this video: https://drive.google.com/file/d/1CcEIP3BxDM8KuRcjqmxv2LsjUIA6BErE/view?usp=sharing

cutting-edge logs: https://drive.google.com/file/d/1yzHxqIYiq8_akWzkWVQRD1AAGZ1QRf6A/view?usp=sharing
osu!lazer logs: https://drive.google.com/file/d/1Gd6PZYzsM50qHhkAywlzz0AcEaBejKDr/view?usp=sharing

ipc-score.txt and ipc-status.txt works fine

**Comment by nekoraw** [comment]
it worked today: https://i.imgur.com/SqEev9r.png but it might stop working out of nowhere
also, tusk_star wasn't able to make it work (because it might simply not work) so he had to crop the tournament manager screen chat section: https://www.twitch.tv/videos/718490374

**Comment by peppy** [comment]
going to close this for now because not sure of the underlying issue and haven't seen other repro it.
