### ISSUE TITLE
Changing the timing signature doesn't effect lines on mania editor

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#528]
in the mania editor, the lines stay at 4/4 but if you change the timing signature to 3/4 it changes on the timeline but not in the mania editor.

![Untitled](https://user-images.githubusercontent.com/52920930/91494367-56eb3580-e87e-11ea-924d-d996abd339ed.png)

**Comment by smoogipoo** [comment]
Seems to work for me... Can you always replicate this?

**Comment by WinterIsPretty** [comment]
Woah that's weird something caused it to do this

**Comment by WinterIsPretty** [comment]
Oh it was caused because the sv I put down is 4/4 but the bpm didn't change it from 4/4 to 3/4 which I didn't know was a thing, it was caused because I used a website for sv because I needed a super long subtle sv increase and i didn't want to crash my game over and over again.

**Comment by WinterIsPretty** [comment]
Maybe this is kinda a bug because it causes the timeline in the mania editor to do this

**Comment by smoogipoo** [comment]
I think the bug here is that inherited timing points can provide their own time signatures, if that's what you mean.

**Comment by WinterIsPretty** [comment]
Yes if the inherited timing signature is 4/4 but the timing signature is 3/4 or any other timing signatures, it causes this to happen

**Comment by smoogipoo** [comment]
Will be fixed in the next CE.
