### ISSUE TITLE
Move "kick" so its not in the same position as "view profile" in multiplayer

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#53]
I've learned not to instinctively click the player and press 2 because doing that while you're match host automatically kicks them from the match... bad idea!

Not sure what the best way to solve this one is, maybe swap the menus around, so have the menu when you're host be the same except add an item that says "match host options" which then allows u to pass host or kick idk

**Comment by peppy** [comment]
How about we just add a confirmation popup?

**Comment by MillhioreF** [comment]
Confirmation added in next cuttingedge.
