### ISSUE TITLE
osu doesn't fully connect to bancho if you close the game while #osu is closed

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-stable-issues#530]
Chat is in a broken state, while online notifications and the online user overview (F9) thing work. You can not message any users in this "receiving data" state. This state is consistent over restarts. Network log doesn't list any error.

How to trigger:
- close #osu
- close the game
- open the game

How to fix permanently:
- close broken #osu
- open #osu again
- **dont close the channel when closing the game**

Version: b20200826.2cuttingedge

**Comment by peppy** [comment]
This should be fixed in next cutting edge. Thanks for reporting!
