### ISSUE TITLE
NF icon is active in the mod selection interface while not active in the multiplayer room

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-stable-issues#531]
**Reproduce steps:**
* Create a lobby
* Enter: `!mp mods DT NF`
* Enter: `!mp mods FreeMod`
* The player click on the "Change" button to choose the mod

In the mod selection interface, the DT icon is inactive but the NF icon is active and is not shown on the player slot (I haven't tested if it affects score or not yet).
![screenshot078](https://user-images.githubusercontent.com/16283764/91743215-abc1df80-ebe1-11ea-872b-d708a6154ef3.png)
![screenshot079](https://user-images.githubusercontent.com/16283764/91743219-ae243980-ebe1-11ea-8e19-8edacb2a30a8.png)

**Comment by smoogipoo** [comment]
Fixed in the next CE.
