### ISSUE TITLE
Auto-saving in the Editor is not a thing

### ISSUE THREAD

**Issue by c-sig** [ppy/osu-stable-issues#534]
Most mappers living in areas with minimal quality in life experience a very infuriating issue whenever the power goes out or a computer crashes. They often go back to see that everything has been corrupted or simply deleted. This is pretty surprising since mapping is a very time-heavy venture and there's no definite way of saving. (Normal CTRL+S saving still has the risk of the whole .osu file getting corrupted. I can replicate this if necessary but this basically just happens whenever power goes out suddenly). 

I propose an auto-save feature OR a very accessible way to export maps (i.e. adding a key-bind such as CTRL+SHIFT+S) to minimize the loss of progress.

**Comment by c-sig** [comment]
Being able to export multiple times without overwriting the export may also help with history during mapping.

**Comment by peppy** [comment]
Have you considered using BSS? It will upload a copy for safekeeping.

**Comment by c-sig** [comment]
Most WIP maps aren't usually uploaded to the BSS to save upload space though. Not to mention that uploading to BSS every few minutes is pretty taxing for people with bad internet when they can just save locally in less than 3 seconds rather than 1-2 minutes of upload.

**Comment by peppy** [comment]
Are the chances of power outage overlappping with a save operation *really* that high? This seems like something that can wait until lazer, to be honest. Where we will implement it in a better way.

**Comment by WinterIsPretty** [comment]
My game crashes a lot when placing a ton of sv lines down and it gets pretty annoying and I save like every 10 seconds because of that

**Comment by peppy** [comment]
how about you report the crash? and we fix it?

**Comment by WinterIsPretty** [comment]
it was already reported

**Comment by peppy** [comment]
Please link the thread so we can give it priority.

**Comment by WinterIsPretty** [comment]
I swear I saw it but I found a new way to crash I'll try to do both ways so I can report them both with the log files but I can only do that tomorrow
