### ISSUE TITLE
"Go to map" button in osu!direct panel going to a wrong difficulty

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu-stable-issues#535]
### Observed
When you click on a "Go to map" button on the osu!direct panel, it goes to the correct beatmapset, but (often) not the right difficulty.

### Expected
If the link that opened the panel is a pointing to a specific beatmap difficulty id (like `osu://b/id` or `https://osu.ppy.sh/b/id`)  and NOT a beatmapset, then the "Go to map" button should redirect to the correct difficulty.

### Why it matters
It is useful to avoid "quiproquo" in beatmap sharing in general, but it would be particularly useful for people playing tournaments to avoid picking the wrong difficulty when checking out a mappool using osu!direct links.
When you have the beatmaps sorted by difficulty, you might not even realize that there is other difficulties that the one you where showed by the game when clicking on "Go to map".

**Comment by peppy** [comment]
Fixed in next cutting edge release.
