### ISSUE TITLE
Logging in whilst updating a beatmap will ask you to upload a new beatmap instead

### ISSUE THREAD

**Issue by Hydria** [ppy/osu-stable-issues#536]
In attempting to update
https://osu.ppy.sh/beatmapsets/998152#mania/2087790
a new mapset was created instead
https://osu.ppy.sh/beatmapsets/1252363#mania/2602869
which I cancelled once I realised a new set was being created instead of updating the old one.

After getting that set deleted and trying again, it created another new set,
https://osu.ppy.sh/beatmapsets/1252500#mania/2603115
and in downloading the new mapset, it asks the user to update to the old mapset instead.

Things to note:
- I was logged out of the client before attempting to update the map (logged in after pressing Upload Beatmap)
- Client Version: b20200831cuttingedge
- Using a freshly installed client and trying to submit/update did not work

Video of the update request after downloading the new set: https://www.youtube.com/watch?v=ON7mU1p_hfs

**Comment by peppy** [comment]
How are you "logged in after pressing upload beatmap"? That doesn't offer any functionality to log you in.

Please attach a copy the osz you are trying to upload. You are probably uploading a non-related osz. The correct process is to download the graveyard one then modify it.

**Comment by Hydria** [comment]
For the "logged in after pressing upload beatmap" confusion, I was referring to the following: https://i.imgur.com/fAxlMs2.gif

The .osz is in the zip file below (since GitHub doesn't support .osz uploading). 

You'll notice that the hard difficulty (which I exported from) has changed it's beatmapSetID to -1 whilst the other two retain the original value (the hard difficulty originally contained the same beatmapSetID until saving the map in-client).

[rainlord. - i wonder..zip](https://github.com/ppy/osu-stable-issues/files/5182258/rainlord.-.i.wonder.zip)

**Comment by Hydria** [comment]
https://www.youtube.com/watch?v=bTpHgtA1Sg0 video evidence of the original issue from start to finish

**Comment by Feerum** [comment]
@peppy hey there, it's been a while. Not sure if you looked into the replies of hydria yet. Just talked with him about it because i wanted to help him ranking this beatmap. But we can't really until this issue still exist.

**Comment by peppy** [comment]
@Feerum / @Hydria does this continue to be an issue? The two incorrectly uploaded/created maps have since been removed. The process for mending this should be the standard one (remove `SubmissionCache`, ensure the beatmap metadata is set correctly, resubmit).

**Comment by Hydria** [comment]
The original broken beatmap set was only fixed after a difficulty name change. The issue shown in the [video above](https://www.youtube.com/watch?v=bTpHgtA1Sg0) is still occuring on the latest CE build (20210311) and stable (20210316)

**Comment by peppy** [comment]
Right, good to know. I'll try and see if we can get that fixed to stop future breakage.

Sorry for the slow response time on this one!

**Comment by peppy** [comment]
Weirdly, I've tried five times and cannot reproduce this issue following the steps you mention. I've also read through the code and can't see how this could easily happen.

Have you seen this happen to anyone else? Are you have to have someone else try and reproduce if possible?

**Comment by Hydria** [comment]
I've asked two members of the community to try this issue out today and well...they also couldn't reproduce it.
I downloaded a fresh client from the website today, installed it somewhere new, and tried the issue, and it still occurs on my end.

**Comment by peppy** [comment]
Could you please reproduce this again and attach your log files afterwards? Especially interested in `network.log`.

**Comment by Hydria** [comment]
[Logs for the issue](https://github.com/ppy/osu-stable-issues/files/6204858/Logs.zip)

Steps performed:
1. Launched new client
2. Cancelled download of most of the new maps
3. Imported the newly download .osz of one of my maps
4. Opened the Editor
5. Clicked Upload Beatmap
6. Logged in
7. BSS shows asking to upload the map as a new map instead of updating
8. Closed out of pop-up, and exited the client

**Comment by peppy** [comment]
So the weird thing in your logs is that the beatmap you're submitting things it has a `BeatmapSetID` of `-1`. Out of curiosity, have you tried deleting your submission cache folder?

**Comment by Hydria** [comment]
Since this was performed on a new client installation, a submission cache folder hasn't been generated.

**Comment by peppy** [comment]
Are you able to reproduced this again, but at the final step (before hitting "upload") cancel out of the BSS dialog, zip the contents of the beatmap folder and attach it? You can omit the larger files - mostly interested in the `.osu` files.

**Comment by Hydria** [comment]
[1411917 midwxst - Final Breath.zip](https://github.com/ppy/osu-stable-issues/files/6210222/1411917.midwxst.-.Final.Breath.zip)

**Comment by peppy** [comment]
So even in the .osu file, the set ID is -1.

Can you try manually editing the file and updating this? Does it get set back to -1 on submitting with the same flow you've been testing, or has it always been on -1?

**Comment by Hydria** [comment]
[It resets back to -1 when uploading.](https://www.youtube.com/watch?v=443d85iE7Gg)
Happens regardless of if you back out of the editor or not.

**Comment by peppy** [comment]
Thanks, might be on to something here. The fact it only happens to you and not myself or others may be a timing / latency race issue. Will investigate further.

**Comment by peppy** [comment]
I think I've identified how this is happening (and why it may only be affecting you). It is both dependent on timing and how many beatmaps you have in your client.

Are you able to try again on the latest cutting edge release?

**Comment by Hydria** [comment]
Just tried on 20210330.2, issue seems to be no longer occurring. Will close as fixed.
