### ISSUE TITLE
Pressing F when a map is on ready state on Auto mod mess up the playback speed

### ISSUE THREAD

**Issue by minhperry** [ppy/osu-stable-issues#538]
**Describe the bug:** 
When you press F (double speed) when a beatmap is on ready mod for Auto playback (usually right after you click the start button), the game will register that the replay is played on 2x speed but it's actually played on normal speed, thus make you be able to watch replays in 0.25x speed
~~This doesn't work with replays without DT/NC~~
This also works with DT/NC replays, you double tap F on ready mode to switch to play it at normal speed (when the game register it being at 0.5x speed), thus switching to 2x speed will play it at 4x real speed

**Steps to recreate:**
1. Open a replay/Select AO mod
2. Quickly press F once if you are not using DT/NC, else twice while the game is on loading mode
3. (not DT) Switch to 0.5x speed. The song will now play at 0.25 its real speed
4. (DT) Switch to 2x speed. The song will now play at 4x its real speed   

**osu! Version:**
b20200831.2 / stable branch

**OS:**
Windows 10 Pro V10.1.18362

**Comment by peppy** [comment]
Thanks for reporting, but I don't think this will be something we fix (high effort / low severity). We've put in a lot of work to cases like this to ensure they won't happen in the next major update (known as lazer).
