### ISSUE TITLE
osu! potentially using outdated cryptographic protocols?

### ISSUE THREAD

**Issue by MagicalDrizzle** [ppy/osu-stable-issues#540]
I was having with trouble with osu! not wanting to connect to the internet:
- Installing wasn't possible, the cilent would stuck at the update step and display the check internet connection dialog.
- Installing was successful with another computer using the same network, so I copied the installation folder to my machine (as per here: https://osu.ppy.sh/community/forums/topics/118473)
> osu! is completely portable. Just copy the whole osu! folder to an external hard drive, USB drive, etc. and you're good.
- It booted up normally, but I couldn't sign in (An unknown error occurred)
- Checking the logs file revealed this line:
` 2020-09-10T09:08:09: System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm`
- A quick search seems to pointing on the direction of cryptographic protocols, and I have only TLS 1.2 enabled, so I enable TLS 1.1 and 1.0, and that resolved the whole issue for me.
Does osu! not support TLS 1.2, or was it just a freak coincidence?

**Comment by peppy** [comment]
Sounds correct. Please don't disable this. osu-stable is on a version of .NET which does not support TLS 1.2. The next major update (aka "lazer") will resolve this.
