### ISSUE TITLE
Game crashed when I scrolled too high in ranking panel

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#541]
I don't know if this is the file I need to send but I think it is
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5210402/runtime.log)
[debug.log](https://github.com/ppy/osu-stable-issues/files/5210415/debug.log)

I'll also send this

here is a video:
https://cdn.discordapp.com/attachments/701334126862794862/754019625909485648/how_to_crash_osu.mp4

when you hold while scrolling it scrolls SUPER FAST

**Comment by peppy** [comment]
Should be fixed in the next release.
