### ISSUE TITLE
Osu doesn't load everybody in when you join the game

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#542]
When you join osu it loads a handful of my friends then after I open the tab where I can see everybody it loads the rest of the people after a second, it doesn't load the rest of the people at all until I open that tab.

**Comment by peppy** [comment]
if you're going to report issues please give useful details. your words are basically useless to developers.

a video showing what you mean, with timestamps and descriptions for instance, would be helpful.

**Comment by WinterIsPretty** [comment]
This is what I explained
https://cdn.discordapp.com/attachments/463638143422169088/754033750836248726/2020-09-11_12-39-51.mp4

**Comment by peppy** [comment]
I don't get it. You mean the notification is split into multiple parts?

**Comment by WinterIsPretty** [comment]
No it doesn't update everybody until you open the player list for some reason

**Comment by peppy** [comment]
Can you try again now?

**Comment by peppy** [comment]
Can see what is happening here. Will require some further thought.

**Comment by WinterIsPretty** [comment]
it's fixed now in stable and cutting edge after the new update

**Comment by peppy** [comment]
Ah yep, forgot to mention here!
