### ISSUE TITLE
Holding a button on sliders and spinners doesnt work after latest update

### ISSUE THREAD

**Issue by Maximchik303** [ppy/osu-stable-issues#543]
While I hold a spinner or a slider it simply releases it, I made sure its not my keyboard being broken. It happens only ingame, it doesnt happen in Osu chat (for example) while I hold the same buttons for the same amount of time. I checked if it may happen in a different app and everything seems to work fine. The issue accured for no reason in the middle of playing Osu.

**Comment by Maximchik303** [comment]
Update: So I just noticed that the same happens with the smoke button, its basically as if turns on and off every second

**Comment by peppy** [comment]
This is something specific to your PC. Please check any changes you may have made. Unplug any input devices, restart your PC etc.
