### ISSUE TITLE
Boxes overlapping on the home page

### ISSUE THREAD

**Issue by idontwantagirlfriend** [ppy/osu-stable-issues#545]
---Bug description---
On 2560x1440 resolution, the client brief box (where beatmap count, playing time and current time are shown) overlaps with the now playing box when the song has unusually long title. Maybe this also happens with other non-widescreen resolutions? 

---Screenshot---
https://osu.ppy.sh/ss/15545263/eb60
![eb60](https://user-images.githubusercontent.com/34613980/93099327-7a194000-f6da-11ea-90ff-627efa230b5f.jpg)

---Logs---
[runtime.log](https://github.com/ppy/osu/files/5219136/runtime.log)

**Comment by peppy** [comment]
Thanks for the report, but we aren't really fixing these kinds of minor issues in stable. Rest assured it can't happen in the next major release of osu! (known as "lazer").
