### ISSUE TITLE
Sending only keydown events without keyup causes problems

### ISSUE THREAD

**Issue by dillonwastaken** [ppy/osu-stable-issues#546]
I'm using a tool to give my caps lock key the function of an Fn key, so pressing Caps+1 = F1, Caps+2 = F2 and so on. However, sometimes I press Caps+1 and it only sends the keydown event of F1 without sending the keyup. When this happens, the next time I press F1 nothing happens. Only when the keyup event is received, then the key will start working again to open the mod menu.

I've only tested this with F1 and F2 keys, but I assume it's the same for the rest

![image](https://user-images.githubusercontent.com/40649376/93346565-b24d8980-f866-11ea-855b-1a323684521b.png)

I hope this image illustrates the problem adequately

**Comment by peppy** [comment]
don't do this.
