### ISSUE TITLE
Constant connection dropping on multiple networks

### ISSUE THREAD

**Issue by bokerlol** [ppy/osu-stable-issues#548]
Hello,

I keep disconnecting from Bancho constantly acrossed 2 separate networks. These are networks in 2 completely different locations. I've unblocked it in my firewall and it still seems to be happening. Is there something going on with Bancho as of the last few days? 

Heres a video showing what it is doing: https://youtu.be/Wi0_v5-E5iM

Longer video(you can see the friends online constantly popping up due to reconnecting): https://youtu.be/Nu6e_3xcmew

Since it's doing this, it's lagging my game to where its unplayable at times. I've tried cutting edge and stable and both give the same issue. Not sure if there are logs I can give but if there are, let me know and I can.

**Comment by peppy** [comment]
Do you have osu! open in multiple locations? You probably have osu! open in multiple locations. You should close osu! at one location.

**Comment by bokerlol** [comment]
I don't believe I do? I thought I closed them both at the other location + i know for sure that when I had it open at the other location that the only other place it COULD be open would be at my house and it wasn't. Is there a way to tell? Or could I just change my password and it would log me out at those other locations?

**Comment by bokerlol** [comment]
Changed password, seems to have fixed it. Thanks! :]
