### ISSUE TITLE
"invalid md5 hash inside client hash" at web when requiring auth from client that starts from .cmd

### ISSUE THREAD

**Issue by arily** [ppy/osu-stable-issues#549]
I would like to start other applications ( such as asio hitsound ) before start osu, so I created a simple cmd file to help me with those,
but then the osu client requires me to auth my client, and when I click the pop-up notification, website refuses the auth of my client with the warning in the title.
https://osu.ppy.sh/client-verifications/create?ch=... ( the url is filled with mac address and hashes but I don't sure if it's good to paste it here.
start osu!.exe directly will not have this issue.

here is my script
```cmd
start "" "osu.asio_sound/osu!asio_sound.exe" 16
start "" "osu!\osu!.exe"
```

**Comment by peppy** [comment]
i have no idea what that is, but please do not run it. it is likely modifying osu! memory and will lead to a ban.
