### ISSUE TITLE
Make "cursor ripple" a skinnable element

### ISSUE THREAD

**Issue by Kastellan** [ppy/osu-stable-issues#55]
This would potentially allow people to see exactly where they tapped, as the current cursor ripple is very hard to see. A more visible cursor ripple could instantly clear up any confusion about how close you were to hitting or missing a note. This is one of the only gameplay elements that isn't skinnable right now.

**Comment by Poliwrath** [comment]
>Report critical osu-stable issues here

**Comment by nl-tatatat** [comment]
^ this seems like a [feature request](https://osu.ppy.sh/community/forums/4).

**Comment by smoogipoo** [comment]
This will be implemented in lazer, we don't want to expand the scope of skinning in stable.
