### ISSUE TITLE
The # of times you've played since osu! started includes watching replays

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#550]
For the `You've played x times since osu! has been started.` message, the playcount includes watching replays (which includes stuff like watching auto and spectating), which I assume is unintended.

https://streamable.com/dh5g45
Shown here, I restart osu! so the playcount is at 0, then retry a map 40 times, then watch a replay/auto 9 times, then I play the map again. The `You've played 50 times since osu! has been started.` message shouldn't have appeared since I only played 41 times.

**Comment by peppy** [comment]
This will be fixed in the next cutting edge release

**Comment by Magnus-Cosmos** [comment]
I think something went wrong with the change, on the latest cutting edge build, it seems like both the retry count and play count are gone (or are just 0 all the time), since I no longer get the `x retries and counting...` message at the top left, and I don't get any of the #userlog messages either.

e.g. https://streamable.com/4hsmvv
I retry the map a bunch of times but don't get the `You've retried {map} a total of x times in a row.` message.

**Comment by peppy** [comment]
great. i'll roll back the fix and we'll leave it broken.

**Comment by peppy** [comment]
Will be fixed in the next cutting edge.
