### ISSUE TITLE
upside-down monitor incompatible with osu

### ISSUE THREAD

**Issue by michaelb7136** [ppy/osu-stable-issues#553]
when I try to play osu in fullscreen on my second monitor (which is upside-down to avoid the bezel creating a gap between the monitors), osu appears to be upside-down, despite the orientation of the monitor being flipped in the windows display settings. also, when I click the button to make osu fullscreen, it has like a chance of making the screen turn entirely black until I close osu (or I guess for like a couple seconds according to the video but I swear it usually lasts longer and I have to close osu to make it stop). the screen also flickers to being completely black for like half a second every now and then even if I manage to get it to go fullscreen.

if your monitor isn't PHYSICALLY FLIPPED UPSIDE-DOWN in addition to having the orientation of the display flipped, your osu will look like it is in the correct orientation. if your monitor is PHYSICALLY FLIPPED UPSIDE-DOWN in addition to being flipped in windows display settings, osu will look like it is upside down, despite everything else on the display being perfectly fine. please PHYSICALLY FLIP YOUR MONITOR and change the orientation of the monitor to be flipped (which makes everything on the monitor look like it is right-side-up) and run osu in fullscreen mode on the flipped display. you will then see that osu is upside down, despite nothing else on the monitor being upside down.

Video or screenshot showing the problem: https://imgur.com/s31CP4w

osu! version: b20200918.3

**Comment by peppy** [comment]
Not much we can do about this sorry. Please run borderless for the time being!
