### ISSUE TITLE
Editor object information moved to an odd position

### ISSUE THREAD

**Issue by Darius-Wattimena** [ppy/osu-stable-issues#555]
When you select an object and map catch, you use the x values specified in the top right corner to check emphasize/consistencies. This is also used by almost all BNs as the information to check how good a map is. This information was shown in the top right corner almost perfectly aligned on the black overlay of the top timeline. 

With the current version of stable the information is moved way too much down and feels rather out of place since it almost overlaps the new combo button.

This issue could be related to #547 although this seems more like a specific issue only for catch mapping?

**The old situation:**
![](https://puu.sh/GwnSK/8e0b31f0ab.jpg)

**The current situation:**
![](https://puu.sh/GwnUf/094ce7c404.jpg)

**Comment by peppy** [comment]
I've rolled back the changes which caused this. Should be fixed in the next cutting edge build.
