### ISSUE TITLE
osu! stable attempts to submit relax scores and fails

### ISSUE THREAD

**Issue by 2secslater** [ppy/osu-stable-issues#556]
![Screenshot of the notification for the score submission failure](https://cdn.discordapp.com/attachments/732659821609877526/759310737147035709/unknown.png)

After playing a map with the relax mod enabled, it seems to try and submit the score, and fails every time. Saying it will try again in 16 minutes, with that time climbing.

I can confirm that playing without the relax mod submits scores successfully.

osu! should not be attempting to submit scores with the relax mod.

For the record: I am running osu! stable version b20200918.3

**Comment by peppy** [comment]
Aware of this one. Probably requires server-side fix.

**Comment by peppy** [comment]
This should now be fixed. Please confirm it's okay for you now!

**Comment by 2secslater** [comment]
Yes, I can confirm that this is solved.
Thanks.
