### ISSUE TITLE
Changing a single diff clears all the letter grades and last played dates for entire beatmapset

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [ppy/osu-stable-issues#557]
When any diff is changed or a new diff is created, the letter grades and the last played dates for the entire beatmapset are cleared.
vid: https://streamable.com/vttput

Unless the beatmap itself is changed, things like letter grade and last played date shouldn't be cleared.

**Comment by peppy** [comment]
This is a best-effort implementation. Would you prefer we just don't clear ever, because that's the alternative.

**Comment by sometimeszzzzzzz** [comment]
I actually do think not clearing would be better. Maybe it's just me but I can't think of any reasons why clearing would be a good thing. I've never had a moment where I needed to clear the letter grades for a beatmapset.
Even the [update to latest version](https://i.imgur.com/Mg8EqHd.jpg) button keeps the letter grades for the map, so I don't see why changing a map from the editor or adding a new diff should clear it.

**Comment by peppy** [comment]
Okay, will just remove this. That was the original bug "fix" and the reason for this behaviour.

**Comment by peppy** [comment]
I've fixed this specifically for the case you're logged out. If logged in, it is already re-retrieving automatically.
