### ISSUE TITLE
Optimal too stuttery and power saving feels too chunky.

### ISSUE THREAD

**Issue by Gandalphf** [ppy/osu-stable-issues#558]
Can we have the custom fps limit back?. My computer can only render 400 fps comfortably, which leads to a sorta stuttery experience on optimal. Power saving and vsync feel chunky or slightly laggy, respectively.
Just a custom frame limit like before, one that you can edit in the .CFG or in-game would be great.

**Comment by Joehuu** [comment]
You can still set a custom fps by:
- closing osu! if still on
- going to cfg
	- changing the `FrameSync` value to `Custom`
	- setting the `CustomFrameLimit` value to 400 or w/e
- opening osu! again

**Comment by peppy** [comment]
Closing as resolved (thanks @Joehuu).
