### ISSUE TITLE
scorev2 still submits even in private multiplayer lobbies. 

### ISSUE THREAD

**Issue by anxosu** [ppy/osu-stable-issues#559]
scorev2 still submits even in private multiplayer lobbies. 

This means that people are able to access player's scores from their profile, using an easy to access extension such as osuplus. 

Here's an example: https://osu.ppy.sh/community/matches/67661859 
This is a private mp link, which can only be accessed by those who were in the multiplayer lobby. 

just in case, here's what it looks like for anyone in that lobby: https://i.imgur.com/rrrsPXY.png
and for anyone not in that lobby they would be asked to sign in/they would be denied access. https://i.imgur.com/xRxjcMK.png

Now that doesn't even matter because you can temporarily see the scores on each individual player's profile. 
this is what it looks like without any extensions: https://i.imgur.com/r6DObq6.png
an this is what it looks like with an extension such as osuplus: https://cdn.discordapp.com/attachments/557417136159719448/760636782915354645/unknown.png

It is now not ideal for players who want to practice for their tournaments in a bancho multiplayer lobby to do so, since the data can be stolen from the opposing team for a competitive advantage. 

I suggest that in private multiplayer lobbies (with scorev2), the actual score and accuracy does not get submitted, or is not accessible in any way to the public, but it still gets added to playcount and other things that would not give away the specific player's score data. Some people have already resorted unfortunately to playing on private servers because it is way less likely that the data will be accessed on those servers. I hope I explained the issue well enough, hopefully this can get fixed before OWC so that people can feel comfortable practice for it on bancho.

**Comment by peppy** [comment]
The people using "private servers" may not be allowed in to any official tournament, so if you know of such users please warn them against this practice.

For the time being, v2 scores have been hidden from profiles once again.
