### ISSUE TITLE
rapid mouse inputs during transition to exclusive fullscreen mode cause beeps

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu-stable-issues#561]
transitions include:
- toggling exclusive fullscreen in options
- reopening after minimizing or boss-key
- going from editor back to main menu (since the editor always uses borderless window regardless of user config)

repro: spin your mouse-wheel during any of these transitions

Clicks can trigger it too, but you'll need an auto clicker. I was unable to reproduce this with mouse movement or keyboard input.

**Comment by peppy** [comment]
The beeps you hear are likely something on your system, not osu! specifically. Especially if you mean "pc speaker beeps" - it's likely a driver you have installed or otherwise.
