### ISSUE TITLE
Re-Opened Channels Upon Reconnection Move to Behind

### ISSUE THREAD

**Issue by ReiFan49** [ppy/osu-stable-issues#562]
## Problem

If you ever close a chat tab (by mistake) and rejoin it again, then Game connectivity have problem like maintenance or whatever is that makes you **need to reconnect to Bancho**. All the reopened chat tab are moved back past last channel (non-PM) tab.

## Steps to Reproduce

1. Close a chat tab (`/p` or `Ctrl-W`)
2. Reopen the chat tab
3. Force-reconnect the client **without restart**
4. Chat tab moved back and join state is stalled until you activate (click) the channel again

PS: the bug is somewhat accompanied with input leak when you `Ctrl-W` from somewhere else and suddenly the chat tab got closed by that too...

**Comment by smoogipoo** [comment]
I think this is such an edge-case scenario that it's not worth the time to fix.
