### ISSUE TITLE
Score not submitted after DNS server went down

### ISSUE THREAD

**Issue by Mrcubix** [ppy/osu-stable-issues#563]
The DNS server i was connected to (google classic 8.8.8.8 8.8.4.4) went down while playing, got highest score on a map, not submitted.
i changed my DNS and had to re-launch the game for them to take effect, except it won't submit my last play now.

![screenshot038](https://user-images.githubusercontent.com/39861216/95657183-51d30480-0b13-11eb-9adc-c86f2f60fb94.jpg)
![screenshot039](https://user-images.githubusercontent.com/39861216/95657185-54cdf500-0b13-11eb-8328-b0416f6c2e35.jpg)
![screenshot037](https://user-images.githubusercontent.com/39861216/95657190-5c8d9980-0b13-11eb-9ba8-1ef96fad8714.jpg)

**Comment by peppy** [comment]
Pending score submissions are lost after you quit the game.
