### ISSUE TITLE
Rank Letter updating on mods leaderboard

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-stable-issues#564]
On the gif below, the game incorrectly updates my best rank achieved on that beatmap based on my HDHR score instead of keeping the global one.

![Peek 10-10-2020 17-17](https://user-images.githubusercontent.com/4985725/95658691-9911c300-0b1c-11eb-90f5-e8f5d3fb5e35.gif)

**Comment by peppy** [comment]
Fixed in next release.

**Comment by Joehuu** [comment]
I think the fix here regressed the personal best display in mods leaderboard. It doesn't update and uses the last leaderboard selection score. Both images have hidden enabled.

Mods leaderboard loaded first:
![screenshot035](https://user-images.githubusercontent.com/35318437/97907212-c572c680-1cf9-11eb-8d54-8e4a869b7ecc.png)

Global -> Mods leaderboard:
![screenshot036](https://user-images.githubusercontent.com/35318437/97907303-f05d1a80-1cf9-11eb-87be-0ad496c516de.png)
