### ISSUE TITLE
"Interface voices" and "osu! music theme" settings re-enable themselves on game startup.

### ISSUE THREAD

**Issue by lokser12** [ppy/osu-stable-issues#565]
just as in title, it started happening after the halloween update to stable client.
vid: https://streamable.com/512hq8

**Comment by peppy** [comment]
This will occur until the end of halloween. Please enjoy!

**Comment by Joehuu** [comment]
Just saying, I believe these settings + snow were disabled (grayed out) before in the last 2 halloween / christmas updates I've been playing this game. If deemed too trivial to fix, I understand.

**Comment by peppy** [comment]
Ah yeah, that's definitely the case. I'll fix it for next update / next year... if stable still exists by then.
