### ISSUE TITLE
Default display title doesn't work for song titles with brackets

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-stable-issues#567]
the default display title is `[size:20,bold:0]Artist|Title`, but it should really be `[size:20,bold:0]Artist|[]Title` to avoid parsing problems when Title starts with a left bracket

example on https://osu.ppy.sh/beatmapsets/1244367 -BlastTheKidd- reported in #modding :
![image](https://user-images.githubusercontent.com/9954349/95820472-ffddda80-0cdc-11eb-9635-29ab8463fdc1.png)

**Comment by peppy** [comment]
Did someone change the display title on this beatmap? It's already got the empty brackets, which is *not* supported syntax.

**Comment by peppy** [comment]
Fixed in the next release, and I'm rolling back the change on that beatmap (which will now be a breaking change).

Whoever did this, don't.
