### ISSUE TITLE
Crash and stutters randomly on Mania maps, no idea why.

### ISSUE THREAD

**Issue by HyperLemons** [ppy/osu-stable-issues#569]
For a while now I've had stutters while playing Mania maps, today I finally had a crash (while making a new high score...). My specs are perfectly fine or at least should be for Osu!. I use Optimal FPS but I do have a custom fps set for when I was trying to troubleshoot on my own.

[runtime.log](https://github.com/ppy/osu-stable-issues/files/5375137/runtime.log)

[session.log](https://github.com/ppy/osu-stable-issues/files/5375138/session.log)

[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/5375185/DxDiag.txt)

I had Firefox Nightly running in the background with quite a few tabs open but it shouldn't really matter since I've had these same stutters with literally nothing else but Osu! running.

**Comment by peppy** [comment]
This repo isn't really for performance trounbleshooting. We have a guide for that [here](https://osu.ppy.sh/help/wiki/Performance_Troubleshooting).

The usual causes are other applications on your system or a badly made skin, so please check those.

**Comment by HyperLemons** [comment]
Sorry, I saw someone make a similar issue like this but had to do with a skin and I don't use skins.

**Comment by peppy** [comment]
If you hit ctrl+f11 twice you can determine where the stutters are occurring (by the colour of the spikes in the graph). If you can capture this I can point you in the right direction.

**Comment by HyperLemons** [comment]
Really appreciate it! Not sure if this will suffice for you though. Sorry everything looks a bit blurry by the way, I'm still working on fixing that.

http://www.mediafire.com/file/8r22t6a9vd52pxi/2020-10-13_23-41-38.mkv/file
