### ISSUE TITLE
The editor's default BPM adjuster should increment by 0.25, 1 and 5, rather than .004, .04 and .38

### ISSUE THREAD

**Issue by squirrelpascals** [ppy/osu-stable-issues#57]
[I'm talking about this thing.](https://puu.sh/Ejei0/5283676486.png)

Pretty much anybody seriously timing a map defaults to using the timing panel and typing into the textbox manually because changing the bpm in such small increments (by using the left/right arrows) is senseless. _I can't stress enough_ how many hours can be saved if we made this feature more usable by changing how the bpm increments with the arrows.

- Holding ctrl (smaller changes) should increment by .25

- Clicking normally should increment by 1

- Holding shift (bigger changes) should increment by 5

Using whole numbers rather than random decimals makes timing discussions easier to communicate between mappers, and makes finding the _exact_ bpm of a new song more efficient (for electronically produced or quantanized music, where bpm is exact). More specific decimals tend to be less necessary in maps; they're more used for very consistent live-performed songs. _That's_ when mappers should be using the timing panel-- if they even need it.

As a bonus, **adding a textbox** to this feature would make it so that we would need to use the timing panel even less (for both BPM and offset). Maybe double-clicking the white number will make it so you can type on it. Not sure if this counts as a "big change" but this would really be the icing on the cake if these changes go through.

**Comment by peppy** [comment]
Fixed in next cutting edge build.
