### ISSUE TITLE
Drop downs are still selectable when closing

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#572]
This issue only becomes annoying when the drop downs are very long. Because the drop downs take a while to close, you can accidentally press/select them.

Video: https://streamable.com/oym9aa
In the video I switch skins, then try to enable raw input right after, but the drop down is still closing, so instead it makes me select a skin instead.

**Comment by peppy** [comment]
Should be fixed in the next release.
