### ISSUE TITLE
Map Online Ranks not updating until clicking on map

### ISSUE THREAD

**Issue by opakq** [ppy/osu-stable-issues#573]
Recently I had to reinstall osu! due to my SSD failing, causing me to replace it. All my songs were stored on another HDD drive, in which I had changed the song directory to. After reinstallation, now I have to click on each song with the drop down menu for the leaderboard to be under an online rank for the online rank to load. Sometimes if I have never selected the song under online rank, and the online ranks don't load, and when I play the song, the score will not submit online. I have to play the song with the online leaderboard selected.

**Comment by peppy** [comment]
delete your osu!.db file i guess, might help

**Comment by opakq** [comment]
Thank you, that seemed to have resolved the issue.
