### ISSUE TITLE
.osz file not loading on the correct windows user

### ISSUE THREAD

**Issue by thebestph** [ppy/osu-stable-issues#576]
I'm not really much of a programmer so I don't know how it works but here's my issue:

So me and my brother share on the same computer (we're poor) with different windows users. Both has osu in it. I loaded my `.osz` file to osu however, it loads to the other user. It happened since the time my brother downloaded osu in his user. 

I would like this to be fixed ASAP. Thanks ;)

**Comment by peppy** [comment]
osu! isn't really coded in a way to exist installed in two locations (and handle that well).

Two options I can suggest:

- Share the osu! install with your siblings.
- Load beatmaps by dragging the files into the osu! window, rather than double-clicking.

**Comment by thebestph** [comment]
Is that so? By the way, thanks for the tip
