### ISSUE TITLE
Crash involving silent hitsound file

### ISSUE THREAD

**Issue by jacobthefailure** [ppy/osu-stable-issues#579]
I currently run a machine on Manjaro Linux 5.6.19 and run osu! with [ThePooN's](https://osu.ppy.sh/users/718454) [wine-osu](https://aur.archlinux.org/packages/wine-osu/) fork of wine. It also may be important to note that I use audio compatibility mode (otherwise the game sounds like a demonic nightmare).

When a beatmap is loaded and either the skin currently used or the beatmap itself has this certain silent hitsound file, the game becomes soft-locked and has to be manually killed. (Of every test I've done while making this report, only once did it have the "osu! crashed" screen.)

[Here](https://pastebin.com/YBySGFCP) is my runtime.log and the problematic hitsound file is located in [this](https://osu.ppy.sh/beatmapsets/1120289#osu/2449773) map (soft-sliderslide.wav). The file behaves normally outside of osu!, so I'm not sure if it's an external issue.

It's important to note that this does not occur with the standard 44-byte file provided on the [Ranking Criteria](https://osu.ppy.sh/help/wiki/Ranking_Criteria#rules.4) page.

This bug occurs on all maps and skins using this particular file. There may be other problematic files as well but I have not identified any yet.

The only solution I've identified thus far is just to remove the problematic file when it comes up, which works well enough, but this is still annoying and reproducible enough to be worth mentioning, I feel.

**Brief video demonstration:** https://youtu.be/IZEY7fXJ30I

osu! version: Stable 20201017.3 (latest)

**Comment by peppy** [comment]
Do you have the same issue on lazer?

**Comment by jacobthefailure** [comment]
Works fine on lazer, so no.

**Comment by huupoke12** [comment]
Doesn't happen on my "near stock" Wine 5.20 build. So I guess the problem is in the patch, which should be reported to the author.

**Comment by jacobthefailure** [comment]
Yeah, trying it with stock Wine shows that it is indeed a problem with the patch. Will see if I can figure that out, but since it doesn't seem to be an osu! problem, no point in keeping this open. Thanks!

**Comment by ThePooN** [comment]
Bit late on my emails, but that sounds more like an issue tied to the version of Wine rather than the patch itself.
