### ISSUE TITLE
Skins' Title is ignored – the folder name is used instead

### ISSUE THREAD

**Issue by SALZKARTOFFEEEL** [ppy/osu-stable-issues#58]
This has been fixed in Lazer, I know, but adding it to Stable would help get more people aware of it before they switch to Lazer and see that all their Skins' names are now messed up.

**Comment by peppy** [comment]
Where is it ignored? Could you please provide screenshots and examples?

**Comment by smoogipoo** [comment]
In the settings dropdown the names displayed are actually folder names (see: https://github.com/peppy/osu-stable/blob/master/osu!/Graphics/Skinning/SkinManager.cs#L77)

**Comment by peppy** [comment]
Right, that's an optimisation and likely can't be quickly improved. Going to close this one as fixed-in-lazer.
