### ISSUE TITLE
Latency Spike Lag

### ISSUE THREAD

**Issue by Littlel0st** [ppy/osu-stable-issues#580]
I just bought a new pc with intel i5 10900k with RTX 3080 and when I am playing osu which is usually around 0.6 or 0.5 ms it spikes up to 1 or 2 ms numerous times causing my gameplay to start disliking the game due to the number of spike lags I am getting. Is there a way to fix it so that I can enjoy the game again?

**Comment by peppy** [comment]
Just no.

"spiking" to 1 or 2ms is not. an. issue.
