### ISSUE TITLE
Beatmap search filter: days played comparison is inverted

### ISSUE THREAD

**Issue by Aldoggen** [ppy/osu-stable-issues#581]
# Issue
The beatmap search has an option to filter based on the time since you last played the beatmap. As I understand it, something like `played<30` should only show the maps you played in the last 30 days, since for me, this syntax translates to "the amount of days since you last played this map is smaller than 30". This is not what happens ingame however, and I think the comparison gets reversed, so that `played<30` only shows maps you _haven't_ played in the last 30 days (which is something you would expect `played>30` to do). The weird thing is that this behaviour is not consistent with the other filter commands: for example `stars>3` will correctly show beatmaps with a star rating above 3.

I propose that the comparison for the `played` filter option gets reversed.

# Images
osu! thinks the map I last played two minutes ago was last played over 30 days ago.
![bug1](https://user-images.githubusercontent.com/37844385/97789214-ea165380-1bbe-11eb-8cbf-d57013610d89.png)
osu! thinks I've played this map in the last 30 days, but I haven't played it since august.
![bug2](https://user-images.githubusercontent.com/37844385/97789215-eb478080-1bbe-11eb-8976-73f6c473a6f1.png)
This issue becomes even more apparent in the "recently played" tab.
![bug3](https://user-images.githubusercontent.com/37844385/97789216-ebe01700-1bbe-11eb-8c58-e5ce2dd3c05f.png)
There's nothing special about the number 30. Here I try to let osu! show me the maps I haven't played in the last 7 days.
![bug4](https://user-images.githubusercontent.com/37844385/97789213-e8e52680-1bbe-11eb-8c1e-4474bcd3112b.png)

**Comment by peppy** [comment]
Should be fixed in the next release.
