### ISSUE TITLE
Fonts doesnt fallback properly

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu-stable-issues#582]
If you specified a font location in skin.ini (E.g. ScorePrefix: Fonts\Score) and the said folder\font doesnt exist it wont fallback to the default fonts. it also appears even if the fonts are in the root folder. i accidentally encountered this problem when trying to prepare the skin to test in lazer regarding https://github.com/ppy/osu/issues/9863

![screenshot129](https://user-images.githubusercontent.com/41866328/97848131-95dcb200-1d2b-11eb-96a6-3dcf614bd9ab.png)
![screenshot128](https://user-images.githubusercontent.com/41866328/97848136-983f0c00-1d2b-11eb-9b2c-a7f935886445.png)

skin: 
[hit300g.zip](https://github.com/ppy/osu-stable-issues/files/5473726/hit300g.zip)

Edit: forgot to mention that this affects the hit circles number, score and combo prefixes

**Comment by peppy** [comment]
so don't do this

**Comment by enoslayd** [comment]
oh ok thanks
