### ISSUE TITLE
Some friends occasionally missing from friend listing

### ISSUE THREAD

**Issue by TobiasLeander** [ppy/osu-stable-issues#586]
I've seen this happen multiple times now where people I would have added on the site and in-game are randomly not added in-game anymore when I then click on them and open their profile they are added on the website but not in-game, this issue only starting happening as of recently and have seen multiple people with the same issue.

Edit: Seems to be if u run IRC and then launch osu! it will remove you from people's friendlist in-game, if u then close the irc client and open osu! u will be added in-game again.

**Comment by peppy** [comment]
So it's not "unfriending" but the users are simply missing from display, correct?

**Comment by TobiasLeander** [comment]
Yeah, they are kept added but only on-site, but u have to re-add them in-game for them to show up in the display when filtered by friends, closing the IRC client, and then relaunching the game will cause u to show up again as added on the game client.

**Comment by peppy** [comment]
Before I look into this one, it seems really strange that having an IRC connection would change anything. Can you confirm beyond doubt (over multiple tests) that this is truly the case?

**Comment by TobiasLeander** [comment]
Did a lot of testing and it 100% seems to have smth to do with IRC connections, the comment I wrote above is the exact way to reproduce it.

**Comment by peppy** [comment]
Do you have yourself added as a friend or anything else weird? Are you sitting close to the maximum friends limit?

On a quick check I can't see anything which would cause friends to be sent any differently depending on IRC connection status.

**Comment by TobiasLeander** [comment]
I do have myself added tho I know multiple people with the same issue that doesn't have themselves added.
Also, I'm at 113/500 friends so not even close to the maximum friends limit.

**Comment by peppy** [comment]
"multiple people" you know all use IRC gateway? could you please name these users too so i can investigate furtehr?

**Comment by TobiasLeander** [comment]
2 people I see this happen to very commonly are **Kobold84** and **Saten** which have themself's added, I have however also seen this happen to **Yuukipon405** who doesn't have himself added.

**Comment by peppy** [comment]
This should finally be fixed in the next release.
