### ISSUE TITLE
osu! crashing with discord running in the background

### ISSUE THREAD

**Issue by xTreeTV** [ppy/osu-stable-issues#588]
For about 3 days now, my osu! client keeps crashing with Discord running. It runs for about 30 seconds an crashes afterwards. The issue does not occure in compatibility mode but isn't fixed by turning Discord Rich Presence off. Without Discord running in the background, osu! runs normally. What's interesting as well is, that the issue only occures in full screen. As long as osu! is running e.g. behind another window in windowed mode or minimized, it won't crash. 

Specs:
Windows 10 Home
Intel i7-1065G7
AMD R9-Fury (eGPU)
16GB RAM

Here's what the event viewer shows (couldn't find a way to export in english other than changing the system language, I hope it's fine like that. Just says unknown anyways, but I never really used the event viewer before):
Protokollname: Application
Quelle:        Application Hang
Datum:         03.11.2020 21:05:07
Ereignis-ID:   1002
Aufgabenkategorie:(101)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      Amins-C940
Beschreibung:
Das Programm osu!.exe Version 1.3.3.7 hat die Interaktion mit Windows beendet und wurde geschlossen. Überprüfen Sie den Problemverlauf in der Systemsteuerung "Sicherheit und Wartung", um nach weiteren Informationen zum Problem zu suchen.
 Prozess-ID: 3678
 Startzeit: 01d6b21c5d85a17d
 Beendigungszeit: 12
 Anwendungspfad: C:\Users\amin2\AppData\Local\osu!\osu!.exe
 Bericht-ID: 629e7241-74f3-4083-b041-04b7292ef5b6
 Vollständiger Name des fehlerhaften Pakets: 
 Relative Anwendungs-ID des fehlerhaften Pakets: 
 Absturztyp: Unknown

**Comment by peppy** [comment]
Please try turning off the discord overlay.

**Comment by xTreeTV** [comment]
Not the most optimal solution but it works. Thank you. I noticed that the Windows Gaming overlay won't work anymore as well. I guess for the same reason. I get why overlays shouldn’t work in osu! though, if it's something that is intentional.

**Comment by peppy** [comment]
This may be due to a change in your graphics drivers, or just too many overlays running at once. We have not changed anything at our end which could cause this to suddenly occur.
