### ISSUE TITLE
Delete all unranked maps button has no confirmation

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-stable-issues#59]
As title states, the delete all unranked maps button doesn't ask for user confirmation, I've accidentally pressed this several times (since it ends up in the spot for skins after you scroll down to select a skin), and usually the game just crashes when I press it.

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/65333981-76082e80-dbfc-11e9-8d12-f96d75a08bd1.png)

It does ask for confirmation.

**Comment by peppy** [comment]
That's a really bad dialog box (probably the reason for the "crash")

**Comment by smoogipoo** [comment]
Ah I understand, reopening then.

**Comment by MillhioreF** [comment]
Fixed in next cuttingedge.
