### ISSUE TITLE
combo on the bottom left is fading away completely sometimes

### ISSUE THREAD

**Issue by DatVeno** [ppy/osu-stable-issues#591]
https://streamable.com/i81065

Seems like that happens randomly, already had the case that it went like that until like 100 combo into the map.
Not really gamebreaking but probably not intended.
Using newest cutting edge version.

**Comment by peppy** [comment]
Nothing has changed which could cause this. Are you able to reproduce on stable?

**Comment by DatVeno** [comment]
Yep, also happening on stable, noticed that today while playing.

**Comment by DatVeno** [comment]
That also happens while watching a replay but it seems like it has almost no pattern. Noticed it only randomly happened at the beginning of the map, when the combo breaks or after a break in the map.

**Comment by peppy** [comment]
Does this happen with the default skin? If so, can you try running the game at a different screen resolution and see if it helps?

**Comment by DatVeno** [comment]
The clip is done with the default skin. Also happens on different resolutions.

**Comment by peppy** [comment]
How often can you reproduce this?

**Comment by DatVeno** [comment]
https://streamable.com/ozz5fk

**Comment by DatVeno** [comment]
ok after some testing, it seems like it only happens when my frame limiter is on unlimited

**Comment by DatVeno** [comment]
Yep, its defenitely the frame limiter
https://streamable.com/x53idk

**Comment by peppy** [comment]
I've pushed a fix to cutting edge, could you please test it resolves the issue?

**Comment by DatVeno** [comment]
Its fixed now!
