### ISSUE TITLE
osu! 20201110 crashing on wine-mono

### ISSUE THREAD

**Issue by X9VoiD** [ppy/osu-stable-issues#592]
| Information | |
| :-- | :-- |
| Operating System | Arch Linux |
| Osu Version | 20201110 |
| Wine Version | wine{-staging} 5.21 |

The update [20201110](https://osu.ppy.sh/home/changelog/stable40/20201110) is broken when running on wine-mono.

Last working version is [20201102.5](https://osu.ppy.sh/home/changelog/stable40/20201102.5).

![image](https://user-images.githubusercontent.com/10338031/98649966-386fe300-2373-11eb-8b7c-b6a4dd95896a.png)

# Reproduction

## Wine Setup

1. Install wine, install winetricks
2. `wineboot` (install wine-mono and wine-gecko when prompted)
3. `sudo winetricks --self-update`
4. `winetricks corefonts gdiplus` (`cjkfonts` optional)

    If installation of `gdiplus` failed due to hash mismatch, download the file (Windows 7 Service Pack 1) manually on [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB976932), then move/copy the file to `~/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe` or wherever winetricks expects the file to be. Then `winetricks gdiplus` to continue the installation.

## Osu

1. Launch osu! [20201110](https://osu.ppy.sh/home/changelog/stable40/20201110) normally through: `wine '<path_to>/osu!.exe'`

2. Crash will happen during launch as shown on the screenshot above.

# When it Works

## 20201110

1. In addition to wine setup lined out above, perform the following command: `winetricks --force dotnet48`

2. Launch osu! [20201110](https://osu.ppy.sh/home/changelog/stable40/20201110) normally through wine.

3. Crash won't happen.

## 20201102.5

1. Launch osu! [20201102.5](https://osu.ppy.sh/home/changelog/stable40/20201102.5) normally through wine. (I fortunately had a separate copy of osu before the 20201110 update)

2. Crash won't happen.

**Comment by peppy** [comment]
osu! was never made to run under mono. can you confirm it works fine with .net framework?

**Comment by TheComputerGuy96** [comment]
> osu! was never made to run under mono. can you confirm it works fine with .net framework?

They already confirmed that osu! works with .NET Framework

And before that update, osu! worked pretty well with Wine Mono

**Comment by X9VoiD** [comment]
Yes, TheComputerGuy96 is correct. The last update broke on wine-mono, it was working before the update.

**Comment by peppy** [comment]
Thanks for the confirmation. Please use .NET framework

**Comment by aspenluxxxy** [comment]
.NET Framework is inferior, though.

**Comment by peppy** [comment]
@aspenluxxxy I'm not sure where this opinion comes from, but as the primary developer of osu! and someone with decades of .NET experience, this is simply not true.

We never have supported mono and it's astounding it even works at all. I'd highly recommend avoiding using mono for any online sessions as there's a risk it's doing things in a completely different way to normal .NET (we experience this with things like difficulty calculation in the past).
