### ISSUE TITLE
Game crashes in multiplayer when using FL in osu!catch mode

### ISSUE THREAD

**Issue by Janaijanai** [ppy/osu-stable-issues#594]
so i tested all modes ( osu,taiko,mania and Ctb ) with all mod combinations and the issue only occur when FL is added here is some infos:
- the issue doesn't occur in other modes but only in osu!catch
- it Doesn't occur in solo mode 
- it Doesn't occur if the "ignore beatmaps skin" was already activated from options 
- the issue  only occurs after adding or playing with FL in multiplayer and trying to ignore beatmap skin manually from "visual options" just before map starts 
(Game close itself and reopen again)

**Comment by peppy** [comment]
Could you please include log files after you made it crash (before restarting osu!, grab runtime.log from your osu! folder)?

**Comment by Janaijanai** [comment]
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5544078/runtime.log)
i hope this is the file you meant, but it seems i can't grab the file before restarting osu since it starts automatically after it crashes ...

**Comment by peppy** [comment]
Unfortunately that's not showing the crash. Could you click on the pippi character on the crash screen when it appears, then hit ctrl-c to copy the log from there (and past here)?

**Comment by Janaijanai** [comment]
apparently its not the crash screen which generates after the crash but osu!updater instead ( so there is no pippi to click ) ??

**Comment by peppy** [comment]
That's a *very* weird crash. Thanks for the video, I'll try and reproduce this locally.

**Comment by TobiasLeander** [comment]
Can't seem to reproduce this could u try going to event viewer and check if there are any crash logs there? if u don't know how to [follow this guide](https://osu.ppy.sh/community/forums/topics/638421?start=6231904).

**Comment by Joehuu** [comment]
FWIW, I can also reproduce with the details in the OP. Can't seem to find anything of concern in event viewer, though.

**Comment by Janaijanai** [comment]
> Can't seem to reproduce this could u try going to event viewer and check if there are any crash logs there? if u don't know how to [follow this guide](https://osu.ppy.sh/community/forums/topics/638421?start=6231904).

i followed those steps but i think it registered nothing it shows this panel instead: 
![kkk](https://user-images.githubusercontent.com/74438696/99341712-51e8c180-2882-11eb-9844-68111133c3ec.png)

**Comment by peppy** [comment]
This should be fixed in the latest cutting edge release, please confirm.

**Comment by Janaijanai** [comment]
im really Sorry since i don't have a supporter tag,  i couldn't use multiplayer in cutting edge to confirm ... but since Joehuu could reproduce it from details i provided, i think he can test it out and confirm too :(

**Comment by Joehuu** [comment]
> This should be fixed in the latest cutting edge release, please confirm.

Yep, cannot reproduce anymore.

**Comment by Janaijanai** [comment]
Cool !!

**Comment by Janaijanai** [comment]
well i can confirm from my side too, finally !!
