### ISSUE TITLE
Images Not Displaying, Grades Not Displaying, PP not given on ranked passes (with wifi), Doesn't display the tracker for when I press a key

### ISSUE THREAD

**Issue by wofflss** [ppy/osu-stable-issues#595]
One day I loaded up osu! to come to songs not having an image right next to the title or my best play/grade (or both of these issues)
Example:  ![image](https://user-images.githubusercontent.com/74570199/99316900-22f72f00-2833-11eb-9241-bdfaab2a6ef8.png)

As for PP not given, I would play a whole song and not have the amount of pp I would've earned for passing the song to load which this had happened a few days after.
Video Example: https://www.youtube.com/watch?v=QACyZiq6Yo0&ab_channel=VincentTai
Song: https://osu.ppy.sh/beatmapsets/56633#osu/171126
The Video had also shown the last problem where the key tracker wouldn't or appear and only for replays.

Note: I am aware that there are songs that do not comply with the problems listed but it still doesn't really fix the others that do align with these problems. The only reason I could think of why they have pictures and grades shown is that I had played them but that is too much work to play every song and it doesn't work all the time so there is that.

**Comment by peppy** [comment]
sorry but there's nothing actionable in this bug report. you may be better off posting to the help / tech support forum. sounds like a network issue at your end (or something between you and the osu! server)
