### ISSUE TITLE
osu!direct thinks that map exist when it doesnt

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-stable-issues#596]
[This](https://osu.ppy.sh/beatmapsets/546878#osu/1158325) map breaks osu!direct for me.

Video: https://www.youtube.com/watch?v=2dCPCowc90Y

**Comment by peppy** [comment]
This works fine for me, so I'd say it's likely an issue with your local beatmaps. You should probably just try deleting the beatmap in question and redownloading it.
