### ISSUE TITLE
Random input that freezes chosen beatmap on menu

### ISSUE THREAD

**Issue by minhperry** [ppy/osu-stable-issues#597]
When I'm rolling between beatmaps this might have a chance to happen. The focused beatmap will shake like crazy. The sound of you moving the cursor between beatmaps will be repeatedly play. Mouse Right click wont work because it will always focus at the beatmap that's playing.

**Comment by minhperry** [comment]
Edit: Happens when I switch from Chrome to already opening osu window in Windowed mode

**Comment by minhperry** [comment]
Edit 2: Happens when I lose focus on osu with Windows key then switch back to it

**Comment by peppy** [comment]
We can't work with this report. Need logs / video / something to go by.

Sounds like something on your system outside of osu!, though.

**Comment by minhperry** [comment]
I'll try to upload a video

**Comment by minhperry** [comment]
Apparently it went away when I restart my computer so I'll reopen when it comes back
