### ISSUE TITLE
Tintable Sliber balls dont function as originally intended

### ISSUE THREAD

**Issue by RBRat3** [ppy/osu-stable-issues#599]
The reason for color-able slider balls was to be a user friendly way of coloring a slider ball without the need for editing or recreating the ball sprite but currently only works to serve combo colors which was only suppose to be a bonus.

Users currently cannot choose a fixed color of the primary and secondary sprites via skin.ini config nor load custom textures for  sprites slider-nd, slider-spec with the existence of a sliderb#.png in their skin directory, with the absence of sliderb#.png they'll be loaded but with the internal resource used for sliderb#.png.

Wiki on the skin.ini points out that `SliderBall: R, G, B` under `[Colours]` to color the primary sprite is an option but upon looking through an old backup of the stable repository code that config option doesn't seem to exist nor can I get it to work with the current build.  >https://osu.ppy.sh/help/wiki/Skinning/skin.ini#latest

Ideally with `AllowSliderBallTint:1` it should enable loading custom sprites for slider-nd.png and slider-spec.png whilst being able to choose a `SliderBall: R ,G ,B` for a primary color (Sliderb.png) and `SliderBallSecondary: R, G, B` for secondary color (sliderb-nd.png). With the absence of color values for either should default to combo colors for the primary and generated contrast color for the secondary. This shouldn't require any new skin versioning....

I setup a test bed skin for this: https://puu.sh/GOQ89/2cacbc013b.osk

Final result should resemble this
![SliderFinal](https://user-images.githubusercontent.com/13491985/99577192-fd8c3180-29a8-11eb-975d-1105cfaddb5f.png)

**Comment by smoogipoo** [comment]
Please make an issue on https://github.com/ppy/osu for addition in lazer. Stable is feature-locked.
