### ISSUE TITLE
AiMod adding nodes to specific sliders

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#6]
Repost of https://osu.ppy.sh/community/forums/topics/766878

If two or more slider heads are perfectly stacked and there are **unsaved changes** in the editor, opening and/or refreshing AiMod will add nodes to the sliders. The changes in the nodes will not be visible on the slider body until the map is saved and reloaded.

This will happen anywhere it applies in the map, meaning a mapper could make changes to a totally different section, and not know AiMod is ruining one of the others. It is a concerning issue because it makes using AiMod risky, it can cause changes in a map that the mapper and modders would be totally unaware of.

Video link: https://www.youtube.com/watch?v=2qGC1ZOK3tA

Before
![image](https://user-images.githubusercontent.com/33286824/65243767-02a8d480-dab7-11e9-867e-3c1b2fd6e4f4.png)
After opening and refreshing AiMod
![image](https://user-images.githubusercontent.com/33286824/65243872-4b608d80-dab7-11e9-9fef-26f21cbf13d7.png)
After saving and reloading the map
![image](https://user-images.githubusercontent.com/33286824/65243888-55828c00-dab7-11e9-99d9-8b493e0e72b0.png)

**Comment by peppy** [comment]
Will look into this one. Very weird and should be a simple fix.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
