### ISSUE TITLE
Failed Scores in Multiplayer do not get submitted

### ISSUE THREAD

**Issue by DatVeno** [ppy/osu-stable-issues#602]
When you fail in multiplayer it doesnt submit the score at all which leads to playcount, playtime, etc not being updated.

**Comment by peppy** [comment]
Is anyone able to confirm whether this is still an issue?

**Comment by smoogipoo** [comment]
Yes, this is still an issue that I confirmed last week.

**Comment by peppy** [comment]
This should be fixed in the next cutting edge release.
