### ISSUE TITLE
False ranking on the Local Leaderboard

### ISSUE THREAD

**Issue by s1rcheese** [ppy/osu-stable-issues#603]
Steps to do this bug:
1. Play a beatmap with the leaderboard being displayed to global.
2. After playing the beatmap, play the exact same beatmap again with the leaderboard being set to local.
3. You can see that your second top play (with your leaderboard set to local and while still playing the beatmap) has the same ranking as your top play on the global leaderboard.

Version:
Stable 20201126 but I have found this same bug in older versions of the game

A video:
https://youtu.be/owjObgrGO3M
(I think I have some pictures as well but forgot where they are)

**Comment by peppy** [comment]
I have no idea what is going on in that video.

Can you explain what you are seeing and where?
