### ISSUE TITLE
Incorrect hitsounds used under specific conditions.

### ISSUE THREAD

**Issue by wmpmiles** [ppy/osu-stable-issues#605]
When:

- My USB DAC (no custom driver) is selected as the sound output in osu!, rather than the default device (which is the same DAC)
- The USB DAC is configured as 24-bit / 48000 Hz as default
- "Ignore all beatmap skins" and "Use skin's sound samples" are enabled

The default hitsounds are used rather than the skin's custom hitsounds.

If I change the USB DAC to be configure as 24-bit / 44100 Hz as default, or select the default device rather than explicitly selecting the DAC in osu! this problem no longer occurs.

The custom hitsounds are all 16-bit / 44100 Hz WAV as far as I can tell.

**Comment by peppy** [comment]
This sounds like a hardware or software issue. If you can reproduce some issue on lazer then please report there, but my recommendation would be to run at 44.1khz as you will get no benefit from running higher.

**Comment by wmpmiles** [comment]
Is there supposed to be any internal difference between selecting the default device and the device that is the default device in the client? That's where the issue is occuring.

**Comment by peppy** [comment]
No

**Comment by wmpmiles** [comment]
Would a video or further information be worth providing?

**Comment by peppy** [comment]
No. We don't have the resources to fix fringe issues like this sorry.

If you can reproduce in lazer, then we may look into it further there.
