### ISSUE TITLE
Cannot toggle ingame overlay when leaderboard toggle is set to a numpad key

### ISSUE THREAD

**Issue by n-word-osu** [ppy/osu-stable-issues#606]
If I bind my leaderboard toggle key to a numpad key, I cannot toggle ingame overlay. Either a fix where I can use Shift+Numpad Key or an addition of being able to bind toggle ingame overlay to a completely separate key would be nice, this effects me very frequently because if I want to toggle ingame overlay I have to change bind for lb toggle, toggle ingame overlay, change bind again, so I would like if this could be fixed in stable

**Comment by peppy** [comment]
I'd recommend binding it to something else. We don't have the resources to fix something like this sorry.
