### ISSUE TITLE
Compatibility mode accessibility on new install

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-stable-issues#607]
IIRC, there is a "compatibility mode" which made use of DirectX instead of OpenGL. To enable compatibility mode, the user must open the game and change it in the setting, or edit the user config file.
But for the old computers that don't have driver support for OpenGL, osu! can't even run. Since osu! doesn't run, no user config file is generated, so the user also can't just edit the config file (they have to copy it from a functional osu! install).

**Comment by peppy** [comment]
It automatically tries running in compatibility if opengl fails. Care to provide more actionable detail? Have you actually reproduced a fail on install which was fixable by changing config?

**Comment by huupoke12** [comment]
Changing config also doesn't fix it on my test setup. I reported this since stable fallback can run on my test setup but stable can't, I thought it was because stable doesn't start with DirectX.

**Comment by peppy** [comment]
Aha, I see.

stable-fallback has a very different directx implementation. we're hoping to bring something similar back in lazer.
