### ISSUE TITLE
Multiplayer doesn't work with autopilot.

### ISSUE THREAD

**Issue by Waveium** [ppy/osu-stable-issues#609]
When playing [https://osu.ppy.sh/beatmapsets/5807#osu/27638] this(url) Map in tag coop, on autopilot it doesn't aim at all. it only does spinners and when you tap with z and x it doesnt work even when aiming to the notes, (i know what autopilot does) version's it happens on are all versions that can still do multiplayer.

**Comment by peppy** [comment]
If this is specific to one beatmap, and tag coop, it is likely out of scope to fix.

We'll definitely make sure tag coop has better support in lazer!
