### ISSUE TITLE
Add option to only use beatmap's combo colors

### ISSUE THREAD

**Issue by willyosu** [ppy/osu-stable-issues#61]
Pretty self-explanatory; the only way currently to use a custom skin while retaining a beatmap's combo colors is to use the whole beatmap skin with the `Ignore beatmap skins` option unticked, but many people would like to just use the combo colors from it and not any other elements that would override parts of their custom skin.
This may be too much effort, but I just hope that this can finally get implemented at some point in either stable, CE, or lazer.

**Comment by smoogipoo** [comment]
Will probably happen in lazer, not worth the implementation complexity for stable.
