### ISSUE TITLE
Black screen when running alt + tab and returning to the game with graphics compatibility mode active and in full screen and chat opened.

### ISSUE THREAD

**Issue by PauloRicardoDeveloper** [ppy/osu-stable-issues#610]
# When I alt + tab my game and go back to my game the game will have a black screen as seen in video 1.0
## I can return to play
I can return to the game using alt + f4 and open the game again, or wait a while, press alt + tab again and reopen the osu window.

## Pc configs
- Windows 8.1 64-Bit (6.3.9600) (The same happens in all versions of windows 10)
- 4gb ram
- 500mb of vram and a gpu compatible with opengl 3.0
- Core 2 Quad T5750

## Osu version
- Stable 20201126

**Comment by peppy** [comment]
This isn't going to be something we can fix, and likely an OS, software or driver issue. My only suggestion is to either avoid the issue happening in the first place (by changing your run configuration) or updating/downgrading windows and or drivers until you find a workaround.

**Comment by PauloRicardoDeveloper** [comment]
Thanks for the answer! I will try. Good night.
