### ISSUE TITLE
[Proposal] Increase flashlight scorev2 multiplier to 1.2

### ISSUE THREAD

**Issue by Purplegaze** [ppy/osu-stable-issues#611]
This doesn't involve implementing a new feature so I hope it's okay to post here.

Currently scorev2 changes score multipliers from what they are in v1, with HR being increased to 1.1 to value it above HD, and DT being increased to 1.2, to value it above HDHR.

HDHR's multiplier is 1.17, which is greater than the 1.12 that FL keeps from scorev1. In a tournament, which is currently where almost all of v2's use is in, it's generally more impressive to get an FL score (where FL is allowed in freemod) than HDHR. FL is very rarely used in tournament freemod picks due to how risky it is but in [the rare case that it is](https://www.twitch.tv/usa_states_cup_osu/clip/AlertBoredKuduWOOP) I feel like it should be rewarded by default at least as much as it is in solo play without the need of tournament organizers adding another multiplier for it.

Personally I believe DT and FL score multipliers should always be equal. Having them equal is nice in scorev1 because it gives people a different opportunity to get leaderboard scores on maps they really like even if they can't DT them, and increasing DT above FL would completely destroy the FL leaderboard community for everything except for HDDTHRFL plays. Scorev2 isn't used for any leaderboards, but this makes setting it to 1.2 make sense rather than having it be some arbitrary value.

**Comment by peppy** [comment]
This is not the correct place for discussions like this. We are currently in the midst of rewriting the game and there are performance and difficulty calculation changes ongoing, so I don't think we will be considering multiplier changes that have been set in stone for a decade or more.

**Comment by Purplegaze** [comment]
This isn't a multiplier change that has been set in stone for a decade though, v2 is relatively new compared to v1 and it's being actively used in the tournament scene and not for ranking

**Comment by peppy** [comment]
Sorry, missed the v2 part.

I'd say you should open a forum thread to discuss this, especially with the tournament scene. Github is not suited to such discussions.

**Comment by Purplegaze** [comment]
Alright, I'll do that. Apologies for misunderstanding how to go about proposing things that should require discussion
