### ISSUE TITLE
Beatmap database keeps corrupting

### ISSUE THREAD

**Issue by 02Naitsirk** [ppy/osu-stable-issues#613]
Fourth time this has happened this last 2 weeks, and it happened 3 times last week. No idea how to reproduce. I am using the latest version of osu stable on OS X. I have 14k beatmaps, and after corruption only 2k show.

![Screen Shot 2020-11-22 at 6 33 11 PM](https://user-images.githubusercontent.com/57512128/101216895-5537c780-364e-11eb-8bdf-31e4b23151e1.png)

osu.db and backuop osu.dbs: http://www.mediafire.com/file/d6erjqmovm1hfgo/Archive.zip/file

**Comment by peppy** [comment]
are you exiting the game using cmd-q or similar? is recommend using the exit button from the main menu and see if it helps.

**Comment by 02Naitsirk** [comment]
I am exiting normally.

**Comment by 02Naitsirk** [comment]
Happened once again today.

**Comment by peppy** [comment]
We can't support edge cases like wine, sorry. The next major update will bring native (reliable) support to your OS.
