### ISSUE TITLE
Game starts from middle of beatmap

### ISSUE THREAD

**Issue by harshavb** [ppy/osu-stable-issues#616]
Video link [here](https://www.youtube.com/watch?v=tDmvMts8I4o)
Explanation: Upon retrying the map, the map began in the middle of the map rather than the beginning. This happened with both quick retry and clicking the retry button in the fail screen. Leaving the map and replaying did not fix it. Picking another map in the mapset resulted in the same issue. Picking a map from a different mapset and then picking the map from the broken mapset fixed the issue. Note that I actually could hit a note right before I failed. I am not sure what caused the issue.

[runtime.log](https://github.com/ppy/osu-stable-issues/files/5669051/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/5669052/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/5669053/update_success.log)

**Comment by peppy** [comment]
You're going to need to link or upload the beatmap. It looks like it may be an issue with your audio playback, or something local to the beatmap causing the issue. The fact that there's no music playing is an issue.

**Comment by harshavb** [comment]
The beatmap is available [here](https://osu.ppy.sh/beatmapsets/450340#osu/966203).

**Comment by peppy** [comment]
Can't reproduce. Does this happen every time you play the map? And on no other maps? Have you tried re-downloading the map?

**Comment by harshavb** [comment]
It's only ever happened once.

**Comment by peppy** [comment]
Okay, safe to ignore then.
