### ISSUE TITLE
Game crashes when logging out without internet

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#618]
My wifi goes out at 10pm and osu keeps telling me that it is trying to connect which gets annoying after like an hour so I wanted to sign out and the game crashed

**Comment by peppy** [comment]
Please attach logs.

**Comment by WinterIsPretty** [comment]
I guess I was unlucky cuz I can't make it happen again... weird

Also when you want logs do you want all the files in the logs folder? I want to know for another time maybe

**Comment by peppy** [comment]
Yes, next time it happens please include the content of the logs folder, along with any other details (if it was a hard crash you can hit ctrl+c at the crash dialog to copy the full crash diagnostics, for instance).

Make sure to do this before restarting osu!, as the logs will get reset on restart.

**Comment by WinterIsPretty** [comment]
I finally got it to happen again
idk why this happens but I got the logs for what I need

[update_success.log](https://github.com/ppy/osu-stable-issues/files/5824909/update_success.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5824910/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/5824911/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/5824912/update.log)

**Comment by WinterIsPretty** [comment]
How do I look at the event viewer and can I look back 2 months
