### ISSUE TITLE
osu! crashes when pressing alt in the editor.

### ISSUE THREAD

**Issue by MiningRocky** [ppy/osu-stable-issues#619]
osu! crashes whenever I press alt in the editor and just the editor. I don't know whether it's because of the distance snap spacing slider in the top right that appears whenever you press alt, but it's super annoying because I'm trying to alt-tab out to go to like mapping tools or something and it just closes the game with no error messages. I've tried this on cutting-edge and also tried using compatibility mode and it does the same thing except with compatibility mode it makes the game hang for a few seconds and then I have to use task manager.

**Comment by peppy** [comment]
Are you running windowed? If not, run windowed.

**Comment by peppy** [comment]
Please leave a comment if you can reproduce this when not running full screen. Full screen support in the editor can be flaky (especially with recent nvidia drivers). We have resolved this in lazer already.

**Comment by MiningRocky** [comment]
It does still close even when in windowed mode.

**Comment by MiningRocky** [comment]
Oh my gosh i just noticed that it only happens with a certain map

**Comment by MiningRocky** [comment]
Ok i've just looked at the .osu file and for some reason the DistanceSpacing is NaN so i'm pretty sure that was it.

I've just tried and yes that was it, i should probably rename the issue then.

**Comment by peppy** [comment]
nice deduction
