### ISSUE TITLE
Unable to view all collections

### ISSUE THREAD

**Issue by Timowoof** [ppy/osu-stable-issues#62]
Main menu screen > Jump to window (3 bars on the top right) > Jump to... Collections:
I have a lot of collections which makes me unable to view all of them due to the way the drop down is formatted
![image](https://user-images.githubusercontent.com/11276247/65307136-fca90700-db3b-11e9-9223-68b33ac8bcff.png)

**Comment by smoogipoo** [comment]
This is actually quite involved to do since dropdowns don't have the capability of scrolling/having a limited height.
