### ISSUE TITLE
Taiko bar and monitor hz

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#620]
I know many people who complain they can't play taiko because they have 60hz or any minor lag makes the game almost unplayable, but I know one way we can fix most of this.

https://cdn.discordapp.com/attachments/592619590433898497/788389235807617064/20201215_065201.mp4

We need a section in the skin.ini for taiko to move the taiko bar vertically because there are only one or two spots on my screen this happens on and it mainly only happens at the exact spot taiko is.

I hope this isn't too much. This problem has been pushing people away from taiko unless they have a good pc or a monitor with a high refresh rate.

**Comment by peppy** [comment]
Turn on vsync.

**Comment by WinterIsPretty** [comment]
you cannot play taiko with vsync your offset goes up to over 200ms and there is a huge visual offset

**Comment by peppy** [comment]
Great.
