### ISSUE TITLE
White flashes with "Shaders" option enabled on Mesa drivers

### ISSUE THREAD

**Issue by TheComputerGuy96** [ppy/osu-stable-issues#621]
### System information

- OS: Arch Linux
- GPU: AMD Renoir (the iGPU in my Ryzen 5 4600H)/GTX 1650 Ti
- Kernel version: 5.9.14-arch1-1
- Mesa version: 20.3.0
- Desktop manager and compositor: GDM/GNOME 3.38.2

I run the game on Linux with wine 4.13/wine-staging 5.22 and dotnet40/gdiplus winetricks

### Describe the issue

When I enable the "Shaders" option in osu! settings, there are white screen flashes instead of effects (those effects seem to be used when flipping between certain menus and sometimes when playing a map)

This issue occurs with the default radeonsi OpenGL Mesa driver for my GPU and even llvmpipe on Windows (so I doubt it's a Wine issue)

I can't try nouveau because it caused crashes on my GPU

Using the NVIDIA binary driver and my GTX 1650 Ti instead of radeonsi and my AMD IGPU on Linux solves this issue

### Apitrace

https://drive.google.com/file/d/12fivh4Jp1b_vaLcc6Efftpw3j1urAtaz/view

Note: The white flashes are visible in the trace (at least with radeonsi driver on Linux)

### Screenshots/video files (if applicable)

https://youtu.be/37PGaJUGzqs

I already submitted [the issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3978) to Mesa's bug tracker, but I'll try posting this issue here just in case if this is a game bug

**Comment by tadeokondrak** [comment]
Note: the fragment shader fails to compile with this error
```
1147912: message: major shader compiler error 2: 0:23(27): error: array constructors forbidden in GLSL 1.10 (GLSL 1.20 or GLSL ES 3.00 required)
1147912: message: major shader compiler error 3: 0:23(27): error: initializer of const variable `offsets' must be a constant expression
1147912: warning: compilation failed
1147912: warning: 0:23(27): error: array constructors forbidden in GLSL 1.10 (GLSL 1.20 or GLSL ES 3.00 required)
0:23(27): error: initializer of const variable `offsets' must be a constant expression
```

**Comment by peppy** [comment]
Thanks for the report, but we simply cannot support wine.

If you can reproduce the issue in lazer then we can definitely investigate further.
