### ISSUE TITLE
NightCore sounds ignore offsets

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu-stable-issues#622]
repro: play any map (i recommend [peppys offset wizard](https://osu.ppy.sh/beatmapsets/4659#osu/)) with NC and hear how music/NCsounds desynchronize more and more the further you change local or global offset.

**Comment by peppy** [comment]
That is... the whole point of setting the offset. I understand you may be using the universal offset for input delays, but that is not its purpose. It is there to synchronise sample and track playback.

**Comment by LastExceed** [comment]
> I understand you may be using the universal offset for input delays

I believe there is a misunderstanding here. I'm not talking about hitsounds, but about the metronome-like sounds built into the NightCore mod. You can hear the desync between music and NC sounds without performing any inputs at all

**Comment by peppy** [comment]
That is correct. That's what UO is there for.

**Comment by LastExceed** [comment]
oh, that is unexpected. If this option is only for aligning track and samples, then what is the correct way to deal with audio latency ?

**Comment by peppy** [comment]
I think you are confused beyond a level I can help with here sorry. This *is* dealing with audio latency. It is *not* dealing with input or display latency.

You can tell apart what needs fixing by *using the offset wizard to set your UO once, and only once*.
