### ISSUE TITLE
Problem rendering sliders with the game at 1360x765

### ISSUE THREAD

**Issue by PauloRicardoDeveloper** [ppy/osu-stable-issues#623]
## Description
When I try to run my game at 1360x765 it doesn't render the slider tracks.
I tested on 3 computers and the same error occurred... All of them with a GTX 1050.

## Steps to reproduce
1. Set the display resolution n windows configs to 1360x765
2. Open the osu!
3. Try to play a map

## Pc configs
- Ryzen 7 2700
- GTX 1050
- 1x 8GB Ram
- _Osu version: Stable 20201210.2_

## Screenshots
<img src="https://up.ppy.sh/files/screenshot821-1.png"/>

**Comment by peppy** [comment]
There's nothing to work with here. The screenshot and provided information is useless.

**Comment by PauloRicardoDeveloper** [comment]
i can record a video @peppy.

**Comment by smoogipoo** [comment]
Is there a reason you're running at such a resolution, and not the more common 1366x768?

Are your drivers up to date?

**Comment by PauloRicardoDeveloper** [comment]
> Is there a reason you're running at such a resolution, and not the more common 1366x768?
> 
> Are your drivers up to date?

Yes, with 1360x768 works.

**Comment by peppy** [comment]
As expected, it works fine here.

**Comment by Sebola3461** [comment]
@peppy try running at 75hz

**Comment by peppy** [comment]
That's not going to change anything, sorry.

**Comment by Sebola3461** [comment]
oki, thx.
