### ISSUE TITLE
osu multi bug

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#624]
if you kick someone many times and they keep joining back you get glitched to the point where it thinks your in a lobby but you are not so when you play maps you can't reset or leave unless you die 

if you join another mutli it thinks you are in the middle of a match

**Comment by peppy** [comment]
This doesn't sound actionable without some kind of reproduction. Please make a video or similar showing this in practice.

**Comment by WinterIsPretty** [comment]
Could just be a communication error between computers when sending things at the same time. Also cannot send any video of multi until May 1 anyways.
