### ISSUE TITLE
All osu maps under 4.99 stars have disappeared 

### ISSUE THREAD

**Issue by koyaaaa** [ppy/osu-stable-issues#625]
I've reset any sorting, and i've restarted the game and the computer multiple times. this has happened for around a month. When i try to download a map under 4.99 stars it will let me play it at first, but then it disappears once i choose a different map, with only the 4.99+ difficulty remaining. i'm sorry if this is something on my part, (possibly i just clicked something wrong to make it do this) but i cant seem to find a solution to this. Thank you!

**Comment by peppy** [comment]
In settings, disable the difficulty filter.

**Comment by koyaaaa** [comment]
That worked! super sorry for the hassle
