### ISSUE TITLE
Game input latency increased upon spamming lots of keys

### ISSUE THREAD

**Issue by usagi123** [ppy/osu-stable-issues#626]
The whole game literally freezes when I spam 10 fingers at the same time constantly https://streamable.com/634oue
The problem is only occur when I running it with PrprLive. However, PrprLive does not causing problem like this with other tested games (R6 Siege, GTA V, Dota2). 
The problem is less prominent on lazer but it seems still there if I input more than 2 normal keys for standard. The shutter is not that bad compared to stable https://streamable.com/iibeud

**Comment by peppy** [comment]
This is due to something else, not osu!. We can't solve this sorry.

Also lazer does not look affected in your videos.
