### ISSUE TITLE
Autoplay gets only 471SPM if the previous hit object is inside the spinner

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu-stable-issues#627]
Notice the behavior of the last 3 spinners

https://user-images.githubusercontent.com/50285552/103166593-a0fd1b80-485e-11eb-8f01-71569066a1dd.mp4

**Comment by peppy** [comment]
Is this important? It goes against the ranking criteria, right?

**Comment by Magnus-Cosmos** [comment]
I don't think there's anything in ranking criteria that says you can't place hitobjects near the center before a spinner. There's a lot of ranked beatmaps where this phenomenon happens (and probably related to this, Auto does something similar when using HT for any spinner, regardless of what's before it).

**Comment by peppy** [comment]
Since this is only on autoplay, I don't think it's high enough priority to be considered for fixing on stable. That said, if you are able to reproduce the behaviour on lazer we'd be happy to look into it.
