### ISSUE TITLE
Creating a new difficulty without giving it a name and then clearing all objects clears the original difficulty

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu-stable-issues#628]
steps to reproduce:

1. open a diff
2. create new diff
3. don't name the new diff and press ok
4. clear all objects
5. original diff nuked

**Comment by smoogipoo** [comment]
I don't see this being fixed. osu-stable works with non-unique file names.

**Comment by peppy** [comment]
We can probably prevent this from happening by disallowing empty difficulty names. Might be worth doing to prevent disaster (loss of user data).

**Comment by peppy** [comment]
This should be fixed on cutting edge (the OK button will now be disabled until the fields are filled in).
