### ISSUE TITLE
Hide keys overlay while watching replay and spectator mode

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-stable-issues#629]
it will be nice to have option to disable keys overlay while replay and spectator mode
because rn im working on my "pp" counter and i needed to hide this overlay
reason: https://youtu.be/wGhPKQ7j4TI

**Comment by peppy** [comment]
We can potentially add this in lazer (please open an issue there if this interests you). in stable you will need to use shift-tab to hide everything.

**Comment by cyperdark** [comment]
shift-tab hide everything except keys overlay (in replay and spectator mode)

https://user-images.githubusercontent.com/21735205/103404873-157cd680-4b4d-11eb-8ca1-e005ccaf4c7d.mp4
