### ISSUE TITLE
Change framelimiter options to refresh-based

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-stable-issues#63]
The game only has VSync, 120 and 240fps framelimiters by default without tinkering with config files ; adding a slider to set the limiter to something like like 480 or anything in between (a reasonable range probably being 60-1000, based on the input tickrate of lazer) could help

Additionally, lazer uses refreshrate multiples instead of hard limits like these ; if a slider is not a viable option, maybe switching to a refreshrate based limited system would work

**Comment by nl-tatatat** [comment]
any reason.. why?

**Comment by smoogipoo** [comment]
These options were added before 144Hz and 240Hz displays were really a thing, and we should definitely move to a refresh-based framelimiter. Slider's not gonna happen.

**Comment by Jeremiidesu** [comment]
> any reason.. why this is an issue?
I use a 289fps frame limiter (2x 144Hz Vsync + 1fps)

**Comment by smoogipoo** [comment]
Because it's unnecessary and unintuitive. Why would one need to run at 888fps vs 887fps? If you absolutely 100% need that sort of flexibility you can edit the config files yourself.

**Comment by peppy** [comment]
I'd suggest we consider adding 2x, 4x and 8x refresh rate and remove unlimited completely. It will solve many performance issues caused by people incorrectly rendering thousands of frames.

**Comment by smoogipoo** [comment]
That's 2ms latency at 60Hz, what I and many other/most people play at. For lazer that works, but we need a 1000fps limiter at the least.

**Comment by nl-tatatat** [comment]
I and many other exclusively use Unlimited because otherwise you get screen tearing.

**Comment by Karoo13** [comment]
since some physics operations are quantized to 1ms intervals, I prefer to use 200, 250, 334, 500, 1000 fps rather than multiples of monitor framerate, just a thought.

**Comment by peppy** [comment]
@nl-tatatat that can likely be solved by using a multiple of the frame rate, as i suggested.

@Karoo13 i have no idea what you mean by "physics operations" being "quantized". are you talking about a different game?

**Comment by nautzz** [comment]
How about just adding a "custom" option, and adding a slider or something to the options menu?

You can already set a custom framerate in the config file, would essentially just be letting you adjust that with greater ease.

**Comment by peppy** [comment]
If we are providing more options, it would be options which work well for the game. Locking discussion as unnecessary. We may still address this, but input is not required.

**Comment by peppy** [comment]
Has been done.
