### ISSUE TITLE
Custom combo colors only load if "Ignore all beatmap skins" is unchecked

### ISSUE THREAD

**Issue by huuishuu** [ppy/osu-stable-issues#630]
An extension of #502 (which has never been replied to apparently?)

The game does not bother checking if you have selected "Ignore beatmap skin" when starting a map. If the option "Ignore all beatmap skins" is checked in the options, then the game won't even load custom combo colors, if present.

For this example, I'm using one of my maps with the following combo colors:
![](https://i.imgur.com/10Aiekw.png)

If "Ignore all beatmap skins" is checked in the options:
![](https://i.imgur.com/aEgwHMs.png)

and then "Ignore beatmap skin" is unchecked:
![](https://i.imgur.com/ZLu8CpR.png)

The map does not load custom combo colors:
![](https://i.imgur.com/zUdjpT5.jpeg)

However, if that same option is unchecked in the options:
![](https://i.imgur.com/IQrJ9qs.png)

And, of course, "Ignore beatmap skin" remains unchecked, the map now suddenly loads the custom combo colors:
![](https://i.imgur.com/k7SQdjw.jpeg)

This has been a long-standing issue and searching the Issues page for osu-stable-issues didn't mention anyone else reporting this problem.

**Comment by peppy** [comment]
What is the expected behaviour here? That custom combo colours should ALWAYS be applied even if the user has selected to not use beatmap skins?

I believe the current behaviour is as it is because people asked for it to be this way..

**Comment by venix12** [comment]
I personally think it would be nice to have two options instead, one for disabling custom combo colours and another one for disabling actual skin elements (like custom hitcircles etc.), similar to how skins and hitsounds are treated separately. I believe a lot of people check the current option just to get rid of custom skin elements at the moment.

**Comment by peppy** [comment]
Two options will be added in lazer, but not stable (see https://github.com/ppy/osu/issues/11458). That's not what I'm asking or interested in here. What is the expected behaviour here?

**Comment by huuishuu** [comment]
Since combo colors are treated as being part of the skin, I thought unchecking the option would at least let me see what custom combo colors were selected for the map, especially given how important it seemingly is when trying to rank it (despite not being mentioned in the ranking criteria, it is generally advised by modders to add them otherwise it's considered unrankable for some reason?)

It feels silly to require them, yet have an option that is supposed to enable skin per-map yet have it not affect combo colors, although looking more into it - I can actually find people complaining about combo colors changing with map. Since this will be resolved in osu!lazer, I'll close this myself then.
