### ISSUE TITLE
Allow difficulty settings and stack leniency to be set to any rankable value in the UI.

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#631]
Maps with difficulty settings such as CS10 and stack-leniency 0 can be ranked, but there's no way to set these using the UI alone; they can only be set by editing the .osu file manually. This also leads to weird behavior like if a mapper ever clicks OK in the map setup UI then any values such as stack-leniency 0 will be overwritten with the lowest value that's available in the UI which is 0.2.

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/103544635-c1267d80-4ee3-11eb-8e43-5380d24ace1d.png)

Could you please link where CS10 is allowed?

**Comment by Joehuu** [comment]
Those are guidelines, which means they can be broken. There's also a recent map thats CS 9: https://osu.ppy.sh/beatmapsets/1224369#osu/2546844.

Ref: https://osu.ppy.sh/wiki/en/Ranking_Criteria#general-terms
> Guidelines: Guidelines may be ignored under exceptional circumstances. These exceptional circumstances must be justified by an exhaustive explanation as of why the guideline has been ignored and why not ignoring it will interfere with the overall quality of the creation.

**Comment by iptq** [comment]
Here is a ranked map that's CS10: https://osu.ppy.sh/beatmapsets/1206001#osu/2511210 . The map is rather slow and follows a concept that is enhanced by the circles being so small.

As Joehuu pointed out, guidelines are allowed to be broken if the mapper can make a case for it.

In any case, even if it's not rankable, people should be able to create maps with any CS the client allows using the UI instead of by editing the .osu file manually.

**Comment by ShiiTsuin** [comment]
Circle Size above 7 has been rankable for about half of a year hahahaha https://osu.ppy.sh/home/news/2020-07-02-mappers-report-may-june

**Comment by peppy** [comment]
@iptq i knew you were going to use that argument, which is why i'm considering hard capping the client.

closing this for now as the UI is not being changed.

**Comment by peppy** [comment]
To make this clear since I guess it wasn't obvious from my reply:

The stack leniency change is something we want, and I already made the change for this yesterday. It will be deployed in the next cutting edge release (today or tomorrow).

The circle size change I am not sure about, so am against changing it until we reconsider things with lazer (ie. whether the value will still allow inputs up to CS10 in the first place, since this *wasn't intended*).

**Comment by peppy** [comment]
To fix the UX issue, I'm also going to make the dialog not reset the setting back down for maps that have values set higher. Hopefully this will be enough to tide things over until lazer's editor.
