### ISSUE TITLE
Search query clears after exiting song selection menu

### ISSUE THREAD

**Issue by Kyorie** [ppy/osu-stable-issues#634]
for example, going into the editor and then coming back to the song selection (using a "back" button, not pressing Esc) results in clearing your search query.

The solution is probably to make a toggle in the settings which allows you to leave your search query in the search box until you remove it manually or exit the game

**Comment by peppy** [comment]
I don't believe this will be something we add to stable, due to the complexity involved. It may be something we consider for the next major update, though.
