### ISSUE TITLE
Negative grades awarded on ranking status change

### ISSUE THREAD

**Issue by samuelhklumpers** [ppy/osu-stable-issues#635]
When a map transitions from qualified->ranked, the rank/grade of the second highest score seems to get decremented from a player's grade counts.

This results in:
![negative grades](https://user-images.githubusercontent.com/34067057/104095654-56d15c80-5298-11eb-96c7-e6de0b6e7cbc.png)
on https://osu.ppy.sh/users/10945523
If not mistaken, 9/9 reproductions on 3 different maps and 9 difficulties total succeeded.

This seems to be perfectly reproducible as follows.
Reproduction for -1 silver S:
1. Pick a difficulty of a qualified map
2. Achieve silver S on this difficulty
3. Achieve a higher S or SS on this difficulty
4. Note current grades, wait until the map gets ranked, and observe that the silver S count decreases by 1.

Overwriting with silver SS not tested, but probably gives similar results.
The grades of the overwriting scores were not tracked, thus these may or may not be affected.

**Comment by peppy** [comment]
Yep, this happens. It will eventually resolve itself as we re-sync these numbers on a schedule.

**Comment by Susko3** [comment]
Same issue as https://github.com/ppy/osu-web/issues/7152 and https://github.com/ppy/osu-web/issues/8443. Has been fixed with https://github.com/ppy/osu-web/pull/7996. So this one can be closed as completed.
