### ISSUE TITLE
The Star Difficulty of maps in all modes in the client sometimes differ from what is listed on the website

### ISSUE THREAD

**Issue by Sleepteiner** [ppy/osu-stable-issues#636]
I saw a few other already posted issues similar to this, but this seemed like a larger scope then them, so I thought it might be best to create a new issue. I apologize if I was wrong to think that.

I have found a large amount of ranked maps in all game modes where the star difficulty varies depending on if you are looking at it in the client or the website. This is especially common in catch and mania.

Redownloading the map sometimes fixes the issue, sometimes does nothing, and a few times it did change the SR in-game, but not to the value listed on the website.

The fact that redownloading sometimes works and sometimes doesn't makes me think that this might be a combination of something wrong with my client (maybe because my osu.db is so big and it struggled to recalculate all the maps when the change to calculate all mania key modes at once happened) and something wrong with how certain things are calculated on the website. Just a guess though. I don't really know what I'm talking about with this stuff.

One way to potentially fix the client side of this issue is to add a way for players to recalculate the SR of maps, individually or in groups, without needing to redownload the whole thing, since it isn't always realistic to redownload 100s of mapsets individually.

Here are some examples from each mode:

*Example link* [ client SR | website SR ]

osu!:
https://osu.ppy.sh/beatmapsets/21550#osu/77785 [1.91|1.90]
https://osu.ppy.sh/beatmapsets/1834#osu/17141 [3.55|3.54] (other people said this was the same for them)
https://osu.ppy.sh/beatmapsets/7668#osu/33447 [4.19|4.20]
https://osu.ppy.sh/beatmapsets/1236927#osu/2573162 (This whole mapset is messed up in terms of SR, but it is such a crazy mapset that I think it isn't a big deal if it isn't perfectly consistent.)

taiko:
https://osu.ppy.sh/beatmapsets/1054456#taiko/2212267 [5.06|5.07]
https://osu.ppy.sh/beatmapsets/623924#taiko/1474944 [3.57|3.58]
https://osu.ppy.sh/beatmapsets/383785#taiko/846143 [1.90|2.04]
https://osu.ppy.sh/beatmapsets/383785#taiko/879155 [3.57|3.58]
It is worth noting that I couldn't find any example of this for taiko-only maps, just converts.

catch:
https://osu.ppy.sh/beatmapsets/60214#fruits/180423 [4.58|4.49]
https://osu.ppy.sh/beatmapsets/245906#fruits/658970 [0.99|0.98]
https://osu.ppy.sh/beatmapsets/285577#fruits/647716 [6.09|6.10]

mania:
https://osu.ppy.sh/beatmapsets/756815#mania/1656650 [2.46|2.47]
https://osu.ppy.sh/beatmapsets/30956#mania/112322 [1.07|1.06]
https://osu.ppy.sh/beatmapsets/620076#mania/1306914 [1.42|1.43]
It seems that most mania maps, both convert and mania-only, are actually off by some small amount for me. There might be some huge calculation error in my client. I have all ranked maps downloaded, so redownloading them all is pretty much out of the question, so I'm not sure what do to about this.

This obviously isn't a big or urgent issue, but it messes with my stat keeping, and more importantly it could potentially be a symptom of some larger database or calculation inconsistency.

**Comment by peppy** [comment]
Server-side mania is one version behind client, I believe. We are looking to deploy the changes in the near future, but it hasn't happened yet.

Other issues look like rounding level, apart from maybe one of the taiko cases you mention. @smoogipoo able to check on this one?

**Comment by smoogipoo** [comment]
- (General) Small errors on the range of 0.01* are intentional.
- (osu!, /b/2573162): This is an aspire map. Intentional (lazer employs sane limits on certain beatmap properties).
- (osu!catch, /b/180423): Update/redownload the beatmap, seems fine here.
- (osu!taiko, /b/180423): This is a good find and represents a bug which I'm in the progress of fixing.

**Comment by bdach** [comment]
Make sure to close this one (since I can't do so without perms despite merging the linked PR).

**Comment by smoogipoo** [comment]
The taiko map has been fixed lazer-side, awaiting recalcs to happen.
