### ISSUE TITLE
Dragging movement in editor is sped up if the start of the selection is a spinner

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#638]
If the spinner is the start of the selection, then when you drag notes around it starts "sticking" to the edges of the screen, seems like dragging makes the objects move a lot faster?

You can repro this by making a new map, putting a spinner at the start and a couple notes after it, selecting everything and trying to move it. This also occurs if notes are _before_ the spinner, but if the spinner is still the start of the selection (eg the notes before the spinner are not selected).

Not a big issue, just bothersome if the map starts with a spinner and you're dragging stuff around

**Comment by ramjam18** [comment]
Tried this

Didn't work

**Comment by iptq** [comment]
Maybe you didn't follow the steps correctly? I had multiple people try this and it reproduces every time.

**Comment by peppy** [comment]
Can you provide a video showing this in practice? I can't seem to reproduce at all.

**Comment by iptq** [comment]
https://user-images.githubusercontent.com/1700346/112886702-e288a700-9097-11eb-9315-f62058c580a1.mp4

**Comment by peppy** [comment]
Thanks for the video. The missing detail is that you were moving things around *positionally*. I was only testing on the timeline, because it wasn't clear what you meant.

**Comment by peppy** [comment]
I've fixed this one, but note that it's still not perfect (there will be an initial incorrect offset applied to the drag operation). I'm not willing to put any further effort into it because the fix I made makes moving things usable again, at least.
