### ISSUE TITLE
Have bad osu!mania settings off by default

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#64]
My issue is that the settings:
"Scale osu!mania scroll speed with BPM" and "Remember osu!mania scroll speed per beatmap"
Are defaulted to being on. 

These settings actively work against new mania players hoping to get in the gamemode and get better. Scale osu!mania scroll speed with BPM means that every map a new player plays will have differing scroll speeds, making practice frustratingly hard. "Remember osu!mania scroll speed per beatmap" is basically only useful with the "Scale osu!mania ..." setting. Having it remember your scroll speed per beatmap can be an absolute nightmare. As mania players get better, they tend to increase their scroll speed over time,  If this setting is enabled, every map they once played at a lower scroll speed they will now have to manually adjust to their current preferred scroll speed. 

A vast majority (90+%) of the active mania community recommends these settings to be off and they are generally universally hated. SOME people still use them though, so they should still be in the game, just new players shouldn't have to suffer through it. 

My suggestion is to default to having these settings off, but not change current user's settings. Because of this though, the default scroll speed will also probably have to be raised to somewhere around 10-13 because the "Scale osu!mania scroll speed with BPM" did tend to increase scroll speed.

**Comment by smoogipoo** [comment]
I know we used to/do disagree with what the defaults on these should be. Can we agree that both of these should be disabled by default @peppy ?

**Comment by smoogipoo** [comment]
Fixed in the next release.
