### ISSUE TITLE
Buzzing sound on black screen and then crash

### ISSUE THREAD

**Issue by fuyu78** [ppy/osu-stable-issues#640]
Encountered issue when trying to alt+tab when a map ended (almost results screen), screen goes black and a buzzing noise comes out from headphones and after a few seconds computer restarts itself. I've encountered this issue 6 times since yesterday

**Comment by smoogipoo** [comment]
Sounds like you're running into hardware issues, perhaps a GPU power surge (likely as a result of running at unlimited) or similar. osu! doesn't have the ability to restart your computer.

Could also be a driver issue. The event viewer crash logs should explain the reason to you, but there's nothing we can address here.
