### ISSUE TITLE
DTB Leaderboard Issue

### ISSUE THREAD

**Issue by K3VRAL** [ppy/osu-stable-issues#641]
No clue if anyone has asked about this yet, nor have I seen many discussions about it (apart from complaints) regarding Dodge the Beat and the loved map https://osu.ppy.sh/beatmapsets/1237212#fruits/2571609 . If there has been talk of it, could you please link it? Thanks!

Ever since Aspire, the map space invaders was loved in which the purpose is to dodge as many beats as possible, however, the leaderboard does not really state otherwise as the people who caught the most got the highest on the leaderboard.

Will there be an attempt to change this around for this specific map and/or up incoming dtb maps for the future?

**Comment by peppy** [comment]
If anything, this would be added as a mod in lazer, which can correctly handling reversing scoring.
