### ISSUE TITLE
Custom frame limit only applied in gameplay

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-stable-issues#643]
In osu!tourney, the frame limit (60fps) is no longer applied outside of gameplay.  
![osu!_2021-01-20_16-21-44](https://user-images.githubusercontent.com/4985725/105196491-fc5bba00-5b3b-11eb-83f6-a2e91b4e74bd.png)

I managed to reproduce this outside of osu!tourney by setting:
```
FrameSync = Custom
CustomFrameLimit = 60
```
![osu!_2021-01-20_16-23-08](https://user-images.githubusercontent.com/4985725/105196598-172e2e80-5b3c-11eb-8121-e43f9570b916.png)

Version: b20210105cuttingedge

**Comment by peppy** [comment]
For the record, nothing changed here (it's been bugged in this way since the end of 2019 or earlier). Are you perhaps running a higher refresh rate than previous?

Should be resolved in the next cutting edge release, regardless.

**Comment by peppy** [comment]
Fixed in all released builds

**Comment by ThePooN** [comment]
Not sure to which of my monitor this was wired to. Likely 60Hz.
