### ISSUE TITLE
Osu 3.5 mm jack latency issue 

### ISSUE THREAD

**Issue by 100qtipssss** [ppy/osu-stable-issues#644]
Hi, I have been playing with a Usb-A headset since I started osu. Then I bought a headset with a 3.5 mm headset because my usb ports are full. Then I tried it out for Osu, but i noticed there is a delay between when i press my osu keybinds and the hitsound. I tried my usb headset again and it works just fine. I've also tested with other 3.5 mm devices but its still delayed. Is this just normal with headphones with 3.5 mm jacks or is this a issue with the game? Or maybe its just all in my head. 

ps. I tried changing the offset but theres still a delay

**Comment by peppy** [comment]
This will be either your sound card, drivers or settings.

**Comment by 100qtipssss** [comment]
hi, i changed my sample rate now it works fine. thanks so much for the help :D
