### ISSUE TITLE
Exit replay when fast-fowarding with >2x speed in Cutting Edge cause the audio still speeded up after exiting

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu-stable-issues#645]
As known, we can fast foward more faster in CE than Stable.

Shortcut | Action
-- | --
5 | Pause the replay.
6 or 0 | Resume or set playback speed to 1x.
7 | Set playback speed to 2x.
8 | Set playback speed to 3x.
9 | Set playback speed to 4x.

But when in the fast-fowarding state, hit ESC, and you'll see the audio is still speeded up until you switch to another song

https://user-images.githubusercontent.com/50285552/105503824-04fded00-5d02-11eb-9ef5-cc1ce8a69fdd.mp4

**Comment by l3lackShark** [comment]
I might be mistaken but this was one of the reasons this stable never got this feature (unpolished, stable got feature locked around that time) Correct me if I'm wrong.

**Comment by peppy** [comment]
Yeah, I don't foresee this getting fixed due to it being a niche cutting-edge only feature.
