### ISSUE TITLE
Maximizing issue

### ISSUE THREAD

**Issue by Kikey-y** [ppy/osu-stable-issues#647]
When I'm playing a map and I minimize the game (alt+tab) to check another program, that works fine.
But if I try to maximize it again, it won't let me. It shows up for a split second then disappears each time.
The game is still running and the icon is still on the taskbar, I just can't enter it anymore.

This only happens when you're in-game (playing a map) or in the pause menu. It never happens when you're on the beatmap list.
This only started happening recently so it's probably due to some update so please fix ASAP.

**Comment by peppy** [comment]
This is probably due to some update, yes. An update of the NVIDIA driver or windows. Please provide any further details on the existing issue rather than opening a new one: https://github.com/ppy/osu-stable-issues/issues/323
