### ISSUE TITLE
First timing point on a new map overrides the sampleset

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#65]
Whenever you create a new map, the first timing point you place will automatically set the sampleset to soft, regardless of what you chose in the Song Setup menu. 

Steps to recreate:
1. Create a brand new map.
Optionally change the sampleset to either Normal or Drum in the Song Setup menu
2. Open the timing panel and create a timing point

If you do this (which you'll always do when creating a new map) the first timing point's sampleset will be overidden as Soft. It should be whatever you chose instead.

**Comment by smoogipoo** [comment]
I can't replicate the Soft - it selects Normal for me. Can you provide a video of this?

**Comment by nl-tatatat** [comment]
I think I found where I forgot to mention a step. You have to change the hitsound volume (in the song setup) before you place that first line. Then it will override to soft. Its not even consistently doing it now though.. Sometimes it does, sometimes it doesn't.
However I still encountered it overiding [to normal](https://i.imgur.com/bj9ITgr.mp4) (from drum)

**Comment by smoogipoo** [comment]
Nope I still can't reproduce. This is my process atm: https://streamable.com/au04j

**Comment by smoogipoo** [comment]
Should be fixed in the next cutting edge release. After it's been deployed, let me know if it's still occurring.

**Comment by nl-tatatat** [comment]
An issue with your testing process could be that your mp3 has metadata attached to it, while mine doesn't, so it autofills the metadata in the song setup. I'll see if its fixed in the next cutting edge. Thanks
