### ISSUE TITLE
installer crashes when run from the Download Folder

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-stable-issues#650]
~~Can't think of why it would have to crash just because the executable was renamed.
![](https://i.imgur.com/0orTZaW.png)~~

Actually it seems like my download folder is triggering it. Renaming the FIle itself doesn't fix it. Moving the file makes it work fine. Might have to do with my Download Folder being at `D:\Downloads`? Never had issues with it before

**Comment by peppy** [comment]
osu! thinks you have a full install in your downloads folder (you must have somehow moved all the dlls there or something).
