### ISSUE TITLE
Opening song setup window sets stack leniency <2 back to 2

### ISSUE THREAD

**Issue by Purplegaze** [ppy/osu-stable-issues#652]
Found this while making practice difficulties of a memory-based map that got ranked recently.

I've noticed the stack leniency 2 doesn't apply to objects as it should in this state, so it may be just a display error.

However, it does get applied to objects if instead of opening song setup, you instead create a new difficulty and press "no" to the "would you like to clear all objects" popup (this is what messed up in my practice difficulty)

Version: b20210125.2cuttingedge
to reproduce:
\1. make a map and set stack leniency to 0
2. place down some objects that should stack on leniency 2 but don't on 0
3. open song setup again and it'll display as being set to 2, but the objects still won't stack.
OR
3. go to file > create a new difficulty and press "no" on the "would you like to clear objects" popup. Now leniency should be set to 2 and the objects _do_ stack.

**Comment by peppy** [comment]
Thanks for the report. This will be fixed in the next cutting edge release.
