### ISSUE TITLE
when restarting a map, it bugs out and keeps restarting

### ISSUE THREAD

**Issue by TatttletailHGL** [ppy/osu-stable-issues#653]
it keeps restarting the map even though im not telling it to.. i tried restarting osu, but it doesnt work and im unable to play any maps, and yes, i did install the latest update.

this is kinda hard to explain, so i have a video.
https://youtu.be/CYx1nqdLS5U

**Comment by peppy** [comment]
Something is holding down your quick restart key. Restart your pc or figure out what's causing it.
