### ISSUE TITLE
Game fail at strat

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#655]
ver. ce 20210128
here is the osr file
[cdwcgt - Hanazawa Kana - Renai Circulation [miccoli's Insane] (2021-01-29) Osu.zip](https://github.com/ppy/osu-stable-issues/files/5892824/cdwcgt.-.Hanazawa.Kana.-.Renai.Circulation.miccoli.s.Insane.2021-01-29.Osu.zip)
when I start the game the fail
and quit to select section it seens song is played outside the length range
this seens like the replay do not reappear question.
when issues appera again I will record to video

**Comment by Sebola3461** [comment]
This appears to be a corrupted replay file, try re-exporting the replay pressing f2 in the results screen of this score...

**Comment by cdwcgt** [comment]
> This appears to be a corrupted replay file, try re-exporting the replay pressing f2 in the results screen of this score...

It is the replay I re-output

**Comment by Sebola3461** [comment]
![screenshot942](https://user-images.githubusercontent.com/62405013/107126089-920d7e00-688c-11eb-916d-a52b7dbd00b9.png)
yes, it's a corrupted replay file

**Comment by Sebola3461** [comment]
https://user-images.githubusercontent.com/62405013/107126308-dbaa9880-688d-11eb-8494-933e4c5dd35e.mp4

**Comment by cdwcgt** [comment]
> 2021-02-06_15-12-39.mp4

yes,when I replay my score.That’s it

**Comment by peppy** [comment]
Can you reproduce this kind of behaviour reliably? Or did it just happen once-off for this replay specifically?

**Comment by cdwcgt** [comment]
> Can you reproduce this kind of behaviour reliably? Or did it just happen once-off for this replay specifically?

I tried to reproduce. But this seems to happen suddenly. And it only happened once, and it was normal after I switched beatmapset in select section. The reliable information I can provide is that music will not play on the song selection page when an error occurs and it likes play pointer is outside the song. Before I switch the beatmapset(and play the music normally),it always fail at start

**Comment by peppy** [comment]
Yeah I'm not sure we can really help with this. I can't really understand what you're trying to say. Unless someone is able to pinpoint what is going on here and give further advice I don't think we're going to be able to help you.

If you're experiencing a sound related issue, please try switching devices or changing your windows settings to see if you can find a resolution yourself.
