### ISSUE TITLE
screen is black but everything works.

### ISSUE THREAD

**Issue by bazded** [ppy/osu-stable-issues#656]
yeah. as title says screen is black. even after alt+enter. i was supposed to give runtime.log file
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5893005/runtime.log)

**Comment by smoogipoo** [comment]
Please provide a [dxdiag log](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).

**Comment by smoogipoo** [comment]
As a temporary workaround you can edit your `osu!.<username>.cfg` file and search for + set the following:
```
CanForceOptimusCompatibility = 0
CompatibilityContext = 0
```

**Comment by bazded** [comment]
ok. it works. needed to change CompatibilityContext to 0. do i still need to provide dxdiag log?

**Comment by smoogipoo** [comment]
Yes please. May need you to do some further tests with `CompatibilityContext=1`.

**Comment by bazded** [comment]
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/5894692/DxDiag.txt)
here.

**Comment by smoogipoo** [comment]
can you test the latest cutting edge with `CompatibilityContext=1`?

**Comment by Kawaii-Miku** [comment]
I got the same problem too. When i update my osu and run it. Its all black but i can hear the sound of the game and still works but the screens all black

**Comment by Kawaii-Miku** [comment]
https://drive.google.com/file/d/1AzbcBirHcIDTW1iT_LYwh3ZuUybwG0RV/view?usp=drivesdk

**Comment by Kawaii-Miku** [comment]
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/5897733/DxDiag.txt)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5897734/runtime.log)

**Comment by Kawaii-Miku** [comment]
> can you test the latest cutting edge with `CompatibilityContext=1`?
I Tried cutting edge with CompatibilityContext=1 but still black screen
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5897739/runtime.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/5897740/performance.log)

**Comment by bazded** [comment]
> can you test the latest cutting edge with `CompatibilityContext=1`?

got black again with `CompatibilityContext=1` on cutting edge.

**Comment by Kawaii-Miku** [comment]
I cant play Osu! Without it.

**Comment by soloopooo** [comment]
I've got that trouble too and here is my way to solve:

Try to get into editor mode and back to the main screen (on black screen, push e button twice), and you should be able to see the game ui. And just go back and play.

But when you minimize the game window, it will be back to black again.

This bug happens in when the game resolution doesn't same with the screen resolution.

**Comment by Kawaii-Miku** [comment]
> I've got that trouble too and here is my way to solve:
> 
> Try to get into editor mode and back to the main screen (on black screen, push e button twice), and you should be able to see the game ui. And just go back and play.
> 
> But when you minimize the game window, it will be back to black again.
> 
> This bug happens in when the game is on fullscreen, and the resolution doesn't same with the original screen resolution (maybe).

Bro it doesnt work on me still black

**Comment by soloopooo** [comment]
> > I've got that trouble too and here is my way to solve:
> > Try to get into editor mode and back to the main screen (on black screen, push e button twice), and you should be able to see the game ui. And just go back and play.
> > But when you minimize the game window, it will be back to black again.
> > This bug happens in when the game is on fullscreen, and the resolution doesn't same with the original screen resolution (maybe).
> 
> Bro it doesnt work on me still black

make sure you are on the main menu when you push e button, or try p+e then

**Comment by flopperpopper** [comment]
> > > I've got that trouble too and here is my way to solve:
> > > Try to get into editor mode and back to the main screen (on black screen, push e button twice), and you should be able to see the game ui. And just go back and play.
> > > But when you minimize the game window, it will be back to black again.
> > > This bug happens in when the game is on fullscreen, and the resolution doesn't same with the original screen resolution (maybe).
> > 
> > 
> > Bro it doesnt work on me still black
> 
> make sure you are on the main menu when you push e button, or try p+e then
> 
> I can seriously tell that osu editor's rendering mode is different from main, but i dont know how and why
> 
> and, i tried that on the stable version but not cuttingedge

still doesnt work for me and I have the same problem

**Comment by Kawaii-Miku** [comment]
> > > I've got that trouble too and here is my way to solve:
> > > Try to get into editor mode and back to the main screen (on black screen, push e button twice), and you should be able to see the game ui. And just go back and play.
> > > But when you minimize the game window, it will be back to black again.
> > > This bug happens in when the game is on fullscreen, and the resolution doesn't same with the original screen resolution (maybe).
> > 
> > Bro it doesnt work on me still black
> 
> make sure you are on the main menu when you push e button, or try p+e then
> 
> I can seriously tell that osu editor's rendering mode is different from main, but i dont know how and why
> 
> and, i tried that on the stable version but not cuttingedge

Yeah still doesnt work.

**Comment by peppy** [comment]
I believe the issue causing this has since been rolled back. Feel free to leave a comment if you are still having issues and we'll revisit it.
