### ISSUE TITLE
Not importing maps correctly when I click on the osz file

### ISSUE THREAD

**Issue by LeleGameplay** [ppy/osu-stable-issues#657]
** When I download a beatmap I always click on the osz file to import, after the latest updates even with my osu open when I click on the osz file it opens another osu and it was already open, it doesn't happen at cutting edge
Video: https://www.youtube.com/watch?v=_F_BC7qmmQQ&ab_channel=Lele

**Comment by peppy** [comment]
Your associations are broken. This isn't a place to get technical support though.

You can try repairing permissions or google for further help.
