### ISSUE TITLE
Have countdown settings disabled by default

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#66]
Literally nobody wants countdown enabled in the beatmap settings. All it does is cause hassle, and the very few use cases of it are purposeful. Purposeful enough to be able to manually toggle it on.

I'm talking about the "Enable countdown" setting. 99% of experienced beatmappers will turn it off anyways, why is it defaulted to on?

**Comment by smoogipoo** [comment]
I agree with this one, it's not common these days.

**Comment by smoogipoo** [comment]
Fixed in the next Cutting Edge build.
