### ISSUE TITLE
Compatible mode performance.

### ISSUE THREAD

**Issue by IrresistibleJuicyFruit** [ppy/osu-stable-issues#660]
I always played in compatibility mode without much problems, but after the update, my ms has reached 30 in some fixed position of some maps. I use HD graphics to play.

![screen](https://user-images.githubusercontent.com/78444807/106655256-e3a9c600-6577-11eb-84f4-b60d31e0c7d3.jpg)

**Comment by smoogipoo** [comment]
Do you remember what sort of performance you were seeing previously? What FPS/ms range is normal for you?

Also please provide the performance.log file in your `osu!/logs` directory.

**Comment by IrresistibleJuicyFruit** [comment]
60fps / 1.5 ~ 1.8 ms, I didn't find this log, I had reinstalled the game to see if it normalized, then it was deleted.

**Comment by IrresistibleJuicyFruit** [comment]
I noticed that maps without pauses or with short pauses + or - 2s have no performance problem.

**Comment by smoogipoo** [comment]
Closing this as the change has been reverted for the time being.
