### ISSUE TITLE
[Request] Option to turn off notes blink at kiai time

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-stable-issues#664]
## Why?
it's beautiful to see but gets in the way a little depending on the map and the bpm ... I've made a lot of mistakes on maps myself because the effect was gradually blinding me during the map.

This affects more in taiko mode because when there are many katsus the effect blinds a little more

## Ingame (Kiai)
![image](https://user-images.githubusercontent.com/62405013/107581055-4af9f280-6bd6-11eb-8e78-dde5a2fdb476.png)

## Ingame normal
![image](https://user-images.githubusercontent.com/62405013/107581210-81d00880-6bd6-11eb-99e2-fabd2ed16419.png)

**Comment by peppy** [comment]
This is out of scope for stable, but we may consider adding such an option in lazer.

**Comment by Sebola3461** [comment]
@peppy thx for ur reply!
