### ISSUE TITLE
I just don't use stable latest because it doesn't work on my computer

### ISSUE THREAD

**Issue by TheWorstMaluS** [ppy/osu-stable-issues#665]
My computer does not support opengl 2.0 so I use fallback because it has directx rendering

**Comment by Joehuu** [comment]
Try toggling compatibility mode, by running the `repair osu!` shortcut.

**Comment by TheWorstMaluS** [comment]
> Tente alternar o modo de compatibilidade, executando o `repair osu!`atalho.
how do I activate compatibility mode?

**Comment by Joehuu** [comment]
Do you get a window like this after running `repair osu!`?

![image](https://user-images.githubusercontent.com/35318437/108275580-65c6ec80-712b-11eb-8142-aa7c04568de7.png)

Just click `Compatibility Mode` and then `start osu!`.

**Comment by TheWorstMaluS** [comment]
no he just restarts osu

**Comment by TheWorstMaluS** [comment]
forget what i said before it doesn't even appear osu repair just restart osu

**Comment by TheWorstMaluS** [comment]
> forget what i said before it doesn't even appear osu repair just restart osu

and shortcut does not exist
