### ISSUE TITLE
Incorrect skin and replay file descripion

### ISSUE THREAD

**Issue by Phantom-bits** [ppy/osu-stable-issues#666]
osu replay, and skin files are labelled as "osu! beatmap"
.osk files should be "osu! skin" and .osr files should be "osu! replay"

![b](https://user-images.githubusercontent.com/69491825/108312121-c6682f00-71e8-11eb-9418-f5078db7026c.PNG)
![a](https://user-images.githubusercontent.com/69491825/108312168-dbdd5900-71e8-11eb-8d26-f6517ea27e83.PNG)

**Comment by peppy** [comment]
Turns out this isn't a super easy one to fix, and something I'd rather not try to fix at risk of breaking more. We'll get this right when we reimplement it in lazer, at which point it will update/fix these associations.
