### ISSUE TITLE
Dropping .ogg file in game does not create a new beatmap

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu-stable-issues#667]
Unlike dropping `.mp3` file which does create a new .osu file which shows up in the songs list, `.ogg` does not do that. When it is attempted, `.ogg` file will get copied to a new directory in the Songs folder, but that's about it. 

This has been an issue for years but since only recently the ranking criteria started allowing ranking `.ogg` files, I thought it would be a valid GitHub issue to create.

**Comment by peppy** [comment]
Should be fixed in the next cutting edge release!

**Comment by Kyuunex** [comment]
p**ogg**ers!

**Comment by c-sig** [comment]
ogg
