### ISSUE TITLE
Stable crashes after ran with Wine

### ISSUE THREAD

**Issue by Maritsu** [ppy/osu-stable-issues#668]
So I've recently moved to Ubuntu 20.04.2 LTS. I've tried installing osu (I ran the installer with Wine) and everything worked perfectly until I ran the actual game. It immediately crashed and gave me this error:
```
System.Runtime.InteropServices.MarshalDirectiveException: Byref array marshalling to managed code is not implemented.
  at (wrapper native-to-managed) System._AppDomain.GetAssemblies(intptr,intptr)
```
I have no idea what happened, what to do or is it just me.

**Comment by peppy** [comment]
This is on you to fix. We can't support end users using emulation to run the game.
