### ISSUE TITLE
Left ctrl kicks you from a multiplayer match

### ISSUE THREAD

**Issue by timiimit** [ppy/osu-stable-issues#670]
**Bug explanation**
If you are in a multiplayer room and match just starts, you get kicked out of the room if you open chat and press left ctrl.
If I try to start a match with `!mp start` while I'm alone in a match and then open chat and press lctrl, it just stops the match but I stay in the room.

**When it started**
I don't know when it started happening because I recently came back from a break. It started at least a month ago.

**I'm the only one**
I will say that I haven't asked anyone else to try to replicate the bug, so it is a possibility that it's happening only to me. I would be happy if you would let me know if it's only a problem on my side.

**Why it bothers me**
It's driving me crazy, I just want to select all text with ctrl+a and clear what I wrote in chat so that I don't forget that I wrote something and that, when map ends, I don't try to send message with 2 unrelated sentences (I start typing without looking at what I wrote before lol). And I keep doing this, it kicked me at least 10 times now and then sometimes I can't even rejoin because I forget the name of the room, or name of players.

**Comment by timiimit** [comment]
Upon testing a bit more, I found out that I don't even need to open chat for the bug.

**Comment by peppy** [comment]
chek your bindings?

**Comment by timiimit** [comment]
oh I don't know why I didn't think of that... and I also don't know why I set keyPause to that key. Thanks for help, and sorry to waste your time.
