### ISSUE TITLE
Hit error meter only shows colors for osu!standard judgements

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu-stable-issues#671]
here the meter shows blue-green-orange for osu!standard's 300-100-50 judgements, even though mania is played, where there is also 200 and 300r judgements and the color convention is different
![screenshot088](https://user-images.githubusercontent.com/14909211/109385482-7d089580-78f4-11eb-916c-c7d7535b1709.png)
also while we're at it, it would be nice if the hit error meter also showed the note-lock range in red

**Comment by smoogipoo** [comment]
This isn't going to happen on stable, sorry. It has already been fixed in lazer.
