### ISSUE TITLE
osu! crashes my computer

### ISSUE THREAD

**Issue by Tresquel** [ppy/osu-stable-issues#672]
UNEXPECTED_STORE_EXCEPTION is the BSOD that i sometimes get from playing osu.
The game freezes and somewhere around a minute later my computer crashes. It happens when i try to select a random map by hitting F2 and sometimes the game freezes for a second and then comes back but sometimes it crashes my computer.

Logs from before the crash:
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6055898/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/6055899/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6055900/update_success.log)

It started happening after the last update before that the game would just lag a little when randomly selecting a map but thats because my computer is a bit dated

If u need any more info let me know i will provide everything i can

**Comment by peppy** [comment]
Please google this BSOD code. It's 100% not related to osu! so we cannot help you, sorry.
