### ISSUE TITLE
"apps" key binding doesn't always work

### ISSUE THREAD

**Issue by lualex403** [ppy/osu-stable-issues#673]
Application (Windows Context Menu Key or "menu" key) doesn't work in the song select page. I have set my extended chat menu as the "apps" key and in the song select page it tries to type the "apps" key instead of opening the extended chat. the "apps" button works elsewhere such as the main menu, while playing a song, etc. just not in the song select.

I've checked in osu!lazer and seems like it doesn't recognize "app" key at all I have also opened a issue there.

**Comment by peppy** [comment]
Out of scope for stable, sorry. We will look at whether this is something we want to support in the issue you opened against lazer.
