### ISSUE TITLE
Unable to create a new difficulty of an old mapset with no artist field

### ISSUE THREAD

**Issue by Purplegaze** [ppy/osu-stable-issues#675]
This probably happened with the new change that disabled empty difficulty names to prevent deletion of other diffs.

To reproduce:
Open this map in the editor and try to make a new difficulty. Artist isn't editable so you can't get past the difficulty creation window.
https://osu.ppy.sh/beatmapsets/2825#osu/20382

**Comment by peppy** [comment]
Thanks for the report. This should be fixed in the next cutting edge release.
