### ISSUE TITLE
Osu Error 0x80004005

### ISSUE THREAD

**Issue by pejzaz** [ppy/osu-stable-issues#677]
Describe the crash: Osu! installer crashes when installing, and gives me error 0x80004005, i played osu! like 3 months ago and everything was ok

Screenshots or videos showing encountered issue:
![error](https://user-images.githubusercontent.com/80106075/110125201-58646000-7dc3-11eb-9761-9761e6042b21.png)

osu! version: newest

Logs:
No logs

Computer Specifications:
Intel HD Graphics Family 1GB
Intel B950 2.1Ghz
4GB RAM

**Comment by peppy** [comment]
This looks like an issue with your windows install. Please google for potential solutions. My recommendation would be to reinstall/refresh windows.
