### ISSUE TITLE
osu! micro-freezes when using Discord Overlay

### ISSUE THREAD

**Issue by DimitriCunev** [ppy/osu-stable-issues#678]
This is really annoying and makes the whole overlay and game to freeze at some points when not moving the mouse.
It makes Discord Overlay unusable because it's very VERY annoying to scroll or preview gifs/videos.

This does not happen in lazer version or other games.

**VIDEO**
https://imgur.com/xevJESm

_I'm moving the mouse slowly on purpose to demonstrate._

**Comment by DimitriCunev** [comment]
It's not a big issue, but this doesn't happen in other games.
I'm pretty sure it's coming from the osu! client.

**Comment by peppy** [comment]
I'm not sure what "coming from the client" means here. We can't really predict what overlays are doing to our game. They are hooking and doing whatever they please. I would recommend contacting discord if you think this is an issue.
