### ISSUE TITLE
Starting multiplayer game while typing in Korean character blocks most keyboard inputs during gameplay 

### ISSUE THREAD

**Issue by pneumonia02013** [ppy/osu-stable-issues#68]
In detail, to type a Korean character (ex>펩), we need to type several alphabets (ex> ㅍ,ㅔ, and ㅂ in order). However, if multiplayer game starts while osu is in this 'building character' process, we cannot use most of keyboard inputs. 
This include tabbing to hide/show multi ranking, pressing F9 to open chat. Fortunately this does not block gameplay inputs (like z,x), but this problem is very annoying and seems to happen to every Korean players. Resolving this will be big life quality improvement for Korean players.
Thanks.

**Comment by pneumonia02013** [comment]
Thanks for fixing it quickly!
However I found that when characters are inserted in middle new characters overlap with existing ones so reporting here.
https://osu.ppy.sh/ss/13864021/7766

**Comment by smoogipoo** [comment]
Scope too large for that one.
