### ISSUE TITLE
Song title with custom colors doesnt recognize color modifier and shows up broken 

### ISSUE THREAD

**Issue by zel-zel** [ppy/osu-stable-issues#681]
Only noticed this on Anhedonia https://osu.ppy.sh/beatmapsets/90784#osu/246280
![image](https://osu.ppy.sh/ss/16330989/79f2)
Does not happen on Kakuzetsu Thanatos https://osu.ppy.sh/beatmapsets/76396#osu/215906
![image](https://osu.ppy.sh/ss/16331015/8e9a)

**Comment by smoogipoo** [comment]
This is not a thing.

**Comment by smoogipoo** [comment]
As it turns out, this is a thing. But it's not going to be supported going forward.

The reason for this is likely just because it's expecting the british-english spelling `colour` instead of `color`.

**Comment by peppy** [comment]
Should be fixed.
