### ISSUE TITLE
Beatmap difficulty bug.

### ISSUE THREAD

**Issue by Br1xton** [ppy/osu-stable-issues#684]
I had to dellete osu! due to different problems, but made a copy of all my beatmaps and skins. I installed osu! again and replaced everything and the skins worked, but the beatmaps got 0* of dificulty for some reason, I clicked F5 to process all beatmaps to see if it would help, and it did, arround 111/2157 beatmaps got their normal difficulties.
Edit:So I was writting this and when I finished I clicked f5 again and every song got normal so I guess it was just prossecing in the background after all.

**Comment by smoogipoo** [comment]
They're likely just being processed in the background? Can you sort by difficulty and see if maps are getting processed?

Also, provide the `runtime.log` file.
