### ISSUE TITLE
upload score bug

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#685]
I was unable to upload my scores twice. There is no upload information after the game. The ranking panel is the same as offline play. After that, I tried to record the process of playing OSU, and found the same situation once again. This time, I recorded the video as evidence. Ranking panel has beatmap rate option, but there is no page to upload the score, and the score in the video cannot be uploaded successfully.
![Image of Yaktocat](http://osu.wanjiaxg.com/cloud/screenshot851.png)
![Image of Yaktocat](http://osu.wanjiaxg.com/cloud/screenshot852.png)
![Image of Yaktocat](http://osu.wanjiaxg.com/cloud/screenshot853.png)
![Image of Yaktocat](http://osu.wanjiaxg.com/cloud/screenshot854.png)
There are two beatmaps in the video, which were uploaded for the first time, but not for the second time.
video Link:  http://osu.wanjiaxg.com/cloud/osu_upload_bug.mp4

**Comment by peppy** [comment]
Can't really do much with this report without attached log files. If you do happen to reproduce this issue, please reply in this thread and attach log files from that play session. We'll look into it further.

**Comment by wanjiaXG** [comment]
How to get osu! runtime log?I try catch it.



---Original---
From: "Dean ***@***.***&gt;
Date: Thu, Mar 25, 2021 12:22 PM
To: ***@***.***&gt;;
Cc: "Feng ***@***.******@***.***&gt;;
Subject: Re: [ppy/osu-stable-issues] upload score bug (#685)




 
Can't really do much with this report without attached log files. If you do happen to reproduce this issue, please reply in this thread and attach log files from that play session. We'll look into it further.

**Comment by peppy** [comment]
After you reproduce the issue, without restarting the game go into settings and choose "open osu! folder". Then copy the files from the `Logs` folder into this issue (you should be able to drag-drop to upload to github).

**Comment by wanjiaXG** [comment]
[session.log](https://github.com/ppy/osu-stable-issues/files/6214032/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6214033/update_success.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6214034/runtime.log)
again
http://osu.wanjiaxg.com/cloud/osu_upload_bug_02.mp4

**Comment by wanjiaXG** [comment]
> After you reproduce the issue, without restarting the game go into settings and choose "open osu! folder". Then copy the files from the `Logs` folder into this issue (you should be able to drag-drop to upload to github).

again
