### ISSUE TITLE
Search Filter inconsistent when applying HR

### ISSUE THREAD

**Issue by hesch** [ppy/osu-stable-issues#687]
I noticed that the osu! seach filters are inconsistent when HR is applied. The search uses the old values (without applying HR) for the filter except for the star rating!
For example let's say we have a map with the following values:
- without HR:  AR 7; SR 2.74
- with HR: AR 9.8; SR 2.95

The following searches produce inconsistent results with HR active:
 - "ar=7 stars=2.74" => map not found
 - "ar=7 stars=2.95" => map found (<= this one shouldn't find the map)
 - "ar=9.8 stars=2.74" => map not found
 - "ar=9.8 stars=2.95" => map not found (<= this one is should find the map)

**Comment by smoogipoo** [comment]
This one's a touch too difficult to fix in osu!stable, sorry.
