### ISSUE TITLE
Remove the message "Deleting backgrounds makes osu! ANGGGGGGGRRRRRRRRRRYYYYYYYYYYYYYYYY!" when starting a map.

### ISSUE THREAD

**Issue by FlagFlayer** [ppy/osu-stable-issues#688]
**Issue:**
Whenever the file for a map background is missing, a message appears when starting the map stating: "Deleting backgrounds makes osu! ANGGGGGGGRRRRRRRRRRYYYYYYYYYYYYYYYY!".

Example:
[Imgur](https://i.imgur.com/lL1QdZ6.jpg)

I personally find it infuriating that the game mocks me for removing background images which make me feel uncomfortable. I won't get into the legal issues of hosting some of these sexualising backgrounds, some depicting children, because I lack the legal expertise to do so. I don't want these images on my computer, hence I delete any background image on my PC that I don't approve of.

While that process IS bothersome to do, I don't mind doing it for my own greater good, because it makes me a lot more comfortable playing this game when there ISN'T any content that could be considered "adult" on my client. However, being actively smack-talked by the game every single time I play certain maps for wanting to feel comfortable while playing? That is truly the last straw for me. It sours A LOT of the experience of enjoying this game.

Moreover, I'll add that some backgrounds were removed after the staff themselves deemed them inappropriate, and yet this message still appears! (e.g. [DJ YOSHITAKA - A Kiss for the FLOWER](https://osu.ppy.sh/s/79702)) A game mocking its own players due to staff removing inappropriate images. Completely and utterly ridiculous.

**Proposal:**
Find & remove the code that triggers the message.

OR

Change the message into one that notifies the player of the background file missing instead of being rude, and add a toggleable option to disable it (This is because seeing any message a large number of times would be extremely draining).

**Comment by peppy** [comment]
Not sure if you are a non-native speaker, but the message is not intended to be (nor can it be read as) mocking.

When we remove images they are usually replaced, so we will look into the one you mention.

As for your issue, if you find the message unacceptable you can replace the background with another one, rather than deleting it.

**Comment by FlagFlayer** [comment]
This is just my own two cents. I personally find it mocking, and it sours my own personal experience. I would have a much better experience if this were to be removed or changed.

I can indeed just replace the background, but I find it hassle enough to remove all of these images, and I shouldn't be bothered by the game to do extra work just because I am made uncomfortable from an image that's packed with a map and downloaded to my computer.

As I understood it, the explicit tag is mainly meant for songs with lyrics that could be considered "adult", which I find a lot less harming. An explicit tag doesn't automatically grant right to add "adult" content, and I still have full right to remove these images if I find them uncomfortable regardless of how the mapset is tagged.

**Comment by peppy** [comment]
the tag is intended to cover graphic content too. plus we have changed rules to allow less through.

this isn't really the place to discuss that tough. i'll consider changing the message but it's not simple as we lose localizations for it.

no further input is required.

**Comment by MANi-kun** [comment]
> This is just my own two cents. I personally find it mocking, and it sours my own personal experience. I would have a much better experience if this were to be removed or changed.
> 
> I can indeed just replace the background, but I find it hassle enough to remove all of these images, and I shouldn't be bothered by the game to do extra work just because I am made uncomfortable from an image that's packed with a map and downloaded to my computer.
> 
> As I understood it, the explicit tag is mainly meant for songs with lyrics that could be considered "adult", which I find a lot less harming. An explicit tag doesn't automatically grant right to add "adult" photographic content, and I still should have the full right to remove these images if I find they make me uncomfortable regardless of how the mapset is tagged.

🧐 No one had issue with that message nor lewd BGs cuz at the and most of them get deleted and you can report bgs from this site [](https://bn.mappersguild.com/reports)
