### ISSUE TITLE
Unable to create new beatmaps when signed out

### ISSUE THREAD

**Issue by E223** [ppy/osu-stable-issues#689]
When logged out of the client, upon importing a new audio file and opening it in the editor, the "Beatmap Creator" field of the Song Setup will be empty but also disabled, preventing you from filling out all of the fields required to click the OK button.

Example of what the song setup menu looks like in this state:
![](https://i.imgur.com/Z5K6pbI.png)

**Comment by peppy** [comment]
Thanks for the report. This is fixed in the next cutting edge release (later today).
