### ISSUE TITLE
Undo (Ctrl-Z) in editor forgetting to remove new object(s)

### ISSUE THREAD

**Issue by nautzz** [ppy/osu-stable-issues#69]
The way I've been able to reliably reproduce this is to place 2 hitcircles, remove them, place a slider, move the sliderbodies endpoint to make the slider longer, quickly undo 3-4 times (as fast as possible after letting go of the endpoint), then redo 3-4 times, and repeat last 3 steps until it eventually bugs out and doesn't undo placement of the slider. Takes me only 5-6 times usually.

I've had this happen before with any number of combinations of circles and sliders, but this is the only way of reproducing the bug that I've found.

**Comment by nautzz** [comment]
For reference, here's a clip of it happening:

https://streamable.com/c5bjn

**Comment by dorothy3242** [comment]
As part of this, Undo is generally extremely buggy, especially when it comes to slider manipulations that often don't get saved in undo history for whatever reason. As a result it's not very useful.

**Comment by jakads** [comment]
happens without exception when you place a note over LN in mania
undo needs to be recoded

**Comment by peppy** [comment]
Probably not worth fixing (scope too large) unless it's just missing a few lines.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
