### ISSUE TITLE
Click on the orange cursour thing broken on aspect ratios bigger then 16:9

### ISSUE THREAD

**Issue by LosPedross** [ppy/osu-stable-issues#690]
Hello, recently I've discovered that the after pauzing the game midway the map if your cursour is on the right side of the screen and you're using something like 21:9 monitor the orange thing is no where it is suposed to be.

![](https://i.imgur.com/ks0pxBB.jpeg)

It seems like the detection is only checking the area of 16:9 or something like this and anything outside of it is just set as the most right side of this detection

Video showing the issue: https://streamable.com/rf2rct

**Comment by LosPedross** [comment]
Hello, so as I see the thread was closed without any comment (which is really unusual from the other issue threads), does this mean that the bug should be fixed in the next update? or are there some complications with the fix for it?

**Comment by peppy** [comment]
A fix for this should already be live in the latest cutting edge release, yes.
