### ISSUE TITLE
DT BPM on osu! applies on rounded values

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu-stable-issues#691]
Literally stumbled onto this randomly.
This map (https://osu.ppy.sh/beatmapsets/67226#taiko/195478) is 187.5BPM, rounding to 188BPM on client
Image 1: BPM in editor
![image](https://user-images.githubusercontent.com/30021847/111874553-c5642200-898d-11eb-9f5c-64b6f0559f51.png)
 
Image 2: BPM on client (rounded)
![image](https://user-images.githubusercontent.com/30021847/111874567-d0b74d80-898d-11eb-8f7a-042937fdfa0d.png)

When you apply DT, on client it shows 282BPM
Image 3: BPM on client w/ DT
![image](https://user-images.githubusercontent.com/30021847/111874656-15db7f80-898e-11eb-9607-312004b507ea.png)

187.5 * 1.5 = 281.25 (true value)
188 * 1.5 = 282

So the client is using the rounded values of bpm to get the DT bpm, which is incorrect.

Super minor issue and it's mostly nitpicking, though I wonder issue is present in lazer?

**Comment by smoogipoo** [comment]
The issue shouldn't be present in lazer, and is out of scope of fixing for stable.
