### ISSUE TITLE
osu!direct cannot search by beatmap id

### ISSUE THREAD

**Issue by Malikil** [ppy/osu-stable-issues#692]
Re-posting from https://osu.ppy.sh/community/forums/topics/1276879  

**Problem details:**
In the past when downloading maps for things like tournament mappools I would type the IDs into osu!direct to download the maps rather than opening every single beatmap page in my browser. But today when entering IDs into osu!direct it isn't finding any maps. I was able to download maps like this last week with no problems, so this happened within the last week.
I tried both Cutting Edge and Stable clients, both are performing the same way. It also seems to be the same regardless of the ranked status of the map.
It does still seem to work with mapset ID, just not beatmap ID. Searching by beatmap id in song select still works as expected, this is specific to osu!direct.

**Video or screenshot showing the problem:**
I expect to find https://osu.ppy.sh/b/2004588 Minamotoya feat. Kuroa* - Hana Kagerou (Graveyard)
![](https://osu.ppy.sh/ss/16359806/6a4c)

I expect to find https://osu.ppy.sh/b/1849487 Mirai Akari - Akari ga Yattekita zo (Loved)
![](https://osu.ppy.sh/ss/16359854/985d)

I expect to find https://osu.ppy.sh/b/772293 yak_won - Sewing Machine (Ranked)
![](https://osu.ppy.sh/ss/16359865/77d8)

**osu! version:** Stable 20210316 (latest) and Cutting Edge b20210311

**Comment by peppy** [comment]
This has now been resolved. Looks to work for your example, too.

![20210323 155107 (Parallels Desktop app)](https://user-images.githubusercontent.com/191335/112105340-9e0c8f80-8bef-11eb-838f-6c6c19f4a5ad.png)
