### ISSUE TITLE
Sample Import is usable in the osu! editor but doesn't work for sliderheads

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-stable-issues#693]
It works as you'd expect on circles, but only on these. I haven't seen anyone use it (apart from one of my mentees on accident) and thus we didn't bother with actually defining stuff about it when initially rewriting the Ranking Criteria.

If you use Sample Import to assign a sample to a sliderhead it won't play anything. If you assign a sample to a circle it works as you'd expect but any other "normal" modifications to the sampleset (adding hitclap / finish / whistle ) to the slider doesn't do anything.

Would be cool if thsi feature was either fixed in its behaviour so we can make it rankable in osu! or disabled in the osu! editor and only enabled for mania or something.

**Comment by peppy** [comment]
not happening in stable, but may in lazer.

**Comment by Okorin** [comment]
Not even making the feature un-usable for osu! mapping so that people don't use it on accident?

**Comment by peppy** [comment]
hmm, how easy is it to accidentally get to right now?

**Comment by Okorin** [comment]
one of my mentees found the feature and thought it was for hitsounding, used it and as a result screwed their map over. It is easy to access when you're trying to get familiar with the editor and find it, thinking it's for hitsounding. 

Compose -> Sample Import is all you need to click to get the impression that it's there to be used 
I clicked it on accident a few times when wondering what the hell live mapping mode was supposed to be. At that point I knew what maps were though so it's hard to tell

Is pretty easy to accidentally end up in i think and if you don't know any better you're probably gonna use it until people tell you it doesn't work

**Comment by peppy** [comment]
right. i think it should only be visible in mania. will look at hiding it.
