### ISSUE TITLE
Profile images are not shown correctly

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-stable-issues#694]
ehw...
![screenshot1115](https://user-images.githubusercontent.com/62405013/111889180-0118df00-89c2-11eb-8886-99ceac508342.png)

 It only happened after I used the "Clear cache" option in osu!Lazer
  I don't know if this is a problem with the stable or the new client

**Comment by peppy** [comment]
need logs

**Comment by Sebola3461** [comment]
[session.log](https://github.com/ppy/osu-stable-issues/files/6176632/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6176633/update_success.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6176634/runtime.log)
all stable logs

**Comment by peppy** [comment]
everything looks fine there, so i'm not sure. can you access https://a.ppy.sh/2 fine in a web browser?

**Comment by Sebola3461** [comment]
![image](https://user-images.githubusercontent.com/62405013/111890315-1d6b4a80-89c7-11eb-8124-1b4d1cae6e3b.png)

**Comment by peppy** [comment]
Then I have no idea sorry. But maybe start with removing whatever the blue thing is on your taskbar.

**Comment by Sebola3461** [comment]
its a pp counter

**Comment by Sebola3461** [comment]
![image](https://user-images.githubusercontent.com/62405013/111890376-8eaafd80-89c7-11eb-957b-29f5e55fd05f.png)
the problem, my folder its corrupted

**Comment by ThePooN** [comment]
This is file-system level corruption, way out of osu!'s capabilities.

You can look into tools like `chkdsk` to check and maybe repair some damage, but this is out-of-scope of this repository.
