### ISSUE TITLE
Select song panel bug

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#695]
IF on select song panel press win key, after back osu, that is look like this video.
By the way, if press insert, the result is same.
http://osu.wanjiaxg.com/cloud/2021-03-21_13-16-02.mp4

**Comment by peppy** [comment]
This is going to be an input device or application on your system pressing a key down.

**Comment by wanjiaXG** [comment]
> This is going to be an input device or application on your system pressing a key down.

So this problem can't be fixed? The result is obvious, osu got the wrong command, I did not press any other keys, only win.

**Comment by peppy** [comment]
This doesn't happen for most users, so it's got to be something specific to your system. Maybe IME, maybe a utility app you're using, maybe an external controller.

**Comment by wanjiaXG** [comment]
> This doesn't happen for most users, so it's got to be something specific to your system. Maybe IME, maybe a utility app you're using, maybe an external controller.

ok
