### ISSUE TITLE
Spanish translation error

### ISSUE THREAD

**Issue by Fasuplusplus** [ppy/osu-stable-issues#696]
After completing a map, on the online ranking chart the "Accuracy" column is labeled "Presición", when it should be "Precisión". The corresponding line in the es.txt localisation file is 1230: "RankingDialog_Accuracy=Presición", which should be "RankingDialog_Accuracy=Precisión".
![image](https://user-images.githubusercontent.com/69156162/111923887-384dc580-8a80-11eb-9158-faada1b69cc1.png)

**Comment by peppy** [comment]
I'll make an update to the localisation file, but can't guarantee the deploy process still works for this (if it is manual, there's a chance this change won't take effect just yet).
