### ISSUE TITLE
Distance spacing/snap in the editor.

### ISSUE THREAD

**Issue by jorgen779** [ppy/osu-stable-issues#697]
Currently you can change distance spacing by 0.1 in-game, but in the map file you can change by 0.01 example 0.72, would be convenient to have it in-game.
![dllhost_2021-03-22_22-25-06](https://user-images.githubusercontent.com/37352434/112053797-7836aa80-8b5d-11eb-8ef4-5e301a0a1465.png)

**Comment by smoogipoo** [comment]
Hold Alt+Shift.

**Comment by smoogipoo** [comment]
Will be fixed in the next release.
