### ISSUE TITLE
Scrolling down the osu!direct sidrebar panel doesn't work properly when downloading enough maps

### ISSUE THREAD

**Issue by FlagFlayer** [ppy/osu-stable-issues#699]
**Issue:**
Whenever you download enough maps to be able to scroll the sidebar in osu!direct the scrolling fails to go the whole way down, resulting in maps at bottom being inaccessable, and therefore outright impossible to cancel download of via the sidebar menu.

**Example:**

1. Sidebar when scrolled down as much as possible: https://i.imgur.com/KpCtbzi.jpg

2. Sidebar when actively being scrolled after reaching the bottom*: https://i.imgur.com/cm2gpSP.jpg

*Note that the menu only appears this way for a split second before being pushed back to how it is in example 1.

**Proposal:**
Honestly, this is a very minor issue, and only applies to the osu!direct tab (the scrolling of the osu!direct sidebar while on the main menu works completely fine, so you can still cancel downloads by going to the main menu). Just thought that this should be noted down somewhere, and if it's an easy fix then it's a good way to polish up the client slightly.

Client version: b20210316

**Comment by peppy** [comment]
Should be fixed in the next release, was a simple one.
