### ISSUE TITLE
TeamVS reporting invalid fails when at HP 0

### ISSUE THREAD

**Issue by Redavor** [ppy/osu-stable-issues#7]
Already made a forum thread where the bug was confirmed, so here's the link to that.

https://osu.ppy.sh/community/forums/topics/942676

Short TL;DR: When playing Multiplayer matches in Team VS, if your HP goes to 0 but you don't actually fail and manage to regain hp, it will throw the other player/team (that didn't fail) out of the map and back into the multiplayer lobby, while you/your team continues playing. 

It happened again this weekend, but we stopped saving mp links since the bug was confirmed.

Thanks for the help in advance. <3

**Comment by peppy** [comment]
This should be fixed as it is a regression from recent HP changes. It should be a relatively simple one (server should not be informed of fail unless actually fail-worthy).

**Comment by peppy** [comment]
As discussed, this is more high effort than first determined.

**Comment by peppy** [comment]
Has been fixed.
