### ISSUE TITLE
Some Pop-Ups in the editor can't be closed with Enter

### ISSUE THREAD

**Issue by SALZKARTOFFEEEL** [ppy/osu-stable-issues#70]
This happens because those windows lack a default button (their OK button is not selected by default).

The windows I found are the following, there may be more:
* “Scale by” (Ctrl+Shift+S)
* “Create Polygon Circles” (Ctrl+Shift+D)

In contrast, look at the “Rotate by” window, for example.

**Comment by MillhioreF** [comment]
Fixed in next cuttingedge.
