### ISSUE TITLE
1/5, 1/7 & 1/9 snap divisors missing in "Timing and Control Points" window causing wrong behaviour while resnapping objects

### ISSUE THREAD

**Issue by ShaidenUNI** [ppy/osu-stable-issues#700]
Found this bug while I was looking at https://github.com/ppy/osu-stable-issues/issues/698 this issue, but these issues are not related.

Seems like with the addition of new snap divisors something went wrong in F6 panel. You can't choose 1/5, 1/7 & 1/9 snap divisor options in the bottom right area, but it acts like they're there. When you try to resnap objects with a checkbox "Snap objects to new timing" using 1/6, it resnaps to 1/5. 1/8 becomes 1/6, 1/12 becomes 1/7, etc.

**Comment by peppy** [comment]
Has been added in the next cutting edge release.
