### ISSUE TITLE
increase multiplayer player amount cap if possible

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu-stable-issues#701]
currently, the maximum amount of players that can be in a multiplayer lobby is 16. 
This is an okay number in case of normal lobbies, but we have found a usecase where we found ourselves reaching this cap fairly easily, and that is feedback lobbies. 

In case you are out of touch, Feedback Lobbies are lobbies mappers participate in to show off their maps to fellow mappers and receive feedback fairly quickly. Feedback Lobbies are nothing new, we've been doing this for years, but since this game has grown so much, and we have gotten more players interested in mapping, we reach the cap fairly quickly. I am aware of at least 2 Discord servers that organize this event regularly, and reach the cap almost instantly. 

So if it's not too much of a work, I would like if this cap is increased, maybe to 32.

![2021-03-26_23-26](https://user-images.githubusercontent.com/5400432/112683438-ff03c400-8e8a-11eb-9123-9381ef40dad2.png)

**Comment by Kyuunex** [comment]
ofc we could host it in lazer, but not many users use it atm

**Comment by peppy** [comment]
Please re-read the readme.

If you need larger lobbies *use lazer*.
