### ISSUE TITLE
Allow users to disable storyboards in the editor

### ISSUE THREAD

**Issue by apaffy** [ppy/osu-stable-issues#703]
Currently, there is no way to disable storyboards in the editor aside from renaming the SB folder/file or straight up deleting it. There's already an option to disable video in the editor (View -> Show Video), but not one for storyboards. My request is allowing us to do the same for Storyboards in the editor. 

This would be quite useful for mappers as well as modders. Many storyboards have numerous objects on screen or otherwise distracting elements on the screen that get in the way while mapping or modding and it would be nice to get rid of that clutter while viewing maps sometimes.

No idea if this is a feature in lazer; my request concerns osu-stable.

**Comment by peppy** [comment]
Transferred to the more correct place to submit this.

**Comment by peppy** [comment]
Would it be fine to just group video and storyboard together into one toggle?

**Comment by Nivalyx** [comment]
i think it should be fine yeah as storyboard and video can be categorized as some kind "visual accompaniment" altogether. most of the time such beatmaps however would only include either a storyboard or a video tho (not both)

---

it is possible for a beatmap to have [both a video and a storyboard tho](https://osu.ppy.sh/beatmapsets?e=storyboard.video) tho, however 

a) from what i counted among tens of thousands of Ranked beatmaps out there there are only 672 beatmaps that contain both a storyboard and a video, and 

b) this practice of combining storyboard + video together is becoming less and less common nowadays as evident from the fact that among the 672 maps there are only 9 of them which are getting Ranked in 2020 or later ((http://osu.ppy.sh/s/1085461 http://osu.ppy.sh/s/1039769 http://osu.ppy.sh/s/1150556 http://osu.ppy.sh/s/1233361 http://osu.ppy.sh/s/917159 http://osu.ppy.sh/s/1143538 http://osu.ppy.sh/s/482464 http://osu.ppy.sh/s/1198327 http://osu.ppy.sh/s/1343575))

...so yeah grouping video and storyboard together into one toggle should be good 👍

**Comment by peppy** [comment]
Should be resolved in the next cutting edge release.

**Comment by Negaosu** [comment]
I feel like grouping them isn't necessary, if:

a) There are still maps (albeit few) combining both.
b) Without them - the average player would have no indication of whether the map has a video or whether it's a storyboard, and I think that info doesn't hurt to have. I suppose an indication for this could be added though if you're still going to combine them

Something more practical would probably be having the button change between "Enable storyboard" and "Enable video" depending on which one the map has, or if it has both then leave both options there (likewise if it has none then there can just be no option)

**Comment by peppy** [comment]
no. you will take what i give you and accept it.

we may add toggles for each in lazer, but this is out of scope for any further attention in stable
