### ISSUE TITLE
Time conversion seems to be off on new submitted score

### ISSUE THREAD

**Issue by Legagit** [ppy/osu-stable-issues#704]
![image](https://user-images.githubusercontent.com/53434941/112756178-eeaf2e80-8fdb-11eb-854c-a9694ae578ff.png)
given that 3600 seconds is an hour, and osu thinks i submitted a play 3555s in the future, I'm guessing that there is a time zone issue here? 
p.s. I am a player of 6 years, and have never had this issue, I also haven't moved to a new time zone (or moved at all) so there's a few reasons ruled out. Not game breaking but a bug none the less.
Refreshing the score page doesn't solve it, it merely takes me closer to the time it thinks i submitted it lol. (i.e i refreshed 50 seconds later and it instead said -3505s)

**Comment by peppy** [comment]
This would mean your PC's time zone is off (potentially due to an incorrect daylight savings setting). Please check your system time zone settings!
