### ISSUE TITLE
Problem with censored username and the tourney client

### ISSUE THREAD

**Issue by ReimUe** [ppy/osu-stable-issues#705]
Heya, just posting this from osu! forum since a support member told me to post this issue here -

Problem details: Recently we streamed a match in the tournament client where player Gender (https://osu.ppy.sh/users/8080777) couldn't be spectated since the lobby name kept censoring the username and changing it to "alligator", preventing the client from detecting Gender in the lobby and spectating him. It also made it difficult to invite him through IRC because of this problem as well since it also gets censored when using !mp commands or the chat in general.

Video or screenshot showing the problem: This entire VOD - https://www.twitch.tv/videos/966168009

osu! version: Latest Tourney Client

**Comment by ThePooN** [comment]
As a temporary work-around, you can use !mp commands using #<user id> in place of their usernames.

For the lobby name however, the only way to escape it is creating it in-game, which is much more inconvenient.

For spectating, the osu!tourney client spectates based on the players in the lobby, not in the title.

I already had this looked into before the osu! rewrite (osu!lazer) even started but it was already considered too difficult to address, especially as there are good-enough existing workarounds (except for lobby creation for bots, which was my use case).

**Comment by peppy** [comment]
Have resolved this for that specific user.
