### ISSUE TITLE
Unable to submit scores at all.

### ISSUE THREAD

**Issue by Kasumiikun** [ppy/osu-stable-issues#707]
As the title says, I'm unable to submit any score to the game in the latest cutting edge release (b20210328), with the game telling me over and over that the version is out-of-date.
I've also restarted the game and went on stable to come back on cutting edge release before making the video linked here, and yet it doesn't work still. It also stopped working suddenly, considering I was on a 3-4 hours session already, and submitting scores just fine.

A video showing this: https://streamable.com/xywv2c

**Comment by peppy** [comment]
you are on “cutting edge”. this is an experimental build which can occasionally have issues like this. please change to “stable” if this worries you.
