### ISSUE TITLE
(Editor/BSS) Rename "Receive email notification on reply" to "Receive push notifications on reply"

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-stable-issues#709]
as it stands i don't really think that the "Receive email notification on reply" checkbox that mappers encounter upon submitting a beatmap actually does what it says anymore tho. i believe what it does nowadays is toggling the "Watch/Unwatch" button on the beatmap's modding page instead :

![image](https://user-images.githubusercontent.com/36564236/113054229-5ed3d500-91d3-11eb-8e1e-f0ebdb9d5a8b.png)

![image](https://user-images.githubusercontent.com/36564236/113054399-90e53700-91d3-11eb-92f8-0976631a834b.png)

not really a major issue per se but i've been had this disabled in the past as i once thought that this checkmark would send me an actual email so a fix for this would be nice to avoid future misunderstandings i suppose ;~;

**Comment by peppy** [comment]
I'll update this, but it's only going to change for english.
