### ISSUE TITLE
Quick Reply button is long dead

### ISSUE THREAD

**Issue by SALZKARTOFFEEEL** [ppy/osu-stable-issues#71]
The button is in Song Select where you can go to the Beatmap Page (to the right of the scoreboard type dropdown) – it is option #3.
Since the Modding Page reform, it just takes you to [a 404 page](https://osu.ppy.sh/forum/posting.php?mode=reply&t=468562).

**Comment by MillhioreF** [comment]
Removed in next cuttingedge.
