### ISSUE TITLE
osu! text not scaling properly

### ISSUE THREAD

**Issue by MagicalDemons** [ppy/osu-stable-issues#711]
The notifications/text pop-ups are not scaling properly when I play osu! at my native resolution, making them too small for me to read. My native resolution is 5120x2880 if that helps. Turning down the resolution fixes the problem, though I'd prefer to play at my native resolution. Any help is appreciated, thanks.

https://imgur.com/tNJb5ZU

**Comment by peppy** [comment]
Wrong game. Also probably won't be fixed due to implementation difficulty and rare usage.

**Comment by mm201** [comment]
I seem to recall making a SpriteManagerScalingMode.DPI or something like that back in the day, but I'm not 100% sure if I got it working.

**Comment by mm201** [comment]
If I'm reading this code properly, it seems that the text size will shrink all the way down to 0 when the window height is 3328. (Your 2880 comes quite close...)

Edit: Should be fixed when my branch is merged.

**Comment by peppy** [comment]
Should be resolved on cutting edge now!
