### ISSUE TITLE
tournament.cfg appears to be parsed with system locale causing ambiguity with the decimal symbol

### ISSUE THREAD

**Issue by omkelderman** [ppy/osu-stable-issues#713]
If you put a number in the tournament.cfg file with a decimal part, for example:
> Aspect = 1.4

it is system dependent on how that line is parsed. On my PC I had to use `1,4` instead of `1.4` and I suspect this is because my system is configured to use a comma as decimal symbol (https://omk.pics/1/5aca9.png) while the system of someone else uses a dot (https://cdn.discordapp.com/attachments/315237496101535754/827518106061504542/unknown.png). This makes the tournament.cfg not as portable and is a little annoying.

Some screenshots:
* My system with the setting set to `1.4`: https://omk.pics/1/c8LOn.png, setting didnt get applied
* My system with the setting set to `1,4`: https://omk.pics/1/zKmUh.png, setting did get applied
* The other persons system with the setting set to `1.4`: https://cdn.discordapp.com/attachments/315237496101535754/827511353614663730/unknown.png, the setting did get applied

Both of us are using b20210330.2cuttingedge.

If it is not too much effort would it be possible to parse that file with a hardcoded default locale that always assumes a dot as decimal symbol regardless of system settings? Makes the file a bit more portable and less hassle when sharing with other people.

**Comment by peppy** [comment]
Should be resolved in the next release.
