### ISSUE TITLE
You cannot upload the same metadata twice

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-stable-issues#714]
I don't think this has been brought up before  in the same capacity (https://github.com/ppy/osu-stable-issues/issues/341 is similar, but not about this exact problem), and it sounds like a pain in the butt to address, but here goes:

### Use case

Currently, if you have ranked a beatmapset with a certain metadata before and you try uploading a different version (e.g. you redid the map years later) and try to use the same difficulty names and haven't changed usernames, the client will tell you that the beatmap you're trying to upload is already ranked even though it clearly is not.

#### Example:

- https://osu.ppy.sh/beatmapsets/356752#osu/784977 (Ranked in 2015)
- https://osu.ppy.sh/beatmapsets/1420607#osu/2926218 (WIP)

Currently, the top difficulty is called `Sensou` and `Survival Game` respectively. If I try to rename the difficulty on the newer map to Survival Game and upate the beatmap, it will tell me this, **only i go to Edit -> Change the name of the difficulty, quit out, go back into the map, try uploading:**
![Example](https://i.imgur.com/l0HfiAS.png)

If you change the difficulty name in one session, and immediately go to upload, it will let you do that. That will result in both showing up correctly on web, but when you download the WIP beatmapset it'll tell you to update to the 'latest version' and replace it with the ranked beatmapset.

This is a problem if I was to make a difficulty that I want to call `Normal`, `Hard`, `Insane`, etc. as the client would just continually tell me the beatmap is already ranked and whatnot.

### Workaround

Currently, the Ranking Criteria has this janky workaround in place (highlighted)

- A beatmapset host cannot indicate possession in a difficulty's name. (e.g. Beatmapset Host's Insane). _**Conflicts caused by beatmapping multiple songs with the same metadata and collaborative difficulties are the only exceptions.**_ Guest difficulties, however, may indicate possession with its creators' username or nickname.

I think that this workaround shouldn't need to exist and if you have a separate beatmapsetid the client should treat the resulting stuff as different beatmaps regardless of the names of the difficulty / song file.

Just to be clear, currently - I could make a full set of difficulties for the second map and call all of the resulting difficulties `oko's Easy`, `oko's Normal`, etc. and it'd be rankable and also plenty stupid.

#### Accepted alternatives to get around the issue:

- changing my username to something else
- using a full set of custom difficulty names to never run into the problem
- Changing the song's metadata if I can come up with valid reasoning to do so

**Comment by Kyuunex** [comment]
this has been on my mind for years but since you made an issue, i would like to add stuff to it.

my best understanding of this is, the game tries to look up a beatmap by it's filename. iirc, in older versions of osu, there used to be no beatmapID, so this was the only way the game checked for updated versions of beatmaps. and this behaviour in the game has not been changed, even with introduction of beatmapIDs years ago. 

a simple solution I can come up with would be changing the lookups to happen using beatmapIDs

**Comment by peppy** [comment]
Please add a suffix to the difficulty name. 

Due to the way osu! (stable) and (legacy fallback) work, this cannot be fixed, sorry.

**Comment by Okorin** [comment]
Fair enough, just wanted to make sure the current RC actually _has_ to stay the way it is. 👍

**Comment by peppy** [comment]
It's a bit unfortunate, but filename matching is actually how the client can check for updates for older beatmaps (which don't have the `BeatmapId` embedded inside the `.osu` file).

I'm hoping we can eventually reprocess all beatmaps in a huge batch and update them with metadata like this, but it's one of those things which won't be addressed until we're done with lazer etc.

**Comment by Kyuunex** [comment]
in that case, how about adding `BeatmapSetID` in the file names upon save/upload from now on? as per the example bellow
`1420607 - NateWantsToBattle feat. Amanda Lee - Kuusou Mesorogiwi (Okoratu) [Survival Game].osu`

**Comment by peppy** [comment]
I'm not looking to make workaround like this sorry. I don't see this as a pressing issue.

**Comment by Kyuunex** [comment]
not to pointlessly argue but i really do feel like adding `2020 remaster` in the diff name is a worse workaround, and probably not even rankable

**Comment by peppy** [comment]
I'm against adding workarounds which break deployed production systems and existing legacy client behaviour. One of these does; one doesn't.

Thanks for your understanding in the fact that I understand the problem at hand.
