### ISSUE TITLE
Change the text of "Show Video" in the editor to mention storyboard

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#717]
![image](https://user-images.githubusercontent.com/1700346/113554797-7807c780-95bf-11eb-979b-a4a42723f8e9.png)

Took me a while to realize that storyboards and videos were grouped together in [this](https://github.com/ppy/osu-stable-issues/issues/703) issue and I couldn't for the life of me figure out why storyboards weren't shown until I found that thread. A friend of mine first had the issue which was what prompted me to even look into it.

Also disabling storyboards in the editor doesn't seem to disable _loading_ the storyboard, so maps with enormous storyboards still take a ridiculously long time to load (for ex: downloading [this map](https://osu.ppy.sh/beatmapsets/1124097#osu/2348896) and deleting all the objects and reloading still takes the same time despite there being 0 objects)

(Also since the previous default was to always show storyboard, it would be _really nice_ to have the option be on by default so people who want to disable the storyboard can disable it instead of not realizing there was ever a storyboard.)

**Comment by peppy** [comment]
This text was updated. Must be some kind of localisation propagation failure.

Loading of storyboard is out of scope, sorry.

**Comment by peppy** [comment]
Fixed for next cutting edge release.
