### ISSUE TITLE
Quick Retry button doesn't work after importing skin in the multiplayer room

### ISSUE THREAD

**Issue by ZeroPyrozen** [ppy/osu-stable-issues#718]
Quick Retry button doesn't work after importing skin in the multiplayer room.

Reproduction Step:
1. Join or create multiplayer room
2. Download any skin file (.osk) from web browser
3. Import the skin by double click or dragging to the osu! window while still in the multiplayer room
4. Player get redirected to main menu
5. Play a solo map any mode and try to use quick retry button
6. The quick retry button doesn't work during gameplay and pause menu

Temporary Solution: Restart osu! game

**Comment by peppy** [comment]
The solution here is probably just to not import the skin when in a multiplayer game. Or to import but not refresh the game's skin list. Does that sounds like a worthwhile change to make?

**Comment by ZeroPyrozen** [comment]
> Does that sounds like a worthwhile change to make?

This is really rare case so it's not worth it to change it in stable. I have tested this case on lazer build and the quick retry button still work after I import the skin.
