### ISSUE TITLE
Repair folder permissions problem.

### ISSUE THREAD

**Issue by 02Rusty** [ppy/osu-stable-issues#720]
clicking on "Repair folder permissions" makes my osu freeze for a couple seconds then show's this message.

![image](https://user-images.githubusercontent.com/70040605/114285438-d77d3180-9a1c-11eb-8ac1-2dca5d87420b.png)

**Comment by peppy** [comment]
Thanks for the report. Don't even remember adding this dialog in to be honest.

I'd say it's related to your dated operating system, and can be ignored. Shouldn't happen on Windows 10, if you ever decide to upgrade to a maintained operating system.
