### ISSUE TITLE
Osu! Compatibility Mode in Cutting Edge( All Black )

### ISSUE THREAD

**Issue by Kawaii-Hori** [ppy/osu-stable-issues#722]
So i use stable then switch to Cutting Edge with compatibility mode on.. its all black when i open osu but it has music but cant see a thing.
![image](https://user-images.githubusercontent.com/78250667/114325229-93e01000-9b61-11eb-97f8-62bab2aee06d.png)
Cutting Edge problem with compatibility mode, well i cant play osu without compatibility mode, so imma  go back to stable hope it got fix on cutting edge.

**Comment by smoogipoo** [comment]
Do you run the game in fullscreen? Can you test if it works in borderless or windowed mode?

Also please provide a [dxdiag log](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).

**Comment by Sebola3461** [comment]
Its ok for me
![screenshot1211](https://user-images.githubusercontent.com/62405013/114490370-1bbe2c80-9beb-11eb-9a3e-3d25432b2409.png)

**Comment by smoogipoo** [comment]
@Kawaii-Hori Can you provide the dxdiag log as mentioned previously?

**Comment by Kawaii-Hori** [comment]
> @Kawaii-Hori Can you provide the dxdiag log as mentioned previously?

here.
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/6355397/DxDiag.txt)

**Comment by smoogipoo** [comment]
Your graphics driver is extremely out of date and/or completely the wrong driver. The most recently available driver for your system looks to be https://downloadcenter.intel.com/download/24970/Intel-Graphics-Driver-for-Windows-15-28-

We've reverted the change on Cutting Edge for the time being, but would appreciate testing again in the future when we try again.
