### ISSUE TITLE
"No osu!stable installation available!"

### ISSUE THREAD

**Issue by xXacelukeXx** [ppy/osu-stable-issues#723]
when i go to maintenance to import a beatmap/skin from stable from osu! its says "No osu!stable installation available!" I try do    re-install but it's dose't work plz help
![Screenshot 2021-04-11 184407](https://user-images.githubusercontent.com/74433577/114325500-074c3800-9af6-11eb-9f29-0c2fe232ca04.png)

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.
