### ISSUE TITLE
I cant make storyboards in cutting-edge

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-stable-issues#724]
![image](https://user-images.githubusercontent.com/62405013/114490763-c898a980-9beb-11eb-93e9-19d87c30faf5.png)
i only cant

[performance.log](https://github.com/ppy/osu-stable-issues/files/6300979/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6300983/runtime.log)
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/6300985/DxDiag.txt)

- cutting-edge 20210316

**Comment by peppy** [comment]
okay.

**Comment by Sebola3461** [comment]
okay.

**Comment by Sebola3461** [comment]
Okay. What happens is that no image that I add is rendered on the storyboard, you can test it yourself

**Comment by peppy** [comment]
You probably have storyboard display turned off in the editor. Please turn it back on from the view menu.

**Comment by Sebola3461** [comment]
![image](https://user-images.githubusercontent.com/62405013/114491980-00a0ec00-9bee-11eb-9ad0-cb94b3d6642f.png)
ok

**Comment by peppy** [comment]
I've reset the state of this toggle in the next release to avoid others running into the same issue.
