### ISSUE TITLE
Deleted beat map link leading to old site 

### ISSUE THREAD

**Issue by MANi-kun** [ppy/osu-stable-issues#725]
Maybe  it would be better if there was new desing or something this only happens when you try to open beatmap listing/scores from ingame but map was previously deleted. (im new to github if I did this post wrong im sorry)

![image_2021-04-13_180635](https://user-images.githubusercontent.com/80633810/114584460-fd0b7480-9c82-11eb-8780-fc6d5e78427b.png)

**Comment by peppy** [comment]
Could you please provide the URL you were directed to, and show which button or area you clicked to make this happen?

**Comment by MANi-kun** [comment]
[https://osu.ppy.sh/b/2598017](url) 
![1](https://user-images.githubusercontent.com/80633810/114773117-ec382d00-9d6e-11eb-8d1f-2d5b95346382.png)
![2](https://user-images.githubusercontent.com/80633810/114773118-ed695a00-9d6e-11eb-8dda-b7658fb92f34.png)
I hope that's all

**Comment by peppy** [comment]
Thanks for that. Definitely need to update this button to go to the newer URL.

**Comment by peppy** [comment]
I've fixed this server side. Also updated the URLs to look more like the new site URLs in the next cutting edge release.
