### ISSUE TITLE
Hitsound issue on specific note

### ISSUE THREAD

**Issue by acrylic-style** [ppy/osu-stable-issues#726]
I set the sample to drum (custom 1) on all timing/inherited points but I'm hearing `soft-normal.wav`, rather than `drum-normal.wav` on a specific note (it does not have whistle/clap/finish hit sound)
This happens also on osu!lazer.

Beatmap: https://osu.ppy.sh/beatmapsets/1285858#osu/2669904 (Extra, `osu://edit/00:13:589 (9)`)

Timing on osu! stable and osu!lazer:

![image](https://user-images.githubusercontent.com/19150229/114649514-a140fa00-9d1b-11eb-89ec-eddcb6064770.png)

![image](https://user-images.githubusercontent.com/19150229/114649498-9a19ec00-9d1b-11eb-9f0f-f62c13d40055.png)

And the video (I changed `soft-normal.wav` on beatmap to make sure it is `soft-normal.wav`):

https://user-images.githubusercontent.com/19150229/114649428-7b1b5a00-9d1b-11eb-83c6-cdc99a8a4b85.mp4

**Comment by peppy** [comment]
It looks like you have local overrides on the object in question:

![20210414 133045 (Safari)](https://user-images.githubusercontent.com/191335/114654698-ad31b980-9d25-11eb-9639-86afd849f9a8.png)

Please change these to "Auto" if you want it to respect the control point specifications.

**Comment by acrylic-style** [comment]
Oh I see, I didn't notice it.
