### ISSUE TITLE
osu crashed when i send message

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-stable-issues#727]
when i try to send message my osu got crashed and send that message 4 times, it happend sometime.
what i should provide?
![image](https://user-images.githubusercontent.com/21735205/114661443-86a05e00-9ce6-11eb-9a83-394fa749f05c.png)

**Comment by peppy** [comment]
We need `runtime.log` from your osu! folder at a very minimum. Please make sure to provide it after the crash, but before starting osu! again.

Alternatively, if you are seeing the "pippi" crash dialog, click pippi then copy the text content there and paste it here.

**Comment by cyperdark** [comment]
i got only this 
![image](https://user-images.githubusercontent.com/21735205/115358691-70464680-a1ad-11eb-812f-bacf5aacf25c.png)

[runtime.log](https://github.com/ppy/osu-stable-issues/files/6341620/runtime.log)

**Comment by cyperdark** [comment]
I have a script on my localhost that is connected to bancho via this module https://www.npmjs.com/package/bancho.js
could this be the reason?

**Comment by peppy** [comment]
No idea. Closing until you provide more information as above.

**Comment by cyperdark** [comment]
the problem was that the "Symbolic link" referred to a folder that does not exist, and since I have logging of all messages enabled, it could not write the chat file, and therefore "osu" crashed

[runtime.log](https://github.com/ppy/osu-stable-issues/files/6363306/runtime.log)

**Comment by peppy** [comment]
Great, so you can fix that yourself yes?

**Comment by cyperdark** [comment]
yep, just re:create the "Symbolic link" to Chat folder
