### ISSUE TITLE
Will not automatically play the next song (the song selection interface plays in a loop)

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#728]
in recent cutting edge update (20210413)
in main menu will not automatically play the next song
and in songs select menu is will not loop play
I think it might play in outro

this problem do not appear in beta(20210312)

When I reupdate to cutting edge(for test beta), it seens solved?

**Comment by peppy** [comment]
Nothing has changed with this logic.

**Comment by peppy** [comment]
Going to close this for now. Was probably just a random occurrence of a long standing bug (and sounds like one we likely won't be resolving).
