### ISSUE TITLE
editor crashes if you remove all timing points and try to add a new one

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-stable-issues#73]
# steps to reproduce:
- open any song in the editor
- delete all timing points
- click "ok"
- accept warning
- try to add a timing point
# screenshots/video:
![](https://i.fiery.me/SdYW.png)
https://streamable.com/cvbcs
# logs:
- see screenshot
# version/setup:
- latest ce (`b20190920.1cuttingedge`)
- windows 10 18362.356 (64 bit)

**Comment by smoogipoo** [comment]
Regressed from the fix to https://github.com/peppy/osu-stable/pull/2194

**Comment by peppy** [comment]
Reverted said fix
