### ISSUE TITLE
Alt tabbing from osumania editor makes notes invisible.

### ISSUE THREAD

**Issue by livablesummer** [ppy/osu-stable-issues#732]
When i alt-tab from osu when in mania editor, the notes disappear, but they do exist and osu reads them fine, they make sound, but they can't be seen on screen. Same with placing new ones. I've tried different skins, and the default one, i also tried compatibility mode and fullscreen but nothing works. I presume this is a known issue since this is a pretty big problem in my opinion. My OS is win 10.

Screenshot shows osu editor before alt tabbing and after alt tabbing.
![helps](https://user-images.githubusercontent.com/76008030/115135260-86ba9980-a017-11eb-9a5f-d12c70201da2.

**Comment by peppy** [comment]
The screenshot you linked does not work.

**Comment by peppy** [comment]
Actually you mention compatibility mode, which is not even in lazer. I think you're in the wrong place.

**Comment by livablesummer** [comment]
I'm not using Osu lazer, just Osu! client, if this thread is to report bugs for osu lazer client, then i'm sorry for not looking.
Link to imgur with cropped images: https://imgur.com/a/B7rK9GZ
images show osu mania editor BEFORE alt tabbing from the game, and AFTER alt tabbing back to the game.
i can try record to show more clearly what's happening if anybody's interested.
And i'm quite surprised this is not known issue, by the looks of it maybe it's just a "me" problem. 

osu! version: Stable 20210316 (latest) with Windows 10

**Comment by peppy** [comment]
This is actually the correct place, please ignore my deleted post (got confused for a moment).

Could you please share what window mode you're running in, and whether you have compatibility mode turned on? If you're using full screen, does it fix the problem if you run windowed?

**Comment by livablesummer** [comment]
I'm playing on 1440x900 widescreen resolution, with fullscreen and render at native resolution turned on. But it doesn't matter if they're turned off / on, or if i switch my resolution - notes disappear anyway.

**Comment by peppy** [comment]
On alt tab? Even in windowed mode?

**Comment by livablesummer** [comment]
Just checked and yes, they disappear even with that setup like you mentioned.

But i've discovered something. If i alt tab once again, notes appear again.
for example i edit a beatmap, then i alt tab for something, and alt tab back to osu - notes disappear.
if i alt tab for something once again and alt tab to osu back again - notes appear.
they appear and disappear every time i switch screens.
Now after this discovery i don't have to leave beatmap editor every time i switch screens, but i hope it can be fixed somehow, before i forget this temporary fix of mine.

**Comment by peppy** [comment]
Unfortunately there's no actionable information here. A videocast of your desktop showing this happening in windowed mode may be able to give some clues.

**Comment by livablesummer** [comment]
done:
https://user-images.githubusercontent.com/76008030/115139617-29ccdc80-a033-11eb-9203-ec2ebee99e18.mp4
Like i said, swapping screens the second time fixes everything.

**Comment by peppy** [comment]
This is apparently a "feature" when pressing tab, which means that for some reason the game is receiving a "tab" key when you alt-tab. This may be due to how your keyboard is reporting the keys, or some kind of hotkey software running on your PC. I don't think we can fix this for you, unfortunately, so i'd use a workaround or find the cause at your end.
