### ISSUE TITLE
ColourHax doesn't work for Spinners

### ISSUE THREAD

**Issue by Wieku** [ppy/osu-stable-issues#733]
https://user-images.githubusercontent.com/5307179/115149245-82b46900-a063-11eb-8f43-4686cdd4e063.mp4

It looks like shift number is being saved in .osu file [4 (new combo) + 8 (spinner) + 16 (shift colour by 1)]:
![image](https://user-images.githubusercontent.com/5307179/115149281-a677af00-a063-11eb-81c2-99d5faa2bd0d.png)

But for some reason osu! does not load that information.

osu! version: 20210413 cutting edge

**Comment by peppy** [comment]
Spinners don't have a combo colour, so I think it's correct that it's ignored (just like new combo is). You're going to need to be more clear with expectations here.

**Comment by Wieku** [comment]
It's "explained" in the video. If we set ColourHax for the spinner, hitcircles after it have shifted colours as expected (red instead of blue). But when we save the map and load it again, circles are blue.

**Comment by peppy** [comment]
This is expected behaviour. As I mentioned, spinners are exceptions to the rules and can't have these kinds of flags applied. Same as new combo.
