### ISSUE TITLE
Pressing mouse back button will not dismiss the mod selection screen (and other screens)

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-stable-issues#734]
Back button doesn't work in screens that have numbered options, such as mod selection, beatmap options, "are you sure you want to quit" etc. Pressing escape will dismiss those screens, so it makes sense that the back button will also do the same.

The back button behaves the same as Escape in the beatmap carousel (going back to the main cookie) and other places.

![screenshot](https://osu.ppy.sh/ss/16483856/b3f7)

**Comment by peppy** [comment]
stable is quite feature locked. would appreciate avoiding reporting weird edge case issues like this.
