### ISSUE TITLE
occasionally lag spike to 600ms or more

### ISSUE THREAD

**Issue by arily** [ppy/osu-stable-issues#735]
it happenes in the middle of playing.
sometimes a popup with message 'An error occurred during score calculation' are shown.
the lags are recorded in the replay files and I got couple of them.
bgm continues to play in the period of lagging.
only one dot is shown in the right-bottom corner if 'Detect performance issues' are checked.
it happenes regardless of whether 480fps 960fps or unlimited fps are chosen.

I tried to use latencymon to findout what happened but there's no lag spike system-wide.

**Comment by smoogipoo** [comment]
Provide logs from your osu folder.

**Comment by arily** [comment]
[Logs.zip](https://github.com/ppy/osu-stable-issues/files/6334113/Logs.zip)
[Replays.zip](https://github.com/ppy/osu-stable-issues/files/6334118/Replays.zip)

**Comment by peppy** [comment]
The freezes during gameplay look to be either disk IO or swapbuffer. Usually we don't see the first occurring unless a user is playing from a very slow disk - can you provide more details on your hardware?

The second is more commonly seen when an external application is drawing. If you run multiple monitors, try closing everything on your other monitors. If you have any overlays (ie. discord) or any electron based applications open, try closing them to see if it helps.

**Comment by arily** [comment]
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/6334218/DxDiag.txt)

I have only one monitor, and almost nothing except osu! are running ( I built this pc for osu ), and no electron-based applications running in the background

**Comment by arily** [comment]
![taskmgr](https://user-images.githubusercontent.com/10007589/115201872-a353e180-a0aa-11eb-831b-0d458799a2fc.png)
and taskmgr

**Comment by smoogipoo** [comment]
Does this happen consistently? Can you try turning of REAL?

**Comment by peppy** [comment]
First, this is running windows 7. We generally can't guarantee performance on such an ancient OS.

Second, please test without `REAL` running.

Third, can you play with task manager open and look at what is using CPU when it stalls? It's important you only look at stalls during gameplay, not the ones you're seeing at song select after gameplay (which is osu!'s end).

**Comment by arily** [comment]
> First, this is running windows 7. We generally can't guarantee performance on such an ancient OS.
> 
> Second, please test without `REAL` running.
> 
> Third, can you play with task manager open and look at what is using CPU when it stalls? It's important you only look at stalls during gameplay, not the ones you're seeing at song select after gameplay (which is osu!'s end).

this is win10 with dwm disbaled

**Comment by peppy** [comment]
The more you mention the more it sounds like you've likely caused issues with settings you've changed on the OS. I'd recommend testing on a clean install without changing things.

**Comment by arily** [comment]
> Does this happen consistently? Can you try turning off REAL?

it happenes more often when REAL in on, but still occur when real is off

**Comment by arily** [comment]
in taskmgr osu!.exe uses the most cpu resources and it seems 1core are constantly 100% when osu is running and 2 if in playing
![taskmgr2](https://user-images.githubusercontent.com/10007589/115204884-d6e43b00-a0ad-11eb-9b9c-d3f538942ebd.png)
( i know 960fps could reduce the usage but it still happenes )
and disk0 is where osu is located.

**Comment by arily** [comment]
> The more you mention the more it sounds like you've likely caused issues with settings you've changed on the OS. I'd recommend testing on a clean install without changing things.

I'll try reinstall when I have some time

**Comment by smoogipoo** [comment]
It doesn't really matter that osu! uses the most CPU resources. What matters is if any other application begins using any CPU _at all_, because it means that it's potentially doing some disk operation or otherwise that's taking time away from the driver.

Also, are you adjusting any process priorities to realtime? Never do this if so.

**Comment by arily** [comment]
> It doesn't really matter that osu! uses the most CPU resources. What matters is if any other application begins using any CPU _at all_, because it means that it's potentially doing some disk operation or otherwise that's taking time away from the driver.
> 
> Also, are you adjusting any process priorities to realtime? Never do this if so.
other than osu!.exe every other applications are 0% and the second highest usage are Sytem interrupts or taskmgr.
TabletDriversService.exe wanted to be prioritzed to high or realtime so i set it realtime (it complains if priority is too low),
other than that I think no? I will try if change it to high fixes the problem.

**Comment by arily** [comment]
[Logs with dwm reumed.zip](https://github.com/ppy/osu-stable-issues/files/6334685/Logs.with.dwm.reumed.zip)
this is when dwm.exe is resumed and real off.
will occur less frequently than dwm disabled and real on

**Comment by arily** [comment]
also this is maybe useful: I was trying to record the lag using obs and by running obs in background I didn't encounter the lag for serval hours.
I don't know if it's just a illusion or if it really does something...

**Comment by xDololow** [comment]
Can you check if Windows Indexing is on.

**Comment by arily** [comment]
> Can you check if Windows Indexing is on.

it's on I think.

**Comment by xDololow** [comment]
> > Can you check if Windows Indexing is on.
> 
> it's on I think.

It can cause lags on HDDs

**Comment by arily** [comment]
I've found out that some beatmaps triggers this stuttering 100% the time.
https://osu.ppy.sh/beatmapsets/39032#osu/204536 like this one,
stuttering are expect to happen from enter the map to about 20 sec (every time it's different)

**Comment by arily** [comment]
> > > Can you check if Windows Indexing is on.
> > 
> > 
> > it's on I think.
> 
> It can cause lags on HDDs
HI, 
I've tried to turn off windows indexing and stuttering still happenes,
I don't have any hdd installed, only ssds.
and I tried copying files from the disk where osu is located and this does not increase the odd of lags.

**Comment by peppy** [comment]
Based on your custom and outdated operating system and the fact that this is most likely only applicable to you, I'm going to close this. We can't really provide per user performance help here. I would recommend updating to a newer operating system and avoid running custom apps like REAL in order to get a normal performance profile.
