### ISSUE TITLE
Unranked maps giving total score 

### ISSUE THREAD

**Issue by MANi-kun** [ppy/osu-stable-issues#736]
So I'm not 100% sure on this one but I think this shouldn't happen based on this 
![image_2021-04-21_211534](https://user-images.githubusercontent.com/80633810/115608554-b7842280-a2e6-11eb-87a7-0aa71774d5f7.png)
Even if it isn't a bug I thinks that's bad because people can level up super easy by just playing 4* maps that have 2k combo buzz slider before streams 
![unknown (3)](https://user-images.githubusercontent.com/80633810/115608887-21043100-a2e7-11eb-9d92-b1b27609ab69.png) before the play
![unknown (4)](https://user-images.githubusercontent.com/80633810/115608914-2792a880-a2e7-11eb-8c26-24783694f569.png)after play
![Screenshot_1](https://user-images.githubusercontent.com/80633810/115608938-311c1080-a2e7-11eb-8598-eaa1d4aff6be.png)
![Screenshot_2](https://user-images.githubusercontent.com/80633810/115608940-31b4a700-a2e7-11eb-8732-e25fc317001b.png)

**Comment by peppy** [comment]
this is intentional
