### ISSUE TITLE
osu! constantly lagging when OBS and/or discord video playback is running in the background 

### ISSUE THREAD

**Issue by hammytr** [ppy/osu-stable-issues#737]
It's as if osu! is constantly skipping 2-3 frames when I have OBS open, a twitch stream, or a discord stream in  a voice call.
It doesn't happen when I run osu! in Compatibility mode, but that comes with its own issues (i.e. can't tab back into the game properly, more delayed gameplay)

**Comment by peppy** [comment]
May I suggest closing those applications, or running with compatibility mode?
