### ISSUE TITLE
osu! beatmaps are not recognized upon daily relaunch

### ISSUE THREAD

**Issue by chiv1** [ppy/osu-stable-issues#739]
hi! i don't know how to explain this very well, but for the last 2 days when i've launched osu only 6k/27k beatmaps on my pc are actually identified on the client - prompting me to refresh the beatmaps, and removing all the local scores from the client itself.

I've asked for help from some people around, and yesterday I was able to save those local scores in the client by accessing the hidden r file in osu's hidden data file and dragging all the osu files into the client itself. however, today the method didn't work and i was wondering if there was any way i could preserve these scores on the client themselves. 

i don't know exactly how i can prove this, but an example is that yesterday 
![chrome_X8QCHoU9XA](https://user-images.githubusercontent.com/83040046/115786402-9fa7af80-a375-11eb-9cdb-cf5ac7044f4a.png) i was able to set a score, 
![screenshot505](https://user-images.githubusercontent.com/83040046/115786431-a9c9ae00-a375-11eb-8bf3-46ee1ab4377e.jpg) and it was properly represented on the global / country rankings. however, upon accessing my local scores, it  doesn't appear, despite being set a mere day ago due to the beatmap refresh.
![screenshot506](https://user-images.githubusercontent.com/83040046/115786476-b948f700-a375-11eb-93fc-c2d7667ad646.jpg)

of course, i don't know if this issue will consistently happen over the next week, but it has happened 3 times in a row now, so i was wondering if you guys had any fix or if this was a known issue. I checked the previous logs of the issue, and the only response was that the problem has already been solved 2 years ago, so my game might be corrupted - although i have utilized the osu repair tool in an attempt to fix this.

thread in question -> https://github.com/ppy/osu-stable-issues/issues/151

thank you for your time!

**Comment by peppy** [comment]
this happens when something has changed the files in your songs folder. check whether the missing beatmaps are actually there in the first place.

closing as a non-bug, but feel free to reply.

**Comment by chiv1** [comment]
understandable, i appreciate the reply though

after some further digging, i looked into my songs folder and all the maps are there - of course, this was after the beatmap refresh, so all the songs are also on the client, and i restarted my computer twice just to make sure this wasn't just a boot-up on launch issue. it's hard for me to verify if this issue will come again, so i plan on checking the songs folder before i launch osu tomorrow just to verify that this issue persistently occurs.

furthermore, however, one of my friends linked me a picture https://cdn.discordapp.com/attachments/807838844036317204/834901213346398338/chrome_Vrx1Tbjomu.png from some osu forum that gave the code for a batch file - opening all the files in quick succession. after changing the path destination it still didn't work, as well as dragging all the replays in from the hidden r folder, but the only actual method that enables me to see the local scores is by individually dragging the replay file in.
![screenshot507](https://user-images.githubusercontent.com/83040046/115809743-861c5d00-a3a1-11eb-8fb1-2f2485cab143.jpg) this is the same belief map that didn't have the original local score

again, thanks for your time as i'm kinda out of ideas besides individually dragging them in, honestly anything helps!

**Comment by chiv1** [comment]
nevermind! i was able to solve it by deleting the score.db file and letting the /r file remake all scores. thank you for your time peppy!

**Comment by ihyvini** [comment]
hi there @chiv1 , 
apparently im going through the same issue and im glad to find you've fixed it even though your comment is so old i hope you're active lol , every day my beatmaps go from 500+ to 88 or so . I usually click on "repair osu!" or drag the "collection" file to osu application and it works , but its a hassle to do that every day .
could you explain how you fixed that please and thank you :)
