### ISSUE TITLE
failed multiplayer scores are saved as long as you live at the end

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-stable-issues#74]
makes it look like you passed the map with nm

![](https://i.fiery.me/ORJU.png)

# steps to reproduce:
- create multi lobby
- start map, die on purpose (for example, don't play the first half)
- make sure to revive before the map ends
- exit lobby
- view local ranking
# screenshots/video:
obviously failed play:
![](https://i.fiery.me/U7sF.png)
# logs:
- none
# version/setup:
- latest ce (`b20190921cuttingedge`)
- windows 10 18362.356 (64 bit)

**Comment by InvisibleSymbol** [comment]
After some discussion with other players, the best solution would be to show an `F` instead of the grade, but that would require work on the default skin/all other skins.
Feel free to close this if the scope is too large.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge build (won't automatically save, but can still be exported via F2).
