### ISSUE TITLE
Beatmap status not updated automaticallly anymore

### ISSUE THREAD

**Issue by DGmGosu** [ppy/osu-stable-issues#742]
peppy told me to post this here, so ill try my best:

when going into editor and out to check on a pattern or something (without changing anything) or when downloading a new map the maps status becomes "unkown" and wont update until you hover over each difficulty. this used to happen automatically until the Stable 20210423.2 update.
There is also no "beatmap calculation" in the bottom right anymore when downloading new maps, idk if that is connected with that.
Here is a video as requested: https://www.youtube.com/watch?v=sSLfGXJuTy8

**Comment by peppy** [comment]
Right, so this is when you're using the editor on ranked beatmaps. That shouldn't be such a common case, but I'll check and see why this started to happen.

**Comment by peppy** [comment]
You are implying that this changed recently, but we've made zero code changes which could change this behaviour. I'm inclined to say that this is how it has always worked.

**Comment by DGmGosu** [comment]
maps used to stay "unknown" until this got fixed https://github.com/ppy/osu-stable-issues/issues/406 after that fix everything updated automatically and with the recent update the newly downlaoded maps are staying "unknown" again like in the video
im downloading new maps with sorting by ranked status every day. i dont know what code changes there were, im just stating what im experiencing

**Comment by peppy** [comment]
You can try deleting your local database if you think it's not in a good state. I'm not sure we can action on this though.

**Comment by DGmGosu** [comment]
i deleted the local database last week but that didnt help, didnt want to bother here anymore for a small thing like that so i ignored it.
today tho it fixed itself and everything works as it did before the update
