### ISSUE TITLE
allow time signatures other than 3/4, 4/4, 5/4, 6/4 and 7/4 in the timing panel ui

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu-stable-issues#745]
just set the range from 3 to a high number like 20 or something.

Currently for this to be achieved, manual editing of the .osu file is required. This turns a 5 minute job into a 30 minute one, because i have to add a timing point, save, exit, open the file in a text editor, locate the right line, change the number, save and open the map again, rinse and repeat because in this case there are multiple timing points needed because time signature changes frequently.

example song where this is needed https://www.youtube.com/watch?v=6L_5eQaXt9Q

![2021-04-30_20-51](https://user-images.githubusercontent.com/5400432/116727666-e9d40500-a9f5-11eb-9d38-725af1770c49.png)

**Comment by peppy** [comment]
I'd say if this is going to happen it will be in lazer. we've already added most of the edge cases in and adding more is probably only going to resolve your one beatmap.

**Comment by Kyuunex** [comment]
oh, I just assumed you only had to change one integer to make this happen.

nevermind i guess

**Comment by peppy** [comment]
I did have a quick look into things and it's quite involved (and subject to potential breakage since it's working with winforms, which I don't really have tooling working for any more).
