### ISSUE TITLE
Osu! Stable does not seem to play nice with newer graphic cards(Nvidia 20+series mostly)

### ISSUE THREAD

**Issue by Xylotic** [ppy/osu-stable-issues#746]
I recently just because aware of how terrible my fps is Osu! STD is, with an RTX 2060 and all background tasks closed, I'm getting 460 fps and random lag spikes. This is coupled with high GPU usage(90-100% ). Compatibility is turned off, and all in game overlays are also off(DC, NVIDIA, Microsoft). Would like to add that I am not CPU bound(Ryzen 9 3950x)

Example of fps and input frame lag with STD(this was with high polling rate, so that problem is fixed)
![screenshot034](https://user-images.githubusercontent.com/83620911/116949243-aa085a00-ac4f-11eb-965d-cea8aadd8fca.jpg)

My FPS in Lazer is also quite low
![osu_2021-05-03_20-28-22](https://user-images.githubusercontent.com/83620911/116949174-76c5cb00-ac4f-11eb-8c11-83d8c9c3d8f4.jpg)

This issue isn't just limited to me however, a quick look around forums and reddit finds many issues like mine's which makes me believe that something with Osu! STD is breaking the GPU's. I have no idea and I hope you can look into this, a almost 50-60% frame cut just by playing the game indicates at least *something*  is going on.

**Comment by Xylotic** [comment]
Just to add for reference, most Nvidia 1060s run Osu! at 1k fps, and a 2060 running it at 400fps is quite absurd. Unfortunately, my programming knowledge is very limited so I have no idea to what might be causing this issue, but I do believe that something with Osu! and the 20 series cards is broken. Another person I found having this issue is here, but with a RTX 2070. https://osu.ppy.sh/community/forums/topics/1313837, couple posts down

**Comment by peppy** [comment]
450fps is already more than enough and easily double your refresh rate. You should NOT be running any games that high. This could be the driver intentionally limiting frame rate to avoid screen tear or unnecessarily overworking your GPU.
