### ISSUE TITLE
Beatmaps not Categorizing Properly, Again

### ISSUE THREAD

**Issue by dudemanPN** [ppy/osu-stable-issues#748]
Unfortunately, I am back with the same problem of beatmaps not properly categorizing themselves. It was fixed about a week ago in my other post https://github.com/ppy/osu-stable-issues/issues/747. Sorry I don't really know how to link it properly. I don't know what happened and why it just stopped working after being fixed. 

I tried reinstalling the client and the other solutions previously mentioned but they also didn't work. This time, hitting F5 will not always categorize them properly. Sometimes it takes two or three refreshes to categorize it. 

I really want to solve this problem because I want to continue playing the game.

Thank you in advance.

**Comment by peppy** [comment]
Please post on the previous issue.
