### ISSUE TITLE
Offset frequently fluctuates on game openings

### ISSUE THREAD

**Issue by tzechiK** [ppy/osu-stable-issues#749]
sometimes when reopening the game, the audio offset can change on it's own, without any clear reason. noticeable on standard, but it's severe for no hitsound taiko and mania players. 

for example, i have to use -50 global offset since i play taiko and mania without hitsounds and rely on my keypresses, but occasionally when i reopen the game, i have to use roughly -110. have tried closing other tabs and such but the global offset i have to use still changes between the 2 values -110 and -50. will gladly send more details if needed

**Comment by peppy** [comment]
Thanks but this is not a tech support forum. You may want to post on the osu! help forum for help with your PC setup, or contact your manufacturer.
