### ISSUE TITLE
Top 50 scores without spinner are getting removed from the global leaderbaords sometimes

### ISSUE THREAD

**Issue by Gracidea16** [ppy/osu-stable-issues#75]
I really don't know, how to explain this issue, but I will give it a try:

Sometimes, my scores are disappearing from the global rankings entirely. This happens exclusively to scores on maps which contain no spinners.

In the following example, we see my score and submittion time on the map [Mrs. GREEN APPLE - Inferno (TV Size) [Normal] mapped by Amandia.](https://osu.ppy.sh/beatmapsets/999645#osu/2090848)

![](https://puu.sh/Ejp8K/3ffbe60f00.jpg)
As shown, my score was submitted on 2019/07/25, 00:50:02

![](https://puu.sh/EjpdT/165fd51f5e.jpg)
Pieruk's score was submitted on 2019/07/25, 00:46:10
![](https://puu.sh/Ejpel/1cbeee3686.jpg)
Fear's score was submitted on 2019/07/25, 01:38:04

As result, my score should show up between these. But it doesn't, even though I have the exact same score.
![](https://puu.sh/Ejpvx/f1037b5ec9.jpg)

Well, actually it does but only on the website.
![](https://puu.sh/EjpyM/c47bc92fc8.png)

**Comment by Magnus-Cosmos** [comment]
This seems to be an issue with old-web (https://github.com/ppy/osu-web/issues/4190), as the client grabs leaderboards from old-web, which your score is missing as well (https://old.ppy.sh/b/2090848)

**Comment by peppy** [comment]
This should be fixed via the underlying infrastructure changes that will be in place when https://github.com/ppy/osu-web/pull/5290 is merged.

**Comment by peppy** [comment]
Closing this for now.
