### ISSUE TITLE
Taiko Mode: Extremely Low Base SV Unskippable Lead-In

### ISSUE THREAD

**Issue by ReiFan49** [ppy/osu-stable-issues#750]
## Issue I'm having

a taiko map that starts with very long lead-in time that is unskippable for some reason. (tl;dr, check attachment to understand this.)

## Screenshots

![Full editor pic](https://osu.ppy.sh/ss/16575454/6a7a)
(Base SV 1.4, Green Timing 0.01x, leadin around 180 seconds)

![memes](https://cdn.discordapp.com/attachments/841320372251263017/841466629594415125/unknown.png)
(Base SV 0.4, Green Timing 0.01x, leadin close to 660 seconds)

## Replicate

1. make your own taiko map
2. set offset to 0ms for both red and green timing
3. set the green timing speed multiplier to **0.01x**
4. tada, unskippable super long lead-in time.

## Notes

from what I observe, for maps with **non 0ms offset** that **have different base SV from other diffs**, have potential different lead-in. an example is [this mapset](https://osu.ppy.sh/beatmapsets/1425422), just compare the WITCH and non-WITCH difficulty lead-in difference.

my [recent map](https://osu.ppy.sh/beatmaps/2996818?mode=taiko) which triggers that bug for examining (just change the green timing on 0.5ms to 0ms to see the behavior of this)

what I wondered is the first note came after 8 barline, which makes the "SV based lead-in" kinda strange when the note itself came with normal speed or something.

## Attachments

Here are the files to try for the bug testing ([slightly modified from the original](https://osu.ppy.sh/beatmaps/2996818?mode=taiko):

* [180 seconds lead in](https://cdn.discordapp.com/attachments/265909019976138754/842216468589445120/Rei_Fan49_-_Concealed_the_Conclusion_Conclusion-Side_Medley_Rei_Hakurei_Lunatic_LEAD-IN_180.osu)
* [660 seconds lead in](https://cdn.discordapp.com/attachments/265909019976138754/842216468158349353/Rei_Fan49_-_Concealed_the_Conclusion_Conclusion-Side_Medley_Rei_Hakurei_Lunatic_LEAD-IN_660.osu)

**Comment by peppy** [comment]
Thanks for the report. A fix for this is in the pipeline and should hit in the next cutting edge release.
