### ISSUE TITLE
ranked status icon with weird angle

### ISSUE THREAD

**Issue by acrylic-style** [ppy/osu-stable-issues#751]
this is just a purely visual bug and can be fixed by going to the approved map, or simply re-entering the map selection screen.

how to reproduce:

https://user-images.githubusercontent.com/19150229/118006857-97480080-b386-11eb-90c8-f52ba00b76ad.mp4

**Comment by peppy** [comment]
Looks kinda cool, not sure we need to fix it.

**Comment by rowario** [comment]
I always thought this is a feature, not a bug 😮

**Comment by peppy** [comment]
Let's just leave it be.
