### ISSUE TITLE
/nping maps links to the wrong difficulty a lot of the time

### ISSUE THREAD

**Issue by xxxzelda101xxx** [ppy/osu-stable-issues#752]
Playing on cutting edge

video: https://www.youtube.com/watch?v=BuWFnNgWYug

This happens consistently. The link the /np makes does link to the correct difficulty. A friend receiving the message and clicking the map is also sent to the wrong difficulty.

**Comment by peppy** [comment]
"The link the /np makes does link to the correct difficulty" this contradicts your report. Can you explain what you mean?

**Comment by xxxzelda101xxx** [comment]
What I originally meant is that if I /np'd a map and looked at the link it in the chat, it would match with the url if I opened the beatmap in a browser.

On closer inspection I just noticed that maybe this is caused by the links being incorrectly formatted? There is a # in the link (presumably to specify mode) but no mode is specified and there is no / between the beatmapset id and the beatmap id so osu! doesn't know which difficulty to go to.

![image](https://user-images.githubusercontent.com/8886218/118082619-1c311b00-b383-11eb-8659-268ff7db5405.png)

**Comment by peppy** [comment]
Could you please provide the failing link in text form, rather than a screenshot?

**Comment by xxxzelda101xxx** [comment]
Sure thing, used /savelog and just copy/paste

https://osu.ppy.sh/beatmapsets/349883#771495

**Comment by peppy** [comment]
Issue seems to be a missing slash. Will get this fixed for the next release, thanks for the report.
