### ISSUE TITLE
SV does not work properly on beatmap start in mania

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#753]
The issue appears in following beatmap and prevents it from getting ranked:

https://osu.ppy.sh/beatmapsets/1349658

The problem is that right now the SV at the start does not work properly without adding an additional timing point before the _actual_ first timing point.  

And that's a problem because it conflicts with the Ranking Criteria. This one states that no unnecessary timing points are allowed in a beatmap. 

However, even when we would make an exception for this case, what really should not be done as Rules count equally for everyone. This is definitely a Bug and should be fixed as with the increasing popularity of SV usage in mania, this issue might appear much more often in the future. 

To reproduce the issue: Testplay the beginning of the beatmap in it's current state, then remove the following timing point: 
-1058,352.941176470588,1,1,1,15,1,8

Then testplay the beatmap again, you will see that the SVs by the green lines are completely ignored. 

But it should actually work like it's right now, without needing to add another timing point. 

We would really love to see that fixed because it's really a bummer to see an otherwise completely fine beatmap being stopped from getting ranked because of a bug.

**Comment by peppy** [comment]
Does it work on lazer?

**Comment by Feerum** [comment]
Just tried it in lazer. 
There it seem to work as intended. The additional timing point is not necessary to make the SV work there

**Comment by Unpredictabl3** [comment]
any update on this? been a while since a response had been made so I want to revive this again since the mapper would like to push the map in it's current state as stated before.

**Comment by peppy** [comment]
No update yet. This is still on my todo list but as it only affects one known beatmap (and is already fixed in lazer) it's a relatively lower priority. If this means the mapper decides to workaround the issue then that may be the best path forward for now.

**Comment by smoogipoo** [comment]
This will be fixed in the next release. Please try it out any point out if any issues occur with _other_ beatmaps ASAP.
