### ISSUE TITLE
api v1 shows different results with easy than what shows in-game (osu!catch)

### ISSUE THREAD

**Issue by wesley-221** [ppy/osu-stable-issues#756]
When trying to get data from the api while applying the easy modifier to the url, you will get very different results from what you get when adding the easy modifier in game. This seems to only affect osu!catch specific beatmaps, converted beatmaps however will have the close to the same star rating. 

**osu!catch specific map:**
https://osu.ppy.sh/beatmapsets/776495#fruits/1631468 (Rain difficulty)
In game star rating (+Easy): 3.43
api v1 star rating (+Easy): 3.95668 (api/get_beatmaps?k=KEY&m=2&b=1631468&mods=2)

**Converted beatmap:**
https://osu.ppy.sh/beatmapsets/148092#osu/366383 (Extreme difficulty)
In game star rating (+Easy): 3.01
api v1 star rating (+Easy): 3.0279 (api/get_beatmaps?k=KEY&m=2&a=1&b=366383&mods=2)

**Comment by smoogipoo** [comment]
This is because we haven't forced an update of SR values in the client. Reimporting the beatmap will fix this.

And always trust the API to give the most up-to-date values.
