### ISSUE TITLE
Nearby Filter range displaying far more players

### ISSUE THREAD

**Issue by scheisseosu** [ppy/osu-stable-issues#758]
When using the nearby filter, it is showing hundreds of players from a far greater than expected distance.

![image](https://user-images.githubusercontent.com/44596843/118899538-ef2dbc80-b8dc-11eb-9c23-58e3562eefac.png)

For example, in this picture, it displays Skill who I believe should be in Florida, even though I am in Indiana. 

The Nearby filter used to work as expected, showing 10-15 people no more than 30 miles away or so. However when updating both my laptop and pc to either Cutting Edge Cutting Edge 20210519.1 or Stable 20210519.3 the bug started occurring. I cannot remember in which version it was last working for me, but I have been experiencing the issue for at least half a year IIRC.

**Comment by scheisseosu** [comment]
Additional note: when testing today from my laptop which still had an older (maybe ~1/2 year old) stable version of osu, the nearby filter appeared to be working fine, only to break again when I updated the game. I believe this should rule out issues with my network connection settings.

**Comment by peppy** [comment]
That's how location works. It depends on the data available and what your ISP offers, and how your ISP works. And the alignment of the planets. It's not intended to be accurate.

**Comment by scheisseosu** [comment]
I understand that it's possible for external factors to make precise location filtering unavailable. But nothing about my ISP or location changed between the time I had it working precisely on one version, and then it being inaccurate a minute later after updating to the current version.

**Comment by peppy** [comment]
Do you work for your ISP? If not you cannot make such a statement.

Please google around and understand how IP location lookups work.
