### ISSUE TITLE
osu! cursor makes the game UNPLAYABLE, always drags behind, moves faster/slower on different parts of the screen

### ISSUE THREAD

**Issue by Mercron** [ppy/osu-stable-issues#759]
Ever since I came back a few years ago I felt that my cursor movement was really different. I had bought a new monitor and the game felt really clunky, the cursor was hard to handle, I would make small movements and the cursor would go flying and then come back to the original position.

I reinstalled windows a few times and it seemed to help a bit, but it still feels like it drags behind or accelerates randomly (happens on 2 different tablets and like 5 mice, its not a hardware problem). It happened on 2 computers aswell, laptop and PC.

I thought it was me that was going crazy but not too long ago I found out that if you open the game and then press windows+ P, select any screen projection mode and then go back to PC screen only, the cursor stops dragging behind, but it keeps randomly accelerating.

I also found that if I spin my cursor right in the middle of the screen in osu! and then alt tab, the same hand motion I was doing yields totally different cursor movements on the desktop. This happens on fullscreen, and windowed I still get the acceleration going but to a lesser extent, and its much laggier because its windowed. I have tried this so far:

-Reinstalling from a clean iso file

-Installing ubuntu and playing from there on both lazer and a lutris version of the game (same issue, nothing changes)

-Deleted the configuration files found on HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers CONFIGURATION, CONNECTIVITY and SCALEFACTORS. Then I rebooted and on some areas of the screen when I moved my cursor the cursor FPS fell to like 10, it was super weird. If I alt tab it sometimes goes away, weirdest thing ever

-Changed scaling to 100% on custom scaling and normal scaling, on regedit, etc, nothing worked. Also clicked on every single possible combination of compatibility options on the game's executable.

-Also tried every single option in the menu, raw input on, off

-I dont have to say this, but windows acceleration off, 6/11, markC fix etc

-Disabled windows ink workplace, did nothing

-Reinstalled graphics drivers with DDU 1 million times and booted on safe mode, nothing worked

-Tried with 2 different graphic cards and older drivers, nothing

-Updated windows a million times aswell, nothing

-Disabled file integrity or whatever on windows

-Disabled windows defender

-Tried ONLY plugging the tablet and keyboard to see if its something thats clashing with my hardware

-Changed scaling settings on nvidia control panel

And why am I so sure that im not crazy and the game is really not working as it should? Because I have a 10 year old laptop and I have tried it, it runs on 30 fps but the cursor is NIGHT and DAY from my last gen PC.

**Comment by peppy** [comment]
so you mention it's better on your old pc. which is likely running windows 7 or order, which means there's only one issue and one solution here:

you are not running in exclusive full screen. you are either running borderless or windowed.

no application can bypass desktop composition in these modes. if you want the lowest latency, you *have* to run in exclusive fullscreen.

**Comment by Mercron** [comment]
Its not about latency, its about having weird and unexpected behaviours and also latency, but latency isnt the issue. I run the game on fullscreen, not windowed or borderless. Its why im asking, since I have tried everything else.

**Comment by peppy** [comment]
It's likely something with your setup. If as you say you've already tried multiple operating systems, i'd turn my head to your USB devices, and how you have things setup. It might be either your input devices, or something between them and the PC (or another device on the same hub).

Try different USB ports, check your BIOS settings (reset to defaults), make sure you're on the latest windows 10 with all updates.

Can't really offer more than this; you may want to contact your PC manufacturer for further help.

**Comment by Mercron** [comment]
It happens on a windows 10 laptop aswell as my main PC, the window 7 laptop works well. I changed every single piece on my PC and it still happens. I have no idea why this happens but contacting my manufacturer didnt work, so I thought I could look for help here. Btw, I tried playing on a friend's PC and this also happens to him (weirdly enough when you move the cursor slowly on his PC the cursor stars jumping, like if it was dragging and skipping pixels). Its unplayable for both of us...

**Comment by peppy** [comment]
Considering this is only affecting you, and not the million odd other players, I think this may either be an issue with your perception, or something you are applying in all cases (something you have running on all systems; some tweak you are performing; some device you are connecting; local magnetic fluxes?)

Regardless, I'm sorry to say I don't think we can help you further. If you can provide a video showing what is occurring (should be less than one minute and *clearly* show the issue beyond doubt) I am willing to take a look, but apart from that, this is not really a support forum and we'll have to leave it here.
