### ISSUE TITLE
"unplayed=" filter doesn't work properly

### ISSUE THREAD

**Issue by Ganondorfosu** [ppy/osu-stable-issues#76]
Some maps that have already been played still show up when using the "unplayed=" filter even if the achieved ranks (SS/S/A etc) are displayed on them and even if there are local scores set. The only way to prevent this is to click on each map for the game to check if a score has already been submitted.

I think the filter should not take maps with achieved rank/local scores into account or a new filter such as "rank=(SSH/XH to None)" could be added.

![screenshot1979](https://user-images.githubusercontent.com/55597697/65346336-c8395780-dbdc-11e9-915d-f6706f9a9509.jpg)
![screenshot1980](https://user-images.githubusercontent.com/55597697/65346350-cf606580-dbdc-11e9-8c43-dbe193247517.jpg)

**Comment by MillhioreF** [comment]
Should behave a bit better in next cuttingedge.

**Comment by E223** [comment]
Seems like whatever was changed here may have broken the "unplayed!=" filter in the process? Never used that filter personally, but it was reported [on the forums](https://osu.ppy.sh/community/forums/topics/965094) and it seems like it may have worked before.

**Comment by MillhioreF** [comment]
Fixing that particular case without undoing this fix would require quite a bit of time investment. Will consider it but I'd recommend they use group sort or the `played` filter instead for their case, e.g. `played>9999999` should have the effect they're looking for.

**Comment by Magnus-Cosmos** [comment]
This isn't really an issue, but I noticed that at `played>737334`, the filter stops working, doesn't need a fix though, since it works fine or lower numbers, just thought it was a bit weird/interesting
https://streamable.com/cnzk1
