### ISSUE TITLE
An Specific Number as a timing point will crash the game,

### ISSUE THREAD

**Issue by Waveium** [ppy/osu-stable-issues#761]
Timing point: 21733,-0.00000000000000000000000000000000000000001,4,1,0,100,0,0
Steps to reproduce: Add timing point or use the map provided here: https://osu.ppy.sh/beatmapsets/1469171#osu/3016401
Click timing point panel, Pippi crash log: 
[pippi crash.log](https://github.com/ppy/osu-stable-issues/files/6525332/pippi.crash.log)
version: b20210520.1

**Comment by peppy** [comment]
It sounds like you are editing the .osu file.

This is not supported.
