### ISSUE TITLE
When press Ctrl+< , osu! get lag

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#763]
I found it when I mapping
I use `Ctrl+<` and osu! get no response until I unpressed.
It makes shortcut useless.
And no matter where once I press ctrl+< it will lag
[Logs.zip](https://github.com/ppy/osu-stable-issues/files/6528319/Logs.zip)

**Comment by peppy** [comment]
This is going to be something else on your PC, not osu!.

**Comment by cdwcgt** [comment]
I ask my friend to try, and they have the same problem

**Comment by peppy** [comment]
Your logs show nothing. I cannot reproduce. This is something you are going to need to investigate at your end.

**Comment by cdwcgt** [comment]
Ok,I will run osu! in a VM machine and reproduction this issues

**Comment by cdwcgt** [comment]
[2021-05-24_00-38-13.zip](https://github.com/ppy/osu-stable-issues/files/6528397/2021-05-24_00-38-13.zip)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6528398/runtime.log)

**Comment by peppy** [comment]
At a guess, it's something to do with your chinese input system settings. Please check the shortcuts you have assigned to them.

**Comment by cdwcgt** [comment]
I check, it may nothing
and even I use English IME it still lag

**Comment by cdwcgt** [comment]
[performance.log](https://github.com/ppy/osu-stable-issues/files/6528444/performance.log)
I saw `Slow Frame Detected` so I upload this performance log

**Comment by peppy** [comment]
It's showing delays in the windows loop, ie. something else on your system.

**Comment by cdwcgt** [comment]
but It's no effect in other games and programs
and I uninstall chinses language pack in my VM and it's still lag

**Comment by peppy** [comment]
Can you reproduce on lazer? If so, we may be able to look into it further. Else it's out of scope.

**Comment by cdwcgt** [comment]
it's normal in lazer

**Comment by cdwcgt** [comment]
I use [process hacker 2](https://processhacker.sourceforge.io/) to analyze threads and it said thread `osu!.exe+0x402626` get into wait state(Wait: WrUserRequest)
![image](https://user-images.githubusercontent.com/34775378/132953560-30240a01-ef69-4ec4-9354-251733e7913f.png)

hope this is helpful

**Comment by peppy** [comment]
This means something else on your system is likely handling that key press and blocking on it.
