### ISSUE TITLE
Osu! HDR Compatibility

### ISSUE THREAD

**Issue by Wheatcake** [ppy/osu-stable-issues#764]
Original Posted on Osu! forums: https://osu.ppy.sh/community/forums/topics/1236267?start=unread

Problem details:
Since I started playing Osu! not long ago, I realised that whenever I launched the game (in fullscreen mode) HDR would turn off, making the overall brightness lower than I'm used to.
I got used to this after time, but suddenly after a couple months HDR started working in fullscreen and now it has stopped working again.

Is anyone else having this issue where you launch or play Osu! in fullscreen mode and HDR gets turned off?
I have to go into Win10 settings to turn it back on, but then when I launch Osu! or make it my active window, HDR turns off again.

**Comment by smoogipoo** [comment]
I don't know why it would suddenly start and stop working - perhaps it's to do with compatibility mode if that's what you're using. We'll eventually look at updating it again, but it's not the highest priority for now.

It's safe to say that this can't be fixed in stable due to the way things work. I believe you need to set the colour bit depths to different values, but we don't have a process to fall back if this fails.

**Comment by Wheatcake** [comment]
The issue is fixed when I use compatability mode. But compatability mode also increases my input latency a lot. So I'll probably just stick with it until it maybe gets fixed in the stable version or something.

But thank you. :)

**Comment by telnet-addictions** [comment]
> I don't know why it would suddenly start and stop working - perhaps it's to do with compatibility mode if that's what you're using. We'll eventually look at updating it again, but it's not the highest priority for now.
> 
> It's safe to say that this can't be fixed in stable due to the way things work. I believe you need to set the colour bit depths to different values, but we don't have a process to fall back if this fails.

is it still impossible to fix this? @smoogipoo

**Comment by peppy** [comment]
If you are on windows, you can adjust HDR settings using game bar overlay.
