### ISSUE TITLE
Osu mania does not open ''Hidden'' and ''Fadeln'' mods.

### ISSUE THREAD

**Issue by RobanoShippo** [ppy/osu-stable-issues#766]
When I try the play osu mania in my computer i can't play hidden and fadeln mods. I tried other game play modes with hidden and it's ok. Just osu mania does not open. I deleted osu and downloaded again for a solution but it didn't worked. I tried it in another skins, it didn't changed. 
This is default osu skin, first time i downloaded osu this skin was already downloaded.
![Default](https://user-images.githubusercontent.com/84748196/119411548-45429b80-bcf3-11eb-9a85-af67de558827.jpg)

And this is another skin. I checked it support the all game play modes and mods. I saw it in a guys video.
![Another Skin](https://user-images.githubusercontent.com/84748196/119411623-61ded380-bcf3-11eb-9ee5-ba8cf16c45b0.jpg)
### Another Issue I Have About osu!
There is something else too. I have an issue about downloading osu! in my computer. I deleted osu! from my device because I thought hidden and fadeln modes could be fixed. While reinstalling, I got a message saying that the application was already installed on my device. If you use an application called "Your Uninstaller" to delete an application, you know, it scans and deletes everything belonging to the application to be deleted on the device. I'm using ''Your Uninstaller'' to delete an application from my computer. Despite that, I got the message. I didn't care, I chose "Upload file and overwrite existing file" from the options. When it loaded, I clicked on it to open it but got a message says osu! crashed. When I said try again, it didn't worked.

**Comment by peppy** [comment]
None of what you are saying makes sense. It sounds like you're downloading osu! from a non-official location.

**Comment by RobanoShippo** [comment]
> None of what you are saying makes sense. It sounds like you're downloading osu! from a non-official location.

No, i'm downloaded osu! from official website. https://osu.ppy.sh/home/download here is the link

**Comment by RobanoShippo** [comment]
> Söylediklerinin hiçbiri mantıklı değil. osu indiriyormuşsunuz gibi geliyor! resmi olmayan bir yerden.

then, where can i download osu? can you help me? because i do not have a solution and i need help.

**Comment by RobanoShippo** [comment]
> This can happen if you have overridden `selection-mod-fadein` in your skin. Check the `Skins/User` (for the default skin) and your custom skin's directory for that file, and delete it.
> 
> I don't know what "your uninstaller" is, but I would highly recommend not using it - it is likely not doing what you expect it to.

didn't get something, am i supposed to do folder thing by using osu! or my own pc's folder menu?

**Comment by smoogipoo** [comment]
Your PC's folder menu. Windows explorer. You should use that to remove or change the `selection-mod-fadein` image.
