### ISSUE TITLE
Tillerino /np doesn't work with DT

### ISSUE THREAD

**Issue by naemwear** [ppy/osu-stable-issues#768]
Usually when you message Tillerino /np  it will send you a message saying how much pp the map you are currently listening to will give also the mods you use will be included BUT I was playing a map called Xue Mao Jiao top dif (https://osu.ppy.sh/beatmapsets/789103#osu/1677982) a DT farm map, I watched a video saying an FC can give you 100+pp so typed to Tillerino /np to see how much 95% acc gives but it only gave me the stats for NM. I decided to try fieryrage's anime ban (https://osu.ppy.sh/beatmapsets/1178935#osu/2469345) top dif and Tillerino gave me the same pp for NM and DT
![Screenshot_454](https://user-images.githubusercontent.com/84918419/119839830-215aa200-bf0d-11eb-95ec-f07b1d25eeba.png)

**Comment by peppy** [comment]
I don't run tillerino. You will need to contact them directly.
