### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Exor10** [ppy/osu-stable-issues#769]
So I play on a laptop, and whenever I close osu forcefully (like holding down the power button causing the whole laptop to shutdown) and reboot and open osu, whenever I play I always get this window popping up saying "osu will be doing some maintenance" then making osu unresponsive as well as the laptop,  here's the video ; https://youtu.be/2saYeByuwYE
edit: it also says "Unable to read requested replay file" over and over and over

**Comment by peppy** [comment]
If you need tech support, please post in the help forum. This is a place for reporting bugs, which your issue is most definitely not. There is something broken with your PC / osu! install.
