### ISSUE TITLE
"Always use skin cursor" isn't worked on the all maps with beatmap skin

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu-stable-issues#77]
Maps with beatmap specific skin:
When i try enable "Always use skin cursor", my skin cursor don't appear on all the maps. Mostly maps appear a default cursor or map specific skin cursor.

Screenshot:
![screenshot10848](https://user-images.githubusercontent.com/53025167/65347125-9b863f80-dbde-11e9-808c-72d70157e286.png)

**This red one cursor is from my selected skin.**

Maps with beatmap skin:
https://osu.ppy.sh/beatmapsets/8277#osu/36249
https://osu.ppy.sh/beatmapsets/287873#osu/789130
Skin as example: http://puu.sh/EjroE/118be980d9.osk

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge release.
