### ISSUE TITLE
Game breaking when selecting the option "Ignore beatmap skin" in the middle of a replay

### ISSUE THREAD

**Issue by Aiquo** [ppy/osu-stable-issues#771]
When selecting the *Ignore beatmap skin* option when watching a replay and then pressing the retry button, the map starts off of the exact time you retried, instead of well, retrying from the start. Retrying once more makes the replay start from the beginning as normal, but, the hit objects up until the point you retried doesn't count, similar to the 0bpm bug.

There's a video showing the bug [here](https://streamable.com/eixg1l)

I don't really know why this happens, but it doesn't seem to happen when checking/unchecking other options mid-replay, such as *Disable storyboard*, *Ignore beatmap hitsounds*, etc. It only happens with the *Ignore beatmap skin* option.

**Comment by smoogipoo** [comment]
This is because changing the skin in the middle of a beatmap is sort of hackily implemented. It's a bit too difficult to fix.
