### ISSUE TITLE
'Cancel changes' button in editor allows joining multiplayer lobbies

### ISSUE THREAD

**Issue by Cerebi** [ppy/osu-stable-issues#774]
To reproduce what I found you must be in the editor and have un-saved changes.
If you click on any invite (whether through PM or in public chats) while having un-saved changes in the editor you will get prompted with the usual warning of whether you want to Save / Not save / Cancel the changes you've made to the current map.
If you press "Cancel" you'll remain within the editor but you'll actually join the lobby (you can't see what's inside the lobby, but those inside can see you): ![lobby contents](https://osu.ppy.sh/ss/16668251/dc15)
![editor view](https://osu.ppy.sh/ss/16668257/5b09)
The last screen also shows that I'm recognized as modding by the system even though I'm inside the lobby.
If the match starts, regardless of how many players there are, you won't show up among players either: ![multi game](https://osu.ppy.sh/ss/16668242/1108)

I'm not sure how impactful this is, as it seems you can only chat inside the lobby.
Among the strange things happening there's:
- you can invite players to the lobby (both clicking on username > invite, and using the /invite command)
- if you're editing the map the other players have, you show up as having it too (even though the map is already different due to the changes you're applying to it)
- if you become the host you cannot start the game, assuming you're editing the same map the others have ('!mp start' doesn't work)
- exiting the editor brings you to the lobby selection screen in multiplayer instead of song selection in the editor

I personally find it harmless as it is right now, but I wanted to make this known in case there's more to it than I can see.

**Comment by peppy** [comment]
Thanks for the report. A fix for this is in the pipeline and should hit in the next cutting edge release.
