### ISSUE TITLE
(Editor) The "Display storyboard in front of combo fire" toggle should no longer be present

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-stable-issues#775]
In the editor, more specifically in the Song Setup --> Design tab, as it stands there's still an option to toggle "Display storyboard in front of combo fire" despite the Combo Fire feature has been long discontinued :

![image](https://user-images.githubusercontent.com/36564236/120795461-b724ab80-c563-11eb-8836-2dc669496ae1.png)

not really a major "bug" per se but i happened to stumble upon it by accident and was genuinely wondering "wait how come that this option is still here" 🐇

**Comment by peppy** [comment]
Removed in next cutting edge release.
