### ISSUE TITLE
Remove audio device while map is played desyncs the music

### ISSUE THREAD

**Issue by heyngra** [ppy/osu-stable-issues#776]
## How to reproduce:
**Important: You need to have two audio devices connected.**
1. Launch map.
2. While having the map active, disconnect your main audio device (for example remove your microjack or usb)
3. Pause the game.
Now the sound is still playing, by the second audio device. Even on pause. (IRL it was playing. Obs did not capture it.)

4. Connect your main sound device again, and resume the map.
 
The map music will be desynced from the actual game, (and from my gameplay, most of hits even to beat aren't registered).

Video showing this (the thing in left side of screen is sound devices, so you can see when it disconnects): [here](https://www.youtube.com/watch?v=sYKcvrOO0E0) (too big for github)

**Comment by peppy** [comment]
Please avoid doing this. We can't fix this one sorry. If you can reproduce on osu!(lazer) we may be able to look into it futher.
