### ISSUE TITLE
editor: when editing mania maps, some snapping shortcuts don't work

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#78]
In the editor, the following shortcuts are available:
Shift + 1, 2, 3, 4, 6, 8: Change Beat Snap Divisor to 1/1, 1/2, 1/3, 1/4, 1/6, and 1/8 respectively 

however for some reason, Shift+1, Shift+2, and Shift+3 do not work when editing osu!mania maps. They work when editing maps of the other game modes.

**Comment by nl-tatatat** [comment]
I never even knew this shortcuts existed. Cool!
