### ISSUE TITLE
Osu beatmap file name limit - Can't upload

### ISSUE THREAD

**Issue by dudehacker** [ppy/osu-stable-issues#780]
**Problem Statement**
![image](https://i.ppy.sh/bbaff6aa94d3a8f103723c6e9ed96f00125cdd9d/68747470733a2f2f692e696d6775722e636f6d2f76355470644b452e706e67)

**Metadata**
Title: 戦略的で予測不能なラブコメディのエンディング曲 (TV Size)
English Title: Senryaku Tekide Yosoku Funou na Love Comedy no Ending Kyoku (TV Size)
Artist: 志田黒羽（CV：水瀬いのり）、可知白草（CV：佐倉綾音）
English Artist: Shida Kuroha (CV: Minase Inori), Kachi Shirokusa (CV: Sakura Ayane)
Meta: https://osamake.com/music.html

Osu beatmap naming convention: `Artist - Title (Mapper) [Difficulty Name].osu` 

Title is way too long and RC doesn't provide guideline to shorten it. Not sure if it needs to be shorten either.
Artist is 2 people , so Various Artists doesn't apply to this.
Asking mapper to change name would be ridiculous.
Difficulty name is short and not causing issue.

If filename was in Unicode, this wouldn't be an issue, but currently its in English so it has way too many characters.

**I believe a change on server side is more appropriate to solve this problem rather than RC change.**

I just called it `Osamake ED` for now to upload the map, but this doesn't follow current RC and would be DQ.

**Comment by dudehacker** [comment]
In case you think increasing filename limit is a big problem, I think changing the naming convention also works.
Before: `Artist - Title (Mapper) [Difficulty Name].osu`
After: `Mapper [Difficulty Name].osu` 

The song folder name already contain Artist - Title so its a bit redundant to have it in filename as well.
I think keeping Mapper in the filename is good because in the future you may allow GD to upload the beatmap themselves with the new addition of GD as difficulty owner on web change.

**Comment by peppy** [comment]
This is a limitation imposed to keep the game working on windows, which has a maximum filename length. We cannot easily change this length as it would break usage of the beatmap on certain PCs or installs.

We wouldn't consider changing this (length or format) until lazer is live and stable is deprecated. Please fine a way around this until then, for instance, by shortening or abbreviating. I'm sure beatmap nominators will help you with this.

I understand this is probably not the answer you hoped for, but it's a very rare case and engineering a fix would take days to weeks.
