### ISSUE TITLE
cant see the replay of my first 300pp play

### ISSUE THREAD

**Issue by jveejustin1** [ppy/osu-stable-issues#783]
Hi so when i was trying to pass galaxy collapse in mania with no halftime i got 300pp and i was very happy. But when i finish the galaxy collapse i immediately press esc but when i try to check out the replay i cant watch it for some reason. Can somebody help pls?

Here is the screenshot:
https://osu.ppy.sh/ss/16716890/c7ac

**Comment by peppy** [comment]
Try changing skin or something. This isn't a help forum. Please try posting to the help forum if you need more help.
