### ISSUE TITLE
selection-mode@2x strange visual bug

### ISSUE THREAD

**Issue by iceflarexd** [ppy/osu-stable-issues#784]
**Describe the bug:** 
I don't know how this affects lazer if at all, but in osu!stable, I was customizing a skin when I noticed a strange bug. The selection-mode@2x picture that covers the menu is gone when the version is set to anything equal to or lower than 1.0. I made a short video detailing this bug so you can understand it better than what I can describe here.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/5dbIlc4cgdI

**osu!stable version:** 
b20210520.2

**Comment by peppy** [comment]
so use a higher version?

**Comment by iceflarexd** [comment]
lol fair enough, i just think i might be problematic for someone like me who didnt know this til 30 min of troubleshooting, and since it was the first version of my skin I had it set to 1.0, a lot of other ppl might have done this and never knew why. maybe ill just go make a PSA or something since this probably isnt high on the priority list for you since lazer is a thing

**Comment by peppy** [comment]
read the wiki. version is not an attribute for you to set to whatever you like.

https://osu.ppy.sh/wiki/hu/Skinning/skin.ini
