### ISSUE TITLE
Osu stuttering (maybe after updating windows)

### ISSUE THREAD

**Issue by MofumofuChan** [ppy/osu-stable-issues#785]
I don't know why this keeps happening but it seems to keep getting worse. I tried so many stuff and nothing worked.

[runtime.log](https://github.com/ppy/osu-stable-issues/files/6697672/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/6697673/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/6697674/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6697675/update_success.log)
[network.log](https://github.com/ppy/osu-stable-issues/files/6697677/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/6697679/performance.log)

**Comment by MofumofuChan** [comment]
If this is of any use, I played one song to show the stuttering (I think it's only visible by seeing the average fps drop)
https://streamable.com/hfglq4

**Comment by MofumofuChan** [comment]
I played a bit more to give more results just to make sure of the problem and it seems to be with Sleep? I have no idea what that means though. 
[performance.log](https://github.com/ppy/osu-stable-issues/files/6697878/performance.log)

**Comment by peppy** [comment]
https://osu.ppy.sh/help/wiki/Performance_Troubleshooting
