### ISSUE TITLE
.osu file doesn't go into the .osz package when uploading through BSS

### ISSUE THREAD

**Issue by mustywzki** [ppy/osu-stable-issues#787]
Hi,

I submitted a map (https://osu.ppy.sh/beatmapsets/1501464#osu/3076575) where the .osz is lacking the .osu file. Meaning that when you download the beatmap set, you only get the audio, background and custom hs. However, the website got the .osu file because it can show stats and you can actually download the map over at https://osu.ppy.sh/osu/3076575

I figured I did something wrong with the upload at the time. So I tried to:
- create a new difficulty and upload from this new one, didn't work.
- reset the beatmapid thing in the .osu file, didn't work.
- re import the map by dragging the mp3 into the game as if it was a fresh new map, didn't work.

However, I noticed that when you export the .osz in the editor, the difficulty is actually in the package though!

As i was in voice chat with Zyf at the time, we did some testing, and i actually gave him my entire set to see if he actually succeeds in successfully uploading it, and it actually did: https://osu.ppy.sh/beatmapsets/1501524#osu/3076643

After that, I accidentally submitted a second beatmap set with the exact same map on my account (Musty), but it still doesn't work. I figured it would be something to do with my own client/network. 

I haven't tested to upload anything else so I am not sure if this actually does that for everything I upload but I assume so.

**Comment by peppy** [comment]
Clear your submission cache and try again

**Comment by mustywzki** [comment]
Hi,
I just did that and it didn't work

**Comment by peppy** [comment]
@mustywzki I finally have some time to look into this. Can you let me know if anything has changed from your end? Are you still experiencing this issue in the same way as mentioned above?

**Comment by mustywzki** [comment]
Hey, it still doesn't work. For some reason I couldn't update the existing mapset so it created a new beatmap set, with the same issue https://osu.ppy.sh/beatmapsets/1531625#osu/3132484

Also, i did submit another map after I first got that issue with this map and it worked so I am not really sure what to look into, it's probably map-specific but I am not sure why it doesn't go through if I submit it when it worked on someone else's submission

**Comment by Dontmakemeeatyou** [comment]
Do you have 0-byte files in your osu! folder? Some custom hitsounds use these, and it will break BSS.

**Comment by peppy** [comment]
@mustywzki are you still encountering this issue? could you please try the solution mentioned by @Dontmakemeeatyou?

I'm going to close this for now as we're not getting any other reports of this happening, but feel free to reply in this thread if you need further help.
