### ISSUE TITLE
Editor does not seek storyboarded sounds

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#79]
When you use the seek bar on the editor, it does not seek storyboarded sounds. However, pressing pause/unpause DOES pause and unpause the sounds (...usually)

This drove me absolutely _nuts_ when storyboarding the osu!tutorial, to the point pishifat had to provide me with a seperate version of the song audio with the lines mixed in so I could time the visuals correctly.

It really makes storyboarded sounds harder to work with, and discourages their use for longer samples.

Here's a video: https://www.youtube.com/watch?v=ocdbzr58l4U

**Comment by MillhioreF** [comment]
It should be possible to have the game stop all storyboarded sounds from playing whenever the user seeks, but seeking within storyboarded samples is quite a bit more complicated and out of scope.

**Comment by smoogipoo** [comment]
Stopping during seeking sounds fine.

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
