### ISSUE TITLE
extreme lag when moving cursor on windows 11

### ISSUE THREAD

**Issue by uku3lig** [ppy/osu-stable-issues#790]
I recently updated my windows install to Windows 11 with the insider build.
When I move my cursor, there are extreme lag spikes.
I tried playing a map with Auto and i had no FPS drops, as long as I was not moving my mouse.

This issue has been mentioned on [this forum post](https://osu.ppy.sh/community/forums/posts/8171849).

**Comment by smoogipoo** [comment]
Don't use an insider build if you don't know what you're doing.
