### ISSUE TITLE
Unwanted reductions of background-dim at combo milestones with combobursts off

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu-stable-issues#793]
Most high-level players play with either :
1- the background dim at 100%
OR
2- the "Don't change dim level during breaks" option enabled.

The main reason is because if you don't have at least one of those two, you will be disturbed with regular "flashes" due to the background-dim reducing when you reach combo milestones (at 30 combo, 60 combo, etc...) that you can not disable.

This behavior seems rather strange and I suggest to either simply disable this behavior when combobursts are disabled (the comboburst option is quite useless as of now anyway since disabling it has the same effect as replacing the sprites with a transparent texture) OR add an option "Don't change dim level during gameplay".

Edit : In a similar way, if you have shaders enabled, the background is lightened on combo milestones even if the comboburst are disabled (which creates an even stronger flash when added to the background-dim reduction), which is also a strange behavior.

**Comment by peppy** [comment]
The combo burst setting specifically mentions that it stops the characters from appearing. The background flashing is not part of this logic. I tried combining the setting but the game feels so empty. The game starts with combo bursts disabled these days and this just removes even more of what makes osu! a visual experience, so I'm not going to make this change. Can re-discuss once this kinda of visual flair is added back in osu!(lazer), but out of scope for stable.

I have fixed the shader specific issue, which was an oversight. It will no longer flash at 100% dim.
