### ISSUE TITLE
Leave multiplayer matches by holding down escape (instead of pressing it twice)

### ISSUE THREAD

**Issue by kuripa44** [ppy/osu-stable-issues#795]
I can't say how many times I have accidentally left a multiplayer match (or lobby), and I know others who can also attest to this. It would be a nice touch to change this in my opinion. If it were considered, maybe it would be better to make the threshold a bit longer than the retry button's?

**Comment by peppy** [comment]
This is already how things work in lazer (the next major update). As such, I'm not sure we'll be making changes like this to stable. it's a bit out of scope.
