### ISSUE TITLE
[Request] background file for play-skip & menu-back animations

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-stable-issues#798]
With a separate file for the background, the "play-skip" & "menu-back" animations will weigh much less (which in theory can speed up skin loading and get rid of bugs that appear because of this, examples: [Example 1](https://i.imgur.com/G9LqKbc.jpeg) [Example 2](https://i.imgur.com/TFKpyE5.jpeg))

Animation example:

https://user-images.githubusercontent.com/21735205/127312717-5a7c020d-dd11-4ed9-8141-28f2f482b143.mp4

Animation weight with background https://i.imgur.com/DQxZhYC.jpeg without https://i.imgur.com/QteYhxM.jpeg
As you can see in this example, the weight of the animation has decreased by 100 times, this is only if there is a lot of things in the background, in other cases it will be 10 times less, but it's still better. So I think it will be useful for both skin users and skinners themselves.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
