### ISSUE TITLE
Add option to remove expanding animation after circle is clicked

### ISSUE THREAD

**Issue by Karthyz** [ppy/osu-stable-issues#8]
After clicking a circle, without Hidden, the circle will expand briefly before disappearing. I find this quite distracting as my eyes tend to focus on the animation rather than the circles I need to be clicking next.

This can be avoided already by skinning hitcircle.png and hitcircleoverlay.png into default-x.png but then you run into issues where numbers past 9 can't be displayed properly, or playing only HD (which is what I currently do).

In my head I wouldn't have thought it be too hard to implement a tickbox within the settings that would just turn this animation off if you dislike it. It's a simple aesthetic feature so I can't see why anyone would be against having the option and it would make playing nomod 10x less frustrating for me (and probably many others).

Might seem petty or extremely minor but it was the first thing that came to my head when I thought "what frustrates me about osu!stable?".

**Comment by peppy** [comment]
The fact that people skinned this out is (in my personal opinion) game-breaking. But what's done is done. We won't be adding this as an accessible option, so please continue using your skin to do so.

In lazer, it will (eventually) be possible for skins to customise - and as such remove - animations.

**Comment by Karthyz** [comment]
Good to know where it stands anyway, cheers.
