### ISSUE TITLE
Old scores set with NoVideo mod do not display on selected mod leaderboards

### ISSUE THREAD

**Issue by sneasel** [ppy/osu-stable-issues#80]
Forum thread mentioning the issue:
https://osu.ppy.sh/community/forums/topics/637025?start=6225960

Replays submitted using the NoVideo mod from many years ago are unable to be displayed on 'selected mod' leaderboards.

Video:
https://www.youtube.com/watch?v=MG3uwh3Rtkg

**Comment by MillhioreF** [comment]
Is this still happening? Both your links are from 2017 and I remember a script was run shortly after that thread was made to purge NoVideo from old rankings.
