### ISSUE TITLE
scorebar-colour getting cropped on cuttingedge

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-stable-issues#800]
I am not 100% sure if this change is new, or if it has been here for a long time.

![image](https://user-images.githubusercontent.com/35633093/127734315-65067765-36c7-4b4b-90ac-81c53a083d8c.png)

Apparently scorebar-colour gets cropped after a specific height on cuttingedge. Didnt see anything related to this in the recent changelog so thought I would open an issue regarding this here.

**Comment by peppy** [comment]
This is intentional

**Comment by RockRoller01** [comment]
What is the reasoning behind this, it just seems like a pretty random nerf to skinning

I was made aware if this by someone who is making their skin currently. I could probably find multiple skins that break by this, considering how many I have (literally thousands). 

Here is the case of the person that made me aware of this:
![image](https://user-images.githubusercontent.com/35633093/127735453-42b21193-2372-4c0b-baf5-aefe398a0987.png)

**Comment by peppy** [comment]
Please provide the *actual skin* not a screenshot. We cannot work with anything less.

**Comment by RockRoller01** [comment]
[Tuyu.zip](https://github.com/ppy/osu-stable-issues/files/6911002/Tuyu.zip)
There you go

**Comment by RockRoller01** [comment]
In addition to this if you could tell me the exact height at which this gets cut off I could give you more skins that are also affected

**Comment by peppy** [comment]
That's not the idea. I will be using your provided skin to reassess the limited height. We do not intend to support all and every height of skins. No further action is required. If you would like to guarantee your skin works as intended, please move the taller content to the non-fill layer.
