### ISSUE TITLE
osu!taiko: Can't hit finishers with DT/NC

### ISSUE THREAD

**Issue by BluePlusSymbol** [ppy/osu-stable-issues#801]
**Describe the bug**: About 1 year ago, I bought a new computer to play osu!taiko using it because my old computer started lagging too much. Since then, I've always failed to hit nearly half of the finishers (but not all of them?!) when I play the game with DT/NC. I find it really weird because I can hit finishers even with OD10 when I don't play the game with DT/NC.
I'm sure it's either because of an osu!taiko's bug or a problem on my computer (?), and not because of my lack of skills to hit 2 keys at the same time, because I could hit every finisher on easy maps easily even with DT/NC before I started using a new computer.

**Screenshots or videos showing encountered issue:** https://drive.google.com/drive/folders/1HmWmNmguZMqxMVj8Gmp58ia5-BzEvyyg?usp=sharing (replay)
Beatmap: https://osu.ppy.sh/beatmapsets/1278695#taiko/2689244
Mod: DT
The maximum possible score on this beatmap with DT is 331,738, while I only scored 302,721.

**osu! version**: Stable 20210520.2

**System specifications**:
Microsoft Windows 10 Pro (Version 10.0.19042)
Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
Intel(R) HD Graphics 4600

**Logs**: https://drive.google.com/drive/folders/1HmWmNmguZMqxMVj8Gmp58ia5-BzEvyyg?usp=sharing

**Comment by peppy** [comment]
Probably related to your frame limiter setting. Try setting it lower, not higher.

**Comment by BluePlusSymbol** [comment]
I changed my frame limiter setting from Optimal to VSync and Power Saving, and I managed to get better scores, but unfortunately, neither of them completely fixed my issue.

**Comment by peppy** [comment]
I think what you are seeing is just how osu!(stable) handles this logic. It's already been vastly improved in the next major release (aka lazer).

**Comment by BluePlusSymbol** [comment]
Thanks for the info. I just hope I'll be able to submit scores in osu!lazer soon.
