### ISSUE TITLE
Revert disabled boss key on wine?

### ISSUE THREAD

**Issue by KatouMegumi-osu** [ppy/osu-stable-issues#803]
There was once a change that removed ability to use boss key for wine users on osu! stable with the reasoning that it broke wine. Now, when using wine-staging version 6.13, the boss key works fine with "hide wine version from applications" for me. I don't see reason to have that bug fix included anymore.

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu-stable-issues/issues/794
