### ISSUE TITLE
osu mania notes "jump" during gameplay

### ISSUE THREAD

**Issue by StevBoi** [ppy/osu-stable-issues#804]
I started getting into mania and catch, and after a while my notes started "jumping"

This happens with any skin I have tried (tested 3). I reinstalled osu, repaired osu, tried compatibility mode, and reinstalled literally every driver I can think of.
I have also tried different keyboards (doubtful it would fix anything).

I have not found any way to recreate this, it seems to just happen mid song during multi or single.
Sorry if this is the wrong place to post/not a good enough post, I am new to this :)
I am able to collect more clips if it happens while I play catch again.

videos:
https://cdn.discordapp.com/attachments/707910558862671954/870265706615296030/Replay_2021-07-28_03-03-38.mp4
https://cdn.discordapp.com/attachments/707910558862671954/870265717562408970/Replay_2021-05-31_21-55-05-1.mp4
https://cdn.discordapp.com/attachments/707910558862671954/870265718678122496/Replay_2021-05-31_21-53-06-1.mp4
https://cdn.discordapp.com/attachments/707910558862671954/870265719772811334/Replay_2021-05-31_21-54-00-1.mp4
https://cdn.discordapp.com/attachments/707910558862671954/870265724227174460/Replay_2021-07-27_01-54-10.mp4
https://cdn.discordapp.com/attachments/707910558862671954/872679037590470706/Replay_2021-07-30_22-57-59.mp4
https://cdn.discordapp.com/attachments/707910558862671954/872679042854309918/Replay_2021-08-04_00-00-51.mp4
https://cdn.discordapp.com/attachments/707910558862671954/872679048252362812/Replay_2021-08-04_16-56-09.mp4

**Comment by smoogipoo** [comment]
I've never seen this happen before, but it looks like something audio timing related. Is the audio fine as this is going on?

**Comment by StevBoi** [comment]
Yes, the audio is fine while this happens

**Comment by peppy** [comment]
The only way this can happen is malfunctioning audio drivers. Try using a different audio device or driver.

**Comment by StevBoi** [comment]
Updated my audio drivers again, ill see if it makes a difference.

**Comment by StevBoi** [comment]
It happened again after updating, I'm not sure how to install different audio drivers if my motherboard uses the realtek codec
