### ISSUE TITLE
Game freezes completely to do osu!.db file actions

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#805]
I finally found out why people have trouble opening their osu! client when they tab out and cannot tab back in or their game freezes after they tab out.

I believe it has to do with the osu!.db file because whenever it happens I can look in my osu! file and osu! uses up more memory than normal and has the extra db file loaded - I am not sure what it does but I know you know what it does.

This happens to the majority of players on osu! - unless you have some major gaming pc that can run anything super fast but still I am not sure because my other computer that can run anything even in VR has this issue too. This is not an issue in osu!lazer as far as I know.

This is the file that shows up when the freezing happens and disappears after it is done (for me it lasts up to 3 minutes)
![unknown (1)](https://user-images.githubusercontent.com/52920930/128600448-ae9c731a-626b-43dd-af68-4703605892ce.png)

extra info:
osu!.db file size: 366mb (I have 117k beatmaps)
osu version: stable (does it on cutting edge and compatibility mode too)
computer memory: 16GB and integrated graphics

**Comment by peppy** [comment]
"happens to the majority of players" yet it has not been reported once. could you please provide references?

**Comment by peppy** [comment]
I've made a preliminary fix for what I believe could be causing this. Please test again on cutting edge and se if you can still reproduce the issue.

**Comment by WinterIsPretty** [comment]
I've used osu for about 4 hours and I've yet to have it happen so far. It happened mostly in the editor because I tab in and out a lot while in the editor and I did a ton of sv stuff which means I have to open the timing panel and exit the timing panel which does the same thing as tabbing in and out and nothing has happened yet.

I think there hasn't been anybody reporting this because it is probably not seen as an error with osu! and also I spent so long trying to figure out what had caused this issue in the first place because for a while I thought it was because my computer is being slow but I realized osu!lazer doesn't do this and no other program I've seen does this...

When I ask my friends what they do when this happens they say they usually alt-f4 or go to the task manager and close osu.

**Comment by WinterIsPretty** [comment]
![image](https://user-images.githubusercontent.com/52920930/128638421-f0ccc414-a44e-4a51-9b97-308cb26dd5bb.png)
![image](https://user-images.githubusercontent.com/52920930/128638436-b8a734f1-2021-4715-a3f2-14eba9f7ae9d.png)
![image](https://user-images.githubusercontent.com/52920930/128638448-567de0a3-bc53-4a1a-8784-4125bf1f84cf.png)
![image](https://user-images.githubusercontent.com/52920930/128638451-f13a159c-ba8e-48c0-9ca6-2e061ec0d456.png)
![image](https://user-images.githubusercontent.com/52920930/128638530-680747ee-2e0b-4a20-9c0d-cd91f731faed.png)
![image](https://user-images.githubusercontent.com/52920930/128638540-da8a89e8-d9e1-49ae-ab21-17b8b7d520f9.png)
images of people responding

**Comment by peppy** [comment]
Thanks. Pretty sure it will be fixed now, so please keep an eye and let us know.
