### ISSUE TITLE
bottom aligned scorebars no longer possible

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-stable-issues#809]
due to the recent changes to scorebar-colour bottom aligned scorebars are no longer possible, since the colour now gets cut off (at which seems to be 120px for SD?)

**Comment by peppy** [comment]
Sorry about that. The existing skinning system was not made to be used in a such a way, and it was causing performance and other issues, so our hand was forced this time.

This functionality is already added in lazer in a more proper way, which will allow you to once again to this in a near future (or now, if you choose to make the switch!).

**Comment by RockRoller01** [comment]
welp, rip. Could you at least please confirm if 120px is the correct cutoff height so I can add it to the wiki?

**Comment by peppy** [comment]
I believe so, yes.

**Comment by Purplegaze** [comment]
Would you consider changing the cap to something larger? I get that bottom-aligned scorebars are not intended, but something like this really doesn't look that egregious...

https://mobile.twitter.com/Ayreth2/status/1421150254297239552/photo/1

**Comment by sr229** [comment]
> Would you consider changing the cap to something larger? I get that bottom-aligned scorebars are not intended, but something like this really doesn't look that egregious...
> 
> https://mobile.twitter.com/Ayreth2/status/1421150254297239552/photo/1

This is already added in Lazer so I doubt they'll make this change for stable.

**Comment by peppy** [comment]
The linked tweet is an incorrectly formed skin. The background portion on the left should not be in the fill layer but the background layer. This layer can extend further downwards. It can be fixed at a skin level.

**Comment by Purplegaze** [comment]
> The linked tweet is an incorrectly formed skin. The background portion on the left should not be in the fill layer but the background layer. This layer can extend further downwards. It can be fixed at a skin level.

Apologies for the bad example, here's a better one:
This skin uses an effect on the HP bar where there's a bare tree branch at 0 HP and it gets filled with flowers as the HP increases. The HP bar is certainly not egregiously large, yet the effect still got broken and cut off at the bottom by this patch:

![screenshot1390](https://user-images.githubusercontent.com/25409695/128944543-6bea9807-84dc-49ce-b776-3ec27b07dfb9.jpg)

**Comment by peppy** [comment]
Please link the skin, not a screenshot of it.

**Comment by Purplegaze** [comment]
[Cozy Skin.zip](https://github.com/ppy/osu-stable-issues/files/6965149/Cozy.Skin.zip)

**Comment by Xaexor** [comment]
Same with a couple of skins that I have made, that has a taller height. Example:
https://drive.google.com/file/d/1abBM6MmRb_o9ka1Jrd6Y58twnGGVlvWA/view?usp=sharing

**Comment by peppy** [comment]
The example you posted on the lazer repository showed skin content which should be in the background layer, not the fill. Can you not just move it?

**Comment by RockRoller01** [comment]
https://drive.google.com/file/d/1XVSIgqI9I--FV9hVNEudaAXEI3_wumuP
http://www.mediafire.com/file/gdlt4jk4hmgzcus/NatureMint.osk/file

Here are another 2 skins that already got reported on the forum for being broken (one of the being a bottom aligned scorebar).
If this whole change was made for the reason I have suspected in my previous issue, I would recommend to maybe consider not limiting non-animated scorebar-colour images, and limiting animated ones to a more sensible height than 120px.

> Can you not just move it?
It is not realy a matter of if it can be fixed, but rather of who will fix it. This change afterall affected the entire catalogue of skins, which is over a decade old.

A lot of skinners have since moved on from osu, or even if they are still around they may no longer want to give active support for their skins. And the average end user of a skin got 0 clue about image editing and is not able to fix it themself. Not to mention it is still quite annoying to have to check on your favorite skin everyone now and then in the hope that the creator, or someone in the comments released a fix. And this is assuming that a skin got a "proper release", and you didn't just get it from e.g. a random discord chat and have no clue where to even find a fix if such a thing exists. (not to mention reddit doesnt allow for commenting/updating on threads, which means even if you wanted to provide a fix you couldn't)

**Comment by Xaexor** [comment]
> The example you posted on the lazer repository showed skin content which should be in the background layer, not the fill. Can you not just move it?

I agree, the example that I shown can be fixed by moving it to the background layer. But there are some others that can't, especially the ones that includes animation at the bottom. For example, this skin: https://drive.google.com/file/d/1uoM3vVJa8lqaB7L6wtgXoet6Z6n4bPAW/view?usp=sharing

I have slight movement animations on the character's arm: https://imgur.com/puM8ko1
It gets cut off: https://imgur.com/a/mjAdQ9J
