### ISSUE TITLE
osu! stable will not open in Wine on Linux (X11 error)

### ISSUE THREAD

**Issue by shinotheshino** [ppy/osu-stable-issues#810]
osu! stable will not run in Wine on Linux with multiple monitors.

Wine outputs the following:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x8000076
  Serial number of failed request:  332
  Current serial number in output stream:  348
```

The same behaviour occurs with Cutting Edge.

This could potentially be related to https://github.com/ppy/osu/issues/14085 and perhaps an SDL update is needed.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
