### ISSUE TITLE
Hit-error bar not showing correct error with Relax

### ISSUE THREAD

**Issue by N45A** [ppy/osu-stable-issues#812]
It only happens when hit is perfectly on time, from what I can say. It does scale with "Score meter size". Does that both on stable and cutting edge. I have no idea if that's just visual or if it goes to replay file like that. I tried opening replay with RX and it's still wrong. I don't really know what to add more. 
Also, should i post it here https://github.com/ppy/osu/issues instead? 

https://user-images.githubusercontent.com/87266241/129429470-969fdabf-f1f2-4294-a577-65cb2bc43821.mp4

**Comment by Wieku** [comment]
It's just how Relax works. Relax mod starts attempting to hit the circle 12ms before the perfect time.

**Comment by peppy** [comment]
Closing as “intended”
