### ISSUE TITLE
"Press F2 to save replay" not translated to other languages

### ISSUE THREAD

**Issue by XetThe** [ppy/osu-stable-issues#814]
I noticed this string is in english only, should be an easy fix I guess.
![image](https://user-images.githubusercontent.com/87451413/129434452-f167d6ff-dfb7-4561-8650-f902293c9154.png)
client version: b20210809.1

**Comment by peppy** [comment]
Thanks for reporting this. Stable is feature locked (and localisation locked) and this was a recently added text string, so unfortunately this isn't happening.
