### ISSUE TITLE
Osu! Crashes on OBS & Streamlabs OBS game capture

### ISSUE THREAD

**Issue by Arizoka** [ppy/osu-stable-issues#823]
Hello, i've had an issue with client for around a week now and I haven't found a solution so far.

Since last Nvidia driver update and since i tweaked some settings in obs to reduce input lag while streaming I've had this issue where the game client would crash on welcome screen if i have obs opened with game capture on Osu! If i try to record a reproduction of the crash I only have black screen.

**OBS Release:** 27.0.1
**Last Nvidia GTX1050 Driver:** Clean Install
**Osu! Release:** b20210820.1cuttingedge

**### Osu! Settings** 
_LastVersionPermissionsFailed =_ b20201017.3
_HeightFullscreen =_ 768
_CustomFrameLimit =_ 700
_WidthFullscreen =_ 1360
_FrameSync =_ Unlimited
_MsnIntegration =_ 1
_MyPcSucks =_ 1
_AudioDevice =_ Speakers (Focusrite Usb Audio)
_AudioCompatibility =_ 1
_RawInput =_ 1

**### OBS Settings**
![image](https://user-images.githubusercontent.com/89308337/130325580-92a49828-6738-446d-ba5c-293d7774f894.png)
![image](https://user-images.githubusercontent.com/89308337/130325584-507c30f5-53b9-478c-a741-f04e6b2b9471.png)
![image](https://user-images.githubusercontent.com/89308337/130325595-18bf8f4a-ecff-4085-b675-992345f64c36.png)

OBS & StreamLabs are also running on powersaving plan in advanced graphic setting to ensure i can capture the game on OBS.

So far i've tried to reinstall OBS with factory settings, Clean install my gpu driver, reinstall Osu!, Try if i have the same issue on Stable and Cutting Edge (Eventhough I mostly play on cutting edge).

I tried to look into the event logs for this crash and this is the logs I have everytime this happens:

Faulting application name: osu!.exe, version: 1.3.3.7, time stamp: 0x611f44d7
Faulting module name: ntdll.dll, version: 10.0.19041.662, time stamp: 0x5f641e44
Exception code: 0xc0000005
Fault offset: 0x00062113
Faulting process ID: 0x2568
Faulting application start time: 0x01d796963d6c91a3
Faulting application path: C:\Users\adibe\AppData\Local\osu!\osu!.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: df0e3db2-6273-4689-9bdf-c6af343f6cc1
Faulting package full name: 
Faulting package-relative application ID: 

I hope you have a solution for this as I'd love to stream again as soon as possible.

**Comment by smoogipoo** [comment]
Are you able to install your previous GPU driver? Are you using game capture, window capture, or monitor capture?

**Comment by Arizoka** [comment]
> Are you able to install your previous GPU driver? Are you using game capture, window capture, or monitor capture?

I always use game capture since windowed mode or screen capture would increase the input lag ingame while recording or streaming.

I tried to downgrade the GPU driver to the previous version but I don't have the option to roll back: 
![image](https://user-images.githubusercontent.com/89308337/130532563-a8650338-79aa-4be6-a207-f1536fc149be.png)

**Comment by PercyDan54** [comment]
Are you using a laptop? If so make sure osu and OBS is running on the same GPU

**Comment by Arizoka** [comment]
> Are you using a laptop? If so make sure osu and OBS is running on the same GPU

Yes, I'm using a laptop for playing and streaming. Both my game and OBS are using same GPU. This is why i have Steamlabs OBS and OBS running on power saving mode. Otherwise i can't capture the game, but that's another topic.

It worked fine so far for more than a year. I can stream and play the game, even though hat times i experience more lag than usual. But Osu! crashing with game capture is very new and unusual for me.

**Comment by peppy** [comment]
You can download older drivers from nvidia's site.

**Comment by PercyDan54** [comment]
Upgrading/downgrading OBS/GPU driver worked for me in the issue below.
I think it's the same as ppy/osu#11599, but the problem has gone for me.

Nvidia driver version 461.40
OBS 27.0.1

**Comment by Arizoka** [comment]
Hi there,

Just a little update about the issue. I switched to compatibility mode to force Osu! to use GTX1050 instead of Intel 630. Currently, I run both Osu! and OBS Streamlabs on GTX1050 as administrator, and it works just fine with game capture (no input lag, no capture bugs or blackscreens). Only issue i have is Alt+Tab flicker where i'm stuck either on desktop and can't go back to osu! thanks for you contributions!
