### ISSUE TITLE
mp link (and tournament client) showing incomplete scores in MWC

### ISSUE THREAD

**Issue by PotassiumF** [ppy/osu-stable-issues#825]
Yesterday in the 4K mania world cup match between Spain and Switzerland, one player's score (CrewK fanboy) appeared much lower in the mp link than what was received by the referee through IRC. The mp link score is impossibly low and has a lower notecount than the other players', so it's safe to say that the mp is showing a score that existed mid-map rather than the final score.

Another player (Guldakh) on the same map had a similar issue with the score shown on stream with the tournament client, but this player's mp link score was correct.

mp link (final map): https://osu.ppy.sh/community/matches/89681977
![image](https://user-images.githubusercontent.com/89407018/130481577-da513125-892c-4f34-a85f-765708cbee94.png)

IRC results received by the ref:
![image](https://user-images.githubusercontent.com/89407018/130480937-3a4ea448-8a36-4adf-a6f9-960abe9e0258.png)

Scores that appeared on stream (1:43:16 https://www.twitch.tv/videos/1126224931):
![image](https://user-images.githubusercontent.com/89407018/130481451-c722457e-b9f5-4935-892d-c3e6dd697e1d.png)

Tournament client discrepencies are fairly common, but since mp links are normally accurate and are commonly used by refs to make decisions, I was asked to report here.

**Comment by peppy** [comment]
This means the user probably had a bad connection and never sent the results to bancho. We've already considered this kind of issue in lazer, where all scores displayed are the final submitted score (not the real-time stream). It wouldn't be a simple change in stable, but luckily it's a very rare occurrence.

I'm not sure this is actionable, but thanks for reporting.

**Comment by ThePooN** [comment]
> This means the user probably had a bad connection and never sent the results to bancho.

Have you looked at the IRC BanchoBot logs? They show the right score at the end of the map like everybody else, it seems Bancho received the correct score. It is only wrong on the mp link. This can cause many issues in refereeing matches, as we now have two sources of info that are supposedly 100% accurate... but disprecancies can happen now.

The tourney client screenshot is only provided as additional info, spectating isn't the reported issue.

**Comment by peppy** [comment]
I've gone through the code with a fine comb multiple times and can not see how this can happen (which is very rare for me). There are already multiple safeties and in theory this order of events should be impossible.

Are the timestamps in that screenshot accurate? They are showing 3 minutes off from the IRC results being reported, which may have something to do with it if so.

**Comment by peppy** [comment]
Another hint is that the timestamps for Haprapra being in the game don't match up. They seem to have joined *after* the match started..

![20210831 231309 (Safari)](https://user-images.githubusercontent.com/191335/131518416-11bc9478-7771-4d77-aa18-28b44b7097d0.png)

**Comment by ThePooN** [comment]
They joined at 3:33am and the match started at 3:34am, finished at 3:38, as reported by the IRC logs. You seem confused by the osu-web UI..?

**Comment by peppy** [comment]
Right, reading numbers is hard.

I'm looking for confirmation on this screenshot though: https://user-images.githubusercontent.com/89407018/130481451-c722457e-b9f5-4935-892d-c3e6dd697e1d.png

**Comment by ThePooN** [comment]
This was streamed from my own machine and its clock (UTC+2) seems accurate, judging by the chat timestamps.

The timestamps on the score results display seems to be from when the client started spectating them. I was convinced it was when the screen displayed but that doesn't seem to be the case when spectating.

**Comment by ThePooN** [comment]
There was quite some lag on this particular map apparently, judging by the VOD and that CrewK fanboy's score arrived several seconds later. Maybe score packets arrived out-of-order?

**Comment by peppy** [comment]
Out of order packets cannot explain the issue (also that would go against tcp protocol ordering, but that's not relevant here). The saving to database (for osu-web display) is only performed once, and only *after* that message is sent to in-game chat. There's no delays to the process, no async, nothing. Everything is locked on a single mutex ensuring (in theory) no thread wonkiness.

In addition, the chat output won't even occur if the match is not in progress, ruling out the player potentially reporting completion twice over.

**Comment by ThePooN** [comment]
Full chat log 🤞

[Spain-Switzerland.txt](https://github.com/ppy/osu-stable-issues/files/7084948/Spain-Switzerland.txt)

**Comment by peppy** [comment]
Thanks, that helps a lot. I think I have a basic idea of how this could have happened now.

**Comment by ThePooN** [comment]
We managed to recover a chat log with full timestamps down to the millisecond:  
[irc-mp_89681977.txt](https://github.com/ppy/osu-stable-issues/files/7084997/irc-mp_89681977.txt)

**Comment by peppy** [comment]
This should be fixed in the next bancho update (sometime this week).
