### ISSUE TITLE
Delete All Visible, deletes more than just the visible.

### ISSUE THREAD

**Issue by Stravitch** [ppy/osu-stable-issues#827]
I posted in the official help forums but I thought I would check here as well. In my infinite wisdom, I wanted to clear up the maps that I hadn't recorded any local scores on so that I could find the maps I did play more easily. I sorted by rank, then clicked on No Rank Achieved, then I clicked delete all visible maps (the number shown was the correct number of no rank achieved maps). All it left behind was the maps that have no rank achieved.

https://youtu.be/pPuELo9GCv4

**Comment by peppy** [comment]
"Delete all visible" doesn't work by grouping. It works by search filter. This is behaving as expected.
