### ISSUE TITLE
osu!direct incorrectly displays 0.0 star rating for some maps

### ISSUE THREAD

**Issue by ricterG** [ppy/osu-stable-issues#828]
It's a duplicate of #383 the only other reporting of this issue I can find, closed prematurely

Searching for some unranked maps in osu!direct and hovering over the difficulty shows the star rating as 0.0, downloading the map shows the real star rating

I got a few examples just searching random artists and scrolling through beatmaps, but there are many more, I'd say this affects maybe ~5% of all maps in graveyard

![image](https://user-images.githubusercontent.com/41763965/130901665-41eec7ce-617c-4f70-a4e5-83d5ef5dfb63.png)
Actual star rating in song select

![image](https://user-images.githubusercontent.com/41763965/130901774-3bc303f9-d5ad-4e53-a261-35c0253bab0c.png)

https://osu.ppy.sh/beatmapsets/1189413#osu/2478427
https://osu.ppy.sh/beatmapsets/1318034#fruits/2730685
https://osu.ppy.sh/beatmapsets/1504093#osu/3081451
https://osu.ppy.sh/beatmapsets/1546841#mania/3161327

No real pattern to which ones will have this issue that I have noticed

Frustrating when I only want to download maps of a certain SR but won't know until I download it or I have to open the beatmap listing in browser

**Comment by peppy** [comment]
I'm running generation on all graveyarded beatmaps, which should resolve this issue. Please give it a few days, as it's running low priority.

**Comment by peppy** [comment]
Seems to be fixed now:

![20210907 162820 (Parallels Desktop)](https://user-images.githubusercontent.com/191335/132302804-34255c4c-a565-4eee-893a-aeb49ed273de.png)
