### ISSUE TITLE
Collections don't save until you close the game

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#83]
This means if osu! crashes for any reason the changes will be lost. To replicate, make/edit a collection and kill osu! process via task manager.

**Comment by MillhioreF** [comment]
This is a known issue (and affects newly imported beatmaps too) but fixing it would most likely require a large overhaul of database backups and sanity checks. Will investigate to see if there's an easy fix but this is probably out of scope.

**Comment by smoogipoo** [comment]
This is intentional. Database saving is generally backgrounded (saves after 10 minutes/1 minute idle) to reduce performance impact.
