### ISSUE TITLE
Mapping: low volume compared to other maps

### ISSUE THREAD

**Issue by Breizh-Brittany** [ppy/osu-stable-issues#831]
Hi guys, I'm new here!
On the ask of Osu! staff I came here to ask you what I can do with my problem as they are not able to answer my question.
Here is the copy of the mail I sent them:

◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡
Many times I drop a song in Osu! to start mapping I got a problem of low volume.
The volume of the song is lower than the other maps.

My audio files are always at the best audio quality possible as I convert them from .flac to .mp3 320kbps [CBR - Constant Bit Rate] using Audacity.
I also amplify the audio to the max before saturation.

On the forum I saw two old threads that speak about that same problem and people said that we should use Audacity to amplify the gain
Or use Mp3DirectCut to amplify the gain too, which is better than Audacity in their opinions.
I downloaded it and did as they said.
I compared two amplified files (+6dB), one from Audacity and the other from Mp3DirectCut and they sound exactly the same: Audio oversaturated.
Oversaturated means not usable. (at least for me)
 
I post my own thread on the forum but no one answered.

Could you do something for it ? maybe add a potentiometer inside the mapping interface so we could adjust the volume of our songs?
 
 
Also, as I write you, I would like to know why many songs of ranked maps have this low bitrate of 192kbp/s.
Is it a normal downgrade for the ranked maps ?
By the way, why don’t Osu! Support other formats like .wav / .flac / .alac  et caetera.
 
This is a music game where the ranked maps are in mp3 192kbp/s ! ⚠
 
 
Sorry for this long message,
Best regards, love your game, awaiting your answer,
Math
◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡◠◡

Can this be solved one day?

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
