### ISSUE TITLE
Typo on Spanish language at the moment of getting a medal in-game.

### ISSUE THREAD

**Issue by kanocchi** [ppy/osu-stable-issues#834]
If you have your game in Spanish, when you get a medal it says "_MEDALLA DESBLOQUEDA_", when it should say "**MEDALLA DESBLOQUEADA**"

Thanks to [b-3n](https://osu.ppy.sh/community/forums/topics/1413468) for finding this issue!

**Comment by peppy** [comment]
Thanks but localisations are currently locked for stable. Should be fixed in lazer when we introduce new translations. Go check crowdin if you're interested in helping with that effort.
