### ISSUE TITLE
Certain skins won't work in-game

### ISSUE THREAD

**Issue by DaGDNoob** [ppy/osu-stable-issues#835]
I'm using Wine 3.12 on Arch and when I certain skins and start playing a map the game locks up and displays nothing
If I go into edit mode and edit any map it displays black and then the game crashes
[runtime.log](https://github.com/ppy/osu-stable-issues/files/7117605/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/7117606/session.log)
I also get this error from wine
003d:err:ntdll:RtlpWaitForCriticalSection section 0x14c1e31c "?" wait timed out in thread 003d, blocked by 0009, retrying (60 sec)
Everything works fine on windows

**Comment by ThePooN** [comment]
Wine is not officially supported, the osu! development team cannot handle such compatibility issues. Please use approppriate support channels instead (I do provide one as the likely distributor of the Wine build you're using).

With that said; I'll still post this solution, hopefully it can help you and others in the future, and to avoid more Wine-specific compatibility issues.  
You need to install the following package on Arch Linux for some skins with specific sound files to load properly:
`sudo pacman -S lib32-gst-plugins-base-libs`

**Comment by DaGDNoob** [comment]
Thank you I'll use the proper support channels from now on
