### ISSUE TITLE
Skin Preview immediately ending

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu-stable-issues#84]
**Issue:** Beatmaps that don't have anything mapped past the preview point immediately end.

This probably happened before as I have very vague memories of it but the chances were low because of how "Preview Skin" behaved where it used to select a random track but now it uses the currently playing track.

**Video:** https://streamable.com/2qz4d

**Comment by smoogipoo** [comment]
This is too involved of a fix for the benefit - stable doesn't know about the position of any hitobjects until the beatmap is fully parsed, and that happens much later in the process.
