### ISSUE TITLE
Endless loop of beatmap proccessing when selecting a beatmap with super long folder name

### ISSUE THREAD

**Issue by rednir** [ppy/osu-stable-issues#840]
Discovered this issue when trying to select a beatmap I created in linux/wine with long metadata.

This locks up the game completely (alt+f4 does nothing)

https://user-images.githubusercontent.com/10225220/132903441-74bb5bdc-f74a-4f55-850a-ef23b485fb9a.mp4

**Comment by peppy** [comment]
Please attach logs and beatmap

**Comment by rednir** [comment]
[runtime.log](https://github.com/ppy/osu-stable-issues/files/7146692/runtime.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/7146694/update_success.log)
(literally nothing in these, not sure if i need to do something extra to get more logging)

I can't upload files here because windows doesn't let me zip it and github doesnt accept other archive files, but you can easily reproduce this with any beatmap if you make the song folder anything long (as shown in video, I did it with disco prince).
Let me know if you want me to try upload to some other file hosting site if you still need me to.

**Comment by peppy** [comment]
Editing content in the songs folder directly is unsupported. It sounds like you are exceeding the NTFS limits of path length (google for more information).

Are you able to reproduce this from an .osz import or something like that? If not, this is not something we'd be looking to fix at our end.

**Comment by rednir** [comment]
This happened with a [beatmap](https://osu.ppy.sh/beatmapsets/1562633#osu/3191050) I created with linux/wine. Due to its long metadata it created a large folder name. I was able to access it with no issue, but I could not access the beatmap when using windows (shared songs folder, not the osz)

I suppose this is also "unsupported" in some way...

**Comment by peppy** [comment]
It's a very edge case in that we haven't seen this happen until now, so I'm trying to discern whether this needs server side validation. Since if users can upload beatmaps like this it could be used to break people's games.

**Comment by rednir** [comment]
Looks like there is already server side validation for long filenames. The song folder name is also truncated on beatmap import, so it's a non-issue.
![image](https://user-images.githubusercontent.com/10225220/132945941-ff1169ca-cafc-4331-af1e-2fc1b2054e7d.png)

**Comment by peppy** [comment]
Right, so this is only possible by manually changing the folder name of a beatmap in the songs folder?

I'll keep this open as I may fix it depending on time and difficulty.

**Comment by peppy** [comment]
I've got a potential fix for this going into the next cutting edge release (later today). Please give it a try and see if it helps.

**Comment by rednir** [comment]
Looks like the endless loading is no more 👍
![image](https://user-images.githubusercontent.com/10225220/133286007-28ed2d61-eb5c-4e6e-91f2-79921fd4eb9e.png)
I assume I can just rename the song folder/files and there hopefully shouldnt be any issues.
