### ISSUE TITLE
Audio Compatibility Mode Makes Gameplay Choppy

### ISSUE THREAD

**Issue by Phattyowo** [ppy/osu-stable-issues#844]
I have to use audio compatibility mode as it reduces my slight audio latency, but using audio compatibility mode makes the approach circles look choppy like when you switch from 144hz to 60hz (cursor is not affected). game is definitely still playable but it feels off and might mess with my reading sometimes especially for EZ mod where there are a bunch of approach circles on the screen.

**Comment by peppy** [comment]
Compatibility mode is offered as an "as-is". It uses a very dated API and is handled differently depending on your windows version and driver. If you are running an ancient windows install, I'd recommend updating to the latest and disabling compatibility mode for the best experience.

You may also want to try updating your audio drivers.
