### ISSUE TITLE
Loved warning not translated

### ISSUE THREAD

**Issue by LirekPL** [ppy/osu-stable-issues#847]
When you use other language than English, you may see that "This map is in a loved state" is not translated, while "This map is in a qualified state" is. This problem can be seen in both languages I tried: Polish and Netherlands. Feel free to ask any questions and I hope this counts as a quick fix.
On this screenshot you can see in the bottom, that my client is set in polish (F10 message):
![screenshot166](https://user-images.githubusercontent.com/29497627/134186776-27c4d4f6-e955-46b7-9d80-1daf930913e1.png)
Here it works perfectly fine (qualified warning):
![screenshot163](https://user-images.githubusercontent.com/29497627/134187086-e1a5796c-f91f-408b-8087-e823293beaa9.png)

**Comment by peppy** [comment]
This will be resolved in the next major update (aka lazer). Translations are locked for stable.
