### ISSUE TITLE
osu! does not force resize the hitcircleoverlay.png resolution

### ISSUE THREAD

**Issue by mhdimo** [ppy/osu-stable-issues#849]
so what i mean for this, apparently you can actually change the resolution of hitcircleoverlay@2x.png  (in case we use a 1080p but this could happen too with hitcircleoverlay.png for display with lower resolution) and make the hitcircle bigger, making playing HDHR (as there is no approach circle) easier to play or streams easier to play
example of what i mean with the hitcircle overlay resized to something bigger
![image](https://user-images.githubusercontent.com/62386208/134591548-5fab8f0d-c73d-4400-a8bb-172bb3025300.png)
![image](https://user-images.githubusercontent.com/62386208/134591612-ef418d73-14a3-430c-bd89-03e56166376a.png)

where here is what it should look like
![screenshot1771](https://user-images.githubusercontent.com/62386208/134591712-221802cd-3c21-4cfa-97a9-bbfca41686d5.jpg)
![screenshot1772](https://user-images.githubusercontent.com/62386208/134591725-16a3e1b1-f575-4d52-abd8-034c1554c6d3.jpg)

if it's not possible to fix it in osu!stable, I hope at least it could be a thing in osu!lazer that does force the size of the hitcircle png/jpg

**Comment by redactdead** [comment]
It's just a visual change, so does it really make it easier to play? If anything, since the edge of the hitcircle wouldn't be actually be clickable, wouldn't it be harder?

**Comment by mhdimo** [comment]
talking for myself (even though I think a lot of people do this): if i have a bigger circle, i tend to snap more as possible to the center of the circle on a jump(especially on cs6/6.5), for streams it's the same thing, it helps me to be more centered to the circles
someone may also can say "right but if somoene plays nomod/HR/DT only, doesn't he notice that the approach circle and hitcircleoverlay isn't aligned? it could make the accuracy worse"
you can make the approach circle bigger too and basically defeat the chance of making it "harder"
the harder thing is initially it could be making you shitmissing a lot, but once you are used to this you wouldn't have problems anymore with cs

in any ways I think that forcing the png to a definite size to make it "eligible" on lazer (at least) is a good solution to avoid this

**Comment by peppy** [comment]
I'm 95% sure this is already done on lazer.
