### ISSUE TITLE
Last tick of some sliders invisible

### ISSUE THREAD

**Issue by domi1819** [ppy/osu-stable-issues#85]
During gameplay some sliders seem to be visually missing their last tick although the tick sound plays.
It's reproducible for me on this map https://osu.ppy.sh/b/1977553 but I've noticed this happen on countless other maps. The first affected slider is at 1:23.231
Another thing to note is that the editor shows all ticks.

Screenshot of gameplay: https://up.domi.re/pn5c9egg
Screenshot of editor: https://up.domi.re/8530o0jf

**Comment by domi1819** [comment]
Also, while the screenshots only show a custom skin this also happens with the default one.

**Comment by MillhioreF** [comment]
This is intentional due to the game not wanting to render ticks on top of slider heads or ends - they're only visible in the editor for clarity. Would require a flag in the skin.ini to override this behavior and I believe skinning changes are out of scope here.
