### ISSUE TITLE
Custom Frame Limiters

### ISSUE THREAD

**Issue by Entropy21** [ppy/osu-stable-issues#850]
Hi, after asking on the forums, I was told to try posting here instead. About the custom frame limiters not saving on the game.

When using the custom frame limit during gameplay and pressing F7(default key for changing limiters), the custom frame limiter I set is gone and I have to edit the cfg file on the osu! folder all over again.

**Comment by peppy** [comment]
Try setting a different value. You might have set one too high, or it may be matching some default and therefore ignorign your setting. Forums are the correct place to post this kind of issue, I'm not sure why you were directed here.
