### ISSUE TITLE
Cursor disappearing

### ISSUE THREAD

**Issue by C0D3-M4513R** [ppy/osu-stable-issues#852]
On F9,F8 and replays the cursor exists, but is invisible for me.
Here my cursor hovers over collections, in a replay.
![image](https://user-images.githubusercontent.com/28912031/134808230-9fa1be7d-a9c0-405b-9e32-c70a4b337475.png)
And here is me hovering over a link in osu chat. again the cursor is invisible.
![image](https://user-images.githubusercontent.com/28912031/134808286-eadc5b76-03b1-408c-9538-995fd2fcaea7.png)

**Comment by peppy** [comment]
Nothing has changed from our end. Please check what has changed at your end, if anything.

**Comment by C0D3-M4513R** [comment]
I changed my overlay, if anything. This issue also happpens, when my overlay software isn't running.
What windows changed in the meantime, I cannot tell you.

default skin has the same issue
osu! stable branch has the same issue though. 
osu! beta branch also has the same issue.
compatibilty mode renderer solves this, as a workaround

**Comment by smoogipoo** [comment]
~~Have you changed your skin? Please provide the skin.~~ I misread, this issue is talking about the Windows cursor.

**Comment by C0D3-M4513R** [comment]
So. This issue just fixed itself. Without any update. Take it as some windows wierdness.
My cursor also had the same issue sometimes on windows. Ctrl-alt-del. fixed that temporarily though.
(the times windows cursor was broken, and osu cursor being broken is unrelated. sometimes one, the other or both were broken. rn both work.)
I am not expecting this to go away.
Maybe use a software cursor for those cases also? idk?

**Comment by peppy** [comment]
It's going to be something on your system. We have changed nothing.

**Comment by C0D3-M4513R** [comment]
Guess I'll be using compatibility renderer for a while, if this ever happenes again.

**Comment by C0D3-M4513R** [comment]
Also duplicate of #729?

**Comment by C0D3-M4513R** [comment]
I reinstalled nvidia drivers yesterday, due to something unrelated. This issue had been happening again.
After the driver reinstall, the cursor appeared again.
