### ISSUE TITLE
Key input bypasses IME

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu-stable-issues#855]
Before if you press enter IME should input the pending text, but now seems in-game actions gets more priority. Somehow a recent update breaks it.
This is annoying when typing English chracters you have to switch IME

**Comment by peppy** [comment]
Has something changed with your setup? Windows version update or software change?

**Comment by PercyDan54** [comment]
Sorry, after searching I found that my IME seems to be updated at 9-27.
Can reproduce on lazer, stable fallback and a 2020 stable.

**Comment by peppy** [comment]
Is this a custom IME package? Or the windows one?

**Comment by PercyDan54** [comment]
It's a custom one, so I guess it's not osu's fault
