### ISSUE TITLE
All my completed maps are missing.

### ISSUE THREAD

**Issue by Darklighter1** [ppy/osu-stable-issues#856]
I've tried to rename my osu!.db file. Still didn't do anything and I've not seen the problem I'm having on the osu site itself so ye...
It also says I've never played before but I clearly have by looking at my profile. My Osu client is up to date and I think it happened a couple weeks ago when I tried playing co-op with a frien
![screenshot007](https://user-images.githubusercontent.com/92040878/136227373-5bcca530-1cff-4e46-adc6-ad7ba08a104b.jpg)
d.

**Comment by Darklighter1** [comment]
Sorry but english is not the best^^

**Comment by peppy** [comment]
Have you checked the difficulty filter settings (in the main settings)? They could be hiding beatmaps.

Also you can try pressing F5 twice to force a full reprocess of your songs folder.

**Comment by Darklighter1** [comment]
I already found the problem... I accidentally pressed Ctrl 2,3,4 and uhm... ye I had to switch back to Osu...
