### ISSUE TITLE
Toggling mouse buttons causes screen to freeze

### ISSUE THREAD

**Issue by xxxzelda101xxx** [ppy/osu-stable-issues#857]
I'm not entirely sure how to describe this, but toggling mouse buttons freeze's the screen. The game itself isn't frozen, pressing the toggle mouse buttons key again or simply clicking makes it unfreeze.

video: https://streamable.com/cbzzhm

**Comment by peppy** [comment]
This is because you are causing a window menu to appear. Search google - it's a common thing which will probably affect other games too. I believe it may be IME related or something.
