### ISSUE TITLE
Osu been consistently stuttering recently

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#858]
A couple of my friends and I have experienced consistent lag spikes that are very annoying and noticeable. This was never an issue for me until recently and I've tried everything I know to fix it and nothing worked.

What I've done and nothing changed
- Changed from stable to cutting edge
- Redownloaded osu
- Recalculated my osu.db
- Used vsync, power-saving, optimal, unlimited, and custom fps
- Changed modes
- Changed skins
- Compatibility mode (makes it worse)
- Closed discord and disabled discord integration
- Administrator mode
- Turned off antivirus and closed all other programs
- Even deleted Etterna, because I don't play it anymore, clearing out 100gb of storage

I'm reporting this because it has gotten so annoying that osu has become nearly unplayable for me because osu would freeze for a quarter of a beat in most songs, causing my input to be delayed, and then missing the note/s.

I'm guessing you need logs for this
[network.log](https://github.com/ppy/osu-stable-issues/files/7314295/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/7314296/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/7314297/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/7314298/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/7314299/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/7314300/update_success.log)

**Comment by peppy** [comment]
Looking at the log, the issue is happening on every game thread in every game system. It's 100% not osu!, but I also can't tell you where the issue is coming from. Might be hardware, migth be throttling, https://osu.ppy.sh/help/wiki/Performance_Troubleshooting etc.

**Comment by WinterIsPretty** [comment]
I think it might be from a new discord update

**Comment by WinterIsPretty** [comment]
I really don't know, osu barely uses my memory or CPU
