### ISSUE TITLE
Stars:-x.xx* (approx.)

### ISSUE THREAD

**Issue by thnhmai06** [ppy/osu-stable-issues#859]
**Mapset star number display error** (`-x.xx* (approx.)`)
_Error in all mapset, all modes (std, ctb, taiko, mania), even when adding HR_

osu! version : Stable b20211014
Operating System : Windows 10 Pro 1903 (18362.30)
Language in image : Vietnamese

![image](https://user-images.githubusercontent.com/62001770/137301795-691777c0-85e8-4f39-97cb-60a3f00b984b.png)
![image](https://user-images.githubusercontent.com/62001770/137301828-055bc551-9dc6-46ab-91f9-5f277c86aba8.png)
![image](https://user-images.githubusercontent.com/62001770/137301860-e3e387cb-8dfd-4395-8879-927d22eace8e.png)
![image](https://user-images.githubusercontent.com/62001770/137301879-202f5fd8-cd96-42fb-bf55-acc55f7c971b.png)

**Comment by peppy** [comment]
it's a ~ not a -
