### ISSUE TITLE
map collections in osu multiplayer lobbies crash osu

### ISSUE THREAD

**Issue by C0D3-M4513R** [ppy/osu-stable-issues#860]
1. You are in a multiplayer lobby.
2. You open the collection menu (where you add that map to collections)
3. The map gets changed
4. You actually want to add/remove the map from the collections menu. So you click on a button
5. Osu sometimes does what you expect. Sometimes nothing happens. Then you try again, and it crashes. Sometimes it crashes instantly.

Osu usually crashes, if the map gets changed quickly, after you opened the map.
I have this bug mostly with MaidBot matches, when I want to add a map to a collection really quick.

I've been using cutting-edge, at the time of writing this post.

**Comment by peppy** [comment]
@C0D3-M4513R how do you get to the collection menu from a multiplayer room? do you mean from the results screen?

**Comment by C0D3-M4513R** [comment]
I just right click the map in the default lobby screen. That instantly opens the collection menu.
Afaik you cannot open the collections menu in the result screen.

**Comment by peppy** [comment]
Thanks! Forgot that was even a thing.

**Comment by peppy** [comment]
I've made a fix for this. It will be in the next cutting edge release.
