### ISSUE TITLE
(Proposal) Display beatmap backgrounds in main menu

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-stable-issues#861]
### Its simple and nice
![screenshot504](https://user-images.githubusercontent.com/62405013/137998567-b5d02772-7c0f-49cf-b3a7-7dddea838193.png)
![screenshot506](https://user-images.githubusercontent.com/62405013/137998596-9be95e7c-9658-41ff-a1cb-2c02798934a5.png)

**Comment by peppy** [comment]
This is already implemented in osu!(lazer).
