### ISSUE TITLE
When you update a map, the approx. doesn't appear

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#864]
If you update a map that is previously uploaded, like getting rid of a section or something, the map will stay at the same star rating and won't update to approx. rating.

![screenshot082](https://user-images.githubusercontent.com/52920930/138532286-134be7d4-e2ca-4074-b94b-75b6c8247753.jpg)
.
Supposed to be like 3-4*. I also notice the star images also align with the approx. star rating.

**Comment by peppy** [comment]
Correct. You would need to remove the online ID to reset it.

**Comment by WinterIsPretty** [comment]
Shouldn't it count the same as a "not submitted" map if you update it though; an unsubmitted version of the map? I just updated it to specifically see the approx. star rating if I removed a section. But if you don't want that then it's ok

**Comment by peppy** [comment]
that is how it will work in lazer, yes.
