### ISSUE TITLE
Displayed number of stars (affects sorting) does not match up with client or web SR

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu-stable-issues#865]
This bug affects both Stable and Cutting Edge.

Example: https://osu.ppy.sh/beatmapsets/608906#taiko/1285965
On the website it shows Star Difficulty is 6.07
The client SR also shows Stars: 6.07
However, the displayed number of stars is between 7.57-7.58 (determined by sorting by difficulty)

![screenshot075](https://user-images.githubusercontent.com/30021847/138570619-3e9aa009-f075-48f2-baa6-d1c4207f4c22.jpg)

Other examples where a discrepancy in SR is found:
https://osu.ppy.sh/beatmapsets/562250#taiko/1188759 (Says it's 7.61, but displays 7.12-7.13)
https://osu.ppy.sh/beatmapsets/673935#taiko/1426134 (Says it's 6.39, but displays 5.65-5.66)

Thanks to Teezel (https://osu.ppy.sh/users/7528639) for bringing this to my attention.

**Comment by peppy** [comment]
This is mentioned. In the changelog.

**Comment by mangomizer** [comment]
I've read the change logs and I think there is more going on here.

There have been zero documented changes to taiko SR calculation since Sept 2020 (morth rework). 

SR of first example was/is 7.58* under morth SR. Web is now showing 6.07* for some reason - so either web is currently inaccurate or morth SR has been doing it wrong for over a year.

If my initial assumptions are true, only one of the above can be correct, but not both.

**Comment by peppy** [comment]
@smoogipoo may be able to give you a better answer

**Comment by smoogipoo** [comment]
I've pushed a fix for this which should land in the next update. Will post more details in #difficulty-taiko in the osu!dev discord.
