### ISSUE TITLE
2021.1016.0 conflicts with "Kalimba Connect"

### ISSUE THREAD

**Issue by FishSnackems** [ppy/osu-stable-issues#867]
For some reason, build 2021.1016.0 conflicts with an app called "Kalimba Connect"
With it installed, osu!lazer will not start, instead leaving on a black/grey screen. Kalimba Connect, even though not open or in the background, starts not responding, eith a toast as well.

Deleting Kalimba Connect solves the issue, and I didn't have this issue in the previous build.

**Comment by peppy** [comment]
no idea what that is but that's out of scope of us.

**Comment by FishSnackems** [comment]
It seems to be a problem with osu!lazer and the way it opens, it seems to call some apps to open
