### ISSUE TITLE
Ignore ".git" hidden folder when uploading beatmap

### ISSUE THREAD

**Issue by dudehacker** [ppy/osu-stable-issues#869]
Problem statement:
osu doesn't have any version control, or support for team collaboration on a song compilation project.

Git can be used but the only issue is the '.git' folder also gets uploaded to osu server which isn't needed.

Solution:
Make osu ignore the ".git" folder when uploading map

I think this would be fairly simple to implement and would be very helpful feature for mappers.

**Comment by peppy** [comment]
You can store the git repository outside of osu!. It shouldn't be in the songs folder.

We will offer better version control in lazer, but for now you will need to find a workaround if you want to use such an approach. If you structure your git repo so the beatmap is in a folder you can symlink/junction it into the songs folder and avoid any issue.
