### ISSUE TITLE
Editor: Wrong snap colors on mania

### ISSUE THREAD

**Issue by jakads** [ppy/osu-stable-issues#87]
the letters in brackets are colors
White Red Blue Yellow Purple Gray

In the other modes:
1/6 (WPP RPP)
![image](https://user-images.githubusercontent.com/16955881/65370007-448c7300-dc8f-11e9-825a-609d195fc8f2.png)
1/12 (WGP BPG RGP BPG)
![image](https://user-images.githubusercontent.com/16955881/65370014-566e1600-dc8f-11e9-9796-9598c0808a00.png)
1/16 (WGYG BGYG RGYG BGYG)
![image](https://user-images.githubusercontent.com/16955881/65370019-684fb900-dc8f-11e9-8c78-6157c483a314.png)

In mania:
1/6 (RPP RPP) (=1/3 without W)
![image](https://user-images.githubusercontent.com/16955881/65370053-bc5a9d80-dc8f-11e9-8192-1108889d59e0.png)
1/12 (RPP RPP RPP RPP) (=1/3 without W)
![image](https://user-images.githubusercontent.com/16955881/65370057-c5e40580-dc8f-11e9-9433-8347d5ba8150.png)
1/16 (WYBY RYBY RYBY RYBY) (=1/8 with one less W)
![image](https://user-images.githubusercontent.com/16955881/65370069-dd22f300-dc8f-11e9-9dea-d4e6c2393f4c.png)

this oversight has been greatly confusing mania mappers between 1/3, 1/6, 1/12, and between 1/8, 1/16
this confusion is critical when trying to suggest a pattern via screenshots
please fix the mania one ok

**Comment by MillhioreF** [comment]
Fixed in next cuttingedge.
