### ISSUE TITLE
Loved Banner Not Working 

### ISSUE THREAD

**Issue by sea-bear1** [ppy/osu-stable-issues#872]
When you open a loved map, the banner thing doesn't open all the way and shows no text.

![image](https://user-images.githubusercontent.com/48499495/140026174-22fb03b5-8a7f-4834-bb07-53c2f57f4b37.png)

**Comment by peppy** [comment]
Nothing was changed surrounding this logic, and it works fine here.

This is going to be something your end, maybe an incorrect localisation or a skinning issue (judging from the brokenness on your screen it's going to be skin related).
