### ISSUE TITLE
cursor in 30 fps

### ISSUE THREAD

**Issue by vetyalmao** [ppy/osu-stable-issues#874]
i installed the new update and it fckd up my tablet. its like my cursor is in 30fps and everything else is fine. this didnt happened before this update, i think.

-older version doesnt fix it
-i use opentabletdriver, i tried wacom, hawku drivers too. didnt fix it
[session.log](https://github.com/ppy/osu-stable-issues/files/7492649/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/7492650/update_success.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/7492651/runtime.log)
.

**Comment by peppy** [comment]
Based on your own admission that older versions exhibit the same issue, this is going to be something else on your PC. Sounds like your drivers or something on your pc is inhibiting the input poll/report rate of your tablet.

You can check the common performance troubleshooting issues in [this guide](https://osu.ppy.sh/help/wiki/Performance_Troubleshooting) but I'd also potentially recommend refreshing (reinstalling) your windows to get rid of all the custom tablet software you have installed, if you still can't figure it out.
