### ISSUE TITLE
Stuttering Cursor Movement (Touchscreen Dragging)

### ISSUE THREAD

**Issue by proxycodone** [ppy/osu-stable-issues#875]
Replay from last year vs. yesterday. The latter's movement is substantially more laggy and I notice it the most.
https://cdn.discordapp.com/attachments/770908245883093002/906689559138545734/2021-11-06_19-38-15.mp4

The past few months I was anticipating to start playing osu! again when I get a touchscreen to play on. But I notice the past few times I made a purchase and installed osu!, it had this incredibly blocky cursor movement that skips and stutters. This time I'm having it with my $1,000 Lenovo Yoga (OS is Windows 11, and the previous computers I tried were Windows 10). I've never had this issue in the past years, but I've already encountered it numerous times this year. I've been able to play on low-end computers completely fine in the past, so I think it's silly to keep believing it's a hardware issue (and that I'm just unlucky with my purchases).

I also quickly drew shapes, stars, and spirals with my touchscreen on MS paint that turned out just as intended, but for whatever reason osu! doesn't handle those touchscreen inputs as well. I conclude it's on the game's side, so there could be a tweak that makes the game recognize touchscreen inputs more clearly. I really hope to hear a response, because this seriously affects my enjoyment of the game.

**Comment by peppy** [comment]
I closed this issue because it was incomplete at the time of viewing, so don't mind that.

Have you tried toggling "enable tablet OS support" in settings? That can help on some devices.

**Comment by proxycodone** [comment]
I tried enabling it yesterday and it didn't help my issue.

**Comment by peppy** [comment]
To investigate further, I'd need to know the touch hardware and drive on both PCs, including driver version.

We already support all known touch APIs, so there's a high possibility it's something local to your system. I'd suggest also trying other games and software and seeing how things work. Also, try toggling raw input as your touch screen may be trying to emulate that.

I don't believe this is a bug with osu! itself.

**Comment by proxycodone** [comment]
You can close this thread. I found a solution to my issue. Sorry for the inconvenience.

**Comment by peppy** [comment]
If possible could you please share the solution you found? It may help future visitors.

**Comment by proxycodone** [comment]
I enabled compatibility mode for Windows 11. However I just downgraded to Win10 and it doesn't matter if I have the option on or not.
