### ISSUE TITLE
Enabling Flashlight does not affect Star Rating in standard ruleset

### ISSUE THREAD

**Issue by MBmasher** [ppy/osu-stable-issues#877]
With the recent deploy, the flashlight mod now affects star rating. This can be seen server-side by calling from API. However the star rating does not change client-side.

**Comment by MBmasher** [comment]
Is this issue completely fixed? It still seems buggy, for example if I click on a certain map with FL enabled it'll show me the SR with FL, however even if I disable FL the SR will stay the same. Unlike other difficulty increasing mods such as HR and DT, enabling FL doesn't make the text turn red which makes me think it has something to do with that.

Also, slightly unrelated (because I don't know where I should post this) but it seems that the SR-based pass and FC medals don't work with FL.

**Comment by smoogipoo** [comment]
Nah, it will require an osu!stable fix, which is a bit more complex to do.

**Comment by smoogipoo** [comment]
Will be fixed in the next cutting edge.
