### ISSUE TITLE
Some skin elements are sometimes displayed incorrectly after changing the game resolution

### ISSUE THREAD

**Issue by ghost** [ppy/osu-stable-issues#879]
Some skin elements and seasonal backgrounds (which are plain black when this happens) are sometimes displayed incorrectly after the game's resolution is changed (for me, this happened when going from 1024x600 to 1440x900, although it may occur with other resolutions). It can be fixed by reloading the skin using Ctrl+Alt+Shift+S.

It makes the game completely unplayable unless you disable the in-game interface using Shift+Tab since something is covering all the objects on the map.

My current GPU is an AMD Radeon(TM) Vega 8 Graphics, and according to Device Manager, it is running driver version 30.0.13033.1000 (10/28/2021). Running osu! stable version b20211103.2 under Windows 11 Pro 21H2 build 22000.318. Not sure about the beta and cutting edge release streams. Compatibility mode disabled.

**Videos and images showing the issue:**

![Main menu](https://i.imgur.com/wcVAQJs.jpg)

![Song selection screen](https://i.imgur.com/IynMeH8.jpg)

![Skip button screenshot](https://i.imgur.com/UF3GYr0.jpg)

Here is also a video that is around 6 minutes of me going through different parts of the game's interface: https://www.youtube.com/watch?v=pKov60OADio

**Other:**
[runtime.log](https://pastebin.com/raw/RCS6X7x6) - [session.log](https://pastebin.com/raw/EYzLNzU5) - [update_success.log](https://pastebin.com/raw/DUCNsT73) - [skin used when this happened](https://cdn.discordapp.com/attachments/810722726440468530/909287857426923530/-__reowoTuna_v1.1_Selyu__-.osk)

**Comment by peppy** [comment]
Could you please show this with the default skin? I can't tell what is broken when you use a custom skin that is using weird elements in the first place.

**Comment by ghost** [comment]
> Could you please show this with the default skin? I can't tell what is broken when you use a custom skin that is using weird elements in the first place.

The problem is that the bug doesn't happen most of the time, and I would have to be changing my game resolution for years until it happens without even knowing if it is a skin-specific problem. The only way I got in the first place is because I play on a TV which makes playing certain maps harder with a specific resolution (for example, playing a jump map at 1920x1080 is harder than using 1366x768 with the "Render at native resolution" option enabled for me, so I just go and change my resolution and when I finish I revert it to what it was before). Also, what do you exactly mean by "weird elements"?

**Comment by peppy** [comment]
If it's a rare one then it's likely not going to be fixed. Stable is feature locked and we're not really looking to fix each and every bug, so if this doesn't affect thousands of users it likely won't be fixed. Stable is eventually being completely replaced.

"weird elements" such as fullscreen song select skinnning on elements which are only supposed to take up a few pixels. The liberties skinners have taken which from my perspective are broken usages.

**Comment by ghost** [comment]
> If it's a rare one then it's likely not going to be fixed. Stable is feature locked and we're not really looking to fix each and every bug, so if this doesn't affect thousands of users it likely won't be fixed. Stable is eventually being completely replaced.
> 
> "weird elements" such as fullscreen song select skinnning on elements which are only supposed to take up a few pixels. The liberties skinners have taken which from my perspective are broken usages.

Yeah, it makes sense. I think it's a won't fix then, I reported it because it happened to me more than once, and in one of those rare cases, the song selection menu looked fine, so I played through a map, got to a break, enabled the in-game interface, break ended, and I lost the map because the entire play area got black.

**Comment by peppy** [comment]
Going to close for now then. If you manage to reproduce with the default skin at some point, I'd be interested to see how it looks.
