### ISSUE TITLE
Pressing Esc on Difficulty Selection window in Editor often closes the map instead of just the window.

### ISSUE THREAD

**Issue by MzudemO** [ppy/osu-stable-issues#88]
The window itself isn't automatically in focus. It does not come into focus from selecting a difficulty. Even if it is clicked on multiple times Esc sometimes closes the whole map. The expected behavior would be Esc closing only the window.

[https://youtu.be/DWSSBccIW_o](url) Video of the problem, in each case I only press Esc once.

**Comment by peppy** [comment]
I believe there's already an attempted fix at this which doesn't work. Not sure it's worth the effort.

**Comment by MillhioreF** [comment]
Fixed in next cuttingedge, it was simpler than it appeared in this particular case.
