### ISSUE TITLE
Offset randomly breaks

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu-stable-issues#881]
It started happening around the halloween update where older maps often require -15ms to -25ms local offset change
The issue gets worse when I sometimes enable HR or alt tab from the game (doesn't seem to matter whether I'm mid song or on song select), the maps suddenly require -50ms even up to -150ms local offset change

Examples:
*Universal Offset is set to 0

[Map #1](https://puu.sh/IpKKa/515228a7c1.png) - No offset change, offset is about 50-65ms wrong
[Map #2](https://puu.sh/IpKHA/1b8e8816ce.png) - No offset change, offset feels correct
[Map #3](https://puu.sh/IpKKw/64111d51b6.png) - Bottom play no offset change, top play -50ms local offset change

Examples on when the issue fixes itself:
Universal Offset change (to a random number then back to 0)
Game restart
Skin change
Watching auto play

Videos:
[Potentially related?](https://puu.sh/IpKZV/645c19a3fe.mp4)
More to be added

**Comment by peppy** [comment]
First of all: it's not related to any update. please instead let us know of any changes to your PC hardware and software.

Potentially related to https://github.com/ppy/osu-stable-issues/issues/306, but lacking enough information to say.

**Comment by RaiLTC** [comment]
Oh I accidentally submitted the issue without it being ready, my bad
No change was made to my PC hardware or software

**Comment by peppy** [comment]
That makes it very hard to work with. If there were no configuration changes, then I can't really provide any insight or troubleshooting to help you.

**Comment by RaiLTC** [comment]
Can the issue be caused by a skin?

**Comment by peppy** [comment]
You can test this yourself by testing with the default skin.

**Comment by RaiLTC** [comment]
Just asked in general. It would be nice to know why it happens to avoid this in the future. I'm still not 100% it happens because of the skin but I'll give it a day's testing without the skin and see how it goes

I'll upload the [skin](https://puu.sh/IpVwj/f80c360273.osk) just in case if you want (I will not say anything if you save the hitsounds, trust me)

**Comment by RaiLTC** [comment]
After testing many skins over a few days it seems like the offset breaks heavily with the skin provided. I do get some offset issues with other skins (including default) but they're very minor. Could be caused by my hardware but I don't remember changing anything in the last few months (except installing and reinstalling games). Will reopen if this issue occurs again with over 10ms offset on a regular basis
