### ISSUE TITLE
Osu keeps scrolling

### ISSUE THREAD

**Issue by yowai-zip** [ppy/osu-stable-issues#883]
When I return to the OSU window from another window, the song selection screen keeps scrolling down and down. I tried unplugging the keyboard and mouse at this time, but the bug stayed happening. At this point, I tried to send a message to the chat in Osu by pressing F8, but I couldn't even type it.
Speaking of which, I recently changed the osumania4k layout from dfjk to zx/\. (It's a Japanese layout, so maybe the placement is different)
I am very confused. What should I do?
using windows 10
osu ver...20211103.2

**Comment by peppy** [comment]
Please post on the support forum https://osu.ppy.sh/community/forums/5. It's probably a controller or stuck key.

**Comment by smoogipoo** [comment]
I think numlock can cause this to happen too, but the above forum will give a more definitive answer.
