### ISSUE TITLE
Inconsistency on replay

### ISSUE THREAD

**Issue by Lock1** [ppy/osu-stable-issues#885]
While this issue may related to timing issue on [#554 Replaying replays is incorrect for some replays set before ~2019](https://github.com/ppy/osu-stable-issues/issues/554), this issue more focused on weird behaviour of client replay.

In beatmap paraoka - Rampage [Kawabunga!] https://osu.ppy.sh/beatmapsets/505170#osu/1075653, Cookiezi's score https://osu.ppy.sh/scores/osu/2466643975 set on 2018 with score shown in web and stable 2.845.401 scorev1 93.78% with 9 misses. For some reason if current client session watch any replay prior watching Cookie's replay, replaying his score will always failed with 2.841.967, 91.64% (https://osu.ppy.sh/ss/17284526/43dc). I never managed to watch Cookie's replay passing after watching any replay. 

But restarting client and watch Cookie's replay seems to fix it, consistently showing 2.845.401, 93.78% (https://osu.ppy.sh/ss/17284520/023a) which match with web score. Subsequent replay after first replay will be failed with same score above. Playing any map prior watching seems still allowing replay played properly. Haven't tested with spectating.

Lazer 2021.1120.0 seems doesn't have any effect on first and subsequent replay, but very often lazer score doesn't match scorev2 leaderboard score (leaderboard 881.604 with 93.78%, replay 881.563-884.374 with varying acc 93.50%-94.09% and 9-11 misses). And due lazer different HP system, Cookie's replay never failed on lazer.

Managed to reproduce this weird behaviour consistently with method above. Tested on stable 20211103.2 with default skin. Using 1660ti and 4800H around 1k FPS, stutter-free while replaying.

**Comment by peppy** [comment]
I can say with confidence any replay inaccuracy will not be fixed on stable. You're welcome to report this against the lazer repository (as a discussion) and we may get to it in a future.

Note that lazer does not use "scorev2", so scores will not match.
