### ISSUE TITLE
"Reset All Mods" button not resetting star rating with Flashlight selected

### ISSUE THREAD

**Issue by E223** [ppy/osu-stable-issues#886]
Re-reported from [here](https://osu.ppy.sh/community/forums/topics/1467411), which has some screenshots.

Selecting flashlight now affects the online difficulty retrieved for a beatmap. Deselecting the mod by using the "Reset All Mods" button on the mod selection panel does not cause the map to reset to its original star rating. Deselecting the mod normally works however.

Tested on both Stable (20211122.1) and Cutting Edge (20211119).

**Comment by mchltang** [comment]
Posting the screenshots here for one less click:

Star rating shown at the top left with FL applied is 8.44*:

![image](https://user-images.githubusercontent.com/5140808/142793749-31f9249d-353b-4362-bf10-9c25ca37aea2.png)

Star rating when FL removed with the "Reset all mods" button does not revert back to original nomod rating:

![image](https://user-images.githubusercontent.com/5140808/142793758-220a5475-c8ca-48dc-8036-74a651a7d602.png)

**Comment by smoogipoo** [comment]
Will be fixed in the next release.
