### ISSUE TITLE
MIDI Stable Support

### ISSUE THREAD

**Issue by sortedcord** [ppy/osu-stable-issues#889]
I thought of using my MIDI keyboard to play osu mania for fun. It was pretty straightforward in lazer as it detected the keys when I was setting the layout up. But I'm not sure why, it does not work in stable no matter what I do. @peppy hinted that it already exists in stable from [this comment](https://github.com/ppy/osu/issues/4328#issuecomment-466849063). If there are some steps I have to do before setting my layout up such that osu detects the midi controller then pls do let me know :)

**Comment by smoogipoo** [comment]
Stable does not support this.
