### ISSUE TITLE
osu! logo upon bootup appears behind any windows

### ISSUE THREAD

**Issue by jakads** [ppy/osu-stable-issues#89]
![image](https://user-images.githubusercontent.com/16955881/65370521-997eb800-dc94-11e9-8ce6-1def2a5cc34b.png)
yes

**Comment by peppy** [comment]
Doesn't happen on win10. Probably specific to windows version or something else. Not important to fix.

**Comment by nl-tatatat** [comment]
it happens for me too, on windows 10
