### ISSUE TITLE
Disabling Fullscreen mode makes Screen go black until osu is closed 

### ISSUE THREAD

**Issue by C0D3-M4513R** [ppy/osu-stable-issues#890]
The screen goes black, whenever the Editor is selected, when Fullscreen mode is active, or Fullscreen mode is disabled.

Sound still works, and you can still Alt+F4/close the game. You could theoretically even play maps, if you can navigate menus blindly, and play maps with a complete black screen.
You cannot open the Windows menu on the monitor, while this issue is occurring.

Discord still manages to capture the screen, while in that state, but Obs doesn't.

This bug was encountered in stable 20211122.1, beta 20211122 and cutting edge 20211119.

**Comment by peppy** [comment]
please search first, this is a duplicate.
