### ISSUE TITLE
pp calculator bug

### ISSUE THREAD

**Issue by miticka** [ppy/osu-stable-issues#892]
I had 145pp play on Ai no Sukima map not FC and when i passed the map again with higher combo and worse accuracy it was worth 139pp. Becouse it had higher combo, system just counted that play as the best play and i lost 4pp can 400 ranks. It happened to me twice on different maps. The system is calculating pp when you get more combo and I want you to fix it.

Thanks, Miticka

**Comment by peppy** [comment]
it will use the highest score you get on the beatmap
