### ISSUE TITLE
[Feature Request] About Design Page

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#894]
1. Add without lines preview storyboard
	In edit design Page, there are many auxiliary lines, can you remove the lines and frame the effective range(osu pixel range) to preview

2. Add reload storyboard
    I created a osb script in an external program, can a button be added to reload the storyboard? Or automatic reload after detecting file changes.

**Comment by peppy** [comment]
1. not sure what you mean.
2. Ctrl-L can be used to reload.

**Comment by wanjiaXG** [comment]
> 1. not sure what you mean.
> 2. Ctrl-L can be used to reload.

![screenshot1365](https://user-images.githubusercontent.com/26690346/144520099-548a1dd7-bcc4-434f-b96c-17e1a39fc2fa.png)
Like this picture, blue frame is effective range.
But now the editor cannot give this range directly for me, I need to add another picture to help me preview.
The other is the white grid, it is almost useless on the design page and affects the preview

So I want to hide the grid and show effective range. It is also possible to replace the grid with effective range

Thank you for telling me Ctrl-L, now reload storyboard is ok.

**Comment by peppy** [comment]
I think this will likely be something we improve in lazer (the next major update), when a design mode editor is added there. For now I'd recommend the existing method of adding a background image to track the edges.

**Comment by wanjiaXG** [comment]
> I think this will likely be something we improve in lazer (the next major update), when a design mode editor is added there. For now I'd recommend the existing method of adding a background image to track the edges.

ok
