### ISSUE TITLE
Major freezes during gameplay hapening randomly throughout gameplay.

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-stable-issues#895]
I have had this issue for about a year (might be shorter) where at random times, I get 2-3 seconds of the client freezing (but not the audio) and then resuming gameplay as if nothing happened making me miss multiple objects in turn.
Will be recording a video soon, but here are the most recent logs with a gameplay freeze just happening at the end of the performance.log
[network.log](https://github.com/ppy/osu-stable-issues/files/7643956/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/7643957/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/7643958/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/7643959/session.log)

I am able to save a replay when I fail or not, however, when I finish the beatmap, it doesn't submit the score and comes up with "Unable to process score" popup.
In this case, I instantly failed to show what the replay looks like under a freeze.
[Coppertine - Hige Driver - I Wanna Feel Your Love (feat. shully) [Insane] (2021-12-02) Osu.osr.zip](https://github.com/ppy/osu-stable-issues/files/7643967/Coppertine.-.Hige.Driver.-.I.Wanna.Feel.Your.Love.feat.shully.Insane.2021-12-02.Osu.osr.zip)
Map: https://osu.ppy.sh/beatmapsets/682289#osu/1442769
(This happens on any map, just providing link so you can view the replay)

https://user-images.githubusercontent.com/37494321/144475479-6be5835a-5cea-49ed-8deb-7d9d4eefe0ba.mp4
Provided video shows what normaly happens on a freeze.

Replay for video above:
[Coppertine - Aimer - Kogoesou na Kisetsu kara (TV Size) [Collab Relentless Love] (2021-12-02) Osu.zip](https://github.com/ppy/osu-stable-issues/files/7644071/Coppertine.-.Aimer.-.Kogoesou.na.Kisetsu.kara.TV.Size.Collab.Relentless.Love.2021-12-02.Osu.zip)
(Map: https://osu.ppy.sh/beatmapsets/773247#osu/1625426)

This is still affected on restart and with discord overlay disabled and game mode enabled.
(Note: in an average play session, I would say this happens around 5-15 times within 3-5 hours)

**Comment by Coppertine** [comment]
Attempting to do diagnostic checks now, no need to close.

**Comment by Coppertine** [comment]
Closing issue for now as enabling "Reduce Dropped frames" and changing to "Optimal" works for now. will reopen, if it still occurs.

**Comment by Coppertine** [comment]
Reopening due to issue still occuring.

**Comment by peppy** [comment]
https://osu.ppy.sh/help/wiki/Performance_Troubleshooting 

This is not an issue with the game. Nothing has changed for years. Please use the above guide or ask for help in the help forum. It is going to be a hardware or software change at your end.
