### ISSUE TITLE
Slidertick counted as sliderend for scoring

### ISSUE THREAD

**Issue by pianodude1011** [ppy/osu-stable-issues#896]
Score for sliders is counted as +10 per slidertick, +30 per sliderend. On some sliders tho, the last slidertick is counted as a sliderend, resulting in 20 extra score.

I made two maps to demonstrate this in [this osk](https://cdn.discordapp.com/attachments/773824340772651008/916226401722593300/wwwwwwwwwwwww_-_wwwwwwwwwwww.osz). slider1 and slider2 are similar, as observed in this picture [here](https://i.imgur.com/Y5gdwG6.png) of the two sliders. The second slider is a bit shorter but since they both have only one slidertick, they should count for the same amount of score, but slider2 gives 20 extra score over slider1.

**Comment by smoogipoo** [comment]
I don't think this is going to be changed in osu!stable, and is likely already fixed in osu!lazer.
