### ISSUE TITLE
osu!mania editor. hitsound sample import doesn't output sound

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu-stable-issues#897]
In osu!mania editor, when you use the "**Sample import**"(ctrl+shift+i) apply the hitsound.  And **open a difficulty for reference.  sample hitsound doesn't work**. (see the video)

For osu!mania mapper is a bit inconvenient, expect it to be fixed..

**video:**
https://youtu.be/kEDpsG5tM84

**Comment by peppy** [comment]
Did it ever work? Is this intended to be a regression report, or a feature request?

**Comment by mas-alone** [comment]
> Did it ever work? Is this intended to be a regression report, or a feature request?

is bug report. I open a difficulty for reference in the video.  then all sample hitsound doesn't work(in video is 00:20, in the Column 0)

**Comment by peppy** [comment]
is it specific to that beatmap? Does it work in other people's beatmaps?

**Comment by mas-alone** [comment]
> is it specific to that beatmap? Does it work in other people's beatmaps?

doesn't work in all has “sample hitsound“ beatmap.
This bug will only appear if a difficulty for reference is opened in the editor

**Comment by mas-alone** [comment]
> is it specific to that beatmap? Does it work in other people's beatmaps?

like this beatmap.
https://osu.ppy.sh/beatmapsets/1408692#mania/2929342

Open the "hitsound (9K)" diff in the editor, you can clearly hear the sound of column 2 (snareclap2), but there is no sound after you "open a difficulty for reference"(any diff)

**Comment by smoogipoo** [comment]
Will be resolved in the next cutting edge build.
