### ISSUE TITLE
[Bug]In Design Page

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#898]
if media file name contain comma, the parser of osu beatmap will fail.

https://user-images.githubusercontent.com/26690346/144698330-741badd3-3629-43cd-aec7-60a1ed37294e.mp4

**Comment by wanjiaXG** [comment]
test file name "vi,d.avi".

**Comment by smoogipoo** [comment]
Don’t do that. This is pretty out of scope.

**Comment by wanjiaXG** [comment]
> 



> Don’t do that. This is pretty out of scope.
I think it can be repaired by judging the symbol and renaming it before using the material, not much code is required.
