### ISSUE TITLE
Offset issue

### ISSUE THREAD

**Issue by mrink28** [ppy/osu-stable-issues#899]
Im fairly sure this is relating to issue #306 but i might as well post it.

I experience all the same issues as in that issue, although for me its not constant between sessions, it sometimes happens and sometimes doesnt. Ive tried reinstalling audio drivers, trying in lazer, other stream releases but nothing fixes it.

(sidenote- it starts to happen in between beatmaps not straight away)

Build- Latest 20211122.1

**Comment by peppy** [comment]
Please post in that thread.
