### ISSUE TITLE
Editor "show in-game help" option does nothing

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#9]
like 5 years or so ago, it used to display an overlay helping to inform the user of shortcuts and other editor information. For the past many years, it has done nothing at all.
The feature would be useful if it actually worked.

![image](https://user-images.githubusercontent.com/33286824/65245802-47366f00-dabb-11e9-9cb0-09167f040c05.png)
(image sourced from https://osu.ppy.sh/community/forums/topics/122335 , I couldn't find other screenshots of what it looked like)

**Comment by peppy** [comment]
I believe this may have been disabled due to it losing relevance (and being misaligned). It may work better to link to wiki pages via the Help menu these days.

**Comment by dorothy3242** [comment]
Something similar to the submission window links there could be a good start - it would make the helpful submission window links accessible without needing to submit/update a beatmap.

or something like
- Ranking Criteria
- https://osu.ppy.sh/help/wiki/Shortcut_Key_Reference/#beatmap-editor Editor shortcut key reference wiki page
- Mapping Discussions forum
- Modding Queues forum
- Mapping / Modding Compendium https://osu.ppy.sh/community/forums/topics/722865 (we could remake this as a wiki page if needed)

Also in this case the tools on the left side should have their tooltips updated too. Tools on the right side state their keyboard shortcuts in the tooltips, tools on the left side do not.

**Comment by peppy** [comment]
The help mentioned above should already be in the BSS upload window. Please open another issue if you want to see any of that updated.

The help screen itself is likely not coming back though.
