### ISSUE TITLE
Editor Ctrl+P should usually open the timing window

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#90]
Ctrl+Shift+P to add inherited lines does open the "Timing and Control Points" window, but Ctrl+P to add uninherited lines does not, nor does it have any warning/confirmation dialogue. 

Ctrl+P should open the timing window to prevent it from being added on mistake, **unless you're on the timing tab**. Or some other kind of notification that the shortcut did something.

It shouldn't open the timing window when the user is on the timing tab because in this case you would be using it to quickly add and adjust timing points, and opening the timing window in that case would make timing more annoying.

Currently it's possible to add timing points by mistake and not realize because of how the command adds the timing point without telling you it did.

**Comment by nl-tatatat** [comment]
I'd say this is actually a useful feature, when I'm timing variable bpm songs, I need to place many red lines in succession, and constantly opening up the timing window everytime I place down a red line is a huge hassle.

**Comment by dorothy3242** [comment]
maybe in that case 
![image](https://user-images.githubusercontent.com/33286824/65379514-54a85080-dc97-11e9-858a-70c57c41c1e8.png) this style notif is a better solution

**Comment by peppy** [comment]
You still have both options with the change, based on where you are in the editor.

**Comment by nl-tatatat** [comment]
yes, but the timing tab is very bad for placing down red lines. [Compose](https://i.imgur.com/l4ChJ2e.png) gives you a lot more useful information than [Timing](https://i.imgur.com/A0wyQsK.png) 
No snaps(besides 1/1 which isn't useful) are shown in the timing tab, the bpm flags get in the way, and the metronome drowns out the music making it harder to actually time the song.

The compose tab is vastly superior for timing, and the originally proposed change will add unneeded overhead to the timing process. Every time you want to add a red line, you'll have to close the timing panel.

For green lines, opening the timing panel every time is perfectly fine. Green lines serve no purpose without opening it up. They're exclusively for SV changes, sample set changes, volume changes, and kiai time. For red lines, this is not the case. Many times you'll want to place down a red line where you think a sound is, and replay the song back at 1/4x speed to fine tune the offest(by adinng another red line and deleting the old one) Red lines can also be for metronome resets, where you don't have to adjust anything about the red line in the timing panel.

**Comment by peppy** [comment]
I think the new behaviour is more consistent, so we will leave it that way for now.

**Comment by nl-tatatat** [comment]
its just a ton of wasted time mapping constantly closing the timing panel. but okay.

**Comment by nl-tatatat** [comment]
Its going to significantly increase the time it takes to time maps, for consistency's sake.
