### ISSUE TITLE
Incorrect replay conversion from stable to lazer

### ISSUE THREAD

**Issue by Ivannomg** [ppy/osu-stable-issues#900]
I dunno should it be here or not, but it is an issue. I tried to add my replay with relax, exported to file, from stable to lazer, but every note, which should be clicked automatically by relax mod, counts as miss. Here are videos I recorded as example:

https://user-images.githubusercontent.com/68359818/144729017-66bdab9e-ccac-4218-bf09-2cfbaf4b77a9.mp4

https://user-images.githubusercontent.com/68359818/144729202-f74e55b7-e1c6-473e-8476-24ebde60b5ef.mp4

How to duplicate:
1)Play any map with relax mod in stable;
2)Export replay to .osr file;
3)Import replay to lazer;
4)Watch replay in lazer.

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/9560

**Comment by Ivannomg** [comment]
sorry
