### ISSUE TITLE
Audio doesn't get sent to proper output

### ISSUE THREAD

**Issue by Ethereal-Dev** [ppy/osu-stable-issues#902]
Hello everyone,

For the past ~2 weeks I've been playing osu! with a virtual mixer (voicemeeter potato) and setting osu! to output the game sound directly to my headphones to bypass the virtual mixer to avoid any delay.

**My issue**
This has been working like a charm for around two weeks now, but 30 minutes ago this stopped working while I was playing.
Now, when I attempt to route my game audio directly to my headphones using the in-game output device setting it routes the sound to the virtual mixer anyway. When I attempt to route my game sound to my monitor instead, it works as expected and the game sound comes through my monitor.

Also, when forcing the audio to go straight to my headphones, the performance I get in the song select menu absolutely tanks to around 38 fps, (instead of the usual 288 fps) making me believe that this is a game issue.
Default output device is set to my headphones as well.
Video: https://youtu.be/PC1gDXoaOm8

**My attempts to fix it**
(None of the following things have resolved the issue)
I have tried:
1. Re-installing osu!
2. Re-installing voicemeeter potato (the virtual mixer)
3. Changing the windows default output device and using the osu! default output device option

**What does work**
I have discovered through some research that after disabling the virtual mixer I can once again route my game sound to my headphones without issue, but then I do not have desktop audio anymore, and if I attempt to re-enable the virtual mixer then the issue returns, leaving me without game sound.

This way, I can at least keep playing osu!, but this is not a "real" fix.

Short video using OBS to show where the audio is going.
the "osu audio" track is my speaker output
the "desktop audio" is my virtual mixer
https://youtu.be/5T73efMbEt4

Does anyone have any idea how I can resolve this issue?

**Comment by peppy** [comment]
No ideas sorry. It’s not going to be an osu! side issue unless you changes device names between when it was and wasn’t working.
