### ISSUE TITLE
Ranked icon not resetting its direction when switching from approved to ranked map.

### ISSUE THREAD

**Issue by eggooooo** [ppy/osu-stable-issues#903]
When quickly switching from an "approved" map to a "ranked" map, the icon in the top-left doesn't reset it's direction and stays tilted

Video demonstrating the issue here:

https://user-images.githubusercontent.com/64386789/145454474-2248140d-f192-4846-9578-f13b46a71d73.mp4

**Comment by peppy** [comment]
Consider it an easter egg.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
