### ISSUE TITLE
Osu! Refuses to launch through samsprung launcher

### ISSUE THREAD

**Issue by FishSnackems** [ppy/osu-stable-issues#904]
I'm running a z flip 3, and I have the samsprung launcher to open apps through the widget screen.

It seems to bug out some apps, because of screen rotation issues.

Osu! Refuses to launch through this, while it will open fine on the main device. From what I can tell, osu! Has trouble running on environments that aren't standard, i.e. plugging in adapters to a phone.

Could be a problem with my specific device, but it's brand new and might just be a clash with samsprung launcher itself.

This is version 2021.1207.0, but I haven't been able to find any version that works with it.

**Comment by smoogipoo** [comment]
Wrong repository. Try https://github.com/ppy/osu.

But we don't have the ability to support every esoteric software combination in existence. It's likely on you to figure out what causes it/to fix it.
