### ISSUE TITLE
Linux Wine Login Failure

### ISSUE THREAD

**Issue by bearrrmann** [ppy/osu-stable-issues#906]
Im running Kubuntu and Wine with osu stable and I can enter my username and password and then it says verification pending forever, it doesnt send me a verification or anything it just says that a verification is pending. I can send a log or whatever it is if you tell me how

**Comment by peppy** [comment]
Sorry but wine isn't officially supported. Please consider using the newer client (https://github.com/ppy/osu#running-osu) instead.
