### ISSUE TITLE
new star rating sometimes goes to 0* when adding flashlight

### ISSUE THREAD

**Issue by Ocklepod** [ppy/osu-stable-issues#909]
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/56438032/146224409-4d6c2c9e-1837-418a-a79b-3d671dcc32ac.png)
and here's one just without FL
![image](https://user-images.githubusercontent.com/56438032/146224568-433851fc-b888-47ce-81b7-9bd4627a4b0a.png)

didn't check all mod combinations, but all combinations of nm,hd,hr,dt are fine without FL and go to 0* with FL

btw this also affects pp, according to osu website hdhrdtfl SS is worth 1 pp, hdhrdt SS ist worth 22 pp

**Comment by peppy** [comment]
This particular beatmap should be fixed now. We're running a larger re-process operation to ensure the same issue isn't present on other beatmaps.
