### ISSUE TITLE
AiMod "this mapset needs 1 easy/normal diff" even if it detects lowest diff as normal

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#91]
example map : https://osu.ppy.sh/beatmapsets/1001305#osu/2096052
![image](https://user-images.githubusercontent.com/33286824/65374827-56085780-dc5c-11e9-8801-3fa9f69171c4.png)

This mapset has a lowest difficulty Easy, shown as such on the website, but AiMod thinks otherwise...

This may be because of different parts of AiMod using different difficulty detection standards than the rest of the game. 
It should detect difficulty based off SR (the same ranges as used for difficulty icons on the website), and apply the warning and AiMod difficulty label based off of that. 

Currently ranking criteria spread requirements differ based on the drain time of the top difficulty of the map, so this warning should be updated to reflect that or be gotten rid of altogether. 

https://osu.ppy.sh/help/wiki/Ranking_Criteria#beatmapset

Under 3:30: Lowest difficulty required is Normal
Between 3:30 - 4:15 : Lowest difficulty required is Hard
Between 4:15 - 5:00 : Lowest difficulty required is Insane
Above 5:00 : No lowest difficulty requirements.

**Comment by nl-tatatat** [comment]
happens on every single non osu!standard mapset too

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge.
