### ISSUE TITLE
Osu having extremely low MS until alt-tabbing and tabbing back in

### ISSUE THREAD

**Issue by emmfreak** [ppy/osu-stable-issues#910]
I am running on a GTX 1650 with an intel i5 9300H

Osu has extremely low MS until alt-tabbing and tabbing back in. I've gone so far as to reinstall the game and running the repair tool within the osu! directory, but it doesn't seem to work. I've also tried enabling and disabling compatibility mode, which works for a little bit but stops working shortly after.

**Comment by peppy** [comment]
https://osu.ppy.sh/help/wiki/Performance_Troubleshooting 

going to be something else on your system interacting with the game. let us know if you figure out what it is.
