### ISSUE TITLE
Mirror not working properly in Special Styled maps for osu!mania

### ISSUE THREAD

**Issue by Sebaex** [ppy/osu-stable-issues#912]
Since special style (N+1) is based on beatmania/bms playstyles, mirror mod seems to be working incorrectly, what's the problem? All the notes being mirrored like if was a normal map (since the "special style" option can be toggled in the editor)

Map used: https://osu.ppy.sh/beatmapsets/634232#mania/2254451

Screenshots: 

- Nomod:
![screenshot2476](https://user-images.githubusercontent.com/22472487/146479682-76a97c42-5b84-4e91-87ba-b95a9232db86.jpg)

- Mirror:
![screenshot2473](https://user-images.githubusercontent.com/22472487/146479688-aa6f0467-f44a-4a8f-962a-6905674fecac.jpg)

As seen on the images, all notes get mirrored so it bothers on the scratch lane (yellow note in this case), while on beatmania/bms clients, mirror applies to notes only (white and blue) leaving the scratch notes on the same lane since this is up to the player how he plays (1P side for left side, 2P side for right side)

**Comment by Sebaex** [comment]
And as a proof for this, the map is ranked and the "special style" option is turned **on** in the editor
![Mirror issue](https://user-images.githubusercontent.com/22472487/146480092-9daf2aba-443f-4fe9-966c-14cf771558da.jpg)

**Comment by smoogipoo** [comment]
Ouch. I suppose this may be alright to fix and break existing replays because it's not such a common scenario? It's also an issue in lazer.

**Comment by Sebaex** [comment]
> Ouch. I suppose this may be alright to fix and break existing replays because it's not such a common scenario? It's also an issue in lazer.

Also, seems like Random is also affecting the scratch lane but only in lazer since there isn't an option there to differentiate special styled from normal ones

**Comment by peppy** [comment]
Not sure if it's worth fixing this in stable. If it hasn't been reported until now, it's safe to say it's a very fringe case that we should (definitely) fix in lazer.

**Comment by smoogipoo** [comment]
Let's not fix this in osu-stable. Discussion for osu-lazer here: https://github.com/ppy/osu/discussions/16144
