### ISSUE TITLE
Sliders disappearing and then game crash

### ISSUE THREAD

**Issue by Ferco124** [ppy/osu-stable-issues#914]
Sliders disappear in the middle of the map when i was playing multiplayer with my friend. The game becomes super laggy with 1 fps only and crashes right after.
Here is a video of what happened https://www.youtube.com/watch?v=0xG3mq6qcY0
It happens at around 1:12
This had also happened to my friend before when he was playing road of resistance mapped by sotarks in single player mode but unfortunally theres no video of it

**Comment by doubledge-spec** [comment]
Logs would be nice. They are found in the Game install directory under the `Logs` folder

**Comment by ghost** [comment]
Could you please provide logs from your osu! folder after a crash (before starting the game again)

_Originally posted by @peppy in https://github.com/ppy/osu-stable-issues/issues/913#issuecomment-996498432_

**Comment by peppy** [comment]
This looks like a driver issue. Please check for recent changes to your GPU drivers and either upgrade or rollback.
