### ISSUE TITLE
BSS Triple Decimals had inconsistencies

### ISSUE THREAD

**Issue by ReiFan49** [ppy/osu-stable-issues#915]
## Problem
- For any beatmaps with low BPM and **actually have at least three decimals behind**, it only shows **two decimals behind** instead. [Beatmap that describes this problem](https://osu.ppy.sh/beatmapsets/1652493), this map was supposed to be 104.**475**bpm instead of 104.**480**bpm.
- ~~I guess the very high BPM beatmap on listing now fixed? Ok.~~

**Comment by peppy** [comment]
This is an intended change. It still uses the correct BPM internally. There's no reason to show this on public facing displays (it has no meaning to a player).
