### ISSUE TITLE
Incorrect Auto Replay Rate

### ISSUE THREAD

**Issue by Stehsaer** [ppy/osu-stable-issues#916]
Select Auto mod and click your mouse to start an autoplay.
just after you click your mouse and quickly press F once or twice, before the ingame interface (such as scores, accuracy) show up, when the playback rate can be toggled to 2x or 0.5x, the actual play rate remains 1x.
if you start with "2x playback" when it's actually 1x playback, switching to "0.5x playback" can lead to 0.25x playback.
start with "0.5x playback" with actual 1x playback, switching to "2x playback" can lead to 4x playback
WOW
ppy pls fix this

**Comment by Stehsaer** [comment]
osu! version: 20211218.2

**Comment by smoogipoo** [comment]
Will be fixed in the next CE.
