### ISSUE TITLE
Extreme delay between music and gameplay on Windows 11

### ISSUE THREAD

**Issue by crnvl** [ppy/osu-stable-issues#918]
I've just recently updated to Windows 11 and now I'm experiencing around 500ms of delay between music and the actual circles for the beat. Input and sounds in other parts of the game work fine. 
I've already updated my .NET Installation and tried Compatibility Mode, but neither of those seemed to work.

**Comment by peppy** [comment]
This isn't really a place for technical support, but I can offer you a few starting points:
- make sure your universal offset in settings is at 0ms (to start with)
- make sure you aren't using wireless headphones
- update and downgrade your audio drivers
- if you're using a usb headset, try plugging in analog headphones to see if it helps

**Comment by crnvl** [comment]
Didn't notice my offset was set to -300ms for some reason (I don't remember changing it from 0), Thanks for the quick response! :)
