### ISSUE TITLE
Inconsistent leaderboard rankings

### ISSUE THREAD

**Issue by revelsix** [ppy/osu-stable-issues#92]
![image](https://user-images.githubusercontent.com/45189851/65378594-967dca80-dc88-11e9-8eb3-58168864d0dd.png)

I've rarely seen a leaderboard rank of mine actually match up with the __ out of ____ number in the personal best section.

**Comment by revelsix** [comment]
Possibly related to #75

**Comment by MillhioreF** [comment]
I'm not sure if this is really wrong in this case since you're tied for 9th place. Displaying ties better would take moderate effort for very little gain.

Leaderboard conditions will be improved by #18 and #75

**Comment by peppy** [comment]
This should be fixed now, thanks to infrastructure changes [detailed here](https://twitter.com/osustatus/status/1196735955559829505).
