### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by Menotdan** [ppy/osu-stable-issues#920]
I've noticed on the forums that a few people are complaining of having some issue with osu! where they will have some sort of memory leak and the memory osu! uses builds up over time, and my friend has had this same issue. I'm not sure what's causing it as I can't do any testing on the issue myself, because it does not affect me. I do know my friend has tried several things to resolve the issue:

- Windows Update
- GPU Driver Updates
- Restarting PC
- sfc /scannow
- Starting an instance of osu! with no local scores or beatmaps other than default stuff

**Comment by smoogipoo** [comment]
Can you get your friend to reproduce the high memory usage and then open the 32-bit task manager (`C:\Windows\SysWOW64\taskmgr.exe`), right click the osu! process -> create dump file, and then send that to pe@ppy.sh along with a link to this issue? Do not post it here.

Also, how many maps do they have loaded?

**Comment by Menotdan** [comment]
They have 12K beatmaps loaded

**Comment by smoogipoo** [comment]
I think I have found a lead on this, do they have seasonal backgrounds turned on? If so, have them turn it off and see if it still happens.

**Comment by Menotdan** [comment]
> I think I have found a lead on this, do they have seasonal backgrounds turned on? If so, have them turn it off and see if it still happens.

alr they are not online rn, but I will still send ppy the dump file in case it helps, and I will tell them to try that

**Comment by Menotdan** [comment]
@smoogipoo Ok just got update from friend who is apparently online rn actually (but only as a quick thing), he has tried turning seasonal backgrounds off already, and it didn't work

**Comment by smoogipoo** [comment]
That's on a fresh restart of osu! too, yes? Unfortunate, because there's definitely an issue there. We'll need that dump from them to go any further.

**Comment by Menotdan** [comment]
@smoogipoo yeah the process dump is from normal osu! install with all the stuff, but the issue was still occurring on a completely fresh install with seasonal backgrounds off
I _have_ sent the process dump already btw

**Comment by Menotdan** [comment]
> Can you get your friend to reproduce the high memory usage and then open the 32-bit task manager (`C:\Windows\SysWOW64\taskmgr.exe`), right click the osu! process -> create dump file, and then send that to [pe@ppy.sh](mailto:pe@ppy.sh)

also here I'm assuming you mean high memory usage before crash right? i cant think of any way to get it after crash so I'm guessing so

**Comment by smoogipoo** [comment]
Yep that's correct. Even just 2GB would be enough to indicate an issue, which should be reached long before a crash.

**Comment by Menotdan** [comment]
> Yep that's correct. Even just 2GB would be enough to indicate an issue, which should be reached long before a crash.

i mean not that long but a substantial amount before, yeah
that was another thing I was gonna mention
my friend says he notices differences in memory buildup in different parts of osu!, like when playing, he says it built up about 2GB in the span of one run of ICDD - Uta (roughly 9 min), in other parts I haven't been given a definite measurement, but he says in the song select the memory buildup is much slower, and when he is tabbed out it is none. I'm not 100% sure how accurate these measurements are because I didn't do them, but they might give a vague idea of where to look if the process dump doesn't immediately give it away

**Comment by smoogipoo** [comment]
Thanks for the additional info. Out of curiosity, is your friend able to provide a [dxdiag report](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe)?

**Comment by Menotdan** [comment]
> Thanks for the additional info. Out of curiosity, is your friend able to provide a [dxdiag report](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe)?

not at the moment cuz they are asleep but
I will ask tommorow

**Comment by smoogipoo** [comment]
As a bonus, have them test with the default skin and see if it still happens.

**Comment by Menotdan** [comment]
> As a bonus, have them test with the default skin and see if it still happens.

They already tried that with the complete fresh install setup, and they said it still happened, but slower. Again, I'm unsure if "slower" is actually the case, or how much slower, but that is what I was told

**Comment by Menotdan** [comment]
@smoogipoo do i send the dxdiag here or to peppy's email

**Comment by smoogipoo** [comment]
Here is fine.

**Comment by Menotdan** [comment]
Ok, here is my friend's DxDiag output
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/7759414/DxDiag.txt)

**Comment by smoogipoo** [comment]
Thanks. Do they have Overwolf installed? We've had a few users experiencing ever-increasing RAM usage with it running.

**Comment by Menotdan** [comment]
> Thanks. Do they have Overwolf installed? We've had a few users experiencing ever-increasing RAM usage with it running.

yeah they did
removing it fixed the problem
do we think this is osu related issue or overwolf issue
and should I close this

**Comment by peppy** [comment]
I think you will need to report this to overwolf. It is an issue their end.

**Comment by Menotdan** [comment]
> I think you will need to report this to overwolf. It is an issue their end.

do you know what exactly the issue is? and how it causes the osu process to use more memory?
it seems weird that another program would be able to create lots of memory usage in osu
and also, why did it only start a week ago? was it some overwolf update that cause it maybe

**Comment by peppy** [comment]
overlays interact with the graphics context of osu!. there's no way for us to know what it's doing. you will need to report to them and have them fix it.
