### ISSUE TITLE
Importing beatmaps in multi freezes the game

### ISSUE THREAD

**Issue by timiimit** [ppy/osu-stable-issues#922]
### What's wrong?
Game started freezing for 3-5 seconds when I download and import a map. It happens only sometimes but always just in multi. Originally I thought it was happening every single time I imported the map, but after I recorded a video for this bug report I found out that's not the case.

### When did it start happening?
I never had such a problem before. It started happening 2 or 3 weeks ago. I'm not sure if there was an update when it started happening. I should mention that it started happening after coming back to windows after using only linux for a week or so (I have a dual boot system), so I'm not ruling out that somehow linux triggered this. This should be kept in mind as this might not even be osu!'s fault but I cannot think of any reason linux would affect it.

### What have you tried so far?
I tried everything I can think of.

- I usually play on cutting edge, so I switched to stable,
- I reset settings and repaired osu! with the `repair osu!` shortcut
- I rebuilt osu!.db database many times while testing
- I checked if theres a problem with my disk, but `chkdsk` command reported no bad sectors or other disk errors.
- I tried removing half of maps just to see if that affects this in any way
- I copied all executable files (without any data) to another disk even though `chkdisk` reported no errors just to make be 100% sure it's not disk's fault

The only thing that seemed like it temporarily fixed the issue was deleting `osu!.db` and rebuilding the database. I did this quite a handful of times while testing and it always allowed me to import 1 (or maybe sometimes 2) maps before it started freezing again when importing maps.

### Can we see what exactly happens?
I decided to record myself downloading same map over and over again from multi to see how freezing changes and if it's beatmap set dependent. In the video I download 4 different maps multiple times and at the end I also download 3 maps directly in the osu!direct menu and show that game doesn't freeze when maps import when I enter song select. Video shows a clean copy of just executable files. In the description of the video I provided timestamps of when I'm importing maps and the outcomes, so you can skip the parts where I'm deleting just downloaded beatmaps. Apologies for not capturing whole game screen, all relevant information is still visible.

Video link: https://youtu.be/RBcZ38Kn22U

### What version of osu! are you using?
As I stated already before, I have stable stream. version `LastVersion = b20211218.2` (from osu!.[USERNAME].cfg).

hashes of my files (i assume) as provided in osu!.cfg:
```
_ReleaseStream = Stable40
_UpdateFailCount = 0
h_avcodec-51.dll = b66478cc0f9ec50810489a039ced642b
h_avformat-52.dll = c00b30289cc427caff97af5aa3d43e03
h_avutil-49.dll = 47c83b958951331ba409d6b80316250c
h_bass.dll = 7623474a8b9bec1e3ffca813cdf93bc3
h_bass_fx.dll = 3ad3c0fd4dca001a2f9e707b74544919
h_Microsoft.Ink.dll = 82d4ee89f4a39c764fa6297a95ebb10e
h_osu!.exe = 26c0fbb9d090d7c47c8467ad071cc3ed
h_osu!ui.dll = 2c2b660b51eceda6e8bc77aa762ae8c5
h_pthreadGC2.dll = 00678eb6be3b52d562b66218c93e21a8
h_osu!gameplay.dll = 4cb98d63f1b2b9dc38e10e9901ec52d8
h_OpenTK.dll = b4d949571134fc3ec6c28f1af7a75e49
h_d3dcompiler_47.dll = c5b362bce86bb0ad3149c4540201331d
h_libEGL.dll = 9f7f22cef980ec272a9b73bf317500e4
h_libGLESv2.dll = a4dfddff62d1e917ebb0688cf8d96be7
h_osu!seasonal.dll = dccf5b6ff65257c9ea301f25f40b4a8b
h_osu!auth.dll = e761006cb6e52f55aeec3a7e42a8f862
```

**Comment by smoogipoo** [comment]
This is going to be related to the recent diffcalc RPC changes. The pause will be reduced to 500ms in the next update, but this is not a situation I foresaw...

**Comment by smoogipoo** [comment]
Should be fixed in the next CE.
