### ISSUE TITLE
Shader issues with letterboxing enabled 

### ISSUE THREAD

**Issue by eggooooo** [ppy/osu-stable-issues#923]
I've been experiencing some weird issues with letterboxing and shaders on.
The shader layer or vice-versa (the actual game window) seems to snap at the bottom-left of my screen when switching between menus, switching songs in song select or even in-game sometimes which is really distracting sometimes when playing.

This issue persists when the "softening filter" is enabled, in which case it'll snap to the bottom-left and stay there until this is disabled again.

Issues occuring in menus/gameplay:

https://youtu.be/P8IO5uYDxek
(had to upload this to yt because of githubs 10mb limit)

Running on Windows 11 Pro 21H2 Build 22000.376
osu! ver: b20211222cuttingedge

**Comment by smoogipoo** [comment]
Thanks for the report. Should be fixed in the next CE. Use beta/stable for the time being.
