### ISSUE TITLE
Scores not saving for up to 15 minutes after map played

### ISSUE THREAD

**Issue by Rulerofzeworld** [ppy/osu-stable-issues#924]
## Problem details:

After completing a map, the score appears on the local leaderboards but doesn't save to the local scores database immediately (called scores.db).
It doesn't save the score for up to 15 minutes after the score is made.
Consequently if the game crashes, or if I force stop it, the score is lost.
This may be an intended feature, but it seems more likely to be an issue.

## Possible solutions:
  - Save the score after playing the song, not 15 minutes after.
  - Save the scores when the boss key is pressed

Note: F5 updates the beatmap database, but not the scores database.

**Comment by peppy** [comment]
This is intentional. osu! should not be crashing in the first place. If you are getting crashes, please report those instead.

Also, the delay is only 1 minute after pressing the boss key or leaving the game inactive.

In the next major update (lazer), such operations will be immediate.
