### ISSUE TITLE
Cut-off elements on Song Setup Difficulty tab on high DPI

### ISSUE THREAD

**Issue by mm201** [ppy/osu-stable-issues#925]
<img src="https://puu.sh/IzXLt/8807037e22.png" alt="Screenshot" width="387" />

The labels on the Difficulty tab have unusually large height on High DPI due to [a bug in Windows Forms](https://stackoverflow.com/a/29766847/3878562). It makes the sliders very difficult to use. The correct fix is to enclose each Label in its own Panel and set Dock to Fill. This is the fix I used for the other tabs and dialogs, but for some reason, it regressed in the Difficulty tab. I'd make the fix myself but I no longer have repo access. It wouldn't take more than a few minutes.

**Comment by mm201** [comment]
Just spotted the same issue on BSS:

<img src="https://puu.sh/IzXXC/8ba9546982.png" alt="Screenshot" width="595" />
<img src="https://puu.sh/IzXYg/89012fce40.png" alt="Screenshot" width="595" />

**Comment by smoogipoo** [comment]
Just making sure - have these been fixed by the recent DPI fixes?

**Comment by peppy** [comment]
Yep, can confirm both are fixed.
