### ISSUE TITLE
Global offset changes editor offset

### ISSUE THREAD

**Issue by Theedoo** [ppy/osu-stable-issues#928]
Global offset changing editor offset sounds as if it were a good idea, but considering the fact that there are some decently well known mappers that use an "absurd" offset, such as Frenz396, whom uses -35ms offset. Changing offset each time you want to map, or even look at something in the editor, is a considerable and constant hassle.

**Comment by peppy** [comment]
This is incorrect usage of the offset, which is intended to sync audio samples to music. Also out of scope for stable.

Recommend if it's a pain to change this setting, that you just keep two copies of osu! installed with different configurations. Lazer will offer preset configurations you can setup for such purposes.
