### ISSUE TITLE
Notifications have noticeably smaller text than usual

### ISSUE THREAD

**Issue by Flamiii** [ppy/osu-stable-issues#929]
This isn't really that big of a deal but I imagined that this would probably be pretty easy to fix so I thought that I should make a post about it.

What it currently looks like:
![image](https://user-images.githubusercontent.com/74088315/148764101-24561fb6-bc6a-4e6c-b974-ae4a3fef1dcd.png)

What it should look like:
![image](https://user-images.githubusercontent.com/74088315/148764784-d8fc399a-de8d-437f-8ff8-9eba742d1493.png)

**Comment by mm201** [comment]
To fix #711 I had to choose a new default font size. I went with 10px to match existing behaviour at 1024x768, but most players are on 1920x1080 and see bigger fonts. I've enlarged it to 13px which should match what you see here.

**Comment by peppy** [comment]
I've rolled back the change for now as no matter what we set it to, people are going to complain (due to not understanding/expecting their windows DPI choice to affect osu!).

**Comment by mm201** [comment]
Is it possible to keep the sanity checks in place so the font size doesn't shrink to zero at high resolutions?

**Comment by peppy** [comment]
ah yeah, i'll look to add that back
