### ISSUE TITLE
Replay +NC using cutting edge fastforward controls removes NC upon stopping the fastforward

### ISSUE THREAD

**Issue by excitedsoup** [ppy/osu-stable-issues#932]
Unsure if I'm even supposed to post here, but couldn't find much on bug reports for CE. To replicate:

View a replay (using auto or a normal replay) that's played with NC. Press 9 (or whichever key that fast-forwards on cutting edge), then press 0 (or whichever returns to normal speed on the replay). Replay will be playing with normal (non-NC) audio and the map at normal (non-DT) speed. Can be fixed by hitting the normal fastforward controls (the one limited to 1x, DT speed and half time speed).

**Comment by peppy** [comment]
Known issue, but probably won't be fixed as we don't plan on rolling out this feature to stable.

**Comment by smoogipoo** [comment]
It's also quite hacked in, in general. Not worth fixing.
