### ISSUE TITLE
Possible regression from control point time rounding

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-stable-issues#933]
https://osu.ppy.sh/beatmapsets/754498#osu/1588443

The very first slider in the top difficulty [Blink] at 00:00:576 - is supposed to have the 0.13x inherited point applied to it, but it doesn't. This leads to the slider behaving not as the mapper intended - you can see how the slider originally played [in this video. ](https://www.youtube.com/watch?v=7tNwljTEFbw)

This is caused by the uninherited point's time not being on a whole millisecond number, see here: 
![image](https://user-images.githubusercontent.com/83023433/150700387-f907d8a6-c81f-4aac-87a4-3fc73d5b0b6a.png)

This was first spotted, as far as I can see, on 28th October 2021. Based on the changelogs, I believe that this most likely regressed in Stable 20210920, if not then Stable 20211014 - but that's just speculation on my behalf.

**Comment by peppy** [comment]
I think we should probably fix the beatmap in this case. Likely a single case?

@smoogipoo thoughts?

**Comment by Ephemeralis** [comment]
The beatmap mentioned here has been fixed via manual submission after ensuring said fixes wouldn't bork replays up. Luckily in this case, the actual gameplay impact seems to be fairly minimal.

**Comment by peppy** [comment]
Will close this for now. If any other beatmaps are found with these weird edge cases please bring them to light and we'll reconsider.
