### ISSUE TITLE
Display of osu!direct

### ISSUE THREAD

**Issue by kz9p2nr52z** [ppy/osu-stable-issues#936]
Display - Loved
Mode - osu!mania

If you change the above with osu!direct, the number found and the actual number displayed will be different.
The number of results (534) and the number of displays (8) do not match.

Version:b20220101.1

https://youtu.be/s9jZh1RT7XE
https://imgur.com/a/BGQ7Wle

**Comment by peppy** [comment]
Results are best-effort. Probably related to some beatmaps already being downloaded. If you turn off the "already owned" filter it should be more correct.

**Comment by kz9p2nr52z** [comment]
Thank you.
As you may know, pressing and holding the radio button on the downloaded map several times will change the number of results and the map.

https://youtu.be/sZuMmyIKBAQ
