### ISSUE TITLE
Negative SB load?

### ISSUE THREAD

**Issue by timelessnesses** [ppy/osu-stable-issues#943]
![image](https://user-images.githubusercontent.com/59832159/154611654-4a008bf0-1c65-48d4-bceb-da287fba994b.png)
is this a storyboard problem or it is osu client problem  
https://osu.ppy.sh/beatmapsets/1573281#osu/3423325

**Comment by peppy** [comment]
You probably caused an integer overflow because the load is so high. I'd say it's likely a *very bad sign*. Especially given your `.osb` is 22mb.

**Comment by timelessnesses** [comment]
> You probably caused an integer overflow because the load is so high. I'd say it's likely a _very bad sign_. Especially given your `.osb` is 22mb.

it run on my crappy 10 years laptop fine though

**Comment by timelessnesses** [comment]
with lowest frame is 45 fps

**Comment by timelessnesses** [comment]
also has been reduced sb to 5 megabytes and still not fixed

**Comment by peppy** [comment]
I've tested this locally and can reproduce. That said, the SB load is a "best effort" calculation and you're doing something which is definitely overflowing it. If your storyboard is running well, then it's probably okay.
