### ISSUE TITLE
submitting beatmaps using the BSS with diacritic marks in difficulty names will cause the beatmap to corrupt on import when downloaded using the website

### ISSUE THREAD

**Issue by juup1ter** [ppy/osu-stable-issues#944]
i don't know if this has always been a thing, but on [this map](https://osu.ppy.sh/beatmapsets/1703374#osu/3480314) i had tried to use the difficulty name "Für immer" and it would submit OK, but wouldn't allow me to re-download the map from the website (would give me a corrupt beatmap message), changing the difficulty name to "Fur immer" resolves this. if one difficulty has this problem, then the entire beatmap has this problem.

i did not see any issue on this, so i assume this is a new bug. the beatmap i linked is my own, and i have included the same map in 2 difficulties, with both examples of the difficulty names i had given.

if you already have the beatmap or with a .osz shared using "Export package" then it will import correctly. this is only an issue with downloading the beatmap from the website, and trying to import THAT file.

**Comment by juup1ter** [comment]
sorry about the title changes, i wanted it to be as verbose as possible when describing the issue

**Comment by peppy** [comment]
Can you take a screenshot of what you have the beatmap metadata set to? Specifically the "romanised title" is of interest here, since it should contain the title without diacritics.

**Comment by peppy** [comment]
I've uploaded a test and everything worked as expected for me. Can you test whether the beatmap I've uploaded imports correctly for you? https://osu.ppy.sh/beatmapsets/1704063#osu/3481914

Also, to action on this any further I will need log files from your osu! client after you reproduce the corrupt error you reported happening.

**Comment by juup1ter** [comment]
> Can you take a screenshot of what you have the beatmap metadata set to? Specifically the "romanised title" is of interest here, since it should contain the title without diacritics.

![osu!_gc1CjEg9ci](https://user-images.githubusercontent.com/88718409/154885662-d4f57919-b49f-49a9-94a0-c723d4ba0691.png)

> I've uploaded a test and everything worked as expected for me. Can you test whether the beatmap I've uploaded imports correctly for you? https://osu.ppy.sh/beatmapsets/1704063#osu/3481914

this imports correctly, the problem for me is when it is used in difficulty names rather than titles or artist names.

> Also, to action on this any further I will need log files from your osu! client after you reproduce the corrupt error you reported happening.

where specifically would i collect this? everything in the /Logs/ folder seems of no use/is irrelevant to this issue

**Comment by peppy** [comment]
oh, you're doing it in the *difficulty* name. i don't believe this is supported.

**Comment by juup1ter** [comment]
hmm, then can we just trim those characters from difficulty names or deny submission? i didn't even know that it wasn't an intended feature but rather a bug -- maybe something for lazer :d

**Comment by peppy** [comment]
To support it, we'd need to add unicode/romanised versions of the difficulty name. I think we'll get to this at some point, but there would need to be enough support for it as it is a non-trivial change (requires client support and also infrastructure changes).

Your best bet is to avoid using diacritics in the difficulty name for the time being.

**Comment by juup1ter** [comment]
ok! thank you for the clarification, closing this issue.
