### ISSUE TITLE
Vector Scale makes an image appear larger than set

### ISSUE THREAD

**Issue by Matiyasu** [ppy/osu-stable-issues#947]
I am currently making a new beatmap when I noticed that the storyboard shows an image larger than the size it should be in. 

I tried redoing the storyboard multiple times, I got the same result every time.

Here's a video of what I'm talking about: https://drive.google.com/file/d/1BDcb2LD5UD1JHTGJW61NktVA1L2T3slN/view?usp=sharing

Basically, if I open the editor or play the beatmap, the image in the storyboard shows really big. And if I'm in the editor (design), and I click on the image name, it goes back to normal. Then I close the editor and I open it again or play the beatmap, the image shows big again.

I tried as much stuff as I could to fix it, or to see if this will happen on other devices or if it was just my computer

1. I tried deleting the beatmap, and downloading it from the website: That didn't do anything
2. I tried restarting osu! on the device where I'm having the problem: That didn't do anything too
3. I tried running the beatmap on osu!lazer (TestFlight build), and it's completely normal
4. I tried running the beatmap on a different computer: The storyboard was just like it should be in the gameplay, but I got the same result in the editor.

edit: I fixed it. The problem was that I used the Vector Scale for the image

**Comment by peppy** [comment]
closing as fixed
