### ISSUE TITLE
Disable hitcircleoverlay animations

### ISSUE THREAD

**Issue by aMalteser** [ppy/osu-stable-issues#950]
There are currently some skins that abuse the fact that the hitcircleoverlay is animatable. I will not link the skins that do this unless required but this is how they work:
- First animation of the circle is either invisible or low opacity (hitcircleoverlay-0.png)
- The subsequent animation frames are normal opacity (hitcircleoverlay-{1,2,3}.png)
These will often reading of low ar much easier (ar<=6)

**Comment by peppy** [comment]
You may want to open a forum thread to get further discussion going on. It would need full community consensus to make a breaking change like this.

**Comment by aMalteser** [comment]
I guess it is implemented now

**Comment by peppy** [comment]
Yes, this change has been made as there was unanimous agreement from the team. It was only ever used for taiko and still remains usable there.
