### ISSUE TITLE
Lag when doing key presses

### ISSUE THREAD

**Issue by minisbett** [ppy/osu-stable-issues#951]
For the past 2-3 weeks I've been experiencing a pretty weird bug.

Whenever I have a lot of circles, a long slider or a spinner on screen osu starts to lag until the circles/slider or spinner is gone.
I did some testing and tracked down the issue to having a relation to my keyboard input.

Whenever I press a lot of keys osu starts to lag. Same when holding a key (probably because of the way Windows handles holding keys, it continuously sends the character you're holding, if I hold a key it starts lagging after like a second, the same delay when holding a key to spam the character).

The key I am pressing does not matter. Same thing for all keys on the keyboard, regardless of what my keybinds are.

I have a 5600X, 16GB RAM, GTX 1660S with newest GPU drivers. Not using Raw Input but it has the same effect so I assume it's not a Windows but rather an osu problem. Running Windows 10 20H2, using OTD newest version.

In the first days restarting my computer helped but now the bug won't fix itself, no matter how often I restart my PC.

**Comment by minisbett** [comment]
https://user-images.githubusercontent.com/39670899/156921282-3d6fb3a1-4571-4502-92e7-78b8d786df31.mp4

Webcam is laggy but you should still notice the difference. Using relax, first one without clicking, second one with clicking.

**Comment by peppy** [comment]
Let's start with getting things out of the way: it's not an osu! problem. You can confirm this by hitting ctrl+f11 until a graph appears and confirming that the graph has white lines when the issue appears, meaning some other app is causing it.

Now that we've done that, can you first restart your PC and check for any changes you made recently? Drivers, hardware, new software etc.

Then make sure you have all overlays and external apps closed. This includes things like keyboard "driver" apps which may be causing the issue.

For more help please see https://osu.ppy.sh/help/wiki/Performance_Troubleshooting.

**Comment by minisbett** [comment]
Oh I found the issue! I am using StarDock's Multiplicity for remotely using my mouse and keyboard on other devices. (https://www.stardock.com/products/multiplicity/). Thanks for the help!
