### ISSUE TITLE
osu!mania editor - notes (sometimes invisible) when tabbing in and out

### ISSUE THREAD

**Issue by force-captain** [ppy/osu-stable-issues#954]
https://user-images.githubusercontent.com/72346798/156938888-411e5570-2487-4d01-b79d-ff043178e366.mp4

Here is an example I encounter.
This happens on both 1920x1080 windowed (borderless), and normal windowed.

**Comment by peppy** [comment]
You’re probably triggering this brhaviour via pressing tab. Try pressing tab again.

**Comment by force-captain** [comment]
Huh, my bad. Didn't know that was a feature. Sorry for the unnecessary issue.

**Comment by peppy** [comment]
No worries, I wouldn't call it "unnecessary". I've made a fix for this in the next release which ensures this mode isn't toggled when alt-tabbing.
