### ISSUE TITLE
[mania] Enabling 4k mod for convert maps results in 0*

### ISSUE THREAD

**Issue by PainTensei** [ppy/osu-stable-issues#96]
Found a forum post about it but I think no one noticed:
https://osu.ppy.sh/community/forums/topics/868042

**Comment by smoogipoo** [comment]
Is it fixed after re-importing the beatmap? I made a fix for this recently.

**Comment by PainTensei** [comment]
> Is it fixed after re-importing the beatmap? I made a fix for this recently.

I just tested a map where this occurred and after re-importing the map, the star rate worked. Does this mean i have to delete all my maps and re-import them tho? Because that is going to take so much effort :( i noticed that this 0* bug happens to like 90% of all my maps

**Comment by smoogipoo** [comment]
We didn't do this initially recompute all beatmaps for performance reasons, what say you @peppy ?

**Comment by peppy** [comment]
Let's switch this over and see how it plays out.

**Comment by peppy** [comment]
Version is bumped, will hopefully resolve next CE release.
