### ISSUE TITLE
The song doesn't start at the same time as the map itself

### ISSUE THREAD

**Issue by SrIzan10** [ppy/osu-stable-issues#962]
Hey peppy! I don't really know how to describe this, but the song starts delayed. I tried restarting osu! and restarting my whole computer. Nothing!

https://user-images.githubusercontent.com/66965250/159734587-40d07b56-cfa5-43f4-a380-eebc549c54e2.mp4

**Comment by peppy** [comment]
Check your "universal offset" setting. You probably changed it.
