### ISSUE TITLE
Sudden death should auto-reset map same as Perfect

### ISSUE THREAD

**Issue by ziomek64** [ppy/osu-stable-issues#964]
What I mean by title is that Sudden death go to game over screen on fail (try again, menu)  instead of instantly restarting the map as Perfect mod.  It's probably not a bug but seems frustrating, question comes up: why? Let me know what you think. Should be quick fix if it is decided to automatically restart the map. A bit more work is to be done if we add option to settings

**Comment by peppy** [comment]
This is not changing in stable sorry.

You are welcome to test and post a proposal for lazer if it doesn’t already match your expectations (https://github.com/ppy/osu#running-osu)

**Comment by ziomek64** [comment]
@peppy Seems to be the same on lazer, I will post issue there.
