### ISSUE TITLE
Taiko big hits are less lenient at higher FPS

### ISSUE THREAD

**Issue by Shadowtail117** [ppy/osu-stable-issues#965]
For the longest time, I was unable to hit big hits nearly ever and wondered if I was doing them wrong. I looked online and noticed some people reported playing at 60fps made the timing window more lenient and after some experimentation, this seems to be the case.

I tested this specifically with this beatmap: https://osu.ppy.sh/beatmapsets/150112#taiko/370551. I normally play on Optimal at 472fps, and in this replay I only successfully hit one big note in the entire song. I don't think it's an issue with skill, I'm not the best player but I am decently accurate, here is a replay playing at Optimal to show: https://osu.ppy.sh/scores/taiko/170853300

I then played the same beatmap at Vsync (60fps) and found the timing leniency to be much more forgiving, to the point that I could hear my keys coming down at different times yet it gave me the big hit.

If I had to guess, the leniency for big hits probably relates to hitting the keys on the same frame which obviously gets harder when there is only a couple of ms between frames. Vsync would more than octuple that window which explains the discrepancy.

**Comment by peppy** [comment]
This is already fixed in lazer. Are you sure you are testing on lazer?

**Comment by peppy** [comment]
Oh this is a stable report.

This won't be fixed on stable, but is fixed on lazer, so in the future you will be able to play at any frame rate.
