### ISSUE TITLE
skin hitsounds not working

### ISSUE THREAD

**Issue by crumpledmint** [ppy/osu-stable-issues#966]
Today skin hitsoounds are not working properly. All .ogg and .wav sounds from skins are replaced with ones from standard skin
Yesterday all worked fine and I tried restarting my pc but it didn't help
Stable 20220323
[runtime.log](https://github.com/ppy/osu-stable-issues/files/8404376/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/8404377/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/8404378/update_success.log)

**Comment by crumpledmint** [comment]
By "replaced" i mean not in the directory but in the game

**Comment by peppy** [comment]
You have probably disabled beatmap hitsounds. Please try toggling it.

**Comment by crumpledmint** [comment]
> You have probably disabled beatmap hitsounds. Please try toggling it.

It was "Use skin's sound samples" turned off
Don't know how I did it, I wasn't aware that there is this option
Sorry for interrupting
