### ISSUE TITLE
Trying to join other chat channels causes an error

### ISSUE THREAD

**Issue by tgpholly** [ppy/osu-stable-issues#967]
This is probably very edge case since I've only been able to reproduce this under WINE.

Steps to reproduce:
1. Open Game
2. Open Chat
3. Click the + Button

The result of this is that you can do nothing in the game and have to force quit.

Not a huge deal breaker since lazer is so good (so I can use that instead) and I don't really use chat all that much but this has been going on for almost 2 years now so I thought I might as well make an issue.

Distro: Arch Linux
Kernel: 5.17.1-zen1-1-zen
Wine Version: 7.5 (Still happens on wine 4.5)

_Not expecting a fix since I'm on linux but thanks for the years of enjoyment so far :)_

https://user-images.githubusercontent.com/37120476/161426400-8d0d81eb-dd5e-4675-9d40-908ecc205c17.mp4
[performance.log](https://github.com/ppy/osu-stable-issues/files/8404408/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/8404409/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/8404410/session.log)

**Comment by peppy** [comment]
As you suspect, this looks to be a wine issue and not something we can help with.

If you haven't yet, please consider using https://github.com/ppy/osu#running-osu, which supports linux natively.

**Comment by tgpholly** [comment]
don't worry I've been following and using lazer for years and am aware of how great it is. :)

keep up the great work

**Comment by tgpholly** [comment]
After looking into this more this was due to .NET 4.0. Installing .NET 4.5.2, which was a pain in the ass to do, fixed the issue.
