### ISSUE TITLE
Translation not applied under certain conditions

### ISSUE THREAD

**Issue by FujiwaraSatomi** [ppy/osu-stable-issues#968]
First, quit (not force quit) osu.
Next, start osu and change to any language. then, extended chat will then show in the language in which user exited.
I have not tried it in all languages, but I was able to reproduce it at least in English, Japanese, and Chinese.

"人現在オンライン" section is in Japanese, and the rest is in English.
![](https://u.cubeupload.com/Yuzupon1133/20220407234354.jpg)

The same applies to the back button.
![](https://u.cubeupload.com/Yuzupon1133/20220408000313.jpg)

Severity is small. There is no direct harm if the change is not made, but some users may be confused.

**Comment by peppy** [comment]
Can you confirm it looks correct after restarting the game? if so, this is just how osu! works. This is resolved in the next major release (aka lazer https://github.com/ppy/osu#running-osu)

**Comment by FujiwaraSatomi** [comment]
Yes, language will be displayed correctly after restarting.
I am looking forward to the next major release.
