### ISSUE TITLE
osu!direct missing sets

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-stable-issues#971]
Searching for `P*Light` only yields ![](https://osu.ppy.sh/ss/17730613/4f37) despite the website showing many more sets with the exact same artist name. https://osu.ppy.sh/beatmapsets?q=P*Light

**Comment by peppy** [comment]
have you tried clicking "show already downloaded maps"?

**Comment by Rekunan** [comment]
still shows only the one set ![](https://osu.ppy.sh/ss/17731836/b18f)

**Comment by peppy** [comment]
Thanks for checking. I can reproduce. Will try and look into this at some point.

**Comment by peppy** [comment]
This should now work. There's a few more similar cases which I'll look into as a follow-up, but p*light is fixed at least.

**Comment by Rekunan** [comment]
Found that this also occurs with `:Poin7less`
![screenshot137](https://user-images.githubusercontent.com/24501632/179238176-a3e0bffa-6ba6-49dd-8988-d291e502bd21.png)
compared to https://osu.ppy.sh/beatmapsets?q=%3APoin7less&s=any

**Comment by peppy** [comment]
Not sure about this one. Probably best left until lazer.
