### ISSUE TITLE
Client beatmap offset and frames is broken 

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-stable-issues#973]
I restarted the client, executed osu!repair.exe and nothing

video:
https://clips.twitch.tv/GleamingSoftArmadilloWutFace-z6ujpirUt_BCnQec

[runtime.log](https://github.com/ppy/osu-stable-issues/files/8526514/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/8526515/session.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/8526516/performance.log)

**Comment by peppy** [comment]
Can you give more details on how often this happens? Does it happen without your streaming applications running? When did it start?

If it started only recently, please observe any changes you made to your PC (drivers, windows updates etc.) and try undoing them.

**Comment by Sebola3461** [comment]
i never changed anything, it happens for no reason

**Comment by peppy** [comment]
There's not much we can help you with then, sorry. We've never seen this reported by another user so it must be something specific to your setup.

**Comment by Sebola3461** [comment]
Np, i will close this, reopen if i find something
