### ISSUE TITLE
Gamma problem with 1176*664

### ISSUE THREAD

**Issue by Frfri1** [ppy/osu-stable-issues#974]
I noticed a small bug with the resolution 1176*664 when fullscreen is enabled and render at native resolution is disabled.

Switching to this specific resolution increases the gamma, and reswitching to another resolution leaves that increased gamma. 

Going into windowed mode or enabling render at native resolution fixes the gamma problem.

**Comment by peppy** [comment]
This is going to be a setting on your GPU driver. osu! doesn't touch gamma.
