### ISSUE TITLE
replay play speed issue

### ISSUE THREAD

**Issue by Bro3nies** [ppy/osu-stable-issues#976]
I've recently found out that I can disable mods (DT, NC, etc) while playing replays.
and while I was playing with those functions, I noticed when I click the space where
the dt or nc mod icon appears right after I start the replay ( before the mod icon appears on the screen)
it adds about 75% speed on the replay (plays the replay faster than it should be)
this bug(?) only worked on DT and NC

i only tested on standard 20220424

**Comment by peppy** [comment]
Thanks for the report. As this only affects replays I'm not sure we'll get around to fixing it. We're currently focusing efforts on "lazer" (the next major update) and this behaviour doesn't exist there yet.
