### ISSUE TITLE
Disconnecting the mouse while gaming causes the default Windows cursor to appear next to the in-game cursor

### ISSUE THREAD

**Issue by MasterAnimit** [ppy/osu-stable-issues#977]
Reproduction steps:
1. Open the application with plugged mouse
2. Un-plug mouse on any screen (Song Select, In-Game etc.)
3. Re-plug the mouse
4. Second cursor should appear, Windows default type.

Only in-game cursor is usable.
Restarting an application resets whole bug.

Corfirmed for newest Cutting Edge (b20220413cuttingedge) and Stable (20220424) versions. OS - Windows 10 Home (10.0.19043)

Videos:

https://user-images.githubusercontent.com/77850598/167574596-ae10ca7e-f103-4d13-9157-c3c0389b54ca.mp4

https://user-images.githubusercontent.com/77850598/167574440-a0f66545-0603-49cd-a99a-b42447aedd09.mp4

https://user-images.githubusercontent.com/77850598/167574396-5a3a125a-c915-4f9b-aa91-e3451d0f781a.mp4

**Comment by smoogipoo** [comment]
This isn't going to be easy for us to fix, so I suggest not doing this.

**Comment by MasterAnimit** [comment]
Sad to hear, but understandable. In this case I also won't report another bug with def. Windows cursor.
Have a nice day smoogi!

**Comment by peppy** [comment]
If you can reproduce the issues on lazer, then we are interested in hearing about them. But please make sure to search before reporting over that way, as we are already tracking several issues with mouse cursor handling.
