### ISSUE TITLE
streaming in discord

### ISSUE THREAD

**Issue by StevenSihhv** [ppy/osu-stable-issues#978]
i  cant stream osu in discord.

![image](https://user-images.githubusercontent.com/105283255/167607779-4d2daeb2-e9f1-4d36-b7fc-db20e066ab04.png)

**Comment by smoogipoo** [comment]
Is your osu! running fullscreen? I think Discord only detects apps which aren't minimised. Use the button in the bottom left where the game's shown to stream it:

![image](https://user-images.githubusercontent.com/1329837/167608327-bff66b79-44f8-4f1b-8ed0-f4e1061aba1f.png)
