### ISSUE TITLE
Sliderticks do not appear during gameplay in certain circumstances.

### ISSUE THREAD

**Issue by Nyanaro** [ppy/osu-stable-issues#979]
Currently, sliderticks do not appear in gameplay when overlapping with the sliderstart- or endcircle, even though said sliderticks appear in the editor.

This even happens when the slider loops back over the start circle.
![Editor](https://user-images.githubusercontent.com/22597387/168125147-dc751299-9558-4dee-91ef-ff43418f2d72.jpg)
![Gameplay](https://user-images.githubusercontent.com/22597387/168124600-fc9c5f4f-910c-482a-998b-1ebee156812d.jpg)

This makes certain otherwise perfectly rankable sliders, in many cases, a nightmare to read, and affects many maps with sliderticks very close to the end circle in particular, as players unable to see the slidertick might break combo in a completely unfair way.

I propose that all sliderticks are forced visible, and to be above the sliderstartcircle and sliderendcircle, as they are in the editor.
![bonus image with startcircle](https://user-images.githubusercontent.com/22597387/168125134-540b95b9-9182-4e14-9c04-b782d4202131.jpg)

**Comment by peppy** [comment]
This is intended.

If it was ever changed it would be done in lazer.

**Comment by Nyanaro** [comment]
> This is intended.
> 
> If it was ever changed it would be done in lazer.

Why would this be intended? It makes the game more difficult to play, and doesn't seem to serve any aesthetic purpose. The inclusion of the ticks in the editor only makes mappers less aware of this issue and making them less able to account for it when mapping.

**Comment by mm201** [comment]
IIRC this was to cover for a worse bug that caused ticks to be incorrectly displayed above the end circles.

**Comment by isakvik** [comment]
Seems to me like you'd be better off displaying sliderticks above the end circles anyway since the ticks require you to be tracking the slider to hit it, which isn't true for the end circles. Hiding sliderticks is admittedly a fringe gameplay experience thing to care about since it doesn't happen often, but I've never been happy to discover I dropped my combo because of an invisible slidertick in maps that try to push slider aim to the edge.
