### ISSUE TITLE
TeamVS multi result screen's judgements for non-std modes are displayed wrongly

### ISSUE THREAD

**Issue by jakads** [ppy/osu-stable-issues#98]
taiko
![screenshot2574](https://user-images.githubusercontent.com/16955881/65528850-17aabb00-df30-11e9-9f57-5d44cefeda0c.png)

catch
![screenshot2576](https://user-images.githubusercontent.com/16955881/65528868-1d080580-df30-11e9-88a9-6c3e634c454b.png)

mania
![screenshot2577](https://user-images.githubusercontent.com/16955881/65528877-2002f600-df30-11e9-8194-28089553999a.png)

why do they all display std judgements
bruh

**Comment by Fatal3ty** [comment]
@jakads Probably is the Ranking Panel, that Combo and Accuracy is on the ranking-panel.png. Not a seperate file. I think is not fixable, need a seperate file ranking-maxcombo.png and ranking-accuracy.png

Like this:
![ranking-panel@2x](https://user-images.githubusercontent.com/53025167/65538209-1fa23500-df07-11e9-8d9f-95e300a1f857.png)

**Comment by jakads** [comment]
![image](https://user-images.githubusercontent.com/16955881/65538894-48482000-df43-11e9-8133-171d02cfd3aa.png)
![image](https://user-images.githubusercontent.com/16955881/65538897-4aaa7a00-df43-11e9-880a-7d8b98049132.png)
no i mean the judgements

**Comment by Fatal3ty** [comment]
Ah i see, that is a bug. Not switch to taiko, mania or ctb hits. Thx :)

**Comment by smoogipoo** [comment]
This might be quite hard to resolve/probably not worth the time investment.

**Comment by peppy** [comment]
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).
