### ISSUE TITLE
Some beatmap hitsounds fallback to default samples instead of skin samples

### ISSUE THREAD

**Issue by myutin** [ppy/osu-stable-issues#981]
Expected behavior: all hitsounds play my skin's samples (i.e., everything silent except hitnormals)

Actual behavior: some sliderticks play default slidertick sample (see video attached)
https://user-images.githubusercontent.com/60725262/168411729-9477b620-66f6-4fd4-a45f-ac15f48c9f73.mp4

Steps to replicate:
- Use a skin that changes normal-slidertick
- Find a beatmap with the following criteria:
  - the beatmap has custom hitsounds
  - the custom hitsounds have a second sampleset
  - the second sampleset includes normal-slidertick2
- Play the beatmap (with settings "use skin sound samples" and "ignore beatmap hitsounds" enabled)

In the video above, the map is https://osu.ppy.sh/beatmapsets/41686#osu/131564. Its song folder looks like this:
![song-folder](https://user-images.githubusercontent.com/60725262/168411917-bceb1fd5-f347-40a8-a29f-69ffb009b5bd.png)
And its timing points' audio looks like this:
![timing-points](https://user-images.githubusercontent.com/60725262/168411935-13c97536-5e1e-4c5d-b382-078088dd7e44.png)

Additional Information:
version: b20220413cuttingedge
here's the same map played with beatmap hitsounds enabled:
https://user-images.githubusercontent.com/60725262/168411973-049ca60a-a900-4810-a3a0-b1cfdbc0c7ac.mp4

**Comment by peppy** [comment]
Thanks for the report, but this requires considerable investigation and likely only affects you (even if it affects others, the chance they will even notice this is very low).

If possible, could you check whether this happens on lazer as well? If it happens there, we will be willing to look into fixing it (https://github.com/ppy/osu#running-osu).

**Comment by myutin** [comment]
I could not reproduce the issue on lazer.
I think some others have noticed this issue (e.g. https://osu.ppy.sh/comments/1137519).
I've found a workaround for myself (by creating louder hitsound samples).
Thank you for your time.
