### ISSUE TITLE
ingame chat bug when playing / paused in a map

### ISSUE THREAD

**Issue by xyndere** [ppy/osu-stable-issues#982]
Copy-Paste from the forum because "Blushing" send me here:

**Problem details:**
If you pause during a map and want to send a message that contains more "ingame keybind" characters than non-keybind characters, the message will not be sent.

**This only happens when you are in a map, in song select it works just fine.**

**To clarify what I mean:**
For example my osu!taiko ingame inputs are "**AS**" and "**KL**".
If I for example try to send a message with just "**LAS**ER", it won't work.
This is because this message has a ratio of 3/2.
It contains 3 characters that are also my taiko keybinds (**LAS**). And only 2 non-keybind characters (ER).
If I type "**LAS**ERR", it will send because the ratio is 3/3.

**There has to be equal or more non-keybind characters to keybind characters in a message for it to be able to send properly.**

Spacebars and special characters also count as non-keybind characters.

So back to the example: "**LAS**ER" wont work but "**LAS**_ER" will work. Because the "_ER" counts as 3 characters, nullifying the amount of "keybind" characters send.
Another example with my "**ASKL**" keybinds: "hhh**aaaa**" won't work (ratio 4 keybind characters to 3 non-keybind), "hhhh**aaa**" will work (ratio 4 non-keybind to 3 keybind characters).

I don't know why this happens, I just know how it happens.

osu! version: Stable 20220424 (latest)

**Comment by peppy** [comment]
This is an intentional mechanic, to avoid users spamming game keybindings at users or public channels. Can you give an example of a case where this would be unwanted?

**Comment by xyndere** [comment]
Ah, this makes sense.
But it happened multiple times now where I couldnt send messages of normal words or phrases, which can be quite annoying.
"Klasse arzt lol lass besser" (german for: great doctor lol better leave it) was the message that made me experiment why it deletes messages.
I mean, it really depends on the keybinds and one could just change the keybinds to keys that are not so frequently used in their language. But its still kind of annoying
Cant think of a better solution

**Comment by peppy** [comment]
I've adjusted the algorithm used for this to be less sensitive. Will fix the case you've mentioned.
