### ISSUE TITLE
recording/streaming osu on obs

### ISSUE THREAD

**Issue by StevenSihhv** [ppy/osu-stable-issues#985]
i didn't have a problem with it until i redownladed osu again. whenever i want to stream/record on osu with obs it shows a black screen. how can i fix this? 

![image](https://user-images.githubusercontent.com/105283255/168792803-e75836bc-7794-46e1-a5a5-072cf70ccb2a.png)

**Comment by smoogipoo** [comment]
Ask on the forums instead.
