### ISSUE TITLE
Your version of osu! is too old to submit scores

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#989]
Started happening today. I ran the updater but it still gives me the error. I tried b20220413cuttingedge, b20220421beta, and b20220424. Happens on any map I try.

[runtime.log](https://github.com/ppy/osu-stable-issues/files/8750521/runtime.log)

**Comment by peppy** [comment]
Please try to run the installer from the website without uninstalling.

**Comment by abraker95** [comment]
Unfortunately that did not help. Not sure if the install worked properly either.

When the installer countdown finished, the installer exited and osu! started up. The client displayed that there is a new version available, but before updating I checked if submission worked and it did not. So then I updated and submission still did not work.

[update_success.log](https://github.com/ppy/osu-stable-issues/files/8758577/update_success.log)

**Comment by quayosu1992** [comment]
i got this today,i tried run updater redownload and change stream release but still not work, it happen on all map help me

**Comment by abraker95** [comment]
This has since been fixed. The issue was that I was running Windows in test mode. Also make sure your desktop background is not white or has a white patch on the bottom right, or you will not see the text that is indicative that windows is in test mode.
