### ISSUE TITLE
creator=, artist= and etc could use an improvement

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu-stable-issues#99]
Let's say for example I want to look for maps by a mapper named **Mir**. I would have to type creator=Mir
However it also returns maps by Mirash. Because the string Mirash has Mir in it. 

Would be nice to have something like creator="Mir" to specify I want the field be the search query, instead of just checking if it contains the search query.

**Comment by smoogipoo** [comment]
This may be out of scope since the osu-stable regex can't parse `"`. Will consider backporting the lazer regex.

**Comment by peppy** [comment]
Let's not. Scope creep++
