### ISSUE TITLE
Raw Input bug when tablet is not plugged in at computer start

### ISSUE THREAD

**Issue by ashyoa** [ppy/osu-stable-issues#990]
I have been experiencing an issue on stable for a while where if my tablet is not plugged in at computer start, the cursor will be locked to the top left of the game window, even while using hawku drivers or OpenTabletDriver.

I've seen similar mentions of this bug on Reddit or osu! forums, and they almost always relate to Windows Ink being enabled, but I am sure this is disabled and the issue still persists across multiple tablets and devices. This has occurred on 2 different Windows 10 devices while using the Wacom Intuos S 2018 and the Wacom Intuos Touch and Pen Small.

This issue does not occur if the tablet is plugged in before the computer has started, and raw input works just fine. Many people say not to use raw input as it causes input lag but I find that having raw input off causes unplayable tablet lag and cursor skipping.

![screenshot](https://user-images.githubusercontent.com/105692796/170672736-6a88ffbf-6f55-4984-b6a3-d0f9c665f728.png)

Edit: I believe I have found a probable cause for this. Certain wacom tablet services may not be starting when the tablet is not plugged in on start. When the tablet is plugged in on start, these services start.

**Comment by peppy** [comment]
This is definitely something outside of osu! causing the issue.

**Comment by ashyoa** [comment]
I'll close this issue in that case, I will have a look at my drivers and startup items.
