### ISSUE TITLE
Mania does not submit TD plays

### ISSUE THREAD

**Issue by ALANVF** [ppy/osu-stable-issues#991]
Mania mode does not seem to submit plays that are done with TD, which is odd because osu!lazer does submit them (however it doesn't have multitouch, which is why I play on stable). Is this a bug or actually intentional?

Logs don't have anything particularly interesting, but I'll add them anyways
[runtime.log](https://github.com/ppy/osu-stable-issues/files/8790284/runtime.log)

**Comment by peppy** [comment]
I don't understand. You are talking about "touch device" right? This is only applied to osu! mode plays.

**Comment by ALANVF** [comment]
Yes I am, basically when you play mania with a touchscreen device.

If it is only applied to osu!std plays, then why support touchscreen for mania at all?

**Comment by peppy** [comment]
I think you are confused. Please show what you're seeing. It's likely not related to touch screen at all.

**Comment by ALANVF** [comment]
Maybe I'm not wording this correctly.

When I play mania mode using a keyboard (like normal), my scores are submitted.

When I play mania mode using a touchscreen, my scores are not submitted and are only stored locally, as if I was playing offline (which I'm not).

My question is: why does the touchscreen score not submit? Is it intentional, or a bug? This is not necessarily related to the TD mod, but touchscreen playstyle instead of keyboard playstyle

**Comment by ALANVF** [comment]
Here's a video I just recorded of a touchscreen play, for further proof: https://www.youtube.com/watch?v=IurmB3g5V3Q

**Comment by smoogipoo** [comment]
I think I can see how this could happen. Does submission work if you use your keyboard to press just one key?

**Comment by ALANVF** [comment]
Yes it does, oddly enough. I wonder if tapping on the lanes does not register as a keypress (which happens in osu!std mode when you tap), so the game sees that no keys are pressed therefore thinks nothing was played? (or it was on auto mode?)

**Comment by smoogipoo** [comment]
Should be fixed on the next CE build.
