### ISSUE TITLE
Can open the IRC function of sending messages to myself?

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#993]
Can open the IRC function of sending messages to myself?
It is supported by the IRC protocol.
I intend to use this function in the live stream scene.
I can push the content of the live chat room to the osu and then I can reply to the chat.
Currently, stable can receive messages sent to self by external IRC software,
but messages sent from stable will be blocked.
Now, If I want to reply in the game, i need use a transit account to achieve this. 
If can open this function，will be convenient.

**Comment by peppy** [comment]
Unfortunately this isn't too simple to implement, and out of scope for osu(stable). I believe you can already use the v2 api to do something similar to this though, since you will be able to see your own messages there.

**Comment by wanjiaXG** [comment]
> Unfortunately this isn't too simple to implement, and out of scope for osu(stable). I believe you can already use the v2 api to do something similar to this though, since you will be able to see your own messages there.

Can't be realized by v2, the message must be able to be sent from the client, otherwise it will be meaningless.
Now only use a transit account or windows hook injection.
Thanks your reply.
