### ISSUE TITLE
Virtual desktop support may be broken

### ISSUE THREAD

**Issue by peppy** [ppy/osu-stable-issues#996]
Report forwarded by microsoft follows:

Application minimizes automatically in Virtual Desktop on enabling Task View

Environment: Desktop
OS Build: 19041, 17763
OS: Windows 10
App Version:  Latest

Repro Steps:
1. Install the Application from the vendor site.
2. Launch the Application from start menu\shortcut.
3. Try the application window is assigned to the newly created virtual desktop.
4. observe.

Actual Results:
Application minimizes automatically to taskbar on enabling Virtual Desktop.

Expected Results:
Application shouldn’t minimize automatically to taskbar on enabling Virtual Desktop.

**Comment by smoogipoo** [comment]
Should be noted that this is only applicable to exclusive fullscreen. Windowed/borderless don't minimise.

**Comment by peppy** [comment]
I have a separate issue (potentially) when stable starts minimised 20% of the time, windowed. No idea about that, thought it might be related. I've heard others report this one too

**Comment by smoogipoo** [comment]
If you're fine with going down that path then sure. Just wasn't sure about breaking user expectations. Guess I'll do that instead and we can see if people complain?

**Comment by peppy** [comment]
I'd have to give it a try and see how it behaves, and also compare to other games. Maybe commit that (or PR) separately and I'll test both.
