### ISSUE TITLE
Issue with chat auto-filter in CuttingEdge

### ISSUE THREAD

**Issue by chromb** [ppy/osu-stable-issues#998]
Chat spam detection feels very trigger happy, appears to remove anything <4 characters, including /np and other non-spam messages. 
I believe this is due to some changes in CE20220605

Below is a video of some of my testing:

https://www.youtube.com/watch?v=jmPQ7hXZ4CU

**Comment by peppy** [comment]
This should be fixed in the latest cutting edge release, thanks for reporting.
