### ISSUE TITLE
Map downloaded from site causes hard freeze when dragged from a browser if already imported

### ISSUE THREAD

**Issue by hburn7** [ppy/osu-stable-issues#999]
Apologies for the messy title. This is an issue that causes osu! to freeze when you try to drag and drop a missing file. 

Edit: Version is `b20220424` (stable)

Steps to reproduce:
- Download a beatmap from the website
- Drag and drop the map from the browser download tab into osu!. The map should import successfully.
- Drag and drop the same map again - osu! should freeze and show a message similar to the attached screenshot.
![osu!_VVhovhN3LJ](https://user-images.githubusercontent.com/38370573/174700352-7375144b-b220-4503-a5df-794f85801b64.jpg)

The only way to close osu! when this occurs is through the Task Manager, osu! becomes completely unresponsive. The dialogue box cannot be clicked.

Edit 2: To elaborate, this is the "browser download tab" I'm referring to:
![VF2Hlk3ZR2](https://user-images.githubusercontent.com/38370573/174701301-cd8a81fd-d244-4336-a260-3d8688ea1bf8.png)

**Comment by minisbett** [comment]
The reason osu! shows that error is because after the map was imported, the .osz file gets deleted. Dragging it into osu! again causes it to try importing a non-existent file. I'm pretty sure osu! is not supposed to crash tho

**Comment by peppy** [comment]
Thanks for the report, but we aren't really fixing these kinds of minor issues in stable. Rest assured it can't happen in the next major release of osu! (known as "lazer").
